Masih/kv store service
CoreumFoundation/coreum pull request #1028
Opened 2024-11-19 12:42 UTC by masihyeganeh

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2024-11-20 08:54 UTC, masihyeganeh reviewed
> Reviewed 24 of 25 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2024-11-20 13:11 UTC, masihyeganeh reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2024-11-21 07:15 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: all files reviewed, 27 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/delay/keeper/keeper.go` line 100 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXDkAAUAn1punF7UF:-OCCXDkAAUAn1punF7UG:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/delay/keeper/keeper.go#L100)):*
> ```Go
> 
> 	store := k.storeService.OpenKVStore(ctx)
> 	if val, _ := store.Has(key); val {
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/delay/keeper/keeper.go` line 132 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXFCi-PEfD2Bdnlip:-OCCXFCi-PEfD2Bdnliq:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/delay/keeper/keeper.go#L132)):*
> ```Go
> 
> 	store := k.storeService.OpenKVStore(ctx)
> 	if val, _ := store.Has(key); val {
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 54 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXaEx7U8nHZdrYAJI:-OCCXaEx7U8nHZdrYAJJ:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L54)):*
> ```Go
> func (k Keeper) GetParams(ctx sdk.Context) types.Params {
> 	store := k.storeService.OpenKVStore(ctx)
> 	bz, _ := store.Get(types.ParamsKey)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 204 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXc4s6afcsZAJn79K:-OCCXc4s6afcsZAJn79L:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L204)):*
> ```Go
> 	}
> 
> 	bz, _ := k.storeService.OpenKVStore(ctx).Get(classKey)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 499 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXdh32G_XB8GdwuFG:-OCCXdh32G_XB8GdwuFH:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L499)):*
> ```Go
> 	}
> 
> 	isBurnt, _ := k.storeService.OpenKVStore(ctx).Get(key)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 671 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXfAU012l6kRjKENi:-OCCXfAU012l6kRjKENj:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L671)):*
> ```Go
> 	}
> 
> 	val, _ := store.Get(key)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 706 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXgdmDDxG_nfGWfdR:-OCCXgdmDDxG_nfGWfdS:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L706)):*
> ```Go
> 	}
> 
> 	val, _ := k.storeService.OpenKVStore(ctx).Get(key)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 888 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXiGB3yF_zRKJXlut:-OCCXiGC8B-R1KeJMGub:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L888)):*
> ```Go
> 	}
> 
> 	val, _ := k.storeService.OpenKVStore(ctx).Get(classKey)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/nft/keeper/keeper.go` line 902 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXj_-BtB7dcjL7vEt:-OCCXj_-BtB7dcjL7vEu:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L902)):*
> ```Go
> 	}
> 
> 	val, _ := k.storeService.OpenKVStore(ctx).Get(key)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/ft/keeper/keeper.go` line 76 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCY767Chee_mX7xMb6:-OCCY767Chee_mX7xMb7:bfe3bt4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L76)):*
> ```Go
> // GetParams gets the parameters of the module.
> func (k Keeper) GetParams(ctx sdk.Context) types.Params {
> 	store := k.storeService.OpenKVStore(ctx)
> ```

In some cases you use 
```
store := ctx.KVStore(k.storeKey)
store.Set()...
```

But in some
```go
k.storeService.OpenKVStore(ctx).Set
```

Let's use one stile (2nd better IMO) for the case when we need it once in the func.
___
*[`x/asset/ft/keeper/keeper.go` line 77 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCUySk8E30aQrc4O3J:-OCCUySk8E30aQrc4O3K:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L77)):*
> ```Go
> func (k Keeper) GetParams(ctx sdk.Context) types.Params {
> 	store := k.storeService.OpenKVStore(ctx)
> 	bz, _ := store.Get(types.ParamsKey)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/ft/keeper/keeper.go` line 998 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCWEEg28eD9pnFhkZg:-OCCWEEg28eD9pnFhkZh:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L998)):*
> ```Go
> 	store := k.storeService.OpenKVStore(ctx)
> 	compositeKey := types.CreateSymbolKey(issuer, symbol)
> 	rawBytes, _ := store.Get(compositeKey)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/ft/keeper/keeper.go` line 1158 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCWKad3y7Yll7xLRAZ:-OCCWKad3y7Yll7xLRA_:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L1158)):*
> ```Go
> func (k Keeper) isGloballyFrozen(ctx sdk.Context, denom string) bool {
> 	store := k.storeService.OpenKVStore(ctx)
> 	isGloballyFrozen, _ := store.Get(types.CreateGlobalFreezeKey(denom))
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/dex/keeper/keeper_store.go` line 98 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXUXc17gN4xtP0CAu:-OCCXUXc17gN4xtP0CAv:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/dex/keeper/keeper_store.go#L98)):*
> ```Go
> 	val proto.Message,
> ) error {
> 	bz, _ := k.storeService.OpenKVStore(ctx).Get(key)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/customparams/keeper/keeper.go` line 36 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXlIs85LC0iNymv-y:-OCCXlIs85LC0iNymv-z:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/customparams/keeper/keeper.go#L36)):*
> ```Go
> func (k Keeper) GetStakingParams(ctx sdk.Context) types.StakingParams {
> 	store := k.storeService.OpenKVStore(ctx)
> 	bz, _ := store.Get(types.StakingParamsKey)
> ```

You shouldn't ignore the error! Either return it or panic. 
___
*[`x/asset/ft/keeper/keeper_dex.go` line 120 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCWQQPEtkAgw8_YT3F:-OCCWQQPEtkAgw8_YT3G:bvufq78) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper_dex.go#L120)):*
> ```Go
> // GetDEXSettings gets the DEX settings of a specified denom.
> func (k Keeper) GetDEXSettings(ctx sdk.Context, denom string) (types.DEXSettings, error) {
> 	 [...]

2024-11-21 10:17 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: all files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 76 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCY767Chee_mX7xMb6:-OCDCDNK7zxVbhcohwKU:btoq4ry) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L76)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In some cases you use 
```
store := ctx.KVStore(k.storeKey)
store.Set()...
```

But in some
```go
k.storeService.OpenKVStore(ctx).Set
```

Let's use one stile (2nd better IMO) for the case when we need it once in the func.
</blockquote></details>

It is mostly used like the first style when store is needed in more than one line or if it is wrapped in a couple of function calls and using the second one makes it less readable. But I'll try to unify them everywhere in code
___
*[`x/asset/ft/keeper/keeper.go` line 77 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCUySk8E30aQrc4O3J:-OCDCV1V9y6mm_5u3xK_:bl42gcc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L77)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

The error happens only if the key is `nil` which in our case it will never be, so it's safe to not handle it
Source: [cosmossdk.io/core/store/store.go](https://github.com/cosmos/cosmos-sdk/blob/main/core/store/store.go#L5)

And I didn't want to add a new return value to functions everywhere for the case that doesn't happen. Let's discuss it in the meeting to decide if we should handle it or not
___
*[`x/asset/ft/keeper/keeper_dex.go` line 569 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCX2Pr2CUUuHNWAUMC:-OCDDM_10ymtzoCYH6EI:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper_dex.go#L569)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about in-line error handling?
</blockquote></details>

Done.
___
*[`x/dex/keeper/keeper.go` line 734 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCZLTiEaaBFmhcgQpp:-OCDDUOL46TwX3j0eIHN:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/dex/keeper/keeper.go#L734)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Good place for in-line error handling
</blockquote></details>

Done.
___
*[`x/dex/keeper/keeper.go` line 938 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCZZ9aA0NJdqo5Wabe:-OCDDVmQ0g-yrqNOkYLW:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/dex/keeper/keeper.go#L938)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You call it differenly in different places, check it please.
</blockquote></details>

Done.
___
*[`x/dex/keeper/keeper.go` line 1227 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCZgqP0nfWDEVYAglF:-OCDDZ1eD6s-i70WU7kT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/dex/keeper/keeper.go#L1227)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Good place for in-line handling.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-21 10:20 UTC, masihyeganeh reviewed
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: all files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2024-11-22 08:32 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: 9 of 52 files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 998 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCWEEg28eD9pnFhkZg:-OCHzdz69SLzCkNLyPCn:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L998)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 1158 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCWKad3y7Yll7xLRAZ:-OCHzeu-BDhBzspSIJAe:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper.go#L1158)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_dex.go` line 120 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCWQQPEtkAgw8_YT3F:-OCHzib54tFviD-d4zUi:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/keeper_dex.go#L120)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/token_upgrade.go` line 54 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXCBCAvu6xWkd0-9B:-OCHzjzjBUy6LIy5OoPy:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/token_upgrade.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/token_upgrade.go` line 70 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXZ_P0-ESgFCKQqIZ:-OCHzkKLAwA-hefNQnID:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/ft/keeper/token_upgrade.go#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 54 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXaEx7U8nHZdrYAJI:-OCHzmlx-9bMa0lka0N2:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 204 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXc4s6afcsZAJn79K:-OCHznX7Ct2IS1AWFwhI:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L204)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 499 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXdh32G_XB8GdwuFG:-OCHzo1D3_BiKPetabwp:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L499)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 671 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXfAU012l6kRjKENi:-OCHzoTp10RLOXCGgkp2:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L671)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 706 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXgdmDDxG_nfGWfdR:-OCHzon9DYuuc82HP2B1:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L706)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 888 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXiGB3yF_zRKJXlut:-OCHzpG3B2AK7NdO1lW3:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L888)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 902 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXj_-BtB7dcjL7vEt:-OCHzpa91NhRDdzpNTxM:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/asset/nft/keeper/keeper.go#L902)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/customparams/keeper/keeper.go` line 36 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXlIs85LC0iNymv-y:-OCHzqaP3NiGHGxBi3no:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/customparams/keeper/keeper.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 100 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXDkAAUAn1punF7UF:-OCHzre11VIPKLkfjU_a:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/delay/keeper/keeper.go#L100)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 132 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXFCi-PEfD2Bdnlip:-OCHzs3T7KeVbrz8ll7K:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/delay/keeper/keeper.go#L132)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/dex/keeper/keeper.go` line 194 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCCXT-a5V0bPjXLx98M:-OCHzspg1kIG2j10wUkq:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec9e5233ff010c66ab76730f43e2651a73b05464/x/dex/keeper/keeper.go#L194)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't ignore the error! Either return it or panic.
</blockquote></details>

Done.
___
*[`x/dex/keeper/keeper_store.go` line 98 at r3](https:// [...]

2024-11-22 08:32 UTC, masihyeganeh reviewed
> Reviewed 43 of 43 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: all files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2024-11-22 08:52 UTC, miladz68 requested changes
> Reviewed 9 of 25 files at r1, 1 of 3 files at r2, 2 of 8 files at r4, 43 of 43 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: all files reviewed, 28 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 692 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCI32023Wi_sqq3Klz0:-OCI32023Wi_sqq3Klz1:bthj252) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d84fbb490d690691da9df02a429f0b21c21e2e75/x/asset/nft/keeper/keeper.go#L692)):*
> ```Go
> 	}
> 
> 	val, _ = store.Get(key)
> ```

same as Dima mentioned above.


<!-- Sent from Reviewable.io -->

2024-11-22 09:17 UTC, masihyeganeh reviewed
> Dismissed @miladz68 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: 46 of 57 files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 692 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/1028#-OCI32023Wi_sqq3Klz0:-OCI71An2RAiaAAmmy-l:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d84fbb490d690691da9df02a429f0b21c21e2e75/x/asset/nft/keeper/keeper.go#L692)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

same as Dima mentioned above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-23 07:41 UTC, miladz68 approved these changes
> Reviewed 9 of 11 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: all files reviewed, 27 unresolved discussions (waiting on @dzmitryhil and @ysv)



<!-- Sent from Reviewable.io -->

2024-11-25 05:44 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2024-11-25 15:39 UTC, merged