copied network config code from crust to cored folder #1
CoreumFoundation/coreum pull request #105
Opened 2022-07-01 08:19 UTC by miladz68

This is a recreation of previous PR which ran into problems due to github issues.
This PR is the first of a set of PRs intended to create
config for different networks. here we create a package
which holds the configurations and in the next 2 PRs. we
will use them in cored cli and crust package.

2022-07-01 09:37 UTC, wojtek-coreum requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/genesis.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5syzLbArkC1KYKUaez:-N5syzLbArkC1KYKUaf-:b6ouekg) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L32)):*
> ```Go
> 	mu           *sync.Mutex
> 	appState     map[string]json.RawMessage
> 	finalized    bool
> ```

I would say this might be removed. This is `znet`-specific field and should not be done in generic implementation
___
*[`pkg/config/genesis.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-2p67NCg0pmKgPj7:-N5t-2p67NCg0pmKgPj8:betuylw) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L75)):*
> ```Go
> 
> // EncodeAsJSON returns json encoded representation
> func (g *Genesis) EncodeAsJSON() ([]byte, error) {
> ```

Non-blocking: if error happends inside this function I would just panic instead of returning it because it really means we screwed up sth
___
*[`pkg/config/genesis.go` line 106 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5szUme6Y-imQ9DkbUj:-N5szUmf0tr9_kTtgAmA:b-b358wq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L106)):*
> ```Go
> 	g.finalized = true
> 
> 	genDocBytes, err := g.EncodeAsJSON()
> ```

call to `EncodeAsJSON` creates a deadlock because mutex is already locked. You need separate non-exported `encodeAsJSON` method not locking on mutex, called from both places
___
*[`pkg/config/genesis.go` line 111 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-S7P2TU68hnbHR6y:-N5t-S7P2TU68hnbHR6z:b-t498fn) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L111)):*
> ```Go
> 	}
> 
> 	err = os.MkdirAll(homeDir+"/config", 0o700)
> ```

Elegance: you may move it into `if` statement
___
*[`pkg/config/genesis.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t4fdp1_YMcD53J2KC:-N5t4fdp1_YMcD53J2KD:bxoxn3e) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L128)):*
> ```Go
> var genesisTemplate string
> 
> func genesis(n Network) ([]byte, error) {
> ```

in case of error this function should panic instead of returning it, because error here means that we made sth wrong during development. This function is not expected to fail on runtime
___
*[`pkg/config/genesis.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-ofx1MVCCydL9V4M:-N5t-ofx1MVCCydL9V4N:becxd4u) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L131)):*
> ```Go
> 	genesisBuf := new(bytes.Buffer)
> 
> 	err := template.Must(template.New("genesis").Parse(genesisTemplate)).Execute(genesisBuf, struct {
> ```

`template.Must(template.New("genesis").Parse(genesisTemplate))`  could be done once and stored in global `var` to not repeat it on every call
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2xtq2i9UptsVGRTv:-N5t2xtq2i9UptsVGRTw:bmqw2l7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
> ```Go
> package config
> ```

Test for `AddGenesisTx` is missing
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5yoXDlAMaxM1R_H_:-N5t5yoXDlAMaxM1R_Ha:b-qkn7ab) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
> ```Go
> package config
> ```

Tests checking if correct token symbol is used everywhere are missing
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t6LRz2r6_r71JAZvR:-N5t6LRz2r6_r71JAZvS:b-4zz8t5) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
> ```Go
> package config
> ```

Test checking if correct address prefix is used to generate addresses is missing
___
*[`pkg/config/genesis_test.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t0wMV3jjIc7Jzuln3:-N5t0wMV3jjIc7Jzuln4:b-r5cpxd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L46)):*
> ```Go
> 	// because comparing json.RawMessage may give false negatives.
> 	appStateMap := map[string]interface{}{}
> 	err = json.Unmarshal(gen.genesisDoc.AppState, &appStateMap)
> ```

Elegance: you could move this call to `assertT.NoError(...)` directly here and below
___
*[`pkg/config/genesis_test.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t17-DDcC7f6Iv3VkP:-N5t17-DDcC7f6Iv3VkQ:b-qutvmh) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L47)):*
> ```Go
> 	appStateMap := map[string]interface{}{}
> 	err = json.Unmarshal(gen.genesisDoc.AppState, &appStateMap)
> 	assertT.NoError(err)
> ```

assertT -> requireT
___
*[`pkg/config/genesis_test.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t19NB5rvTNFqbHeUO:-N5t19NCDdbZLaME1XRD:b-qutvmh) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L50)):*
> ```Go
> 	parsedAppStateMap := map[string]interface{}{}
> 	err = json.Unmarshal(parsedGenesisDoc.AppState, &parsedAppStateMap)
> 	assertT.NoError(err)
> ```

assertT -> requireT
___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N5t2Au0BAGc8q1mzvbx:bc5pds2) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	assertT.Contains(state.Bank.Balances, balance{
> ```

there are more things to check:
- account must be defined in app_state / auth / accounts
- total supply must be correct in app_state / bank / supply

to make those tests more complete, it's better to create two accounts holding different amounts of two tokens, and then check if total supply of each token is correct
___
*[`pkg/config/networks.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3Aq26JeCs7zS80fm:-N5t3Aq30ycQ8_idFFPi:b-cfknow) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L19)):*
> ```Go
> )
> 
> // ChainID represents predefined chain-ids
> ```

chain-ids -> chain ID
___
*[`pkg/config/networks.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t379qC2uHQy06bHdY:-N5t379qC2uHQy06bHdZ:b-z51cb6) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L22)):*
> ```Go
> type ChainID string
> 
> // Predefined chainIDs
> ```

chainIDs -> chain IDs
___
*[`pkg/config/networks.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3RdXA1-iUwh8loE3:-N5t3RdXA1-iUwh8loE4:bdgckun) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L36)):*
> ```Go
> )
> 
> var networks = map[ChainID]Network{
> ```

I would recommend to do it like this:

```go
var networks = []Network{
	{
		GenesisTime:    time.Date(2022, 6, 27, 12, 0, 0, 0, time.UTC) [...]

2022-07-01 09:39 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/genesis.go` line 106 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5szUme6Y-imQ9DkbUj:-N5t778k3vCY9sZWBLXB:bblw2jx) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

call to `EncodeAsJSON` creates a deadlock because mutex is already locked. You need separate non-exported `encodeAsJSON` method not locking on mutex, called from both places
</blockquote></details>

Now I see that mutex here is not needed once you remove `finalized`


<!-- Sent from Reviewable.io -->

2022-07-01 09:40 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3RdXA1-iUwh8loE3:-N5t7Mt-4dUowYooxeyc:bcg4w3x) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would recommend to do it like this:

```go
var networks = []Network{
	{
		GenesisTime:    time.Date(2022, 6, 27, 12, 0, 0, 0, time.UTC),
		ChainID:        Mainnet,
		AddressPrefix:  "core",
		TokenSymbol:    TokenSymbolMain,
		FundedAccounts: []fundedAccount{},
	},
	{
		GenesisTime:    time.Date(2022, 6, 27, 12, 0, 0, 0, time.UTC),
		ChainID:        Devnet,
		AddressPrefix:  "devcore",
		TokenSymbol:    TokenSymbolDev,
		FundedAccounts: []fundedAccount{},
	},

}

var networkMap = func() map[ChainID]Network {
    res := make(map[ChainID]Network, len(networks))

    for _, nw := range networks {
        res[nw.ChainID] = nw
    }

    return res
}()
```

By doing it this way, the relation between map key and nw.ChainID is maintained automatically removing the possibility of human error.
</blockquote></details>

The alternative way could be writing a unit test checking that key in map matches the chain ID, but I prefer the first solution as it does not require to specify chain ID twice manually


<!-- Sent from Reviewable.io -->

2022-07-01 09:52 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t4Iib4FWzcJ9wFxQP:-N5t9n9n7up7jNQT1Y_o:bij4a7e) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`fundedAccount` must be exported because `znet` will use it to define initial wallets
</blockquote></details>

Sorry, now I see that this type is not accepted as a param in `FundAccount`. But this type should be exported anyway because `Network` type uses it for exported field


<!-- Sent from Reviewable.io -->

2022-07-01 10:55 UTC, xlab requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 19 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tO5Kg5RIJq3q_0wlG:b-cqi1ow) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This function should also panic in case of error because all the errors here are related to network misconfiguration, and they can't be fixed by the user of the binary
</blockquote></details>

In Go it's bad idea to mix panics and errors, let's not create artificial panics everywhere.
___
*[`pkg/config/networks.go` line 85 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tOOT3DOY58TAIdv5w:-N5tOOT3DOY58TAIdv5x:b-63klq7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L85)):*
> ```Go
> 	genesisDoc, err := tmtypes.GenesisDocFromJSON(genesis)
> 	if err != nil {
> 		return nil, err
> ```

Errors returned from external functions don't have stack info, nor description, consider doing wrapping 

```
errors.Wrap(err, "failed to unmarshal genesis doc from JSON")
```

That adds more context to the error message and also attaches stack.

That comment should be applied to all places where an error is bubbled up and returned.


<!-- Sent from Reviewable.io -->

2022-07-01 10:56 UTC, xlab commented
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tOrWk4R1MKXYJSN1q:bxb9uim) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

In Go it's bad idea to mix panics and errors, let's not create artificial panics everywhere.
</blockquote></details>

Coda that panics is hard to reuse and test.


<!-- Sent from Reviewable.io -->

2022-07-01 10:57 UTC, xlab commented
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tP9wU7rF9hfrW8NZ4:bhi5xlt) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
> The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.

https://go.dev/blog/defer-panic-and-recover

So, this method is an exported method of an exported object, it must not panic.


<!-- Sent from Reviewable.io -->

2022-07-01 11:14 UTC, oliverasistemas requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/node.go` line 72 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tSxH0-yKlJSnnchyH:-N5tSxH0-yKlJSnnchyI:bkjw9x5) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/node.go#L72)):*
> ```Go
> 
> // NodeID computes node ID from node public key
> func NodeID(pubKey ed25519.PublicKey) string {
> ```

This function is not used.


<!-- Sent from Reviewable.io -->

2022-07-01 11:29 UTC, ysv requested changes
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

___
*[`pkg/config/networks.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3RdXA1-iUwh8loE3:-N5tOPXf0--XiSC8YuEq:bd0306p) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The alternative way could be writing a unit test checking that key in map matches the chain ID, but I prefer the first solution as it does not require to specify chain ID twice manually
</blockquote></details>

yes map approach is slightly better
I would just do initialization of networkMap via `func init()` I think it is more common but not critical for me
___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tSLsJCTc2QXMaT3pG:by7va37) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.

https://go.dev/blog/defer-panic-and-recover

So, this method is an exported method of an exported object, it must not panic.
</blockquote></details>

Good point by @xlab 
I think we are overusing panics and that is not common practice
We should return errors instead 

@wojtek-coreum what is your point on using panics everywhere ?
I personally barely use them in usual development only in some specific cases
___
*[`pkg/config/networks.go` line 85 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tOOT3DOY58TAIdv5w:-N5tSaj81_xBzFcM425E:be0elg) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L85)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Errors returned from external functions don't have stack info, nor description, consider doing wrapping 

```
errors.Wrap(err, "failed to unmarshal genesis doc from JSON")
```

That adds more context to the error message and also attaches stack.

That comment should be applied to all places where an error is bubbled up and returned.
</blockquote></details>

good point
pls check all places
___
*[`pkg/config/networks.go` line 88 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tSg0t7d0MQve0dVtu:-N5tSg0t7d0MQve0dVtv:burselt) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L88)):*
> ```Go
> 	}
> 	var appState map[string]json.RawMessage
> 	err = json.Unmarshal(genesisDoc.AppState, &appState)
> ```

minor: move error to if
___
*[`pkg/config/networks.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tSquP4dSXPZ96oMMW:-N5tSquP4dSXPZ96oMMX:b-ot00lq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L110)):*
> ```Go
> 
> 	for _, fundedAccount := range n.FundedAccounts {
> 		err = g.FundAccount(fundedAccount.PubKey, fundedAccount.Balance)
> ```

minor: move error to if

Viewing this issue multiple times. 
Do you prefer to make it like this @miladz68 ? 
___
*[`pkg/config/networks.go` line 121 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tTBXY71qpSWTN7pDz:-N5tTBXY71qpSWTN7pE-:bhrp2sd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L121)):*
> ```Go
> // NetworkByChainID returns config for a predefined config.
> // predefined networks are "coreum-mainnet" and "coreum-devnet".
> func NetworkByChainID(id ChainID) (Network, error) {
> ```

map approach seems to be slightly better for me
___
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5tUVW72ndbLldSVtwN:b-lsk4wj) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
> ```Go
> 
> func (w Wallet) String() string {
> 	return fmt.Sprintf("%s@%s", w.Name, w.Key.Address())
> ```

I was also always using `fmt.Sprintf` for string interpolation and was sure that it is sort of best-practice

Then I saw that Wojtek uses `+` (e.g `w.Name + "@" + w.Key.Address()` for this case).
I checked a benchmark results and found that + seems to be more performant
https://dev.to/pmalhaire/concatenate-strings-in-golang-a-quick-benchmark-4ahh
I definitely don't care much about performance here but we should stick to a single approach everywhere

On the other hand `Sprintf` seems to be more commonly used & readable in the most case (for me personally)

@xlab @miladz68 @oliverasistemas @wojtek-coreum what are your thoughts on this ?


<!-- Sent from Reviewable.io -->

2022-07-01 11:31 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tVFv03rX24xEmPLuf:b-dxtvhs) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Good point by @xlab 
I think we are overusing panics and that is not common practice
We should return errors instead 

@wojtek-coreum what is your point on using panics everywhere ?
I personally barely use them in usual development only in some specific cases
</blockquote></details>

From the link: 
"The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values."

I don't like this rule. If the error is caused by the package being broken by its developers, I don't see much sense in returning an error to the user because user can't do anything to solve the problem. The problem must be solved by the authors of the package instead. It means that error is unrecoverable, and panic is a very good way of handling unrecoverable errors.

Moreover the rule presented in a link makes completely no sense to me. They allow for panics in non-exported functions, but at the end of the day every non-exported function of the package is called by the exported one to deliver the functionality of the package. So no matter what, the `panic` happens down the call stack initiated by the exported function. And the fact that exported function calls a non-exported one instead of doing everything directly is just an implementation detail.

@miladz68 @ysv WDYT?
___
*[`pkg/config/networks.go` line 85 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tOOT3DOY58TAIdv5w:-N5tUfbDCSzn-kKWpzkt:b-6kgdop) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L85)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Errors returned from external functions don't have stack info, nor description, consider doing wrapping 

```
errors.Wrap(err, "failed to unmarshal genesis doc from JSON")
```

That adds more context to the error message and also attaches stack.

That comment should be applied to all places where an error is bubbled up and returned.
</blockquote></details>

and please apply it everywhere (`os.MkDirAll`, etc.). If writing additional message doesn't make sense for you, just use `return errors.WithStack(err)`


<!-- Sent from Reviewable.io -->

2022-07-01 11:33 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3RdXA1-iUwh8loE3:-N5tX4FpDmE73yCgXUf5:b-bvvopq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes map approach is slightly better
I would just do initialization of networkMap via `func init()` I think it is more common but not critical for me

</blockquote></details>

using `init` is much more common but the approach above places initialization code closer to the variable. I've learnt this trick from my colleague in previous company and like it very much. But I'm not going to block solution using `init`.


<!-- Sent from Reviewable.io -->

2022-07-01 11:34 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5tXSJAAA_L5fi_yk59:b6iclk5) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I was also always using `fmt.Sprintf` for string interpolation and was sure that it is sort of best-practice

Then I saw that Wojtek uses `+` (e.g `w.Name + "@" + w.Key.Address()` for this case).
I checked a benchmark results and found that + seems to be more performant
https://dev.to/pmalhaire/concatenate-strings-in-golang-a-quick-benchmark-4ahh
I definitely don't care much about performance here but we should stick to a single approach everywhere

On the other hand `Sprintf` seems to be more commonly used & readable in the most case (for me personally)

@xlab @miladz68 @oliverasistemas @wojtek-coreum what are your thoughts on this ?


</blockquote></details>

I don't care much which solution is used. Personally I use `+' for simple operations like this one here and `fmt.Sprintf` for more complex patterns.


<!-- Sent from Reviewable.io -->

2022-07-01 11:34 UTC, oliverasistemas reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5tXE5hCm31Rl-8jK_F:bhjdsyv) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't care much which solution is used. Personally I use `+' for simple operations like this one here and `fmt.Sprintf` for more complex patterns.
</blockquote></details>

I would go with the most performant.  `Sprintf` might be necessary if you are not just concatenating strings.  


<!-- Sent from Reviewable.io -->

2022-07-01 11:38 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5tYEXLAAVuDB2EO19J:bqfxqzr) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

I would go with the most performant.  `Sprintf` might be necessary if you are not just concatenating strings.  
</blockquote></details>

To add more to the discussion: I use `fmt.Sprintf` while constructing strings requiring type conversions like `%s/sth/%d` or for types which implement `Stringer` interface to just use `%s` instead of calling `String()` method directly


<!-- Sent from Reviewable.io -->

2022-07-01 12:07 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5t__lw1OPNObg7f-dG:bdxag4s) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
> I don't see much sense in returning an error to the user because user can't do anything to solve the problem

it gives them ability to handle it in more friendly & explicit way (e.g retry, log etc)While panics are implicit and are likely to. Of course it is all possible to handle panics by recovering  but the truth is that it is more likely for app to recover somehwer on the top of stack without much of contex or even kill it 

> Moreover the rule presented in a link makes completely no sense to me. They allow for panics in non-exported functions, but at the end of the day every non-exported function of the package is called by the exported one to deliver the functionality of the package. So no matter what, the panic happens down the call stack initiated by the exported function. And the fact that exported function calls a non-exported one instead of doing everything directly is just an implementation detail.

I fully disagree with this. The do allow panics in non-exported funcs if strongly needed but advise to handle them and return errors from public funcs. So ewerything makes sense for me


My point For errors are:
1. they are testable
2. event if error happens because of package developer we return it in friendly format as a last argument and give pkg user chance to handle it. Panics could also be handled but the flow is more complicated & implicit.
3. errors is the thingy which we like & hate in golang because they are explicit so you could not ignore them. But that is how it is done & it is the specifics of golang


<!-- Sent from Reviewable.io -->

2022-07-01 12:07 UTC, xlab commented
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5tdcCRElCFSzJyOEiK:b-cq22ss) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To add more to the discussion: I use `fmt.Sprintf` while constructing strings requiring type conversions like `%s/sth/%d` or for types which implement `Stringer` interface to just use `%s` instead of calling `String()` method directly
</blockquote></details>

It's not about using single approach. They are different things. Sometimes you just need to concatenate two strings and that's + is for.

`fmt.Sprintf` is when you need to format something. `%s/%s/%d` as a format spec if much clearer than `foo + "/" + bar + "/" + stconv.Itoa(baz)`, I hope you guys get the point. 

So on this side I'm with @wojtek-coreum, let's not force `fmt.Sprintf` when you just need to join two strings, but don't force `append` or `+` for performance coz it's really neglectable


<!-- Sent from Reviewable.io -->

2022-07-01 12:08 UTC, xlab commented
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5teHuF0zNdr8rQ56d-:byok4as) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's not about using single approach. They are different things. Sometimes you just need to concatenate two strings and that's + is for.

`fmt.Sprintf` is when you need to format something. `%s/%s/%d` as a format spec if much clearer than `foo + "/" + bar + "/" + stconv.Itoa(baz)`, I hope you guys get the point. 

So on this side I'm with @wojtek-coreum, let's not force `fmt.Sprintf` when you just need to join two strings, but don't force `append` or `+` for performance coz it's really neglectable
</blockquote></details>

Sidenote: I'd prefer to use `fmt.Sprinf("%d", i)` when I need to format integer, because it's flexible to maintain than `strconv.Itoa(i)`.


<!-- Sent from Reviewable.io -->

2022-07-01 12:11 UTC, xlab commented
*[`pkg/config/networks.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tSquP4dSXPZ96oMMW:-N5tesqIBUup-C3Vexbb:b-t2xz0g) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L110)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: move error to if

Viewing this issue multiple times. 
Do you prefer to make it like this @miladz68 ? 
</blockquote></details>

I prefer it as well, as sometimes combining everything in a single line makes the line extremely long.

This is a style preference and I think we shouldn't try to achieve one single style for every piece we produce.


<!-- Sent from Reviewable.io -->

2022-07-01 12:11 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5teHAw70DT4TwGs3Db:bx6ytuq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> I don't see much sense in returning an error to the user because user can't do anything to solve the problem

it gives them ability to handle it in more friendly & explicit way (e.g retry, log etc)While panics are implicit and are likely to. Of course it is all possible to handle panics by recovering  but the truth is that it is more likely for app to recover somehwer on the top of stack without much of contex or even kill it 

> Moreover the rule presented in a link makes completely no sense to me. They allow for panics in non-exported functions, but at the end of the day every non-exported function of the package is called by the exported one to deliver the functionality of the package. So no matter what, the panic happens down the call stack initiated by the exported function. And the fact that exported function calls a non-exported one instead of doing everything directly is just an implementation detail.

I fully disagree with this. The do allow panics in non-exported funcs if strongly needed but advise to handle them and return errors from public funcs. So ewerything makes sense for me


My point For errors are:
1. they are testable
2. event if error happens because of package developer we return it in friendly format as a last argument and give pkg user chance to handle it. Panics could also be handled but the flow is more complicated & implicit.
3. errors is the thingy which we like & hate in golang because they are explicit so you could not ignore them. But that is how it is done & it is the specifics of golang
</blockquote></details>

another point is that funcs which could potentially panic should have this in name e.g MustParse, ParseOrDie, ParseOrPanic etc

I also want to have some input from other team members @miladz68 @xlab @oliverasistemas 


<!-- Sent from Reviewable.io -->

2022-07-01 12:13 UTC, xlab commented
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tfO9p72t7rFjrUXZY:b-8o475d) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
> funcs which could potentially panic should have this in name e.g MustParse, ParseOrDie, ParseOrPanic etc

100% agree, when panic is expected as a result and is part of the API


<!-- Sent from Reviewable.io -->

2022-07-01 12:14 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5teq9I3H_1Sz1yhAP8:b-ebo6ht) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> funcs which could potentially panic should have this in name e.g MustParse, ParseOrDie, ParseOrPanic etc

100% agree, when panic is expected as a result and is part of the API
</blockquote></details>

For me, this particular case where genesis template is incorrect, is a fatal condition like an airplane crash, apocalypse, zombie attack or sth like these. If this kind of thing happens it's the end of the world (panic).


<!-- Sent from Reviewable.io -->

2022-07-01 12:24 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tgfLi8FOsIqkIc9V1:b-ql2v9x) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

For me, this particular case where genesis template is incorrect, is a fatal condition like an airplane crash, apocalypse, zombie attack or sth like these. If this kind of thing happens it's the end of the world (panic).
</blockquote></details>

BTW, Important note:

panic is not just sth similar to error but more harmful. Panic informs that sth "impossible" happened. On the other hand, error is created if goes wrong but is possible. IMO this is very important difference. In previous company we had special handler on top of application incrementing a prometheus metric counting panics and if this happened DevOps department was alarmed by grafana.


<!-- Sent from Reviewable.io -->

2022-07-01 12:25 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5ti0ld22Bob_UV8YGM:bnqk1jh) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

BTW, Important note:

panic is not just sth similar to error but more harmful. Panic informs that sth "impossible" happened. On the other hand, error is created if goes wrong but is possible. IMO this is very important difference. In previous company we had special handler on top of application incrementing a prometheus metric counting panics and if this happened DevOps department was alarmed by grafana.
</blockquote></details>

One more note :-):

Error in case of invalid genesis template here is more like accessing nil pointer. You don't continue, but panic.


<!-- Sent from Reviewable.io -->

2022-07-01 12:39 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tlJSf1F51W2CoSBvR:bj84dfo) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Yes but this could happen in 1 case:
- package wasn't tested and released as fully broken and whatever user does with it nothing will help. It is like 500

Maybe for this specific case it makes sense to panic if genesis is brokn.
But we have other places where we overuse it especially with must.

e.g
```golang
// cored/node.go
  
  must.OK(os.MkdirAll(homeDir+"/data", 0o700))
```
here it depends on homeDir passed by user and doesn't mean that the package is broken but could be issue on user side


My concern is that we have more panics in our code than 10 times bigger projects
</blockquote></details>

Since we have concerns on this function I prefer to create 2 functions MustGenesis & Genesis and that is it


<!-- Sent from Reviewable.io -->

2022-07-01 12:44 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5D5v4n0ChFp1TMZh:-N5tlclt9S2dfk2Nj1q9:b-7gcrs7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L75)):*
Yes, in `znet`I used panics in many places, to handle errors returned by all the functions everywhere. I did it because the `znet` is our internal tool and despite few places it controls the environment entirely. We could change those places eventually if you don't like it. But here, in case of genesis template, the panic is very obvious to me.

> Since we have concerns on this function I prefer to create 2 functions MustGenesis & Genesis and that is it

It makes no sense to me. Let's decide which way we want to follow and use it consistently.


<!-- Sent from Reviewable.io -->

2022-07-01 13:27 UTC, xlab commented
*[`pkg/types/types.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tUVW72ndbLldSVtwM:-N5twK8Y7huY5k8FROZw:b3k61xb) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/types/types.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

for simple things makes sense for me.
so I guess here it is quite simple and we could use `+` to follow consistency with what we aready have but not important for me.

Just wanted to make sure we are all on the same page

And here are some example references from crust where I would prefer `Sprintf`

```	

//hasura/hasura.go
DatabaseURL: "postgresql://" + postgres.User + "@" + infra.JoinNetAddr("", h.postgres.Info().HostFromContainer, h.postgres.Port()) + "/" + postgres.DB,

// infra/types.go
specFile := configF.HomeDir + "/" + configF.EnvName + "/spec.json"

```

</blockquote></details>

🫤


<!-- Sent from Reviewable.io -->

2022-07-04 09:53 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: 4 of 10 files reviewed, 22 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/config/genesis.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5syzLbArkC1KYKUaez:-N5tVNcw0lpKkxmIHC4f:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would say this might be removed. This is `znet`-specific field and should not be done in generic implementation
</blockquote></details>

Done.
___
*[`pkg/config/genesis.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-2p67NCg0pmKgPj7:-N5tVPqzDMRNIVvvIWux:bw7dh2t) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: if error happends inside this function I would just panic instead of returning it because it really means we screwed up sth
</blockquote></details>

I know that this is a non recoverable error, But I would rather not use panic anywhere. @ysv @xlab @oliverasistemas, would you care to comment ?
___
*[`pkg/config/genesis.go` line 106 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5szUme6Y-imQ9DkbUj:-N5tXCN08QzEbAhrCnDq:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now I see that mutex here is not needed once you remove `finalized`
</blockquote></details>

Done.
___
*[`pkg/config/genesis.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t4fdp1_YMcD53J2KC:-N5tXSLUCCQJHYz0OInm:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

in case of error this function should panic instead of returning it, because error here means that we made sth wrong during development. This function is not expected to fail on runtime
</blockquote></details>

Done.
___
*[`pkg/config/genesis.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-ofx1MVCCydL9V4M:-N5tmwJrCuBIstOVU2lF:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`template.Must(template.New("genesis").Parse(genesisTemplate))`  could be done once and stored in global `var` to not repeat it on every call
</blockquote></details>

Done.
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2xtq2i9UptsVGRTv:-N67I8n8ALlsE5b7ukiv:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Test for `AddGenesisTx` is missing
</blockquote></details>

Done.
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t5yoXDlAMaxM1R_H_:-N67MgqCB2vG4oPvH9C3:bwsylu3) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Tests checking if correct token symbol is used everywhere are missing
</blockquote></details>

I have no Idea how this could be achieved, without encoding the entire genesis logic into the test.
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t6LRz2r6_r71JAZvR:-N67MncE1K181TSVechL:bwsylu3) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Test checking if correct address prefix is used to generate addresses is missing
</blockquote></details>

I have no Idea how this could be achieved, without encoding the entire genesis logic into the test.
___
*[`pkg/config/genesis_test.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t0wMV3jjIc7Jzuln3:-N67NBSdDFV2OcsOlNwf:b-4yhqrz) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Elegance: you could move this call to `assertT.NoError(...)` directly here and below
</blockquote></details>

I tend to dislike this pattern. Yes it combines 2 lines of code into one, but it makes it harder to read.
___
*[`pkg/config/genesis_test.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t17-DDcC7f6Iv3VkP:-N67NWDG90e8y1PZQQ0m:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

assertT -> requireT
</blockquote></details>

Done.
___
*[`pkg/config/genesis_test.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t19NB5rvTNFqbHeUO:-N67NWyv9ejOiY_V8wdQ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

assertT -> requireT
</blockquote></details>

Done.
___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N67Nhl7A3xY9Ug_m-dE:bmzhyqc) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

there are more things to check:
- account must be defined in app_state / auth / accounts
- total supply must be correct in app_state / bank / supply

to make those tests more complete, it's better to create two accounts holding different amounts of two tokens, and then check if total supply of each token is correct
</blockquote></details>

I disagree to test these things here. @xlab @ysv would you care to comment ?
___
*[`pkg/config/networks.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3Aq26JeCs7zS80fm:-N67PChY8pzZhxe0gczP:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

chain-ids -> chain ID
</blockquote></details>

Done.
___
*[`pkg/config/networks.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t379qC2uHQy06bHdY:-N67PK9w1BvwTuVJfFLI:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L22)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

chainIDs -> chain IDs
</blockquote></details>

Done.
___
*[`pkg/config/networks.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3RdXA1-iUwh8loE3:-N67Pg3W95JI_s95ZXkP:b-imyx9) ([raw file](https://github.com/coreumfoundation/coreum/blob [...]

2022-07-04 10:49 UTC, wojtek-coreum requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 14 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67lnzZAqqFmaNTiQL8:-N67lnzZAqqFmaNTiQL9:bixprcm) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/cmd/cored/main.go#L14)):*
> ```Go
> 
> func main() {
> 	network, err := config.NetworkByChainID(config.Mainnet)
> ```

`network.SetupPrefixes()` must be called here, and maybe it could return address prefix, so `AddressPrefix` method is not needed
___
*[`pkg/config/genesis.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67huAg3DvON4a6909W:-N67huAg3DvON4a6909X:by7xupe) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L30)):*
> ```Go
> 	genesisDoc *tmtypes.GenesisDoc
> 
> 	mu           *sync.Mutex
> ```

Why removed? The fields listed below still must be protected
___
*[`pkg/config/genesis.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-ofx1MVCCydL9V4M:-N67kHHt-P4Ws1xb1FFj:bqwqog8) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L131)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Current version will create a mess if I request genesis for two different `Network`s. You can cache only the part parsing the template, i mentioned in first comment. But parameter substitution must be done each time from scratch.
___
*[`pkg/config/genesis.go` line 106 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67iNGG34mNwVJxhgV0:-N67iNGH2fIQHCSBvi5u:bnr23rv) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L106)):*
> ```Go
> 	}
> 
> 	err = tmos.WriteFile(homeDir+"/config/genesis.json", genDocBytes, 0644)
> ```

You could simply use `ioutil.WriteFile` instead
___
*[`pkg/config/genesis.go` line 107 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67hdBqDpv3t-ojanqS:-N67hdBrCx73yGytXl1l:bgcv2mi) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L107)):*
> ```Go
> 
> 	err = tmos.WriteFile(homeDir+"/config/genesis.json", genDocBytes, 0644)
> 	return errors.Wrap(err, "unable to write genesis bytes to file")
> ```

return error only if `err != nil`
___
*[`pkg/config/genesis.go` line 110 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67j2eq76eF2jFTa3ki:-N67j2eq76eF2jFTa3kj:b-g12hk0) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L110)):*
> ```Go
> }
> 
> func (g *Genesis) GenerateAddValidatorTx(
> ```

This method does not use any knowledge held by `Genesis` type, so it might be used to generate any `MsgCreateValidator` transaction, not only the one included in genesis. That's why it should be defined as a function outside `Genesis` type.
___
*[`pkg/config/genesis.go` line 147 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67jkrU0QWEJqnh3T1d:-N67jkrU0QWEJqnh3T1e:bwcahve) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L147)):*
> ```Go
> }
> 
> func (g *Genesis) AddValidator(
> ```

The previous idea, where `AddGenesisTx` took any transaction as an argument and added it to genesis looked better IMO. It should be the responsibility of the caller to call `GenerateAddValidatorTx` first and then `AddGenesisTx`
___
*[`pkg/config/genesis_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t6LRz2r6_r71JAZvR:-N67mxKs6gHDRvGpeOaH:bpsa9z3) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have no Idea how this could be achieved, without encoding the entire genesis logic into the test.
</blockquote></details>

1. You take the network and call `SetupPrefixes`
2. You generate random private / public key
3. You encode public key into address
4. You check that the prefix of bech32-encoded address is the same as the one set inside the network
___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N67m_Tk3HqKrUaoyaIr:bn78san) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I disagree to test these things here. @xlab @ysv would you care to comment ?
</blockquote></details>

But these are the correct outcomes of `AddFunds` if it doesn't work, genesis is invalid
___
*[`pkg/config/networks.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t3RdXA1-iUwh8loE3:-N67nkrX2P1n3PH5m-29:b-ivimul) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L36)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I will use the init approach, the problem with the function approach is that it will generate a new map on every function call.
</blockquote></details>

It doesn't matter, because this function is called only once when package is imported, just like `init`. But as i said `init` is good enough for me
___
*[`pkg/config/networks.go` line 36 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67o-iX0_n_Q26zJNds:-N67o-iX0_n_Q26zJNdt:b-xhpqx9) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/networks.go#L36)):*
> ```Go
> 
> func init() {
> 	networksList := []Network{
> ```

Non-blocking: I would prefer to have `networksList` outside the `init` because there is nothing in this list requiring it to be here


<!-- Sent from Reviewable.io -->

2022-07-04 11:07 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/config/networks.go` line 62 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67t52N1YmLw_GT6m5u:-N67t52N1YmLw_GT6m5v:b8spry9) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/networks.go#L62)):*
> ```Go
> // Network holds all the configuration for different predefined networks
> type Network struct {
> 	genesisTime         time.Time
> ```

I imagine that `znet` will create its own `Network` configuration, so the fields here can't be private


<!-- Sent from Reviewable.io -->

2022-07-04 11:11 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 19 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/config/genesis.go` line 49 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67toqW1Vnck5v3DsFE:-N67toqXBLtCky9EQ8nr:b5pd890) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L49)):*
> ```Go
> 
> // FundAccount funds address with balances at genesis
> func (g *Genesis) FundAccount(publicKey types.Secp256k1PublicKey, balances string) error {
> ```

I think this method might be private because all the funded accounts should be included in `Network` object


<!-- Sent from Reviewable.io -->

2022-07-04 13:16 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 14 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67lnzZAqqFmaNTiQL8:-N68IS4_7UO2j7dZUQTv:b-5x40eb) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/cmd/cored/main.go#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

adress prefixes are getting set inside the rootCmd, so it is not needed to be done here. I will set it here anyway.
</blockquote></details>

Ah, I see.  So there is no need to do it explicitly then, I think
___
*[`pkg/config/genesis.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67huAg3DvON4a6909W:-N68IeO7Eq8VCA_Btxik:b6et24y) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

In your previous comment you mentioned to remove a line which I interpreted to remove the mutex lock. and I don't think the genesis config needs to be thread safe as I cannot thing of a use case at this point.
</blockquote></details>

In `znet` many cored nodes are configured in parallel by separate goroutines, they add the validator transaction to gentx, and staker balance to funded accounts.
___
*[`pkg/config/genesis.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-ofx1MVCCydL9V4M:-N68FkGC1LwivmyMaUFe:b-ebnq1m) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Current version will create a mess if I request genesis for two different `Network`s. You can cache only the part parsing the template, i mentioned in first comment. But parameter substitution must be done each time from scratch.
</blockquote></details>

The `template.Must(...)` part might be done once
___
*[`pkg/config/genesis.go` line 49 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67toqW1Vnck5v3DsFE:-N68J3DoCKuVN-bTPx9i:b-wo1o0h) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L49)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Genesis might be modified by znet to add fund more accounts.
</blockquote></details>

Yes, but I'm still not sure if it should be done using this method, or just by adding them to network's funded accounts
___
*[`pkg/config/genesis.go` line 110 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N68FR_u28kxhYmNM0rT:-N68FR_u28kxhYmNM0rU:bp6nkox) ([raw file](https://github.com/coreumfoundation/coreum/blob/11bd9cf6c4b44caa96de2b6116f8c66931c1b47d/pkg/config/genesis.go#L110)):*
> ```Go
> 
> func GenerateAddValidatorTx(
> 	g *Genesis,
> ```

I don't see `g` to be used inside this function
___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N68IAOL2LrL80xiJjvv:b-cbxuyr) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I disagree since I cannot think of a way of doing this in a blackbox manner. I mean to test it, I need to know the implementation detail of the function.
</blockquote></details>

I don't understand, the only thing to check is that particular json fields contain valid token amounts.


<!-- Sent from Reviewable.io -->

2022-07-04 15:28 UTC, xlab commented
*[`pkg/config/genesis.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-2p67NCg0pmKgPj7:-N68onsLBTujKdx_lXhF:bccygg7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L75)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I know that this is a non recoverable error, But I would rather not use panic anywhere. @ysv @xlab @oliverasistemas, would you care to comment ?
</blockquote></details>

It's a public function over a public object, it should return an error. Especially if it may wrap up a lot of other errors.


<!-- Sent from Reviewable.io -->

2022-07-04 15:31 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N68pELO1vl1A05XPYDF:bbncq1r) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand, the only thing to check is that particular json fields contain valid token amounts.
</blockquote></details>

Those are unit tests, they should cover the new logic added, that logic code coverage is all that we care about.

I agree that PR doesn't need to meet 100% coverage, but it's nice to have or be closer to.


<!-- Sent from Reviewable.io -->

2022-07-04 15:32 UTC, xlab approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-04 15:33 UTC, xlab submitted a review, later dismissed
> Reviewed 4 of 10 files at r1, 2 of 6 files at r2, 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-04 16:11 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, and @ysv)

___
*[`pkg/config/genesis.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-ofx1MVCCydL9V4M:-N68xXBvCfFivxlGJyTJ:bzcavfz) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The `template.Must(...)` part might be done once
</blockquote></details>

Changing it to non-blocking but personally would still prefer to have sth like:
```go
var genesisParsedTemplate = template.Must(template.New("genesis").Parse(genesisTemplate))
```
___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N68xoaL5RlIVLlS_juq:b-j97wqr) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Those are unit tests, they should cover the new logic added, that logic code coverage is all that we care about.

I agree that PR doesn't need to meet 100% coverage, but it's nice to have or be closer to.



</blockquote></details>

And adding accounts and total supply *is* the logic introduced by *us*:
here: https://github.com/miladz68/coreum/blob/milad/create-network-config/pkg/config/genesis.go#L51
and here: https://github.com/miladz68/coreum/blob/milad/create-network-config/pkg/config/genesis.go#L58

So if we decided that logic of generating genesis.json should be covered by unit tests then let's not stop half the way.


<!-- Sent from Reviewable.io -->

2022-07-04 16:14 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/config/genesis.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67huAg3DvON4a6909W:-N68TEyq09viUmvIE8C4:b-g6910d) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In `znet` many cored nodes are configured in parallel by separate goroutines, they add the validator transaction to gentx, and staker balance to funded accounts.
</blockquote></details>

re-added.
___
*[`pkg/config/genesis.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-ofx1MVCCydL9V4M:-N68OevBAte210WuMgLI:b-12lrb) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Changing it to non-blocking but personally would still prefer to have sth like:
```go
var genesisParsedTemplate = template.Must(template.New("genesis").Parse(genesisTemplate))
```
</blockquote></details>

it might, but i argue that it is a premature optimization, I don't see the use case for fetching a lot of genesis files.
___
*[`pkg/config/genesis.go` line 49 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N67toqW1Vnck5v3DsFE:-N68OMd36EbLPXIPY1xc:b-oitw3w) ([raw file](https://github.com/coreumfoundation/coreum/blob/61f144920f44e3790313b31e0519b147b354714a/pkg/config/genesis.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, but I'm still not sure if it should be done using this method, or just by adding them to network's funded accounts
</blockquote></details>

we will discuss it when we get there.
___
*[`pkg/config/genesis.go` line 110 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N68FR_u28kxhYmNM0rT:-N68OTOe7A6sofkw0fc1:b-dmqojf) ([raw file](https://github.com/coreumfoundation/coreum/blob/11bd9cf6c4b44caa96de2b6116f8c66931c1b47d/pkg/config/genesis.go#L110)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see `g` to be used inside this function
</blockquote></details>

absolutely right
___
*[`pkg/config/genesis_test.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t2Au0BAGc8q1mzvbw:-N68U6kD2jRwQY30MEvP:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis_test.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

And adding accounts and total supply *is* the logic introduced by *us*:
here: https://github.com/miladz68/coreum/blob/milad/create-network-config/pkg/config/genesis.go#L51
and here: https://github.com/miladz68/coreum/blob/milad/create-network-config/pkg/config/genesis.go#L58

So if we decided that logic of generating genesis.json should be covered by unit tests then let's not stop half the way.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-04 16:24 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @oliverasistemas, and @ysv)

___
*[`pkg/config/genesis.go` line 36 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N6908Wc2Q9yq5nEdbcK:-N6908Wc2Q9yq5nEdbcL:b9qcqn9) ([raw file](https://github.com/coreumfoundation/coreum/blob/2458f7498bf4d357ddd2b99e5886f7fb31da138a/pkg/config/genesis.go#L36)):*
> ```Go
> 	codec        codec.Codec
> 	genesisDoc   *tmtypes.GenesisDoc
> 	mu           *sync.Mutex
> ```

Pointer is not needed here because `Genesis` is already use by pointer.
___
*[`pkg/config/genesis_test.go` line 152 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N69-m7gDLu0BiiC2vvC:-N69-m7h5VTYlNrx-4w5:besndds) ([raw file](https://github.com/coreumfoundation/coreum/blob/2458f7498bf4d357ddd2b99e5886f7fb31da138a/pkg/config/genesis_test.go#L152)):*
> ```Go
> 	)
> 	requireT.Len(state.Auth.Accounts, 2)
> 	assertT.EqualValues(state.Auth.Accounts[0].Address, accountAddress.String())
> ```

Is this line a leftover? Looks like the next one does exactly that but for both accounts


<!-- Sent from Reviewable.io -->

2022-07-04 20:34 UTC, oliverasistemas submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`pkg/config/genesis.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5t-2p67NCg0pmKgPj7:-N69uiPL9VdGOonp8cW7:b-8tzaks) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/genesis.go#L75)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's a public function over a public object, it should return an error. Especially if it may wrap up a lot of other errors.
</blockquote></details>

I prefer error


<!-- Sent from Reviewable.io -->

2022-07-05 06:35 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`pkg/config/genesis.go` line 36 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N6908Wc2Q9yq5nEdbcK:-N6C2lRf9xK1evoJNSLf:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2458f7498bf4d357ddd2b99e5886f7fb31da138a/pkg/config/genesis.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Pointer is not needed here because `Genesis` is already use by pointer.
</blockquote></details>

Done.
___
*[`pkg/config/genesis_test.go` line 152 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N69-m7gDLu0BiiC2vvC:-N6C2uCcEBTRB_0MgkND:b-c683c4) ([raw file](https://github.com/coreumfoundation/coreum/blob/2458f7498bf4d357ddd2b99e5886f7fb31da138a/pkg/config/genesis_test.go#L152)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is this line a leftover? Looks like the next one does exactly that but for both accounts
</blockquote></details>

it is, removed.


<!-- Sent from Reviewable.io -->

2022-07-05 06:57 UTC, wojtek-coreum requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`pkg/config/networks.go` line 111 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N6C8P990qk-lmKUO_Ru:-N6C8P990qk-lmKUO_Rv:b-1tk4wu) ([raw file](https://github.com/coreumfoundation/coreum/blob/500c76590c527550d0ef21f338ebbc6ce0e05bef/pkg/config/networks.go#L111)):*
> ```Go
> 	g := &Genesis{
> 		codec:        codec,
> 		mu:           sync.Mutex{},
> ```

You don't need this line


<!-- Sent from Reviewable.io -->

2022-07-05 07:02 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`pkg/config/networks.go` line 111 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N6C8P990qk-lmKUO_Ru:-N6C9eiG9bKbeZYxUt_W:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/500c76590c527550d0ef21f338ebbc6ce0e05bef/pkg/config/networks.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need this line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 07:02 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-07-05 10:31 UTC, ysv approved these changes
> Reviewed 2 of 10 files at r1, 1 of 6 files at r2, 1 of 4 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`pkg/config/networks.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/105#-N5tSquP4dSXPZ96oMMW:-N6Ct0aC9uv428yomL8C:bg1nvhp) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa33f3f3842dd69fbca620ed4bf990f67857db7/pkg/config/networks.go#L110)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv I don't have a strong opinion here, but I totally agree with Max here. that combining lines comes at the cost of readability. and I think it has a strong effect on readability. 
</blockquote></details>

Ok
I don't mind makes sense for me also


<!-- Sent from Reviewable.io -->

2022-07-05 10:42 UTC, wojtek-coreum approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/105)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-07-05 10:54 UTC, merged