re-implemented init command so it uses pre-defined network configs
CoreumFoundation/coreum pull request #113
Opened 2022-07-22 13:59 UTC by miladz68

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/coreum/113)

2022-07-22 18:18 UTC, wojtek-coreum reviewed
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: all files reviewed, 32 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7b6bpx7OfcxZMKHUaq:-N7b6bpx7OfcxZMKHUar:b-c8d55k) (no related file):*
All the comments I left here are non-blocking. It doesn't mean they are not important, just don't want to block this PR so it can be merged before I come back.

I leave it to you and @ysv (he may set his status to "blocking" on the comments he feels are important) to decide if and how to fix the mentioned issues. 

___
___
*[`app/network.go` line 194 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7anLCt-Y1SADm1YK_c:-N7anLCt-Y1SADm1YK_d:b-qf2t7p) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L194)):*
> ```Go
> 		addressPrefix:  c.AddressPrefix,
> 		tokenSymbol:    c.TokenSymbol,
> 		nodeConfig:     c.NodeConfig,
> ```

You must make a copy of `c.NodeConfig.SeedPeers`. Otherwise modifying that config will modify already created network too.
Also it should be checked in one of existing unit tests.
___
*[`app/network.go` line 230 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7anhZx26xp1gabmPYD:-N7anhZx26xp1gabmPYE:bfvzzvf) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L230)):*
> ```Go
> // NodeConfig returns NodeConfig
> func (n *Network) NodeConfig() *NodeConfig {
> 	return &n.nodeConfig
> ```

Here `SeedPeers` should be copied too.
Maybe `Clone()` should be added to all the config structure to make all the copies in an organized way.
___
*[`app/network.go` line 263 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aoXuS7qsr-LTKPvI-:-N7aoXuT3JYQSLsHyZtu:b-rdr97z) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L263)):*
> ```Go
> 
> // GenesisDoc returns the genesis doc of the network
> func (n Network) GenesisDoc() (*tmtypes.GenesisDoc, error) {
> ```

Why do you export this function. Is there a plan to use it anywhere outside this package?
___
*[`app/network.go` line 312 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ao-xf8KtLLGzdKlAy:-N7ao-xf8KtLLGzdKlAz:b1rtwpv) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L312)):*
> ```Go
> 
> 	genesisDoc.AppState, err = json.MarshalIndent(appState, "", "  ")
> 	return genesisDoc, err
> ```

I had this discussion with Max previously. I would recommend to not return meaningful result (`genesisDoc`) together with non-nil error.
It may lead to situation where caller forgets to check the error and is still able to use the result without causing panic.
___
*[`app/node_config.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aooVKBWYBxNH91OrR:-N7aooVKBWYBxNH91OrS:b-xwaw7t) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L19)):*
> ```Go
> 	Name           string
> 	PrometheusPort int
> 	NodeKey        tmed25519.PrivKey
> ```

Earlier we agreed that we don't want to expose cosmos-specific types to the outside world. That's why I used `ed25519` package from standard library. This change is against what we have decided.
___
*[`app/node_config.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ax_ed76lDrsJ2VH0f:-N7ax_ed76lDrsJ2VH0g:b1lz5b8) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L58)):*
> ```Go
> 	cfg.Moniker = nc.Name
> 	// set addr_book_strict to false so nodes connecting from non-routable hosts are added to address book
> 	cfg.P2P.AddrBookStrict = false
> ```

These parameters were never set like this with the intention of being used in production. If you want to use them as defaults for public nodes, their values should be reconsidered. And maybe (I don't know) all or some of them should be configured per network.
___
*[`app/node_config.go` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ayNyICmUms0yZHZn2:-N7ayNyICmUms0yZHZn3:b-4s45ei) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L77)):*
> ```Go
> 
> // SaveConfig saves tendermint config to file
> func (nc NodeConfig) SaveConfig(homeDir string) error {
> ```

Once `TendermintNodeConfig` is thre, I don't see a reason for having this function. Only `znet` will call this, which means that this piece of code might be used there directly without this helper.
___
*[`cmd/cored/flag_process_test.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aqwDO7ZKZmg3S9ETt:-N7aqwDP9wVVBn1IzFzy:besioor) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/flag_process_test.go#L17)):*
> ```Go
> 		expected []string
> 	}{
> 		{
> ```

I miss the test case where `--home` is not provided at all
___
*[`cmd/cored/flag_process_test.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aqdQK0C02Pj5G11iN:-N7aqdQK0C02Pj5G11iO:bi42xm1) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/flag_process_test.go#L49)):*
> ```Go
> 			err := appendStringFlag(tc.input, tc.flag, tc.newVal)
> 			assertT.NoError(err)
> 			assertT.EqualValues(tc.input, tc.expected)
> ```

First argument should be the expected value, and second the value produced by the tested code
___
*[`cmd/cored/init.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7arEaMEugw3bFN3cmt:-N7arEaN5jhNVib6dG4Y:bfn5qvi) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L27)):*
> ```Go
> 	FlagOverwrite = "overwrite"
> 
> 	// FlagSeed defines a flag to initialize the private validator key from a specific seed.
> ```

Sth is wrong with the comment or constant here
___
*[`cmd/cored/init.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7asmSX4MXVfSuwd0y6:-N7asmSY7yTSyDhKWCms:b-2i7wj3) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L40)):*
> ```Go
> 			chainID, _ := cmd.Flags().GetString(flags.FlagChainID)
> 			if chainID == "" {
> 				return errors.New("chain id not provided")
> ```

Minor: this error is covered by calling `app.NetworkByChainID(chainID)` anyway, and you do it later
___
*[`cmd/cored/init.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7atErf12Op-bc1RORJ:-N7atErg82QpIt2qwHXS:bgmxfnz) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L50)):*
> ```Go
> 			// Get bip39 mnemonic
> 			var mnemonic string
> 			recoverFlg, _ := cmd.Flags().GetBool(FlagRecover)
> ```

Minor: Skipping `a` in `Flg` instead of `Flag` does not save a lot of space but makes coder less readable.
___
*[`cmd/cored/init.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ate4jDVqt7HqvZMub:-N7ate4jDVqt7HqvZMuc:byxpuek) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L50)):*
> ```Go
> 			// Get bip39 mnemonic
> 			var mnemonic string
> 			recoverFlg, _ := cmd.Flags().GetBool(FlagRecover)
> ```

Minor: `recoverFlg` is not a flag actually, but bool (the value of a flag)
___
*[`cmd/cored/init.go` line 51 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7atmmK8gOjjgWv0RlY:-N7atb2X5tSLy7EYY3Qd:bompt3q) ([raw file](https://github.com/coreumfoundation/coreum/blob/b1 [...]

2022-07-26 10:36 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 2 of 9 files reviewed, 21 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7b6bpx7OfcxZMKHUaq:-N7ty3HkAW-GyCRhno_S:b-fyujmv) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

All the comments I left here are non-blocking. It doesn't mean they are not important, just don't want to block this PR so it can be merged before I come back.

I leave it to you and @ysv (he may set his status to "blocking" on the comments he feels are important) to decide if and how to fix the mentioned issues. 
</blockquote></details>

@ysv 
I addressed all the comments, please review when you have time.

___
___
*[`app/network.go` line 194 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7anLCt-Y1SADm1YK_c:-N7tSFYAAoHc75fXNBWE:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L194)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You must make a copy of `c.NodeConfig.SeedPeers`. Otherwise modifying that config will modify already created network too.
Also it should be checked in one of existing unit tests.
</blockquote></details>

Done
___
*[`app/network.go` line 230 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7anhZx26xp1gabmPYD:-N7tTAM91kbYJD179Irx:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L230)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here `SeedPeers` should be copied too.
Maybe `Clone()` should be added to all the config structure to make all the copies in an organized way.
</blockquote></details>

Done
___
*[`app/network.go` line 263 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aoXuS7qsr-LTKPvI-:-N7tTKyV5wq9CU6mGd2_:b-2qe6hw) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L263)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why do you export this function. Is there a plan to use it anywhere outside this package?
</blockquote></details>

I used it when we had 2 use cases in init cmd. now it is not used. I will unexport it.
___
*[`app/network.go` line 312 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ao-xf8KtLLGzdKlAy:-N7tTkbyAP3RbzjoBRl_:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L312)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I had this discussion with Max previously. I would recommend to not return meaningful result (`genesisDoc`) together with non-nil error.
It may lead to situation where caller forgets to check the error and is still able to use the result without causing panic.
</blockquote></details>

Done
___
*[`app/node_config.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aooVKBWYBxNH91OrR:-N7tToxAAJHxVq7esNe8:bpcgoan) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Earlier we agreed that we don't want to expose cosmos-specific types to the outside world. That's why I used `ed25519` package from standard library. This change is against what we have decided.
</blockquote></details>

reverted to not use cosmo types.
___
*[`app/node_config.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ax_ed76lDrsJ2VH0f:-N7pAGJJ-IHe3fLNx-iB:b-uddspa) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

These parameters were never set like this with the intention of being used in production. If you want to use them as defaults for public nodes, their values should be reconsidered. And maybe (I don't know) all or some of them should be configured per network.
</blockquote></details>

Done. will move this settings to crust part.
___
*[`app/node_config.go` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ayNyICmUms0yZHZn2:-N7pBRIs254hagVvhpwd:b-4a5p47) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Once `TendermintNodeConfig` is thre, I don't see a reason for having this function. Only `znet` will call this, which means that this piece of code might be used there directly without this helper.
</blockquote></details>

save config will abstracts the call to `config.WriteConfigFile()` from tendermint config package. so znet does not have to reach tendermint config package. 
I refactored this method into standalone function which only exports the internal `WriteConfigFile` function from tendermint.
___
*[`cmd/cored/init.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7arEaMEugw3bFN3cmt:-N7tYO1PCIGF3p6NqNKX:bf85g7a) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Sth is wrong with the comment or constant here
</blockquote></details>

Copied from cosmos, I fixed it first time but some how it got overwritten. probably copied it again and forgot to change it second time.
___
*[`cmd/cored/init.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7asmSX4MXVfSuwd0y6:-N7tZ-5t6G_DtoUdnHBK:b-djvjer) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: this error is covered by calling `app.NetworkByChainID(chainID)` anyway, and you do it later
</blockquote></details>

This is different error IMO. this checks that cmd interface rules are observed (i.e chainID flag is set with default value). the other check is whether the provided chain id is a valid one. I don't think we should remove the first check because the second check will catch it.
___
*[`cmd/cored/init.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7atErf12Op-bc1RORJ:-N7tZYOWEHjOuGFwqctx:b6ayvog) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: Skipping `a` in `Flg` instead of `Flag` does not save a lot of space but makes coder less readable.
</blockquote></details>

Renamed to `isRecover`
___
*[`cmd/cored/init.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ate4jDVqt7HqvZMub:-N7tZcgfCcq6ahqbfzfm:b-o35iei) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: `recoverFlg` is not a flag actually, but bool (the value of a flag)
</blockquote></details>

commented above
___
*[`cmd/cored/init.go` line 51 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7atmmK8gOjjgWv0RlY:-N7tZhyy18R4kw7A5P0G:b18o1v) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L51) [...]

2022-07-26 13:46 UTC, ysv requested changes
> Reviewed 1 of 9 files at r1, 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 5 of 9 files reviewed, 29 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7b6bpx7OfcxZMKHUaq:-N7ujs191QarUFCZ3wG8:b-spho74) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv 
I addressed all the comments, please review when you have time.
</blockquote></details>

@miladz68 can I kindly ask you to write a few paragraphs of description for this PR because I'm struggling to understand it fully.
I'm especially interested in how it was/hot it works now

___
___
*[`go.mod` line 18 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uR2HY3qb7NnmzaGJP:-N7uR2HY3qb7NnmzaGJQ:be9bql6) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/go.mod#L18)):*
> ```XML
> 	github.com/ignite/cli v0.22.2
> 	github.com/pkg/errors v0.9.1
> 	github.com/rs/zerolog v1.26.1
> ```

We were using zap everywhere before

I don't mind using zerolog or zap. actually it is probably worth checking the difference between 2. But we should probably stick to a single logger everywhere

WDYT ?
___
*[`app/network.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uS1mA5g9TgLcVJR5d:-N7uS1mA5g9TgLcVJR5e:bry08l5) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/network.go#L91)):*
> ```Go
> 			},
> 			NodeConfig: NodeConfig{
> 				SeedPeers: []string{"4ae4593aff8dd5ececd217f273195549503e2df8@35.223.81.227:26656"},
> ```

non blocking:

I'm just thinking what if we decide to move our devnet to other server and IP changes ?
will this force all users to update to a newer version ?

This solution is fine for now but as for long-running solution we should probably use some domain or have smth better here

What are your thoughts/plan on this ?
___
*[`app/node_config.go` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ayNyICmUms0yZHZn2:-N7uYEzYBsFkOhWUYX6z:b5girn7) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/node_config.go#L77)):*
> from tendermint config package. so znet does not have to reach tendermint config package
100% agree

current solution is ok for me and I think it is the cleanest we can have in this situation
___
*[`app/node_config.go` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uUMi50mCvSXo0b_8Y:-N7uUMi50mCvSXo0b_8Z:biyw926) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L40)):*
> ```Go
> 	}
> 
> 	copied.NodeKey = append(copied.NodeKey, nc.NodeKey...)
> ```

minor
I think using copy is more idiomatic way but I don't insist

```
NodeKey:        make([]byte{}, len(nc.NodeKey))
// ...
copy(copied.NodeKey, nc.NodeKey)
```
___
*[`app/node_config.go` line 76 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uYb5j2-ApyFTEefIr:-N7uYb5j2-ApyFTEefIs:b-5pz6my) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L76)):*
> ```Go
> }
> 
> // TendermintNodeConfig applies node's tendermint config
> ```

does it really apply tendermint config ?
I actually struggle to understand this method logic fully
___
*[`cmd/cored/init.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7asmSX4MXVfSuwd0y6:-N7uZHExANW9Fj887q6Q:b-te4cl0) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L40)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is different error IMO. this checks that cmd interface rules are observed (i.e chainID flag is set with default value). the other check is whether the provided chain id is a valid one. I don't think we should remove the first check because the second check will catch it.
</blockquote></details>

ok for me
it is like basic validation of flag
___
*[`cmd/cored/init.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7aydV5Cb1_BRReMXW-:-N7uaIn067YOuC69S2Rm:b-qwpb4e) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/init.go#L99)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think existing key is more accurate, it could be any existing key that they want to recover not necessarily previous validator's key.
</blockquote></details>

agree with Milad
___
*[`cmd/cored/init.go` line 48 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uZbw45azqkl-hWXNc:-N7uZbw51aELRed7RkPC:b-5m9y4t) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/init.go#L48)):*
> ```Go
> 			// Get bip39 mnemonic
> 			var mnemonic string
> 			isRecover, _ := cmd.Flags().GetBool(FlagRecover)
> ```

do we really want to just ignore second value returned (err) ?
___
*[`cmd/cored/init.go` line 100 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ua2F8E_vrJW9oz_ML:-N7ua2F8E_vrJW9oz_MM:bitzv7m) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/init.go#L100)):*
> ```Go
> 	cmd.Flags().String(flags.FlagChainID, string(app.DefaultChainID), "genesis file chain-id, if left blank will be randomly created")
> 	cmd.Flags().BoolP(FlagOverwrite, "o", false, "overwrite the genesis.json file")
> 	cmd.Flags().Bool(FlagRecover, false, "provide seed phrase to recover existing key instead of creating")
> ```

minor: shouldn't we provide shorthand for FlagRecover also in the same way as it is done for overwrite
___
*[`cmd/cored/main.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7b1Opr4Kt8v7SaY1oz:-N7uhO7Y0X7fJbtYobUF:b-ft3eif) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/main.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I argued in previous comment to remove these commands, if we decide not to remove them, then they should be included here for sure.
</blockquote></details>

I nee more context for this one
___
*[`cmd/cored/main.go` line 37 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uh7wt6uJu5gRJXgeS:-N7uh7wt6uJu5gRJXgeT:bt5xr8u) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/main.go#L37)):*
> ```Go
> 
> 	for _, cmd := range rootCmd.Commands() {
> 		if isStringInList(cmd.Name(), "start", "collect-gentxs") {
> ```

can we use https://github.com/samber/lo
___
*[`cmd/cored/main.go` line 51 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uhDeV6967k6k9vtlM:-N7uhDeV6967k6k9vtlN:b-pkw9cc) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/main.go#L51)):*
> ```Go
> }
> 
> func isStringInList(str string, list ...string) bool {
> ```

can you put TODO to replace this func with https://github.com/samber/lo once we start using 1.18+
___
*[`cmd/cored/main.go` line 64 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uhk8s0LFYdYYEWaeF:-N7uhk8s0LFYdYYEWaeG:b1v8q03) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/main.go#L64)):*
> ```Go
> 	network, err := app.NetworkByChainID(app.ChainID(chainID))
> 	if err != nil {
> 		return errors.Errorf("error processing chain-id=%s", chainID)
> ```

shouldn't we wrap err returned from NetworkByChainID in return 
Currently you build custom error but I would stick to wrap [...]

2022-07-26 13:51 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 5 of 9 files reviewed, 28 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`cmd/cored/main.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7b-HdJ1v5IKXEiuwZg:-N7ulansBxMUxq5JWWBb:bvekiby) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/main.go#L37)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

For `add-genesis-account` we can add the flag directly to the command since we have copied it in `cosmoscmd` package. But I would argue that all these commands should be removed, now that we only want to support preconfigured networks. What do you think ?
</blockquote></details>

To discuss on the call
___
*[`cmd/cored/main.go` line 37 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uh7wt6uJu5gRJXgeS:-N7ulZd15GrSQRLo-Xe3:bwbelgb) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/main.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we use https://github.com/samber/lo
</blockquote></details>

not relevant


<!-- Sent from Reviewable.io -->

2022-07-26 14:54 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 5 of 9 files reviewed, 10 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 18 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uR2HY3qb7NnmzaGJP:-N7um0Ac0N01qYUERidK:b-i2t7mn) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/go.mod#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

We were using zap everywhere before

I don't mind using zerolog or zap. actually it is probably worth checking the difference between 2. But we should probably stick to a single logger everywhere

WDYT ?
</blockquote></details>

we are using zap in crust, but all over cosmos sdk code zero log is used by default. However they are using an interface and we can write an implementation backed by zap. But I think it is beyond the scope of this PR.
___
*[`app/network.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uS1mA5g9TgLcVJR5d:-N7umRd-BDBWZ55e77lw:b-obf9k0) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/network.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

non blocking:

I'm just thinking what if we decide to move our devnet to other server and IP changes ?
will this force all users to update to a newer version ?

This solution is fine for now but as for long-running solution we should probably use some domain or have smth better here

What are your thoughts/plan on this ?
</blockquote></details>

It will force them to update the binary. I asked Artem to provide a url for this but I think he has been busy. I will ask again. It is definitely better not use IP addresses and I will try to replace it.
___
*[`app/node_config.go` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uUMi50mCvSXo0b_8Y:-N7unDMxEmrSbep5Zw9y:b7tajnw) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor
I think using copy is more idiomatic way but I don't insist

```
NodeKey:        make([]byte{}, len(nc.NodeKey))
// ...
copy(copied.NodeKey, nc.NodeKey)
```
</blockquote></details>

it actually is. but I thought performance is not that important here.
___
*[`app/node_config.go` line 76 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uYb5j2-ApyFTEefIr:-N7upSHp71eHM8lVe0yO:b-328jvy) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L76)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it really apply tendermint config ?
I actually struggle to understand this method logic fully
</blockquote></details>

There are some tendermint configuration  (in config.toml) file that znet might want to modify. it is also possible to modify them via flags.
___
*[`cmd/cored/init.go` line 48 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uZbw45azqkl-hWXNc:-N7uuU8cCbwkGUaC8VPS:b-hkxjgo) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/init.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really want to just ignore second value returned (err) ?
</blockquote></details>

Done. Now checking the error. Although it was ignored in cosmos sdk code.
___
*[`cmd/cored/init.go` line 100 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ua2F8E_vrJW9oz_ML:-N7uupxS0cFPGWyl_l75:b-69jf8z) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/init.go#L100)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: shouldn't we provide shorthand for FlagRecover also in the same way as it is done for overwrite
</blockquote></details>

Shorthand is there as `-o` option.
___
*[`cmd/cored/main.go` line 51 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uhDeV6967k6k9vtlM:-N7uw47L1CQ-wezg0NOa:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/main.go#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you put TODO to replace this func with https://github.com/samber/lo once we start using 1.18+
</blockquote></details>

Done.
___
*[`cmd/cored/main.go` line 64 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uhk8s0LFYdYYEWaeF:-N7uw9llAlAUfe6D2lV8:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/main.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we wrap err returned from NetworkByChainID in return 
Currently you build custom error but I would stick to wrapping err with extra context 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 14:55 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 4 of 10 files reviewed, 9 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/node_config.go` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uUMi50mCvSXo0b_8Y:-N7v-Lk2A1y00Dhr9oqF:bvbrl38) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L40)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it actually is. but I thought performance is not that important here.
</blockquote></details>

fixed to use copy instead


<!-- Sent from Reviewable.io -->

2022-07-26 14:57 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 4 of 10 files reviewed, 9 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/node_config.go` line 76 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uYb5j2-ApyFTEefIr:-N7v-YNt24UuG6Rn4JJ4:bqkq2on) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L76)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

There are some tendermint configuration  (in config.toml) file that znet might want to modify. it is also possible to modify them via flags.
</blockquote></details>

to give you an example. `Seeds` is a tendermint config which decides which peers to try to connect.


<!-- Sent from Reviewable.io -->

2022-07-27 13:39 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 18 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uR2HY3qb7NnmzaGJP:-N7zrJEh424gdxWzWsmE:b-pi3t8w) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/go.mod#L18)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we are using zap in crust, but all over cosmos sdk code zero log is used by default. However they are using an interface and we can write an implementation backed by zap. But I think it is beyond the scope of this PR.
</blockquote></details>

Fine for me
___
*[`app/network.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uS1mA5g9TgLcVJR5d:-N7zrOwL-sb-HOvvb02m:b-4x4lfi) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/network.go#L91)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It will force them to update the binary. I asked Artem to provide a url for this but I think he has been busy. I will ask again. It is definitely better not use IP addresses and I will try to replace it.
</blockquote></details>

ok do keep it as it is
just wanted to make sure we have plan for the future
___
*[`app/node_config.go` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uUMi50mCvSXo0b_8Y:-N7zrZ7m4Xv5U1rJfwXh:bvt8c11) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L40)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

fixed to use copy instead
</blockquote></details>

Ok
Resolving   but I think it would be better to either don't initialize it with empty slices (just skip these fields) in `NodeConfig{ ... }` or put make right away there so `NodeConfig { SeedPeers:      make([]string, len(nc.SeedPeers))`
___
*[`app/node_config.go` line 76 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uYb5j2-ApyFTEefIr:-N7zs3B07KI8RCIW65QS:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L76)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

to give you an example. `Seeds` is a tendermint config which decides which peers to try to connect.
</blockquote></details>

ok
___
*[`cmd/cored/init.go` line 100 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ua2F8E_vrJW9oz_ML:-N7zsM_Q2io6O9-3ukWC:b-28qucs) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/init.go#L100)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Shorthand is there as `-o` option.
</blockquote></details>

ok 
maybe I misunderstood smth
I thought -o sets FlagOverwrite and we don't have one for FlagRecover
___
*[`cmd/cored/init.go` line 69 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7zsB5N3e-_46j9p4bc:-N7zsB5N3e-_46j9p4bd:b-byi41) ([raw file](https://github.com/coreumfoundation/coreum/blob/5496e733dd26e206af42c1a89b59c63215020719/cmd/cored/init.go#L69)):*
> ```Go
> 
> 			genFile := config.GenesisFile()
> 			overwrite, _ := cmd.Flags().GetBool(FlagOverwrite)
> ```

non blocking:

do we really want to just ignore second value returned (err) ?
___
*[`cmd/cored/main.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7b-HdJ1v5IKXEiuwZg:-N7uyNo_BwO7T4-Ahlfs:budyd7) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/cmd/cored/main.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

To discuss on the call
</blockquote></details>

as discussed on the call lets remove it


<!-- Sent from Reviewable.io -->

2022-07-27 13:40 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-28 10:24 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 4 of 18 files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 18 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uR2HY3qb7NnmzaGJP:-N83K_5J30gj8nK7xaDL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/go.mod#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Fine for me
</blockquote></details>

Done.
___
*[`app/node_config.go` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7uUMi50mCvSXo0b_8Y:-N82nx-n-Yi7LKNoHmSK:bjfbtr2) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/app/node_config.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Ok
Resolving   but I think it would be better to either don't initialize it with empty slices (just skip these fields) in `NodeConfig{ ... }` or put make right away there so `NodeConfig { SeedPeers:      make([]string, len(nc.SeedPeers))`
</blockquote></details>

Great suggestion. done.
___
*[`cmd/cored/init.go` line 100 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7ua2F8E_vrJW9oz_ML:-N82oIj_4GmdmqHPOZgz:b-f9g8tg) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec859bb67801dcd44e4164b9cb67ba420e437c8d/cmd/cored/init.go#L100)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok 
maybe I misunderstood smth
I thought -o sets FlagOverwrite and we don't have one for FlagRecover
</blockquote></details>

you did not misuderstand, I did :) . flag recover does not have a short hand in the original init command as well. so I decided not to have it here as well. 


<!-- Sent from Reviewable.io -->

2022-08-01 07:28 UTC, wojtek-coreum requested changes
> Reviewed 2 of 7 files at r2, 9 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 13 of 18 files reviewed, 16 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 194 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7anLCt-Y1SADm1YK_c:-N8N6fsn-YXKLhQNgC_6:b-igakvo) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L194)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done
</blockquote></details>

If you decided to add `Clone` for `NodeConfig`, could you do the same for `c.Fee`?
___
*[`app/network.go` line 229 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N76k-3Us2QyUTpQL5:-N8N76k-3Us2QyUTpQL6:bc3m38e) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L229)):*
> ```Go
> 
> // NodeConfig returns NodeConfig
> func (n *Network) NodeConfig() *NodeConfig {
> ```

Why `*NodeConfig` is returned instead of `NodeConfig`?
___
*[`app/network.go` line 170 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N6KcgCpNK_RyiYP9Z:-N8N6Kch0Y5k42qJPiIu:b-71tccv) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/network.go#L170)):*
> ```Go
> 	fee           FeeConfig
> 	nodeConfig    NodeConfig
> 	enabled       bool
> ```

Do we need it here? `New` could just panic or return an error if network config with `Enabled == false` is passed.
___
*[`app/network.go` line 229 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N7H6x1M-zPfKFe7Wx:-N8N7H6x1M-zPfKFe7Wy:b-9nju8y) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/network.go#L229)):*
> ```Go
> 
> // Enabled shows whether a network is enabled or not
> func (n *Network) Enabled() bool {
> ```

Like I described in another comment, it should not be possible to create disabled network in the first place.
___
*[`app/network.go` line 242 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N7UaW1A_MK1ns7For:-N8N7UaW1A_MK1ns7Fos:b43egxz) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/network.go#L242)):*
> ```Go
> 
> // ResetGenesisTxs resets genesis list to empty
> func (n *Network) ResetGenesisTxs() {
> ```

Why is it needed? If it's for `znet` then it should be done in different way. `znet` should just create its own `NetworkConfig` object and create network out of it, not by doing magic on top of existing network.
___
*[`app/node_config.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N8CjF3DvhzwnmBcmV:-N8N8CjG7DhqZ8K_goDM:b-7a2bh7) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L18)):*
> ```Go
> 
> // DefaultNodeConfigPath is the default path there the config.toml is saved
> var DefaultNodeConfigPath = filepath.Join("config", "config.toml")
> ```

Do we ever plan to use different path anywhere? If not, maybe use unexported constant?
___
*[`app/node_config.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N91Oa0lHptOL7GDoL:-N8N91ObAG3YrvLgQoak:b-u84i8g) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L32)):*
> ```Go
> // are copied as immutable.
> func (nc NodeConfig) Clone() NodeConfig {
> 	copied := NodeConfig{
> ```

`nc` is received by value here so `Name` and `PrometheusPort` fields are already copied for you.
So you need just this:

```
nc.NodeKey = 
nc.ValidatorKey = 
nc.SeedPeers = 
```

Also, I would use `append` instead of `copy` to make  copy in one line, but I'm not insisting on it.
___
*[`app/node_config.go` line 99 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NAVw1271DPC_Qb2rj:-N8NAVw28WWE67J7QsfB:bugux70) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L99)):*
> ```Go
> 
> // WriteTendermintConfigToFile saves tendermint config to file
> func WriteTendermintConfigToFile(filePath string, cfg *config.Config) error {
> ```

Could you change the sequence of parameters? `(cfg, filePath)`. It's more natural because you say "It saves config into a file", so config goes first in this sentence.
___
*[`app/node_config.go` line 101 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NA6NAEFPSD4uulIaY:-N8NA6NAEFPSD4uulIaZ:b-rtr8iw) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L101)):*
> ```Go
> func WriteTendermintConfigToFile(filePath string, cfg *config.Config) error {
> 	dir := filepath.Dir(filePath)
> 	if _, err := os.Stat(dir); os.IsNotExist(err) {
> ```

This block may be replaced by

```go
if err := os.MkdirAll(dir, 0o700); err != nil {
  return errors.WithStack(err)
}
```

`MkdirAll` checks atomically that dir does not exist and creates it. If it exists it **does not** return an error.
___
*[`cmd/cored/init.go` line 80 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NBIfw4KeyxmDvU39N:-N8NBIfw4KeyxmDvU39O:bnecrjh) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/init.go#L80)):*
> ```Go
> 			}
> 
> 			if !network.Enabled() {
> ```

Continuing on "enabled" here: In this case `NetworkByChainID` (and going down the call stack, `New` should do it) should just return this error once for all.
___
*[`cmd/cored/main.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NCGep89PbQNNdM6qr:-N8NCGep89PbQNNdM6qs:bf422wz) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/main.go#L49)):*
> ```Go
> }
> 
> func checkChainIDNotMain(cmd *cobra.Command, args []string) error {
> ```

rename `checkChainIDNotMain` to sth better, because every network might be disabled, not only mainnet
___
*[`cmd/cored/main.go` line 56 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NCK4A3Pb0NLe_jyKi:-N8NCK4A3Pb0NLe_jyKj:b-7ropln) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/main.go#L56)):*
> ```Go
> 	}
> 
> 	if !network.Enabled() {
> ```

ditto
___
*[`cmd/cored/preprocess_flags.go` line 22 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NCqwMENFX05gMU4CB:-N8NCqwMENFX05gMU4CC:b-u5xnas) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/preprocess_flags.go#L22)):*
> ```Go
> 	chainID := flagSet.String(flags.FlagChainID, string(app.DefaultChainID), "The network chain ID")
> 	//nolint:errcheck // since we have set ExitOnError on flagset, we don't need to check for errors here
> 	flagSet.Parse(os.Args[1:])
> ```

Minor: if you do `_ = flagSet.Parse(...)` you won't need `nolint`. But comment explaining why error is ignored is still valid.
___
*[`cmd/cored/preprocess_flags.go` line 46 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NDFrY8-Xt87UaTFoh:-N8NDFrY8-Xt87UaTFoi:b-cpqkj6) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/preprocess_flags.go#L46)):*
> ```Go
> func appendStringFlag(args []string, flag string, newVal string) error {
> 	for pos, arg := range args {
> 		if !(arg == "--"+flag || strings.HasPrefix(arg, "--"+flag+"=")) {
> ```

why not: `if arg != "--"+flag && !strings.HasPrefix(arg, "--"+flag+"=") {
___
*[`cmd/cored/cosmoscmd/cosmosapp.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NHpSt4BsYW1HkwcKL:-N8NHpSt4BsYW1HkwcKM:b-rti9f3) ([raw file](https://github.com/coreumfoundati [...]

2022-08-01 10:25 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 13 of 18 files reviewed, 15 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 194 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N7anLCt-Y1SADm1YK_c:-N8NhntA5Fxg1rfeLbIJ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L194)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If you decided to add `Clone` for `NodeConfig`, could you do the same for `c.Fee`?
</blockquote></details>

Done.
___
*[`app/network.go` line 229 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N76k-3Us2QyUTpQL5:-N8Ni4Ly44XW65cz-5CM:bwom4mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/b10bb2f0e3612b2f44ce879df30e0c29d9328a93/app/network.go#L229)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why `*NodeConfig` is returned instead of `NodeConfig`?
</blockquote></details>

We want node config to be mutable so the callers can modify fields such as name.
___
*[`app/network.go` line 170 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N6KcgCpNK_RyiYP9Z:-N8NbhQa4tI4-YcCcMdz:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/network.go#L170)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we need it here? `New` could just panic or return an error if network config with `Enabled == false` is passed.
</blockquote></details>

Done
___
*[`app/network.go` line 229 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N7H6x1M-zPfKFe7Wx:-N8NjN_T7KKz4xp2uH92:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/network.go#L229)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Like I described in another comment, it should not be possible to create disabled network in the first place.
</blockquote></details>

Done
___
*[`app/network.go` line 242 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N7UaW1A_MK1ns7For:-N8NjTVRBmvRqvOa_HWg:b-pektuw) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/network.go#L242)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why is it needed? If it's for `znet` then it should be done in different way. `znet` should just create its own `NetworkConfig` object and create network out of it, not by doing magic on top of existing network.
</blockquote></details>

Yes, it is for znet. I will use a custom network config then. 
___
*[`app/node_config.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N8CjF3DvhzwnmBcmV:-N8Njl3u3Npdxp2b583S:bfvzjs6) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we ever plan to use different path anywhere? If not, maybe use unexported constant?
</blockquote></details>

It is exported to znet will use the same path.
___
*[`app/node_config.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N91Oa0lHptOL7GDoL:-N8NkHyK2lvt36lrByFW:b-cmcv9z) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`nc` is received by value here so `Name` and `PrometheusPort` fields are already copied for you.
So you need just this:

```
nc.NodeKey = 
nc.ValidatorKey = 
nc.SeedPeers = 
```

Also, I would use `append` instead of `copy` to make  copy in one line, but I'm not insisting on it.
</blockquote></details>

`Name` and `PrometheusPort` can be copied by doing `copied := nc` and then overwriting the parts that are mutable. but i think that is less intention specific to first copy and then overwrite some fields.
___
*[`app/node_config.go` line 99 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NAVw1271DPC_Qb2rj:-N8NnJzv9QxA-_1fGxtc:bfkbgy) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you change the sequence of parameters? `(cfg, filePath)`. It's more natural because you say "It saves config into a file", so config goes first in this sentence.
</blockquote></details>

I disagree that changing input orders are more natural. 
firstly the original function which is wrapped uses the same sequence, secondly it is conformant to the way std is doing it. for example we have `os.WriteFile(path,content)`
___
*[`app/node_config.go` line 101 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NA6NAEFPSD4uulIaY:-N8NoO3JAWujKbY9sxA3:b-zdqotz) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L101)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This block may be replaced by

```go
if err := os.MkdirAll(dir, 0o700); err != nil {
  return errors.WithStack(err)
}
```

`MkdirAll` checks atomically that dir does not exist and creates it. If it exists it **does not** return an error.
</blockquote></details>

good catch. fixed.
___
*[`cmd/cored/init.go` line 80 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NBIfw4KeyxmDvU39N:-N8NurlJ2TtUZ5ocEJ-n:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/init.go#L80)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Continuing on "enabled" here: In this case `NetworkByChainID` (and going down the call stack, `New` should do it) should just return this error once for all.
</blockquote></details>

Done.
___
*[`cmd/cored/main.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NCGep89PbQNNdM6qr:-N8Nv-ub8kramZaeNAgz:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/main.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

rename `checkChainIDNotMain` to sth better, because every network might be disabled, not only mainnet
</blockquote></details>

Done.
___
*[`cmd/cored/main.go` line 56 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NCK4A3Pb0NLe_jyKi:-N8Nv-WM7aU-TwHrx-s0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/main.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`cmd/cored/preprocess_flags.go` line 46 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NDFrY8-Xt87UaTFoh:-N8NvBDu7tmHpslmdR7F:bza6h6x) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/preprocess_flags.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why not: `if arg != "--"+flag && !strings.HasPrefix(arg, "--"+flag+"=") {
</blockquote></details>

I think this would need more mental processing since it invloves more logics.
___
*[`cmd/cored/cosmoscmd/cosmosapp.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NHpSt4BsYW1HkwcKL:-N8NvLyO092V-8J7WDOF:bh1q9cv) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0 [...]

2022-08-01 13:58 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 13 of 18 files reviewed, 7 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 151 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8Of77m-YSIXbsi4FKQ:-N8Of77m-YSIXbsi4FKR:b-epm4ot) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/network.go#L151)):*
> ```Go
> // Clone creates a copy of FeeConfig to allow to pass by reference
> func (f FeeConfig) Clone() FeeConfig {
> 	return FeeConfig{
> ```

`f` already contains a copy of most of the fields. You need to only set a copy of `InitialGasPrice` and `MinDiscountedGasPrice` there
___
*[`app/network.go` line 394 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8Oew7J0d1rAM024QgU:-N8Oew7K8z8eQpAp_th0:bvzgr7h) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/network.go#L394)):*
> ```Go
> 	}
> 
> 	if !nw.Enabled {
> ```

Could it be checked inside `NewNetwork`? Because by using that constructor it's still possible to create Network from disabled NetworkConfig
___
*[`app/node_config.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8N8CjF3DvhzwnmBcmV:-N8OfpL89YZWhUsBFPUi:bp5e3w5) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/app/node_config.go#L18)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is exported to znet will use the same path.
</blockquote></details>

Non-blocking: this will be always `config/config.toml` relative to home directory so `WriteTendermintConfigToFile` could accept path to home dir instead of full file path and then append `config/config.toml` to it.
___
*[`app/node_config.go` line 102 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8OgATlBt1IuUPZtFXF:-N8OgATlBt1IuUPZtFXG:buowu3) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/node_config.go#L102)):*
> ```Go
> 	dir := filepath.Dir(filePath)
> 	if err := os.MkdirAll(dir, 0o700); err != nil {
> 		if err != nil {
> ```

Redundant `if`
___
*[`cmd/cored/main.go` line 51 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8OgUY6-RkCKyFH3uUs:-N8OgUY6-RkCKyFH3uUt:b19ecsi) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/cmd/cored/main.go#L51)):*
> ```Go
> 	chainID, _ := cmd.Flags().GetString(flags.FlagChainID)
> 	_, err := app.NetworkByChainID(app.ChainID(chainID))
> 	if err != nil {
> ```

just `return err` maybe
___
*[`cmd/cored/cosmoscmd/cosmosapp.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NHpSt4BsYW1HkwcKL:-N8OgejE1VG6_CUCNn0s:b-u38h90) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/cosmoscmd/cosmosapp.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It allows to remove the init command, later we will remove more comomands related to genesis. we will also move our own init command inside this package (we cannot do so right now because of circular dependency).

we could remove those commands the hacky way from the cmd/cored package, but it is hacky.
</blockquote></details>

But is it just a copy or you made some modifications?


<!-- Sent from Reviewable.io -->

2022-08-01 14:18 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: 13 of 18 files reviewed, 6 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 151 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8Of77m-YSIXbsi4FKQ:-N8Ok_1T1kEZkniB6iv7:b-jlx60) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/network.go#L151)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`f` already contains a copy of most of the fields. You need to only set a copy of `InitialGasPrice` and `MinDiscountedGasPrice` there
</blockquote></details>

there are only 3 fields, what do you mean that it contains most of the fields ?
___
*[`app/network.go` line 394 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8Oew7J0d1rAM024QgU:-N8OkkpAC5RhlgV_aFZm:b-3zgxhi) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/network.go#L394)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could it be checked inside `NewNetwork`? Because by using that constructor it's still possible to create Network from disabled NetworkConfig
</blockquote></details>

I would rather not to do that.
It is only a temprorary check and we will remove that field when we enable all the networks.
___
*[`app/node_config.go` line 102 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8OgATlBt1IuUPZtFXF:-N8Ol7h_3Q4ntwBeoILR:b-ppqsse) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/node_config.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Redundant `if`
</blockquote></details>

it is not really redundant though. 
___
*[`cmd/cored/main.go` line 51 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8OgUY6-RkCKyFH3uUs:-N8OkEUGABfhj2k5PSuN:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/cmd/cored/main.go#L51)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

just `return err` maybe
</blockquote></details>

Done.
___
*[`cmd/cored/cosmoscmd/cosmosapp.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8NHpSt4BsYW1HkwcKL:-N8OkHdP8M76kidDAf8d:bmq570i) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b605040c893dd0a47b19a1b9d098bdd26245544/cmd/cored/cosmoscmd/cosmosapp.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But is it just a copy or you made some modifications?
</blockquote></details>

it is just a copy


<!-- Sent from Reviewable.io -->

2022-08-01 14:38 UTC, wojtek-coreum requested changes
> Reviewed 5 of 14 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 394 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8Oew7J0d1rAM024QgU:-N8OpTebBopGWHxWHc6c:bagpcmc) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/network.go#L394)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I would rather not to do that.
It is only a temprorary check and we will remove that field when we enable all the networks.
</blockquote></details>

So please add a TODO around that field saying that it should be removed once mainnet is ready
___
*[`app/node_config.go` line 102 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8OgATlBt1IuUPZtFXF:-N8OpfN56VUPFmUPOvVV:b48rucy) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/node_config.go#L102)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is not really redundant though. 
</blockquote></details>

```go
	if err := os.MkdirAll(dir, 0o700); err != nil {
		if err != nil {
			return err
		}
	}

```
you check if `err != nil` twice


<!-- Sent from Reviewable.io -->

2022-08-01 15:09 UTC, wojtek-coreum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113#-:-N8Ox0Fp-4fE9mQpeEgq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-01 15:40 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/113)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 394 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8Oew7J0d1rAM024QgU:-N8Ow-896hXh3BLvZfCc:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/network.go#L394)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So please add a TODO around that field saying that it should be removed once mainnet is ready
</blockquote></details>

Done.
___
*[`app/node_config.go` line 102 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/113#-N8OgATlBt1IuUPZtFXF:-N8Ovi7VDNsnf_uS6_9M:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6a61d7e247ffa8fc5e9c99435c7abdd7ae3e021b/app/node_config.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

```go
	if err := os.MkdirAll(dir, 0o700); err != nil {
		if err != nil {
			return err
		}
	}

```
you check if `err != nil` twice
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-02 08:07 UTC, merged