Make client more ready for WASM contracts
CoreumFoundation/coreum pull request #123
Opened 2022-08-05 02:01 UTC by xlab

There is a list of things:
* Added keyring support (+ unit test), to init wallets using proper cosmos keyring
* Fixes to client rpc addr
* Exported bank querier (to allow querying addresses without wallets, e.g. contract addresses)
* Exported wasm queries for wasm stuff
* Added dynamic gas simulation query
* Exposed EventLogs from the Tx results

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/coreum/123)

2022-08-05 08:28 UTC, wojtek-coreum requested changes
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 4 of 11 files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h5PDT9_goecNg-Mck:-N8h5PDT9_goecNg-Mcl:b-95wz9b) (no related file):*
Related to `test_fixtures/keyring-file`):

Let's use underscores in file names everywhere, it's forced by `*_test.go` and by the fact that directories containing `-` can't be imported as packages. Mixing both `_` and `-` seems weird.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h68hl9hjJJVQe1E9H:-N8h68hl9hjJJVQe1E9I:bvde5kg) (no related file):*
I'm completely against instroducing keyring concept. This tool is just for development. User may just provide a path to the file containing the key. We don't need to support all the keyring types. Let's discuss after daily.
Because of that I'm not reviewing this part until we discuss it.

___
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsKS5DZp30NtuuhWo:-N8gsKS5DZp30NtuuhWp:b-4outc) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L47)):*
> ```Go
> 		strings.HasPrefix(addr, "https://"):
> 	default:
> 		addr = "http://" + addr
> ```

Please return an error here. Caller should be required to provide correct protocol. If it's not enforced the typos like `htp://` made by users will create weird errors down the call stack, instead of one providing clear explanation.
___
*[`pkg/client/client.go` line 141 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsxeKE6LDBTD-T4j8:-N8gsxeKE6LDBTD-T4j9:b8wp67x) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L141)):*
> ```Go
> 	TxHash    string
> 	GasUsed   int64
> 	EventLogs sdk.StringEvents
> ```

This breaks the type encapsulation. We decided that client should not expose cosmos sdk types. If you want to provide arguments against this decision, let's discuss it during the daily.
___
*[`pkg/client/client.go` line 217 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h-RnOAQZuLL2IbThN:-N8h-RnOAQZuLL2IbThO:bt2jmrr) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L217)):*
> ```Go
> // EstimateGas runs the transaction cost estimation and returns new suggested gas limit,
> // in contrast with the default Cosmos SDK gas estimation logic, this method returns unadjusted gas used.
> func (c Client) EstimateGas(ctx context.Context, input tx.BaseInput, msgs ...sdk.Msg) (uint64, error) {
> ```

To conform to the design of the other parts of the client, logic of this method (and probably calling code) should be separated into three different methods:
- `Prepare*` (like `PrepareTxBankSend`) which takes arguments required by smart contract message and returns `[]byte` containing encoded transaction.
- `SimSign` (like `Sign`) signing the transaction
- `EstimateGas` (like `Broadcast`) taking `[]byte` containing signed transaction and sending it for estimation.

Notes:
- In current version `EstimateGas` accepts cosmos type as an argument, which we decided to avoid, that's why it needs to be redone
- It should be possible to reuse `EstimateGas` for any message, that's why it should cooperate with values returned from all `Prepare*` functions (currently there is only one, but in the future we will have more). Probably this PR should introduce one for smart contracts.
- I know that `PrepareTxBankSend` calls `Sign` internally, it needs to be redesigned so it's possible to support both sign types (for broadcast and gas estimation) for all types of transactions. It was done like that because I didn't know at that time that other way of signing might be needed. It means that we need to find a better way of handling this situation now, not just ignore the problem. We need to discuss in a team how it might be approached. 
- I also know that `Prepare*` methods are designed to return `authsigning.Tx` at the moment which is against the encapsulation rule we set earlier. It's a bug, not a feature, coming from early days of this client. I will find a way to fix this. Please don't use it as an argument to allow that kind of leakage in other places.
___
*[`pkg/client/client.go` line 219 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gvFKm-M2x3JZuZQg8:-N8gvFKm-M2x3JZuZQg9:bq0jrx7) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L219)):*
> ```Go
> func (c Client) EstimateGas(ctx context.Context, input tx.BaseInput, msgs ...sdk.Msg) (uint64, error) {
> 	signer := input.Signer
> 	if signer.AccountNumber == 0 && signer.AccountSequence == 0 {
> ```

This logic is copy-pasted from `Sign` method. Please encapsulate it in separate function and reuse in both places.
___
*[`pkg/client/client.go` line 236 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gyqfa4_8GTlazxuTs:-N8gyqfa4_8GTlazxuTt:b9tzbgs) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L236)):*
> ```Go
> 
> 	txSvcClient := txtypes.NewServiceClient(c.clientCtx)
> 	simRes, err := txSvcClient.Simulate(ctx, &txtypes.SimulateRequest{
> ```

Please create new context with timeout instead of passing `ctx` directly, like this:

```go
requestCtx, cancel := context.WithTimeout(ctx, requestTimeout)
defer cancel()
```

It is important to assign reasonable timeout to all networking operations. Otherwise it might hang forever.
___
*[`pkg/client/client.go` line 244 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gzMV_6_6kMBC5sdiL:-N8gzMV_6_6kMBC5sdiM:b-zddqkf) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L244)):*
> ```Go
> 	}
> 
> 	// usually gas has to be multiplied by some adjustment coeff: e.g. *1,5
> ```

coeff -> coefficient

1,5 -> 1.5
___
*[`pkg/client/client.go` line 246 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gzXHW9IZDcKY1UrU2:-N8gzXHW9IZDcKY1UrU3:bplp80v) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L246)):*
> ```Go
> 	// usually gas has to be multiplied by some adjustment coeff: e.g. *1,5
> 	// but in this case we return unadjusted, so every module can decide the adjustment value
> 	unadjustedGas := simRes.GasInfo.GasUsed
> ```

Non-blocking: It's so simple that could be moved to `return` statement
___
*[`pkg/client/client.go` line 287 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8guFAk-gI2NO9S4ITF:-N8guFAk-gI2NO9S4ITG:bzhmnx8) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L287)):*
> ```Go
> // using the internal clientCtx.
> func (c Client) BankQueryClient() banktypes.QueryClient {
> 	return c.bankQueryClient
> ```

This should not be exposed. According to earlier decisions, full logic of interacting with the external service should be implemented directly in the client instead.
___
*[`pkg/client/client.go` line 293 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8guh4u0DEbWN38pCC6:-N8guh4u0DEbWN38pCC7:bzhmnx8) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L293)):*
> ```Go
> // using the internal clientCtx.
> func (c Client) WASMQueryClient() wasmtypes.QueryClient {
> 	return c.wasmQueryClient
> ```

This should not be exposed. According to earlier decisions, full logic of interacting with the external service should be implemented directly i [...]

2022-08-05 08:30 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 4 of 11 files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h5PDT9_goecNg-Mck:-N8h6xm49w62rRacvnRS:b-gt98it) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Related to `test_fixtures/keyring-file`):

Let's use underscores in file names everywhere, it's forced by `*_test.go` and by the fact that directories containing `-` can't be imported as packages. Mixing both `_` and `-` seems weird.
</blockquote></details>

sorry, actually packages containing `-` might be imported.

___


<!-- Sent from Reviewable.io -->

2022-08-05 16:28 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h5PDT9_goecNg-Mck:-N8ipLka6LqURYVLGiX6:bx3o72z) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

sorry, actually packages containing `-` might be imported.
</blockquote></details>

`keyring-file` is an internal keychain representation from Cosmos SDK, I didn't create that dir.




<!-- Sent from Reviewable.io -->

2022-08-05 16:31 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h68hl9hjJJVQe1E9H:-N8ipbVF1d5pzh7BqDEp:b-ey1elu) (no related file):*
> User may just provide a path to the file containing the key. 

The file is inside Cosmos keyring and is a bit cumbersome to work with. The keyring package I'm adding simplifies the flow of instantiating the Cosmos keyring.

Also, you keep forgetting that every sane user would prefer to use Ledger or other hardware wallet, not having them hardcoded or provided as files.

The original Cosmos keyring solves many problems and has multiple backends, allowing cross-OS flexibility. We just introduced a simpler constructor there for that keyring flow.




<!-- Sent from Reviewable.io -->

2022-08-05 16:36 UTC, xlab commented
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsKS5DZp30NtuuhWo:-N8iqFNu0ibl2D7MaJaF:b9z3r7w) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please return an error here. Caller should be required to provide correct protocol. If it's not enforced the typos like `htp://` made by users will create weird errors down the call stack, instead of one providing clear explanation.
</blockquote></details>

I've already explained that in other PR. Weird typos will generate weird errors. Enforcing the schema will break the current interface of the client and I don't want to revise all other scripts and code that uses it incorrectly (having host without schema).

To check `htp://` and IP dresses to avoid `34.332.363.777` etc -  is not a responsibility of this package.


<!-- Sent from Reviewable.io -->

2022-08-05 16:38 UTC, xlab commented
*[`pkg/client/client.go` line 141 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsxeKE6LDBTD-T4j8:-N8irN4Y54sQPI7-T5dF:b-cvwjk5) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L141)):*
> We decided that client should not expose cosmos sdk types

That's a bad decision, and will lead to more problems in the future.


<!-- Sent from Reviewable.io -->

2022-08-05 16:40 UTC, xlab commented
*[`pkg/types/types.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h46Tu-YVVUePSBBvF:-N8isHQt-W-mm49Lg1Ai:b-ry91ny) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/types/types.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`sdk.AccAddress` should not be exposed
</blockquote></details>

It's a bad idea to keep reinventing SDK and all its types, trying to wrap them. Just a waste of time. And will not work eventually.


<!-- Sent from Reviewable.io -->

2022-08-05 16:42 UTC, xlab commented
*[`pkg/types/types.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h4RpYElQbh9UN4zxZ:-N8isTpb-ozir3pIYuSr:b-1uaiqk) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/types/types.go#L41)):*
> This entire code (Wallet, Client etc.) was never intended to be used as any kind of professional, production-ready 

Yes, and we keep developing it. It looks like our entire codebase will never be intended to be used as any kind of professional, production-ready, or anything else, except have battles in PR reviews.


<!-- Sent from Reviewable.io -->

2022-08-05 17:02 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 4 of 11 files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsKS5DZp30NtuuhWo:-N8iwYaq2R23hrsQw3ER:b-u1e12t) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L47)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I've already explained that in other PR. Weird typos will generate weird errors. Enforcing the schema will break the current interface of the client and I don't want to revise all other scripts and code that uses it incorrectly (having host without schema).

To check `htp://` and IP dresses to avoid `34.332.363.777` etc -  is not a responsibility of this package.
</blockquote></details>

Did you check in how many places `New` is called?


<!-- Sent from Reviewable.io -->

2022-08-08 15:26 UTC, xlab commented
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsKS5DZp30NtuuhWo:-N8y39KRCOWwksyq8oAJ:b5w0b1f) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Did you check in how many places `New` is called?
</blockquote></details>

It's used as a part of CLI commands and accept dynamic variables from TF, etc


<!-- Sent from Reviewable.io -->

2022-08-08 15:27 UTC, xlab commented
*[`pkg/client/client.go` line 219 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gvFKm-M2x3JZuZQg8:-N8y3IcEETD-BNkSquSv:b-tx3648) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L219)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This logic is copy-pasted from `Sign` method. Please encapsulate it in separate function and reuse in both places.
</blockquote></details>

Encapsulate a single `if` statement?


<!-- Sent from Reviewable.io -->

2022-08-08 15:28 UTC, xlab commented
*[`pkg/client/client.go` line 219 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gvFKm-M2x3JZuZQg8:-N8y3Ll77C1sTuJ4K4vq:b-yhlukq) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L219)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Encapsulate a single `if` statement?
</blockquote></details>

I think the Sign and other methods exposed by clients are designed poorly, so I am not focusing on re-structuring the client in this PR. I am adding a part that is needed for things to work. The Client will be refactored later, you specifically said it's not production ready yet.


<!-- Sent from Reviewable.io -->

2022-08-08 15:29 UTC, xlab commented
*[`pkg/client/client.go` line 246 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gzXHW9IZDcKY1UrU2:-N8y3emI4tSu8rSC-JXj:b-k1p63m) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L246)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: It's so simple that could be moved to `return` statement
</blockquote></details>

It's written this way to boost the significance of the fact that this is unadjusted gas value.


<!-- Sent from Reviewable.io -->

2022-08-08 15:30 UTC, xlab commented
*[`pkg/client/client.go` line 287 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8guFAk-gI2NO9S4ITF:-N8y3oXD35453bdaFxst:bkzlv5b) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L287)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This should not be exposed. According to earlier decisions, full logic of interacting with the external service should be implemented directly in the client instead.
</blockquote></details>

Maybe , but current BankQuery methods of the clients are poorly designed and require to pass a private key of a wallet, to know its balance.


<!-- Sent from Reviewable.io -->

2022-08-08 15:33 UTC, xlab commented
*[`pkg/client/client.go` line 293 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8guh4u0DEbWN38pCC6:-N8y42inEh8jmuYGOMiX:b-dia9m2) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L293)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This should not be exposed. According to earlier decisions, full logic of interacting with the external service should be implemented directly in the client instead.
</blockquote></details>

That means client API surface grows too big, implementing every module's niche use cases, it will be useless. What we need there is a  client that initializes the context (tm RPC connection with chain settings) and allows to submit msgs and query data..

We don't need a monster API that knows about everything about every Cosmos module. And you can see that `wasmtypes.QueryClient` is actually an interface, so it doesn't bound the Client to a particular impementation.


<!-- Sent from Reviewable.io -->

2022-08-08 15:34 UTC, xlab commented
*[`pkg/client/client.go` line 297 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gtda5DK06iUoAd-gh:-N8y4iYcCRwCcgwb4IBf:b-o886ym) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L297)):*
They are valuable because they are generic but still useful. It allows us to learn about how events are structured, and maybe later we will implement an intelligent parsing that highlights only important logs.

>  for now I just don't like that for single transaction many log lines containing those events are printed.

You can set the logging level to `warn` 


<!-- Sent from Reviewable.io -->

2022-08-08 15:36 UTC, xlab commented
*[`pkg/client/client.go` line 217 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h-RnOAQZuLL2IbThN:-N8y5HRFA6OIzXlyXoz-:b-x6fpg) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L217)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To conform to the design of the other parts of the client, logic of this method (and probably calling code) should be separated into three different methods:
- `Prepare*` (like `PrepareTxBankSend`) which takes arguments required by smart contract message and returns `[]byte` containing encoded transaction.
- `SimSign` (like `Sign`) signing the transaction
- `EstimateGas` (like `Broadcast`) taking `[]byte` containing signed transaction and sending it for estimation.

Notes:
- In current version `EstimateGas` accepts cosmos type as an argument, which we decided to avoid, that's why it needs to be redone
- It should be possible to reuse `EstimateGas` for any message, that's why it should cooperate with values returned from all `Prepare*` functions (currently there is only one, but in the future we will have more). Probably this PR should introduce one for smart contracts.
- I know that `PrepareTxBankSend` calls `Sign` internally, it needs to be redesigned so it's possible to support both sign types (for broadcast and gas estimation) for all types of transactions. It was done like that because I didn't know at that time that other way of signing might be needed. It means that we need to find a better way of handling this situation now, not just ignore the problem. We need to discuss in a team how it might be approached. 
- I also know that `Prepare*` methods are designed to return `authsigning.Tx` at the moment which is against the encapsulation rule we set earlier. It's a bug, not a feature, coming from early days of this client. I will find a way to fix this. Please don't use it as an argument to allow that kind of leakage in other places.
</blockquote></details>

Sounds cool, but refactoring of the client is not a goal of this PR, so the comment is irrelevant.


<!-- Sent from Reviewable.io -->

2022-08-08 15:39 UTC, xlab commented
*[`pkg/tx/sign.go` line 82 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gxUxxCqJvVf9qPFyd:-N8y5tXM5EpuLLWKhUiw:boqohk5) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/tx/sign.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I didn't know this approach of using factory and `BuildUnsignedTx`, when I wrote `Sign` function. Your approach looks better to me, please move the same logic there for consistency. Because it is identical in both places, please encapsulate it in a function and reuse in both places.
</blockquote></details>

Refactoring of the client is not a goal of this PR, so the comment is irrelevant.

You can learn many cool stuff by looking at what's already implemented in Cosmos SDK.


<!-- Sent from Reviewable.io -->

2022-08-08 15:40 UTC, xlab commented
*[`pkg/types/types.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h4Vdg0QpU5iiQ-kaV:-N8y65j97w5Ol-eBuRDn:bjtu708) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/types/types.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This function also accepts sdk types as arguments
</blockquote></details>

Like many other places in the client before this PR. Let's solve type issues once for all, but when the proper abstractions are introduced. Replacing an address with a struct containing a private key is not OK.


<!-- Sent from Reviewable.io -->

2022-08-08 15:46 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 4 of 11 files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`pkg/client/client.go` line 236 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gyqfa4_8GTlazxuTs:-N8y7UJyCSWEfD5Axk4D:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L236)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please create new context with timeout instead of passing `ctx` directly, like this:

```go
requestCtx, cancel := context.WithTimeout(ctx, requestTimeout)
defer cancel()
```

It is important to assign reasonable timeout to all networking operations. Otherwise it might hang forever.
</blockquote></details>

Done.
___
*[`pkg/client/client.go` line 244 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gzMV_6_6kMBC5sdiL:-N8y7GQO7SouOR4BdSwB:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L244)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

coeff -> coefficient

1,5 -> 1.5
</blockquote></details>

Done.
___
*[`pkg/tx/sign.go` line 87 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gx-IK1-TH3QZNcCDV:-N8y7ET64GehajIdWJcD:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/tx/sign.go#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please use the `signing.SignMode_SIGN_MODE_DIRECT` constant directly. Yes, you will need to put `nolint` here, it's fine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 17:01 UTC, wojtek-coreum requested changes
> Reviewed 3 of 11 files at r1, 16 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 27 of 37 files reviewed, 15 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`integration-tests/testing/types.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8yO3ZqEiMbTpsg5l93:-N8yO3ZrDSjLwuf8Ggzu:bnsenba) ([raw file](https://github.com/coreumfoundation/coreum/blob/8ef4e1ad74aed9a3f62dd74bec18b836f04ee071/integration-tests/testing/types.go#L27)):*
> ```Go
> 	Network *app.Network
> 	Client  client.Client
> 	RPCAddr string
> ```

No no no


<!-- Sent from Reviewable.io -->

2022-08-08 17:25 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 25 of 37 files reviewed, 15 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/types.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8yO3ZqEiMbTpsg5l93:-N8yTPuPB-yNwfYKZ_pX:b-grjq6d) ([raw file](https://github.com/coreumfoundation/coreum/blob/8ef4e1ad74aed9a3f62dd74bec18b836f04ee071/integration-tests/testing/types.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No no no
</blockquote></details>

No what? Please be more constructive in the PR review comments, this is not a drama theater.

As for this change I am making - to keep integration tests compatible with testing infra that was available in crust. After moving them to coreum, it was soft-locked to use only `client.Client`. But `client.Client` is nowhere ready to be used in the integration tests of WASM. It has private keys hardcoded everywhere. Refactoring `client.Client` was never part of this PR.

I know it's very convenient to introduce breaking changes that force us to rewrite many unrelated lines of code, but this PR is pretty much finished and I am moving integration tests there, not interested in refactoring everything for always changing underlying infra.


<!-- Sent from Reviewable.io -->

2022-08-08 17:45 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 19 of 37 files reviewed, 15 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`integration-tests/testing/types.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8yO3ZqEiMbTpsg5l93:-N8yYkep6-hosnODYuzN:b-3mcqzn) ([raw file](https://github.com/coreumfoundation/coreum/blob/8ef4e1ad74aed9a3f62dd74bec18b836f04ee071/integration-tests/testing/types.go#L27)):*
> No what?

Given what you wrote later in the comment, I see that you very clearly understood what my "No no no" means.


<!-- Sent from Reviewable.io -->

2022-08-08 18:02 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 19 of 37 files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybTcjBnzCsHZLXsZI:-N8h5AHp9vB8QMnJAo33:bjpyd1x) (no related file):*
Please explain what the files inside `test_fixtures/keyring-file` are for

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybXrRCX9rrxBYVB_K:-N8ybXrRCX9rrxBYVB_L:b-dfzccd) (no related file):*
I see that this PR goes to a dead end. Please let's stop for a moment and redesign client first. I stop reviewing this PR further until we prepare correct client handling new use cases.

___


<!-- Sent from Reviewable.io -->

2022-08-08 18:07 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 19 of 37 files reviewed, 18 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/tx/sign.go` line 82 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8yctPQ8vAPIbI31ZDS:-N8yctPQ8vAPIbI31ZDT:b-8ma7uv) ([raw file](https://github.com/coreumfoundation/coreum/blob/29ccbdd747435693b34ab2cc82a7c4391539dfe4/pkg/tx/sign.go#L82)):*
> ```Go
> // built.
> func BuildSimTx(clientCtx client.Context, base BaseInput, msgs ...sdk.Msg) ([]byte, error) {
> 	factory := new(clienttx.Factory).
> ```

clienttx -> clientCtx


<!-- Sent from Reviewable.io -->

2022-08-08 18:11 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 19 of 37 files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/tx/sign.go` line 92 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ydr5vAnytuOwZ7WAw:-N8ydr5vAnytuOwZ7WAx:b-4z68vv) ([raw file](https://github.com/coreumfoundation/coreum/blob/29ccbdd747435693b34ab2cc82a7c4391539dfe4/pkg/tx/sign.go#L92)):*
> ```Go
> 	txb, err := factory.BuildUnsignedTx(msgs...)
> 	if err != nil {
> 		return nil, err
> ```

add `errors.WithStack`
___
*[`pkg/tx/sign.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ydtVY0ZzlQjNDBeWx:-N8ydtVY0ZzlQjNDBeWy:b-4z68vv) ([raw file](https://github.com/coreumfoundation/coreum/blob/29ccbdd747435693b34ab2cc82a7c4391539dfe4/pkg/tx/sign.go#L112)):*
> ```Go
> 	}
> 	if err := txb.SetSignatures(sig); err != nil {
> 		return nil, err
> ```

add `errors.WithStack`


<!-- Sent from Reviewable.io -->

2022-08-08 20:15 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybTcjBnzCsHZLXsZI:-N8z56s27YU2FuN3P_6a:b-xdcun) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please explain what the files inside `test_fixtures/keyring-file` are for
</blockquote></details>

fixtures for keyring unit-tests




<!-- Sent from Reviewable.io -->

2022-08-08 20:17 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 19 of 37 files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybXrRCX9rrxBYVB_K:-N8z5JsF0A6q4Y4nKucR:b-b8zyg1) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see that this PR goes to a dead end. Please let's stop for a moment and redesign client first. I stop reviewing this PR further until we prepare correct client handling new use cases.
</blockquote></details>

I don't understand why the entire WASM team should stop, drop the work, and redesign something irrelevant to the tasks.

The client was poorly designed, that's a fact, and I agree it will be redesigned. However this is not an excuse to block this PR from merging.

@ysv, what are your thoughts on this approach?

___


<!-- Sent from Reviewable.io -->

2022-08-08 20:19 UTC, xlab commented
*[`pkg/tx/sign.go` line 82 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8yctPQ8vAPIbI31ZDS:-N8z6CqH9CPq6cy1EGkY:bz84g5f) ([raw file](https://github.com/coreumfoundation/coreum/blob/29ccbdd747435693b34ab2cc82a7c4391539dfe4/pkg/tx/sign.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

clienttx -> clientCtx
</blockquote></details>

]clienttx.Factory] is a type from package `clienttx`, unrelated to clientCtx


<!-- Sent from Reviewable.io -->

2022-08-08 20:22 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 18 of 37 files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/tx/sign.go` line 92 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ydr5vAnytuOwZ7WAw:-N8z6rrQ5zxE8w4IjuN5:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/29ccbdd747435693b34ab2cc82a7c4391539dfe4/pkg/tx/sign.go#L92)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

add `errors.WithStack`
</blockquote></details>

Done.
___
*[`pkg/tx/sign.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ydtVY0ZzlQjNDBeWx:-N8z6s5w-GohT0O9hTah:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/29ccbdd747435693b34ab2cc82a7c4391539dfe4/pkg/tx/sign.go#L112)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

add `errors.WithStack`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-09 03:25 UTC, wojtek-coreum requested changes
> Reviewed 2 of 4 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 27 of 37 files reviewed, 18 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybXrRCX9rrxBYVB_K:-N9-aud46r3HCO8Q9-7r:b-50rspw) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I don't understand why the entire WASM team should stop, drop the work, and redesign something irrelevant to the tasks.

The client was poorly designed, that's a fact, and I agree it will be redesigned. However this is not an excuse to block this PR from merging.

@ysv, what are your thoughts on this approach?
</blockquote></details>

The very first problem of this PR is that you decided to proceed by including all those "workarounds" instead of bringing the idea of redesigning the client first. Now you try to convince me to agree on including a lot of technical debt in the master saying that it will be resolved in the future. No way.

___
___
*[`go.mod` line 14 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N9-bxZh7fI6KgAkjJEM:-N9-bxZiDvRDzh17_b-c:b-dr2mjp) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/go.mod#L14)):*
> ```XML
> require (
> 	github.com/CoreumFoundation/coreum-tools v0.2.1
> 	github.com/CoreumFoundation/crust/pkg/contracts v0.0.0-20220808170449-f658d0e8b653
> ```

We agreed already that `coreum` repo must not import `crust`. As I've already written many times here. Logic for communicating with RPC client should be implemented here, in client and then `crust` should import `coreum` (it already does) and call the client in `contracts`.


<!-- Sent from Reviewable.io -->

2022-08-09 10:42 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 27 of 37 files reviewed, 26 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 81 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N917m6W7KHG7kvDdXfZ:-N917m6XBtI3MHtm8uK6:bpi5ga5) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L81)):*
> ```Go
> 	}
> 
> 	return initTestState, runTestFunc
> ```

It might be simplified:

```go
return initTestState, testBankSendContract(
			chain,
			adminWallet,
			testWallet,
			networkConfig,
			stagedContractPath,
			nativeDenom,
			nativeTokens,
)
```
___
*[`integration-tests/wasm/bank_send.go` line 81 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N919tHN1B6y6EjY0mw5:-N919tHN1B6y6EjY0mw6:b-hnjy72) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L81)):*
> ```Go
> 	}
> 
> 	return initTestState, runTestFunc
> ```

Also because of introducing those variables, test names printed in logs look like this now: `wasm.TestBankSendContract.func2`.
Please fix the code here: https://github.com/CoreumFoundation/crust/blob/master/infra/testing/types.go#L83
so not only `.func1` suffix is removed but any `.func[0-9]+`.
___
*[`integration-tests/wasm/simple_state.go` line 43 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N918J-S2C6-wKK3vrF1:-N918J-S2C6-wKK3vrF2:b-mgls62) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/simple_state.go#L43)):*
> ```Go
> 		networkConfig = contracts.ChainConfig{
> 			ChainID: string(chain.Network.ChainID()),
> 			// FIXME: Take this value from Network.InitialGasPrice() once Milad integrates it into crust
> ```

Required change has been integrated so you may apply it here
___
*[`integration-tests/wasm/simple_state.go` line 48 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N918S-u18iVpjF-5WsI:-N918S-u18iVpjF-5WsJ:b-gqp94v) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/simple_state.go#L48)):*
> ```Go
> 		}
> 
> 		// FIXME: if workdir for the test is fixed, we can avoid embedding & staging
> ```

`znet` receives an argument called `--bin-dir` which points to the `bin` directory of the repo. Once contracts are built from source and stored under that directory you may access them. But for now, embedding seems to be a good idea IMO.
___
*[`integration-tests/wasm/simple_state.go` line 58 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N918jyg2lYua-LyVgYL:-N918jyg2lYua-LyVgYM:b-htj3k0) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/simple_state.go#L58)):*
> ```Go
> 
> 		stagedContractPath = filepath.Join(stagedContractsDir, "simple_state.wasm")
> 		if err := ioutil.WriteFile(stagedContractPath, simpleStateWASM, 0600); err != nil {
> ```

It shouldn't be done by storing the file. Instead, client should accept []byte containing the smart contract and deploy it to the blockchain
___
*[`integration-tests/wasm/simple_state.go` line 87 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N9198J-Aq1pnkzJ5cKF:-N9198J-Aq1pnkzJ5cKG:b-fgnsgw) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/simple_state.go#L87)):*
> ```Go
> 		// Store the contract code on the chain, instantiation will be done in later step
> 
> 		deployOut, err := contracts.Deploy(ctx, contracts.DeployConfig{
> ```

Instead of calling code imported from `crust`, you should use `chain.Client` where method for deploying the contract should exist.
`crust contracts deply` should use the same client method imported from `coreum`.
___
*[`integration-tests/wasm/simple_state.go` line 101 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N919TVx8qjuuKEUT6t4:-N919TVx8qjuuKEUT6t5:b-6iqvwz) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/simple_state.go#L101)):*
> ```Go
> 		// so we could chech the intermediate result of code storage.
> 
> 		deployOut, err = contracts.Deploy(ctx, contracts.DeployConfig{
> ```

My personal taste is that I would prefer to have two different functions (`contracts.Deploy` and `contracts.Instantiate`). It still means that they might be called one after another in `crust contracts deploy` command without exposing those separate steps to the end user. I don't have a strong opinion on this, so I'm waiting for opinion of others.
___
*[`integration-tests/wasm/fixtures/.gitignore` line 2 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91AxKnCV45OSyEXQe_:-N91AxKnCV45OSyEXQea:b-e9ph75) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/.gitignore#L2)):*
> ```ignore
> checksums_intermediate.txt
> target
> ```

Please store the artifacts in the better-named directory, like `bin/contracts` under repo root
___
*[`integration-tests/wasm/fixtures/README.md` line 7 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91AlLmCyKqg_DD3hxi:-N91AlLmCyKqg_DD3hxj:b-9kksy4) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/README.md#L7)):*
> ```Markdown
> 
> > crust contracts build --optimized ./bank-send
> ```
> ```

could you add `crust build/test-contracts` command executing those commands? This would actually close the topic of source code recompilation


<!-- Sent from Reviewable.io -->

2022-08-09 12:10 UTC, ysv requested changes
> Reviewed 3 of 11 files at r1, 1 of 10 files at r2, 13 of 21 files at r3, 2 of 4 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 29 of 37 files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 14 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N9-bxZh7fI6KgAkjJEM:-N912Vvo0WTQb9NlEhjp:b-yy8e5x) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/go.mod#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We agreed already that `coreum` repo must not import `crust`. As I've already written many times here. Logic for communicating with RPC client should be implemented here, in client and then `crust` should import `coreum` (it already does) and call the client in `contracts`.
</blockquote></details>

This one is absolutely necessary and was a hard requirement from Reza
___
*[`integration-tests/wasm/bank_send.go` line 21 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N913NwB45-AUVLRVt1e:-N913NwB45-AUVLRVt1f:b7cz7zq) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L21)):*
> ```Go
> 
> var (
> 	//go:embed fixtures/bank-send/artifacts/bank_send.wasm
> ```

can you pls move fixtures to `integration-tests` folder so everything related to integration tests live there ?
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsKS5DZp30NtuuhWo:-N919xTS2kLHbRu4_eHm:b-fhc6gm) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L47)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's used as a part of CLI commands and accept dynamic variables from TF, etc
</blockquote></details>

I also vote for returning error here
there is not than many places were it is used 
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/TYTc3SjGfbxhIAOUE1yrAni4/image.png)
___
*[`pkg/client/client.go` line 141 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsxeKE6LDBTD-T4j8:-N918xjICMcoIpt-0c7_:b-9p0gb1) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L141)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> We decided that client should not expose cosmos sdk types

That's a bad decision, and will lead to more problems in the future.
</blockquote></details>

Our thought was to abstract client from cosmos SDK types so end user of the client doesn't need to know about cosmos SDK internals

So far we were managing to achieve this. However it might bring more drawbacks than benefits I agree. Since we are facing issues with this approach I don't mind changing my opinion on this.

Let discuss on the call
___
*[`pkg/client/client.go` line 217 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h-RnOAQZuLL2IbThN:-N91DLqQBUPkGIHYEdy7:b-xlswl7) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L217)):*
Refactoring client is not a goal of this PR but we should try to implement things as clean as possible because otherwise we will never get back to this which will end up having dirty client

> To conform to the design of the other parts of the client, logic of this method (and probably calling code) should be separated into three different methods

Sounds logical. It is sort of splitting responsibilities but might make this method inconvenient.
Needs discussion.

> In current version EstimateGas accepts cosmos type as an argument, which we decided to avoid, that's why it needs to be redone

I see Maxim's point now for using cosmos types. I'm not sure how to avoid `sdk.Msg` in this case and make it elegant. @wojtek-coreum Do you have any ideas for this ?
Needs discussion.

> I know that PrepareTxBankSend calls Sign internally, it needs to be redesigned so it's possible to support both sign types (for broadcast and gas estimation) for all types of transactions. It was done like that because I didn't know at that time that other way of signing might be needed. It means that we need to find a better way of handling this situation now, not just ignore the problem. We need to discuss in a team how it might be approached.

Needs discussion

> I also know that Prepare* methods are designed to return authsigning.Tx at the moment which is against the encapsulation rule we set earlier. It's a bug, not a feature, coming from early days of this client. I will find a way to fix this. Please don't use it as an argument to allow that kind of leakage in other places.

It also uses `sdk.Msg`. Are we still sure that we can avoid cosmos sdk types and it is a good idea ?
Needs discussion


@wojtek-coreum I can see that we use `must.Ok` which panic in various places here. I don't think it is acceptable in client
___
*[`pkg/client/client.go` line 219 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gvFKm-M2x3JZuZQg8:-N91I18kAloNpgEa2UEz:bhwc7eg) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L219)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I think the Sign and other methods exposed by clients are designed poorly, so I am not focusing on re-structuring the client in this PR. I am adding a part that is needed for things to work. The Client will be refactored later, you specifically said it's not production ready yet.
</blockquote></details>

This comment makes sense for me. These 2 pieces of code are almost identical
Needs discussion
___
*[`pkg/client/client.go` line 246 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gzXHW9IZDcKY1UrU2:-N91IrVV76JP9PNG6PJ1:bt8o7vc) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L246)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's written this way to boost the significance of the fact that this is unadjusted gas value.
</blockquote></details>

I would also prefer to return it without creating a new variable
we have comment on top of func and right before return and it seems to be pretty enough for me
___
*[`pkg/client/client.go` line 287 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8guFAk-gI2NO9S4ITF:-N91MdMq-0RHDRorIRNv:b-4hlfg1) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L287)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Maybe , but current BankQuery methods of the clients are poorly designed and require to pass a private key of a wallet, to know its balance.
</blockquote></details>

We should probably work on redesigning our client. After checking this PR I see some drawbacks in initial design

Needs discussion
___
*[`pkg/client/client.go` line 293 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8guh4u0DEbWN38pCC6:-N91Pp9REEAbLgVOuol-:becwtdc) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L293)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

That means client API surface grows too big, implementing every module's niche use cases, it will be useless. What we need there is a  client that initializes the context (tm RPC connection with chain settings) and allows to submit msgs and query data..

We don't need a monster API that knows about eve [...]

2022-08-09 12:20 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 29 of 37 files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h5PDT9_goecNg-Mck:-N91X6VY04SIPDtU53V4:bll6rkd) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

`keyring-file` is an internal keychain representation from Cosmos SDK, I didn't create that dir.
</blockquote></details>

I don't care much but I would probably stick to `-` dashes everywhere because it looks a bit strange

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h68hl9hjJJVQe1E9H:-N91XJ6ZBGttFKHFe2Nw:buy466o) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> User may just provide a path to the file containing the key. 

The file is inside Cosmos keyring and is a bit cumbersome to work with. The keyring package I'm adding simplifies the flow of instantiating the Cosmos keyring.

Also, you keep forgetting that every sane user would prefer to use Ledger or other hardware wallet, not having them hardcoded or provided as files.

The original Cosmos keyring solves many problems and has multiple backends, allowing cross-OS flexibility. We just introduced a simpler constructor there for that keyring flow.


</blockquote></details>

We should first of all decide on the purpose of our client and only after this it starts to make/not make sense of introducing keyring or not 

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybXrRCX9rrxBYVB_K:-N91XgtV6KIV4Q9l_eRm:bng26y3) (no related file):*
> The client was poorly designed, that's a fact, and I agree it will be redesigned. However this is not an excuse to block this PR from merging.

It is for me. The proper time is now. Unless we do it properly now we will end up having even worse situation after merging. 

___


<!-- Sent from Reviewable.io -->

2022-08-09 12:22 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 29 of 37 files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 14 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N9-bxZh7fI6KgAkjJEM:-N91Wo8ZE914kyecRdfI:b-eln14m) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/go.mod#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

This one is absolutely necessary and was a hard requirement from Reza
</blockquote></details>

I'm not saying that we don't need `crust contracts` command, I'm saying that coreum should not include it as dependency
___
*[`pkg/client/client.go` line 217 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h-RnOAQZuLL2IbThN:-N91Y--J6ODpVyZAEG70:bbcohms) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L217)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Refactoring client is not a goal of this PR but we should try to implement things as clean as possible because otherwise we will never get back to this which will end up having dirty client

> To conform to the design of the other parts of the client, logic of this method (and probably calling code) should be separated into three different methods

Sounds logical. It is sort of splitting responsibilities but might make this method inconvenient.
Needs discussion.

> In current version EstimateGas accepts cosmos type as an argument, which we decided to avoid, that's why it needs to be redone

I see Maxim's point now for using cosmos types. I'm not sure how to avoid `sdk.Msg` in this case and make it elegant. @wojtek-coreum Do you have any ideas for this ?
Needs discussion.

> I know that PrepareTxBankSend calls Sign internally, it needs to be redesigned so it's possible to support both sign types (for broadcast and gas estimation) for all types of transactions. It was done like that because I didn't know at that time that other way of signing might be needed. It means that we need to find a better way of handling this situation now, not just ignore the problem. We need to discuss in a team how it might be approached.

Needs discussion

> I also know that Prepare* methods are designed to return authsigning.Tx at the moment which is against the encapsulation rule we set earlier. It's a bug, not a feature, coming from early days of this client. I will find a way to fix this. Please don't use it as an argument to allow that kind of leakage in other places.

It also uses `sdk.Msg`. Are we still sure that we can avoid cosmos sdk types and it is a good idea ?
Needs discussion


@wojtek-coreum I can see that we use `must.Ok` which panic in various places here. I don't think it is acceptable in client

</blockquote></details>

PR of new client is already there: https://reviewable.io/reviews/CoreumFoundation/coreum/130#-


<!-- Sent from Reviewable.io -->

2022-08-09 12:27 UTC, ysv requested changes
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 29 of 37 files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 14 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N9-bxZh7fI6KgAkjJEM:-N91Yrhs07Z1AH8LGlXI:b-jlkj7t) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/go.mod#L14)):*
> We agreed already that coreum repo must not import crust

I meant this. That we cant import crust into coreum


<!-- Sent from Reviewable.io -->

2022-08-09 13:47 UTC, miladz68 requested changes
> Reviewed 4 of 21 files at r3, 2 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 29 of 37 files reviewed, 36 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 3 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91jNtcBuLXsmjHf58r:-N91jNtcBuLXsmjHf58s:b-eywpcg) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/go.mod#L3)):*
> ```XML
> module github.com/CoreumFoundation/coreum
> 
> go 1.18
> ```

this makes me happy 
___
*[`integration-tests/wasm/bank_send.go` line 12 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91m97J5TRZ8RVwHCCw:-N91m97J5TRZ8RVwHCCx:bq3z2l5) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L12)):*
> ```Go
> 	"github.com/CoreumFoundation/coreum/integration-tests/testing"
> 	"github.com/CoreumFoundation/coreum/pkg/types"
> 	"github.com/CoreumFoundation/crust/pkg/contracts"
> ```

config should reside in coreum repo. In other worlds the coreum should not depend on crust, and all the chain setup should be provided by coreum and crust is a simple test runner.
___
*[`integration-tests/wasm/bank_send.go` line 21 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91kBYi4kpD-6OQLJj8:-N91kBYi4kpD-6OQLJj9:b-lvp9bl) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L21)):*
> ```Go
> 
> var (
> 	//go:embed fixtures/bank-send/artifacts/bank_send.wasm
> ```

since we now have the source code available in this repo, I see no point in embeding this. 
___
*[`integration-tests/wasm/bank_send.go` line 42 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91mZCL7BrUVyMp276L:-N91mZCL7BrUVyMp276M:b-i35qy7) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L42)):*
> ```Go
> 
> 	initTestState := func(ctx context.Context) error {
> 		orPanic(chain.Network.FundAccount(adminWallet.Key.PubKey(), nativeTokens("100000000000000000000000000000000000")))
> ```

we should not use panic
___
*[`integration-tests/wasm/fixtures/bank-send/Cargo.lock` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91nofvEKcFeytS0gmx:-N91nofvEKcFeytS0gmy:b-93yb1p) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/Cargo.lock#L1)):*
> ```TOML
> # This file is automatically @generated by Cargo.
> ```

This a huge file, we should use a shared cargo.lock file for all wasm tests.
___
*[`integration-tests/wasm/fixtures/bank-send/Cargo.toml` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91o-Ib2hD5IAvHYQqB:-N91o-Ib2hD5IAvHYQqC:bgu4aw8) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/Cargo.toml#L1)):*
> ```TOML
> [package]
> ```

As I argued before, this should be common between all integration tests.
___
*[`integration-tests/wasm/fixtures/bank-send/artifacts/bank_send.wasm` line 0 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91o7WJ1JAY2nefkOcS:-N91o7WJ1JAY2nefkOcT:bbf50qc) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/artifacts/bank_send.wasm#L0)):*
now that the contracts are in the repo, I think these should be removed. 
___
*[`integration-tests/wasm/fixtures/bank-send/artifacts/checksums.txt` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91oIEwBgtyBjvoXgEq:-N91oIEwBgtyBjvoXgEr:b-igr3v0) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/artifacts/checksums.txt#L1)):*
> ```Checksums
> 45ae90c5383d4510494a0a83d8e38c82c8ca972bde401c7d18d5edd1ba6d4e1c  bank_send.wasm
> ```

Since I argued that binaries be removed, if we remove them, then we will not need this.
___
*[`integration-tests/wasm/fixtures/bank-send/src/contract.rs` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91oi7l7azlYNofDw9m:-N91oi7l7azlYNofDw9n:b-oqieir) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/src/contract.rs#L1)):*
> ```XML
> use cosmwasm_std::entry_point;
> ```

quick question, did you write this contract or is it copied from somewhere ?
___
*[`integration-tests/wasm/fixtures/simple-state/.gitignore` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91oxl1ExikRTLX6sZ9:-N91oxl1ExikRTLX6sZA:b-y6zh3e) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/simple-state/.gitignore#L1)):*
> ```ignore
> target/
> ```

I think the target folder should be shared between all wasm tests and the .gitignore directive should be moved to the root directory.


<!-- Sent from Reviewable.io -->

2022-08-09 14:04 UTC, xlab commented
*[`integration-tests/wasm/bank_send.go` line 21 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N913NwB45-AUVLRVt1e:-N91uhlgB3JsR-qZ_DcN:b2c87xd) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you pls move fixtures to `integration-tests` folder so everything related to integration tests live there ?
</blockquote></details>

This is inside already. The path in embed is relative.


<!-- Sent from Reviewable.io -->

2022-08-09 14:05 UTC, xlab commented
*[`integration-tests/wasm/bank_send.go` line 21 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91kBYi4kpD-6OQLJj8:-N91us4q4Lv0PUaDhV2u:b-lrsxc4) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

since we now have the source code available in this repo, I see no point in embeding this. 
</blockquote></details>

We always had the source code in the repo. The idea was to provide deployable binaries without recompiling them on every CI run. The source is not going to change, so it's a waste of time to compile it every time.


<!-- Sent from Reviewable.io -->

2022-08-09 14:06 UTC, xlab commented
*[`integration-tests/wasm/bank_send.go` line 81 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N917m6W7KHG7kvDdXfZ:-N91vKFL7LbqUl-AyZIg:b69l8rl) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L81)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It might be simplified:

```go
return initTestState, testBankSendContract(
			chain,
			adminWallet,
			testWallet,
			networkConfig,
			stagedContractPath,
			nativeDenom,
			nativeTokens,
)
```
</blockquote></details>

Putting too much inside return statements doesn't simplify things.


<!-- Sent from Reviewable.io -->

2022-08-09 14:08 UTC, xlab commented
*[`integration-tests/wasm/fixtures/bank-send/Cargo.lock` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91nofvEKcFeytS0gmx:-N91veI770sMABRb_iZf:b-9gv47j) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/Cargo.lock#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This a huge file, we should use a shared cargo.lock file for all wasm tests.
</blockquote></details>

Since when 20K files are considered "HUGE" ?


<!-- Sent from Reviewable.io -->

2022-08-09 16:38 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: 29 of 37 files reviewed, 36 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 21 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91kBYi4kpD-6OQLJj8:-N92SeR6EBcUarojEDc7:b-aglmvj) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L21)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

We always had the source code in the repo. The idea was to provide deployable binaries without recompiling them on every CI run. The source is not going to change, so it's a waste of time to compile it every time.
</blockquote></details>

I don't think it is waste of time. As I remember we agreed in the talk that the `correct` way of doing this is not include compile binary in the source code.
___
*[`integration-tests/wasm/fixtures/bank-send/Cargo.lock` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91nofvEKcFeytS0gmx:-N92SED90B5VBQsxIDHq:b3eekag) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/fixtures/bank-send/Cargo.lock#L1)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Since when 20K files are considered "HUGE" ?
</blockquote></details>

750 lines of code is huge. I am not talking about file size. imagine we add 20 integration tests and each introduces 750 lines of code. 


<!-- Sent from Reviewable.io -->

2022-08-10 06:12 UTC, wojtek-coreum requested changes
> Reviewed 4 of 11 files at r1, 1 of 10 files at r2, 3 of 21 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/123)* status: all files reviewed, 32 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h5PDT9_goecNg-Mck:-N95E7Ll43KgQA23rnce:bhz344g) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't care much but I would probably stick to `-` dashes everywhere because it looks a bit strange
</blockquote></details>

I would also prefer to have dashes in all directories

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8h68hl9hjJJVQe1E9H:-N8mKkag4WB3bpDENc3l:b-w8b5km) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

We should first of all decide on the purpose of our client and only after this it starts to make/not make sense of introducing keyring or not 
</blockquote></details>

We agreed during the meeting to move keyring to `crust` to be `contracts`-command specific thing, not implemented natively in the client here.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8ybXrRCX9rrxBYVB_K:-N95Enwh-m0eJfArcJZ3:b-pd3ivd) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> The client was poorly designed, that's a fact, and I agree it will be redesigned. However this is not an excuse to block this PR from merging.

It is for me. The proper time is now. Unless we do it properly now we will end up having even worse situation after merging. 


</blockquote></details>

So it was decided that this PR waits for new client and once it's in master we will come back here.

___
___
*[`go.mod` line 14 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N9-bxZh7fI6KgAkjJEM:-N95F3A58AVP0g2JJ30D:by06iz9) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/go.mod#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> We agreed already that coreum repo must not import crust

I meant this. That we cant import crust into coreum
</blockquote></details>

We agreed that `coreum` won't import `crust`. Instead `crust` will import `coreum` and use client to deploy contracts.
___
*[`integration-tests/wasm/bank_send.go` line 42 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N91mZCL7BrUVyMp276L:-N95KedbD9TXXvoC53zX:b-jan244) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should not use panic
</blockquote></details>

This is sth I would eventually like to discuss.
This is a test. Test works or doesn't work. If it doesn't work I don't care much if it fails due to panic or error. The testing framework support both scenarios and panic is converted to error without affecting other tests. At the same time, using helpers like this can save a lot of dumb typing on `if err != nil { return err }`.

We agreed that in official/production code errors must be returned but in tests `return err` and `panic(err)` are effectively the same thing because testing framework catches the panic and converts it to error: https://github.com/CoreumFoundation/crust/blob/master/infra/testing/run.go#L137
___
*[`integration-tests/wasm/bank_send.go` line 81 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N917m6W7KHG7kvDdXfZ:-N95FKFQ7Idqe5N2D9F8:b-3ny3tt) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L81)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Putting too much inside return statements doesn't simplify things.
</blockquote></details>

The main reasoning in my comment is about converting this:

```go
	runTestFunc := func(ctx context.Context, t testing.T) {
		testBankSendContract(
			chain,
			adminWallet,
			testWallet,
			networkConfig,
			stagedContractPath,
			nativeDenom,
			nativeTokens,
		)(ctx, t)
	}

```

to this:

```go
	runTestFunc := testBankSendContract(
			chain,
			adminWallet,
			testWallet,
			networkConfig,
			stagedContractPath,
			nativeDenom,
			nativeTokens,
		)
```

because you introduced dummy wrapper doing nothing interesting.

I still prefer, like @ysv , to just inline those functions. If linter complains then let's adjust the linter.
___
*[`integration-tests/wasm/bank_send.go` line 94 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N95M7JCDPYNZaUn6Rvx:-N95M7JCDPYNZaUn6Rvy:b-cvujwa) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L94)):*
> ```Go
> ) func(context.Context, testing.T) {
> 	return func(ctx context.Context, t testing.T) {
> 		expect := require.New(t)
> ```

expect -> requireT

We have already set this convention in entire code base.

Also if it's possible to continue, please use `assert` instead of `require` to catch as many errors in one go as possible.
___
*[`integration-tests/wasm/bank_send.go` line 182 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N95MYYPBqmOF-hgNLbh:-N95MYYPBqmOF-hgNLbi:b-2wb2z7) ([raw file](https://github.com/coreumfoundation/coreum/blob/28da10af9225bd7e0c7e7309c210647421127eb0/integration-tests/wasm/bank_send.go#L182)):*
> ```Go
> }
> 
> func orPanic(err error) {
> ```

you have `must.OK`
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gsKS5DZp30NtuuhWo:-N95FnLV-1R1arL1y9m8:bnhl47a) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also vote for returning error here
there is not than many places were it is used 
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/TYTc3SjGfbxhIAOUE1yrAni4/image.png)

</blockquote></details>

And most of them are introduced by this PR. There are only 2 existing in `master`, so applying the requested change is super-trivial.
___
*[`pkg/client/client.go` line 297 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gtda5DK06iUoAd-gh:-N95GknH7waYMUKzac2p:b-vzoxam) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/client/client.go#L297)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would probably keep this code in a different place since it is not related to client
</blockquote></details>

For now I haven't got any explanation for logging this stuff. You may provide an example of those logs here for everyone as I requested or wait until I find some time to check it myself.
___
*[`pkg/tx/sign.go` line 82 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/123#-N8gxUxxCqJvVf9qPFyd:-N95H72P4VgSY-NcjxRK:bqvk8s) ([raw file](https://github.com/coreumfoundation/coreum/blob/0a426886d926c05034cba1f468e42726ed1ec059/pkg/tx/sign.go#L82)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would also prefer to not duplicate the same logic twice and to call one method from other or do another composition but to avoid logic duplication 
</blockquote></details>

It seems that "signing" for estimation is the same as regular signing with one step skipped. Compare: https://github.com/CoreumFoundation/coreum/blob/new-client-1/pkg/tx2/sign.go#L59

It will be probably discussed further in PR introducing new client [...]

2022-08-29 11:03 UTC, dzmitryhil commented
closing this PR, the brach will be deliver by this one: https://github.com/CoreumFoundation/coreum/pull/148

2022-08-29 11:03 UTC, closed without merging