Add module implementing fee model
CoreumFoundation/coreum pull request #131
Opened 2022-08-09 12:54 UTC by wojtek-coreum

2022-08-10 12:05 UTC, miladz68 requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 18 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/app.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N962tSJ9SrAnvJzBmit:-N962tSJ9SrAnvJzBmiu:bb1htdw) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/app.go#L101)):*
> ```Go
> 	feekeeper "github.com/CoreumFoundation/coreum/x/fee/keeper"
> 	feetypes "github.com/CoreumFoundation/coreum/x/fee/types"
> ```

this line seems to be extra, they seem to belong to the same import group.
___
*[`app/network.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N968YquD92kh83u2l_8:-N968YquD92kh83u2l_9:b-e4yi6m) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L68)):*
> ```Go
> 				FeeModel: FeeModel{
> 					InitialGasPrice:                      big.NewInt(1500),
> 					MaxDiscount:                          0.15,
> ```

I thing it shoule be `0.5` right ? at least that is the number that was getting thrown around in discussions.
___
*[`app/network.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N968mLe0YQl1yVOlWp8:-N968mLe0YQl1yVOlWp9:b304l0x) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L69)):*
> ```Go
> 					InitialGasPrice:                      big.NewInt(1500),
> 					MaxDiscount:                          0.15,
> 					OptimalBlockGas:                      43750000, // 350 * BankSend transactions
> ```

350 is too close to 400 given the fact that fee escalation goes up very slowly at first. I would go with 300.
if we go with 300, then at 350 we will have the gasPrice doubled by 350, which looks like a good point to me.
___
*[`app/network.go` line 154 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96C8keBldHnrVg1XDl:-N96C8keBldHnrVg1XDm:b-xc7bqy) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L154)):*
> ```Go
> 	MaxDiscount                          float64
> 	OptimalBlockGas                      int64
> 	MaxBlockGas                          int64
> ```

max block gas should be enforced (applied) on tendermint config as well.  Also you should check out to see if that config is applied at node level or network level. if it is only applied at node level, then an ante handler should enforce it at chain level.
___
*[`app/network.go` line 155 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N969q5n0KFo7maglB9N:-N969q5o9-wkdRl34yXR:bsdodnl) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L155)):*
> ```Go
> 	OptimalBlockGas                      int64
> 	MaxBlockGas                          int64
> 	NumOfBlocksForCurrentAverageBlockGas uint
> ```

these names are not very clear.
I suggest the following names with comments providing more context, maybe with links to our whitepaper ?
```
NumOfBlocksForShortAverageBlockGas
NumOfBlocksForLongAverageBlockGas
```



_Code quote:_
```Go
	NumOfBlocksForCurrentAverageBlockGas uint
	NumOfBlocksForAverageBlockGas        uint
```
___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Kk9x0O6D0H9WZKuo:-N96Kk9x0O6D0H9WZKup:b-au9cji) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/integration-tests/testing/network.go#L11)):*
> ```Go
> 
> // NetworkConfig is the network config used by integration tests
> var NetworkConfig = app.NetworkConfig{
> ```

I now see a problem when defining a network config for testing, that most of the fields must reflect values defined in Devnet. Because crust is using Devent to launch a test chain. I think reusing Devnet and reseting genesis tx as I did before is a plausible method. or we could just cop Devnet config and empty out genesis tx here. I think the second method is better.
___
*[`x/auth/ante/ante.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lm06-eUWS5bOFhcb:-N96Lm06-eUWS5bOFhcc:b4rg2xv) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L20)):*
> ```Go
> 	BankKeeper         types.BankKeeper
> 	FeegrantKeeper     authante.FeegrantKeeper
> 	GasPriceKeeper     GasPriceKeeper
> ```

I think these 2 keepers could be merged to one.



_Code quote:_
```Go
	GasPriceKeeper     GasPriceKeeper
	GasCollectorKeeper GasCollectorKeeper
```
___
*[`x/auth/ante/ante.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lr4-5M0u_BvP-HnS:-N96Lr4-5M0u_BvP-HnT:b-g7mkrj) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L62)):*
> ```Go
> 		NewDeterministicGasDecorator(options.GasRequirements),
> 		authante.NewValidateMemoDecorator(options.AccountKeeper),
> 		NewFeeDecorator(options.GasPriceKeeper),
> ```

These 2 decorators could be merged as well since they work together to achieve a single functionality. 



_Code quote:_
```Go
		NewFeeDecorator(options.GasPriceKeeper),
		NewCollectGasDecorator(options.GasCollectorKeeper),
```
___
*[`x/auth/ante/fee.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96MaED1m8KD4Xh32Wp:-N96MaED1m8KD4Xh32Wq:b-kfap6l) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L41)):*
> ```Go
> 	fees := feeTx.GetFee()
> 	minGasPrice := fd.gasPriceKeeper.GetMinGasPrice(ctx)
> 	for _, coin := range fees {
> ```

instead of ranging over fees we can assert there is only one coin as fees.
___
*[`x/auth/ante/fee.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96OLR63l7_Fv-NSjKa:-N96OLR63l7_Fv-NSjKb:b-9rv9df) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L48)):*
> ```Go
> 
> 	gasDeclared := sdk.NewInt(int64(feeTx.GetGas()))
> 	feeOffered := sdk.NewCoin(minGasPrice.Denom, fees.AmountOf(minGasPrice.Denom))
> ```

I think `feeOffered` should be calculated via `feeTx.GetFee()`, not the way it is done here. here we take the gas limit and assume that the user submitted the limit according to the network price. but they might have a lower price in mind when they were submitting their requests.
___
*[`x/auth/ante/fee.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96PNDG4ix0HsBXcaR0:-N96PNDG4ix0HsBXcaR1:b-695qz4) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L83)):*
> ```Go
> 	}
> 
> 	cgd.gasCollectorKeeper.TrackGas(ctx, int64(feeTx.GetGas()))
> ```

can we move this logic to `EndBlocker` ? we are interested in block gas and not gas limit in transaction. although they are almost the same thing now, because refund is not implemented in cosmos sdk, but if refund is implemented, then this logic here would be incorrect, and the value return from `EndBlocker` would be more accurate.  
___
*[`x/fee/module.go` line 136 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96R9LD8BUd18dZdc6P:-N96R9LE5xYmGi0usESA:b-gzjl80) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L136)):*
> ```Go
> 
> // ConsensusVersion implements AppModule/ConsensusVersion.
> func (AppModule) ConsensusVersion() uint64 { return 2 }
> ```

This should start with 1. It will be used by migration pacakge to allow for in-place migrations.
___
*[`x/fee/module.go` line 183 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9 [...]

2022-08-10 12:30 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 18 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N968YquD92kh83u2l_8:-N96eJqT3b8JMN1an07q:b-dh353c) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L68)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I thing it shoule be `0.5` right ? at least that is the number that was getting thrown around in discussions.
</blockquote></details>

I really don't know. For now I used the first number which came to my mind. If there is any final decision I will adjust of course, but are you sure about 0.5? Let's ask Reza.
___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Kk9x0O6D0H9WZKuo:-N96f-8W14oPZD90MSBN:b-te0tlz) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/integration-tests/testing/network.go#L11)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I now see a problem when defining a network config for testing, that most of the fields must reflect values defined in Devnet. Because crust is using Devent to launch a test chain. I think reusing Devnet and reseting genesis tx as I did before is a plausible method. or we could just cop Devnet config and empty out genesis tx here. I think the second method is better.
</blockquote></details>

Yes, I think some common function like `NetworkConfigForTest` which takes devnet network config and removes fields from there would be good
___
*[`x/auth/ante/ante.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lm06-eUWS5bOFhcb:-N96fFL19Xd4V3Y_vnXW:bdipmo9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think these 2 keepers could be merged to one.
</blockquote></details>

Yes, it's reasonable if your another request to merge decorators is applied
___
*[`x/auth/ante/fee.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96OLR63l7_Fv-NSjKa:-N96fze76E8WA0iFLejl:b-n2phl5) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L48)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think `feeOffered` should be calculated via `feeTx.GetFee()`, not the way it is done here. here we take the gas limit and assume that the user submitted the limit according to the network price. but they might have a lower price in mind when they were submitting their requests.
</blockquote></details>

this is exactly what I do:

```go
fees := feeTx.GetFee()
```

`fees.AmountOf(minGasPrice.Denom)` is just about taking amount of core (because `fees` may contain many tokens)
___
*[`x/auth/ante/fee.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96PNDG4ix0HsBXcaR0:-N96h68s3XT99jLhiLol:b-4wg57v) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

can we move this logic to `EndBlocker` ? we are interested in block gas and not gas limit in transaction. although they are almost the same thing now, because refund is not implemented in cosmos sdk, but if refund is implemented, then this logic here would be incorrect, and the value return from `EndBlocker` would be more accurate.  
</blockquote></details>

It can't be done in the `EndBlocker` because I don't have an access to transactions there. Ante handler is the only place where I can do it.
___
*[`x/fee/module.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UG5Z0kAspU2_CVhe:-N96ha0C3Dx3z1PpoAnd:b4vhsgw) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L187)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I understand that it is like putting a cap on price factor. then I would suggest be explicit and put an explicit priceFactor cap. something like 100.
</blockquote></details>

But I don't know what this price factor should be because it depends on the configuration of the network (as you see in the formula). What I do here I set the factor which is used for `feeModel.MaxBlockGas - 1` which gives a flat line after that point. But as I said, that point is not constant - it depends on values set for network.
___
*[`x/fee/module.go` line 189 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UriYBV87gq_ANVQG:-N96i9T541ci3xg7yFn9:bcw24dr) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L189)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is possible that currentAverageGas gets very close to MaxBlock gas, and we get unrealistic numbers like 1,000,000 times more gas price. I suggest to cap priceFactor to 100 here.
</blockquote></details>

This is exactly what our fee model is intended to do - escalate price to infinity. If you would like to change the model let's discuss it in a team outside this PR.
___
*[`x/fee/module.go` line 191 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Vhgk7Ruo3SPE1_ia:-N96iZZC9Fm6lnn-eMRH:bcxjr8e) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L191)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I guess this check is introduced to avoid changing priceFactor in genesis block. in that case it is absolutely unreadable. However I don't know how it could be avoided. Maybe pass a boolean value to this function to indicate that this is a genesis block ? or maybe add a comment and explain it in detail ?
</blockquote></details>

This check is introduced to protect against division by 0 in `float64(currentAverageGas)/float64(averageGas))` one line below.
___
*[`x/fee/keeper/keeper.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96cr642z1u3QBIuDIG:-N96ip8a54xaTEhbT92T:b5jnmy2) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/keeper/keeper.go#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

if we move gas tracking logic to `EndBlocker` as I argued, we would not need this.
</blockquote></details>

As I said, it's not possible


<!-- Sent from Reviewable.io -->

2022-08-10 12:49 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 16 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N968YquD92kh83u2l_8:-N96jxdPDHYHNwJfcNSm:b-cglvh6) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I really don't know. For now I used the first number which came to my mind. If there is any final decision I will adjust of course, but are you sure about 0.5? Let's ask Reza.
</blockquote></details>

let's ask him today.
___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Kk9x0O6D0H9WZKuo:-N96k2ro62fpyaac97jE:b-t77xc3) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/integration-tests/testing/network.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, I think some common function like `NetworkConfigForTest` which takes devnet network config and removes fields from there would be good
</blockquote></details>

agreed
___
*[`x/auth/ante/fee.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96PNDG4ix0HsBXcaR0:-N96lrN56Sp84Quj3utT:b-lvi9po) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L83)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It can't be done in the `EndBlocker` because I don't have an access to transactions there. Ante handler is the only place where I can do it.
</blockquote></details>

can you check the whole gas consumed ?
___
*[`x/fee/module.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UG5Z0kAspU2_CVhe:-N96mKIB2PTSmnf5Nh1R:bnrhb53) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L187)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But I don't know what this price factor should be because it depends on the configuration of the network (as you see in the formula). What I do here I set the factor which is used for `feeModel.MaxBlockGas - 1` which gives a flat line after that point. But as I said, that point is not constant - it depends on values set for network.
</blockquote></details>

the value of this `feeModel.MaxBlockGas - feeModel.OptimalBlockGas` is a constant based on the network config. all I am saying that a real constant should be used as the cap. and since this cap is in place for this case, it should apply to the next case as well.
___
*[`x/fee/module.go` line 189 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UriYBV87gq_ANVQG:-N96nCTe7s9M5WJ3bEu3:bbnq5yd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L189)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is exactly what our fee model is intended to do - escalate price to infinity. If you would like to change the model let's discuss it in a team outside this PR.
</blockquote></details>

let's discuss it.


<!-- Sent from Reviewable.io -->

2022-08-10 13:11 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 16 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`x/auth/ante/fee.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96PNDG4ix0HsBXcaR0:-N96rSAs23jcHWiXdIYD:b-k64oye) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

can you check the whole gas consumed ?
</blockquote></details>

That's the problem. I can check the gas consumed but fee model operates on the gas limits declared by signers - and this is known only in ante handler. And we operate on gas limits because transactions are included in block by proposer based on that number.
___
*[`x/fee/module.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UG5Z0kAspU2_CVhe:-N96s5CJ1tJb_tEXGtdl:b-yq8vr7) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L187)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the value of this `feeModel.MaxBlockGas - feeModel.OptimalBlockGas` is a constant based on the network config. all I am saying that a real constant should be used as the cap. and since this cap is in place for this case, it should apply to the next case as well.
</blockquote></details>

Are you requesting adding another field to network config? Then the value of that constant must be managed manually by doing this calculation.


<!-- Sent from Reviewable.io -->

2022-08-10 14:14 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 14 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`x/fee/module.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UG5Z0kAspU2_CVhe:-N975YHQ3XS8592bqHjU:b-gn5xdc) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L187)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Are you requesting adding another field to network config? Then the value of that constant must be managed manually by doing this calculation.
</blockquote></details>

it can be hardcoded. like 1000x/100x is the max amount.


<!-- Sent from Reviewable.io -->

2022-08-12 11:36 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 14 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/app.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N962tSJ9SrAnvJzBmit:-N9GmBMKDl17QTnvY9rX:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/app.go#L101)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this line seems to be extra, they seem to belong to the same import group.
</blockquote></details>

Done.
___
*[`app/network.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N968YquD92kh83u2l_8:-N9GfUDm5UoWJCIrDLmu:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L68)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's ask him today.
</blockquote></details>

Done.
___
*[`app/network.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N968mLe0YQl1yVOlWp8:-N9GfVxe9jFgRMCNMaeD:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L69)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

350 is too close to 400 given the fact that fee escalation goes up very slowly at first. I would go with 300.
if we go with 300, then at 350 we will have the gasPrice doubled by 350, which looks like a good point to me.
</blockquote></details>

Done.
___
*[`app/network.go` line 154 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96C8keBldHnrVg1XDl:-N9Gpjnj6GM0SQGHQkyD:b2ffdbo) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L154)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

max block gas should be enforced (applied) on tendermint config as well.  Also you should check out to see if that config is applied at node level or network level. if it is only applied at node level, then an ante handler should enforce it at chain level.
</blockquote></details>

Ok, but separate PR?
___
*[`app/network.go` line 155 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N969q5n0KFo7maglB9N:-N9GjoeTE_3XVREyJuyC:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L155)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

these names are not very clear.
I suggest the following names with comments providing more context, maybe with links to our whitepaper ?
```
NumOfBlocksForShortAverageBlockGas
NumOfBlocksForLongAverageBlockGas
```
</blockquote></details>

Done.
___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Kk9x0O6D0H9WZKuo:-N9GoX530dTwWqyDKTpQ:b-em0lyp) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/integration-tests/testing/network.go#L11)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

agreed
</blockquote></details>

I will do it in separate PR as it has nothing to do with fee model
___
*[`x/auth/ante/ante.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lr4-5M0u_BvP-HnS:-N9GpKAeBZSk0bYDf1Em:b-bw4qmb) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L62)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

These 2 decorators could be merged as well since they work together to achieve a single functionality. 
</blockquote></details>

Now when Ilook at it again I see that, yes both decorators cooperate with fee model, but their purposes are very different and I would prefer to not mix them. If you like we may wait for what @ysv says.
___
*[`x/auth/ante/fee.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96MaED1m8KD4Xh32Wp:-N9GlfjbApxD_8PypxdL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/fee.go#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

instead of ranging over fees we can assert there is only one coin as fees.
</blockquote></details>

Done.
___
*[`x/fee/module.go` line 136 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96R9LD8BUd18dZdc6P:-N9GlkoE5w--U71nviIQ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L136)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This should start with 1. It will be used by migration pacakge to allow for in-place migrations.
</blockquote></details>

Done.
___
*[`x/fee/module.go` line 183 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96TCaf9Fe5oIL-hom5:-N9GoF9o89GadfjS2tQH:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L183)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this function can be moved into a separate file as it is not part of the module interface. same goes for the `Model` struct.
</blockquote></details>

Done.
___
*[`x/fee/module.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UG5Z0kAspU2_CVhe:-N9Glq1g2ATox6RiD3or:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L187)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it can be hardcoded. like 1000x/100x is the max amount.
</blockquote></details>

Done.
___
*[`x/fee/module.go` line 189 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96UriYBV87gq_ANVQG:-N9GlsVy7-HZY20-2Gbs:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module.go#L189)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss it.
</blockquote></details>

Done.
___
*[`x/fee/module_test.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Z92t3X75X17NyGv2:-N9GlygR3q5aRQ_N7wRa:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/fee/module_test.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

TestCalculateNextGasPriceKeyPoints
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-12 11:58 UTC, miladz68 requested changes
> Reviewed 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 14 of 18 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 154 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96C8keBldHnrVg1XDl:-N9GsSqW7ApemGY3i7-f:b-659648) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L154)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ok, but separate PR?
</blockquote></details>

let's discuss after daily. 
I am fine by doing a separate PR by you have argued on separate occasions that a half ready solution must not go to the master. I guess the discussion kinda involves our release plan flow as well.
@ysv also for your attention on how to approach this.
___
*[`app/network.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9GtwqD627g-wYO0FFi:-N9GtwqD627g-wYO0FFj:b-tos54r) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/app/network.go#L171)):*
> ```Go
> 
> 	// EscalationInertia defines how slow gas price goes up after triggering escalation algorithm (the lower the inertia, the faster price goes up)
> 	EscalationInertia float64
> ```

I tried to understand this variable by looking at the CalculatePrice function, and then thought to myslef: "Can't we just increase the inertia by increasing the `NumOfBlocksForShortAverageBlockGas`". And I think increasing the inertia is the only utility of `NumOfBlocksForShortAverageBlockGas`, you want twice the inertia then just increase this number by 2. I know that increasing `NumOfBlocksForShortAverageBlockGas` will not incrase the inertia by 2 exactly, but it achieves the same functionality. 


<!-- Sent from Reviewable.io -->

2022-08-12 11:59 UTC, miladz68 reviewed
> Reviewed 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-12 13:32 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 154 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96C8keBldHnrVg1XDl:-N9HE6Lc5C9og-wrG4ZM:b-dg69jm) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L154)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss after daily. 
I am fine by doing a separate PR by you have argued on separate occasions that a half ready solution must not go to the master. I guess the discussion kinda involves our release plan flow as well.
@ysv also for your attention on how to approach this.
</blockquote></details>

It's not about half ready solution. Playing with configuration of node seems to be a different topic than implementing a module. But if you insist on it I may do it here.
___
*[`app/network.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9GtwqD627g-wYO0FFi:-N9HEQhd9pAHIJ2vqTel:b1iyo4w) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/app/network.go#L171)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I tried to understand this variable by looking at the CalculatePrice function, and then thought to myslef: "Can't we just increase the inertia by increasing the `NumOfBlocksForShortAverageBlockGas`". And I think increasing the inertia is the only utility of `NumOfBlocksForShortAverageBlockGas`, you want twice the inertia then just increase this number by 2. I know that increasing `NumOfBlocksForShortAverageBlockGas` will not incrase the inertia by 2 exactly, but it achieves the same functionality. 
</blockquote></details>

I agree more ore less but:
- `NumOfBlocksForShortAverageBlockGas` adds inertia to the entire curve so gas prices changes are smoother
- `EscalationInertia` is exclusively about telling how dynamic the gas price escalation should be (going from being linear if it's 1 or flat for very long time if it's 100)

So IMO purposes are similar but not exactly. Maybe we should just hardcode `EscalationInertia` to some constant number and not make it a parameter of the network. I don't have an opinion here because exact shape of the curve is not a technical problem but business decision, and barely believe that there is someone ho has an idea of how this curve should be shaped exactly :-)


<!-- Sent from Reviewable.io -->

2022-08-16 00:28 UTC, oliverasistemas reviewed
> Reviewed 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`x/fee/module.go` line 52 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9Z22_nCeQBD1gkL40L:-N9Z22_nCeQBD1gkL40M:b-pjw9md) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/x/fee/module.go#L52)):*
> ```Go
> 
> // RegisterRESTRoutes registers the REST routes for the fee module.
> func (AppModuleBasic) RegisterRESTRoutes(clientCtx client.Context, rtr *mux.Router) {}
> ```

Why are these empty methods created? Is this a requirement to satisfy some necessary interface?


<!-- Sent from Reviewable.io -->

2022-08-16 05:26 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`x/fee/module.go` line 52 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9Z22_nCeQBD1gkL40L:-N9_6R9V32m8YZZA4bH5:b-g53o1q) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/x/fee/module.go#L52)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

Why are these empty methods created? Is this a requirement to satisfy some necessary interface?
</blockquote></details>

yes, this is an interface required by cosmos


<!-- Sent from Reviewable.io -->

2022-08-16 06:53 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9GtwqD627g-wYO0FFi:-N9_OzQfA_nY1WEsGGgR:b6cmdfi) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/app/network.go#L171)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I agree more ore less but:
- `NumOfBlocksForShortAverageBlockGas` adds inertia to the entire curve so gas prices changes are smoother
- `EscalationInertia` is exclusively about telling how dynamic the gas price escalation should be (going from being linear if it's 1 or flat for very long time if it's 100)

So IMO purposes are similar but not exactly. Maybe we should just hardcode `EscalationInertia` to some constant number and not make it a parameter of the network. I don't have an opinion here because exact shape of the curve is not a technical problem but business decision, and barely believe that there is someone ho has an idea of how this curve should be shaped exactly :-)
</blockquote></details>

As discussed in the call, wojtek decided to change the formula for the gas escalation part of the fee model. basically we are now using a  polynomial function instead of a recirocal one. and `Inertia` indicates the degree of the polynomial. it was decided to hardcode 2 as the degree of polynomial and remove this parameter.


<!-- Sent from Reviewable.io -->

2022-08-16 08:39 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 7 of 21 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 154 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96C8keBldHnrVg1XDl:-N9__s69D4Pk_a4YBlsS:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/app/network.go#L154)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not about half ready solution. Playing with configuration of node seems to be a different topic than implementing a module. But if you insist on it I may do it here.
</blockquote></details>

Done
___
*[`app/network.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9GtwqD627g-wYO0FFi:-N9__jjF1Ir-eBjePI6E:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/app/network.go#L171)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

As discussed in the call, wojtek decided to change the formula for the gas escalation part of the fee model. basically we are now using a  polynomial function instead of a recirocal one. and `Inertia` indicates the degree of the polynomial. it was decided to hardcode 2 as the degree of polynomial and remove this parameter.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-17 06:48 UTC, miladz68 reviewed
> Reviewed 12 of 14 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-17 12:12 UTC, oliverasistemas reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`x/fee/module.go` line 68 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9fi-b39PtBn4ql5jyl:-N9fi-b39PtBn4ql5jym:b7m4cy1) ([raw file](https://github.com/coreumfoundation/coreum/blob/6535804c9fc62d19ecef3ae1a3dc48696d0920ee/x/fee/module.go#L68)):*
> ```Go
> 
> // RegisterInterfaces registers interfaces and implementations of the fee module.
> func (AppModuleBasic) RegisterInterfaces(registry codectypes.InterfaceRegistry) {}
> ```

May be silent unused parameters here and the rest of the empty methods.


<!-- Sent from Reviewable.io -->

2022-08-17 12:36 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`x/fee/module.go` line 68 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9fi-b39PtBn4ql5jyl:-N9fnN0pDY1Ppsm0pG1Q:b-g6spgk) ([raw file](https://github.com/coreumfoundation/coreum/blob/6535804c9fc62d19ecef3ae1a3dc48696d0920ee/x/fee/module.go#L68)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

May be silent unused parameters here and the rest of the empty methods.
</blockquote></details>

then in the future I won't know what those parameters mean


<!-- Sent from Reviewable.io -->

2022-08-18 11:19 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 16 of 22 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9kfIpc4lQ1Lc6e5zUw:-N9kfIpd-pm_c7QA4Wuo:b-lofkw) (no related file):*
Simulations requested by @ysv :
https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=0
https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=940400407

___


<!-- Sent from Reviewable.io -->

2022-08-19 17:25 UTC, ysv requested changes
> Reviewed 1 of 17 files at r1, 2 of 14 files at r3, 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 17 of 22 files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9kfIpc4lQ1Lc6e5zUw:-N9qCR9D8b739eQwdpxW:bmjkkza) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Simulations requested by @ysv :
https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=0
https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=940400407
</blockquote></details>

1. This sort of drop in simulations 
Is it expected and done intentionally ?
![Screenshot 2022-08-19 at 15.05.20.png](https://files.reviewableusercontent.io/images/reviewable/19859122/fqnprNQ6rpw4oOz8nLVm0Ak3/Screenshot%202022-08-19%20at%2015.05.20.png)
Screenshot 2022-08-19 at 15.05.20

2. can we have some values on x axis ?
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/C6lRvEykg195acduchwCw6QG/image.png)

3. can you pls do calculations via formula (exactly the same as you use in code) on 'Fee model Curve' sheet instead of hardcoding values. I thinks it should be 1st column - block size in gas, 2nd column (calculated) - gas price

___
___
*[`go.mod` line 16 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9XXc-bAPzcRWxo9Rsy:-N9XXc-bAPzcRWxo9Rsz:b7mt60u) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/go.mod#L16)):*
> ```XML
> 	github.com/cosmos/go-bip39 v1.0.0
> 	github.com/cosmos/ibc-go/v3 v3.0.0
> 	github.com/gorilla/mux v1.8.0
> ```

surprisingly
is this dep expected to be here ?
Because gorilla is http stuff mostly AFAIK
___
*[`app/app.go` line 100 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qEKxH8GB0vSXF1mm2:-N9qEKxH8GB0vSXF1mm3:b76wros) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L100)):*
> ```Go
> 	"github.com/CoreumFoundation/coreum/docs"
> 	"github.com/CoreumFoundation/coreum/x/auth/ante"
> 	"github.com/CoreumFoundation/coreum/x/fee"
> ```

Do you have any other option for this module name ?
not sure why but fee seems to be too generic for me

WDYT about fee schedule eg. ?
___
*[`app/app.go` line 418 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qIqI235UhHyIWSKkW:-N9qIqI235UhHyIWSKkX:b-s27il6) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L418)):*
> ```Go
> 
> 	feeModel := ChosenNetwork.FeeModel()
> 	feeModule := fee.NewAppModule(appCodec, app.FeeKeeper,
> ```

please read about other moving average types: weighted moving average (WMA) & Exponential Moving Average (EMA)

https://www.tradingview.com/support/solutions/43000502589-moving-average


Lets discuss if it makes sense to use WMA/EMA
___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-N9qH0Cj-QDWFr3FtgyB:b-evwtoq) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
> ```Go
> 			EscalationStartBlockGas:            feeModel.EscalationStartBlockGas,
> 			MaxBlockGas:                        feeModel.MaxBlockGas,
> 			NumOfBlocksForShortAverageBlockGas: feeModel.NumOfBlocksForShortAverageBlockGas,
> ```

I suggest a bit better names here:

`ShortSMABlockLength` or `ShortSMALengthInBlocks`

(same for LongAverage)

but we need to discuss previous comment first
___
*[`app/network.go` line 67 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qtZxe0UfuCliEkYoK:-N9qtZxe0UfuCliEkYoL:bd99t0o) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L67)):*
> ```Go
> 				FeeModel: FeeModel{
> 					InitialGasPrice:                    big.NewInt(1500),
> 					MaxGasPrice:                        big.NewInt(15000),
> ```

I would probably put even bigger number here. Because we just multiplied it by 10 which means that if usually fee is 0.01-0.1$ now it becomes 0.1-1$ which is still small amount. 

I think we should put smth so big so none even wants to create a tx because of high fees.
E.g 1,000 or 10,000 times more

Also it would be nice to understand on which value we achieve this critical value ?
Lets put this value into code as comment 
___
*[`app/network.go` line 153 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r-JP3EcGllGDLqme6:-N9r-JP3EcGllGDLqme7:bfsm3gc) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L153)):*
> ```Go
> type FeeModel struct {
> 	// InitialGasPrice is required if short average block gas is 0
> 	InitialGasPrice *big.Int
> ```

does it define gas price without any discount ?
___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-N9r7XbYDGH3a5NXtZAg:b-se3iah) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
> ```Go
> 
> 	// MaxDiscount is th maximum discount we offer on top of gas price if short average block gas is between long average block gas and escalation start block gas
> 	MaxDiscount float64
> ```

I always try to avoid using floats because of various calculation issues and use decimal instead

What about cosmos do they have some replacement for it or it is ok to use float


<!-- Sent from Reviewable.io -->

2022-08-19 17:26 UTC, ysv requested changes
I finished with the first batch of comments
Will continue to review on Monday

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131#-:-N9r7tD47MuWMVfyFVwl:b-q4ivun)* status: 17 of 22 files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-21 12:27 UTC, miladz68 reviewed
> Reviewed 1 of 3 files at r5, 2 of 3 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/app.go` line 418 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qIqI235UhHyIWSKkW:-NA-F_z_925UAKfFCkSw:b-ydcwdj) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L418)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

please read about other moving average types: weighted moving average (WMA) & Exponential Moving Average (EMA)

https://www.tradingview.com/support/solutions/43000502589-moving-average


Lets discuss if it makes sense to use WMA/EMA

</blockquote></details>

Only SMA applies here since we do not deal with WMA and EMA. Therefore adding those brings no new value IMO. 
___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-NA-FmvY0WgmWheHfrUQ:b-n0kj7z) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest a bit better names here:

`ShortSMABlockLength` or `ShortSMALengthInBlocks`

(same for LongAverage)

but we need to discuss previous comment first


</blockquote></details>

`BlockLengthForShortAverage` seems ok as well
___
*[`app/network.go` line 153 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r-JP3EcGllGDLqme6:-NA-MF-j4fUlhX41HCjv:bb77ufg) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L153)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it define gas price without any discount ?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2022-08-22 07:39 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9kfIpc4lQ1Lc6e5zUw:-NA3LDlfDve9d5ZgQf7a:bwjnca3) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. This sort of drop in simulations 
Is it expected and done intentionally ?
![Screenshot 2022-08-19 at 15.05.20.png](https://files.reviewableusercontent.io/images/reviewable/19859122/fqnprNQ6rpw4oOz8nLVm0Ak3/Screenshot%202022-08-19%20at%2015.05.20.png)
Screenshot 2022-08-19 at 15.05.20

2. can we have some values on x axis ?
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/C6lRvEykg195acduchwCw6QG/image.png)

3. can you pls do calculations via formula (exactly the same as you use in code) on 'Fee model Curve' sheet instead of hardcoding values. I thinks it should be 1st column - block size in gas, 2nd column (calculated) - gas price
</blockquote></details>

Ad.1. To limit the number of rows in the sheet (othrwise it's hard to work ith it) I printed only every 100th row.

___
___
*[`go.mod` line 16 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9XXc-bAPzcRWxo9Rsy:-NA3LW1t0AbkP2sw4qoa:bng0po6) ([raw file](https://github.com/coreumfoundation/coreum/blob/2301617b6dfcbd91334a8a0ed1470036801628d9/go.mod#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

surprisingly
is this dep expected to be here ?
Because gorilla is http stuff mostly AFAIK
</blockquote></details>

Some dependency imports it. Personally I don't need it.
___
*[`app/app.go` line 100 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qEKxH8GB0vSXF1mm2:-NA3LkvM1tuZD7RCkfMg:bsgys7e) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L100)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Do you have any other option for this module name ?
not sure why but fee seems to be too generic for me

WDYT about fee schedule eg. ?
</blockquote></details>

`feemodel`, `coreumfee`, `coreumfeemodel`?
___
*[`app/app.go` line 418 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qIqI235UhHyIWSKkW:-NA3MAnbC-5S0MLwpW5Z:b-baf4u6) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L418)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Only SMA applies here since we do not deal with WMA and EMA. Therefore adding those brings no new value IMO. 
</blockquote></details>

I'm not using SMA here because it requires storing gas used by all past 1000 blocks explicitly and on each block the history must be shifted to add new item at the end.

What I really use here is the EMA, just written in different form. It requires only two numbers as an input: previous average and current value. It means that only 1 value must be stored on every block (instead of 1000) to calculate price.

I just use the EMA equation in different form, which in general case is:

```
EMA(current) = alpha * EMA(previous) + (1 - alpha)*CurrentValue, where alpha is between 0 and 1
```

The `alpha` coefficient defines the priority of history vs new value. The equation above is basically an weighted average written in fancy form, after rewriting it a bit we get:

```
EMA(current) = ((N - 1) * EMA(previous) + CurrentValue) / N, where N is the number of blocks in our case, as in case of alpha, the higher the N the higher priority we give to the history vs new value. Basically alpha = (N - 1) / N
```

Now weighted average is written explicitly and this is the formula I use. By using EMA instead of SMA I introduce some error here.
To be perfectly ok I should use sth like this:

```
AVG(latest N items) = ((N - 1) * AVG(previous N-1 items) + CurrentValue) / N <-- this is SMA
```
Because then the weighted-average formula would give the same result as SMA. But as I said previously, it would require storing all N values. Instead I do:

```
AVG(latest N items) = ((N - 1) * AVG(previous latest N items) + CurrentValue) / N <-- this is EMA
```

The difference between two formulas is that the second one (EMA) converges slower than first one (SMA) to the new value in case of rapid change. But I believe it's negligible in our case. The advantage is that it's simpler to store and compute.
___
*[`app/network.go` line 67 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qtZxe0UfuCliEkYoK:-NA3TU9QAoUB1hdi6yPY:b-gbhac) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would probably put even bigger number here. Because we just multiplied it by 10 which means that if usually fee is 0.01-0.1$ now it becomes 0.1-1$ which is still small amount. 

I think we should put smth so big so none even wants to create a tx because of high fees.
E.g 1,000 or 10,000 times more

Also it would be nice to understand on which value we achieve this critical value ?
Lets put this value into code as comment 
</blockquote></details>

Please consider also that going really high will also set higher numbers when gas is lower. So it would be carefully combined with the right `inertia` coefficient.
___
*[`app/network.go` line 153 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r-JP3EcGllGDLqme6:-NA3TfPEByY0z28zs_8q:b2nign3) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L153)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

yep
___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-NA3TkzvCQKCvlhr-ZiN:b69tn2y) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I always try to avoid using floats because of various calculation issues and use decimal instead

What about cosmos do they have some replacement for it or it is ok to use float
</blockquote></details>

Cosmos does not operate at floats anyway. `float` is `float` there is strictly defined way of calculating them so the results are the same on all architectures (as long as they use the same IEEE industry standard and I believe no one tries to do it differently). Our fee model requires floating-point math by definition and it can't be avoided. I could define `MaxDiscountedGasPrice *big.Int` instead here but internally fee model will use floats anyway.


<!-- Sent from Reviewable.io -->

2022-08-22 07:59 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9kfIpc4lQ1Lc6e5zUw:-NA3Yazh69SokMtWMY8a:b-6xnbc0) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad.1. To limit the number of rows in the sheet (othrwise it's hard to work ith it) I printed only every 100th row.
</blockquote></details>

Ad. 3. It means I would have to rewrite this function: https://github.com/CoreumFoundation/coreum/blob/fee-model/x/fee/model.go#L26

to a formula in cells, which is a nightmare. That's why I created this unit test: https://github.com/CoreumFoundation/coreum/blob/fee-model/x/fee/model_sim_test.go#L24
allowing you to generate results for any parameters you like and paste them into the sheet

___


<!-- Sent from Reviewable.io -->

2022-08-22 08:18 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9kfIpc4lQ1Lc6e5zUw:-NA3cLZY9jdbBDiEnLPP:bfz7t3g) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad. 3. It means I would have to rewrite this function: https://github.com/CoreumFoundation/coreum/blob/fee-model/x/fee/model.go#L26

to a formula in cells, which is a nightmare. That's why I created this unit test: https://github.com/CoreumFoundation/coreum/blob/fee-model/x/fee/model_sim_test.go#L24
allowing you to generate results for any parameters you like and paste them into the sheet
</blockquote></details>

Ad. 2. Done

___


<!-- Sent from Reviewable.io -->

2022-08-22 12:46 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 20 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 100 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qEKxH8GB0vSXF1mm2:-NA4XdvPE0ee1apKV1SX:bllmib9) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L100)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would probably prefer to not mention coreum 
`feemodel` ok I personally like `feeschedule`

@miladz68 @dzmitryhil WDYT ?
</blockquote></details>

I don't like it as well, since I feel it might conflict, we can call it, "cfee" or "flexfee" :-)
___
*[`app/app.go` line 281 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4RM7E4xYj6CBQneOQ:-NA4RM7E4xYj6CBQneOR:b983dvr) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L281)):*
> ```Go
> 		// this line is used by starport scaffolding # stargate/app/storeKey
> 	)
> 	tkeys := sdk.NewTransientStoreKeys(paramstypes.TStoreKey, feetypes.TransientStoreKey)
> ```

What is the purpose of the "transientStoreKey" for the fee module?
___
*[`app/app.go` line 420 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4N8fF6TlmAl_DZiKf:-NA4N8fF6TlmAl_DZiKg:b26e11m) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L420)):*
> ```Go
> 	feeModule := fee.NewAppModule(appCodec, app.FeeKeeper,
> 		fee.Model{
> 			FeeDenom:                           ChosenNetwork.TokenSymbol(),
> ```

The Module ususaly keeps the params to be integrated with the chain, and keeper for the business logic, so most of those params should go to the keeper, also they should come from the genesis not from the constants (changeable from the Params none changeable form the root). 
___
*[`app/app.go` line 582 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4QCphCB1DrQBwATf7:-NA4QCpi9qEDqcRfOjI-:b-uw4jgs) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L582)):*
> ```Go
> 			FeegrantKeeper:     app.FeeGrantKeeper,
> 			GasPriceKeeper:     app.FeeKeeper,
> 			GasCollectorKeeper: app.FeeKeeper,
> ```

Since you all you need might be in fee module, you could integrate the ante handler into the fee module.
___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-NA4YdVu88mV8LmYtF8Q:b-le6ial) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about using decimal ?
</blockquote></details>

sdk.Dec can be used, and you can use the trancate or round to get the int and do what ever you need with the reminder.
The same is about the sdk.Int, we can use just 2 type for the most of those computations. 
___
*[`app/genesis/genesis.tmpl.json` line 1 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YxqBCPDECGnDR1DU:-NA4YxqBCPDECGnDR1DV:bk8gah5) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L1)):*
> ```JSON
> {
> ```

You have integrated the new modlue, so it have the initial root here, even if the genesis state is nil, so it would be nice to add it here as well
___
*[`app/genesis/genesis.tmpl.json` line 8 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YyqOCRlyKrBzLwYr:-NA4YyqOCRlyKrBzLwYs:b9q668i) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L8)):*
> ```JSON
>     "block": {
>       "max_bytes": "22020096",
>       "max_gas": "{{ .MaxBlockGas }}",
> ```

It would be nice to dicuss the relationship of it and our fee model
___
*[`x/fee/model.go` line 26 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4Txsr12qL2g8yAc51:-NA4Txsr12qL2g8yAc52:b-gkm0ce) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L26)):*
> ```Go
> }
> 
> func calculateNextGasPrice(feeModel Model, shortAverageGas int64, longAverageGas int64) *big.Int {
> ```

What is the purpose of the "*big.Int " here? And alow I saw the big.Float.
The SDK contains 2 types the sdk.Int (int) and sdk.Dec (fload) which can be used accoess the code, so ne need to upwrap the big.Int and wrapt again.



_Suggestion:_
```Go
The same you can do with the int and unit and so on, in the places where you mix them up, jut use the cosmos types.
```
___
*[`x/fee/model_sim_test.go` line 2 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4Wz6eC51kADDmYeI6:-NA4Wz6eC51kADDmYeI7:b-gblghc) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_sim_test.go#L2)):*
> ```Go
> //go:build simulation
> // +build simulation
> ```

This is teml file right?
___
*[`x/fee/module.go` line 120 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4V5foBwPiJmBPy3eI:-NA4V5foBwPiJmBPy3eJ:b-1vaxeg) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/module.go#L120)):*
> ```Go
> // no validator updates.
> func (am AppModule) InitGenesis(ctx sdk.Context, cdc codec.JSONCodec, data json.RawMessage) []abci.ValidatorUpdate {
> 	am.keeper.SetMinGasPrice(ctx, sdk.NewCoin(am.feeModel.FeeDenom, am.feeModel.InitialGasPrice))
> ```

The bad plcae to do it :-) The input is json data here, so if you don't use it here, don't do it here
___
*[`x/fee/module.go` line 138 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4_NSQ34EREgf3eoPe:-NA4_NSQ34EREgf3eoPf:b-2n8jxa) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/module.go#L138)):*
> ```Go
> // EndBlock returns the end blocker for the fee module. It returns no validator
> // updates.
> func (am AppModule) EndBlock(ctx sdk.Context, _ abci.RequestEndBlock) []abci.ValidatorUpdate {
> ```

Do we have an EndBlocker tests?
___
*[`x/fee/keeper/keeper.go` line 29 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4NtbFE_NwwwXnnA7d:-NA4NtbFE_NwwwXnnA7e:b-908xhh) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/keeper/keeper.go#L29)):*
> ```Go
> 
> var (
> 	gasTrackingKey       = []byte{0x00}
> ```

it's not a standard but ususlly thoe keys are stored in the keys.go file (on the same level as you use them now)
___
*[`x/fee/keeper/keeper.go` line 39 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4RXW6CvXEEJrhLVN-:-NA4RXW6CvXEEJrhLVN0:b1xgq4r) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/keeper/keeper.go#L39)):*
> ```Go
> 	tStore := ctx.TransientStore(k.transientStoreKey)
> 
> 	gasUsed := sdk.NewInt(0)
> ```

What is the pupose to init it with the 0 ?
If we fill it with the matshaller better to use "var your_var Type".


By the way there is sdk.ZeroInt() to create zero Ints. So you can use it in other places.
___
*[`x/fee/keeper/keeper.go` line 44 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4RyJB-TmNJEO3DDp_:-NA4RyJB-TmNJEO3DDpa:bebg84y) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/keeper/keeper.go#L44)):*
> ```Go
> 	if bz != nil {
> 		if err := gasUsed.Unmarshal(bz); err != nil {
> 			panic(err)
> ```

This is bad place for the panic, it's better to return the error, and let you consumer to decide what to do with it.
Same comment for other places with the panic in the Keeper.


<!--  [...]

2022-08-22 12:52 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 69 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SvuZ2n3kUjOGh40g:-NA4SvuZ2n3kUjOGh40h:b-cn7wij) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L69)):*
> ```Go
> 					MaxGasPrice:                        big.NewInt(15000),
> 					MaxDiscount:                        0.5,
> 					EscalationStartBlockGas:            37500000, // 300 * BankSend message
> ```

I'm just thinking of numbers we have to put here. Because 300 is number of txs in an "ideal" network environment.
But what if in real world case we get less throughput ? It means that fee escalation will never start even though the network is congested.
___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NA4SzwpE5rATg4m1HWG:bnfi35n) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
> ```Go
> 				},
> 				DeterministicGas: DeterministicGasConfig{
> 					BankSend: 125000,
> ```

How should we calculate this number ? E.g for other tx types ?
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NA4T7yH3h6_amjWVpRh:b-k8dfai) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
> ```Go
> 
> // FeeModel stores parameters defining fee model of coreum blockchain
> type FeeModel struct {
> ```

1. In general description for params is ok but since this params are core of our fee model I want to put a bit more love to their description mostly on adding examples of how each value works.
E.g:
"// InitialGasPrice is required if short average block gas is 0"
Change to:
"// InitialGasPrice is used when block gas short average is 0. This happens when last NumOfBlocksForShortAverageBlockGas (including/excluding current block?) has 0 gas size"

"// MaxGasPrice is required if short average block gas is greater than or equal to max block gas"
Change to:
"// MaxGasPrice is used when block gas short average is greater than or equal to MaxBlockGas. This value is used to limit gas price escalation to avoid having possible infinity GasPrice value otherwise."
...

2. Another approach is to add general comment on top of FeeModel struct and describe our fee behaviour there using names of fields defined in structure.

3. Do we include current block in short & long avarages ? AFAIK we don't

I would probably prefer 2nd approach.
___
*[`app/network.go` line 193 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TG_U78Je837x2-_e:-NA4TG_U78Je837x2-_f:bu6uzjh) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L193)):*
> ```Go
> 
> // Clone creates a copy of FeeConfig to allow to pass by value
> func (fc FeeConfig) Clone() FeeConfig {
> ```

Shouldn't we set `DeterministicGas` here also ?
You probably don't set it because it is just a single uint64 inside. But what if we use some other type there. Then we are likely to forget to change this clone method.
I would also suggest defining Clone for DeterministicGasConfig and use it, so the struct is responsible for making a copy of itself.
___
*[`app/network_test.go` line 273 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TNUX68PngoFG41Ur:-NA4TNUX68PngoFG41Us:btibf48) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network_test.go#L273)):*
> ```Go
> 	cfg.GenTxs[0] = []byte("tx2")
> 
> 	assertT.True(n1.FeeModel().InitialGasPrice.Cmp(big.NewInt(2)) == 0)
> ```

Minor:
1. `assertT.Equal(int64(10), n1.FeeModel().EscalationStartBlockGas)`
You can also use EqualValues() to avoid type casting int64().

2. I personally prefer to be explicity in tests & assert to values I expect not just true/false.
`assertT.True(n1.FeeModel().MaxGasPrice.Cmp(big.NewInt(4)) == 0)` ->
`assertT.EqualValues(0, n1.FeeModel().MaxGasPrice.Cmp(big.NewInt(4)))`
___
*[`app/network_test.go` line 324 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TTIT2aNG9DN5ajiK:-NA4TTIT2aNG9DN5ajiL:b-oguj3q) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network_test.go#L324)):*
> ```Go
> 		TokenSymbol:   TokenSymbolMain,
> 		Fee: FeeConfig{
> 			FeeModel: FeeModel{
> ```

Minor:
We have FeeModel define with the same values 3 times. I suggest moving this to func/var defined in a single place.
___
*[`integration-tests/auth/gas.go` line 96 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TlWf3P3RHmsos1ok:-NA4TlWf3P3RHmsos1ol:br2uoty) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/integration-tests/auth/gas.go#L96)):*
> ```Go
> 
> // TestGasLimitEqualToMaxBlockGas verifies that transaction requiring MaxBlockGas gas succeeds
> func TestGasLimitEqualToMaxBlockGas(chain testing.Chain) (testing.PrepareFunc, testing.RunFunc) {
> ```

I guess there is no way to make similar test cases with multiple txs because we can't be sure how they are divided between blocks etc. Is there a way ?
Because I can't tell that I'm 100% sure that fees work properly after these cases.
And that is probably where we might need some manual testing or you have any other idea of checking this ?


<!-- Sent from Reviewable.io -->

2022-08-22 13:03 UTC, dzmitryhil reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-22 13:44 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 36 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 281 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4RM7E4xYj6CBQneOQ:-NA4e5Of9IbOGGYRwgEy:b7wylt7) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L281)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the purpose of the "transientStoreKey" for the fee module?
</blockquote></details>

Collecting the sum of gas limits declared by all the transactions included in the block. I need it to calculate next gas price at the end of the block but I don't need to store it persistently.
___
*[`app/app.go` line 420 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4N8fF6TlmAl_DZiKf:-NA4eMEf6TSoWrxjzRd2:brp3zdl) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L420)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The Module ususaly keeps the params to be integrated with the chain, and keeper for the business logic, so most of those params should go to the keeper, also they should come from the genesis not from the constants (changeable from the Params none changeable form the root). 
</blockquote></details>

I my plan is to do it in next PR. In this one I wanted that we all agree just on the mathematical model of our fee (it has taken some time already)
___
*[`app/app.go` line 582 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4QCphCB1DrQBwATf7:-NA4eg5FEOgFaPVZR7At:b-3oulfq) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L582)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Since you all you need might be in fee module, you could integrate the ante handler into the fee module.
</blockquote></details>

Ante handler decorator is the interface with one method. So it's not possible to have to decorators defined by single struct. Also defined method `AnteHandle` is not so descriptive. In the first version of my code (it was not committed to the repo) I crated two methods in the module and created adapter encapsulating the method and exposing Ante handler decorator. But then decided that it is not the cosmos way of writing them.
___
*[`app/network.go` line 69 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SvuZ2n3kUjOGh40g:-NA4fQbc9rWLu2usjcvd:b-cn0fxq) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L69)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm just thinking of numbers we have to put here. Because 300 is number of txs in an "ideal" network environment.
But what if in real world case we get less throughput ? It means that fee escalation will never start even though the network is congested.
</blockquote></details>

I think it's too early to define "good" numbers. We will probably do it around lunching testnet.
___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NA4fnSP8pUQcdCMChWr:b-k808xr) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

How should we calculate this number ? E.g for other tx types ?
</blockquote></details>

There is an integration test for this: https://github.com/CoreumFoundation/coreum/blob/master/integration-tests/bank/gas.go#L23
We should have similar one for each deterministic message type.
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NA4g4B840vg2E6QhiT5:b-5fy75d) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. In general description for params is ok but since this params are core of our fee model I want to put a bit more love to their description mostly on adding examples of how each value works.
E.g:
"// InitialGasPrice is required if short average block gas is 0"
Change to:
"// InitialGasPrice is used when block gas short average is 0. This happens when last NumOfBlocksForShortAverageBlockGas (including/excluding current block?) has 0 gas size"

"// MaxGasPrice is required if short average block gas is greater than or equal to max block gas"
Change to:
"// MaxGasPrice is used when block gas short average is greater than or equal to MaxBlockGas. This value is used to limit gas price escalation to avoid having possible infinity GasPrice value otherwise."
...

2. Another approach is to add general comment on top of FeeModel struct and describe our fee behaviour there using names of fields defined in structure.

3. Do we include current block in short & long avarages ? AFAIK we don't

I would probably prefer 2nd approach.
</blockquote></details>

Ad. 3. No, because it's impossible. Once I proposed that eventually we could do it partially, so gas used in the block "up until" current transaction could be included. But we all agreed that it's a terrible idea.
___
*[`app/network.go` line 193 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TG_U78Je837x2-_e:-NA4gWkQ0bQaWyUJ5pzf:b-lbj6x8) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L193)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Shouldn't we set `DeterministicGas` here also ?
You probably don't set it because it is just a single uint64 inside. But what if we use some other type there. Then we are likely to forget to change this clone method.
I would also suggest defining Clone for DeterministicGasConfig and use it, so the struct is responsible for making a copy of itself.
</blockquote></details>

If we use some non-value types there then we will have to add `Clone()` to `DeterministicGas` too. By defining our world this way we would have to add `Clone` to all the types we want to use.
___
*[`app/network_test.go` line 273 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TNUX68PngoFG41Ur:-NA4h2d01rhnE5-km7YL:b1s3dvq) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network_test.go#L273)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Minor:
1. `assertT.Equal(int64(10), n1.FeeModel().EscalationStartBlockGas)`
You can also use EqualValues() to avoid type casting int64().

2. I personally prefer to be explicity in tests & assert to values I expect not just true/false.
`assertT.True(n1.FeeModel().MaxGasPrice.Cmp(big.NewInt(4)) == 0)` ->
`assertT.EqualValues(0, n1.FeeModel().MaxGasPrice.Cmp(big.NewInt(4)))`

</blockquote></details>

Ad.2. Ok I will do it this way, but here 0 is not the result of computation but weird indicator saying that two numbers are equal (`big` package is done in horrible way). That's why I prefer to use `True` because the question I'm asking is "Are two numbers equal" and the answer is true or false. I'm not asking the question "What is the value returned by this function computing something".
___
*[`app/genesis/genesis.tmpl.json` line 8 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YyqOCRlyKrBzLwYr:-NA4hhwlCoT12-LLdRaN:bglqld3) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L8)):*
<details><summ [...]

2022-08-23 07:15 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 9 of 24 files reviewed, 34 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-NA8AW703VVD3IUeWBSU:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> BlockLengthForShortAverage

a bit too long but better than current name
</blockquote></details>

Done.
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NA8DA-o0nsFkdakwQ_-:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad. 3. No, because it's impossible. Once I proposed that eventually we could do it partially, so gas used in the block "up until" current transaction could be included. But we all agreed that it's a terrible idea.
</blockquote></details>

Done.
___
*[`app/network.go` line 153 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r-JP3EcGllGDLqme6:-NA8F5LG-tMD4BwQYSBD:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L153)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see
I think the description here could be improved
Adding details in the next comment
</blockquote></details>

Done.
___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-NA8OLyx3pK63T_zl38w:b-4v8t5w) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

sdk.Dec can be used, and you can use the trancate or round to get the int and do what ever you need with the reminder.
The same is about the sdk.Int, we can use just 2 type for the most of those computations. 
</blockquote></details>

Done but using `sdk.Dec` is not possible because it doesn't implement division, and `Power` is implemented only for ints in exponent
___
*[`app/network_test.go` line 273 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TNUX68PngoFG41Ur:-NA8R4cJClPy1CUrkbx3:b36wxpz) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network_test.go#L273)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad.2. Ok I will do it this way, but here 0 is not the result of computation but weird indicator saying that two numbers are equal (`big` package is done in horrible way). That's why I prefer to use `True` because the question I'm asking is "Are two numbers equal" and the answer is true or false. I'm not asking the question "What is the value returned by this function computing something".
</blockquote></details>

Done, Ad.2. is no longer relevant
___
*[`app/network_test.go` line 324 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TTIT2aNG9DN5ajiK:-NA8SCFg4SroV4Gl_NjA:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network_test.go#L324)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Minor:
We have FeeModel define with the same values 3 times. I suggest moving this to func/var defined in a single place.
</blockquote></details>

Done
___
*[`x/fee/model.go` line 26 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4Txsr12qL2g8yAc51:-NA8STMoBaurQuBisoYY:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's just a leftover after initial approach of not using cosmos-sdk types. Will chnge it to cosmos ones.
</blockquote></details>

Done.
___
*[`x/fee/model.go` line 26 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dG-C6djF-DOzeBT8:-NA8WNu15FxnW0JhJGaQ:b-mvo05z) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. For me it is more natural to have these defined as a methods of feeModel struct:
`func (fm) calculateNextGasPrice(currentAverageGas int64, averageGas int64) *big.Int {`
`func (fm) computeMaxDiscountedGasPrice`

2. I suggest to keep only switch case in this method and put all calculation logic into separate methods so we have:
```golang
switch {
  case a:
    return calculate1(...)
  case b:
    return calculate2(...)
    // ...
    }
```

3. I suggest putting a link to the chart similar to one you provided in google sheet 1.
The best would be to use some website which builds chart from formula in URL & paste such a URL here.

4. I suggest to rename `currentAverageGas` -> `shortSMA` & `averageGas` -> `longSMA`

</blockquote></details>

Done, Ad. 3.: This chart can't be provided as a single formula, as I said in another comment the chart is generated by complex function
___
*[`x/fee/model.go` line 35 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dMaB4V7AN4L6pFCI:-NA8WgaKCv0E_IQQgXNO:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't know about this short way of defining floats. I still believe 2.0 is more familiar for everyone. Same for other places.
</blockquote></details>

Done.
___
*[`x/fee/model.go` line 41 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dV_mC08z8BhLz5O-:-NA8WkT5DhYvHb0nQxMg:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`new(big.Float).SetFloat64(math.Pow(x/width, inertia))` -> `big.NewFloat(...)`
</blockquote></details>

Done.
___
*[`x/fee/keeper/keeper.go` line 29 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4NtbFE_NwwwXnnA7d:-NA8Wv4k3YiZqVWqxIGQ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/keeper/keeper.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

O copied the structure from `bank` module :-). But ok, will move them there
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 07:18 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 9 of 24 files reviewed, 34 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 100 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qEKxH8GB0vSXF1mm2:-NA8Z19S7tg6A2dOcpzJ:b-wh0d08) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L100)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't like it as well, since I feel it might conflict, we can call it, "cfee" or "flexfee" :-)
</blockquote></details>

I prefer to not introduce yet another fancy word ("schedule" or "flex"), we ahve a lot of them already there


<!-- Sent from Reviewable.io -->

2022-08-23 07:19 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 9 of 24 files reviewed, 34 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/auth/ante/fee.go` line 42 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4d-ZRD1p5RvVLdvvG:-NA8ZNmD9GbtnH9i8LEI:b-ai23nn) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/auth/ante/fee.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad. 3. is done here: https://github.com/CoreumFoundation/coreum/blob/master/integration-tests/auth/gas.go#L17
</blockquote></details>

Ad. 2. is impossible now, because we don't have a way to introduce another token at the moment


<!-- Sent from Reviewable.io -->

2022-08-23 11:08 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 9 of 24 files reviewed, 26 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/fee/keeper/keeper.go` line 39 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4RXW6CvXEEJrhLVN-:-NA9NQ_Q0ghx88lNtbp3:b1z13pp) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/keeper/keeper.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> What is the pupose to init it with the 0 ?

Because we need to return some value for first block and 0 is very good value for that purpose

</blockquote></details>

In that case 



_Suggestion:_
```Go
then use sdk.NewInt(0) -> sdk.ZeroInt(), or better to return zero directly in case the "if bz != nil"
```


<!-- Sent from Reviewable.io -->

2022-08-23 11:09 UTC, dzmitryhil reviewed
> Reviewed 3 of 17 files at r1, 1 of 9 files at r2, 5 of 14 files at r3, 15 of 15 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 25 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-23 11:26 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 100 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qEKxH8GB0vSXF1mm2:-NA8qHPk3pEgdjtwW6C1:b-tp1ncb) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L100)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I prefer to not introduce yet another fancy word ("schedule" or "flex"), we ahve a lot of them already there
</blockquote></details>

`fee`
___
*[`app/app.go` line 582 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4QCphCB1DrQBwATf7:-NA9-MhsDtwQdCAF995t:b-xjczov) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L582)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ante handler decorator is the interface with one method. So it's not possible to have to decorators defined by single struct. Also defined method `AnteHandle` is not so descriptive. In the first version of my code (it was not committed to the repo) I crated two methods in the module and created adapter encapsulating the method and exposing Ante handler decorator. But then decided that it is not the cosmos way of writing them.
</blockquote></details>

Note: This comment is about moving ante handers to fee module 
___
*[`app/network.go` line 67 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qtZxe0UfuCliEkYoK:-NA90GA84FLt1s18ywPB:b-pje2sx) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought it works in a bit different way

Needs to be discussed on call
</blockquote></details>

MaxGasPrice should be increased to 1000*initialGasPrice
___
*[`app/network.go` line 69 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SvuZ2n3kUjOGh40g:-NA92nURAdTTyZnCLFVG:b-2u7zyy) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think it's too early to define "good" numbers. We will probably do it around lunching testnet.
</blockquote></details>

lets add todo to adjust these numbers before doing testnet/mainnet launch
___
*[`app/genesis/genesis.tmpl.json` line 8 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YyqOCRlyKrBzLwYr:-NA99BTTCDzK7ADF2MSZ:b-exo303) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Our fee model assumes that block does not use more gas, so we enforce it on the tendermint level.
</blockquote></details>

lets add todo here also to be adjusted before testnet & mainnet



_Code quote:_
```JSON
MaxBlockGas
```
___
*[`x/auth/ante/ante.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lm06-eUWS5bOFhcb:-NA9BNHl3UR_hjNYsoGf:bfewgmf) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

For me personally it makes sense to keep them separately

@miladz68 if you have strong opinion on this I don't mind discussion on the call
</blockquote></details>


lets merge them
___
*[`x/auth/ante/ante.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lr4-5M0u_BvP-HnS:-NA9BLcX9FM9mJ98BJte:biyzbuv) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

For me personally it makes sense to keep them separately

@miladz68 if you have strong opinion on this I don't mind discussion on the call
</blockquote></details>

lets merge them
___
*[`x/fee/model_sim_test.go` line 1 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9CFSm5lyEekFVcZlN:-NA9CFSm5lyEekFVcZlO:bo60vwm) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/model_sim_test.go#L1)):*
> ```Go
> //go:build simulation
> ```

lets add spec in spec folder for this module in cosmos-sdk style
It is better to do this in a separate PR probably
___
*[`x/fee/model_sim_test.go` line 31 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9CVPBAR48R9cSoL1W:-NA9CVPBAR48R9cSoL1X:b-fc602e) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/model_sim_test.go#L31)):*
> ```Go
> 	}
> 	// Output: list of gas prices for each gas usage
> 	// https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=0
> ```

we can reference specs here
___
*[`x/fee/module.go` line 120 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4V5foBwPiJmBPy3eI:-NA9EH4Q2-hJSY_U3VN4:bb4xj4d) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/module.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So it should first be set in genesis.json and then read from `data` here, right?
</blockquote></details>

to be moved to keeper
___
*[`x/fee/module.go` line 138 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4_NSQ34EREgf3eoPe:-NA9EhRF6gIZ-L83ThGl:bvs72mu) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/module.go#L138)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

add TODO to add these tests
___
*[`x/fee/keeper/keeper.go` line 115 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9GSz16fVydP9ETWyV:-NA9GSz16fVydP9ETWyW:b-jasqpk) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/keeper/keeper.go#L115)):*
> ```Go
> 	bz := store.Get(gasPriceKey)
> 	if bz == nil {
> 		panic(errors.New("minimum gas price is not set"))
> ```

we should return initial gas price if minimum gas price is not set
___
*[`x/fee/types/key.go` line 6 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4duq75pQtUPT7XCoN:-NA9GdsG7s0t77bgVj_J:buyhlwg) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/types/key.go#L6)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`feemodel` maybe?
</blockquote></details>

rename to 'fee'
___
*[`x/fee/model_test.go` line 14 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9DgFr15i5_QDQN8E8:-NA9DgFr15i5_QDQN8E9:bndi506) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/model_test.go#L14)):*
> ```Go
> 	maxGasPrice           int64 = 200000000
> 	maxDiscount                 = 0.5
> 	minDiscountedGasPrice       = int64((1. - maxDiscount) * float64(initialGasPrice))
> ```

`gasPriceWithMaxDiscount` pls check other places also


<!-- Sent from Reviewable.io -->

2022-08-23 12:12 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 15 of 24 files reviewed, 26 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-NA9Z2WX0eElsy1Uo6jM:b-4m2b96) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After discussion, how should it be named?
___
*[`app/app.go` line 582 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4QCphCB1DrQBwATf7:-NA9ZoGEDssm1JLIZ6wk:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L582)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Note: This comment is about moving ante handers to fee module 
</blockquote></details>

Done
___
*[`app/network.go` line 67 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qtZxe0UfuCliEkYoK:-NA9_3MiCOQrEtAmXrh6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

MaxGasPrice should be increased to 1000*initialGasPrice
</blockquote></details>

Done.
___
*[`app/network.go` line 69 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SvuZ2n3kUjOGh40g:-NA9_H-LB98lMaRxxDo0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L69)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets add todo to adjust these numbers before doing testnet/mainnet launch
</blockquote></details>

Done.
___
*[`app/genesis/genesis.tmpl.json` line 8 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YyqOCRlyKrBzLwYr:-NA9_MGB5KpDaRsHzgYa:bm0gusi) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets add todo here also to be adjusted before testnet & mainnet
</blockquote></details>

comments can't be added to json file
___
*[`x/fee/model_sim_test.go` line 31 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9CVPBAR48R9cSoL1W:-NA9_dS1Ekqk0ysOllgj:b-e4ijp5) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/model_sim_test.go#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we can reference specs here
</blockquote></details>

once spec is created in separate PR
___
*[`x/fee/keeper/keeper.go` line 39 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4RXW6CvXEEJrhLVN-:-NA9aYuH1e-bCve9Qofi:b-xkvl7e) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/keeper/keeper.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In that case 
</blockquote></details>

but this function returns gas, and cosmos sdk uses `int64` for gas everywhere, not `sdk.Int`
___
*[`x/fee/types/key.go` line 6 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4duq75pQtUPT7XCoN:-NA9avaQEVDCrd5a38Zp:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/types/key.go#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

rename to 'fee'
</blockquote></details>

Done.
___
*[`x/fee/model_test.go` line 14 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9DgFr15i5_QDQN8E8:-NA9aHS-5z8_sTmh_vmr:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/model_test.go#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`gasPriceWithMaxDiscount` pls check other places also
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 12:28 UTC, dzmitryhil reviewed
> Reviewed 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 25 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-23 12:53 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 16 of 25 files reviewed, 25 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`app/genesis/genesis.tmpl.json` line 1 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YxqBCPDECGnDR1DU:-NA9dBQz2kdQStasDhu6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You have integrated the new modlue, so it have the initial root here, even if the genesis state is nil, so it would be nice to add it here as well
</blockquote></details>

Done.
___
*[`x/auth/ante/ante.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lm06-eUWS5bOFhcb:-NA9fLEd9VxMNAfMSob3:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets merge them
</blockquote></details>

Done.
___
*[`x/auth/ante/ante.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lr4-5M0u_BvP-HnS:-NA9fMt33ZZs0QXG9AuB:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets merge them
</blockquote></details>

Done.
___
*[`x/fee/module.go` line 120 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4V5foBwPiJmBPy3eI:-NA9gqui3QC8xO96dQEL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/module.go#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to be moved to keeper
</blockquote></details>

Done.
___
*[`x/fee/keeper/keeper.go` line 115 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9GSz16fVydP9ETWyV:-NA9goDLEZVJG9Eus_vR:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f670cf654a50da800f6a772b9678a6967a14e767/x/fee/keeper/keeper.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we should return initial gas price if minimum gas price is not set
</blockquote></details>

Done.
___
*[`x/auth/ante/fee.go` line 42 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4d-ZRD1p5RvVLdvvG:-NA9hVsk7f1Pl4SJg_K4:b1bdygb) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/auth/ante/fee.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad. 2. is impossible now, because we don't have a way to introduce another token at the moment
</blockquote></details>

Ad. 1. done


<!-- Sent from Reviewable.io -->

2022-08-23 13:53 UTC, ysv requested changes
> Reviewed 3 of 14 files at r3, 6 of 15 files at r10, 4 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 10 of 25 files reviewed, 18 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NA9cdIbDdul1EUOaXX4:b-mnzuyt) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is an integration test for this: https://github.com/CoreumFoundation/coreum/blob/master/integration-tests/bank/gas.go#L23
We should have similar one for each deterministic message type.
</blockquote></details>

what does `result.GasUsed` mean here then ?

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/GdhzsCNqJg6ejitbuyRcnfHW/image.png)
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NA9eOnQ-8a-h3u1c-Yr:b-awwbw5) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
> Ad. 3. No, because it's impossible. Once I proposed that eventually we could do it partially, so gas used in the block "up until" current transaction could be included. But we all agreed that it's a terrible idea.

ok
make sure to add a comment somewhere so we can easily figure out in the future
___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-NA9egA21tiMQj1rTUg3:b-s858ft) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done but using `sdk.Dec` is not possible because it doesn't implement division, and `Power` is implemented only for ints in exponent
</blockquote></details>

discussed on the call that it has everything needed pls check
___
*[`app/network.go` line 193 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TG_U78Je837x2-_e:-NA9gVUMDeSb5W5_9H9F:b6lkx3k) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L193)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If we use some non-value types there then we will have to add `Clone()` to `DeterministicGas` too. By defining our world this way we would have to add `Clone` to all the types we want to use.
</blockquote></details>

I meant to do this explicitly
But we don't have this method now so it is not relevant anymore
___
*[`app/network.go` line 152 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9dDWA1AeiX9s2-TnC:-NA9dDWA1AeiX9s2-TnD:b-urvmsj) ([raw file](https://github.com/coreumfoundation/coreum/blob/5389be3a8195715313202942a2dd2120ba9e29ed/app/network.go#L152)):*
> ```Go
> // FeeModel stores parameters defining fee model of coreum blockchain
> // There are four regions on the fee model curve
> // - between 0 and "long average block gas" where gas price goes down from InitialGasPrice to minimum discounted gas price (InitialGasPrice * (1 -MaxDiscount))
> ```

where gas price goes down linearly/ quadratically / exponentially   ?
___
*[`app/network.go` line 152 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9dnDJ1Df0I1zHcc4g:-NA9dnDJ1Df0I1zHcc4h:b-y6dyp) ([raw file](https://github.com/coreumfoundation/coreum/blob/5389be3a8195715313202942a2dd2120ba9e29ed/app/network.go#L152)):*
> ```Go
> // FeeModel stores parameters defining fee model of coreum blockchain
> // There are four regions on the fee model curve
> // - between 0 and "long average block gas" where gas price goes down from InitialGasPrice to minimum discounted gas price (InitialGasPrice * (1 -MaxDiscount))
> ```

to minimum discounted gas price -> to gas price with maximum discount

Pls check other places also



_Code quote:_
```Go
rom InitialGasPrice to minimum discounted gas price
```
___
*[`app/genesis/genesis.tmpl.json` line 8 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4YyqOCRlyKrBzLwYr:-NA9gr2r1UWasN1GycQ0:bttst4m) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/genesis/genesis.tmpl.json#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

comments can't be added to json file
</blockquote></details>

lets add to the place where we render this json and pass .MaxBlockGas
___
*[`integration-tests/auth/gas.go` line 96 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TlWf3P3RHmsos1ok:-NA9h5ke9g4KE2uazA_0:b90c1qa) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/integration-tests/auth/gas.go#L96)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> Is there a way ?

no

> And that is probably where we might need some manual testing or you have any other idea of checking this ?

There are many tests running in parallel, all generating transactions. So you really don't know in which place on fee model curve test is at the moment. To do it correctly we would have to create separate chain for this single model, being able to pause it at particular block and enforcing it to include transaction in defined block number. Short answer: not possible.
</blockquote></details>

yes makes sense
Discussed on the call and decided to proceed with simchain
___
*[`integration-tests/bank/transfer.go` line 53 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4cljcBl9TBFEqA81t:-NA9hQ3r0ir54UFjh8sp:b-4kyuep) ([raw file](https://github.com/coreumfoundation/coreum/blob/1975f24ddd435ccb6e16a29df4e5c3efd185c664/integration-tests/bank/transfer.go#L53)):*
> Not really, most test use initial gas price, because it is really unlikely that integration test will enter escalation region.

yes  initial price that is what I menat

> Is it a good PR for making this proposal?

not sure
lets add todo if you like the idea
___
*[`x/fee/model.go` line 26 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dG-C6djF-DOzeBT8:-NA9hujc4XGXSLHVRx_P:bk438pn) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done, Ad. 3.: This chart can't be provided as a single formula, as I said in another comment the chart is generated by complex function
</blockquote></details>

ad. 3: ok
___
*[`x/fee/model.go` line 35 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dMaB4V7AN4L6pFCI:-NA9iiom58wguCsEVUVz:bldujru) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

a few other places

![Screenshot 2022-08-23 at 14.43.18.png](https://files.reviewableusercontent.io/images/reviewable/19859122/8Ka7hnbxpdmWmcUZ702gb-z2/Screenshot%202022-08-23%20at%2014.43.18.png)
Screenshot 2022-08-23 at 14.43.18

pls check if I didn't skip anything else
___
*[`x/fee/model.go` line 42 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dPr18WI4EuOTehe0:-NA9izK6By03JUFIPjq0:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, it tells us how much precision was lost during the convertion. But we don't care because we need  [...]

2022-08-23 14:14 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 10 of 25 files reviewed, 18 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NA9zS2P2GZipglUg8iF:bp4udtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what does `result.GasUsed` mean here then ?

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/GdhzsCNqJg6ejitbuyRcnfHW/image.png)

</blockquote></details>

amount of gas consumed by the transaction
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NA9zdwm72CorEsVsPpZ:b-mx4r8g) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Ad. 3. No, because it's impossible. Once I proposed that eventually we could do it partially, so gas used in the block "up until" current transaction could be included. But we all agreed that it's a terrible idea.

ok
make sure to add a comment somewhere so we can easily figure out in the future
</blockquote></details>

comment on what?
___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-NA9zils36vI96QV-aBo:b-akcdid) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

discussed on the call that it has everything needed pls check
</blockquote></details>

ah, forgot about it
___
*[`integration-tests/auth/gas.go` line 96 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TlWf3P3RHmsos1ok:-NA9zwil2TdyFwQKA-j2:b-eia5i5) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/integration-tests/auth/gas.go#L96)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes makes sense
Discussed on the call and decided to proceed with simchain
</blockquote></details>

please unblock
___
*[`x/auth/ante/fee.go` line 42 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4d-ZRD1p5RvVLdvvG:-NAA-7JT7KfJ052q1QEw:bwq2j0c) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/auth/ante/fee.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

2 but can't we just set fee as 100ABC because of client ? Or because we don't have asset issuance ? any other reason ?
</blockquote></details>

we don't have asset issuance and horn of plenty does not hold any other coin despite `core`


<!-- Sent from Reviewable.io -->

2022-08-23 14:51 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 10 of 25 files reviewed, 17 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/gas.go` line 96 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4TlWf3P3RHmsos1ok:-NAAAx326gdB-Gdj-Sdj:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/integration-tests/auth/gas.go#L96)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please unblock
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-08-23 15:01 UTC, dzmitryhil reviewed
> Reviewed 4 of 9 files at r12, 10 of 10 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 10:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 16 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 159 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9r7XbXCKh_ogYSPQOE:-NAEFIudCIwsy9_WMe4U:b-h8hi4e) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L159)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ah, forgot about it
</blockquote></details>

I think this part: `math.Pow(1.0-m.MaxDiscount, float64(shortEMA)/float64(longEMA))` can't be written using `sdk.Dec`. There is a way of converting float64 to string and then string to sdk.Dec but I'm really against making this kind of gymnastics.
___
*[`app/network.go` line 152 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9dDWA1AeiX9s2-TnC:-NAE59WzCrIKY1AsgmEo:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/5389be3a8195715313202942a2dd2120ba9e29ed/app/network.go#L152)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

where gas price goes down linearly/ quadratically / exponentially   ?
</blockquote></details>

Done.
___
*[`app/network.go` line 152 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9dnDJ1Df0I1zHcc4g:-NAE5GODChJSrQKACJLM:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/5389be3a8195715313202942a2dd2120ba9e29ed/app/network.go#L152)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to minimum discounted gas price -> to gas price with maximum discount

Pls check other places also
</blockquote></details>

Done.
___
*[`app/genesis/genesis.tmpl.json` line 212 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAA3nSx95oeUO26iQEL:-NAE6eqpA3ZNQHunQpjt:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ee53a815bee6af454fe8e0ed9ffaf85906f5419a/app/genesis/genesis.tmpl.json#L212)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

fee or feemodel ?
</blockquote></details>

Done.
___
*[`integration-tests/bank/transfer.go` line 53 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4cljcBl9TBFEqA81t:-NAE749eBKVDK1fUP6Ya:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1975f24ddd435ccb6e16a29df4e5c3efd185c664/integration-tests/bank/transfer.go#L53)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Not really, most test use initial gas price, because it is really unlikely that integration test will enter escalation region.

yes  initial price that is what I menat

> Is it a good PR for making this proposal?

not sure
lets add todo if you like the idea
</blockquote></details>

Done.
___
*[`x/auth/ante/ante.go` line 18 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAA44h-CnFEh73surAb:-NAE7B3rBtjV2mylr-Ph:b-8p2vr) ([raw file](https://github.com/coreumfoundation/coreum/blob/ee53a815bee6af454fe8e0ed9ffaf85906f5419a/x/auth/ante/ante.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

we will move the ante handler later?
</blockquote></details>

WDYM? feemodel-specific ante handler decorator is now in `x/feemodel/ante/ante.go` 
___
*[`x/fee/model.go` line 35 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4dMaB4V7AN4L6pFCI:-NAE82ld07yBRqlcTZvt:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

a few other places

![Screenshot 2022-08-23 at 14.43.18.png](https://files.reviewableusercontent.io/images/reviewable/19859122/8Ka7hnbxpdmWmcUZ702gb-z2/Screenshot%202022-08-23%20at%2014.43.18.png)
Screenshot 2022-08-23 at 14.43.18

pls check if I didn't skip anything else
</blockquote></details>

Done.
___
*[`x/fee/model.go` line 23 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA9i9WaB43M13sszc4d:-NAE7akkArU66ceWvZoL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/5389be3a8195715313202942a2dd2120ba9e29ed/x/fee/model.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets not mention doc directly because it is  private and code in open

lets refer to `asset/image` once we have doc for this module
</blockquote></details>

Done.
___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAEEzra0DFl6AO2KjDL:b-32cy1s) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. Currently they are all the same so l would prefer to unify at least for now. And I think they are likely to always be the same because we want our envs to be as similar as possible
</blockquote></details>

Created common config in app/network.go` but it can't be imported here because of circular dependency


<!-- Sent from Reviewable.io -->

2022-08-24 16:00 UTC, dzmitryhil reviewed
> Reviewed 5 of 6 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 14 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 16:04 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/model_test.go` line 11 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAF_PeVBUBR88basmn5:-NAF_PeVBUBR88basmn6:bb8d3tl) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model_test.go#L11)):*
> ```Go
> 
> var (
> 	initialGasPrice         int64 = 100000000
> ```

As we agreed we want to have the test with the huge initial values


<!-- Sent from Reviewable.io -->

2022-08-25 06:46 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 18 of 25 files reviewed, 16 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAIjv--CEVKZZl2OsKS:-NAIjv-0ALIP5jPrsje0:bhnre3x) (no related file):*
Fee model was adjusted, so all the computations there might be done using `sdk.Dec` type. Take a look at updated charts:

https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=0
https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=940400407

___


<!-- Sent from Reviewable.io -->

2022-08-25 06:53 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 18 of 25 files reviewed, 16 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`x/feemodel/model_test.go` line 11 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAF_PeVBUBR88basmn5:-NAIleKg1YL_Kgwnvo5O:b290q2q) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model_test.go#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As we agreed we want to have the test with the huge initial values
</blockquote></details>

Done. InitialGasPrice is now 10 times higher than initial total supply for mainnet


<!-- Sent from Reviewable.io -->

2022-08-25 06:58 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 18 of 25 files reviewed, 16 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/model_test.go` line 11 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAF_PeVBUBR88basmn5:-NAImYfv8S3o7V1CGgGz:br5ijy2) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model_test.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done. InitialGasPrice is now 10 times higher than initial total supply for mainnet
</blockquote></details>

Hm, what about much highter I mean 10^10 times for example. To have extreamy high values.


<!-- Sent from Reviewable.io -->

2022-08-25 08:35 UTC, dzmitryhil requested changes
> Reviewed 6 of 7 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 18 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6wSB37TbK3lTmxEY:-NAJ6wSB37TbK3lTmxEZ:b-683nhh) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
> ```Go
> 
> 	// EscalationStartBlockGas defines block gas usage where gas price escalation starts if short average block gas is higher than this value.
> 	EscalationStartBlockGas int64
> ```

Why don't we use the sdk types here? And in there FeeModel calculations?
___
*[`x/feemodel/model.go` line 44 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6ZpJBtlDLBGQvoUO:-NAJ6ZpJBtlDLBGQvoUP:b-jv97hj) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/x/feemodel/model.go#L44)):*
> ```Go
> 	const exponent = 2
> 	height := sdk.NewDecFromInt(m.MaxGasPrice.Sub(gasPriceWithMaxDiscount))
> 	width := sdk.NewDecFromInt(sdk.NewInt(m.MaxBlockGas - m.EscalationStartBlockGas))
> ```

There is a methods invVal.ToDec() -> to convert Int to Dec. Use it instead for all such calls.


<!-- Sent from Reviewable.io -->

2022-08-25 10:14 UTC, ysv requested changes
> Reviewed 2 of 9 files at r12, 5 of 10 files at r13, 2 of 6 files at r15, 3 of 4 files at r16, 5 of 7 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 17 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAIjv--CEVKZZl2OsKS:-NAJPwLB69SCsLxAM0L3:b-olr1a8) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Fee model was adjusted, so all the computations there might be done using `sdk.Dec` type. Take a look at updated charts:

https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=0
https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=940400407
</blockquote></details>

chart doesn't use new MaxGasPrice which is x1000 from initial

___
___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NAEvH6h29BmgmMKhcfF:btvqsbz) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

amount of gas consumed by the transaction
</blockquote></details>

but how does it work if we have fixed gas by tx type ? So it should always be 125000 for bank send, isn't it ?

Or it returns sort of "real" gas consumed ?
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NAEwAl85Q5DKI1uLx9n:b5wu4f8) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

comment on what?
</blockquote></details>

add comment to describe how we calculate our averages and that we don't include current block for average value
___
*[`app/network.go` line 142 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAEvnzQA7LHCjgx7M3C:-NAEvnzQA7LHCjgx7M3D:bjnzik5) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/app/network.go#L142)):*
> ```Go
> // There are four regions on the fee model curve
> // - between 0 and "long average block gas" where gas price goes down exponentially from InitialGasPrice to gas price with maximum discount (InitialGasPrice * (1 -MaxDiscount))
> // - between "long average block gas" and EscalationStartBlockGas where we offer minimum discounted gas price all the time
> ```

minimum discounted gas price -> gas price with maximum discount
___
*[`app/network.go` line 143 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAEvuAq2Nwlkuk0Q3dN:-NAEvuAq2Nwlkuk0Q3dO:bjnzik5) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/app/network.go#L143)):*
> ```Go
> // - between 0 and "long average block gas" where gas price goes down exponentially from InitialGasPrice to gas price with maximum discount (InitialGasPrice * (1 -MaxDiscount))
> // - between "long average block gas" and EscalationStartBlockGas where we offer minimum discounted gas price all the time
> // - between EscalationStartBlockGas and MaxBlockGas where price goes up rapidly (being an output of a power function) from minimum discounted gas price to MaxGasPrice
> ```

minimum discounted gas price -> gas price with maximum discount
___
*[`app/network.go` line 150 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJSWK-2SZzlId2fVSw:-NAJSWK-2SZzlId2fVSx:b-pb9353) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L150)):*
> ```Go
> // The input (x value) for that function is calculated by taking short block gas average.
> // Price (y value) being an output of the fee model is used as the minimum gas price for next block.
> type FeeModel struct {
> ```

Why do we need 2 separate structs if they are almost identical
![Screenshot 2022-08-25 at 12.03.48.png](https://files.reviewableusercontent.io/images/reviewable/19859122/fCFjGTG8N3o1xiJnJiLJNad8/Screenshot%202022-08-25%20at%2012.03.48.png)
Screenshot 2022-08-25 at 12.03.48

Why don't we just use `feemodel.Model` everywhere ?
___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJO6cCAwpgF7PJJtYL:-NAJO6cCAwpgF7PJJtYM:bkbesqf) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
> ```Go
> 
> 	// EscalationStartBlockGas defines block gas usage where gas price escalation starts if short average block gas is higher than this value.
> 	EscalationStartBlockGas int64
> ```

I'm also wondering why we use sdk.Int in some places and in other int64/uint
___
*[`x/auth/ante/ante.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lm06-eUWS5bOFhcb:-NAJPAqm4JnupOMp1uls:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`x/auth/ante/ante.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N96Lr4-5M0u_BvP-HnS:-NAJPDfq0Fcy0LNfUpfI:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a3918a4b91a78af4580d1208df5e97205b405441/x/auth/ante/ante.go#L62)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`x/auth/ante/fee.go` line 42 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4d-ZRD1p5RvVLdvvG:-NAJPNq482AQEOvEeM-I:b-e7b81s) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/auth/ante/fee.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we don't have asset issuance and horn of plenty does not hold any other coin despite `core`
</blockquote></details>

ok
can we add TODO to have a test for this case ?
___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAJTDW82YWlKVs4cjkm:bctus7v) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Created common config in app/network.go` but it can't be imported here because of circular dependency
</blockquote></details>

I see
I still believe this is an issue because we keep changing our real-world values but in tests we forget to do this 
Any ideas on how to avoid this ?
___
*[`x/feemodel/model.go` line 24 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAFMCCw-bLhg9mjQDXb:-NAFMCCw-bLhg9mjQDXc:b-j534io) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model.go#L24)):*
> ```Go
> // CalculateNextGasPrice calculates minimum gas price for next block
> // Chart showing a sample output of the fee mdoel: https://docs.google.com/spreadsheets/d/1YTvt06CIgHpx5kgOXk2BK-kuJ63DwVYtGfDEHLxvCZQ/edit#gid=0
> func (m Model) CalculateNextGasPrice(shortEMA int64, longEMA int64) sdk.Int {
> ```

can we have fuzz testing for this method also ?
___
*[`x/feemodel/model_sim_test.go` line 13 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJPimZ9irvUHM4LV6W:-NAJPim_8_dcrZOTUrae:b-1etwi2) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/x/feemodel/model_sim_test.go#L13)):*
> ```Go
> 
> var (
> 	feeMo [...]

2022-08-25 10:15 UTC, miladz68 reviewed
> Reviewed 1 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-NAJUh2tAMHFqCuHakIq:bti7ovy) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After discussion, how should it be named?
</blockquote></details>

I still suggest `ShortAverageBlockLength`


<!-- Sent from Reviewable.io -->

2022-08-25 10:27 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 22 of 26 files reviewed, 15 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6wSB37TbK3lTmxEY:-NAJRw5x8XF7xm6PQxUc:b-tw7jir) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't we use the sdk types here? And in there FeeModel calculations?
</blockquote></details>

@dzmitryhil @ysv : We do, sdk uses int64 or uint64 for gas depending on place. An example:

```go
	FeeTx interface {
		Tx
		GetGas() uint64   <---- here
		GetFee() Coins
		FeePayer() AccAddress
		FeeGranter() AccAddress
	}
```
___
*[`x/feemodel/model.go` line 44 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6ZpJBtlDLBGQvoUO:-NAJRe68EEdVd4vpbhGA:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/x/feemodel/model.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

There is a methods invVal.ToDec() -> to convert Int to Dec. Use it instead for all such calls.
</blockquote></details>

Done.
___
*[`x/feemodel/model_test.go` line 11 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAF_PeVBUBR88basmn5:-NAJRhJZ1MllMGMWD_Wo:bfz2xwq) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model_test.go#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Hm, what about much highter I mean 10^10 times for example. To have extreamy high values.
</blockquote></details>

@ysv ? Previously when I created an account with extremely high balance you argued that I should use more or less realistic numbers.


<!-- Sent from Reviewable.io -->

2022-08-25 10:32 UTC, miladz68 reviewed
> Reviewed 2 of 9 files at r12, 6 of 10 files at r13, 1 of 1 files at r14, 2 of 6 files at r15, 3 of 4 files at r16, 4 of 7 files at r17, 1 of 1 files at r18, 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-25 10:54 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NAJb4CKB6dB8z563CQc:b-c54kzg) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but how does it work if we have fixed gas by tx type ? So it should always be 125000 for bank send, isn't it ?

Or it returns sort of "real" gas consumed ?
</blockquote></details>

yes, it uses the real gas used by the transaction, not the one we set as deterministic
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NAJb_nW5f9ruPKWtI2T:b-u3wpct) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

add comment to describe how we calculate our averages and that we don't include current block for average value
</blockquote></details>

Both things are there already:

"Price (y value) being an output of the fee model is used as the minimum gas price for next block."
"NewAverage = ((ShortAverageInertia - 1)*PreviousAverage + GasUsedByCurrentBlock) / ShortAverageInertia"
___
*[`app/network.go` line 150 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJSWK-2SZzlId2fVSw:-NAJc1AJ-spkr31F4OGz:b-xbm2se) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L150)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Why do we need 2 separate structs if they are almost identical
![Screenshot 2022-08-25 at 12.03.48.png](https://files.reviewableusercontent.io/images/reviewable/19859122/fCFjGTG8N3o1xiJnJiLJNad8/Screenshot%202022-08-25%20at%2012.03.48.png)
Screenshot 2022-08-25 at 12.03.48

Why don't we just use `feemodel.Model` everywhere ?
</blockquote></details>

leftover after using non-cosmos types, will do
___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAJcecJARk7LMwqQX6Y:bncwzto) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
> Any ideas on how to avoid this ?

No
___
*[`x/feemodel/model_sim_test.go` line 13 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJPimZ9irvUHM4LV6W:-NAJcPDDEjJxhgYnnL68:b-6zr3ur) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/x/feemodel/model_sim_test.go#L13)):*
> can we use globally defined Model the same as for testnet/mainnet/devnet ?

Once @miladz68 moves `NetworkConfig` out of `app` package, now importing `app` here will cause circular dependency


<!-- Sent from Reviewable.io -->

2022-08-25 11:17 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAJhqXR5N1iQhHiKkI3:br4zlfw) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> Any ideas on how to avoid this ?

No
</blockquote></details>

Now I see that we could move default values to `feemodel` package and use it in `app` package. But storing network-specific data in module package seems weird to me


<!-- Sent from Reviewable.io -->

2022-08-25 11:29 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-NAJir2d6c0fh5YjVYW0:b7rhc19) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I still suggest `ShortAverageBlockLength`
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/qGmk7p8gPZ3KlmZN41BUqkJu/image.png)
___
*[`app/network.go` line 75 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4SzwpE5rATg4m1HWF:-NAJivQR45nFqK5hPV5Z:be802e1) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, it uses the real gas used by the transaction, not the one we set as deterministic
</blockquote></details>

interesting 
ok
___
*[`app/network.go` line 151 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4T7yH3h6_amjWVpRg:-NAJj08Z8o8B50KYMZmA:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/network.go#L151)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Both things are there already:

"Price (y value) being an output of the fee model is used as the minimum gas price for next block."
"NewAverage = ((ShortAverageInertia - 1)*PreviousAverage + GasUsedByCurrentBlock) / ShortAverageInertia"
</blockquote></details>

ok
___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6wSB37TbK3lTmxEY:-NAJjyXo62kR-ITCz98G:b5wiclh) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@dzmitryhil @ysv : We do, sdk uses int64 or uint64 for gas depending on place. An example:

```go
	FeeTx interface {
		Tx
		GetGas() uint64   <---- here
		GetFee() Coins
		FeePayer() AccAddress
		FeeGranter() AccAddress
	}
```
</blockquote></details>

I just want to make sure it is really required to use both types and we can't stick to using one everywhere:

1. why can't we use int64/uint everywhere (including InitialGasPrice etc)
2. why can't we use sdk.Int everywhere (including MaxBlockGas, ShortAverageInertie etc)
___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJO6cCAwpgF7PJJtYL:-NAJkMrd-nHeiQ-L_lAY:brohjpg) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm also wondering why we use sdk.Int in some places and in other int64/uint
</blockquote></details>

continuing the discussion in the comment above
___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAJheui5luoSAOPsZQI:bdk3r0i) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
> Now I see that we could move default values to feemodel package and use it in app package

Yes that is my thought also

> But storing network-specific data in module package seems weird to me

100%
if we want to override fee model for some network we should do it in network.go. But for now all of them will just use default config
___
*[`x/feemodel/model_sim_test.go` line 13 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJPimZ9irvUHM4LV6W:-NAJjag46lcmkGvhtDsA:b-jgdmff) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/x/feemodel/model_sim_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> can we use globally defined Model the same as for testnet/mainnet/devnet ?

Once @miladz68 moves `NetworkConfig` out of `app` package, now importing `app` here will cause circular dependency
</blockquote></details>

lets just put the same values manually for now then ?
___
*[`x/feemodel/model_test.go` line 11 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAF_PeVBUBR88basmn5:-NAJhhaY2YcqbncbBfqD:bp0agi3) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model_test.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv ? Previously when I created an account with extremely high balance you argued that I should use more or less realistic numbers.
</blockquote></details>

Yes because:
1. this code is used not only in tests but for running default devnet and might cause issues in different parts. Eg. explorer might be broken because of this. So I prefer to use smth realistic there
2. account balances is smth we can control and we don't expect to have such a huge amounts

But for gas model here it is test-only code and since we have plenty of moving parts and we just want to make sure that our calculations will not brake in some extreme cases. With fuzz testing we can cover more that doing it manually


<!-- Sent from Reviewable.io -->

2022-08-25 11:56 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 17 of 26 files reviewed, 10 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAIjv--CEVKZZl2OsKS:-NAJk5Wo-dcusf3gOwsb:b-ff5q29) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

chart doesn't use new MaxGasPrice which is x1000 from initial
</blockquote></details>

Done but it doesn't make charts better IMO

___
___
*[`app/app.go` line 426 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-N9qH0Ci5rjJYjNJE3UP:-NAJmpczB98EY930DV5s:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/app/app.go#L426)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/qGmk7p8gPZ3KlmZN41BUqkJu/image.png)
</blockquote></details>

Done.
___
*[`app/network.go` line 142 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAEvnzQA7LHCjgx7M3C:-NAJl4Ql9wSin1CEXzVh:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/app/network.go#L142)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minimum discounted gas price -> gas price with maximum discount
</blockquote></details>

Done.
___
*[`app/network.go` line 143 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAEvuAq2Nwlkuk0Q3dN:-NAJl5CQAUfvED25XQuU:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/app/network.go#L143)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minimum discounted gas price -> gas price with maximum discount
</blockquote></details>

Done.
___
*[`app/network.go` line 150 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJSWK-2SZzlId2fVSw:-NAJl9sl4oFBfuYkQqd0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L150)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

leftover after using non-cosmos types, will do
</blockquote></details>

Done.
___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6wSB37TbK3lTmxEY:-NAJlGRT7aFnJZmse-Z0:b-p4g2st) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I just want to make sure it is really required to use both types and we can't stick to using one everywhere:

1. why can't we use int64/uint everywhere (including InitialGasPrice etc)
2. why can't we use sdk.Int everywhere (including MaxBlockGas, ShortAverageInertie etc)
</blockquote></details>

Price is the concept where sdk.Int/sdk.Coin types are used in cosmos
Gas usage is the concept where int64/uint64 are used in cosmos

We may use sdk.Int for gas usage but it's not the type used by cosmos. We decided to use cosmos types, and this is how it works there.
___
*[`x/auth/ante/fee.go` line 42 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4d-ZRD1p5RvVLdvvG:-NAJmBrnBOmAg4Ta9t2D:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/auth/ante/fee.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
can we add TODO to have a test for this case ?
</blockquote></details>

Done
___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAJmRDb5hmOXXW5n9mJ:b-if40kv) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Now I see that we could move default values to feemodel package and use it in app package

Yes that is my thought also

> But storing network-specific data in module package seems weird to me

100%
if we want to override fee model for some network we should do it in network.go. But for now all of them will just use default config
</blockquote></details>

So, do you want me to move the config to the module? I'm against it but if you want that then I will do.
___
*[`x/feemodel/model_sim_test.go` line 13 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJPimZ9irvUHM4LV6W:-NAJmK3O6LehA3wTqh-U:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/x/feemodel/model_sim_test.go#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets just put the same values manually for now then ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-25 12:16 UTC, dzmitryhil reviewed
> Reviewed 9 of 9 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-25 16:14 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAIjv--CEVKZZl2OsKS:-NAKZ52f4MOQciH3Q_ac:b-4bjzj) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done but it doesn't make charts better IMO
</blockquote></details>

yes doesn't look nice but at least it is correct now
I also changed vertical axis to logarithmic scale. Still doesn't look perfect but better. 
Before preparing the doc we should probably play with it to make nice

___
___
*[`app/network.go` line 161 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAJ6wSB37TbK3lTmxEY:-NAKlLvc-1HqVBC-t9I0:b-k5ynhc) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c410c473802be08f1fa6f140645222cf48fec6f/app/network.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Price is the concept where sdk.Int/sdk.Coin types are used in cosmos
Gas usage is the concept where int64/uint64 are used in cosmos

We may use sdk.Int for gas usage but it's not the type used by cosmos. We decided to use cosmos types, and this is how it works there.
</blockquote></details>

I see
ok for me
___
*[`x/fee/model_test.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NA4da-QApqnFGHMkXNz:-NAKli-32yzxn75nx1nx:b-zd7084) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d3490f1a9e972bbd3849a57ccc8030e5577ef4a/x/fee/model_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So, do you want me to move the config to the module? I'm against it but if you want that then I will do.
</blockquote></details>

if you are against It also makes sense for me to not move it depending on our view here
I'm satisfied with the current imple. what is more I think we will move all of this params to gov and this will be anyways changed


<!-- Sent from Reviewable.io -->

2022-08-25 16:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 25 of 26 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/model.go` line 8 at r22](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAKoLEO1wzjmh2Vf6th:-NAKowHD4YQs4uR_FhFt:b-akx344) ([raw file](https://github.com/coreumfoundation/coreum/blob/aab89eb6f5ff3bf160d51caafbefffb1a0512036/x/feemodel/model.go#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought a bit more 
An I think it makes sense to have default config 
smth similar to this https://github.com/terra-money/core/blob/main/app/wasmconfig/config.go#L46
</blockquote></details>

Do you mean sth like `feemodel.DefaultModel` function? It's possible but it still makes the same mistake - defines our network-specific parameters inside reusable module, just hiding it behind the function name making an impression that it's sth generic.


<!-- Sent from Reviewable.io -->

2022-08-26 07:10 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`x/feemodel/model.go` line 24 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAFMCCw-bLhg9mjQDXb:-NANz4BMAB_t0QsQrBCh:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we have fuzz testing for this method also ?
</blockquote></details>

Done.
___
*[`x/feemodel/model_test.go` line 11 at r16](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAF_PeVBUBR88basmn5:-NANz6PT2uIF-vbbgrdo:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/bce9a2bf568665c6c9165e96fc26bf6235ebb65a/x/feemodel/model_test.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Yes because:
1. this code is used not only in tests but for running default devnet and might cause issues in different parts. Eg. explorer might be broken because of this. So I prefer to use smth realistic there
2. account balances is smth we can control and we don't expect to have such a huge amounts

But for gas model here it is test-only code and since we have plenty of moving parts and we just want to make sure that our calculations will not brake in some extreme cases. With fuzz testing we can cover more that doing it manually
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 08:26 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-26 10:47 UTC, miladz68 requested changes
> Reviewed 5 of 9 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, 1 of 1 files at r23, 2 of 2 files at r25, 4 of 4 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 128 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOiS1t9cAuAZqWooj-:-NAOiS1t9cAuAZqWooj0:b-iw4fxc) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/app/app.go#L128)):*
> ```Go
> 	// this line is used by starport scaffolding # stargate/app/govProposalHandlers
> 
> 	govProposalHandlers = append(govProposalHandlers, wasmclient.ProposalHandlers...)
> ```

just a quesiton
how is wasclient part of fee model PR ?
___
*[`x/feemodel/model_test.go` line 107 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOjQ9S9I8uPwSF-kQf:-NAOjQ9S9I8uPwSF-kQg:budrcrm) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/model_test.go#L107)):*
> ```Go
> }
> 
> func TestFuzzGasPriceInExpectedRange(t *testing.T) {
> ```

This is not really a fuzz test. Fuzz tests and a different signature and are not run by default, only when you specify with -fuzz flag (similar to benchmarks).

To provide more context, fuzz testing is not just a random generator, it tries to feed the test from different sections of different distribution models to have a better chance of finding edge cases. 


<!-- Sent from Reviewable.io -->

2022-08-26 10:53 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/model_test.go` line 107 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOjQ9S9I8uPwSF-kQf:-NAOm9SX-fUfIBdUUY2c:b-838bqj) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/model_test.go#L107)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is not really a fuzz test. Fuzz tests and a different signature and are not run by default, only when you specify with -fuzz flag (similar to benchmarks).

To provide more context, fuzz testing is not just a random generator, it tries to feed the test from different sections of different distribution models to have a better chance of finding edge cases. 
</blockquote></details>

Also I want to add that this is not really wrong, and I don't disagree with the approach taken here. 


<!-- Sent from Reviewable.io -->

2022-08-26 11:05 UTC, dzmitryhil requested changes
> Reviewed 2 of 2 files at r25, 4 of 4 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module.go` line 83 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOnFoS73dQRnWDljnA:-NAOnFoS73dQRnWDljnB:bnw3rz4) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/module.go#L83)):*
> ```Go
> 
> 	keeper   Keeper
> 	feeDenom string
> ```

Those "feeDenom string" should be alos moved to the the geneis file, not as a "param" but at least to the root. (At least we need to add FIXME). 
Also do we validate that fee is paid in that particular denom?


<!-- Sent from Reviewable.io -->

2022-08-26 11:22 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 128 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOiS1t9cAuAZqWooj-:-NAOpxw56XbJtwipPDYM:b5czsio) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/app/app.go#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

just a quesiton
how is wasclient part of fee model PR ?
</blockquote></details>

It was merged from master. I had to resolve conflicts that's why reviewable shows this I guess
___
*[`x/feemodel/model_test.go` line 107 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOjQ9S9I8uPwSF-kQf:-NAOriwH5i13PZUHJRPt:bm5aazo) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/model_test.go#L107)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Also I want to add that this is not really wrong, and I don't disagree with the approach taken here. 
</blockquote></details>

I explained this in a comment inside `generateRandomizedModel` function:
```
// fuzz engine of go test is not used because it doesn't allow to maintain relationships between generated parameters
```



_Code quote:_
```Go
// fuzz engine of go test is not used because it doesn't allow to maintain relationships between generated parameters
```
___
*[`x/feemodel/module.go` line 83 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOnFoS73dQRnWDljnA:-NAOrvoNCn7Jcm8SP-V7:b8opl4i) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/module.go#L83)):*
> Those "feeDenom string" should be alos moved to the the geneis file, not as a "param" but at least to the root. (At least we need to add FIXME).

Done

> Also do we validate that fee is paid in that particular denom?

Yes: https://github.com/CoreumFoundation/coreum/blob/fee-model/x/feemodel/ante/ante.go#L55


<!-- Sent from Reviewable.io -->

2022-08-26 11:24 UTC, dzmitryhil approved these changes
> Reviewed 2 of 2 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-26 11:49 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-26 11:59 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`x/feemodel/model.go` line 8 at r22](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAKoLEO1wzjmh2Vf6th:-NAP0Bpk775ZR80wAfen:b-9xpkxw) ([raw file](https://github.com/coreumfoundation/coreum/blob/aab89eb6f5ff3bf160d51caafbefffb1a0512036/x/feemodel/model.go#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you mean sth like `feemodel.DefaultModel` function? It's possible but it still makes the same mistake - defines our network-specific parameters inside reusable module, just hiding it behind the function name making an impression that it's sth generic.
</blockquote></details>

I'm considering these params as default values which will be used unless you override them 
similar to what we have in other cosmos modules

e.g https://docs.cosmos.network/v0.46/modules/distribution/07_params.html#
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/y8XY6JmpMJoIbFI2KiaXJ1G0/image.png)

Isn't it the same thing ?


<!-- Sent from Reviewable.io -->

2022-08-26 12:24 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 22 of 28 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`x/feemodel/model.go` line 8 at r22](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAKoLEO1wzjmh2Vf6th:-NAP6-zg0shq6Gvr3aMn:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/aab89eb6f5ff3bf160d51caafbefffb1a0512036/x/feemodel/model.go#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm considering these params as default values which will be used unless you override them 
similar to what we have in other cosmos modules

e.g https://docs.cosmos.network/v0.46/modules/distribution/07_params.html#
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/y8XY6JmpMJoIbFI2KiaXJ1G0/image.png)

Isn't it the same thing ?

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 12:30 UTC, miladz68 approved these changes
> Reviewed 2 of 2 files at r28, 6 of 6 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @ysv)

___
*[`x/feemodel/model_test.go` line 107 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOjQ9S9I8uPwSF-kQf:-NAP7AYqDcQrbTHBY59J:b-e7dege) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/model_test.go#L107)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I explained this in a comment inside `generateRandomizedModel` function:
```
// fuzz engine of go test is not used because it doesn't allow to maintain relationships between generated parameters
```
</blockquote></details>

I understand, but if you have to control the relationship between the input params, then you are not really fuzz testing. 


<!-- Sent from Reviewable.io -->

2022-08-26 12:35 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`x/feemodel/model_test.go` line 107 at r27](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAOjQ9S9I8uPwSF-kQf:-NAP8Um38ixUvEUoulh6:bef0457) ([raw file](https://github.com/coreumfoundation/coreum/blob/4cb769d994716268933f52de6bc6a5c3445f0e34/x/feemodel/model_test.go#L107)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I understand, but if you have to control the relationship between the input params, then you are not really fuzz testing. 
</blockquote></details>

changed the name of the function


<!-- Sent from Reviewable.io -->

2022-08-26 12:56 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-26 13:24 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-26 16:03 UTC, ysv approved these changes
> Reviewed 1 of 10 files at r13, 1 of 1 files at r14, 1 of 1 files at r21, 1 of 1 files at r22, 2 of 2 files at r25, 3 of 4 files at r27, 2 of 2 files at r28, 5 of 6 files at r29, 1 of 1 files at r30, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

___
*[`x/feemodel/model.go` line 8 at r22](https://reviewable.io/reviews/coreumfoundation/coreum/131#-NAKoLEO1wzjmh2Vf6th:-NAP6uK547TROw32NUQe:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/aab89eb6f5ff3bf160d51caafbefffb1a0512036/x/feemodel/model.go#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-08-26 16:04 UTC, merged