New client (client v2, tx v2)
CoreumFoundation/coreum pull request #134
Opened 2022-08-12 13:38 UTC by xlab

2022-08-12 13:48 UTC, wojtek-coreum reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-12 13:55 UTC, wojtek-coreum requested changes
> Reviewed 5 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HJXyeC-5a9m2YGonh:-N9HJXyeC-5a9m2YGoni:bxj7pd9) (no related file):*
Do I understand correctly that adjusting existing code (integration tests) to use new client is out of scope of this PR? (I'm ok with it and I prefer to do it like this).

___
___
*[`integration-tests/testing/types.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HKQtt7XcsH_swoFWk:-N9HKQtt7XcsH_swoFWl:b-954h7t) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e75c7bbd498196b1bb177474b6fcbafe6e2e7fc/integration-tests/testing/types.go#L27)):*
> ```Go
> type Chain struct {
> 	Network *app.Network
> 	// FIXME (wojtek): Remove once crust is updated
> ```

wojtek -> max?


<!-- Sent from Reviewable.io -->

2022-08-15 12:33 UTC, ysv requested changes
> Reviewed 3 of 12 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 8 of 12 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HJXyeC-5a9m2YGonh:-N9VqQ87-aTPCz-s-spj:bhz8ooi) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do I understand correctly that adjusting existing code (integration tests) to use new client is out of scope of this PR? (I'm ok with it and I prefer to do it like this).
</blockquote></details>

yes 100%

___
___
*[`pkg/client2/client.go` line 42 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9Vu2ck4Jm4j_kub_2t:-N9Vu2ck4Jm4j_kub_2u:bgzjlq2) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L42)):*
> ```Go
> 
> // Client is the client for cored blockchain
> type Client interface {
> ```

I think here it is a good decision to use interface :thumbsup: 
___
*[`pkg/client2/client.go` line 58 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9VtSYW8aY_katMQPEh:-N9VtSYW8aY_katMQPEi:b-qzv23d) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L58)):*
> ```Go
> }
> 
> // TestingClient includes some high-level methods for simplifying testing transactions creation
> ```

I think that this interface should be defined in ./integration-tests on the place where it is used 

I would prefer to to not define it here for now but do this when changing integration tests to use client2 

We should also remove this methods `QueryBankBalances ...` . They should be implemented in integration-tests also
___
*[`pkg/client2/client.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WStip1p4DxDypribd:-N9WStip1p4DxDypribe:b-1408w5) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L172)):*
> ```Go
> 
> // Broadcast sends transaction to chain, ensuring it passeses CheckTx. Doesn't await until Tx is uncluded in block.
> func (c coreClient) Broadcast(ctx context.Context, encodedTx []byte) (BroadcastResult, error) {
> ```

If I understand correctly you suggest to use `Broadcast` to publish both Sync & Async and then call AwaitTx if we want to have sync ? Smth like this for sync:
```
encodedTx := ...
cl.Broadcast(ctx, encodedTx)
cl.AwaitTx(ctx, encodedTx)
```

Because I personally prefer way implemented here https://github.com/CoreumFoundation/coreum/pull/130/files where we have 2 methods:
```
func (c Client) BroadcastSync(ctx context.Context, encodedTx []byte) (BroadcastResult, error) 
func (c Client) BroadcastAsync(ctx context.Context, encodedTx []byte) (BroadcastResult, error)
```

As for AwaitTx I would make it private method `awaitTx`


<!-- Sent from Reviewable.io -->

2022-08-15 12:48 UTC, xlab commented
*[`pkg/client2/client.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WStip1p4DxDypribd:-N9WXfY_CzQMWo7gdSlf:b-ipjnln) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L172)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

If I understand correctly you suggest to use `Broadcast` to publish both Sync & Async and then call AwaitTx if we want to have sync ? Smth like this for sync:
```
encodedTx := ...
cl.Broadcast(ctx, encodedTx)
cl.AwaitTx(ctx, encodedTx)
```

Because I personally prefer way implemented here https://github.com/CoreumFoundation/coreum/pull/130/files where we have 2 methods:
```
func (c Client) BroadcastSync(ctx context.Context, encodedTx []byte) (BroadcastResult, error) 
func (c Client) BroadcastAsync(ctx context.Context, encodedTx []byte) (BroadcastResult, error)
```

As for AwaitTx I would make it private method `awaitTx`

</blockquote></details>

The previous naming was confusing, e.g. you didn't understand the difference between them correctly.

`BroadcastAsync` was not just `BroadcastSync` without await ;)


<!-- Sent from Reviewable.io -->

2022-08-15 12:49 UTC, xlab commented
*[`pkg/client2/client.go` line 58 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9VtSYW8aY_katMQPEh:-N9WYMgBCBV8RLDsPgnh:ba57m3v) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think that this interface should be defined in ./integration-tests on the place where it is used 

I would prefer to to not define it here for now but do this when changing integration tests to use client2 

We should also remove this methods `QueryBankBalances ...` . They should be implemented in integration-tests also
</blockquote></details>

makes sense to me


<!-- Sent from Reviewable.io -->

2022-08-16 06:17 UTC, wojtek-coreum requested changes
> Reviewed 5 of 12 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 47 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_E3MX91sBjgEJDmaI:-N9_E3MX91sBjgEJDmaJ:bof1r) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L47)):*
> ```Go
> 	PrepareTx(ctx context.Context, input tx2.BaseInput, msgs ...sdk.Msg) ([]byte, error)
> 	GetNumberSequence(ctx context.Context, address types.Address) (uint64, uint64, error)
> 	EstimateGas(ctx context.Context, encodedTx []byte) (int64, error)
> ```

Accepting `encodedTx []byte` in `EstimateGas` and `Broadcast` was jsut a trick I introduced to not expose sdk types. Now, they may take `msgs ...sdk.Msg` and call `PrepareTx` internally (which should be unexported then).
___
*[`pkg/client2/client.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_8wOM0e86c5RYuRL0:-N9_8wOM0e86c5RYuRL1:b-r9e4oy) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L59)):*
> ```Go
> 
> // TestingClient includes some high-level methods for simplifying testing transactions creation
> type TestingClient interface {
> ```

Client should not implement this interface at all. This is what we decided, to not accumulate all those methods for all the queries and messages in a single place, right?
___
*[`pkg/client2/client.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WStip1p4DxDypribd:-N9_A-Lo4W5pWnHUnApS:b-h74ubv) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L172)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

The previous naming was confusing, e.g. you didn't understand the difference between them correctly.

`BroadcastAsync` was not just `BroadcastSync` without await ;)


</blockquote></details>

@xlab  so please explain...

In my implementation `BroadcastSync` broadcasted transaction then waited until `CheckTx` validated it on node, and then waited until it was included in a block.
On the other hand `BroadcastAsync` broadcasted transaction and returned immediately without even waiting for the result of `CheckTx` validation.

Motivation for having those two methods:
- `BroadcastSync` is a convenient method for waiting until tx is included ina block - it is used by integration tests, ping-pong and zstress like `Broadcast` in old client
- `BroadcastAsync` + `AwaitTx` implements logic required by facuet, where request for money is enqued, then tx is created for bunch of them, tx hash is returned asap (`BroadcastAsync`) and then faucet waits (`AwaitTx`) until the same funding account might be used again.

So both `BroadcastSync` and `BroadcastAsync` should be implemented, and also `AwaitTx` should be exported.

The idea behind not waiting for `CheckTx` in `BroadcastAsync` is to return tx hash to the requester asap.
Also a method `BroadcastSync` which internally calls `AwaitTx` is there for our convenience because it is very common scenario in our code, so doing both operations in single call makes our life easier.
___
*[`pkg/client2/client.go` line 198 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_CyK7A2DuIe6ht-6p:-N9_CyK8Bfw6UVDvAV5Y:b2ka9m6) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L198)):*
> ```Go
> 
> // AwaitTx awaits until a signed transaction is included in a block
> func (c coreClient) AwaitTx(ctx context.Context, encodedTx []byte) (BroadcastResult, error) {
> ```

@miladz68 also touched this topic.

This function should take `txHash` as argument, not `encodedTx`.
The only reason I didn't done it this way in first place is that `client.CheckTendermintError` requires `encodedTx`.
And it does that just to.... compute `txHash` from `encodedTx`: https://github.com/cosmos/cosmos-sdk/blob/main/client/broadcast.go#L54
(We love Cosmos SDK).

It completely doesn't make sense so I would propose to copy the logic from `client.CheckTendermintError` and implement it in better way.

There is no sense to pass entire encoded tx to get its status, tx hash is all what is needed.
___
*[`pkg/tx2/sign.go` line 14 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X5XJZB6Cipd8OIog2:-N9_FCfR7B9_ZzGypBG8:b5n397g) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/sign.go#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the sign function seems to be the only valuable function in this package, move it to client and remove this package. Also BaseInput type can have a simpler interface.
</blockquote></details>

Doing this will create circular dependency between, `app` and `client2` packages
___
*[`pkg/tx2/types.go` line 17 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X6kI8AmXEPtqTohtE:-N9_FmPb6ZWvReTMisfE:b2bt3u0) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

with the discussion that we had, this type is only useful for the sign method, we don't need the public key anymore, and the comment does not seem relavant anymore. I also think we don't need account info anymore.
</blockquote></details>

We need `PublicKey` because transaction for gas estimation is not signed with private key, only public key is set there.
`Account` is required to be able to set account number and sequence for signing. If the value is `nil` the current values are fetched from the blockchain.

@xlab the reason I decided to put both private and public keys is because estimation requires public key, while signing requires private key. I didn't like this idea from the very beginning but I haven't got better idea at that time. Now I see there is a better solution:
- private key by definition contains both private and public key, so information about public key is redundant here if both keys are set
- for gas estimation fake private key could be created containing `0x00`s for bytes representing private key and real values for bytes representing public key
- `Sign` method of client could detect this and don't sign using privste key if bytes are `0x00`s
- It means this struct could contain private key only
___
*[`pkg/types/key.go` line 9 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_HOCU-ktWHy3_z3v5:-N9_HOCU-ktWHy3_z3v6:bmwu6zo) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/key.go#L9)):*
> ```Go
> 
> // Secp256k1PrivateKey is a secp256k1 private key
> type Secp256k1PrivateKey []byte
> ```

use cosmos type directly
___
*[`pkg/types/key.go` line 24 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_HQBeEQjJIk_5k_GX:-N9_HQBeEQjJIk_5k_GY:bmwu6zo) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/key.go#L24)):*
> ```Go
> 
> // Secp256k1PublicKey is a secp256k1 public key
> type Secp256k1PublicKey []byte
> ```

use cosmos type directly
___
*[`pkg/types/types.go` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_HVnu4r7FaxzJjcJG:-N9_HVnu4r7FaxzJjcJH:b-m6ley5) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/types.go#L10)):*
> ```Go
> 
> // Address is an account address encoded using bech32 format
> type Address string
> ```

cosmos uses `string` type directly to [...]

2022-08-16 08:08 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WStip1p4DxDypribd:-N9_gCVsAERdrupP6Dbu:b1mokmm) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L172)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab  so please explain...

In my implementation `BroadcastSync` broadcasted transaction then waited until `CheckTx` validated it on node, and then waited until it was included in a block.
On the other hand `BroadcastAsync` broadcasted transaction and returned immediately without even waiting for the result of `CheckTx` validation.

Motivation for having those two methods:
- `BroadcastSync` is a convenient method for waiting until tx is included ina block - it is used by integration tests, ping-pong and zstress like `Broadcast` in old client
- `BroadcastAsync` + `AwaitTx` implements logic required by facuet, where request for money is enqued, then tx is created for bunch of them, tx hash is returned asap (`BroadcastAsync`) and then faucet waits (`AwaitTx`) until the same funding account might be used again.

So both `BroadcastSync` and `BroadcastAsync` should be implemented, and also `AwaitTx` should be exported.

The idea behind not waiting for `CheckTx` in `BroadcastAsync` is to return tx hash to the requester asap.
Also a method `BroadcastSync` which internally calls `AwaitTx` is there for our convenience because it is very common scenario in our code, so doing both operations in single call makes our life easier.
</blockquote></details>

Now I see that tx hash might be computed without even trying to broadcast the transaction. So we may use a single `Broadcast` implementation for all the scenarios. Faucet could use exported `PrepareTx` method to compute encoded tx to get txHash and then pass encoded Tx to `Broadcast`. Having a helper like `BroadcastAndWait` still would be useful.


<!-- Sent from Reviewable.io -->

2022-08-16 09:52 UTC, dzmitryhil requested changes

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/client2/client.go
> +	txStatusPollInterval = 500 * time.Millisecond
Those params should be configarable for the client, so you should be able to pass the "Config" with the them to the "New" func. Or use the DefaultConfig() with the defaults.

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/client2/client.go
> +}
I didn't get why we need it. Could you explain please.

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/client2/client.go
> +	} else if res.Code != 0 {
The 'else' is redundant here

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/client2/client.go
> +	txHash := fmt.Sprintf("%X", txHashBytes)
This part looks like a pattern for the hash creation, I would recommend to extract a func for it.

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/client2/client.go
> +		}
If the order of the "errors.Is(err, requestCtx.Err())" and next check isn't required, then you can simplify like this:
```
if err != nil {
	if errRes := client.CheckTendermintError(err, encodedTx); errRes != nil {
		if !isTxInMempool(errRes) {
			return errors.WithStack(err)
		}
	}
	return retry.Retryable(errors.WithStack(err))
}
```
If required like this:
```
if err != nil {
	if errors.Is(err, requestCtx.Err()) {
		return retry.Retryable(errors.WithStack(err))
	}
	if errRes := client.CheckTendermintError(err, encodedTx); errRes != nil {
		if !isTxInMempool(errRes) {
			return errors.WithStack(err)
		}
	}
	return retry.Retryable(errors.WithStack(err))
}
```

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/types/types.go
> +type Address string
Why do we use address as a string instead of sdk.Address, and convert in to the address anyway in the func call?

2022-08-16 09:52 UTC, dzmitryhil commented on pkg/tx2/sign.go
> +		PubKey:   privKey.PubKey(),
The signer private key might be 'nil' based on the next lines, do you expect this here?

2022-08-16 10:57 UTC, xlab commented
*[`pkg/client2/client.go` line 55 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9Wd8rj2I8xgUD588aL:-N9aI9lt49DNZrcXOHOW:b-837i4v) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L55)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think we need to expose query client for different packages. we just need to expose ClientContext and each package can build the query client that they need with a single line of code. 
</blockquote></details>

Okay


<!-- Sent from Reviewable.io -->

2022-08-16 10:58 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_8wOM0e86c5RYuRL0:-N9aINIB8AGT0ijMW5ft:b-xhnpn8) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Client should not implement this interface at all. This is what we decided, to not accumulate all those methods for all the queries and messages in a single place, right?
</blockquote></details>

It shouldn't, but we decided that it's nice to have a higher-level method once implemented. We decided that we did not require that, but don't remember we forbidding it now.
___
*[`pkg/client2/client.go` line 63 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-63:-N9aID1T3eH9j1hu1rTv:b5eyv48) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get why we need it. Could you explain please. 
</blockquote></details>

Legacy code that I didn't want to remove, because on the call we decided that "it's nice to have high-level helpers".


<!-- Sent from Reviewable.io -->

2022-08-16 11:01 UTC, xlab commented
*[`pkg/client2/client.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WStip1p4DxDypribd:-N9aIfqPDANi1IPdKXpo:b-c7si40) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L172)):*
> On the other hand BroadcastAsync broadcasted transaction and returned immediately without even waiting for the result of CheckTx validation.

Without a response from CheckTx there is no use of that API, you can submit even invalid Tx and it will not return any error.

The await/no-await switch is to decide if we need to ensure that Tx was included in the block. I believe that CheckTx must be used to validate Tx sanity.

> tx hash to the requester asap.

You know tx hash without sending anything to the node, it's just a hash of encoded tx data.


<!-- Sent from Reviewable.io -->

2022-08-16 11:01 UTC, xlab commented
*[`pkg/client2/client.go` line 186 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-186:-N9aJCEN0PfvANuRpTXI:byfa5pk) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L186)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The 'else' is redundant here
</blockquote></details>

Please elaborate. 


<!-- Sent from Reviewable.io -->

2022-08-16 11:02 UTC, xlab commented
*[`pkg/client2/client.go` line 198 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_CyK7A2DuIe6ht-6p:-N9aJKES7YVuccNpGxjy:b5yjqe) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L198)):*
> I would propose to copy the logic from client.CheckTendermintError and implement it in better way.


Sounds like a deviation from what this PR supposed to be.


<!-- Sent from Reviewable.io -->

2022-08-16 11:05 UTC, xlab commented
*[`pkg/tx2/types.go` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X7VU0DZfuBMdWnASs:-N9aK0Ma81s6pCMSJprB:b-qsef6j) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L6)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

commented below that this type is redunant after the refactor. 
</blockquote></details>

This goes far beyond what's been discussed on the calls and the plan for this PR.


<!-- Sent from Reviewable.io -->

2022-08-16 11:16 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/tx2/types.go` line 17 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X6kI8AmXEPtqTohtE:-N9aKFJg9hQWT_IX-YX2:b-n3rl3j) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L17)):*
> We need PublicKey because transaction for gas estimation is not signed with private key, only public key is set there.

PublicKey is not used for gas estimation afaik. The only reason why SDK was getting pubkey from keyring (and I was following the idea) is because of this issue: https://github.com/cosmos/cosmos-sdk/issues/8201


>  fake private key could be created containing 0x00s for bytes representing private key

This is a super overcomplication and implicit hack, I prefer my old code which exits there that doesn't try to squash everything into a single function and has two distinct methods for corresponding tasks:

https://github.com/CoreumFoundation/crust/blob/b249580ebe19f80a8d1b5a29b1819303d90671c3/infra/apps/cored/client.go#L392


<!-- Sent from Reviewable.io -->

2022-08-16 11:18 UTC, xlab commented
*[`pkg/tx2/types.go` line 17 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X6kI8AmXEPtqTohtE:-N9aMqyH-cNA_fB6wJ4-:b-yozl7j) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L17)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> We need PublicKey because transaction for gas estimation is not signed with private key, only public key is set there.

PublicKey is not used for gas estimation afaik. The only reason why SDK was getting pubkey from keyring (and I was following the idea) is because of this issue: https://github.com/cosmos/cosmos-sdk/issues/8201


>  fake private key could be created containing 0x00s for bytes representing private key

This is a super overcomplication and implicit hack, I prefer my old code which exits there that doesn't try to squash everything into a single function and has two distinct methods for corresponding tasks:

https://github.com/CoreumFoundation/crust/blob/b249580ebe19f80a8d1b5a29b1819303d90671c3/infra/apps/cored/client.go#L392


</blockquote></details>

Obviously sim txns don't need signatures, so this interface and `Sign` method must not be used for building sim transactions.


<!-- Sent from Reviewable.io -->

2022-08-16 11:37 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 29 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 186 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-186:-N9aO5Hw60XH9JR4aUWG:b59xort) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L186)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Please elaborate. 
</blockquote></details>

With the updated logic (in the next commit), you can keep it. But with prev (the one we see here),  you could use the if(){} and then next if(){} without 'else', since the second "returned" the error.  


<!-- Sent from Reviewable.io -->

2022-08-16 11:44 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 29 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_8wOM0e86c5RYuRL0:-N9aRb-CA33kjqxtIJ8N:b-kg6n01) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L59)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It shouldn't, but we decided that it's nice to have a higher-level method once implemented. We decided that we did not require that, but don't remember we forbidding it now.
</blockquote></details>

So, first we decided that we don't want to have this central point for commonly used methods because it adds a hassle, but now we add them because it is convenient? I don't get it.
___
*[`pkg/client2/client.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WStip1p4DxDypribd:-N9aRyb228wYCCfmt6FS:bg0aucw) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L172)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> On the other hand BroadcastAsync broadcasted transaction and returned immediately without even waiting for the result of CheckTx validation.

Without a response from CheckTx there is no use of that API, you can submit even invalid Tx and it will not return any error.

The await/no-await switch is to decide if we need to ensure that Tx was included in the block. I believe that CheckTx must be used to validate Tx sanity.

> tx hash to the requester asap.

You know tx hash without sending anything to the node, it's just a hash of encoded tx data.

</blockquote></details>

I agree... Let's wait for CheckTx everywhere. Let's also add a common function to compute tx hash so faucet may get it immediately.
___
*[`pkg/client2/client.go` line 198 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_CyK7A2DuIe6ht-6p:-N9aSeSQ73jicTcGGjdc:b-qofv1z) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L198)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> I would propose to copy the logic from client.CheckTendermintError and implement it in better way.


Sounds like a deviation from what this PR supposed to be.
</blockquote></details>

This PR is about setting the interface of client. Creating an interface which requires full encoded tx to get info about tx makes no sense. Otherwise someone will have to change this interface later, causing yet another code refactoring everywhere.
___
*[`pkg/tx2/types.go` line 17 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X6kI8AmXEPtqTohtE:-N9aQbWW-d9hoW9ug7GL:b96c4g0) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L17)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Obviously sim txns don't need signatures, so this interface and `Sign` method must not be used for building sim transactions.
</blockquote></details>

Okay, I included that logic only because I've seen that your code started using public key for gas estimation. If public key is not required to estimate the gas then entire logic there might be probably simplified.

On the other hand gas used by smart contract (and any other transaction) may depend on who signed the tx, so for me it's reasonable to use the real public key to give the estimator a hint on who will be the signer (but have no idea if this information is used).


<!-- Sent from Reviewable.io -->

2022-08-16 12:43 UTC, xlab commented
*[`pkg/staking/staking.go` line 44 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WlHa83op3W2DsiI6Y:-N9afZtH0Fl9A8uoKa4K:bz0ovm7) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/staking/staking.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think the tx2 and staking package are redundant now, so this change  seems unnecessary. 
</blockquote></details>

Yes, nuked them


<!-- Sent from Reviewable.io -->

2022-08-16 12:43 UTC, xlab commented
*[`pkg/tx2/sign.go` line 14 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X5XJZB6Cipd8OIog2:-N9afcPqA5TlZKQqpK6K:b-83kpuq) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/sign.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Doing this will create circular dependency between, `app` and `client2` packages
</blockquote></details>

Nuked


<!-- Sent from Reviewable.io -->

2022-08-16 12:44 UTC, xlab commented
*[`pkg/tx2/sign.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMu-r4-49:-N9afe7085-czgYz9B7y:b-ptg1wy) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/sign.go#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The signer private key might be 'nil' based on the next lines, do you expect this here?
</blockquote></details>

It was a hack, removed in new cleaner version


<!-- Sent from Reviewable.io -->

2022-08-16 12:44 UTC, xlab commented
*[`pkg/tx2/types.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WkZOoDovXP6KI8bTQ:-N9afivs7eBuNoDyGdKi:bisnci9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Since we decided to not have a central client package and reach out to cosmos SDK for every thing, these types wrappers seems unnecessary to me. 
Actually the whole tx and types package seem redundant now. 
</blockquote></details>

Yes. However, I kept types since they are used in client v1 for now.


<!-- Sent from Reviewable.io -->

2022-08-16 12:45 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 8 of 21 files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9afn875DGD8kAk0Qgc:-N9afn875DGD8kAk0Qgd:bdaztvp) (no related file):*
Previously we made a decision that keyring/keystore won't be a part of this client and will exist only in `crust` as a part of `contracts` command.

___


<!-- Sent from Reviewable.io -->

2022-08-16 12:46 UTC, xlab commented
*[`pkg/tx2/types.go` line 17 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X6kI8AmXEPtqTohtE:-N9afn_ICvnSwJcdTKWQ:b-fmz40d) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L17)):*
> may depend on who signed the tx

It's not taken from tx pubkey, every Msg has a field corresponding to the actor.

Again, we use Cosmos SDK approach and they use empty pubkey.

The approach is now clear and I have new code that uses it.


<!-- Sent from Reviewable.io -->

2022-08-16 12:46 UTC, xlab commented
*[`pkg/tx2/types.go` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9X7VU0DZfuBMdWnASs:-N9agC-a2koEqs18mkSu:b-q7bc91) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/tx2/types.go#L6)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This goes far beyond what's been discussed on the calls and the plan for this PR.
</blockquote></details>

Okay, given that we need to rewrite part about privkeys, I've replaced this with new struct that splits account info and keyreing.


<!-- Sent from Reviewable.io -->

2022-08-16 12:47 UTC, xlab commented
*[`pkg/types/key.go` line 9 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_HOCU-ktWHy3_z3v5:-N9agJqX0PLZcbrqyQAd:byqma70) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/key.go#L9)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

use cosmos type directly
</blockquote></details>

This package is for client v1 only.


<!-- Sent from Reviewable.io -->

2022-08-16 12:47 UTC, xlab commented
*[`pkg/types/key.go` line 24 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_HQBeEQjJIk_5k_GX:-N9agOyO3xT98Xx9VpLO:b31fob4) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/key.go#L24)):*
> This package is for client v1 only.


<!-- Sent from Reviewable.io -->

2022-08-16 12:47 UTC, xlab commented
*[`pkg/types/key.go` line 27 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9XDu3J4t23HUaglaWM:-N9agQLeC4jV2LC5RNv4:by16ur5) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/key.go#L27)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think the client v2 needs to wrap private/ keys anymore and can reach directly to cosmos types, if we plan to reach to cosmos types, then such abstractions seem unnecessary. 
</blockquote></details>

This package is for client v1 only. New client uses keyring and doesn't wrap anything.


<!-- Sent from Reviewable.io -->

2022-08-16 12:48 UTC, xlab commented
*[`pkg/types/types.go` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WqTth2PnPDeq7EJgQ:-N9agV0yE230JHfVsYr6:b-uzeoya) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/types.go#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should strive to remove this package not to add more to it.
</blockquote></details>

I didn't add anything in this PR. Just trying to refactor @wojtek-coreum existing code


<!-- Sent from Reviewable.io -->

2022-08-16 12:48 UTC, xlab commented
*[`pkg/types/types.go` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_HVnu4r7FaxzJjcJG:-N9agaxhE27k0morchVr:blvidxp) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/types.go#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

cosmos uses `string` type directly to represent bech32-encoded addresses. So once we made a decision to expose types it uses, we should also stick to `string`
</blockquote></details>

to `sdk.AccAddress`. string is used in messages and that's `sdk.AccAddress.String()`


<!-- Sent from Reviewable.io -->

2022-08-16 12:49 UTC, xlab commented
*[`pkg/types/types.go` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMx-r4-10:-N9agiku-kEmrzMH6HkC:bt1erv5) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/types/types.go#L10)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we use address as a string instead of sdk.Address, and convert in to the address anyway in the func call?
</blockquote></details>

It was from the idea that we need to avoid SDK types at all cost. Lately the team made a decision to reuse SDK types and it's `sdk.AccAddress` indeed.


<!-- Sent from Reviewable.io -->

2022-08-16 12:50 UTC, xlab commented
*[`pkg/client2/client.go` line 289 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9Wjr6XCY7D77CdtQXa:-N9ah0yr0SMu5G-hjSm0:b-83kpuq) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L289)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

As far as I can remember from the discussion, this needs to be removed, alongside its input type.
</blockquote></details>

Nuked


<!-- Sent from Reviewable.io -->

2022-08-16 12:50 UTC, xlab commented
*[`pkg/client2/client.go` line 252 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9Wjh5330X5clIn_6XI:-N9ah2z5B3Xsl62iFdC2:b-83kpuq) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L252)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

As far as I can remember from the discussion, this needs to be removed, and each package will directly reach to the cosmos type to achieve this.
</blockquote></details>

Nuked


<!-- Sent from Reviewable.io -->

2022-08-16 12:50 UTC, xlab commented
*[`pkg/client2/client.go` line 223 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-223:-N9ah6ED7s7z0EYR2Ntt:b5qgns2) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L223)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If the order of the "errors.Is(err, requestCtx.Err())" and next check isn't required, then you can simplify like this:
```
if err != nil {
	if errRes := client.CheckTendermintError(err, encodedTx); errRes != nil {
		if !isTxInMempool(errRes) {
			return errors.WithStack(err)
		}
	}
	return retry.Retryable(errors.WithStack(err))
}
```
If required like this:
```
if err != nil {
	if errors.Is(err, requestCtx.Err()) {
		return retry.Retryable(errors.WithStack(err))
	}
	if errRes := client.CheckTendermintError(err, encodedTx); errRes != nil {
		if !isTxInMempool(errRes) {
			return errors.WithStack(err)
		}
	}
	return retry.Retryable(errors.WithStack(err))
}
```
</blockquote></details>

@wojtek-coreum needs to rewrite this code, I don't think I can understand what it does.


<!-- Sent from Reviewable.io -->

2022-08-16 12:51 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 8 of 21 files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 198 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_CyK7A2DuIe6ht-6p:-N9ahG0N68NF2s1GYNN3:b5jgc1f) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L198)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This PR is about setting the interface of client. Creating an interface which requires full encoded tx to get info about tx makes no sense. Otherwise someone will have to change this interface later, causing yet another code refactoring everywhere.
</blockquote></details>

Changed client.CheckTendermintError -> `checkTendermintError` that accepts tx hash.
___
*[`pkg/client2/client.go` line 200 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-200:-N9ahDVG68CfWHHXD5SL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L200)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This part looks like a pattern for the hash creation, I would recommend to extract a func for it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 12:53 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 8 of 21 files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_8wOM0e86c5RYuRL0:-N9ahcfB5Op4bhyzyiwF:b40mfvj) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So, first we decided that we don't want to have this central point for commonly used methods because it adds a hassle, but now we add them because it is convenient? I don't get it.
</blockquote></details>

I didn't add anything, just didn't remove them. Now it's all nuked 👍 ☢️
___
*[`pkg/client2/client.go` line 126 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9Wev6Y60UKO_ijkRRp:-N9aha_TAD5bM6QKFA8C:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L126)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we should remove this function. If I remember correctly we discussed that this package will not be used to wrap query methods.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 12:54 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 8 of 21 files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 48 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9WgOIm8ZyZf6lnxpAb:-N9ahoyB8_lu4ZiCjD83:by5tys9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L48)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Broadcast is returning GasUsed, which will always be empty right ? if it is always empty, it should not be returned.
</blockquote></details>

I've created BroadcastAsync and BroadcastSync. The first one returns just a Tx hash. Latter has TxResult with GasUsed and (in wasm branch) execution logs. So it's all good now.


<!-- Sent from Reviewable.io -->

2022-08-16 12:54 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 8 of 21 files reviewed, 30 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 47 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9_E3MX91sBjgEJDmaI:-N9ai0CmEy8szT0d_8HV:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Accepting `encodedTx []byte` in `EstimateGas` and `Broadcast` was jsut a trick I introduced to not expose sdk types. Now, they may take `msgs ...sdk.Msg` and call `PrepareTx` internally (which should be unexported then).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 13:53 UTC, wojtek-coreum requested changes
> Reviewed 6 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 38 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/client2/build_tx.go` line 95 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9au2rj6XN487UwqJcm:-N9au2rj6XN487UwqJcn:brp5git) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L95)):*
> ```Go
> // the encoded transaction or an error if the unsigned transaction cannot be
> // built.
> func buildSimTx(
> ```

again, most of the logic here and in signTx is the same, why can't they be merged?
___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9ai4SxDqmhrEz5jcJr:b1d6tps) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Those params should be configarable for the client, so you should be able to pass the "Config" with the them to the "New" func. Or use the DefaultConfig() with the defaults. 
</blockquote></details>

Could you give an example of scenario where you would like to provide different values?
___
*[`pkg/client2/client.go` line 41 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ajLScAqLrKqhhgr3n:-N9ajLScAqLrKqhhgr3o:b5mj09m) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L41)):*
> ```Go
> 	EstimateGas(ctx context.Context, config TxConfig, msgs ...sdk.Msg) (int64, error)
> 	BroadcastAsync(ctx context.Context, config TxConfig, msgs ...sdk.Msg) (string, error)
> 	BroadcastSync(ctx context.Context, config TxConfig, msgs ...sdk.Msg) (*TxResult, error)
> ```

*TxResult -> TxResult There is no need to use pointer
___
*[`pkg/client2/client.go` line 42 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ajMkx13LWFagNsDx3:-N9ajMkx13LWFagNsDx4:b5mj09m) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L42)):*
> ```Go
> 	BroadcastAsync(ctx context.Context, config TxConfig, msgs ...sdk.Msg) (string, error)
> 	BroadcastSync(ctx context.Context, config TxConfig, msgs ...sdk.Msg) (*TxResult, error)
> 	TxResult(ctx context.Context, txHash string) (*TxResult, error)
> ```

*TxResult -> TxResult There is no need to use pointer
___
*[`pkg/client2/client.go` line 85 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ajlzC0zWLcz-ff3Dd:-N9ajlzC0zWLcz-ff3De:b-tp6oto) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L85)):*
> ```Go
> }
> 
> func (c coreClient) ClientContext() client.Context {
> ```

ClientContext -> Context, the code will be called like `client.ClientContext()` which seems weird, `client.Context()` is cleaner
___
*[`pkg/client2/client.go` line 158 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9alBbw6Pqbm63lMptp:-N9alBbw6Pqbm63lMptq:bxpznf) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L158)):*
> ```Go
> 	if err != nil {
> 		if errors.Is(err, requestCtx.Err()) {
> 			return txHash, errors.WithStack(err)
> ```

don't return real txHash in case of error, error message should contsain it instead
___
*[`pkg/client2/client.go` line 163 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9alPPz3Eb6d7hN5wnH:-N9alPPz3Eb6d7hN5wnI:bxpznf) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L163)):*
> ```Go
> 		errRes := checkTendermintError(err, txHash)
> 		if !isTxInMempool(errRes) {
> 			return txHash, errors.WithStack(err)
> ```

don't return real txHash in case of error, error message should contsain it instead
___
*[`pkg/client2/client.go` line 171 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9am8tzDia0QRdHFM-u:-N9am8tzDia0QRdHFM-v:bveocii) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L171)):*
> ```Go
> 	}
> 
> 	return res.Hash.String(), nil
> ```

res.Hash.String() -> txHash, no need to compute it again



_Code quote:_
```Go
res.Hash.String()
```
___
*[`pkg/client2/client.go` line 175 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9amy3RA3Q7tXGvq-nT:-N9amy3RA3Q7tXGvq-nU:b-p62e4r) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L175)):*
> ```Go
> 
> // TxResult awaits until a signed transaction is included in a block, returing the TxResult.
> func (c coreClient) TxResult(ctx context.Context, txHash string) (*TxResult, error) {
> ```

Method name should be more self-explanatory here. Previous `AwaitTx` was better IMO.
___
*[`pkg/client2/client.go` line 179 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9amUPg473oz98YrenM:-N9amUPg473oz98YrenN:brdi2hk) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L179)):*
> ```Go
> 	if err != nil {
> 		err = errors.Wrap(err, "tx hash is not a valid hex")
> 		return nil, err
> ```

@miladz68 @ysv 

For past weeks I tried to give this pattern:

```go
err = ...
return nil, err
```

 a chance but I still find it to be weird. Is it acceptable across the team?
___
*[`pkg/client2/client.go` line 322 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9aqR_Z269UJJChTpsf:-N9aqR_Z269UJJChTpsg:bgdnl05) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L322)):*
> ```Go
> // function returns the correct code back in TxResponse.
> //
> // NOTE: Copypasta from Cosmos SDK! To avoid hassle getting the tx hash.
> ```

Copypasta -> Copy-paste
Please provide the link to the original code
___
*[`pkg/client2/client.go` line 323 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9arUc18GGmInL3oD3l:-N9arUc18GGmInL3oD3m:b-7vm4nf) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L323)):*
> ```Go
> //
> // NOTE: Copypasta from Cosmos SDK! To avoid hassle getting the tx hash.
> func checkTendermintError(err error, txHash string) *sdk.TxResponse {
> ```

Once this logic was copied, this function could return `*sdkerrors.Error` leading to great simplification of `isTxInMempool`, `isSDKErrorResult` and other code around.
___
*[`pkg/client2/tx.go` line 11 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9asDBODCU8wIifu0Vc:-N9asDBODCU8wIifu0Vd:b7cu3sc) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L11)):*
> ```Go
> type TxConfig struct {
> 	From        sdk.AccAddress
> 	FromAccount *accountInfo
> ```

Field is exported so type `accountInfo` must be exported too
___
*[`pkg/client2/tx.go` line 14 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9as5Qe9UgdEuWGLPtr:-N9as5Qe9UgdEuWGLPts:bi9wrul) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L14)):*
> ```Go
> 	Keyring     keyring.Keyring
> 	GasLimit    uint64
> 	GasPrice    *sdk.Coin
> ```

why is it a pointer?
___
*[`pkg/client2/tx.go` line 19 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9aspjr9mBpCIOOLpza:-N9aspjr9mBpCIOOLpzb:b-rrnbg5) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L19)):*
> ```Go
> 
> // SetA [...]

2022-08-16 13:56 UTC, dzmitryhil reviewed
> Reviewed 8 of 12 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 42 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/client2/build_tx.go` line 2 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9agqtz8S2fi0QsswU9:-N9agqtz8S2fi0QsswUA:bgvv0zz) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L2)):*
> ```Go
> package client2
> ```

Just curious, what is the reason to have build_tx and tx in separate files?
___
*[`pkg/client2/build_tx.go` line 85 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ahzB52uMVUaQ5jsUR:-N9ahzB52uMVUaQ5jsUS:bedx1ic) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L85)):*
> ```Go
> 	sigData.Signature = sigBytes
> 
> 	if err := txBuilder.SetSignatures(sig); err != nil {
> ```

Could you please elaborate why do you call this func here and few lines above? 
___
*[`pkg/client2/client.go` line 168 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9av-VN-sONl55SzqkA:-N9av-VN-sONl55SzqkB:bkgpac9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L168)):*
> ```Go
> 		err := errors.Wrapf(sdkerrors.New(res.Codespace, res.Code, res.Log),
> 			"transaction '%s' failed", txHash)
> 		return txHash, err
> ```

Do you want to retrun the hash even in the case of error? 
___
*[`pkg/client2/tx.go` line 37 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9alqis3c48-F3duOwL:-N9alqis3c48-F3duOwM:beqnbkx) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L37)):*
> ```Go
> 
> // accountInfo stores account number and sequence
> type accountInfo struct {
> ```

What is the pupose to make in unexported?
___
*[`pkg/keyring/keyring.go` line 88 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ak_Oj0bZbc6WpcIBo:-N9ak_Oj0bZbc6WpcIBp:b-pxr9nm) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/keyring.go#L88)):*
> ```Go
> 			// kb has a key and it's totally usable
> 			return keyInfo.GetAddress(), kb, nil
> 		case keyring.TypeLedger:
> ```

All types apart from the "TypeLocal" are not covered by the tests.  The table tests could simplify that process. 
You can check the other blocks in this file as well. Since the file contains not straightforward logic better to cover it, if the team access the entire implementation of course.
___
*[`pkg/keyring/keyring_test.go` line 36 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9akFTYCfvTLCvQYrJz:-N9akFTZ4npEQ1YtPVfS:b-g8rnc2) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/keyring_test.go#L36)):*
> ```Go
> 	requireT.Equal(hd.Secp256k1Type, info.GetAlgo())
> 
> 	showPrivkey(kb, accAddr)
> ```

Do we need to print the private key in the test ?
___
*[`pkg/keyring/testdata/keyring-file/f8321703ec9d253eede8eb50b15ed243b8459e53.address` line 0 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9aifxXB9IwoHtGPpnY:-N9aifxXB9IwoHtGPpnZ:b-n4rl6k) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/testdata/keyring-file/f8321703ec9d253eede8eb50b15ed243b8459e53.address#L0)):*
Don't you know whether it's possible to generate it on flight for the tests, instead of keeping the files?


<!-- Sent from Reviewable.io -->

2022-08-16 13:59 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 41 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9awX2C9VD8QP-Kxap_:bm0j9mj) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you give an example of scenario where you would like to provide different values?
</blockquote></details>

I expect to work with the nodes under load so the "10 * time.Second" request timeout isn't enoght for me. 


<!-- Sent from Reviewable.io -->

2022-08-16 14:10 UTC, xlab commented
*[`pkg/client2/build_tx.go` line 85 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ahzB52uMVUaQ5jsUR:-N9azVdXDWdmz2XwJws6:b-f0wqus) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please elaborate why do you call this func here and few lines above? 
</blockquote></details>

probably leftover from many merges, let me check


<!-- Sent from Reviewable.io -->

2022-08-16 14:11 UTC, xlab commented
*[`pkg/client2/build_tx.go` line 95 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9au2rj6XN487UwqJcm:-N9azZOx2ilWi08i2qr3:b-xzpmgj) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

again, most of the logic here and in signTx is the same, why can't they be merged?
</blockquote></details>

Because there is no signing logic, and I don't want to introduce special cases to make the switch between modes as obscure as possible.

There is no harm if 10 lines of code are repeated twice.


<!-- Sent from Reviewable.io -->

2022-08-16 14:18 UTC, xlab commented
*[`pkg/client2/client.go` line 42 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ajMkx13LWFagNsDx3:-N9b02Q76a4INNj3LUDP:b-5y2ov9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

*TxResult -> TxResult There is no need to use pointer
</blockquote></details>

It's needed to pass `nil` around, instead of making an  empty result `TxResult{}` every time.


<!-- Sent from Reviewable.io -->

2022-08-16 14:18 UTC, xlab commented
*[`pkg/client2/client.go` line 41 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ajLScAqLrKqhhgr3n:-N9b0DWf5NsLUddSY2ct:b-bgnygp) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

*TxResult -> TxResult There is no need to use pointer
</blockquote></details>

It's needed to pass nil around, instead of making an empty result TxResult{} every time.


<!-- Sent from Reviewable.io -->

2022-08-16 14:18 UTC, xlab commented
*[`pkg/client2/build_tx.go` line 2 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9agqtz8S2fi0QsswU9:-N9b0GyU8IoEDcBiMM0_:b9e57oz) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Just curious, what is the reason to have build_tx and tx in separate files?
</blockquote></details>

I'll merge.


<!-- Sent from Reviewable.io -->

2022-08-16 14:20 UTC, xlab commented
*[`pkg/client2/client.go` line 158 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9alBbw6Pqbm63lMptp:-N9b0O7hAdhlfwPKM27x:bqcxlbo) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L158)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

don't return real txHash in case of error, error message should contsain it instead
</blockquote></details>

If external code wants to access the tx result and parse it, it shouldn't try to get tx hash from outside an error string.

The function accepts list of msgs, so there is no way for any external code to get that hash. 

The hash is known and this point, there is no point of hiding it.


<!-- Sent from Reviewable.io -->

2022-08-16 14:21 UTC, xlab commented
*[`pkg/client2/client.go` line 168 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9av-VN-sONl55SzqkA:-N9b0vg-Bmr5RHRosjcd:b8p8mpt) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L168)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you want to retrun the hash even in the case of error? 
</blockquote></details>

https://reviewable.io/reviews/CoreumFoundation/coreum/134#-N9alBbw6Pqbm63lMptp

Hash is known regardless the server response


<!-- Sent from Reviewable.io -->

2022-08-16 14:23 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 41 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 243 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9Wm_xH2R_86SkijVA5:-N9b1IXRA4pD-4bHntgi:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L243)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This type needs to be removed, alongside the method that uses it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 14:23 UTC, xlab commented
*[`pkg/client2/client.go` line 323 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9arUc18GGmInL3oD3l:-N9b1M8MC7ir5dMVO5qQ:b-d4m47y) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L323)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Once this logic was copied, this function could return `*sdkerrors.Error` leading to great simplification of `isTxInMempool`, `isSDKErrorResult` and other code around.
</blockquote></details>

I am not intended to rewrite copy-pasted code. The good part about it is that this action can be done blindly and don't introduce any issues.


<!-- Sent from Reviewable.io -->

2022-08-16 14:24 UTC, xlab commented
*[`pkg/client2/tx.go` line 14 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9as5Qe9UgdEuWGLPtr:-N9b1ac80NwJQcrg7xV5:b-tlpd8s) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it a pointer?
</blockquote></details>

To align with previous logic that uses it. Previous logic checked the value for `nil`.


<!-- Sent from Reviewable.io -->

2022-08-16 14:25 UTC, xlab commented
*[`pkg/client2/tx.go` line 19 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9aspjr9mBpCIOOLpza:-N9b1hSO3joYK5qjbY5l:b-y44cgj) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You provide only `SetAccountNumber` and `SetAccountSequence`, but no `SetMemo` for example. What's the point? `FromAccount` might be set manually like other fields.
</blockquote></details>

It's unrelated, the idea is that both are overriding the default value and make this action explicit.


<!-- Sent from Reviewable.io -->

2022-08-16 14:26 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 41 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/tx.go` line 37 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9alqis3c48-F3duOwL:-N9b1vtIEfNSIQnQj5Z3:byiw851) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the pupose to make in unexported?
</blockquote></details>

Info like should be managed by client, with explicit overrides from outside. By default, it fetches this data from chain.


<!-- Sent from Reviewable.io -->

2022-08-16 14:30 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 41 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/keyring/keyring_test.go` line 36 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9akFTYCfvTLCvQYrJz:-N9b2Sst6jTet4Jcp7SP:bvl9ih9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/keyring_test.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need to print the private key in the test ?
</blockquote></details>

Many keys in other tests (integrations, etc) are hardcoded as hex privkeys. That was a quick helper to quickly obtain a hex-encoded privkey that is a valid Cosmos key. 

I initially commented it out, but linter will complain that `showPrivkey` is not used. I decided not to remove `showPrivkey`, because it is useful while maintaining this test and others. So this is a forced usage :D

TL;DR: just so linter doesn't complain about dead code


<!-- Sent from Reviewable.io -->

2022-08-16 14:34 UTC, xlab commented
*[`pkg/keyring/testdata/keyring-file/f8321703ec9d253eede8eb50b15ed243b8459e53.address` line  at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9aifxXB9IwoHtGPpnY:-N9b33ceEcTadV3-JMgm:b58vtb2) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/testdata/keyring-file/f8321703ec9d253eede8eb50b15ed243b8459e53.address#L)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't you know whether it's possible to generate it on flight for the tests, instead of keeping the files?
</blockquote></details>

Dunno, that's a testdata (fixtures) pattern. Rebuilding it every time test runs is easy, but requires that binary of the node is existing in PATH, etc. Or we could dynamically orchestrate key generation but that means copying CLI chunks from SDK. And they are not trivial and require own testing..

The fixtures there were obtained by running the node keys command: `cored keys add test`


<!-- Sent from Reviewable.io -->

2022-08-16 16:03 UTC, oliverasistemas commented
@xlab Can you please update branch with latest master?

2022-08-16 17:06 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 41 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9bag9QAFoYwczAETA_:b-4gmrwi) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I expect to work with the nodes under load so the "10 * time.Second" request timeout isn't enoght for me. 
</blockquote></details>

If our blockchain can't add transaction to mempool in 10 seconds it means that our problem is somewhere else, not in the timeout set here
___
*[`pkg/client2/client.go` line 41 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ajLScAqLrKqhhgr3n:-N9bb-9k03EVErp8m2th:bsk4ast) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L41)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's needed to pass nil around, instead of making an empty result TxResult{} every time.
</blockquote></details>

I think returning empty `TxResult{}` is the preferred solution as this is a data storage object not something managing internal state


<!-- Sent from Reviewable.io -->

2022-08-17 04:31 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 41 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 323 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9arUc18GGmInL3oD3l:-N9e2b_E4Ugko3qtvgVj:b-esw8jl) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L323)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I am not intended to rewrite copy-pasted code. The good part about it is that this action can be done blindly and don't introduce any issues.
</blockquote></details>

If you look how the result of this function is used (by being passed to `isTxInMempool` function) you will find that

```go
strings.Contains(errStr, strings.ToLower(mempool.ErrTxInCache.Error())
```

is the only interesting line here. The rest is a garbage.


<!-- Sent from Reviewable.io -->

2022-08-17 06:36 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 43 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9bW1ox96XgWmEJqJf2:-N9bW1ox96XgWmEJqJf3:b4n1y48) (no related file):*
@xlab 
It was decided to rename the package from client to tx. It will no longer be an interface but a set of independent functions like the following.
It naturally follows that key-ring will not be supported since it is no longer a client abstraction but a set of helper functions, and private key will be used. 
```
package tx

func Broadcast(ctx context.Context,clientContext client.Context, config TxConfig, msgs ...sdk.Msg) (FullBroadCastSdkResponse, error)
func Await(ctx context.Context,clientContext client.Context,txHash string) (sdk.awaitResponseFromSDK,error)
func EstimateGas(ctx context.Context,clientContext client.Context, msgs ...sdk.Msg) (int64, error)
```

___
___
*[`pkg/client2/tx.go` line 12 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9b0eDnEm69nqfugRvN:-N9b0eDnEm69nqfugRvO:b-4l8t21) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/tx.go#L12)):*
> ```Go
> 	From        sdk.AccAddress
> 	FromAccount *accountInfo
> 	Keyring     keyring.Keyring
> ```

The keyring seems unnecessary, I would just pass private key.



_Code quote:_
```Go
TxConfig
```


<!-- Sent from Reviewable.io -->

2022-08-17 07:04 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 43 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9bW1ox96XgWmEJqJf2:-N9ebE819DKg551Idg8h:b-t17tm8) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@xlab 
It was decided to rename the package from client to tx. It will no longer be an interface but a set of independent functions like the following.
It naturally follows that key-ring will not be supported since it is no longer a client abstraction but a set of helper functions, and private key will be used. 
```
package tx

func Broadcast(ctx context.Context,clientContext client.Context, config TxConfig, msgs ...sdk.Msg) (FullBroadCastSdkResponse, error)
func Await(ctx context.Context,clientContext client.Context,txHash string) (sdk.awaitResponseFromSDK,error)
func EstimateGas(ctx context.Context,clientContext client.Context, msgs ...sdk.Msg) (int64, error)
```
</blockquote></details>

@xlab 
the function and struct names there are not final, it is just to provide a sketch on how it will look like. spend some time to suggest better names and it will probably discussed again. 

___


<!-- Sent from Reviewable.io -->

2022-08-17 07:13 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 38 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/build_tx.go` line 2 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9agqtz8S2fi0QsswU9:-N9edW9g525L29RHn1Cj:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L2)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I'll merge.
</blockquote></details>

ok
___
*[`pkg/client2/build_tx.go` line 85 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ahzB52uMVUaQ5jsUR:-N9edRpS1jD5_XnVwMsd:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/build_tx.go#L85)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

probably leftover from many merges, let me check
</blockquote></details>

ok
___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9ecA1C9qUUaMCMIgcr:bl3anb) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If our blockchain can't add transaction to mempool in 10 seconds it means that our problem is somewhere else, not in the timeout set here
</blockquote></details>

Nope, the issue might be with network, or with the CPU load and so on, I'm OK to implement it separately not in this PR, but we should implement it. Do we create the github issues?
___
*[`pkg/client2/client.go` line 223 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-223:-N9edT1wDWP_krvXufPY:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L223)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

@wojtek-coreum needs to rewrite this code, I don't think I can understand what it does.
</blockquote></details>

ok
___
*[`pkg/client2/client.go` line 158 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9alBbw6Pqbm63lMptp:-N9ecdt_BwUR4Cg2-Sfv:b-nemxu9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L158)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

If external code wants to access the tx result and parse it, it shouldn't try to get tx hash from outside an error string.

The function accepts list of msgs, so there is no way for any external code to get that hash. 

The hash is known and this point, there is no point of hiding it.
</blockquote></details>

In that case the hash should be inside the error
___
*[`pkg/client2/client.go` line 168 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9av-VN-sONl55SzqkA:-N9eciN56sTLzvuLtyKr:b-ryxi6v) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L168)):*
> https://reviewable.io/reviews/CoreumFoundation/coreum/134#-N9alBbw6Pqbm63lMptp
 Left message in that thread
___
*[`pkg/keyring/keyring.go` line 88 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9ak_Oj0bZbc6WpcIBo:-N9ecuGI8EWwc0XzIxPy:b-hnrxj9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/keyring.go#L88)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

We don't access other stuff, but once we start to do it, it's worth covering. The idea is that the existence of this keyring wrapper is questionable, once approved, tests can be extended.
</blockquote></details>

Right, thant's why I left "if the team access the entire implementation" part. But if we go with the keyrink we should cover it. 
___
*[`pkg/keyring/keyring_test.go` line 36 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9akFTYCfvTLCvQYrJz:-N9ed44A2wbGTQgEKYck:b-l1jphk) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/keyring/keyring_test.go#L36)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Many keys in other tests (integrations, etc) are hardcoded as hex privkeys. That was a quick helper to quickly obtain a hex-encoded privkey that is a valid Cosmos key. 

I initially commented it out, but linter will complain that `showPrivkey` is not used. I decided not to remove `showPrivkey`, because it is useful while maintaining this test and others. So this is a forced usage :D

TL;DR: just so linter doesn't complain about dead code
</blockquote></details>

The PR is to the master, right, so no dead code should there, if you want to keep it anyway better to add nolint then print has without a reason 


<!-- Sent from Reviewable.io -->

2022-08-17 07:14 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 179 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9amUPg473oz98YrenM:-N9ed2xc9VFxSw2A8s1X:bkwem6c) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L179)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

In this instance nothing is achieved by that extra code, but there are instances that one extra line increases readability. 
I would call it acceptable, I prefer not to have this extra line, but it seems nitpicking.


<!-- Sent from Reviewable.io -->

2022-08-17 07:50 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 14 of 21 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9ejdv61a1pIZal0MXu:b-22h5kv) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Nope, the issue might be with network, or with the CPU load and so on, I'm OK to implement it separately not in this PR, but we should implement it. Do we create the github issues?
</blockquote></details>

Before doing this could we wait for the moment when it is really needed? The change you propose requires adding 3 CLI flags to all the tools we create. If your network or CPU is overloaded it just means that it is not a good moment to use your resources. If your computer can't send transaction in 10 seconds it means your computer/network needs to be fixed first, not the software.
___
*[`pkg/client2/client.go` line 223 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-223:-N9ekXtH3ne8lLYqELjS:bjnxz1p) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L223)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

ok
</blockquote></details>

@xlab weren't it you who proposed using `client.CheckTendermintError` to detect particular tendermint error? I believe you understand pretty well what this code does. After copying `client.CheckTendermintError` to our codebase this logic might be greatly simplified and I think this PR is a good moment to do it.


<!-- Sent from Reviewable.io -->

2022-08-17 09:15 UTC, dzmitryhil reviewed
> Reviewed 7 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 23 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9f3nOtDz9hNmRfKb5f:b5yj8oq) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Before doing this could we wait for the moment when it is really needed? The change you propose requires adding 3 CLI flags to all the tools we create. If your network or CPU is overloaded it just means that it is not a good moment to use your resources. If your computer can't send transaction in 10 seconds it means your computer/network needs to be fixed first, not the software.
</blockquote></details>

I'm ok to wait. But for sure it's a good practice to let consumers decide, we can just recommend.


<!-- Sent from Reviewable.io -->

2022-08-22 05:52 UTC, wojtek-coreum reviewed
> Reviewed 8 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: 17 of 22 files reviewed, 22 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-22 06:36 UTC, wojtek-coreum requested changes
> Reviewed 5 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 22 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network_test.go` line 341 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3CQji7P1FZ24Gh2P1:-NA3CQji7P1FZ24Gh2P2:b-gc2i70) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/app/network_test.go#L341)):*
> ```Go
> 
> // prepareTxStakingCreateValidator generates transaction of type MsgCreateValidator
> func prepareTxStakingCreateValidator(
> ```

@miladz68 @ysv 

This is the first place where I immediately see that two repositories will have to create the same helper around cosmos sdk. The same logic is used by `znet` to prepare the network. Do you think it's reasonable to export it and move it to `tx` package?
___
*[`app/network_test.go` line 343 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3DhaP8PeLRaEnFVoL:-NA3DhaP8PeLRaEnFVoM:b-31ttkh) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/app/network_test.go#L343)):*
> ```Go
> func prepareTxStakingCreateValidator(
> 	clientCtx client.Context,
> 	validatorPublicKey ed25519.PublicKey,
> ```

here and in the next line: we decided to use sdk types directly so we should use them consistently everywhere insted of types which will be deleted
___
*[`app/network_test.go` line 362 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3DKdkCtTrctLAo4VJ:-NA3DKdkCtTrctLAo4VK:b-dtgmea) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/app/network_test.go#L362)):*
> ```Go
> 	stakerAddress := sdk.AccAddress(stakerPrivKey.PubKey().Address())
> 
> 	msg, err := stakingtypes.NewMsgCreateValidator(sdk.ValAddress(stakerAddress), valPubKey, amount, stakingtypes.Description{Moniker: stakerAddress.String()}, commission, sdk.OneInt())
> ```

I remember that, during the discussion you said that message constructors in cosmos sdk are legacy and it's better to create a message struct directly. Should it be the case here too?
___
*[`integration-tests/testing/types.go` line 29 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3AWEzE1AW7fEmc8rt:-NA3AWEzE1AW7fEmc8ru:bdczacc) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/integration-tests/testing/types.go#L29)):*
> ```Go
> 	Client client.Client
> 
> 	RPCAddr string
> ```

I think tests should receive ready to use client context instead
___
*[`pkg/tx2/tx.go` line 16 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3An4XAkV6LSps4c2f:-NA3An4YEkBvXnzE1lfY:b-ldw1c8) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/pkg/tx2/tx.go#L16)):*
> ```Go
> // TxConfig holds values common to every transaction
> type TxConfig struct {
> 	From     sdk.AccAddress
> ```

Address can be derived from private key as long as we don't use `zauth`. 
___
*[`pkg/tx2/tx.go` line 19 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3BrEy6Gmpb7nGWhVX:-NA3BrEy6Gmpb7nGWhVY:bsvao68) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/pkg/tx2/tx.go#L19)):*
> ```Go
> 	PrivKey  cryptotypes.PrivKey
> 	GasLimit uint64
> 	GasPrice *sdk.Coin
> ```

Could you check if `znet` starts chain correctly if this value is not a pointer but default `sdk.Coin{}` is used instead of nil?
___
*[`pkg/tx2/tx.go` line 22 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3B8t5EXrG0subFrgG:-NA3B8t5EXrG0subFrgH:b-w6f4un) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/pkg/tx2/tx.go#L22)):*
> ```Go
> 	Memo     string
> 
> 	fromAccount *accountInfo
> ```

I don't see reason for having this field private and having methods used to set it instead of exposing it directly to the caller.


<!-- Sent from Reviewable.io -->

2022-08-22 06:41 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 23 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/tx2/client.go` line 68 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA3GTt0BXF8EsgAWel9:-NA3GTt166UWGnjxdZ5B:b-pj0n6f) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/pkg/tx2/client.go#L68)):*
> ```Go
> 	address sdk.AccAddress,
> ) (num uint64, seq uint64, err error) {
> 	addr, err := sdk.AccAddressFromBech32(string(address))
> ```

`address` is of type `sdk.AccAddress` now


<!-- Sent from Reviewable.io -->

2022-08-22 10:16 UTC, ysv requested changes
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 19 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-N9ao4HWEzVzA9qyEYCQ:bnrvw01) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Those params should be configarable for the client, so you should be able to pass the "Config" with the them to the "New" func. Or use the DefaultConfig() with the defaults. 
</blockquote></details>

makes sense for me
___
*[`pkg/client2/client.go` line 179 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9amUPg473oz98YrenM:-NA41OPxEeNYPuM2mFnU:b-bnma2r) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0280bce15c7678f3409f060dfd83006e7b98949/pkg/client2/client.go#L179)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

In this instance nothing is achieved by that extra code, but there are instances that one extra line increases readability. 
I would call it acceptable, I prefer not to have this extra line, but it seems nitpicking.
</blockquote></details>

Absolutely the same for me.
I was trying to get used to this version but it still doesn't make a lot of sense for me
@wojtek-coreum lets create a poll in chat because we have 2 new members 


<!-- Sent from Reviewable.io -->

2022-08-22 10:18 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 20 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-22 10:27 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 20 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client2/client.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/134#-N9HGtl189PwYQlZZbMr-r4-36:-NA44qiaBVebWv6F8niy:bexi8kv) ([raw file](https://github.com/coreumfoundation/coreum/blob/e0c27962388cfe1e37cbb28661b51d36e5e95229/pkg/client2/client.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

makes sense for me
</blockquote></details>

makes sense to do this configurable
not critical right now


<!-- Sent from Reviewable.io -->

2022-08-22 11:16 UTC, dzmitryhil reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-22 13:04 UTC, dzmitryhil reviewed
> Reviewed 4 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-22 17:35 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/134)* status: all files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/tx2/client.go` line 153 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/134#-NA5bRRF8P293bv7zI_Z:-NA5bRRG-xybVzfSACuF:b-vsm210) ([raw file](https://github.com/coreumfoundation/coreum/blob/6e813e453023924b5fd59199cb79ab1239853592/pkg/tx2/client.go#L153)):*
> ```Go
> 		}
> 	} else if res.Code != 0 {
> 		err := errors.Wrapf(sdkerrors.New(res.Codespace, res.Code, res.Log),
> ```

This is the wrong usage of the New. The New registers the New error and return it, but if the error is already registered it will cause the papic. Use the "ABCIError" instead, to get the registered error. Same comment for all "sdkerrors.New(". 


<!-- Sent from Reviewable.io -->

2022-08-24 10:50 UTC, ysv commented
Closing this PR
@miladz68 will do this in a separate one

2022-08-24 10:50 UTC, closed without merging