Run integration tests using `go test` framework
CoreumFoundation/coreum pull request #140
Opened 2022-08-17 18:47 UTC by wojtek-coreum

This is PoC of running integration tests using `go test` command.
- It is implemented in the way that existing tests may be executed both by old and new framework during transition period (with minor modification).
- Parameters (node address, private key) are hardcoded now
- It still needs to be integrated into crust
- It is slower because it funds accounts one by one (waiting for new client helpers to fund all accounts at once)

How to run tests manually before crust supports new framework:
```
$ znet start --mode=test
$ cd coreum/integration-tests
$ go test -tags=integration -parallel=10 -v .
```

2022-08-18 11:05 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-N9kUSRAAkBBhc8ilGD1:bu5y3ib) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
> ```Go
> // +build integration
> 
> package tests_test
> ```

rename to `integration_tests` ? 
Also I would prefer file to be named integration_tests.go
___
*[`integration-tests/integration_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9k_Dhl1ZFrEj1vLlMS:-N9k_Dhl1ZFrEj1vLlMT:b-haeexf) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L25)):*
> ```Go
> )
> 
> func Test(t *testing.T) {
> ```

is it some sort of specific func ?
because I knew about customizing this using `TestMain(m *testing.M)` but this one is smth new for me
___
*[`integration-tests/integration_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kYZLl29nN4l2MmORx:-N9kYZLl29nN4l2MmORy:bjc4v44) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L28)):*
> ```Go
> 	var (
> 		coredAddress        = "localhost:26657"
> 		hornOfPlentyPrivKey = types.Secp256k1PrivateKey{0x86, 0x2f, 0x17, 0xc3, 0x51, 0x83, 0xbe, 0x2a, 0x2b, 0x5d, 0x5b, 0x5b, 0xb5, 0x53, 0x86, 0xd8, 0xad, 0xc8, 0xde, 0x51, 0xa9, 0x73, 0x3f, 0xb7, 0x7d, 0x72, 0xb9, 0x29, 0x91, 0xb7, 0x2c, 0x60}
> ```

funny name )
but was a bit hard to understand initially what you mean
___
*[`integration-tests/integration_test.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9k_OJj5A9QXalI3GN7:-N9k_OJj5A9QXalI3GN8:b3gj249) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L31)):*
> ```Go
> 	)
> 
> 	loggerConfig := logger.ToolDefaultConfig
> ```

can we split this func into multiple ? I see 2-3 clear parts: setup, funding of wallets, running of tests
___
*[`integration-tests/integration_test.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kb4XY1K4S95QAqlKg:-N9kb4XY1K4S95QAqlKh:bp578je) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L92)):*
> ```Go
> 	}
> 
> 	for _, test := range testList {
> ```

pls rename to `tc` or `testCase` to not collude with existing type
___
*[`integration-tests/integration_test.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kaa_R1GK6Q4CQAAr8:-N9kaa_R1GK6Q4CQAAr9:bholrgo) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L97)):*
> ```Go
> 			t.Parallel()
> 
> 			ctx, cancel := context.WithCancel(logger.With(ctx, zap.String("test", test.Name)))
> ```

small improvement:

I would probably initialize log into a separate variable so we don't need to get it from ctx later
```
log := logger.With(ctx, zap.String("test", test.Name))
ctx, cancel := context.WithCancel(log)

t.Cleanup(cancel)

log.Info ...
```
___
*[`integration-tests/integration_test.go` line 112 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kawsn6rdAOL0mJpOx:-N9kawsn6rdAOL0mJpOy:b59qenj) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L112)):*
> ```Go
> }
> 
> func funcToName(f interface{}) string {
> ```

I'm just wondering how do they build this in default testing framework ?
Maybe we can reuse it ?
___
*[`integration-tests/integration_test.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kbgKG8NoLz2q8hUmc:-N9kbgKG8NoLz2q8hUmd:b-k6vdfh) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L117)):*
> ```Go
> 	funcName := strings.TrimSuffix(parts[len(parts)-1], ".func1")
> 
> 	return repoName + "." + funcName
> ```

is repo name still applicable if we have these tests only for coreum repo ?


<!-- Sent from Reviewable.io -->

2022-08-18 11:50 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-N9kl3hlC4wwxn7iv6vR:b-lkdr5o) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

rename to `integration_tests` ? 
Also I would prefer file to be named integration_tests.go
</blockquote></details>

The `go test` requires files to end with `_test.go`
Also package name must be the same as folder or with `_test` suffix added
___
*[`integration-tests/integration_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9k_Dhl1ZFrEj1vLlMS:-N9klSPR4r_LPma2dBFY:b-31qdzt) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it some sort of specific func ?
because I knew about customizing this using `TestMain(m *testing.M)` but this one is smth new for me
</blockquote></details>

Discussed in a meeting
___
*[`integration-tests/integration_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kYZLl29nN4l2MmORx:-N9klVeTA67yZF-9eDHW:b-vo9wef) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

funny name )
but was a bit hard to understand initially what you mean
</blockquote></details>

might it be like this or you prefer to change it?
The other option was `faucetPrivKey` but it would be misleading because of our real faucet API. Anything else? `fundingPrivKey`?
___
*[`integration-tests/integration_test.go` line 112 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kawsn6rdAOL0mJpOx:-N9km5iw34vO6ee1-sfA:b6cjvkg) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L112)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm just wondering how do they build this in default testing framework ?
Maybe we can reuse it ?
</blockquote></details>

I don't know. But in default framework they use only function name. Here I also add repo name so in the logs of CI we clearly see where too look for the particular function
___
*[`integration-tests/integration_test.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kbgKG8NoLz2q8hUmc:-N9kmSLV4dyVu4r0ufUf:bixpahd) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L117)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is repo name still applicable if we have these tests only for coreum repo ?
</blockquote></details>

As discussed in the meeting, once we have more repos with integration tests we will put this code in some common place and reuse.


<!-- Sent from Reviewable.io -->

2022-08-18 12:26 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-N9krVOx4T8Q4WGDRW8X:bqps9yh) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The `go test` requires files to end with `_test.go`
Also package name must be the same as folder or with `_test` suffix added
</blockquote></details>

should we rename directory to `integration-test` & package & file accordingly ?
___
*[`integration-tests/integration_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kYZLl29nN4l2MmORx:-N9kuTBO1N-MneedHV2r:b-y4n8lx) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

might it be like this or you prefer to change it?
The other option was `faucetPrivKey` but it would be misleading because of our real faucet API. Anything else? `fundingPrivKey`?
</blockquote></details>

fundingPrivKey ok for me
___
*[`integration-tests/integration_test.go` line 112 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kawsn6rdAOL0mJpOx:-N9kuct-2hkHUijMTFuA:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L112)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't know. But in default framework they use only function name. Here I also add repo name so in the logs of CI we clearly see where too look for the particular function
</blockquote></details>

ok
___
*[`integration-tests/integration_test.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kbgKG8NoLz2q8hUmc:-N9kucCtEcCO1zeEOUX3:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L117)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As discussed in the meeting, once we have more repos with integration tests we will put this code in some common place and reuse.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-08-18 12:54 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-N9l02Cw-UTrznPo09tL:bfnf81g) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we rename directory to `integration-test` & package & file accordingly ?
</blockquote></details>

we may do that I guess


<!-- Sent from Reviewable.io -->

2022-08-18 15:33 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-N9l_fLMA_1BUOkFH1Lq:b9bxrgx) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we may do that I guess
</blockquote></details>

It might be done once crust starts using new framework


<!-- Sent from Reviewable.io -->

2022-08-18 16:30 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kYZLl29nN4l2MmORx:-N9la8v7EjYjXR72iq_u:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fundingPrivKey ok for me
</blockquote></details>

Done.
___
*[`integration-tests/integration_test.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9k_OJj5A9QXalI3GN7:-N9lhc03EznpaAV0NJQ8:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we split this func into multiple ? I see 2-3 clear parts: setup, funding of wallets, running of tests
</blockquote></details>

Done.
___
*[`integration-tests/integration_test.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kb4XY1K4S95QAqlKg:-N9ladmJ0FRd2jQL1_TR:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls rename to `tc` or `testCase` to not collude with existing type
</blockquote></details>

Done.
___
*[`integration-tests/integration_test.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kaa_R1GK6Q4CQAAr8:-N9laqmyEu4Yzviz0DFI:bh53ipk) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L97)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

small improvement:

I would probably initialize log into a separate variable so we don't need to get it from ctx later
```
log := logger.With(ctx, zap.String("test", test.Name))
ctx, cancel := context.WithCancel(log)

t.Cleanup(cancel)

log.Info ...
```
</blockquote></details>

`logger.With` returns context, not logger. Returned context contains logger with additional fields. This context is then passed to test so whenever test logs something the field is there


<!-- Sent from Reviewable.io -->

2022-08-18 17:58 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9m07aC1GZ3CxgG-NC_:-N9m07aC1GZ3CxgG-NCa:bffqa4t) (no related file):*
I implemented this functionality using `go test` framework as @ysv proposed but I still think it's a bad idea. My arguments:

- using two functions `TestMain` and `Test` instead of `main`
- global `cfg`, forced by previous item
- using `flag` package instead of `pflag`, which we use in all other applications and we have helpers for (configuring logger)
- `pflag` would allow to specify many filters and running tests matching ay of them, with `flag` setting only one filter is possible
- we must set `//go:build integration` to not collide wit regular unit tests
- no `--help` flag printing our custom flags
- we had to implement our own `-filter` flag because existing `-run` does not serve our needs
- logs produced by `go test` don't go through `zap` logger, so tests produce logs in two different formats now
- if integration test starts goroutines and would like to use `require.*` functions, it can't
- reading `-v` flag from CLI is a crap


And we accept all those disadvantages just because `go test` gives us one feature: tests are run in parallel automatically.
This thing is trivial to do ourselves (and BTW we already have it). I highly recommend to rethink this decision once more.

___


<!-- Sent from Reviewable.io -->

2022-08-19 11:58 UTC, dzmitryhil reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 177 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9pxEZL9K9mQ_3IGQck:-N9pxEZL9K9mQ_3IGQcl:bmfo0ls) ([raw file](https://github.com/coreumfoundation/coreum/blob/ef2886a49b52cd5fef2efbaa7b361401041d4474/integration-tests/integration_test.go#L177)):*
> ```Go
> }
> 
> func runTests(t *testing.T, ctx context.Context, testCases []testCase) {
> ```

It it's a temp solution, then I'm ok with that. If not, then we should rewrite it in different way:
Here the testify/suite which does the similar but with the go idiomatic way. Also the IDE support the launch of just one test in the site, which is't allowed here.

https://pkg.go.dev/github.com/stretchr/testify/suite


<!-- Sent from Reviewable.io -->

2022-08-19 11:59 UTC, dzmitryhil reviewed
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-19 13:04 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/integration_test.go` line 177 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9pxEZL9K9mQ_3IGQck:-N9qBmJT2w9Gv2BosG2l:byggao1) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L177)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It it's a temp solution, then I'm ok with that. If not, then we should rewrite it in different way:
Here the testify/suite which does the similar but with the go idiomatic way. Also the IDE support the launch of just one test in the site, which is't allowed here.

https://pkg.go.dev/github.com/stretchr/testify/suite
</blockquote></details>

For now it can't be changed anyway because it needs to be compatible with what `crust` does at the moment. So as long `crust` uses old framework it must be done this way. As I mentioned at the beginning of this PR I'm against using `go test` for this at all because this is wrong tool for the job.


<!-- Sent from Reviewable.io -->

2022-08-19 14:05 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 177 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9pxEZL9K9mQ_3IGQck:-N9qPy9vEUuMSvLKnSTB:b9td4uf) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L177)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

For now it can't be changed anyway because it needs to be compatible with what `crust` does at the moment. So as long `crust` uses old framework it must be done this way. As I mentioned at the beginning of this PR I'm against using `go test` for this at all because this is wrong tool for the job.
</blockquote></details>

Sure, that time is ok, but let's not forget it nex time :-)


<!-- Sent from Reviewable.io -->

2022-08-19 16:54 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-21 11:51 UTC, miladz68 requested changes
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-N9zshrI5IGEpNSMCw2t:b-awxmqn) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
> integration_tests
why not `integration_test` without plural s ? or maybe `main_test.go` ?
___
*[`integration-tests/integration_test.go` line 53 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9ztRue3BcGCdGL0F2N:-N9ztRue3BcGCdGL0F2O:b-vqm4fq) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L53)):*
> ```Go
> 	cfg.LogFormat = logger.Format(logFormat)
> 	for _, flag := range os.Args[1:] {
> 		if flag == "-test.v=true" {
> ```

why not use pflag to achieve this ?
___
*[`integration-tests/integration_test.go` line 61 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA-7DPQ9Y0uUAo88nBc:-NA-7DPQ9Y0uUAo88nBd:b-cs9sko) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L61)):*
> ```Go
> }
> 
> func Test(t *testing.T) {
> ```

I see no good reason to have a `Test` function. its content should be moved to `TestMain`. if it is a helper function to make `TestMain` shorter and more readable, it must have a better name and not be exported. perhaps you discussed it in a meeting. 
___
*[`integration-tests/testing/types.go` line 29 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA-DmaX9WwoMs-bIyVz:-NA-DmaX9WwoMs-bIyW-:b-i5kori) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/testing/types.go#L29)):*
> ```Go
> 	Client  client.Client
> 	// FIXME (wojtek): Temporary solution to be removed after transition period
> 	Fund func(wallet types.Wallet, amount types.Coin)
> ```

I don't grasp why we will need this for the transition, we can use the old method on the network type.
___
*[`pkg/types/key.go` line 27 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA-8-hlBthDsQKHbR5B:-NA-8-hlBthDsQKHbR5C:b-g37mgf) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/pkg/types/key.go#L27)):*
> ```Go
> 
> // Address returns bech32 encoded wallet address for corresponding key
> func (key Secp256k1PublicKey) Address() string {
> ```

I don't see this added function being used.


<!-- Sent from Reviewable.io -->

2022-08-22 06:56 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-NA3KRTl930LYGXtaERU:b-gujfyd) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

> integration_tests
why not `integration_test` without plural s ? or maybe `main_test.go` ?
</blockquote></details>

renaming package is not possible in this PR because crust uses it
___
*[`integration-tests/integration_test.go` line 53 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9ztRue3BcGCdGL0F2N:-NA3HrTh8-frwVX5y-SL:bfi02rm) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L53)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why not use pflag to achieve this ?
</blockquote></details>

Because `go test` framework uses `flag`. I've already provided my arguments that `go test` is not the right tool to do the job, but @ysv and @dzmitryhil disagreed so we have what we have.
___
*[`integration-tests/integration_test.go` line 61 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA-7DPQ9Y0uUAo88nBc:-NA3IBWQ6X6B4QPPZBBf:b-555qg7) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L61)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see no good reason to have a `Test` function. its content should be moved to `TestMain`. if it is a helper function to make `TestMain` shorter and more readable, it must have a better name and not be exported. perhaps you discussed it in a meeting. 
</blockquote></details>

`TestMain` has no access to `t` which is essential for tests.
___
*[`integration-tests/testing/types.go` line 29 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA-DmaX9WwoMs-bIyVz:-NA3ILvMC4MGKQBKb3jw:b-olpypi) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/testing/types.go#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't grasp why we will need this for the transition, we can use the old method on the network type.
</blockquote></details>

Because `network` does not expose funded accounts. I could add a method there of course but I don't want to propagate hacky tmp changes to `app` package.
___
*[`pkg/types/key.go` line 27 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA-8-hlBthDsQKHbR5B:-NA3K96f24EiQJBL76Uo:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/pkg/types/key.go#L27)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't see this added function being used.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 08:00 UTC, miladz68 requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA3YKnm5rDq-26lvNw5:-NA3YKnm5rDq-26lvNw6:b-4q54s9) (no related file):*
@ysv @dzmitryhil 
I know that this is very late to have a comment like this, but I would like to know if you have considered using a test suite like this (https://github.com/stretchr/testify#suite-package). I am not saying it is a better practice per se, but please take a look if you have not already and give your opinion. I have seen many different packages use this test suite to manage their integration tests. 

___
___
*[`integration-tests/integration_test.go` line 53 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9ztRue3BcGCdGL0F2N:-NA3Urtu8MLIXn0kpjs_:b-7g524b) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L53)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because `go test` framework uses `flag`. I've already provided my arguments that `go test` is not the right tool to do the job, but @ysv and @dzmitryhil disagreed so we have what we have.
</blockquote></details>

I meant why not use flag/pflag to process the args, or why are we processing those cmd args directly and not using flag package ?


<!-- Sent from Reviewable.io -->

2022-08-22 08:21 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA3YKnm5rDq-26lvNw5:-NA3cYyi6UOnzwP6RsfH:bki2my0) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv @dzmitryhil 
I know that this is very late to have a comment like this, but I would like to know if you have considered using a test suite like this (https://github.com/stretchr/testify#suite-package). I am not saying it is a better practice per se, but please take a look if you have not already and give your opinion. I have seen many different packages use this test suite to manage their integration tests. 
</blockquote></details>

@dzmitryhil already proposed this. It might eventually be done, but first I need to switch to calling `go test` inside `crust` instead of imported go code directly

___
___
*[`integration-tests/integration_test.go` line 53 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9ztRue3BcGCdGL0F2N:-NA3cmaK4zr74neaAylz:b-nq7fxh) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L53)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I meant why not use flag/pflag to process the args, or why are we processing those cmd args directly and not using flag package ?
</blockquote></details>

This is flag delivered by `go test` directly and I can't use `flag` to access it, or is there any way I missed?


<!-- Sent from Reviewable.io -->

2022-08-22 08:31 UTC, dzmitryhil approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 9 unresolved discussions (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-08-22 11:54 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 8 unresolved discussions (waiting on @ysv)

___
*[`integration-tests/integration_test.go` line 53 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9ztRue3BcGCdGL0F2N:-NA4O3L_8rEuC6Alh7ZH:bu32mfe) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L53)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is flag delivered by `go test` directly and I can't use `flag` to access it, or is there any way I missed?
</blockquote></details>

You should be able to look it up with `Lookup` function if it is defined on the flagset, or define it if it is not already defined. If this flag is present in os.Args, then it should be accessible via flag package as well.

Either way I will make this comment as discussing if you cannot find a way, you can resolve it.


<!-- Sent from Reviewable.io -->

2022-08-22 13:49 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 8 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/integration_test.go` line 53 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9ztRue3BcGCdGL0F2N:-NA4o7FF7J9AkWBzd-kA:bsnq6p) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cf3ee0cac70b92e071c0d7428abe93a63953403/integration-tests/integration_test.go#L53)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

You should be able to look it up with `Lookup` function if it is defined on the flagset, or define it if it is not already defined. If this flag is present in os.Args, then it should be accessible via flag package as well.

Either way I will make this comment as discussing if you cannot find a way, you can resolve it.
</blockquote></details>

now I see that `flag.Lookup` is there, will try


<!-- Sent from Reviewable.io -->

2022-08-23 12:28 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 8 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 10:45 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/140)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9m07aC1GZ3CxgG-NC_:-NAEQxUR5nRfbCCg4ygF:b-psv7cr) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I implemented this functionality using `go test` framework as @ysv proposed but I still think it's a bad idea. My arguments:

- using two functions `TestMain` and `Test` instead of `main`
- global `cfg`, forced by previous item
- using `flag` package instead of `pflag`, which we use in all other applications and we have helpers for (configuring logger)
- `pflag` would allow to specify many filters and running tests matching ay of them, with `flag` setting only one filter is possible
- we must set `//go:build integration` to not collide wit regular unit tests
- no `--help` flag printing our custom flags
- we had to implement our own `-filter` flag because existing `-run` does not serve our needs
- logs produced by `go test` don't go through `zap` logger, so tests produce logs in two different formats now
- if integration test starts goroutines and would like to use `require.*` functions, it can't
- reading `-v` flag from CLI is a crap


And we accept all those disadvantages just because `go test` gives us one feature: tests are run in parallel automatically.
This thing is trivial to do ourselves (and BTW we already have it). I highly recommend to rethink this decision once more.
</blockquote></details>

discussed on the call
and all these points mentioned are not critical

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/140#-NA3YKnm5rDq-26lvNw5:-NAERDZICn-IAg14TXeq:b-fyixhc) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@dzmitryhil already proposed this. It might eventually be done, but first I need to switch to calling `go test` inside `crust` instead of imported go code directly
</blockquote></details>

@miladz68 absolutely makes sense for me
We can do this as another improvement step

___
___
*[`integration-tests/integration_test.go` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kUSR95C91nYJ1OBvG:-NAERVpz4xfZHeiyxLyq:bopjq2n) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

renaming package is not possible in this PR because crust uses it
</blockquote></details>

ok
lets pls do changes once integrated into crust
___
*[`integration-tests/integration_test.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/140#-N9kaa_R1GK6Q4CQAAr8:-NAERvsp37jmgWUfhS0K:bdbu8yu) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b3e3f3b7cc61e89e28cac404f0b95eaab1306ae/integration-tests/integration_test.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`logger.With` returns context, not logger. Returned context contains logger with additional fields. This context is then passed to test so whenever test logs something the field is there
</blockquote></details>

makes me confused all of the time
we need to rename it
ok for now here


<!-- Sent from Reviewable.io -->

2022-08-24 10:47 UTC, merged