Wasm module basic integration tests
CoreumFoundation/coreum pull request #148
Opened 2022-08-29 11:02 UTC by dzmitryhil

Add integration tests with the conjunction of the new deploy/execute/query client for the wasm module contracts. The client contains the extended functionality which is not fully used in the integration tests but covers most of the wasm options required for the client.

2022-08-29 11:12 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAdI-k37kRATafCPopv:-NAdI-k37kRATafCPopw:b-siwh80) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/simple_state.go#L29)):*
> ```Go
> 
> 	initTestState := func(ctx context.Context) error {
> 		// FIXME (wojtek): Temporary code for transition
> ```

The comment is here, since it was on the all tests at the time of the raising that PR


<!-- Sent from Reviewable.io -->

2022-08-30 07:50 UTC, wojtek-coreum requested changes
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 57 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRgnm8xK7Qk9zoboO:-NAhRgnm8xK7Qk9zoboP:b-qteeb9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L28)):*
> ```Go
> 	adminWallet := testing.RandomWallet()
> 	nativeDenom := chain.Network.TokenSymbol()
> 	nativeTokens := func(v string) string {
> ```

looks like the signature of this function should be sth like `func (v sdk.Int) sdk.Coin`. You could add it to `testing/helpers.go` because it might be reused by other tests too.
___
*[`integration-tests/wasm/bank_send.go` line 43 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhQtdR6BSrMefbolWP:-NAhQtdR6BSrMefbolWQ:b-shbofn) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L43)):*
> ```Go
> 
> 	runTestFunc := func(ctx context.Context, t testing.T) {
> 		expect := require.New(t)
> ```

`expect` -> `requireT`, this is a naming convention we agreed on some time ago.
___
*[`integration-tests/wasm/bank_send.go` line 56 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhSe3o5o2gDbk9siYo:-NAhSe3pB7JL_kX6mi45:brcw8yv) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L56)):*
> ```Go
> 				InstantiatePayload: `{"count": 0}`,
> 				// transfer some coins during instantiation, so we could withdraw them later using contract code.
> 				Amount: nativeTokens("10000"),
> ```

In this entire integration test two operations are tested:
- instantiation with initial balance
- withdrawing from smart contract

I miss another case: Funds are transferred to smart contract. The scenario could be like this:
- instantiate smart contract with balance of 10000 (done)
- verify balance of smart contract (done)
- transfer another 5000 to smart contract (to do)
- verify balance again (to do)
- withdraw 12000 (more than 10000) (to do)
- verify balances (done)
___
*[`integration-tests/wasm/bank_send.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRY-s0qvNfkgI-PWp:-NAhRY-s0qvNfkgI-PWq:b-l9yer0) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L68)):*
> ```Go
> 		expect.NotNil(contractBalance.Balance)
> 		expect.Equal(nativeDenom, contractBalance.Balance.Denom)
> 		expect.Equal("10000", contractBalance.Balance.Amount.String())
> ```

`contractBalance.Balance.Amount.Equal(...)`. Maybe you could even use methods of `sdk.Coin` to verify both denom and amount at the same time?
___
*[`integration-tests/wasm/bank_send.go` line 72 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhS5ty2MnW64P2fIru:-NAhS5ty2MnW64P2fIrv:b-249lr0) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L72)):*
> ```Go
> 		testWallet := testing.RandomWallet()
> 		withdrawMsg := fmt.Sprintf(
> 			`{"withdraw": { "amount":"5000", "denom":"%s", "recipient":"%s" }}`,
> ```

Here and in other places: I would prefer to have a `struct` defined for all those messages and then `json.Marshal` it. I would even say that fields like `ExecutePayload` and `InstantiatePayload` could accept an `interface{}` instead of `string` and marshal it internally inside `wasm` package.
___
*[`integration-tests/wasm/bank_send.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhUjTn42DUAgO8afpB:-NAhUjTn42DUAgO8afpC:b-h6tiar) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L110)):*
> ```Go
> 		expect.Equal("5000", testWalletBalance.Balance.Amount.String())
> 		// bank send invoked by the contract code succeeded! 〠
> 	}
> ```

Please verify that it's not possible to withdraw 5000 from smart contract now, because 5000+fees exceed the balance hold by the smart contract.
___
*[`integration-tests/wasm/bank_send.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXLhM3as4XUoUQM4p:-NAhXLhM3as4XUoUQM4q:b-6j0gxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L115)):*
> ```Go
> }
> 
> func fundDeployerAcc(chain testing.Chain, wallet types.Wallet) error {
> ```

instead of returning `error` you could pass `expect` (`requireT`) like you do in next function. Both ways are ok, but please choose one and be consistent.
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVDwg4-tVQ5cCNgmr:-NAhVDwg4-tVQ5cCNgms:b-tn7l4j) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
> ```Go
> 
> func fundDeployerAcc(chain testing.Chain, wallet types.Wallet) error {
> 	bv, ok := big.NewInt(0).SetString("1000000000000", 10)
> ```

`new(big.Int).SetString(...)`
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAhVmMe08rGfdB24JI2:bxi7fhd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
> ```Go
> 
> func fundDeployerAcc(chain testing.Chain, wallet types.Wallet) error {
> 	bv, ok := big.NewInt(0).SetString("1000000000000", 10)
> ```

Account used to fund testing wallets holds high but not infinite balance (that's why I preferred to fund accounts in genesis). So please use reasonable amount required by test. Your tests use amounts like 10000, so please adjust the amount here.
___
*[`integration-tests/wasm/bank_send.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXIfx2IqlMvgvl7oG:-NAhXIfx2IqlMvgvl7oH:b-obczms) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L132)):*
> ```Go
> 	config wasm.DeployConfig,
> 	contractData []byte,
> 	expect *require.Assertions,
> ```

expect -> requireT
___
*[`integration-tests/wasm/bank_send.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhWKW65Ska2K2vShCF:-NAhWKW65Ska2K2vShCG:b-oub0tx) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L137)):*
> ```Go
> 	expect.NoError(err)
> 
> 	_, err = wasmFile.Write(contractData)
> ```

I guess the algorithm is like this:
1. wasm contract is embedded (go:embed) in the binary as `[]byte`
2. wasm contract is saved to disk
3. during deployment, wasm contract is read from disk to `[]byte`
4. bytes are sent to API

Please remove points 2 and 3.
___
*[`integration-tests/wasm/simple_state.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhZ7eKBwiHR8vjzpRf:-NAhZ7eKBwiHR8vjzpRg:b-oblg6k) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/simple_state.go#L1)):*
> ```Go
> package wasm
> ```

Most of the comments I added in `bank_send.go` apply to this file as well.
___
*[`integration-tests/wasm/simple_state.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXpnr6l-JAiGeYgjk:-NAhXpnr6l-JAiGeYgjl:bfv5bi9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/simple_state.go#L52)):*
> ```Go
> 	 [...]

2022-08-30 12:00 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 19 of 27 files reviewed, 57 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRgnm8xK7Qk9zoboO:-NAiNM0r11-gxCSEHpqT:b1k906o) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

looks like the signature of this function should be sth like `func (v sdk.Int) sdk.Coin`. You could add it to `testing/helpers.go` because it might be reused by other tests too.
</blockquote></details>

Don't need it anymore, replaced with the type instead if string.
___
*[`integration-tests/wasm/bank_send.go` line 43 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhQtdR6BSrMefbolWP:-NAiNSr79o0_haizYQmK:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`expect` -> `requireT`, this is a naming convention we agreed on some time ago.
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/bank_send.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRY-s0qvNfkgI-PWp:-NAi2Dx5CqwcYEr2CXyX:bla64c0) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`contractBalance.Balance.Amount.Equal(...)`. Maybe you could even use methods of `sdk.Coin` to verify both denom and amount at the same time?
</blockquote></details>

Actually this check should be refactored anyway once we stop using our custom types and start using the SDK type. In that case we will be able to assert the sdk.Coins here instead. For now it's seems Ok to me.



_Code quote:_
```Go
contractBalance.Balance.Amount
```
___
*[`integration-tests/wasm/bank_send.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXLhM3as4XUoUQM4p:-NAiNedqDc-SDFDY78Y_:b31pacf) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L115)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

instead of returning `error` you could pass `expect` (`requireT`) like you do in next function. Both ways are ok, but please choose one and be consistent.
</blockquote></details>

Removed this function. Just added new type.NewCoinUnsafe function to reduce the redundant complexity. 



_Code quote:_
```Go
func fundDeployerAcc(chain testing.Chain, wallet types.Wallet) error {
```
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAiLnhO-0SxVwjno4ba:b-34te9q) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Account used to fund testing wallets holds high but not infinite balance (that's why I preferred to fund accounts in genesis). So please use reasonable amount required by test. Your tests use amounts like 10000, so please adjust the amount here.
</blockquote></details>

On my env it takes about "2057688000dacore" for each test. So I've update the value to "5000000000" to have enough some extra. 
BWT as for me the fauset account for the tests should be almost unlimited. 
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVDwg4-tVQ5cCNgmr:-NAiNuem4sMuinBkXz2Q:b-lw4htn) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`new(big.Int).SetString(...)`
</blockquote></details>

The code is removed.
___
*[`integration-tests/wasm/bank_send.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXIfx2IqlMvgvl7oG:-NAiNxUn7lBAfvQUWYeR:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

expect -> requireT
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/bank_send.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhWKW65Ska2K2vShCF:-NAiNz-H5WkfLblZaO18:bocn03l) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L137)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I guess the algorithm is like this:
1. wasm contract is embedded (go:embed) in the binary as `[]byte`
2. wasm contract is saved to disk
3. during deployment, wasm contract is read from disk to `[]byte`
4. bytes are sent to API

Please remove points 2 and 3.
</blockquote></details>

Do you mean to get it form the disk? 
That was my thought as well, but my guess was that the team accepted to it that was, so I decided to keep it. 
___
*[`integration-tests/wasm/contracts/.gitignore` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhPApE5_9NMsLEkPk6:-NAiOW5X5seUEuoaw7IA:b5wkpvd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/contracts/.gitignore#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we really need this file? Could artifacts of building contracts be created outside the repo? `/tmp` seems to be a very good place
</blockquote></details>

The docker image do it this way by default, the possible option is to refactor the wasm docker cli and images which I don't really want to do.



_Code quote:_
```ignore
checksums_intermediate.txt
```
___
*[`integration-tests/wasm/contracts/README.md` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhPfci-JDd_tE8vsIn:-NAiOiocCH0D-W9r-IEk:b-p619k2) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/contracts/README.md#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could we have a command like `crust build/smart-contracts` which does whatever is needed to rebuild them? We are software developers, not factory workers. We automate things instead of doing them manually.
</blockquote></details>

In general - yes it's possible. But we decided to postpone that wasm cli on the crust side, that's why I use the wasm docker image here now. 
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhJKcR9M4MiC8Wj6l-:-NAi3oq-8NcoWpaxN9tV:b-kotpgi) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/pkg/client/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

return error in this case so protocol must always be provided
</blockquote></details>

This will break the prev logic, since by default that variable for the tests is "localhost:26657" without the protocol.
I see that the prev protocol was "tcp://" current default is "http://", so what do want to use for default URL then, "http://localhost:26657"?
___
*[`pkg/client/client.go` [...]

2022-08-30 22:01 UTC, ysv requested changes
> Reviewed 15 of 27 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 20 of 27 files reviewed, 62 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`go.mod` line 3 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAiykIX185RCLZaGIsc:-NAiykIX185RCLZaGIsd:bpunxwb) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/go.mod#L3)):*
> ```XML
> module github.com/CoreumFoundation/coreum
> 
> go 1.18
> ```

is it really safe to update to 1.18 ?
I'm just wondering why we didn't do this before
Maybe cosmos 0.45 is not supposed to work with this version or any other issue
___
*[`go.mod` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAiz4X-C8RYZikX1CY2:-NAiz4X-C8RYZikX1CY3:bwg4q3a) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/go.mod#L6)):*
> ```XML
> 
> replace (
> 	github.com/99designs/keyring => github.com/cosmos/keyring v1.1.7-0.20210622111912-ef00f8ac3d76
> ```

do we really need keyring here ?
as far as I remeber we made the decision to not use it for now
___
*[`integration-tests/wasm/bank_send.go` line 56 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhSe3o5o2gDbk9siYo:-NAj2jry2Qem345cgnxM:b-qtnde3) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In this entire integration test two operations are tested:
- instantiation with initial balance
- withdrawing from smart contract

I miss another case: Funds are transferred to smart contract. The scenario could be like this:
- instantiate smart contract with balance of 10000 (done)
- verify balance of smart contract (done)
- transfer another 5000 to smart contract (to do)
- verify balance again (to do)
- withdraw 12000 (more than 10000) (to do)
- verify balances (done)

</blockquote></details>

very reasonable comment
Test becomes a bit big but
___
*[`integration-tests/wasm/bank_send.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRY-s0qvNfkgI-PWp:-NAkek5uBObDY_hhK8i1:bix6nde) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually this check should be refactored anyway once we stop using our custom types and start using the SDK type. In that case we will be able to assert the sdk.Coins here instead. For now it's seems Ok to me.
</blockquote></details>

I would say that we can live with it as a tmp solution to be changed once we remove this type
___
*[`integration-tests/wasm/bank_send.go` line 72 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhS5ty2MnW64P2fIru:-NAkf-o4DD5_uDYANh2o:b-pqov82) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L72)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and in other places: I would prefer to have a `struct` defined for all those messages and then `json.Marshal` it. I would even say that fields like `ExecutePayload` and `InstantiatePayload` could accept an `interface{}` instead of `string` and marshal it internally inside `wasm` package.
</blockquote></details>

makes sense
___
*[`integration-tests/wasm/bank_send.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXLhM3as4XUoUQM4p:-NAkfsZa7UhI5lPb54ro:b-31i1wd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L115)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Removed this function. Just added new type.NewCoinUnsafe function to reduce the redundant complexity. 
</blockquote></details>

I prefer to return error everywhere
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAkf_7I3cDYJzW2c97W:bv3277f) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

On my env it takes about "2057688000dacore" for each test. So I've update the value to "5000000000" to have enough some extra. 
BWT as for me the fauset account for the tests should be almost unlimited. 
</blockquote></details>

if you use dacore the amount is ok 
___
*[`integration-tests/wasm/bank_send.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhWKW65Ska2K2vShCF:-NAkg2D17DOVKMIqJB98:b809sfp) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L137)):*
> That was my thought as well, but my guess was that the team accepted to it that was, so I decided to keep it.

That is absolutely strange and needs to be redone properly
That is why this PR didn't end up in master because there were plenty of things like this which didn't make sense
___
*[`integration-tests/wasm/bank_send.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAj0MzP9yqjM2bsG81A:-NAj0MzP9yqjM2bsG81B:b-m2u3b0) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/integration-tests/wasm/bank_send.go#L19)):*
> ```Go
> 
> var (
> 	//go:embed contracts/bank-send/artifacts/bank_send.wasm
> ```

I think testdata folder is designed to store these type of files
I think it should be integration-tests/wasm/testdata or integration-tests/testdata etc
___
*[`integration-tests/wasm/bank_send.go` line 53 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAj1_Nu4ry7_N0ED3EC:-NAj1_Nu4ry7_N0ED3ED:b-99p213) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/integration-tests/wasm/bank_send.go#L53)):*
> ```Go
> 				Amount: types.NewCoinUnsafe(big.NewInt(10000), nativeDenom),
> 			},
> 		}, bankSendWASM, requireT)
> ```

I personally prefer to not pass requreT outside of test case itself because it makes function unnatural and test oriented. While if you refactor it to return errors as it is usually done it looks like usual go code

I prefer deployWasmContract to return error and then you can require error to be nil in test itself
```
func deployWasmContract(
	ctx context.Context,
	config wasm.DeployConfig,
	contractData []byte,
) *wasm.DeployOutput, error {
	wasmFile, err := os.CreateTemp("", "test_contract.wasm")
        // return error


	_, err = wasmFile.Write(contractData)
       // return error

	config.ArtefactPath = wasmFile.Name()
	deployOut, err := wasm.Deploy(ctx, config)
        // return error

	requireT.NoError(err)
        // check that txHash is not empty and return error
        // check that contractAddr is not empty and return error


	return deployOut
}
```
___
*[`integration-tests/wasm/contracts/README.md` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhPfci-JDd_tE8vsIn:-NAkiGWzCsaUvE0DyWAS:bg67mwd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/contracts/README.md#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In general - yes it's possible. But we decided to postpone that wasm cli on the crust side, that's why I use the wasm docker image here now. 
</blockquote></details>

yes we decided to do this as a next st [...]

2022-08-31 08:59 UTC, wojtek-coreum requested changes
> Reviewed 1 of 5 files at r2, 4 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 49 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn6yYK4j7IXSYyAB8z:-NAn6yYK4j7IXSYyAB9-:b-skutqx) (no related file):*
I love how many lines of code were removed from the original code so far

___
___
*[`integration-tests/wasm/bank_send.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRY-s0qvNfkgI-PWp:-NAmyy7y4LcEI0mIlXpF:b-q34ov1) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L68)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would say that we can live with it as a tmp solution to be changed once we remove this type
</blockquote></details>

But you use native bank client of cosmos sdk, so you already get `sdk.Coin` type here
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAmzuP1DbXiQQPMqHOg:b618di1) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
> for me the fauset account for the tests should be almost unlimited

It's not possible. That's why previous version of testing framework funded accounts through genesis.json, so every test could get as much as it likes without limits.
___
*[`integration-tests/wasm/bank_send.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXIfx2IqlMvgvl7oG:-NAn-A1lDy81LBYGO6IS:bfxzrk9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L132)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

After reading @ysv 's comment I also think that it's better tor eturn error here and use `requireT` outside, as it is a more goish way
___
*[`integration-tests/wasm/bank_send.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhWKW65Ska2K2vShCF:-NAn1YXnCkMHKZBkWRUi:b-jy342) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L137)):*
> Do you mean to get it form the disk?

I meant getting it from `go:embed`-ed variable like you did
___
*[`integration-tests/wasm/bank_send.go` line 47 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAmzK9o78Zk2gFPpYcG:-NAmzK9o78Zk2gFPpYcH:bybm3hl) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L47)):*
> ```Go
> 		}
> 
> 		initialPayload, err := json.Marshal(bankInstantiatePayload{
> ```

marshaling could be implemented inside `deployWasmContract` and accepting `InstantiatePayload interface{}`. Then it is done once for all.
___
*[`integration-tests/wasm/bank_send.go` line 117 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn0e-_4fxvgk65Kapu:-NAn0e-_4fxvgk65Kapv:b-i9sh7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L117)):*
> ```Go
> }
> 
> func deployWasmContract(
> ```

Minor: the body of this function is so trivial now that IMO the included logic could be used directly in appropriate places
___
*[`integration-tests/wasm/bank_send.go` line 123 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn0LY2EEtTymLpepFC:-NAn0LY2EEtTymLpepFD:b9dnjnq) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L123)):*
> ```Go
> 	requireT *require.Assertions,
> ) *wasm.DeployOutput {
> 	config.Contract = contractData
> ```

This should be done outside of this function.
Now you pass both `config` and `contractData` as arguments to this function instead of setting `config.Contract` outside and pass only `config`.
___
*[`integration-tests/wasm/simple_state.go` line 21 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn16512Agf9Wa0jZte:-NAn16512Agf9Wa0jZtf:bx19chr) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/simple_state.go#L21)):*
> ```Go
> )
> 
> type simpleTateInstantiatePayload struct {
> ```

Tate -> State
___
*[`integration-tests/wasm/simple_state.go` line 65 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn1p-07XD-Ds2A_4W9:-NAn1p-07XD-Ds2A_4WA:bfgsle9) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/simple_state.go#L65)):*
> ```Go
> 		queryOut, err := wasm.Query(ctx, deployOut.ContractAddr, wasm.QueryConfig{
> 			Network:      networkConfig,
> 			QueryPayload: `{"get_count": {}}`,
> ```

use struct here too
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhJKcR9M4MiC8Wj6l-:-NAn2-r-4TUd5WDnRMZ7:bev50lz) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/pkg/client/client.go#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This will break the prev logic, since by default that variable for the tests is "localhost:26657" without the protocol.
I see that the prev protocol was "tcp://" current default is "http://", so what do want to use for default URL then, "http://localhost:26657"?
</blockquote></details>

Yes, we need to update existing places. Both "tcp" and "http" work for our current setup so we may use any of them, I don't have preference.
___
*[`pkg/client/client.go` line 141 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhJXeyETeZH_UBp8tO:-NAn2QhFBVXXtdcarMRW:bt05auq) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/pkg/client/client.go#L141)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes those logs/events as the logs by which we get the deployed contract address.
https://github.com/CoreumFoundation/coreum/blob/feat/wasm-module-basic-integration-tests/pkg/wasm/deploy.go#L406

Those events are produced by the wasm.keeper.
https://github.com/CosmWasm/wasmd/blob/main/x/wasm/keeper/keeper.go#L201
</blockquote></details>

So could we process those logs internally and return only contract address then?
___
*[`pkg/types/types.go` line 60 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAkk-XPELtlGGoK7Dhm:-NAmwn4DAni49HroP4lP:blwunk7) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/pkg/types/types.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`MustNewCoin`
</blockquote></details>

Some time ago when I introduced similar thing, @ysv and @miladz68 argued that error should be returned from test instead of panicking. I have nothing against @dzmitryhil 's proposal because it makes life easier and IMO panicking in this case inside test is ok. Just asking if other guys changed their minds eventually.

If it's ok now, then I would recommend to do it the `go test`-way:

```go
func MustNewCoin(t *testing.T, amount *big.Int, denom string) Coin {
    c, err := NewCoin(amount, denom)
    require.NoError(t, err)
    return c
}
```

and this function should be defined only inside `integration-tests/testing` because regular code should not use it and handle error instead.

Anyway `MustNewCoin` is a better name.
___
*[`pkg/wasm/deploy.go` line 34 at r1] [...]

2022-08-31 09:21 UTC, ysv requested changes
> Reviewed 4 of 27 files at r1, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 50 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhWKW65Ska2K2vShCF:-NAnARtn1XiYpYIh0ZBJ:b-4v0d3v) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L137)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> Do you mean to get it form the disk?

I meant getting it from `go:embed`-ed variable like you did
</blockquote></details>

Wojtek probably means that you should use embeded `[]byte` directly to instantiate contract instead of writing it to tmp file and reading from it
___
*[`integration-tests/wasm/bank_send.go` line 47 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAmzK9o78Zk2gFPpYcG:-NAn9CXzEY3hdGcuwep8:bqi41dk) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

marshaling could be implemented inside `deployWasmContract` and accepting `InstantiatePayload interface{}`. Then it is done once for all.
</blockquote></details>

another option is to use `map[string]interface{}` thats is how we can represent any JSON needed here and avoid defining dummy structs

If you still prefer to use struct I suggest to define them inline since they are used only once
```golang
a := struct{ foo string }{foo: "bar"}
```
___
*[`integration-tests/wasm/bank_send.go` line 111 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnA1Nj-0SFyPeX2mTS:-NAnA1Nj-0SFyPeX2mTT:b-p1gqax) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L111)):*
> ```Go
> 		requireT.Equal(nativeDenom, testWalletBalance.Balance.Denom)
> 		requireT.Equal("5000", testWalletBalance.Balance.Amount.String())
> 		// bank send invoked by the contract code succeeded! 〠
> ```

what is it ? ` 〠`



_Code quote:_
```Go
 〠
```
___
*[`integration-tests/wasm/bank_send.go` line 123 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn0LY2EEtTymLpepFC:-NAnAhh1AuiXDmyFkLjq:b3kqu) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L123)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This should be done outside of this function.
Now you pass both `config` and `contractData` as arguments to this function instead of setting `config.Contract` outside and pass only `config`.
</blockquote></details>

+
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhJKcR9M4MiC8Wj6l-:-NAnBvcj38tBYk9sdb0Q:b-1kpqge) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/pkg/client/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, we need to update existing places. Both "tcp" and "http" work for our current setup so we may use any of them, I don't have preference.
</blockquote></details>

is it used only in coreum repo or crust also ?
because if it is about creating additional PR to crust I prefer to keep signature of New as it is now to avoid extra changes since we are going to drop it soon


<!-- Sent from Reviewable.io -->

2022-08-31 09:55 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 51 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 35 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnJxM77uHMdm_B35k2:-NAnJxM77uHMdm_B35k3:b1ioofm) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L35)):*
> ```Go
> 		// FIXME (wojtek): Temporary code for transition
> 		if chain.Fund != nil {
> 			chain.Fund(adminWallet, types.NewCoinUnsafe(big.NewInt(5000000000), chain.Network.TokenSymbol()))
> ```

funding should be done in a way that whenever parameters of the fee (`chain.NetworkConfig.Fee`) change, balances are calculated appropriately so fees and operations made by the test are covered. Take a look how `testing.ComputeNeededBalance` is used in other tests to serve this purpose


<!-- Sent from Reviewable.io -->

2022-08-31 09:58 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 51 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 47 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAmzK9o78Zk2gFPpYcG:-NAnK7qQ9zBkrbEFroJn:bt59dla) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

another option is to use `map[string]interface{}` thats is how we can represent any JSON needed here and avoid defining dummy structs

If you still prefer to use struct I suggest to define them inline since they are used only once
```golang
a := struct{ foo string }{foo: "bar"}
```
</blockquote></details>

I prefer inline structs over maps
___
*[`pkg/client/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhJKcR9M4MiC8Wj6l-:-NAnKMol6dXlsJlCpO-v:btmdell) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/pkg/client/client.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it used only in coreum repo or crust also ?
because if it is about creating additional PR to crust I prefer to keep signature of New as it is now to avoid extra changes since we are going to drop it soon
</blockquote></details>

It is used in some places in crust, and also in faucet


<!-- Sent from Reviewable.io -->

2022-08-31 10:26 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 51 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/types/types.go` line 60 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAkk-XPELtlGGoK7Dhm:-NAnR32l5ZO7MbU659aU:b-pc6bg4) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/pkg/types/types.go#L60)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Some time ago when I introduced similar thing, @ysv and @miladz68 argued that error should be returned from test instead of panicking. I have nothing against @dzmitryhil 's proposal because it makes life easier and IMO panicking in this case inside test is ok. Just asking if other guys changed their minds eventually.

If it's ok now, then I would recommend to do it the `go test`-way:

```go
func MustNewCoin(t *testing.T, amount *big.Int, denom string) Coin {
    c, err := NewCoin(amount, denom)
    require.NoError(t, err)
    return c
}
```

and this function should be defined only inside `integration-tests/testing` because regular code should not use it and handle error instead.

Anyway `MustNewCoin` is a better name.
</blockquote></details>

Because Roman created yet another wrapper for the same thing in his PR, let's do it once for all: https://reviewable.io/reviews/CoreumFoundation/coreum/152



_Code quote:_
```Go
// NewCoinUnsafe returns a new instance of coin type and panics in case of the validation error.
func NewCoinUnsafe(amount *big.Int, denom string) Coin {
	c, err := NewCoin(amount, denom)
	if err != nil {
		panic(errors.Wrap(err, "invalid new coin"))
	}

	return c
}
```


<!-- Sent from Reviewable.io -->

2022-08-31 12:02 UTC, wojtek-coreum requested changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 31 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn6yYK4j7IXSYyAB8z:-NAnhxyR64-z9UrLjdR_:b-1qe0ab) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I love how many lines of code were removed from the original code so far
</blockquote></details>

After removing another  bunch of files I love this PR even more

___
___
*[`integration-tests/index.go` line 17 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAndyAf68RoPtmXCfl8:-NAndyAf68RoPtmXCfl9:b-95n679) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/index.go#L17)):*
> ```Go
> 			auth.TestTooLowGasPrice,
> 			auth.TestNoFee,
> 			// FIXME (wojtek): This test might be enabled once crust imports new version of coreum containing feemodel
> ```

This comment does not exist in `master` anymore
___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAngt7A77EvlyVDcSzq:-NAngt7A77EvlyVDcSzr:b-8p5mnz) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
> ```Go
> package wasm
> ```

Non-blocking: just an item to discuss

@miladz68 @ysv 
In the past, after a discussion, team decided that we don't want to have a central `client` package where all the helpers for creating messages go. The main argument was that it's a huge effort to write those helpers. At that time I argued that this code (helpers) will be written anyway, they just be spread across entire codebase and eventually we will have many copies of them. This file is a perfect example of what I was talking about.
___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAniKkZ-Fny-reAvXCx:-NAniKkZ-Fny-reAvXCy:b-hsu37e) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
> ```Go
> package wasm
> ```

@ysv @miladz68  This file is named `client.go` and struct contains "Client", I remember the discussion where we decided to not call anything "client" to avoid creating false notion in the community that we provide any reusable client package. I know it's inside testing so I'm not blocking on this but maybe it should be renamed.

We also decided to replace client with a set of helpers, and here yet another client structure is created, which is probably related to my previous comment above. So we want to avoid creating a central client,  but at the same time we create smaller clients everywhere and distribute logic around them. Probably we should discuss it in a meeting.
___
*[`integration-tests/wasm/client.go` line 23 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjkiXBwW9iM0L3Uc0:-NAnjkiXBwW9iM0L3Uc1:b-l5sza7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L23)):*
> ```Go
> }
> 
> func newWasmTestClient(baseInput tx.BaseInput, coredClient client.Client) *testClient {
> ```

`coredClient`: so now we start wrapping one client in another. It goes in bad direction IMO.
___
*[`integration-tests/wasm/client.go` line 41 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjFho73YFVVs0-iuM:-NAnjFho73YFVVs0-iuN:b-y1j74i) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L41)):*
> ```Go
> 
> // deploys the wasm contract and returns its codeID.
> func (c *testClient) deploy(ctx context.Context, wasmData []byte) (uint64, error) {
> ```

here and below: it's more readable if methods being a public interface of the struct are exported even if they are used only in the scope of the same package because it clearly indicates which method are called by the "users" of the struct and which are there for internal use only.
___
*[`integration-tests/wasm/client.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjwfs5NANjosFOx0y:-NAnjwfs5NANjosFOx0z:b-ajh6cz) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L47)):*
> ```Go
> 	}
> 
> 	res, err := c.coredClient.SubmitMessage(ctx, c.baseInput, msgStoreCode, client.WithGasMultiplier(c.gasMultiplier))
> ```

`SubmitMessage` should be an internal method of this struct or function in this package
___
*[`integration-tests/wasm/client.go` line 52 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnk0Mx9QhWW2rAUssu:-NAnk0Mx9QhWW2rAUssv:bmz1c5n) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L52)):*
> ```Go
> 	}
> 
> 	ok, codeIDStr := client.FindEventAttribute(res.EventLogs, wasmtypes.EventTypeStoreCode, wasmtypes.AttributeKeyCodeID)
> ```

`FindEventAttribute` should be an internal method of this struct or function in this package
___
*[`integration-tests/wasm/simple_state.go` line 99 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnlAR93u7FJm9LQ81n:-NAnlAR93u7FJm9LQ81o:bsjfcg7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/simple_state.go#L99)):*
> ```Go
> 
> func methodToEmptyBodyPayload(methodName simpleStateMethod) json.RawMessage {
> 	return json.RawMessage(fmt.Sprintf(`{"%s": {}}`, methodName))
> ```

Minor (I don't care much): `return map[string]struct{}{methodName: struct{}{}}`
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NAnf8SM82qnyzJMZC5o:b8c3iax) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
> ```Go
> }
> 
> // submitModifier is the customisation option for the SubmitMessage.
> ```

We could organize a competition on how much code must be written to multiply two numbers :-).
I think we should explicitly forbid to add new code to the `client` package and freeze it until @miladz68 finishes refactoring.

IMO `testWasmClient` is a better place for adding margin to gas limit
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnfry46Ir4bj6onFJr:-NAnfry46Ir4bj6onFJs:b-2zy99m) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385)):*
> ```Go
> 
> // FindEventAttribute finds the first event attribute by type and attribute name.
> func FindEventAttribute(event sdk.StringEvents, etype, attribute string) (bool, string) {
> ```

please keep it consistent and make the `bool` returned value the last one
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAng4bb-10PZJTMWGe4:-NAng4bb-10PZJTMWGe5:b-fnpsvj) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385)):*
> ```Go
> 
> // FindEventAttribute finds the first event attribute by type and attribute name.
> func FindEventAttribute(event sdk.StringEvents, etype, attribute string) (bool, string) {
> ```

Minor: Personally I would merge those two functions, but I'm not blocking here.
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAni60xAVaGkV_nm5RW:-NAni60xAVaGkV_nm5RX:b-p8ibl) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385 [...]

2022-08-31 12:37 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 5 of 29 files reviewed, 31 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn6yYK4j7IXSYyAB8z:-NAnearB2clqKlfeRdCS:b2nh4j5) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After removing another  bunch of files I love this PR even more
</blockquote></details>

:-)

___
___
*[`go.mod` line 3 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAiykIX185RCLZaGIsc:-NAnewrn8puRr2iCYYdT:b-6l7ybh) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/go.mod#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it really safe to update to 1.18 ?
I'm just wondering why we didn't do this before
Maybe cosmos 0.45 is not supposed to work with this version or any other issue
</blockquote></details>

Actually, I don't see a problem with the go, since it's backyard compatible with the previous versions. But if you prepare different to in in the separate PR, I'm ok. 
___
*[`go.mod` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAiz4X-C8RYZikX1CY2:-NAngUpiCiGGeEQjCWfY:b326nmo) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/go.mod#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need keyring here ?
as far as I remeber we made the decision to not use it for now
</blockquote></details>

This replace was taken from the lygacy PR, removed it now.



_Code quote:_
```XML
github.com/99designs/keyring
```
___
*[`integration-tests/index.go` line 17 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAndyAf68RoPtmXCfl8:-NAnpWY96X_CedF2ddkj:b9yk3yc) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/index.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This comment does not exist in `master` anymore
</blockquote></details>

Updated mater and removed the comment.



_Code quote:_
```Go
	// FIXME (wojtek): This test might be enabled once crust imports ne
```
___
*[`integration-tests/wasm/bank_send.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhRY-s0qvNfkgI-PWp:-NAnjV_jCfjwQP4N6gZt:bvditjx) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But you use native bank client of cosmos sdk, so you already get `sdk.Coin` type here
</blockquote></details>

Undestood your point now. Updated. (I uses Coin.String() assertions now because it's easy ot see the mismatch in case of the failure). 



_Code quote:_
```Go
contractBalance.Balance.Amount
```
___
*[`integration-tests/wasm/bank_send.go` line 72 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhS5ty2MnW64P2fIru:-NAnjpxr-cuhTu89N6pS:b5bf82j) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L72)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

makes sense
</blockquote></details>

Reworked. But I decided to use json.Raw message as an input, so the client (I'm py case test) converts it. I personally prepare to avoid the interface{} type as much as possible.
___
*[`integration-tests/wasm/bank_send.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhUjTn42DUAgO8afpB:-NAnkIPH6llw1tMG2bPH:btzbetr) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L110)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please verify that it's not possible to withdraw 5000 from smart contract now, because 5000+fees exceed the balance hold by the smart contract.
</blockquote></details>

Sure, will update as a part for the test-case improvement you requested 
___
*[`integration-tests/wasm/bank_send.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXLhM3as4XUoUQM4p:-NAnkos47YLsaqi6P0qX:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I prefer to return error everywhere
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAnkQAH-5wduIOYCJ_r:baauux6) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> for me the fauset account for the tests should be almost unlimited

It's not possible. That's why previous version of testing framework funded accounts through genesis.json, so every test could get as much as it likes without limits.
</blockquote></details>

I didn't get why it's impossible. But it's not related to that thread I guess.
___
*[`integration-tests/wasm/bank_send.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXIfx2IqlMvgvl7oG:-NAnkjhRDOBvULwZHcb_:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After reading @ysv 's comment I also think that it's better tor eturn error here and use `requireT` outside, as it is a more goish way
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/bank_send.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhWKW65Ska2K2vShCF:-NAnk_Zw7qR3FDN0yPlQ:b-dgu8il) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L137)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Wojtek probably means that you should use embeded `[]byte` directly to instantiate contract instead of writing it to tmp file and reading from it
</blockquote></details>

Refactored. Now I use the []byte directly.
___
*[`integration-tests/wasm/bank_send.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAj0MzP9yqjM2bsG81A:-NAngne_CKzgCarTU240:b-g4hkaa) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/integration-tests/wasm/bank_send.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think testdata folder is designed to store these type of files
I think it should be integration-tests/wasm/testdata or integration-tests/testdata etc

</blockquote></details>

I'm ok to go with that name as a convention. Updated.
___
*[`integration-tests/wasm/bank_send.go` line 53 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAj1_Nu4ry7_N0ED3EC:-NAnizcj6_-mvZRwnfvn:b-qj4lsq) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/integration-tests/wasm/bank_send.go#L53)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I personally prefer to not pass requreT outside of test case itself because it makes function unnatural and test oriented. While if you refactor it to r [...]

2022-08-31 13:03 UTC, wojtek-coreum requested changes
> Reviewed 24 of 24 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 20 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAnw4ZT0RADl4m-9MJq:b66uqr9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get why it's impossible. But it's not related to that thread I guess.
</blockquote></details>

Because it's impossible to have an account holding infinite balance :-)
___
*[`integration-tests/wasm/bank_send.go` line 35 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnJxM77uHMdm_B35k2:-NAnvBzwC07J2JxUbmE8:bo2kpbr) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L35)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I've review it, but this function doesn't feat my use case, the contract deployment require much more gas then bankSend or any simple transaction. There is even a gasMultiplier param to add more gas that Estimation returns. That's why it set here for that value. 
Also it seems useless to use that funf for all use-cases.
</blockquote></details>

yea, I see now that wasm is a specific use case
___
*[`integration-tests/wasm/client.go` line 41 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjFho73YFVVs0-iuM:-NAnwjtLE8BS7INr74aq:b-p9e45o) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure about that. Initialy I had the exported methods but then refactored to unexported, both options are correct as for me, but I would keep them unxported now.
</blockquote></details>

@ysv @miladz68 WDYT? For me it's quite obvious that `struct` exports methods which might serve the logic for the user and methods which serve internal needs are unexported. Same for types like `instantiateConfig`.
___
*[`integration-tests/wasm/client.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjwfs5NANjosFOx0y:-NAnwX3t4SMXdbeFnB_h:bb0h564) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It might be a great candidate to be used by other tests
</blockquote></details>

@miladz68 is working on new logic of the client helpers so I would prefer to stop extending that code until it is done
___
*[`integration-tests/wasm/simple_state.go` line 21 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAn16512Agf9Wa0jZte:-NAnxeYzD-1L_tf6wGAu:b-usa96o) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/simple_state.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't see what I need to update.
</blockquote></details>

you already fixed it in previous commit
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NAnyYRr0UFdoqvMYfP-:b-yjnxsv) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> place
Not sure about that. As for me the this actually the useful option, which seems to be reused amd extended. I would prepare to keep it in the v2 client as well.
</blockquote></details>

@ysv @miladz68 WDYT?
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnfry46Ir4bj6onFJr:-NAnyfNsAvGBgtB8cNSp:b21sdl9) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, But vice vice versa - bool first. Updated.
</blockquote></details>

actually all the functions in go sdk and other libs return bool as the last argument. Compare:

```go
v, ok := something.(someInterface)

v, exists := someMap[someKey]
```
___
*[`pkg/client/client.go` line 46 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnyMV0B5JuZg3QpuzE:-NAnyMV0B5JuZg3QpuzF:b-6erjxe) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/pkg/client/client.go#L46)):*
> ```Go
> 		strings.HasPrefix(addr, "https://"):
> 	default:
> 		panic(errors.Errorf("the protocol is required for the address:%s", addr))
> ```

error should be returned instead


<!-- Sent from Reviewable.io -->

2022-08-31 13:29 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 27 of 29 files reviewed, 19 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 56 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhSe3o5o2gDbk9siYo:-NAo312x7bIKxefsftVv:b-26gjuq) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L56)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

very reasonable comment
Test becomes a bit big but
</blockquote></details>

Updated not in the exect way @wojtek-coreum mentioed but it covers all it logicaly
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAo3FxK-LfUN54Vw8cT:bcklk6d) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because it's impossible to have an account holding infinite balance :-)
</blockquote></details>

At least Max we can get :-)
___
*[`integration-tests/wasm/client.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjwfs5NANjosFOx0y:-NAo3QLS0AscgjCPz89i:b-fwh8re) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 is working on new logic of the client helpers so I would prefer to stop extending that code until it is done
</blockquote></details>

Yes and no at the same time. We need it in the new client as well, also I started the PR beofer means I had to work with what I had :-) 
I understands that it's a conflict, but don't see the different right way. 
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnfry46Ir4bj6onFJr:-NAo3zFq5f_NxwPABcQ7:bdw6w4b) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

actually all the functions in go sdk and other libs return bool as the last argument. Compare:

```go
v, ok := something.(someInterface)

v, exists := someMap[someKey]
```
</blockquote></details>

My bad. Updated.
___
*[`pkg/client/client.go` line 46 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnyMV0B5JuZg3QpuzE:-NAo3kq263Nfh6vBJHve:bbsnf7i) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/pkg/client/client.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

error should be returned instead
</blockquote></details>

Why do you use the must.OK in the next lines then?


<!-- Sent from Reviewable.io -->

2022-08-31 13:44 UTC, wojtek-coreum requested changes
> Reviewed 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 20 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAo6bcq0DVlyP1Q0GFt:btmizf7) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

At least Max we can get :-)
</blockquote></details>

initially it was like this (really tremendous number), but @ysv was against assigning unrealistic values
___
*[`integration-tests/wasm/bank_send.go` line 99 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5kd26r7Cgu1q3GBQ:-NAo5kd26r7Cgu1q3GBR:bejyecm) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L99)):*
> ```Go
> 	requireT.Equal(sdk.NewInt64Coin(nativeDenom, 15000).String(), contractBalance.Balance.String())
> 
> 	testWallet := testing.RandomWallet()
> ```

please add a comment describing this step
___
*[`integration-tests/wasm/bank_send.go` line 111 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5rZ-EJg5DWFu2B0z:-NAo5rZ-EJg5DWFu2B1-:b-s1rs65) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L111)):*
> half of the coins

it's no longer a half
___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NAo5xSQ8ldm29j7xzwn:b-u0aaoa) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
> has another half

it's no longer a half
___
*[`integration-tests/wasm/bank_send.go` line 141 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo6LZ788yuL2mo1U67:-NAo6LZ788yuL2mo1U68:bymtr7w) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L141)):*
> ```Go
> 	requireT.NoError(err)
> 	err = wasmTestClient.execute(ctx, contractAddr, withdrawPayload, types.Coin{})
> 	requireT.Error(err)
> ```

Could you paste here (in discussion) an example error given by this?
___
*[`pkg/client/client.go` line 46 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnyMV0B5JuZg3QpuzE:-NAo6sEc5_M6RON_ZoAv:b3o2i7z) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/pkg/client/client.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you use the must.OK in the next lines then?
</blockquote></details>

Because that code comes from the time of my dictatorship, before team decided that code should not panic (as a rule of thumb). But this code is going to be refactored anyway, so I don't care much. Changing to non-blocking.
___
*[`pkg/client/client.go` line 243 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo7GkIAZQiT9zjouok:-NAo7GkIAZQiT9zjouol:bmxf4vk) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/pkg/client/client.go#L243)):*
> ```Go
> 	}
> 
> 	if input.GasLimit == 0 {
> ```

no no no, it might cause that someone's balance will go to hell after sending huge tx with gas limit not set accidentally. I know that **so far*** we use this code only for testing but let's not create traps like this.


<!-- Sent from Reviewable.io -->

2022-08-31 13:50 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 21 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 130 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo9Fhc1nOg0631fluD:-NAo9Fhc1nOg0631fluE:b-r2vkcs) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cd86c061b022283e861fd93061963328363caaa/integration-tests/wasm/bank_send.go#L130)):*
> ```Go
> 	requireT.Equal(sdk.NewInt64Coin(nativeDenom, 5000).String(), testWalletBalance.Balance.String())
> 
> 	// try to exceed the contract limit
> ```

Please move this test to be the first one. Otherwise the transfer may fail e.g. because testing account goes out of funds (and tx fee is not covered) which might eventually hide the real issue (that transfer succeeds).


<!-- Sent from Reviewable.io -->

2022-08-31 14:41 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 21 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 99 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5kd26r7Cgu1q3GBQ:-NAoBQdI9BQV_tJF2JT3:b-rt2dlr) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please add a comment describing this step
</blockquote></details>

I would prefate to remove all comments. But will keep it just to support the reviewers. :-)
Updated.
___
*[`integration-tests/wasm/bank_send.go` line 111 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5rZ-EJg5DWFu2B0z:-NAoBXdfAN4Y3rjwnMRt:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> half of the coins

it's no longer a half
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NAoIWjj5Bc77WkTsSWw:b-4cljc0) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> has another half

it's no longer a half
</blockquote></details>

Remvoed. Comments are for the actions only.



_Code quote:_
```Go
testWalletBalance, err := chain.Client.BankQ
```
___
*[`integration-tests/wasm/bank_send.go` line 141 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo6LZ788yuL2mo1U67:-NAoIyviCYqNCxjLVLQ-:bxn3d0g) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L141)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you paste here (in discussion) an example error given by this?
</blockquote></details>

```
failed to execute message; message index: 0: dispatch: submessages: 15000dacore is smaller than 16000dacore: insufficient funds: invalid request
```
Same as bank send error.
___
*[`integration-tests/wasm/bank_send.go` line 130 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo9Fhc1nOg0631fluD:-NAoIsvS8N9B7kMwvdC7:bd6w5y) ([raw file](https://github.com/coreumfoundation/coreum/blob/8cd86c061b022283e861fd93061963328363caaa/integration-tests/wasm/bank_send.go#L130)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please move this test to be the first one. Otherwise the transfer may fail e.g. because testing account goes out of funds (and tx fee is not covered) which might eventually hide the real issue (that transfer succeeds).
</blockquote></details>

Make sence. Updated.
___
*[`pkg/client/client.go` line 46 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnyMV0B5JuZg3QpuzE:-NAoJdL-E25RfAUyyVj5:b64z7bd) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/pkg/client/client.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because that code comes from the time of my dictatorship, before team decided that code should not panic (as a rule of thumb). But this code is going to be refactored anyway, so I don't care much. Changing to non-blocking.
</blockquote></details>

So now I follow the current practice. So panic is OK. 
___
*[`pkg/client/client.go` line 243 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo7GkIAZQiT9zjouok:-NAoJpyfCbxtp4KYbqmM:blmard6) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/pkg/client/client.go#L243)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

no no no, it might cause that someone's balance will go to hell after sending huge tx with gas limit not set accidentally. I know that **so far*** we use this code only for testing but let's not create traps like this.
</blockquote></details>

Ok, updated with the new option.


<!-- Sent from Reviewable.io -->

2022-09-01 14:02 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 25 of 29 files reviewed, 16 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 3 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAiykIX185RCLZaGIsc:-NAsxA6k9Ao9alfg3n9N:b-1j6bex) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/go.mod#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, I don't see a problem with the go, since it's backyard compatible with the previous versions. But if you prepare different to in in the separate PR, I'm ok. 
</blockquote></details>

ok for me I think
would be better to do in a separate PR but not critical
___
*[`go.mod` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAiz4X-C8RYZikX1CY2:-NAsxKI6CKdJmm03h0Dl:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/go.mod#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This replace was taken from the lygacy PR, removed it now.
</blockquote></details>

ok
___
*[`integration-tests/wasm/bank_send.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhVmMe08rGfdB24JI1:-NAt2wGSAisS4gWuxnBm:b-b34zju) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

initially it was like this (really tremendous number), but @ysv was against assigning unrealistic values
</blockquote></details>

lets fix it once we face this problem.
I still believe that total supply should be enough for all cases
___
*[`integration-tests/wasm/bank_send.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhXIfx2IqlMvgvl7oG:-NAt3GaS42wwfuPM11fP:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L132)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

ok
___
*[`integration-tests/wasm/bank_send.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAj0MzP9yqjM2bsG81A:-NAsxNRZC_ATgcPD33bY:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa67061594f4b25f722a47b5a143f6ba68fba69e/integration-tests/wasm/bank_send.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I'm ok to go with that name as a convention. Updated.
</blockquote></details>

ok
___
*[`integration-tests/wasm/bank_send.go` line 47 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAmzK9o78Zk2gFPpYcG:-NAsxsC79FSMMw9JSnke:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Reworked.
</blockquote></details>

ok
___
*[`integration-tests/wasm/bank_send.go` line 111 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnA1Nj-0SFyPeX2mTS:-NAt2dzX0D_ubB5rCmwF:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/c42642ed0415ede2885f930d3eeedd89e22de6a4/integration-tests/wasm/bank_send.go#L111)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> Reworked. But I decided to use json.Raw message as an input, so the client (I'm py case test) converts it. I personally prepare to avoid the interface{} type as much as possible.
Removed. That was a pretty sympol, from the prev PR :-)
</blockquote></details>

ok
___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAngt7A77EvlyVDcSzq:-NAt3tRMCdQU91c4N7h1:be2cd6s) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: just an item to discuss

@miladz68 @ysv 
In the past, after a discussion, team decided that we don't want to have a central `client` package where all the helpers for creating messages go. The main argument was that it's a huge effort to write those helpers. At that time I argued that this code (helpers) will be written anyway, they just be spread across entire codebase and eventually we will have many copies of them. This file is a perfect example of what I was talking about.
</blockquote></details>

yes but this file still provides limited functionality so we should extend it each time or provide access to original client directly which will causes mix

Lets keep this code here for now. 
If we start to like it at some point we will move expose it to the world but not now
___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAniKkZ-Fny-reAvXCx:-NAt4mDL-VCxeCkaLrQ0:b53d70w) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv @miladz68  This file is named `client.go` and struct contains "Client", I remember the discussion where we decided to not call anything "client" to avoid creating false notion in the community that we provide any reusable client package. I know it's inside testing so I'm not blocking on this but maybe it should be renamed.

We also decided to replace client with a set of helpers, and here yet another client structure is created, which is probably related to my previous comment above. So we want to avoid creating a central client,  but at the same time we create smaller clients everywhere and distribute logic around them. Probably we should discuss it in a meeting.
</blockquote></details>

I disagree to call this client at least in the format we have right now. I don't like that it receives baseInput on initialization which should be arg of function

we can:
1. restruct it a bit to be wrapper around WASMclient with reusable functionality and some fancy name
2. keep it as a set of helper funcs

I would probably do smth like this:
```golang
type wasmTestClient struct {
  client.Client
}

func (c *wasmTestClient) deploy(ctx context.Context, baseInput BaseInput, wasmData []byte) (uint64, error) {
 // ...
}

// ...
func (c *wasmTestClient) query(ctx context.Context, contractAddr string, payload json.RawMessage) (json.RawMessage, error) {
// ...
}
```
Then it looks and feels like just extending existing client

Naming is subject for changes in this exmpl
___
*[`integration-tests/wasm/client.go` line 23 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjkiXBwW9iM0L3Uc0:-NAt7jF79lpw9HTfVCOq:b-w2ufq0) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But that the client for the tests only. To reduce the code lines. I don't want to share it with anyone.
</blockquote></details>

see previous comment
___
*[`integration-tests/wasm/client.go` line 41 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjFho73YFVVs0-iuM:-NAt9zwl4u8UIhttgRIg:bqouqbk) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv @miladz68 WDYT? For me it's quite obvious that `struct` exp [...]

2022-09-02 09:36 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 99 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5kd26r7Cgu1q3GBQ:-NAxT8oR2r0-W16kiTCe:b-84hyfj) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would prefate to remove all comments. But will keep it just to support the reviewers. :-)
Updated.
</blockquote></details>

they are important to newcomers to understand the goals
___
*[`integration-tests/wasm/bank_send.go` line 111 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5rZ-EJg5DWFu2B0z:-NAxTOkq5eVEzZgsOcFd:b-u85hvd) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L111)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

but please keep the comment
___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NAxTVad12gww-snsiTu:b-exv2yg) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Remvoed. Comments are for the actions only.
</blockquote></details>

but please keep the comment, the integration test is long so it's important to make the flow clear to others
___
*[`integration-tests/wasm/bank_send.go` line 141 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo6LZ788yuL2mo1U67:-NAxTjo05Uy5PAunnpoC:byrl6ki) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L141)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

```
failed to execute message; message index: 0: dispatch: submessages: 15000dacore is smaller than 16000dacore: insufficient funds: invalid request
```
Same as bank send error.
</blockquote></details>

Okay, so could you please check that error returned is the exact expected one like I do in other tests by using `require.True(t, client.IsInsufficientFeeError(err))` not any error? You will need to add similar function checking if error is `ErrInsufficientFunds`. The logic for checking the error will be simplified in new `tx` package, but for now please follow the convention.

Also please add `FIXME (wojtek): add test verifying that transfer fails if sender is out of balance` in `integration-tests/bank/transfer.go`.
___
*[`integration-tests/wasm/client.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjwfs5NANjosFOx0y:-NAxVlAODxpE4KvN5DVD:br5b585) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes and no at the same time. We need it in the new client as well, also I started the PR beofer means I had to work with what I had :-) 
I understands that it's a conflict, but don't see the different right way. 
</blockquote></details>

I'm unblocking this comment to let this PR go before having new `tx` package
___
*[`integration-tests/wasm/simple_state.go` line 70 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAxX1BfBye5qI9Pelfw:-NAxX1BfBye5qI9Pelfx:b-6umee9) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/integration-tests/wasm/simple_state.go#L70)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// Query the contract state to get the initial count
> ```

Please keep this comment as it describes the flow of the test
___
*[`integration-tests/wasm/simple_state.go` line 87 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAxX6oD5FyAlxIRdovu:-NAxX6oD5FyAlxIRdovv:b-6umee9) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/integration-tests/wasm/simple_state.go#L87)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// Query the contract once again to ensure the count has been incremented
> ```

Please keep this comment as it describes the flow of the test
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NAxXKGx2eeve8vi04bj:b-668d0j) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Pls discuss it with Milad
If this approach is smth he agrees to keep in v2 of "client helpers" then I'm ok
However I would probably prefer to minimize changes in pkg/client
</blockquote></details>

After `WithGasEstimation` is added I don't like this concept even more. This is non-intuitive indirection. If you want to broadcast transaction with estimated gas, do it in steps:

1. estimate gas
2. multiply it by 1.5
3. set gas limit when calling `Broadcast`

That's why I'm saying that entire `SubmitMessage` function and the modifier are not needed here. This logic might be implemented as a helper function locally in your wasm test because this is the only place where it is required.
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAni60xAVaGkV_nm5RW:-NAxYZ7i80Cqq98OQY6m:b-s34be2) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets put it to WASM for now
</blockquote></details>

After seeing a comment saying that it might be useful for gov too, I'm accepting this solution.
___
*[`pkg/client/client.go` line 243 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo7GkIAZQiT9zjouok:-NAxYI7fAWM0B8stvn72:bz6ntqu) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/pkg/client/client.go#L243)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, updated with the new option.
</blockquote></details>

Continuing discussion in another comment: https://reviewable.io/reviews/CoreumFoundation/coreum/148#-NAnf8SM82qnyzJMZC5n


<!-- Sent from Reviewable.io -->

2022-09-02 11:18 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/wasm/bank_send.go` line 56 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhSe3o5o2gDbk9siYo:-NAxs22R-rDtC7yQk6WW:b-bq4nqq) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated not in the exect way @wojtek-coreum mentioed but it covers all it logicaly
</blockquote></details>

ok for me
I would say that adding last step to withdraw everything is also nice to have because it is another critical case but we can live without it.
As you prefer
___
*[`integration-tests/wasm/bank_send.go` line 72 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAhS5ty2MnW64P2fIru:-NAxsP2H--9pQHbNZI5f:b7bm4tx) ([raw file](https://github.com/coreumfoundation/coreum/blob/a32052a4dfc289ed6631ffbe69917be7a5ddfe10/integration-tests/wasm/bank_send.go#L72)):*
> I personally prepare to avoid the interface{} type as much as possible
sure
but it is natural in some places (e.g json Marshal) and we can do nothing about it

satisfied
___
*[`integration-tests/wasm/bank_send.go` line 141 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo6LZ788yuL2mo1U67:-NAxt8JI8BcSlvkW0bE0:b-qes09f) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L141)):*
> Okay, so could you please check that error returned is the exact expected one like I do in other tests by using

very reasonable
___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAniKkZ-Fny-reAvXCx:-NAxtFbRBqC6Iybr6G1l:bvuy6rz) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I disagree to call this client at least in the format we have right now. I don't like that it receives baseInput on initialization which should be arg of function

we can:
1. restruct it a bit to be wrapper around WASMclient with reusable functionality and some fancy name
2. keep it as a set of helper funcs

I would probably do smth like this:
```golang
type wasmTestClient struct {
  client.Client
}

func (c *wasmTestClient) deploy(ctx context.Context, baseInput BaseInput, wasmData []byte) (uint64, error) {
 // ...
}

// ...
func (c *wasmTestClient) query(ctx context.Context, contractAddr string, payload json.RawMessage) (json.RawMessage, error) {
// ...
}
```
Then it looks and feels like just extending existing client

Naming is subject for changes in this exmpl
</blockquote></details>

resolving all discussion related to client
I accept we do whatever is needed now here and in next Milad's PR we restructure some parts
___
*[`integration-tests/wasm/client.go` line 41 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjFho73YFVVs0-iuM:-NAxu5679-x2dMl0cQZw:b-vrtlis) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see your point Wojtek and it sort of makes sense for me
I personally slightly prefer having 2 public methods capitalised
But if smn has strong opinion on this I'm open for discussion
</blockquote></details>

posted this discussion in channel
Waiting for input from other team members
___
*[`integration-tests/wasm/client.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjwfs5NANjosFOx0y:-NAxuLF593YIx5zIKK5o:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I'm unblocking this comment to let this PR go before having new `tx` package
</blockquote></details>

ok
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NAxucXo1gn7-cFmpT1V:b-4g8l) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After `WithGasEstimation` is added I don't like this concept even more. This is non-intuitive indirection. If you want to broadcast transaction with estimated gas, do it in steps:

1. estimate gas
2. multiply it by 1.5
3. set gas limit when calling `Broadcast`

That's why I'm saying that entire `SubmitMessage` function and the modifier are not needed here. This logic might be implemented as a helper function locally in your wasm test because this is the only place where it is required.
</blockquote></details>

I think ok approach for now will be to keep this in integration-tests
___
*[`pkg/client/client.go` line 385 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAni60xAVaGkV_nm5RW:-NAxv5qa--J1VEviOnD5:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L385)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After seeing a comment saying that it might be useful for gov too, I'm accepting this solution.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-02 11:21 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 9 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAniKkZ-Fny-reAvXCx:-NAxvXGy8bPWE_Z8-g19:bb89uj8) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

resolving all discussion related to client
I accept we do whatever is needed now here and in next Milad's PR we restructure some parts
</blockquote></details>

ok for me currently


<!-- Sent from Reviewable.io -->

2022-09-02 13:32 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 111 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5rZ-EJg5DWFu2B0z:-NAxoxSO8EZR4zmu-Fg2:b-eajom0) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but please keep the comment
</blockquote></details>

That part seems too obvious to keep it.
___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NAxp4uX5O4-oh17Ey-h:b-19t6dg) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but please keep the comment, the integration test is long so it's important to make the flow clear to others
</blockquote></details>

The code shows what we do, it's splitter into the logical blocks, so no need to add the same by text.
___
*[`integration-tests/wasm/bank_send.go` line 141 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo6LZ788yuL2mo1U67:-NAxr6XT-zmEaKrxBGGU:bhn1k92) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L141)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Okay, so could you please check that error returned is the exact expected one like I do in other tests by using

very reasonable
</blockquote></details>

Updated with the error check. The updated code is tricky but that was the only way to do it.

It's a bit strange to add this FIXME, :-) But I've added.
___
*[`integration-tests/wasm/client.go` line 1 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAniKkZ-Fny-reAvXCx:-NAy28Xp7JkISiBL9K1R:bq6xgj7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok for me currently
</blockquote></details>

Updated. The baseInput is not a part of the client anymore.
___
*[`integration-tests/wasm/client.go` line 23 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjkiXBwW9iM0L3Uc0:-NAy2NOY0sgMWaMcC2Lx:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

see previous comment
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/client.go` line 41 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnjFho73YFVVs0-iuM:-NAy2SS-2lmZ1OxgQONW:bph6lxa) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/integration-tests/wasm/client.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

posted this discussion in channel
Waiting for input from other team members
</blockquote></details>

Now the updated Client is Exported also as the 3 Exported methods: DeployAndInstantiate, Execute and Query. All others are private. 
___
*[`integration-tests/wasm/simple_state.go` line 70 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAxX1BfBye5qI9Pelfw:-NAy1Di812s6LO1rMc-4:b-ii2j8e) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/integration-tests/wasm/simple_state.go#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please keep this comment as it describes the flow of the test
</blockquote></details>

The same reply regarding all removed comments.
___
*[`integration-tests/wasm/simple_state.go` line 87 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAxX6oD5FyAlxIRdovu:-NAy1JpP803Ld_NpoJe0:b-ii2j8e) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/integration-tests/wasm/simple_state.go#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please keep this comment as it describes the flow of the test
</blockquote></details>

The same reply regarding all removed comments.
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NAy2tNx6_sbWM8Wr6hz:b-glia3r) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think ok approach for now will be to keep this in integration-tests
</blockquote></details>

In order to simplify our migration to the new tx pack, I've remove this code and move the simplified version to the wasm test Client. 


<!-- Sent from Reviewable.io -->

2022-09-02 15:48 UTC, ysv submitted a review, later dismissed
> Reviewed 1 of 7 files at r4, 3 of 8 files at r6, 20 of 24 files at r7, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NAyVFBd8j2B7DIUzP6I:b-7ng22e) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The code shows what we do, it's splitter into the logical blocks, so no need to add the same by text.
</blockquote></details>

I would keep the comments
For me they help to navigate within these tests because everything is very similar there
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NAyTQlY47WK-rMVU1y8:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In order to simplify our migration to the new tx pack, I've remove this code and move the simplified version to the wasm test Client. 
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-05 06:30 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 28 of 30 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NBBGtQr6pC7DPTzxKr4:b-w90v3e) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would keep the comments
For me they help to navigate within these tests because everything is very similar there
</blockquote></details>

I've kept them, for that test.
But let's imagine that there was no comment. Would you ask me to add them? :-)
IMHO Any test should be read by code, not by the comments, so the comments are kind of the "information duplication" and also disctructs from the code. Adding the comments is required only for not trivial things, here is trivial. For that case, when in the test we execute the "BalanceSend" and then check something it's obvious that we check the updated balance.

But that description not for that test-case, since I've updated it, but for my future commits :-)
___
*[`pkg/client/client.go` line 214 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAnf8SM82qnyzJMZC5n:-NBBGoEH39NYPGSoUnPs:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1875077eabe8254f52c0b84f3333dee178519aa8/pkg/client/client.go#L214)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-05 06:31 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: 28 of 30 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 111 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5rZ-EJg5DWFu2B0z:-NBBL4pU5fTfFpN5RIzB:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L111)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That part seems too obvious to keep it.
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/bank_send.go` line 141 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo6LZ788yuL2mo1U67:-NBBL7Dt-QdF1N221XAa:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L141)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated with the error check. The updated code is tricky but that was the only way to do it.

It's a bit strange to add this FIXME, :-) But I've added.
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/simple_state.go` line 70 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAxX1BfBye5qI9Pelfw:-NBBKwl05OnflIXVAioQ:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/integration-tests/wasm/simple_state.go#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The same reply regarding all removed comments.
</blockquote></details>

Updated.
___
*[`integration-tests/wasm/simple_state.go` line 87 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAxX6oD5FyAlxIRdovu:-NBBL-YFAJUXMTd6poNN:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddf7bfbdbcc006ecd23083078fe6c6bcbedf4db2/integration-tests/wasm/simple_state.go#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The same reply regarding all removed comments.
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-09-05 08:31 UTC, wojtek-coreum requested changes
> Reviewed 3 of 5 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/wasm/bank_send.go` line 121 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NAo5xSP1uuEfrrFdApO:-NBBiPwX7jiihEldlfGz:b-883e5r) ([raw file](https://github.com/coreumfoundation/coreum/blob/cd63a9c9e228718a0553a45f0896b6f85b34b278/integration-tests/wasm/bank_send.go#L121)):*
> Would you ask me to add them?

yes

> here is trivial

it's not
___
*[`pkg/client/client.go` line 241 at r12](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NBBl-Y9D5AUoPuF5tSj:-NBBl-Y9D5AUoPuF5tSk:bejokwv) ([raw file](https://github.com/coreumfoundation/coreum/blob/d9507abb23219ddd090096122fa3e43f534cb1eb/pkg/client/client.go#L241)):*
> ```Go
> 		TxBytes: simTxBytes,
> 	})
> 	errRes := client.CheckTendermintError(err, simTxBytes)
> ```

leftover?
___
*[`pkg/client/client.go` line 338 at r12](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NBBl3Vf9_ss-GqoPcfQ:-NBBl3Vf9_ss-GqoPcfR:b-9s5rme) ([raw file](https://github.com/coreumfoundation/coreum/blob/d9507abb23219ddd090096122fa3e43f534cb1eb/pkg/client/client.go#L338)):*
> ```Go
> 
> // IsInsufficientFeeError returns true if error was caused by insufficient fee provided with the transaction.
> // TODO (dhil) this func should re replaced by the IsErr in all tests.
> ```

re -> be
___
*[`pkg/client/client.go` line 338 at r12](https://reviewable.io/reviews/coreumfoundation/coreum/148#-NBBlKhxAE3GMAlkPxxg:-NBBlKhxAE3GMAlkPxxh:b-zd9adq) ([raw file](https://github.com/coreumfoundation/coreum/blob/d9507abb23219ddd090096122fa3e43f534cb1eb/pkg/client/client.go#L338)):*
> ```Go
> 
> // IsInsufficientFeeError returns true if error was caused by insufficient fee provided with the transaction.
> // TODO (dhil) this func should re replaced by the IsErr in all tests.
> ```

could you do it? There are only 2 or 3 places, so it doesn't deserve its own PR, and it's better to eliminate technical debt immediately


<!-- Sent from Reviewable.io -->

2022-09-05 09:38 UTC, ysv approved these changes
> Reviewed 2 of 2 files at r12, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-09-05 10:10 UTC, wojtek-coreum approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)



<!-- Sent from Reviewable.io -->

2022-09-05 10:29 UTC, dzmitryhil reviewed
> Reviewed 1 of 27 files at r1, 1 of 7 files at r4, 20 of 24 files at r7, 2 of 5 files at r11, 2 of 2 files at r12, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)



<!-- Sent from Reviewable.io -->

2022-09-05 10:51 UTC, merged