Export state of `feemodel` module
CoreumFoundation/coreum pull request #154
Opened 2022-09-01 06:59 UTC by wojtek-coreum

2022-09-01 08:10 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs4azj8OTwLPxpBkMn:-NAs4azj8OTwLPxpBkMo:b-6poc6x) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/module.go#L127)):*
> ```Go
> 	// FIXME (wojtek): Remove this after crust imports new version of coreum
> 	if genesis.Validate() != nil {
> 		genesis = types.DefaultGenesisState()
> ```

If the genesis.Validate() retruns error -> panic(), we can't proceed next. 
Or your "FIXME" says that you will start "panic" later ?



_Code quote:_
```Go
genesis.Validate()
```
___
*[`x/feemodel/module.go` line 138 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs3Yv5DXkeBjwa9d2a:-NAs3Yv5DXkeBjwa9d2b:bggma1q) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/module.go#L138)):*
> ```Go
> // ExportGenesis returns the exported genesis state as raw bytes for the fee
> // module.
> func (am AppModule) ExportGenesis(ctx sdk.Context, cdc codec.JSONCodec) json.RawMessage {
> ```

Don't see the unit tests for it. 
___
*[`x/feemodel/types/genesis.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs4vrG5ir06JPcVLk2:-NAs4vrG5ir06JPcVLk3:b-qe83om) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/types/genesis.go#L12)):*
> ```Go
> 	return &GenesisState{
> 		Params:      model,
> 		MinGasPrice: sdk.NewCoin("cosmos", model.InitialGasPrice),
> ```

Why do you use the "cosmos" name here? :-) 
If you are going to replace it in any case, use the ```sdk.DefaultBondDenom``` at least it will be registered in the metadata by default, and will exist on chain.


<!-- Sent from Reviewable.io -->

2022-09-01 11:46 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs4azj8OTwLPxpBkMn:-NAsr93U7Jc-moO6JmM1:by7l5bg) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/module.go#L127)):*
> Or your "FIXME" says that you will start "panic" later ?

exactly, this is a temporary thing until crust imports new config of genesis, otherwise `znet` does not work
___
*[`x/feemodel/types/genesis.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs4vrG5ir06JPcVLk2:-NAsrO6V3cFJ09dtadl_:b-967fbn) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/types/genesis.go#L12)):*
> Why do you use the "cosmos" name here? :-)

Because all the modules use `cosmos` for default genesis state

> use the sdk.DefaultBondDenom

`sdk.DefaultBondDenom` resolves to `stake`, and the functionality here is not related to staking


<!-- Sent from Reviewable.io -->

2022-09-01 12:10 UTC, dzmitryhil reviewed
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-01 14:14 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/types/genesis.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs4vrG5ir06JPcVLk2:-NAtOoTi0FrsxlWjbXTF:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/types/genesis.go#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> here
The "stake" is used in may other modules as default param as well. For example "gov", "mint", "crisis" actually all modules with the demon in the genesis
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-02 11:54 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module.go` line 138 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAs3Yv5DXkeBjwa9d2a:-NAy2QGf5sqzIQDua7rB:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e29a88902bc0beb0497f40d8b62e44a7115be103/x/feemodel/module.go#L138)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't see the unit tests for it. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-02 13:42 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NAyQ0xt7Ox0gWKsu-9S:b2gx623) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
> ```Go
> 
> func TestExport(t *testing.T) {
> 	cdc := app.NewEncodingConfig().Marshaler
> ```

You don't need the keeper mock to tests it, just check how the cosmos.sdk tests it. 
Best way to use it is simapp or initialized module, the mocks is rarely used for tests in cosmos sdk.


<!-- Sent from Reviewable.io -->

2022-09-02 13:48 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NAySK-fDmV54iCjHbRI:b-xs2t4w) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need the keeper mock to tests it, just check how the cosmos.sdk tests it. 
Best way to use it is simapp or initialized module, the mocks is rarely used for tests in cosmos sdk.
</blockquote></details>

Could you point me to some example of how to use simapp?


<!-- Sent from Reviewable.io -->

2022-09-05 06:41 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBBM3fB3L1oFd8upgkj:b-t1d8s5) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you point me to some example of how to use simapp?
</blockquote></details>

Sure, for example
1) https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/keeper/genesis_test.go#L49
2) https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/keeper/genesis_test.go#L75
Here it uses the tests sute, but in your case you can do that same but without the sute. 
Also it's possible to do the import/export and check the the import json = export json.
3) https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/keeper/genesis_test.go#L75


<!-- Sent from Reviewable.io -->

2022-09-05 08:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBBgoTq1V5Z3m5UW6m0:b2zixyr) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Sure, for example
1) https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/keeper/genesis_test.go#L49
2) https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/keeper/genesis_test.go#L75
Here it uses the tests sute, but in your case you can do that same but without the sute. 
Also it's possible to do the import/export and check the the import json = export json.
3) https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/keeper/genesis_test.go#L75
</blockquote></details>

What I see in provided examples is that:
- they don't test using simapp, they test only keepers
- all the operations are implemented inside the keeper (`InitGenesis`, `ExportGenesis`)
- they only create keeper and test it, without testing the module itself

On the other hand I do it this way:
- init genesis and export genesis logic is implemented inside the module, treating keeper only as a data source
- I test module, not keeper
- that's why I create a mock of keeper - to test the module

IMO, my way is better.
Maybe I should also add unit tests for keeper

@ysv WDYT?


<!-- Sent from Reviewable.io -->

2022-09-05 08:50 UTC, miladz68 approved these changes
> Reviewed 1 of 6 files at r1, 6 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-05 08:50 UTC, miladz68 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-05 09:35 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBBzP_lDCehQZK3if0_:bp41upa) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What I see in provided examples is that:
- they don't test using simapp, they test only keepers
- all the operations are implemented inside the keeper (`InitGenesis`, `ExportGenesis`)
- they only create keeper and test it, without testing the module itself

On the other hand I do it this way:
- init genesis and export genesis logic is implemented inside the module, treating keeper only as a data source
- I test module, not keeper
- that's why I create a mock of keeper - to test the module

IMO, my way is better.
Maybe I should also add unit tests for keeper

@ysv WDYT?
</blockquote></details>

It's possible access the modlue as well. But in your case I would move the Import/Export to the keeper and test it there as a keeper test.
___
*[`x/feemodel/module_test.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBBz4fZ7biDgpKEFMO8:-NBBz4f_BhBIO6Rnl4lH:b-blf8hn) ([raw file](https://github.com/coreumfoundation/coreum/blob/adcd250d85a84caf4c039e7fe62744ba54f70201/x/feemodel/module_test.go#L15)):*
> ```Go
> )
> 
> var genesis = types.GenesisState{
> ```

The best version would be to use mock-gen, but at lest  keep it inside the mock. And init in the newKeeperMock. The global variable a very bad practice in the tests as well.


<!-- Sent from Reviewable.io -->

2022-09-05 11:51 UTC, dzmitryhil reviewed
> Reviewed 4 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-06 06:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBGTdTm4tvbjHSiygNN:b-ewk12w) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
> I would move the Import/Export to the keeper and test it there as a keeper test.

I have different opinion. Keeper is the storage, it's responsibility is to store and retrieve values.
`InitGenesis` and `ExportGenesis` is the concept implemented on the module level, keeper only delivers data for those operations.
That's why it's logic IMO should be implemented in module, not in keeper.
___
*[`x/feemodel/module_test.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBBz4fZ7biDgpKEFMO8:-NBGTaUbCzxWbTNmfjUq:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/adcd250d85a84caf4c039e7fe62744ba54f70201/x/feemodel/module_test.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The best version would be to use mock-gen, but at lest  keep it inside the mock. And init in the newKeeperMock. The global variable a very bad practice in the tests as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-06 09:16 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBH4DWwCZL4pI4FgJCH:b-fg711v) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> I would move the Import/Export to the keeper and test it there as a keeper test.

I have different opinion. Keeper is the storage, it's responsibility is to store and retrieve values.
`InitGenesis` and `ExportGenesis` is the concept implemented on the module level, keeper only delivers data for those operations.
That's why it's logic IMO should be implemented in module, not in keeper.

</blockquote></details>

That is correct, but you don't test it in the keep as well :-)
In order to be sure that it goes well and integration with the params and stores succuessed we should use the simapp test to set and get them.


<!-- Sent from Reviewable.io -->

2022-09-06 09:16 UTC, dzmitryhil reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-06 09:26 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBH6n7N0Vc2kqVEFsh4:b-eb07m) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That is correct, but you don't test it in the keep as well :-)
In order to be sure that it goes well and integration with the params and stores succuessed we should use the simapp test to set and get them.
</blockquote></details>

I will write separate tests for keeper as well


<!-- Sent from Reviewable.io -->

2022-09-06 09:46 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBHBKUkDi6achpBVvxu:b-z8c1rc) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I will write separate tests for keeper as well
</blockquote></details>

What do you mean "separate" ?


<!-- Sent from Reviewable.io -->

2022-09-06 11:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBHV9TAAoqddRSiLd0o:b-ydvv65) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What do you mean "separate" ?
</blockquote></details>

`keeper/keeper_test.go` testing methods of the keeper


<!-- Sent from Reviewable.io -->

2022-09-06 12:22 UTC, ysv requested changes
> Reviewed 4 of 6 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, and @wojtek-coreum)

___
*[`x/feemodel/module.go` line 158 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBHKkqsCaf7t7tJdU5e:-NBHKkqsCaf7t7tJdU5f:b-9j36l7) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d7acff848b19ce34b761ff0be86aea6ed2e8358/x/feemodel/module.go#L158)):*
> ```Go
> 	params := am.keeper.GetParams(ctx)
> 	model := types.NewModel(params)
> 	oldMinGasPrice := am.keeper.GetMinGasPrice(ctx)
> ```

`prev/previous MinGasPrice` ?
___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBHjSTM6HDUFkN3z2VL:b-x18b3o) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`keeper/keeper_test.go` testing methods of the keeper
</blockquote></details>

If I understand correctly here we just mock keeper and simply return structure from it. Then encode, decode and compare.

In terms of approach this test is right that each component is tested separately. But it is so simple that I would write a single test for both real keeper & module


<!-- Sent from Reviewable.io -->

2022-09-06 12:39 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module.go` line 158 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBHKkqsCaf7t7tJdU5e:-NBHo5vNA5Vg7MHYDry_:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d7acff848b19ce34b761ff0be86aea6ed2e8358/x/feemodel/module.go#L158)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`prev/previous MinGasPrice` ?
</blockquote></details>

Done.
___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBHndOB33XYpB1e5Rjl:bxe684u) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

If I understand correctly here we just mock keeper and simply return structure from it. Then encode, decode and compare.

In terms of approach this test is right that each component is tested separately. But it is so simple that I would write a single test for both real keeper & module
</blockquote></details>

tests of keeper should go in `keeper/keeper_test.go` because testing code should be next to tested the tested one. Here only module should be tested.


<!-- Sent from Reviewable.io -->

2022-09-06 13:51 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBI2s446X_hFDvMGU9U:b98c9z2) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

tests of keeper should go in `keeper/keeper_test.go` because testing code should be next to tested the tested one. Here only module should be tested.
</blockquote></details>

waiting for keeper test for now
After we see it we will have more context and will decide on this one


<!-- Sent from Reviewable.io -->

2022-09-06 13:52 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-07 10:20 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: 5 of 11 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBMSAnlDKS97RbR2OKF:bv6q199) ([raw file](https://github.com/coreumfoundation/coreum/blob/14db1e7703f26866189b0cfdb2313049f7aca3fd/x/feemodel/keeper/keeper_test.go#L43)):*
> ```Go
> 
> func setup() (sdk.Context, keeper.Keeper) {
> 	key := sdk.NewKVStoreKey(types.StoreKey)
> ```

Why don't you use simapp for the test? Becase you mock the "ParamSubspace" here, but use the real DB. The simapp will it for you, so you won't need to init in here.
___
*[`x/feemodel/keeper/keeper_test.go` line 107 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSV757p2pouqfnt4I:-NBMSV757p2pouqfnt4J:b-4w1dzu) ([raw file](https://github.com/coreumfoundation/coreum/blob/14db1e7703f26866189b0cfdb2313049f7aca3fd/x/feemodel/keeper/keeper_test.go#L107)):*
> ```Go
> 	params := keeper.GetParams(ctx)
> 
> 	assert.True(t, defParams.InitialGasPrice.Equal(params.InitialGasPrice))
> ```

Why do you use the assert.True and assert.Equal for the same asserts?


<!-- Sent from Reviewable.io -->

2022-09-07 10:20 UTC, dzmitryhil reviewed
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-07 10:37 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBMWJTW0dztE8gPiPil:bnrot9i) ([raw file](https://github.com/coreumfoundation/coreum/blob/14db1e7703f26866189b0cfdb2313049f7aca3fd/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you use simapp for the test? Becase you mock the "ParamSubspace" here, but use the real DB. The simapp will it for you, so you won't need to init in here.
</blockquote></details>

I do it the way it is done in examples for `feegrant` you provided
___
*[`x/feemodel/keeper/keeper_test.go` line 107 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSV757p2pouqfnt4I:-NBMWSP-CR8nWvtf0VRE:bokspwy) ([raw file](https://github.com/coreumfoundation/coreum/blob/14db1e7703f26866189b0cfdb2313049f7aca3fd/x/feemodel/keeper/keeper_test.go#L107)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you use the assert.True and assert.Equal for the same asserts?
</blockquote></details>

`sdk.Int` can't be compared using `assert.Equal` because under the hood pointer to `big.Int` is stored, so `assert.Equal` will compare ointers, not real values. That's why I use `Equal` method of `sdk.Int` which returns bool, so `assert.True` is here.


<!-- Sent from Reviewable.io -->

2022-09-07 17:02 UTC, ysv requested changes
> Reviewed 1 of 1 files at r6, 3 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @wojtek-coreum)

___
*[`app/app.go` line 358 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBNjust2WfZuIyYLtY7:-NBNjusv1MBQu8GkL-hP:br23ivr) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/app/app.go#L358)):*
> ```Go
> 
> 	app.FeeModelKeeper = feemodelkeeper.NewKeeper(
> 		app.GetSubspace(feemodeltypes.ModuleName).WithKeyTable(paramstypes.NewKeyTable().RegisterParamSet(&feemodeltypes.Params{})),
> ```

do I understand this line correctly
It is sort of table with structure of feemodel.Params in feemodel module subspace created specifically to store these params ?
___
*[`x/feemodel/module.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBNkSmP-nooEtzxvLnz:-NBNkSmP-nooEtzxvLo-:b-4bn5y5) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/x/feemodel/module.go#L128)):*
> ```Go
> 	if genesis.Validate() != nil {
> 		genesis = types.DefaultGenesisState()
> 		genesis.MinGasPrice.Denom = "dacore"
> ```

I think Milad has updated crust to use lates coreum now
___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBNqRcQ49mIBW3fO-4A:b-a17rh) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I do it the way it is done in examples for `feegrant` you provided
</blockquote></details>

@wojtek-coreum @dzmitryhil pls decide on this one
___
*[`x/feemodel/keeper/keeper_test.go` line 107 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSV757p2pouqfnt4I:-NBNq4mJBdm6pjXCg3bv:b-i19d20) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/x/feemodel/keeper/keeper_test.go#L107)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`sdk.Int` can't be compared using `assert.Equal` because under the hood pointer to `big.Int` is stored, so `assert.Equal` will compare ointers, not real values. That's why I use `Equal` method of `sdk.Int` which returns bool, so `assert.True` is here.
</blockquote></details>

I've tried and it works for me
I believe assert.Equeal uses equal if it is define somewhere under the hood

![Screenshot 2022-09-07 at 18.45.42.png](https://files.reviewableusercontent.io/images/reviewable/19859122/4UJgZZS0Xm3Y2U5_IzKiROEh/Screenshot%202022-09-07%20at%2018.45.42.png)
Screenshot 2022-09-07 at 18.45.42


<!-- Sent from Reviewable.io -->

2022-09-08 06:01 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 358 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBNjust2WfZuIyYLtY7:-NBQeo7UEjH3emVb0c-J:b-drduyi) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/app/app.go#L358)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do I understand this line correctly
It is sort of table with structure of feemodel.Params in feemodel module subspace created specifically to store these params ?

</blockquote></details>

It is a weird way of telling params module to create a subspace inside its keeper for storing params related to fee model. Don't ask me why it is implemented this way...
___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBQfDCECX27rgzOsApM:b36k1we) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum @dzmitryhil pls decide on this one
</blockquote></details>

personally I prefer to test things in the simplest (classic) way by creating mocks for dependencies and testing object directly instead of using some simulator, t least in so trivial case. I agree that simulator might be used to test complex flows like generating many blocks etc.
___
*[`x/feemodel/keeper/keeper_test.go` line 107 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSV757p2pouqfnt4I:-NBQff29-83mlvQspb6L:b3moua9) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc49fb3c5f8ac1c5525df51cf21bbc722ad9627d/x/feemodel/keeper/keeper_test.go#L107)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I've tried and it works for me
I believe assert.Equeal uses equal if it is define somewhere under the hood

![Screenshot 2022-09-07 at 18.45.42.png](https://files.reviewableusercontent.io/images/reviewable/19859122/4UJgZZS0Xm3Y2U5_IzKiROEh/Screenshot%202022-09-07%20at%2018.45.42.png)
Screenshot 2022-09-07 at 18.45.42
</blockquote></details>

weird, must check this


<!-- Sent from Reviewable.io -->

2022-09-08 07:14 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBQwZv836cIiO6qVbv-:bqwy0xw) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

personally I prefer to test things in the simplest (classic) way by creating mocks for dependencies and testing object directly instead of using some simulator, t least in so trivial case. I agree that simulator might be used to test complex flows like generating many blocks etc.
</blockquote></details>

I would you the sim app here as well, it would help to remove the mock code on the one hand and test deeper on the other.
___
*[`x/feemodel/keeper/keeper_test.go` line 107 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSV757p2pouqfnt4I:-NBQw7iq7eA86YJKFXc1:b-n2rew6) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/keeper/keeper_test.go#L107)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

weird, must check this
</blockquote></details>

You Int.String(), that will give better assert errors in case of mismatch 


<!-- Sent from Reviewable.io -->

2022-09-08 10:42 UTC, miladz68 requested changes
> Reviewed 1 of 2 files at r5, 5 of 6 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module.go` line 128 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBRfNuc9Mv5SSSzSj--:-NBRfNuc9Mv5SSSzSj-0:bfj5hk8) ([raw file](https://github.com/coreumfoundation/coreum/blob/35743df91d7e3b420a8e32c29abf16a47a9e45bb/x/feemodel/module.go#L128)):*
> ```Go
> 	if genesis.Validate() != nil {
> 		genesis = types.DefaultGenesisState()
> 		genesis.MinGasPrice.Denom = "dmcore"
> ```

is there a way not to have it hardcoded ? like using app.TokenSymbolDev ?


<!-- Sent from Reviewable.io -->

2022-09-08 10:55 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module.go` line 128 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBRfNuc9Mv5SSSzSj--:-NBRjEHc5oUVZ6rsUfAS:bytir7y) ([raw file](https://github.com/coreumfoundation/coreum/blob/35743df91d7e3b420a8e32c29abf16a47a9e45bb/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

is there a way not to have it hardcoded ? like using app.TokenSymbolDev ?
</blockquote></details>

I can't import `app` here because it will create circular dependency


<!-- Sent from Reviewable.io -->

2022-09-08 11:31 UTC, ysv requested changes
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @wojtek-coreum)

___
*[`x/feemodel/module.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBNkSmP-nooEtzxvLnz:-NBRo82KC1RcJ5qZd2Ar:bogfa9v) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

but doesn't it mean that we can remove this `if` fully ?
___
*[`x/feemodel/module.go` line 128 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBRfNuc9Mv5SSSzSj--:-NBRoBEz8WSt-nekArlX:b-6k4yyz) ([raw file](https://github.com/coreumfoundation/coreum/blob/35743df91d7e3b420a8e32c29abf16a47a9e45bb/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I can't import `app` here because it will create circular dependency
</blockquote></details>

we should look for a way to fix this (maybe in other PR)
this doesn't seems to be correct approach
___
*[`x/feemodel/module_test.go` line 68 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NAyQ0xs6AH0aicGc17p:-NBRoJ_S4ew0_HE-SFSm:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/6d139937e273adef97e1bc033450d1bfd746aaa5/x/feemodel/module_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBRqacsD2oKM_RtJQNg:bfh292a) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As I said, I prefer to keep unit tests as simple as possible (in the sense of design, not number of lines), it means simulator adds another layer of magic in the place where that magic is not really needed. @ysv please decide :-)
</blockquote></details>

I think that it is better here to use simapp here because I prefer to have test fully independent when we have complicated business logic which needs to be tested separately. But for this exactly case it is overkill because the logic is simple so it is better to test full flow

However since we have these tests written using mocks I think to not spend more time on this we can keep them as they are


<!-- Sent from Reviewable.io -->

2022-09-08 12:16 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, and @wojtek-coreum)

___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBS0fnC4_aTV1apA8wN:bnyp1ky) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think that it is better here to use simapp here because I prefer to have test fully independent when we have complicated business logic which needs to be tested separately. But for this exactly case it is overkill because the logic is simple so it is better to test full flow

However since we have these tests written using mocks I think to not spend more time on this we can keep them as they are
</blockquote></details>

Ok, resolved, with the hope to future :-)


<!-- Sent from Reviewable.io -->

2022-09-08 12:16 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-09-08 13:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBNkSmP-nooEtzxvLnz:-NBSDeXo4ExT9vSe-L7v:b-8p9qny) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but doesn't it mean that we can remove this `if` fully ?
</blockquote></details>

No, we can remove it once crust starts using this (and next) PR because it contains required changes in genesis.json
___
*[`x/feemodel/module.go` line 128 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBRfNuc9Mv5SSSzSj--:-NBSDppV7YAhAxnpz1pp:b-i60rl7) ([raw file](https://github.com/coreumfoundation/coreum/blob/35743df91d7e3b420a8e32c29abf16a47a9e45bb/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we should look for a way to fix this (maybe in other PR)
this doesn't seems to be correct approach
</blockquote></details>

this is temporary code


<!-- Sent from Reviewable.io -->

2022-09-08 13:17 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @oliverasistemas)

___
*[`x/feemodel/module.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBNkSmP-nooEtzxvLnz:-NBSEudUCiV271LbNyYt:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, we can remove it once crust starts using this (and next) PR because it contains required changes in genesis.json
</blockquote></details>

ok
___
*[`x/feemodel/module.go` line 128 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBRfNuc9Mv5SSSzSj--:-NBSEvLk7uDmShm0nA8i:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/35743df91d7e3b420a8e32c29abf16a47a9e45bb/x/feemodel/module.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this is temporary code
</blockquote></details>

ok
___
*[`x/feemodel/keeper/keeper_test.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/154#-NBMSAnk02RJKoiAiz7H:-NBSExENDluqQ2qC50QU:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/cc434a7e9cf2b836cd0bd461075875ac106d002b/x/feemodel/keeper/keeper_test.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, resolved, with the hope to future :-)
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-08 13:27 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @oliverasistemas)



<!-- Sent from Reviewable.io -->

2022-09-08 13:27 UTC, merged