Add multisig integration test
CoreumFoundation/coreum pull request #163
Opened 2022-09-08 07:22 UTC by dzmitryhil

2022-09-08 08:38 UTC, wojtek-coreum requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 10 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 61 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9eba1_ZEYxvzuP08:-NBR9ebb6Ezc2WfnXI0N:b-87okud) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L61)):*
> ```Go
> 	keyNamesSet := []string{key1, key2, key3}
> 	kr := sdkkeyring.NewInMemory()
> 	publicKeysSet := make([]cryptotypes.PubKey, 0, len(keyNamesSet))
> ```

publicKeysSet -> publicKeySet
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAtop2wUs2dBZ7roq:-NBRAtop2wUs2dBZ7ror:bjjmjnc) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
> ```Go
> 	multisigAddress, err := sdk.AccAddressFromHex(multisigPublicKey.Address().String())
> 
> 	// fund the multisign account
> ```

multisign -> multisig
___
*[`integration-tests/auth/multisig.go` line 114 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAr_U3SHOYXl5PX7i:-NBRAr_U3SHOYXl5PX7j:bid08g0) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L114)):*
> ```Go
> 	txConfig := clientCtx.TxConfig
> 
> 	// build the bank send tx to sing later
> ```

sing -> sign
___
*[`integration-tests/auth/multisig.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRCEoM4GtZcgCo5Syo:-NBRCEoM4GtZcgCo5Syp:b42vkxd) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L115)):*
> ```Go
> 
> 	// build the bank send tx to sing later
> 	txBuilder := txConfig.NewTxBuilder()
> ```

Usually everything is set in factory and then txbuilder is created using `txF.BuildUnsignedTx`:
https://github.com/CoreumFoundation/coreum/blob/new-client/pkg/tx2/sign.go#L32

so txBuilder is preconfigure by the factory
___
*[`integration-tests/auth/multisig.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBbmY3NCZrSNgfEgR:-NBRBbmY3NCZrSNgfEgS:b-s29eh7) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L117)):*
> ```Go
> 	txBuilder := txConfig.NewTxBuilder()
> 	txBuilder.SetGasLimit(bankSendGas)
> 	txBuilder.SetFeeAmount(sdk.NewCoins(sdk.NewCoin(nativeDenom, initialGasPrice.Mul(sdk.NewInt(int64(bankSendGas))))))
> ```

You could use `WithGas` and `WithGasPrices` methods of tx factory, to not compute fee yourself:
https://github.com/CoreumFoundation/coreum/blob/new-client/pkg/tx2/sign.go#L20
https://github.com/CoreumFoundation/coreum/blob/new-client/pkg/tx2/sign.go#L29
___
*[`integration-tests/auth/multisig.go` line 125 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRCXt41PWhPO-PmHgn:-NBRCXt41PWhPO-PmHgo:bid08g0) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L125)):*
> ```Go
> 	bankSendRawTx := txBuilder.GetTx()
> 
> 	// prepare the tx factory to sing with the account seq and number of the multisig account
> ```

sing -> sign
___
*[`integration-tests/auth/multisig.go` line 130 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBNmwDVttlmFtyq-J:-NBRBNmx9xsqSpz3UR3x:b5wjzlb) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L130)):*
> ```Go
> 	txF := sdktx.Factory{}. // TODO (dhil) move this code to helpers after the migration to the ne tx package
> 				WithAccountNumber(multisigAccNum).
> 				WithSequence(multisigAccSeq).
> ```

isn't it just 0 (first tx)?
___
*[`integration-tests/auth/multisig.go` line 137 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRE3cg0K1K1Bl1yVWe:-NBRE3cg0K1K1Bl1yVWf:b-q9cqpm) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L137)):*
> ```Go
> 
> 	// sign and submit with just one key to check the tx rejection
> 	bankSendMultisignTx, err := copyTx(txConfig, bankSendRawTx) // copy since the tx builder mutate it
> ```

by using `txF.BuildUnsignedTx` you should solve the problem of copying
___
*[`integration-tests/auth/multisig.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBREeHR0hbxHhDJ3vWz:-NBREeHS9U3JNXnptRTX:b-4sddqr) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L170)):*
> ```Go
> }
> 
> func addRandomAccountToKeyring(name string, kr sdkkeyring.Keyring) (sdkkeyring.Info, error) {
> ```

@ysv I t seems like an another implementation of what you did in #162 . Could you coordinate please?
___
*[`integration-tests/auth/multisig.go` line 189 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBREs_19qprBDPnuy-0:-NBREs_19qprBDPnuy-1:b194mmm) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L189)):*
> ```Go
> }
> 
> func createMulisignTx(txBuilder sdkclient.TxBuilder, accSec uint64, multisigPublicKey *sdkmultisig.LegacyAminoPubKey) (authsigning.Tx, error) {
> ```

Mulisign -> Multisig


<!-- Sent from Reviewable.io -->

2022-09-08 09:20 UTC, miladz68 requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 16 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR7OvO5JLpJA6MzZdr:-NBR7OvO5JLpJA6MzZds:bt0dpha) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L34)):*
> ```Go
> 	)
> 
> 	faucetWallet := testing.RandomWallet()
> ```

`faucetWallet` name is confusing, what is the purpose of this account ? can we have a better name for it ?
currently the code reads
```
transfer from faucet to faucetAccount.
```
___
*[`integration-tests/auth/multisig.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRACMU3uThxuQcfmzf:-NBRACMU3uThxuQcfmzg:b6y2luv) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L44)):*
> ```Go
> 	requireT.NoError(chain.Faucet.FundAccounts(ctx,
> 		testing.FundedAccount{
> 			// TODO (dhil): the test uses the faucetWallet since the FundedAccount consumes the Wallet instead of the address.
> ```

I don't think TODO is needed here, once the faucet API changes the compiler will complain and we will know. 
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9r5xD-t2RUp09RNA:-NBR9r5xD-t2RUp09RNB:b5h0h9g) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
> ```Go
> 	multisigAddress, err := sdk.AccAddressFromHex(multisigPublicKey.Address().String())
> 
> 	// fund the multisign account
> ```

we can fund it directly from the faucet.
___
*[`integration-tests/auth/multisig.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAwxJ1wipHgom0NJN:-NBRAwxJ1wipHgom0NJO:bvlkxie) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L95)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	// TODO (dhil) replace to new Broadcast once we finish with it
> ```

non-blocking
the new broadcast is in master and can be used
___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBRB8j31MmIjCCUjXaR:b-5i37ib) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	multisigBalances, err := coredClient.BankQueryClient().AllBalances(ctx, &banktypes.QueryAllBalancesRequest{
> ```

let's refrain from using coredClient in new code we produce.
___
*[`integration-tests/auth/multisig.go` line 106 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBNSd3C_fkH4_o0g7:-NBRBNSd3C_fkH4_o0g8:b32tm2q) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L106)):*
> ```Go
> 
> 	// prepare account to be funded from the multisign
> 	recipientWallet := testing.RandomWallet()
> ```

non-blocking
Maybe move all account declarations to the start of the function.


<!-- Sent from Reviewable.io -->

2022-09-08 12:11 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR7OvO5JLpJA6MzZdr:-NBReP_B3Na8Fq_Ikp1e:bqqnxcw) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

`faucetWallet` name is confusing, what is the purpose of this account ? can we have a better name for it ?
currently the code reads
```
transfer from faucet to faucetAccount.
```
</blockquote></details>

We use that account to fund the multisig account, since the "testing.Funded Account" consumes the wallet instead of address.
___
*[`integration-tests/auth/multisig.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRACMU3uThxuQcfmzf:-NBReeOV5NpLCvdmo4E7:b-3i9fyt) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think TODO is needed here, once the faucet API changes the compiler will complain and we will know. 
</blockquote></details>

It's needed. We need to refactor the logic, and don't use the faucet wallet. 
___
*[`integration-tests/auth/multisig.go` line 61 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9eba1_ZEYxvzuP08:-NBRelp73AwPdcN3rvLf:b-uahxwb) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L61)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

publicKeysSet -> publicKeySet
</blockquote></details>

The current name seems correct.
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAtop2wUs2dBZ7roq:-NBRdFSwBtlXjfFOioHP:b-ug48o9) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

multisign -> multisig
</blockquote></details>

The cosmos uses the "multisign", so the name is correct.



_Code quote:_
```Go
multisign
```
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9r5xD-t2RUp09RNA:-NBRf2483Ra0KJF26IXf:b-gnqvbk) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we can fund it directly from the faucet.
</blockquote></details>

Could you share an example with me?
___
*[`integration-tests/auth/multisig.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAwxJ1wipHgom0NJN:-NBRjWSB2rcgSAc9bPpn:b-psoptp) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L95)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
the new broadcast is in master and can be used
</blockquote></details>

It's possible in other places, so I've update it, but not in this. I need a way to fund the account by address from the genesis fauset account, then I'll just remove that code.
___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBRfAUS-MGHhBYxwfob:b-f5119a) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's refrain from using coredClient in new code we produce.
</blockquote></details>

We will use it anyway, we might call it differently, and mighr refactor, but I'm sure that we will have kind of share client, because most of the tests might need the similar functionality. 
@ysv  @wojtek-coreum  what are you thoughts, should I init new bankClient here or reuse existing?
___
*[`integration-tests/auth/multisig.go` line 106 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBNSd3C_fkH4_o0g7:-NBRfcSpCusn5c6qOJ72:bh9ccgg) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L106)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
Maybe move all account declarations to the start of the function.
</blockquote></details>

Ok, moved.



_Code quote:_
```Go
recipientWallet := testing.RandomWallet()
```
___
*[`integration-tests/auth/multisig.go` line 114 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAr_U3SHOYXl5PX7i:-NBRfpY-47SxbHph8SZj:b-xp7l7x) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L114)):*
> sing 
Updated.
___
*[`integration-tests/auth/multisig.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRCEoM4GtZcgCo5Syo:-NBRhKBNBzsetnhl462c:b-1td1j9) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L115)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Usually everything is set in factory and then txbuilder is created using `txF.BuildUnsignedTx`:
https://github.com/CoreumFoundation/coreum/blob/new-client/pkg/tx2/sign.go#L32

so txBuilder is preconfigure by the factory
</blockquote></details>

Agree. Simplified the code. Now the txF produces the builder.



_Code quote:_
```Go
txBuilder := txConfig.NewTxBuilder()
```
___
*[`integration-tests/auth/multisig.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBbmY3NCZrSNgfEgR:-NBRhRYNDgE6lydQRKH_:bfiwtfh) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L117)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You could use `WithGas` and `WithGasPrices` methods of tx factory, to not compute fee yourself:
https://github.com/CoreumFoundation/coreum/blob/new-client/pkg/tx2/sign.go#L20
https://github.com/CoreumFoundation/coreum/blob/new-client/pkg/tx2/sign.go#L29
</blockquote></details>

Set the values in the txF now. But didn't get about the " to not compute fee yourself". What do you mean?
___
*[`integration-tests/auth/multisig.go` line 125 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRCXt41PWhPO-PmHgn:-NBRhbM30JM4gORrg0Hz:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

sing -> sign
</blockquote></details>

Updated.
___
*[`integration-tests/auth/multisig.go` line 130 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBNmwDVttlmFtyq-J:-NBRheZo7kwE7oIxBYKn:b-srvv5z) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L130)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

isn't it just 0 (first tx)?
</blockquote></details>

Right, for that test in that case is 0.
___
*[`integration-tests/auth/multisig.go` line 137 at r1](https://reviewable.io/reviews/core [...]

2022-09-08 13:24 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 61 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9eba1_ZEYxvzuP08:-NBSESIm1Yn29lipgSf3:bw1mzy0) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The current name seems correct.
</blockquote></details>

Whoa, it is even discussed on stackoverflow: :D

https://ell.stackexchange.com/questions/97306/singular-or-plural-form-before-the-word-set-list
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAtop2wUs2dBZ7roq:-NBSF16n54D_CRj2-Pa7:b-5uygrg) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The cosmos uses the "multisign", so the name is correct.
</blockquote></details>

So please use it everywhere here. You mixed "multisig" and "multisign"
___
*[`integration-tests/auth/multisig.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBbmY3NCZrSNgfEgR:-NBSFK3oDxq-Gwilqufw:b74cz6r) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L117)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Set the values in the txF now. But didn't get about the " to not compute fee yourself". What do you mean?
</blockquote></details>

You multiplied values (gas limit and gas price) yourself to get the fee. txF does it for you if you set both values.
___
*[`integration-tests/auth/multisig.go` line 116 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBSG865310ScTsda-NE:-NBSG865310ScTsda-NF:b-bhz8yd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1c65608cd0f5164e375f39b6de582dfe731ae6ea/integration-tests/auth/multisig.go#L116)):*
> ```Go
> 
> 	// prepare the tx factory to sign with the account seq and number of the multisig account
> 	multisigAccInfo, err := tx.GetAccountInfo(ctx, clientCtx, multisigAddress)
> ```

Could `tx.GetAccountInfo` accept tx factory and return updated tx factory, so no manual action of reassigning values is required?
___
*[`integration-tests/auth/multisig.go` line 125 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBSGJEFC9gk6-2iGVxW:-NBSGJEFC9gk6-2iGVxX:byj74bm) ([raw file](https://github.com/coreumfoundation/coreum/blob/1c65608cd0f5164e375f39b6de582dfe731ae6ea/integration-tests/auth/multisig.go#L125)):*
> ```Go
> 				WithKeybase(kr).
> 				WithTxConfig(clientCtx.TxConfig).
> 				WithFees(sdk.NewCoins(sdk.NewCoin(nativeDenom, initialGasPrice.Mul(sdk.NewInt(int64(bankSendGas))))).String()).
> ```

Use `WithGasPrices` instead so multiplication is done for you under the hood


<!-- Sent from Reviewable.io -->

2022-09-08 13:42 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAwxJ1wipHgom0NJN:-NBSKNzI33CfY3Kgtil3:b-hjc9ul) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L95)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's possible in other places, so I've update it, but not in this. I need a way to fund the account by address from the genesis fauset account, then I'll just remove that code.
</blockquote></details>

I don't know why it cannot happen, you use sign and broadcast which are already available on tx package.


<!-- Sent from Reviewable.io -->

2022-09-09 06:31 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 61 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9eba1_ZEYxvzuP08:-NBVrIShEVK1JzLdE9_8:b6bbh44) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L61)):*
> https://ell.stackexchange.com/questions/97306/singular-or-plural-form-before-the-word-set-list
The stackexchange isn't the source of thrues :-)
But if you you insist, I'll update. 
Done.
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAtop2wUs2dBZ7roq:-NBVrfz96mLIyl8FVQv_:bumym5y) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
> multisign
Already updated.
___
*[`integration-tests/auth/multisig.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAwxJ1wipHgom0NJN:-NBVrlVkB42zU_ZuR_yy:b7y494v) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L95)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't know why it cannot happen, you use sign and broadcast which are already available on tx package.
</blockquote></details>

Because I need to send tx from the Wallet (our type). I can import its private key to the keystote and so on, but we don't do it that way, and won't do it that way in the future as well. That's why better to leave the TODO and refactor it in the way we will use it later.
___
*[`integration-tests/auth/multisig.go` line 117 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRBbmY3NCZrSNgfEgR:-NBVu1oS0as2n5idIvt8:bu5u04j) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L117)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You multiplied values (gas limit and gas price) yourself to get the fee. txF does it for you if you set both values.
</blockquote></details>

Got your point, updated.
___
*[`integration-tests/auth/multisig.go` line 116 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBSG865310ScTsda-NE:-NBVugcyBJOHX0727NB6:b-qrnopa) ([raw file](https://github.com/coreumfoundation/coreum/blob/1c65608cd0f5164e375f39b6de582dfe731ae6ea/integration-tests/auth/multisig.go#L116)):*
> GetAccountInfo
In that cast it woul be SetAccountInfo :-). 
In general it's possible. Butin my case I reuse the "multisigAccSeq" later as well. 
___
*[`integration-tests/auth/multisig.go` line 125 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBSGJEFC9gk6-2iGVxW:-NBVu_U-5lKa3d17KPub:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/1c65608cd0f5164e375f39b6de582dfe731ae6ea/integration-tests/auth/multisig.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Use `WithGasPrices` instead so multiplication is done for you under the hood
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-09-09 06:42 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 61 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBR9eba1_ZEYxvzuP08:-NBVxPmM8ecUhKknAroE:b6ivkbr) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> https://ell.stackexchange.com/questions/97306/singular-or-plural-form-before-the-word-set-list
The stackexchange isn't the source of thrues :-)
But if you you insist, I'll update. 
Done.
</blockquote></details>

But in this case this is true
___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAtop2wUs2dBZ7roq:-NBVydRS0SGsqx77D_QJ:bt04c4p) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> multisign
Already updated.
</blockquote></details>

I still see "multisig" in this comment and in lines above
___
*[`integration-tests/auth/multisig.go` line 65 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVxs6GAZBTw2E8Ry1y:-NBVxs6GAZBTw2E8Ry1z:b-5sowbe) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L65)):*
> ```Go
> 	publicKeySet := make([]cryptotypes.PubKey, 0, len(keyNamesSet))
> 	for _, key := range keyNamesSet {
> 		info := addRandomAccountToKeyring(requireT, key, kr)
> ```

but IIRC we decided yesterday that in this case `t` should be passed to the function, not entire `requireT`
___
*[`integration-tests/auth/multisig.go` line 169 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVyISlAqOBrV7mHygM:-NBVyISlAqOBrV7mHygN:b-hh8n6d) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L169)):*
> ```Go
> }
> 
> func generateRandomMnemonic(requireT *require.Assertions) string {
> ```

Another case where it clashes with #162 . My idea is to wait a day until that PR is merged (let's finish it today) and not introduce another fix for the same problem. @ysv 


<!-- Sent from Reviewable.io -->

2022-09-09 07:38 UTC, miladz68 requested changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`pkg/tx/tx.go` line 34 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBW6rar4RL6Mgvd5K68:-NBW6rar4RL6Mgvd5K69:bme5lxp) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L34)):*
> ```Go
> type Factory = tx.Factory
> 
> // SignTx signs a given tx with a named key. The bytes signed over are canconical.
> ```

canconical -> canonical 
This sentence seems cryptic  `The bytes signed over are canconical`, what does it mean for a byte to be canonical ? :thinking: 
they probably mean it has canonical form, but anyways, there is typo in the sentence :smile: 
___
*[`pkg/tx/tx.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBWA_Ni75F5LKNMhlXp:-NBWA_Ni75F5LKNMhlXq:b-5fllct) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L75)):*
> ```Go
> 
> // BroadcastRawTx broadcast the txBytes using the clientCtx and set BroadcastMode.
> func BroadcastRawTx(ctx context.Context, clientCtx client.Context, txBytes []byte) (*sdk.TxResponse, error) {
> ```

non-blocking
how about `BroadcastBytes` since it not getting any `tx` as input, just `[]byte`.


<!-- Sent from Reviewable.io -->

2022-09-09 08:45 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRAtop2wUs2dBZ7roq:-NBWOznJ5FWknvfrnLIg:b-399x5g) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L73)):*
> multisig
I use the "multisig" only. 
___
*[`integration-tests/auth/multisig.go` line 65 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVxs6GAZBTw2E8Ry1y:-NBWOo5k1byK7PNTKuNr:b6kpx7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L65)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but IIRC we decided yesterday that in this case `t` should be passed to the function, not entire `requireT`
</blockquote></details>

We decided that it's up do dev to decide :-) 
___
*[`pkg/tx/tx.go` line 34 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBW6rar4RL6Mgvd5K68:-NBWPHqo6Cu_Kid4JMrk:bjtf9sr) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L34)):*
> canconical
This comment is just a copy. But I'm ok to update it.
Updated. 
___
*[`pkg/tx/tx.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBWA_Ni75F5LKNMhlXp:-NBWPcC7CPc56kg6huKg:bldm674) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L75)):*
> BroadcastBytes
I for me both are the same in terms of understanding. 


<!-- Sent from Reviewable.io -->

2022-09-09 10:42 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 169 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVyISlAqOBrV7mHygM:-NBWpv-_7ZUYEJ3t8dQJ:bji8mm8) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L169)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Another case where it clashes with #162 . My idea is to wait a day until that PR is merged (let's finish it today) and not introduce another fix for the same problem. @ysv 
</blockquote></details>

This was done before the #162, I just can add TODO.


<!-- Sent from Reviewable.io -->

2022-09-09 10:52 UTC, miladz68 reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`pkg/tx/tx.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBWA_Ni75F5LKNMhlXp:-NBWs5R9-OoY1CrE2-6a:b-3juo6z) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L75)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> BroadcastBytes
I for me both are the same in terms of understanding. 
</blockquote></details>

@ysv @wojtek-coreum 


<!-- Sent from Reviewable.io -->

2022-09-09 12:09 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman and @ysv)

___
*[`pkg/tx/tx.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBWA_Ni75F5LKNMhlXp:-NBX8g_w-I3lO8fkuE8T:b-s20cy3) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L75)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv @wojtek-coreum 
</blockquote></details>

Both names are ok for me


<!-- Sent from Reviewable.io -->

2022-09-09 13:06 UTC, ysv requested changes
Mostly good for me
Just needs to be refactored to use code introduced in #162. Blocking for now

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163#-:-NBXLp7EEB29EcTNycsq:bstldo8)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBXDB7s3V8zXht15jTL:bea7h0s) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We will use it anyway, we might call it differently, and mighr refactor, but I'm sure that we will have kind of share client, because most of the tests might need the similar functionality. 
@ysv  @wojtek-coreum  what are you thoughts, should I init new bankClient here or reuse existing?
</blockquote></details>

I think we should try to use coredClient as less as possible and only in places where it is absolutely necessary to make it removal less painful 
on this exactly place It could be easily removed `banktypes.NewQueryClient(clientCtx)`
___
*[`integration-tests/auth/multisig.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBREeHR0hbxHhDJ3vWz:-NBXLgn8EDaZOodrTDDJ:b-h4dwfe) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L170)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The #162 is in progress, so I can't reuse it.
</blockquote></details>

162 merged so reuse it pls
___
*[`integration-tests/auth/multisig.go` line 169 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVyISlAqOBrV7mHygM:-NBXLiy2EYm8YQWMuL-A:b-h4dwfe) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L169)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This was done before the #162, I just can add TODO.
</blockquote></details>

162 merged so reuse it pls
___
*[`pkg/tx/tx.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBWA_Ni75F5LKNMhlXp:-NBXELSC5iJiUBXDhBee:b48dkjw) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/pkg/tx/tx.go#L75)):*
> BroadcastRawTx

is better 


<!-- Sent from Reviewable.io -->

2022-09-09 13:20 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBXNHUa9fgm88aPQzML:bedyomw) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we should try to use coredClient as less as possible and only in places where it is absolutely necessary to make it removal less painful 
on this exactly place It could be easily removed `banktypes.NewQueryClient(clientCtx)`

</blockquote></details>

Updated, fully removed the usage for the client from the test.



_Code quote:_
```Go
coredClient.BankQueryClient()
```
___
*[`integration-tests/auth/multisig.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBREeHR0hbxHhDJ3vWz:-NBXNw179BPJOFixeRen:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L170)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

162 merged so reuse it pls
</blockquote></details>

Done.
___
*[`integration-tests/auth/multisig.go` line 169 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVyISlAqOBrV7mHygM:-NBXNwpyEgX8dVCSLiLv:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L169)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

162 merged so reuse it pls
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-09 14:06 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBXQ2HX5_qoNdbwjfIc:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated, fully removed the usage for the client from the test.
</blockquote></details>

ok
___
*[`integration-tests/auth/multisig.go` line 26 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBXQEaZ5OKH4ZSWqf9u:-NBXQEaZ5OKH4ZSWqf9v:b-6pk559) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4379b9eedfff5901de48dee661f1a90b2901f7e/integration-tests/auth/multisig.go#L26)):*
> ```Go
> // TestMultisig tests the cosmos-sdk multisig accounts and API.
> func TestMultisig(ctx context.Context, t testing.T, chain testing.Chain) { //nolint:funlen // The test covers step-by step use case, no need split it
> 	faucetWallet := chain.RandomWallet()
> ```

but we already have faucet in chain 
Why do we need a second one ?

As far as I understand you first fund this wallet from chain.Faucet and then send to multisig from this wallet ?
Is it done in purpose ?
___
*[`integration-tests/auth/multisig.go` line 30 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBXPi9dASlBt1_QIyMb:-NBXPi9dASlBt1_QIyMc:bvnlfri) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4379b9eedfff5901de48dee661f1a90b2901f7e/integration-tests/auth/multisig.go#L30)):*
> ```Go
> 	signerOneWallet := chain.RandomWallet()
> 	signerTwoWallet := chain.RandomWallet()
> 	signerThreeWallet := chain.RandomWallet()
> ```

minor
signer1, signer2 .. is going to be more readable
___
*[`integration-tests/auth/multisig.go` line 46 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBXRVfY3u-IQdCGXFPD:-NBXRVfY3u-IQdCGXFPE:bieewed) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4379b9eedfff5901de48dee661f1a90b2901f7e/integration-tests/auth/multisig.go#L46)):*
> ```Go
> 			// Once we start using the sdk types directly this code will be refactored, and multisig account will be funded directly.
> 			Wallet: chain.AccAddressToLegacyWallet(faucetWallet),
> 			Amount: testing.MustNewCoin(t,
> ```

it would be nice if you start using chain.NewCoin instead of testing.MustNewCoin & sdk.NewCoin 


<!-- Sent from Reviewable.io -->

2022-09-09 16:08 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBXjPLGE85dPhZNzxJV:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`integration-tests/auth/multisig.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBREeHR0hbxHhDJ3vWz:-NBXjQup7Zw5pFNII5I3:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L170)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`integration-tests/auth/multisig.go` line 169 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVyISlAqOBrV7mHygM:-NBXjRYa0s5AO1aBMGZq:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L169)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`integration-tests/auth/multisig.go` line 26 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBXQEaZ5OKH4ZSWqf9u:-NBXzu4xDeJCjnx6828b:b-pvbl0z) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4379b9eedfff5901de48dee661f1a90b2901f7e/integration-tests/auth/multisig.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

>  
I can't send to account address from the chain faucet. I need legacy 'wallet'.
</blockquote></details>

oh I see the problem
Can you leave a TODO for me (ysv) 
I will change the flow once Wallet is removed
___
*[`integration-tests/auth/multisig.go` line 46 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBXRVfY3u-IQdCGXFPD:-NBXjINlCjFinloZAfew:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4379b9eedfff5901de48dee661f1a90b2901f7e/integration-tests/auth/multisig.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It returns different type sdk.Coin but I need the types.Coin
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-12 06:08 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/auth/multisig.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBRB8j31MmIjCCUjXaQ:-NBkICh20-MdvkCnZL14:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`integration-tests/auth/multisig.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBREeHR0hbxHhDJ3vWz:-NBkIDLI58Q8WcpPHZN4:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/854d500621c64c70653db8160c3829702d2cd1cc/integration-tests/auth/multisig.go#L170)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`integration-tests/auth/multisig.go` line 169 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBVyISlAqOBrV7mHygM:-NBkIDvv5VLRSAS036_D:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f81d676d7dbce88eb11f071aa8aa94c1bdc0bb01/integration-tests/auth/multisig.go#L169)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`integration-tests/auth/multisig.go` line 26 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/163#-NBXQEaZ5OKH4ZSWqf9u:-NBkIUHJ7FbidEa80Wfd:bbiz4w1) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4379b9eedfff5901de48dee661f1a90b2901f7e/integration-tests/auth/multisig.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

oh I see the problem
Can you leave a TODO for me (ysv) 
I will change the flow once Wallet is removed
</blockquote></details>

I guess the better way to keep it with my nickname, so I'll be able to do it after the refactoring. It's a wierd practice to leave comments with teammates nicknames :-).
Anyways there is already comment to do to, so if you would like to it despite my nickname, you will be able do it. :-)


<!-- Sent from Reviewable.io -->

2022-09-12 06:56 UTC, miladz68 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163#-:-NBkU2vWAHmtMLVJCbnH:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-09-12 09:02 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)



<!-- Sent from Reviewable.io -->

2022-09-12 09:06 UTC, merged