Add governance helpers for the integration tests
CoreumFoundation/coreum pull request #190
Opened 2022-09-21 07:45 UTC by dzmitryhil

2022-09-22 07:24 UTC, wojtek-coreum requested changes
> Reviewed 19 of 19 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 10 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/staking/proposal.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ3XOw7QQi6OKhw-MN:-NCZ3XOw7QQi6OKhw-MO:blaw61g) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/staking/proposal.go#L41)):*
> ```Go
> 	requireT.Equal(govtypes.StatusVotingPeriod, proposal.Status)
> 
> 	// Vote yes from all vote accounts.
> ```

What about previous test where we tested that one vote is not enough?
___
*[`integration-tests/testing/chain.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxY6X5h9-5dtd771P:-NCYxY6YE07XRoidM3J8:bllkvhs) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L26)):*
> ```Go
> 	ClientContext cosmosclient.Context
> 	NetworkConfig app.NetworkConfig
> 	mu            sync.Mutex
> ```

Mutex is the only thing which requires a pointer receiver. So I would prefer to keep value receivers and create a pointer for mutex instead. This is my personal feeling so I'm open to negotiation and opinions of others
___
*[`integration-tests/testing/chain.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxsLh9nbc0vCg8doo:-NCYxMdD8kFGuzPtVd1u:b-xu0rhf) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L34)):*
> ```Go
> 		ClientContext: clientCtx,
> 		NetworkConfig: networkCfg,
> 		mu:            sync.Mutex{},
> ```

if we decide to keep mutex as value, not pointer, then this line is not needed
___
*[`integration-tests/testing/chain.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYzN2C1Oet-xCDpFGV:-NCYzN2DAaFb9ATT9yKr:b-amgybl) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L52)):*
> ```Go
> 
> 	// Store generated mnemonic using account address as UID
> 	if _, err = c.ClientContext.Keyring.NewAccount(keyInfo.GetAddress().String(), mnemonic, "", "", hd.Secp256k1); err != nil {
> ```

You might move mutex locking just above this line, because it is not needed earlier, and parallelism will be improved (maybe not so important but still... :-)).
___
*[`integration-tests/testing/chain.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ-GPa9TFg7GFGdGJD:-NCZ-GPa9TFg7GFGdGJE:b-eo332b) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L97)):*
> ```Go
> func (c *ChainContext) AccAddressToLegacyWallet(accAddr sdk.AccAddress) types.Wallet {
> 	name := accAddr.String()
> 	privKeyHex, err := keyring.NewUnsafe(c.ClientContext.Keyring).UnsafeExportPrivKeyHex(name)
> ```

This line requires mutex, otherwise reading may fail if writing is done in parallel. I recommend using `sync.RWMutex` type so many reads may happen in parallel.
___
*[`integration-tests/testing/chain.go` line 139 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ0J6q5vXZoHgppM3d:-NCZ0J6q5vXZoHgppM3e:b-9z0ejp) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L139)):*
> ```Go
> 		WithClient(rpcClient).
> 		WithKeyring(keyring.NewInMemory()).
> 		WithBroadcastMode(flags.BroadcastBlock)
> ```

How `BroadcastBlock` coexists with our polling mechanism? If retrieving event fails and error is returned inside our `Broadcast` helper (e.g. because of broken conenction), does it recover correctly to polling?
___
*[`integration-tests/testing/gov.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1Vjo4wvXJVboQfAJ:-NCZ1Vjp2kKx8NCzekl9:bh9cs9f) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L32)):*
> ```Go
> 	chainContext *ChainContext,
> 	faucet *Faucet,
> ) (*Governance, error) {
> ```

Do you really need to return pointer?
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCZ1rlwBqZA2uT5zsQ9:b-2vma00) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
> ```Go
> 	}
> 
> 	govParams, err := queryGovParams(ctx, govClient)
> ```

IMO it is a bad design if object constructor executes network operations. Those things should be done in different place (e.g. when network resource is needed for the first time).
Another option is to do networking externally (e.g. in some kind of factory) and pass results to the constructor. It is counter-intuitive to assume that when calling constructor some "heavy" or "time-consuming" operation is done under the hood.
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCZ2gSj7yjgtpJI36gy:bu16hpo) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
> ```Go
> 	proposerInitialBalance := ComputeNeededBalance(
> 		g.chainContext.NetworkConfig.Fee.FeeModel.Params().InitialGasPrice,
> 		uint64(g.chainContext.NetworkConfig.Fee.FeeModel.Params().MaxBlockGas),
> ```

Not sure if this should be done in this PR but maybe it's a good moment to add voting-related messages to deterministic gas so we know here how much gas needs to be declared
___
*[`integration-tests/testing/gov.go` line 24 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ47SSA1kHKVTILJk2:-NCZ47SSA1kHKVTILJk3:b-awwltj) ([raw file](https://github.com/coreumfoundation/coreum/blob/07cb84883cffbb52150e426c6bf9ea4bc321d5b4/integration-tests/testing/gov.go#L24)):*
> ```Go
> 	govClient      govtypes.QueryClient
> 	faucet         *Faucet
> 	votersAccounts []sdk.AccAddress
> ```

votersAccounts -> voterAccounts


<!-- Sent from Reviewable.io -->

2022-09-22 09:46 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 10 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/proposal.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ3XOw7QQi6OKhw-MN:-NCZ7Igu9wIv3B5ivfQH:b-vltggm) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/staking/proposal.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about previous test where we tested that one vote is not enough?
</blockquote></details>

We didn't have it in the master. 
___
*[`integration-tests/testing/chain.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxY6X5h9-5dtd771P:-NCZ7haK-QIcwVIkrA5X:b75qwlz) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Mutex is the only thing which requires a pointer receiver. So I would prefer to keep value receivers and create a pointer for mutex instead. This is my personal feeling so I'm open to negotiation and opinions of others
</blockquote></details>

I would actually prefere to go with the pointers, since we don't need to copy the strcut all the time we pass them. But that's my personal feeling as well. :-)
@ysv @miladz68 @begmaroman  what are your thoughts?
___
*[`integration-tests/testing/chain.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxsLh9nbc0vCg8doo:-NCZ_T7sCP3vyIvODLQy:bsxmfku) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

if we decide to keep mutex as value, not pointer, then this line is not needed
</blockquote></details>

Let's wait for the team's opinion
___
*[`integration-tests/testing/chain.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYzN2C1Oet-xCDpFGV:-NCZYWyw1G8TCOxkKZqF:b-7chrxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You might move mutex locking just above this line, because it is not needed earlier, and parallelism will be improved (maybe not so important but still... :-)).
</blockquote></details>

Agree, Updated.



_Code quote:_
```Go
// Store generated mnemonic using account add
```
___
*[`integration-tests/testing/chain.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ-GPa9TFg7GFGdGJD:-NCZYeYE9Nzm7F6-EZ6X:b-uvz9ab) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This line requires mutex, otherwise reading may fail if writing is done in parallel. I recommend using `sync.RWMutex` type so many reads may happen in parallel.
</blockquote></details>

Agree. Good catch.



_Code quote:_
```Go
 AccAddre
```
___
*[`integration-tests/testing/chain.go` line 139 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ0J6q5vXZoHgppM3d:-NCZYibSAtPyapwjw87W:b-sybgxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L139)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

How `BroadcastBlock` coexists with our polling mechanism? If retrieving event fails and error is returned inside our `Broadcast` helper (e.g. because of broken conenction), does it recover correctly to polling?
</blockquote></details>

This logic was here before, I just moved it. 
But I can unswer: we have out own impl of the flags.BroadcastBlock, in which we use the polling.  
___
*[`integration-tests/testing/gov.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1Vjo4wvXJVboQfAJ:-NCZZ6Si0ERCc9nqnIXL:bkhmr57) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you really need to return pointer?
</blockquote></details>

The same I mention. I would go with the pointers for such "service" structs.
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCZ_26tCM_4_n4zvYnd:b-ksqx1f) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO it is a bad design if object constructor executes network operations. Those things should be done in different place (e.g. when network resource is needed for the first time).
Another option is to do networking externally (e.g. in some kind of factory) and pass results to the constructor. It is counter-intuitive to assume that when calling constructor some "heavy" or "time-consuming" operation is done under the hood.
</blockquote></details>

I understand your point, but in that case, we will create new instance and call .Init() just after, what is the same. In case the team agree with you I can update it.
@ysv @miladz68 @begmaroman 
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCZ7cW74nY7Ovg1Nhi9:bd1rna0) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Not sure if this should be done in this PR but maybe it's a good moment to add voting-related messages to deterministic gas so we know here how much gas needs to be declared
</blockquote></details>

Not for the PR for sure :-) 
___
*[`integration-tests/testing/gov.go` line 24 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ47SSA1kHKVTILJk2:-NCZZ3h2BJZMusby7AJk:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/07cb84883cffbb52150e426c6bf9ea4bc321d5b4/integration-tests/testing/gov.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

votersAccounts -> voterAccounts
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-09-22 10:44 UTC, wojtek-coreum requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ-GPa9TFg7GFGdGJD:-NCZl_rQ0MqFXDsiVg_S:ba1dj1y) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree. Good catch.
</blockquote></details>

What about using `sync.RWMutex`? I'm not insisting on it but could improve parallelism a little bit.
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCZmqL44bwUBj7mjZ2q:b-vls7gl) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I understand your point, but in that case, we will create new instance and call .Init() just after, what is the same. In case the team agree with you I can update it.
@ysv @miladz68 @begmaroman 
</blockquote></details>

Calling `Init` immediately after a constructor is not a good option either, because it means that `Init` will be called in the constructor of `Chain` - which is the same bad design just moved to different place.
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCZm1-JE-9IlFRe-qJ6:b-7kpx0h) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not for the PR for sure :-) 
</blockquote></details>

So please leave TODO in all the places here where `MaxBlockGas` is used


<!-- Sent from Reviewable.io -->

2022-09-22 13:22 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 18 of 19 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ-GPa9TFg7GFGdGJD:-NC_MDnCCsxYMMTR79u4:bfvaflz) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about using `sync.RWMutex`? I'm not insisting on it but could improve parallelism a little bit.
</blockquote></details>

Not sure, that you will feel the difference, but updated :-)



_Code quote:_
```Go
defer c.mu.Unlock()
```
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NC_Kl8L9lADU7enPjzj:b-8noihg) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Calling `Init` immediately after a constructor is not a good option either, because it means that `Init` will be called in the constructor of `Chain` - which is the same bad design just moved to different place.
</blockquote></details>

I didn't get your proposition then.
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NC_KyKl-Mw_TviinHyt:bux55r6) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So please leave TODO in all the places here where `MaxBlockGas` is used
</blockquote></details>

I don't think it's related to that PR as well. If we don't have such task but want it, then we need create such task, that's it.


<!-- Sent from Reviewable.io -->

2022-09-22 13:23 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 18 of 19 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NC_MVHU1ssUSxiUzfNT:b-a4cqtc) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get your proposition then.
</blockquote></details>

What do you propose? 


<!-- Sent from Reviewable.io -->

2022-09-23 07:19 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ-GPa9TFg7GFGdGJD:-NCdBrk07oP4yE7tKcqj:b-f6pp2n) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure, that you will feel the difference, but updated :-)
</blockquote></details>

Probably not :-)
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCdC7HLA3eVtgKX5B31:bi6v0on) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What do you propose? 
</blockquote></details>

IMO the voting accounts should be set here: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/apps.go#L60
where all the balances are known and voting accounts might be set without the magic, and transactions might be added to network's gentxs to delegate their funds to the validators
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCdCdhs3N6YNc4mdI4D:b-63tjw9) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't think it's related to that PR as well. If we don't have such task but want it, then we need create such task, that's it.
</blockquote></details>

@ysv let's create a task about adding gov-related txs to deterministic gas


<!-- Sent from Reviewable.io -->

2022-09-23 09:58 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCdlFPbBIgtZDiCUnHO:b-e6setv) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO the voting accounts should be set here: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/apps.go#L60
where all the balances are known and voting accounts might be set without the magic, and transactions might be added to network's gentxs to delegate their funds to the validators
</blockquote></details>

I don't wont to extend crust's logic, if that logic we can implement here. 
The same example as for me was with the "accounts funding", we moved that logic from the crust to the coreum, same example is here.


<!-- Sent from Reviewable.io -->

2022-09-23 13:14 UTC, ysv requested changes
> Reviewed 15 of 19 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/chain.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxY6X5h9-5dtd771P:-NCeRTmBEHgtlmH674uu:b-vkci63) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would actually prefere to go with the pointers, since we don't need to copy the strcut all the time we pass them. But that's my personal feeling as well. :-)
@ysv @miladz68 @begmaroman  what are your thoughts?
</blockquote></details>

I'm slightly more for non-pointer ChainContext & pointer Mutex here. But don't have strong preference also
___
*[`integration-tests/testing/chain.go` line 23 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeAaqY2SdqmMdiQo4C:-NCeAaqY2SdqmMdiQo4D:byvdvx7) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L23)):*
> ```Go
> 
> // ChainContext is a types used to store the components required for the test chains subcomponents.
> type ChainContext struct {
> ```

what is the logic applied when splitting fields between ChainContext vs Chain ?
___
*[`integration-tests/testing/chain.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeCkql1ggd1GSqhHT2:-NCeCkql1ggd1GSqhHT3:b-98bx1t) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L49)):*
> ```Go
> 	}
> 
> 	c.mu.Lock()
> ```

controversial thing here is that we try to protect ClientContext.Keyring with this mutex and expose it as public field at the same time. As result anyone can access it bypassing our mutex resulting into possible issues.

I would agree with the approach you take here but I think it is partial fix and might still cause issues because we pass Keyring via clientContext & TxFactory to different methods and there cosmos SDK access it e.g in sign method which might again cause issue we already have.

The only way for fully fixing this I see is to define our own keyring which is concurrent safe. Probably we can use it only for testing.

```go
type concurentSafeKeyring struct {
  mu *RWMutex
  keyring keyring.Keyring
}


func (k concurentSafeKeyring) List() ([]Info, error) {
  k.mu.RLock()
  defer k.mu.Unlock()
  
  return k.keyring.List()
}

// ...
```
 
Maybe it is too much of dummy methods but I still see that current solution only partially fixes the issue. LMK if it is not the case
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCePGrD5MOGmrftL_bV:bwp60yk) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't wont to extend crust's logic, if that logic we can implement here. 
The same example as for me was with the "accounts funding", we moved that logic from the crust to the coreum, same example is here.
</blockquote></details>

I partially agree with Wojtek. I also don't like all this magic happening here when initializing struct.
But I don't also want to have this logic to be fully defined in crust.

Do we fully generate genesis from crust & don't have access to it from coreum ?
I also don't like having Gov inside Chain & passed everywhere. I prefer chain to be simple while Gov introduces a lot of functionality into it. What is more we will have more helpers and I don't want to store all of them inside Chain.

I see it designed a bit differently so it just wraps chain with gov helpers or smth similar:

```go
type Gov struct {
  ...
}

func NewGov(chain Chain) Gov {...}

func ExampleUsage(ctx context.Context, t testing.T, chain *testing.Chain) {
  gov := NewGov(chain)
  gov.CreateProposer()
}
```

Let discuss details this on the call
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCe9lLL5sja9cvXGBH4:b3fpm4a) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv let's create a task about adding gov-related txs to deterministic gas
</blockquote></details>

added, this will be done together with gov module "integration" task

but using MaxBlockGas here directly is a bit harsh don't you think so @dzmitryhil ?
I agree with Wojtek it makes sense to me to add this message type into DeterministicGas. 
You may put some roughly estimated value there (e.g 10*BankSend) we will adjust it later it is not problem but logically the code will look correct here. And the exact value is subject for changes which is fine
___
*[`integration-tests/testing/gov.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeOqfW2vY2rxQMMtNc:-NCeOqfW2vY2rxQMMtNd:b-ac80ff) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/gov.go#L41)):*
> ```Go
> 	log.Info("Initialising the governance accounts")
> 
> 	delegationMultiplierDec, err := sdk.NewDecFromStr(delegationMultiplier)
> ```

you can use `MustNewDecFromStr`


<!-- Sent from Reviewable.io -->

2022-09-23 13:32 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxY6X5h9-5dtd771P:-NCeXvHW6Mij4njEh4WU:bam1llw) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm slightly more for non-pointer ChainContext & pointer Mutex here. But don't have strong preference also
</blockquote></details>

Ok, let's discuss. 
___
*[`integration-tests/testing/chain.go` line 23 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeAaqY2SdqmMdiQo4C:-NCeWVAe8crUw5HhB_9-:b-fsb8yu) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the logic applied when splitting fields between ChainContext vs Chain ?
</blockquote></details>

We need the ChainContext for the set-up of the test chain, for example in the Governance helper which is the part of the chain.
___
*[`integration-tests/testing/chain.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeCkql1ggd1GSqhHT2:-NCeWtLx3AYn5BAOYlm7:b-kzhhi3) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

controversial thing here is that we try to protect ClientContext.Keyring with this mutex and expose it as public field at the same time. As result anyone can access it bypassing our mutex resulting into possible issues.

I would agree with the approach you take here but I think it is partial fix and might still cause issues because we pass Keyring via clientContext & TxFactory to different methods and there cosmos SDK access it e.g in sign method which might again cause issue we already have.

The only way for fully fixing this I see is to define our own keyring which is concurrent safe. Probably we can use it only for testing.

```go
type concurentSafeKeyring struct {
  mu *RWMutex
  keyring keyring.Keyring
}


func (k concurentSafeKeyring) List() ([]Info, error) {
  k.mu.RLock()
  defer k.mu.Unlock()
  
  return k.keyring.List()
}

// ...
```
 
Maybe it is too much of dummy methods but I still see that current solution only partially fixes the issue. LMK if it is not the case
</blockquote></details>

Agree, good idea, let's create a separate task for it then, since it's out of scope for the current PR.
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCeXKjEEnQT1v6PrBft:bh4qqte) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I partially agree with Wojtek. I also don't like all this magic happening here when initializing struct.
But I don't also want to have this logic to be fully defined in crust.

Do we fully generate genesis from crust & don't have access to it from coreum ?
I also don't like having Gov inside Chain & passed everywhere. I prefer chain to be simple while Gov introduces a lot of functionality into it. What is more we will have more helpers and I don't want to store all of them inside Chain.

I see it designed a bit differently so it just wraps chain with gov helpers or smth similar:

```go
type Gov struct {
  ...
}

func NewGov(chain Chain) Gov {...}

func ExampleUsage(ctx context.Context, t testing.T, chain *testing.Chain) {
  gov := NewGov(chain)
  gov.CreateProposer()
}
```

Let discuss details this on the call
</blockquote></details>

Ok, but the example you shared is similar to the current but with 2 steps instead of one.
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCeXWzg4PWqDjO70fN4:b-a4gr3a) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

added, this will be done together with gov module "integration" task

but using MaxBlockGas here directly is a bit harsh don't you think so @dzmitryhil ?
I agree with Wojtek it makes sense to me to add this message type into DeterministicGas. 
You may put some roughly estimated value there (e.g 10*BankSend) we will adjust it later it is not problem but logically the code will look correct here. And the exact value is subject for changes which is fine
</blockquote></details>

10*BankSend is the as useless as MaxBlocks :-)

Best option would be to compute it automatically in the "tx", but also it's out of scope for that PR.
___
*[`integration-tests/testing/gov.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeOqfW2vY2rxQMMtNc:-NCeXBhC6lpxBLqEfLeO:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/gov.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you can use `MustNewDecFromStr`
</blockquote></details>

Updated.



_Code quote:_
```Go
sdk.NewDecFromStr(delegationMultiplier)
```


<!-- Sent from Reviewable.io -->

2022-09-26 05:09 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-26 07:36 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 5 of 19 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxY6X5h9-5dtd771P:-NCsi0st5UUtZCAk87HC:bvcf6ww) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, let's discuss. 
</blockquote></details>

Updated to structs without pointer in all places.
___
*[`integration-tests/testing/chain.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxsLh9nbc0vCg8doo:-NCsi1k34UjY2KFcGO10:b-xia0b1) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's wait for the team's opinion
</blockquote></details>

Updated to structs without pointer in all places. 
IMHO the direct initalisaction of that arg is better then, the default which you don't see in the code.
___
*[`integration-tests/testing/chain.go` line 23 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeAaqY2SdqmMdiQo4C:-NCshy143dIR5LwbXswi:bvcf6ww) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We need the ChainContext for the set-up of the test chain, for example in the Governance helper which is the part of the chain.
</blockquote></details>

Updated to structs without pointer in all places.
___
*[`integration-tests/testing/gov.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1Vjo4wvXJVboQfAJ:-NCsiT2u0AsQqn0PLwJV:b-mqhtb4) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The same I mention. I would go with the pointers for such "service" structs.
</blockquote></details>

Updated to structs without pointer in all places. 


<!-- Sent from Reviewable.io -->

2022-09-26 13:42 UTC, wojtek-coreum requested changes
> Reviewed 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCu0vOkCuw8b5EuhdyN:bqeomxd) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, but the example you shared is similar to the current but with 2 steps instead of one.
</blockquote></details>

We already have a staker account for each validator in crust. The only required change is to add some balance there (to cover fees) and pass their private keys to integration tests. What is done here is a complex way of providing simple feature.
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCu19gLB3E4hLs34vuV:b-u7h7sh) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

10*BankSend is the as useless as MaxBlocks :-)

Best option would be to compute it automatically in the "tx", but also it's out of scope for that PR.
</blockquote></details>

But at least it will move the problem to the place where it is easy and obvious to fix


<!-- Sent from Reviewable.io -->

2022-09-26 14:41 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/chain.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxY6X5h9-5dtd771P:-NCuCvOH5ZEqWgbA2t0D:b-4sttta) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated to structs without pointer in all places.
</blockquote></details>

let keep values for now
___
*[`integration-tests/testing/chain.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCYxsLh9nbc0vCg8doo:-NCuCxBu1MNxAc-tegtu:boby4hy) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/chain.go#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated to structs without pointer in all places. 
IMHO the direct initalisaction of that arg is better then, the default which you don't see in the code.
</blockquote></details>

values for now
___
*[`integration-tests/testing/chain.go` line 23 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeAaqY2SdqmMdiQo4C:-NCuBoNpCxCPyyUQD8cv:b6vlnav) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated to structs without pointer in all places.
</blockquote></details>

After you make change for Gov reconsider merging ChainContext & Chain together
___
*[`integration-tests/testing/chain.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeCkql1ggd1GSqhHT2:-NCswZoy6hQQfS7U-eC-:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, good idea, let's create a separate task for it then, since it's out of scope for the current PR.
</blockquote></details>

ok
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-NCuABH_CufiuZM_SyIc:by12rpm) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We already have a staker account for each validator in crust. The only required change is to add some balance there (to cover fees) and pass their private keys to integration tests. What is done here is a complex way of providing simple feature.
</blockquote></details>

1. use validators from crust
2. Gov to be initialized and used inside test where it is needed
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-NCuBTt2ERx_jPxDlds3:b-k55o09) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But at least it will move the problem to the place where it is easy and obvious to fix
</blockquote></details>

Lets just add another value to DeterministicGas.CreateValidatorGas with some quite big value and in one of the next PRs it will be put to proper value
___
*[`integration-tests/testing/gov.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeOqfW2vY2rxQMMtNc:-NCswaV0C8UdQDuHjp19:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/gov.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-28 12:09 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 9 of 24 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 23 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCeAaqY2SdqmMdiQo4C:-ND2wYZOCzO832Ds02L5:b3rvan9) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d091de00024cd555e3c472d09402fdf4011a2b9/integration-tests/testing/chain.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

After you make change for Gov reconsider merging ChainContext & Chain together
</blockquote></details>

Discussed, after to leave the chain Context
___
*[`integration-tests/testing/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ1rlwBqZA2uT5zsQ8:-ND2wj-f9-xzorQVCK93:br0m5ti) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. use validators from crust
2. Gov to be initialized and used inside test where it is needed
</blockquote></details>

Integrated.
___
*[`integration-tests/testing/gov.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NCZ2gSj7yjgtpJI36gx:-ND2wp_i2FarJ4sTEFME:b-qk5x07) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/testing/gov.go#L147)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets just add another value to DeterministicGas.CreateValidatorGas with some quite big value and in one of the next PRs it will be put to proper value
</blockquote></details>

Added the Deterministic values for SubmitProposal and Vote. Didn't get about the "CreateValidatorGas".


<!-- Sent from Reviewable.io -->

2022-09-28 13:17 UTC, ysv requested changes
> Reviewed 6 of 14 files at r6, 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/auth/multisig.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND32Eh5-sNoJtIvOYDd:-ND32Eh5-sNoJtIvOYDe:b-swl5a5) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/auth/multisig.go#L83)):*
> ```Go
> 
> 	clientCtx := chain.ClientContext.
> 		WithFromName(faucetWallet.String()).
> ```

faucetWallet name is confusing with our testing faucet.
Lets use some different name here pls
___
*[`integration-tests/testing/gov.go` line 29 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND37emK2DHKiIZLoUkE:-ND37emK2DHKiIZLoUkF:b-715616) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L29)):*
> ```Go
> func NewGovernance(chainContext ChainContext, voterMnemonics []string) Governance {
> 	voterAccounts := make([]sdk.AccAddress, 0, len(voterMnemonics))
> 	for _, stakerMnemonic := range voterMnemonics {
> ```

staker vs voter can we stick to a single name here ?
___
*[`integration-tests/testing/gov.go` line 55 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND38TZDC4lM_JiWQUvq:-ND38TZDC4lM_JiWQUvr:btoppij) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L55)):*
> ```Go
> 	proposerInitialBalance := ComputeNeededBalance(
> 		initialGasPrice,
> 		NetworkConfig.Fee.DeterministicGas.GovSubmitProposal,
> ```

you can use `chain.GasLimitByMsgs(&gov.SubmitProposalMsg{})` instead
___
*[`integration-tests/testing/gov.go` line 75 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND36sYC8UUuIcGwjFkw:-ND36sYC8UUuIcGwjFkx:b-epa205) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L75)):*
> ```Go
> 
> 	txf := g.chainContext.TxFactory()
> 	txf = txf.WithGas(NetworkConfig.Fee.DeterministicGas.GovSubmitProposal)
> ```

you can use `chain.GasLimitByMsgs(msg)` instead
___
*[`integration-tests/testing/gov.go` line 119 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3EJfbB5koV9WHqO4y:-ND3EJfbB5koV9WHqO4z:bvbtctd) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L119)):*
> ```Go
> 
> 		txf := g.chainContext.TxFactory()
> 		txf = txf.WithGas(g.chainContext.GasLimitByMsgs(msg))
> ```

minor: 
I personally would do this in a single line `txf := g.chainContext.TxFactory.WithGas`
___
*[`pkg/tx/tx.go` line 62 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND34DT64Ce-KR7Mhi_4:-ND34DT64Ce-KR7Mhi_5:btbd97n) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/pkg/tx/tx.go#L62)):*
> ```Go
> 	unsignedTx.SetFeeGranter(clientCtx.GetFeeGranterAddress())
> 
> 	fromName := clientCtx.GetFromName()
> ```

is it done to make it possible to pass one of address/name instead of requiring both ?

if yes then add comment pls 


<!-- Sent from Reviewable.io -->

2022-09-28 13:30 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 22 of 24 files reviewed, 8 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND32Eh5-sNoJtIvOYDd:-ND3Fuaq0fTupeszQtES:belsfu2) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e1b26021922bd504d08797741630ecaa39bb262/integration-tests/auth/multisig.go#L83)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

faucetWallet name is confusing with our testing faucet.
Lets use some different name here pls
</blockquote></details>

But the purpose of it is the same, so we use it as a faucet for the tests. Similar to what we have on the devnet.
___
*[`integration-tests/testing/gov.go` line 29 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND37emK2DHKiIZLoUkE:-ND3GUGW9dFXSHXD1y0V:b-skznj) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

staker vs voter can we stick to a single name here ?
</blockquote></details>

Sure, updated.



_Code quote:_
```Go
voterA
```
___
*[`integration-tests/testing/gov.go` line 55 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND38TZDC4lM_JiWQUvq:-ND3Gjcp4pCMfAllMiSk:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L55)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you can use `chain.GasLimitByMsgs(&gov.SubmitProposalMsg{})` instead
</blockquote></details>

Done.
___
*[`integration-tests/testing/gov.go` line 75 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND36sYC8UUuIcGwjFkw:-ND3H6TLEXzXo-QdNtid:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you can use `chain.GasLimitByMsgs(msg)` instead
</blockquote></details>

Done.



_Code quote:_
```Go
GovSubmitProposal
```
___
*[`integration-tests/testing/gov.go` line 119 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3EJfbB5koV9WHqO4y:-ND3HCcZ6O02HcL8aQFE:bioizhz) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L119)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: 
I personally would do this in a single line `txf := g.chainContext.TxFactory.WithGas`
</blockquote></details>

Right, why not :-)
Updated.



_Code quote:_
```Go
txf := g.chainContext.TxFactory()
```
___
*[`pkg/tx/tx.go` line 62 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND34DT64Ce-KR7Mhi_4:-ND3HHh2E-7IdbUP-gZA:bkmro8i) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/pkg/tx/tx.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it done to make it possible to pass one of address/name instead of requiring both ?

if yes then add comment pls 
</blockquote></details>

Yes.
Added the comment


<!-- Sent from Reviewable.io -->

2022-09-28 13:53 UTC, wojtek-coreum requested changes
> Reviewed 14 of 15 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 14 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/testing/gov.go` line 36 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LnMEDp02_PJBkTkL:-ND3LnMEDp02_PJBkTkM:b9eofio) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L36)):*
> ```Go
> 		chainContext:   chainContext,
> 		stakerAccounts: stakerAccounts,
> 		govClient:      govtypes.NewQueryClient(chainContext.ClientContext),
> ```

Ensure that all the errors returned by the methods of govClient are wrapped by `errors.WithStack`. Same about other errors, which are nto produced by us (if any)
___
*[`integration-tests/testing/gov.go` line 125 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3JYQyC5_ZCSa7Fbzi:-ND3JYQz5FiOxi1Xz1Ia:bplipwx) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L125)):*
> ```Go
> 		res, err := tx.BroadcastTx(
> 			ctx,
> 			clientCtx.
> ```

we have wide monitors :-)
___
*[`integration-tests/testing/gov.go` line 142 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3JufF3Qi4Lq5EXs_4:-ND3JufG31h0HbX1ESyG:bcr94bq) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L142)):*
> ```Go
> 			return err
> 		}
> 		if res.TxResult.Code != 0 {
> ```

`AwaitTx` does this for you already
___
*[`integration-tests/testing/gov.go` line 161 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3KBvN7BK5cF6hx1Fk:-ND3KBvN7BK5cF6hx1Fl:b-xou8u2) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L161)):*
> ```Go
> 	timeout := time.NewTimer(govParams.VotingParams.VotingPeriod + time.Second*10)
> 
> 	ticker := time.NewTicker(time.Millisecond * 250)
> ```

You must call `ticker.Stop()` when it's no longer needed. That's why I prefer `time.After` because it is a fire-and-forget solution
___
*[`integration-tests/testing/gov.go` line 162 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3KjJX1zs1uYNMx9fF:-ND3KjJX1zs1uYNMx9fG:b31dd61) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L162)):*
> ```Go
> 
> 	ticker := time.NewTicker(time.Millisecond * 250)
> 	for range ticker.C {
> ```

I don't understand how `range ticker.C`, `case <-timeout.C:` and `default:` work togher.
___
*[`integration-tests/testing/gov.go` line 184 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LIaQ9L-1M7_olRvg:-ND3LIaQ9L-1M7_olRvh:bbmj6ti) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L184)):*
> ```Go
> 
> // GetVotersAccounts returns the configured voting accounts.
> func (g Governance) GetVotersAccounts() []sdk.AccAddress {
> ```

Is it used anywhere? IMO those accounts should not be exposed
___
*[`integration-tests/testing/gov.go` line 189 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LVqA8yeqhOxL2fGB:-ND3LVqA8yeqhOxL2fGC:b-q5y577) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L189)):*
> ```Go
> 
> func (g Governance) getParams(ctx context.Context) (govtypes.Params, error) {
> 	return queryGovParams(ctx, g.govClient)
> ```

This is the only place where `queryGovParams` is called. Why not to put that code here directly?
___
*[`pkg/tx/tx.go` line 62 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3MkLQEoCdr2W0FtCs:-ND3MkLQEoCdr2W0FtCt:b-pjpp9v) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/pkg/tx/tx.go#L62)):*
> ```Go
> 	unsignedTx.SetFeeGranter(clientCtx.GetFeeGranterAddress())
> 
> 	// in case the name is not provided by that address is, take the name by the address
> ```

remove "is"


<!-- Sent from Reviewable.io -->

2022-09-29 07:31 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 21 of 24 files reviewed, 14 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/gov.go` line 36 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LnMEDp02_PJBkTkL:-ND798sf5PyhdycJKQaO:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ensure that all the errors returned by the methods of govClient are wrapped by `errors.WithStack`. Same about other errors, which are nto produced by us (if any)
</blockquote></details>

Done.
___
*[`integration-tests/testing/gov.go` line 125 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3JYQyC5_ZCSa7Fbzi:-ND75pDG0yD2V-raiy2I:byy2wni) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we have wide monitors :-)
</blockquote></details>

:-) 
Updated.



_Code quote:_
```Go
res, err := tx.BroadcastTx(
```
___
*[`integration-tests/testing/gov.go` line 142 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3JufF3Qi4Lq5EXs_4:-ND75XhL0IWdD4Vyxw4j:b-hfpv0l) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L142)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`AwaitTx` does this for you already
</blockquote></details>

removed



_Code quote:_
```Go
if res.TxResult.Code != 0 {
```
___
*[`integration-tests/testing/gov.go` line 161 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3KBvN7BK5cF6hx1Fk:-ND75wZvBxw4v944jN8f:b-ggsalk) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You must call `ticker.Stop()` when it's no longer needed. That's why I prefer `time.After` because it is a fire-and-forget solution
</blockquote></details>

Actually I didn't tuch this code from the prev PR. 
I've updated it now with `Stop`. With the After I would need to updated the code with the `for`.
___
*[`integration-tests/testing/gov.go` line 162 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3KjJX1zs1uYNMx9fF:-ND77FoBBhQUcUzd3s6u:b-n8m839) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L162)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand how `range ticker.C`, `case <-timeout.C:` and `default:` work togher.
</blockquote></details>

As I mentioned, this is a copy paste from the master code base. :-)
Each tick we check that either the "ctx is canceled", "process timeout" and "state of proposal".
___
*[`integration-tests/testing/gov.go` line 184 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LIaQ9L-1M7_olRvg:-ND775w11fwrWwkay3zZ:b-kmyrq3) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L184)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it used anywhere? IMO those accounts should not be exposed
</blockquote></details>

You might need to get some info about the voters, but I agree to remove it. Once it needed we will add.



_Code quote:_
```Go
GetVotersAccounts() []sdk.AccAddress {
```
___
*[`integration-tests/testing/gov.go` line 189 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LVqA8yeqhOxL2fGB:-ND78IfrEV2sZSMCeCHT:b3b7ejj) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L189)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the only place where `queryGovParams` is called. Why not to put that code here directly?
</blockquote></details>

To make better readability of the caller function
___
*[`pkg/tx/tx.go` line 62 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3MkLQEoCdr2W0FtCs:-ND78UuG3XX2z-_tfoTe:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/pkg/tx/tx.go#L62)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

remove "is"
</blockquote></details>

Done.



_Code quote:_
```Go
 in case the name is not provided by that address is, take the name by the add
```


<!-- Sent from Reviewable.io -->

2022-09-29 08:54 UTC, wojtek-coreum requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/testing/gov.go` line 29 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND37emK2DHKiIZLoUkE:-ND7S1_i7pvwXcnIEUrC:b-ju3kiw) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Sure, updated.
</blockquote></details>

I don't see the change
___
*[`integration-tests/testing/gov.go` line 189 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LVqA8yeqhOxL2fGB:-ND7RGAR45Y6-_wvLKlJ:b-ga7xhe) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L189)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

To make better readability of the caller function
</blockquote></details>

TBH, I don't find it to be more readable. Now I'm two clicks from the logic instead of one (when I follow the calls).


<!-- Sent from Reviewable.io -->

2022-09-29 10:32 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/gov.go` line 29 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND37emK2DHKiIZLoUkE:-ND7mkSZ1ODnorVDpA94:bq0zoyd) ([raw file](https://github.com/coreumfoundation/coreum/blob/997161ca266af2d868d8d33b376ff39699f2bfd5/integration-tests/testing/gov.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see the change
</blockquote></details>

For some reason, this part miseed. Updated. Thanks for the catch.



_Code quote:_
```Go
voterMnemonics
```
___
*[`integration-tests/testing/gov.go` line 189 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LVqA8yeqhOxL2fGB:-ND7nT0s97HVtzN7KRRQ:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L189)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

TBH, I don't find it to be more readable. Now I'm two clicks from the logic instead of one (when I follow the calls).
</blockquote></details>

Updated.



_Code quote:_
```Go
getParams
```


<!-- Sent from Reviewable.io -->

2022-09-29 11:40 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

___
*[`integration-tests/testing/gov.go` line 189 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/190#-ND3LVqA8yeqhOxL2fGB:-ND81rzKDDhnfMB0tcjm:b-ssjv6j) ([raw file](https://github.com/coreumfoundation/coreum/blob/ddc089f4ecf3a43b15f9b44b1a83c5fdf767c66c/integration-tests/testing/gov.go#L189)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

Minor: I thought about moving logic from function to method, not to remove method and call function instead. But both solutions are ok for me so whatever you prefer


<!-- Sent from Reviewable.io -->

2022-09-30 07:38 UTC, wojtek-coreum requested changes
> Reviewed 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 30 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NDCJs1H20O-P962xU-V:-NDCJs1H20O-P962xU-W:b1y752) ([raw file](https://github.com/coreumfoundation/coreum/blob/1eb35a25fffde12fec37fbfc0c23f21902c9965c/integration-tests/auth/multisig.go#L30)):*
> ```Go
> 	faucetWallet := chain.RandomWallet()
> 
> 	signer1KeyInfo, err := chain.ClientContext.Keyring.KeyByAddress(chain.RandomWallet())
> ```

Looks like that it will be a common usecase. Could you modify `RandomWallet` to return keyInfo instead of address only?


<!-- Sent from Reviewable.io -->

2022-09-30 07:42 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 30 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NDCJs1H20O-P962xU-V:-NDCL1aT0jKop8vAAQnU:bv25wfc) ([raw file](https://github.com/coreumfoundation/coreum/blob/1eb35a25fffde12fec37fbfc0c23f21902c9965c/integration-tests/auth/multisig.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Looks like that it will be a common usecase. Could you modify `RandomWallet` to return keyInfo instead of address only?
</blockquote></details>

Not in the scope of that PR. I have a task to remove the custom types, there I'll see how to do it properly.


<!-- Sent from Reviewable.io -->

2022-09-30 07:46 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 30 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NDCJs1H20O-P962xU-V:-NDCLpTB4LfnQE3QWw_u:btm4zn4) ([raw file](https://github.com/coreumfoundation/coreum/blob/1eb35a25fffde12fec37fbfc0c23f21902c9965c/integration-tests/auth/multisig.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not in the scope of that PR. I have a task to remove the custom types, there I'll see how to do it properly.
</blockquote></details>

`chain.RandomWallet` does not use custom types. It returns `sdk.AccAddress` now but internally it creates an entry in the keyring which means keyInfo is available there instantly. It means that we have keyInfo, return only AccAddress just to get full info from keyring again. Let's simplify it.


<!-- Sent from Reviewable.io -->

2022-09-30 07:59 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 30 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NDCJs1H20O-P962xU-V:-NDCOcPc6LqV_B3pXrFG:bs03lvq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1eb35a25fffde12fec37fbfc0c23f21902c9965c/integration-tests/auth/multisig.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`chain.RandomWallet` does not use custom types. It returns `sdk.AccAddress` now but internally it creates an entry in the keyring which means keyInfo is available there instantly. It means that we have keyInfo, return only AccAddress just to get full info from keyring again. Let's simplify it.
</blockquote></details>

I got it, but I'll have to update a lot of tests in that case, which are not relevant to gov, that's why such changes better to do separately. That test I had to update because I had to start importing the staker menemonics, and had to change the import strategy. I'll do the proposed changes but not in that PR.


<!-- Sent from Reviewable.io -->

2022-09-30 08:03 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 30 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NDCJs1H20O-P962xU-V:-NDCPv7J0xe9TlZpEe53:b269ixv) ([raw file](https://github.com/coreumfoundation/coreum/blob/1eb35a25fffde12fec37fbfc0c23f21902c9965c/integration-tests/auth/multisig.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I got it, but I'll have to update a lot of tests in that case, which are not relevant to gov, that's why such changes better to do separately. That test I had to update because I had to start importing the staker menemonics, and had to change the import strategy. I'll do the proposed changes but not in that PR.
</blockquote></details>

Please leave a TODO in `chain.RandomWallet` to say that it should return keyInfo


<!-- Sent from Reviewable.io -->

2022-09-30 08:17 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/multisig.go` line 30 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/190#-NDCJs1H20O-P962xU-V:-NDCSo3r04BRHABnu6Zs:b-xz7u9t) ([raw file](https://github.com/coreumfoundation/coreum/blob/1eb35a25fffde12fec37fbfc0c23f21902c9965c/integration-tests/auth/multisig.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please leave a TODO in `chain.RandomWallet` to say that it should return keyInfo
</blockquote></details>

Ok. Added. 


<!-- Sent from Reviewable.io -->

2022-09-30 08:31 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-30 08:34 UTC, merged