Add integration tests for staking module
CoreumFoundation/coreum pull request #200
Opened 2022-09-27 11:06 UTC by begmaroman

2022-09-28 13:21 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/index.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3CWNG7ldbfLxoCgPj:-ND3CWNG7ldbfLxoCgPk:b-xwzock) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/index.go#L18)):*
> ```Go
> 
> 	// Add gov module tests
> 	testSet.SingleChain = append(testSet.SingleChain, gov.SingleChainTests()...)
> ```

It's a bad idea to do it right now, since we wanted to migrate to the test sites instead of the custom test framework.
That would help to run the tests independently.
___
*[`integration-tests/index.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3CofD5gt8InPYDS2x:-ND3CofD5gt8InPYDS2y:bpkyuo2) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/index.go#L41)):*
> ```Go
> 	// with a single one running 200 of them.
> 	for i := 0; i < 10; i++ {
> 		testSet.SingleChain = append(testSet.SingleChain, bank.TestTransferMaximumGas(20))
> ```

The code woun't compile. 
___
*[`integration-tests/staking/create_validator.go` line 27 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3D0fV685kz_EynOCX:-ND3D0fV685kz_EynOCY:bqqj8yl) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/create_validator.go#L27)):*
> ```Go
> 
> 	// Create random validator wallet
> 	validator := testing.RandomWallet()
> ```

This method is depricated, check the "TestCoreTransfer" as an example of the test.
___
*[`integration-tests/staking/create_validator.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3DIEqBrlMNp-8i3wI:-ND3DIEqBrlMNp-8i3wJ:b-j5j87p) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/create_validator.go#L36)):*
> ```Go
> 
> 	// Create validator
> 	txBytes, err := chain.Client.PrepareTxCreateValidator(ctx, client.TxCreateValidatorInput{
> ```

Don't use the "Client" it's depricated and will be remove soon (same for other palces).
___
*[`integration-tests/staking/create_validator.go` line 54 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3DWIU58JHcmMY__0H:-ND3DWIU58JHcmMY__0I:b-u4rj0c) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/create_validator.go#L54)):*
> ```Go
> 
> 	// Make sure validator has been created
> 	validatorModel, err := chain.Client.GetValidator(ctx, validatorAddr)
> ```

What is the validators status? 
___
*[`integration-tests/staking/delegate.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3E1sa8bA18ELiOy_X:-ND3E1sa8bA18ELiOy_Y:bkbiydn) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/delegate.go#L15)):*
> ```Go
> 
> // TestDelegate checks that delegation works correctly
> func TestDelegate(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

Why do you need the delgate in case it's covered in the undelegate?
___
*[`integration-tests/staking/undelegate.go` line 20 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3E8fD785aSRq83yi-:-ND3E8fD785aSRq83yi0:burt4zo) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L20)):*
> ```Go
> 	delegatorInitialBalance := testing.ComputeNeededBalance(
> 		chain.NetworkConfig.Fee.FeeModel.Params().InitialGasPrice,
> 		uint64(chain.NetworkConfig.Fee.FeeModel.Params().MaxBlockGas),
> ```

@ysv what we do with the staking, do we want to update the Deterministic model as well ?
___
*[`integration-tests/staking/undelegate.go` line 43 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3EClp3w8V-BldZG1Y:-ND3EClp3w8V-BldZG1Z:b-4aynso) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L43)):*
> ```Go
> 	// Delegate coins
> 	txBytes, err := chain.Client.PrepareTxSubmitDelegation(ctx, client.TxSubmitDelegationInput{
> 		Base: tx.BaseInput{
> ```

Base input is deprecated and will be remove soon
___
*[`integration-tests/staking/undelegate.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3FUR96Z0sclIBihnN:-ND3FUR96Z0sclIBihnO:b-5evyj5) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L59)):*
> ```Go
> 	validator, err := chain.Client.GetValidator(ctx, valAddress)
> 	require.NoError(t, err)
> 	require.Equal(t, validators[0].Tokens.Add(delegateAmount), validator.Tokens)
> ```

You can get the delegation of the delegator to the validator and check that it exists
___
*[`integration-tests/staking/undelegate.go` line 82 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3Ew3cAZUlh_AwmZOT:-ND3Ew3cAZUlh_AwmZOU:b-h3wstp) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L82)):*
> ```Go
> 
> 	// Make sure coins have been undelegated
> 	validator, err = chain.Client.GetValidator(ctx, valAddress)
> ```

You need to check the "delegator" balance first of all
___
*[`integration-tests/staking/undelegate.go` line 84 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3F6il-wmcCIl_YfXU:-ND3F6il-wmcCIl_YfXV:bjvjubp) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L84)):*
> ```Go
> 	validator, err = chain.Client.GetValidator(ctx, valAddress)
> 	require.NoError(t, err)
> 	require.Equal(t, validators[0].Tokens, validator.Tokens)
> ```

I don't understand what you check here :-)
___
*[`pkg/client/client.go` line 271 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3EVmq7YZvbiTo0hwL:-ND3EVmq7YZvbiTo0hwM:bmexezo) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/pkg/client/client.go#L271)):*
> ```Go
> func (c Client) PrepareTxBankSend(ctx context.Context, input TxBankSendInput) ([]byte, error) {
> 	fromAddress, err := sdk.AccAddressFromBech32(input.Sender.Key.Address())
> 	if err != nil {
> ```

This package is depricated and will be removed soon, don't update it and don't use it


<!-- Sent from Reviewable.io -->

2022-09-28 13:31 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/index.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3CWNG7ldbfLxoCgPj:-ND3H_zk6eYeQTPFwkC4:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/index.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's a bad idea to do it right now, since we wanted to migrate to the test sites instead of the custom test framework.
That would help to run the tests independently.
</blockquote></details>

Done
___
*[`integration-tests/index.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3CofD5gt8InPYDS2x:-ND3H_AkALt0qwJgnocU:b-886gsx) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/index.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The code woun't compile. 
</blockquote></details>

Fixed
___
*[`integration-tests/staking/undelegate.go` line 84 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3F6il-wmcCIl_YfXU:-ND3HkKl0X4YAN6YNo7A:bzh1hk8) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't understand what you check here :-)
</blockquote></details>

I check that initial balance of the validator is the same as it is after undelegating 


<!-- Sent from Reviewable.io -->

2022-09-28 13:48 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 27 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3D0fV685kz_EynOCX:-ND3Is9o2OKQnNU-SA1f:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/create_validator.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This method is depricated, check the "TestCoreTransfer" as an example of the test.
</blockquote></details>

Done
___
*[`integration-tests/staking/create_validator.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3DIEqBrlMNp-8i3wI:-ND3LgYw4HAo-vebS4UW:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/create_validator.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't use the "Client" it's depricated and will be remove soon (same for other palces).
</blockquote></details>

Done
___
*[`integration-tests/staking/delegate.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3E1sa8bA18ELiOy_X:-ND3Iy-f6EXTj_zllvNz:b62kt32) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/delegate.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need the delgate in case it's covered in the undelegate?
</blockquote></details>

Do you suggest combining it within one test? 
___
*[`integration-tests/staking/undelegate.go` line 43 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3EClp3w8V-BldZG1Y:-ND3Lepc-G7Qw2gWjB35:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Base input is deprecated and will be remove soon
</blockquote></details>

Done
___
*[`pkg/client/client.go` line 271 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3EVmq7YZvbiTo0hwL:-ND3Lcu5-hV0SotM8RDD:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/pkg/client/client.go#L271)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This package is depricated and will be removed soon, don't update it and don't use it
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-28 14:16 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 54 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3DWIU58JHcmMY__0H:-ND3R7ipEek812FHIkWg:b-hlv2ot) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/create_validator.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the validators status? 
</blockquote></details>

Added check
___
*[`integration-tests/staking/undelegate.go` line 82 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3Ew3cAZUlh_AwmZOT:-ND3RxRa-UTAPv0DAdV_:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You need to check the "delegator" balance first of all
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-29 08:49 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/delegate.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3E1sa8bA18ELiOy_X:-ND7QWjH2bbjDKRHnfgh:bb77ufg) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/delegate.go#L15)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

Do you suggest combining it within one test? 
</blockquote></details>

Yes.
___
*[`integration-tests/staking/delegate.go` line 37 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7OOcL5W4zikodMGNg:-ND7OOcL5W4zikodMGNh:b9owdhr) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/delegate.go#L37)):*
> ```Go
> 
> 	// Fetch existing validator
> 	validators, err := chain.Client.GetValidators(ctx)
> ```

I see you still use the "Client" don't use it at all in any of your tests
___
*[`integration-tests/staking/undelegate.go` line 85 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7PKMu-brgnobarGDL:-ND7PKMu-brgnobarGDM:bylpt8k) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L85)):*
> ```Go
> 	unbondingTime, err := time.ParseDuration(chain.NetworkConfig.StakingConfig.UnbondingTime)
> 	require.NoError(t, err)
> 	time.Sleep(unbondingTime)
> ```

it's unsafe to sleep exact unbonding Time time, since the block might be not completed and the time of the check. I would recommend to either add +2 sec or go with the await/retry approach.
___
*[`integration-tests/staking/undelegate.go` line 87 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7OnrKAhQhMoZ_GHEk:-ND7OnrKAhQhMoZ_GHEl:bc7nd4b) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L87)):*
> ```Go
> 	time.Sleep(unbondingTime)
> 
> 	// Check delegator address
> ```

address? (same comment related to other similar comment it the code)
___
*[`pkg/client/client.go` line 271 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3EVmq7YZvbiTo0hwL:-ND7Q9dq73T3RCnEZUq5:b-4t6olv) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/pkg/client/client.go#L271)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

Done
</blockquote></details>

But I still se the changes in that package.
___
*[`pkg/config/deterministic_gas.go` line 17 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7QYbR6ebjmbhdomG7:-ND7QYbR6ebjmbhdomG8:bbxub6f) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/pkg/config/deterministic_gas.go#L17)):*
> ```Go
> 		FreeSignatures:  1,
> 		BankSend:        30000,
> 		Delegate:        51000,
> ```

Add Prefix to all your types: StakingDelegate, StakingUndelegate, StakingCreateValidator.
And add the new task in the clickup to add tests which test the Gas for those messages


<!-- Sent from Reviewable.io -->

2022-09-29 09:05 UTC, wojtek-coreum requested changes
> Reviewed 1 of 2 files at r2, 1 of 2 files at r4, 7 of 7 files at r6, 1 of 4 files at r7, 2 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 18 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7TBv65uUG9eryMmm_:-ND7TBv65uUG9eryMmma:bixr282) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/create_validator.go#L18)):*
> ```Go
> 
> // TestCreateValidator checks that validator creation works correctly
> func TestCreateValidator(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

Please remove validator at the end of the test
___
*[`integration-tests/staking/undelegate.go` line 43 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7TrMDDhwc_512ps8V:-ND7TrMDDhwc_512ps8W:b-oauvmy) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L43)):*
> ```Go
> 	require.NotEmpty(t, validators)
> 
> 	valAddress, err := sdk.ValAddressFromBech32(validators[0].OperatorAddress)
> ```

Please ensure that you take one of the "main" validators, not the one you create in another test. That validator will be removed (as I suggested in another comment) so it might happen that you try to stake validator which doesn't exist anymore.
___
*[`integration-tests/staking/undelegate.go` line 85 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7PKMu-brgnobarGDL:-ND7UGy9AMes9WT4ueAa:b-2wpl03) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

it's unsafe to sleep exact unbonding Time time, since the block might be not completed and the time of the check. I would recommend to either add +2 sec or go with the await/retry approach.
</blockquote></details>

retry is the way to go, depending on `time.Sleep`  in tests is a bad design
___
*[`pkg/config/genesis/genesis.tmpl.json` line 189 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7ScBv9-l5-n9j8dPs:-ND7ScBwBaM9y8n5E1_t:b-b1g2q7) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/pkg/config/genesis/genesis.tmpl.json#L189)):*
> ```JSON
>       "params": {
>         "unbonding_time": "{{ .Staking.UnbondingTime }}",
>         "max_validators": 32,
> ```

Maybe it should go to `NetworkConfig`?


<!-- Sent from Reviewable.io -->

2022-09-29 17:19 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 9 of 14 files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/delegate.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3E1sa8bA18ELiOy_X:-ND9FIq2AtjXztbwijm3:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/delegate.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done
___
*[`pkg/client/client.go` line 271 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3EVmq7YZvbiTo0hwL:-ND9FLhhB68rRTOKpsZ0:bwvyox4) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/pkg/client/client.go#L271)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But I still se the changes in that package.
</blockquote></details>

Reverted
___
*[`pkg/config/deterministic_gas.go` line 17 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7QYbR6ebjmbhdomG7:-ND9FO4s7IkzlOOC8orw:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/pkg/config/deterministic_gas.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Add Prefix to all your types: StakingDelegate, StakingUndelegate, StakingCreateValidator.
And add the new task in the clickup to add tests which test the Gas for those messages
</blockquote></details>

Done
___
*[`pkg/config/genesis/genesis.tmpl.json` line 189 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7ScBv9-l5-n9j8dPs:-ND9FPGP6tpJoG7rVuUJ:b-cg1vf6) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/pkg/config/genesis/genesis.tmpl.json#L189)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe it should go to `NetworkConfig`?
</blockquote></details>

Is it really configurable per network? Seems like we are not going to change it much 
___
*[`integration-tests/staking/undelegate.go` line 87 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7OnrKAhQhMoZ_GHEk:-ND9FZET2VAHLHWuMUMn:b-886gsx) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

address? (same comment related to other similar comment it the code)
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2022-09-30 07:43 UTC, wojtek-coreum requested changes
> Reviewed 3 of 5 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/delegate.go` line 47 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDCL7tTAhczucRDNMFM:-NDCL7tTAhczucRDNMFN:b-oauvmy) ([raw file](https://github.com/coreumfoundation/coreum/blob/29bad8c76125d5de4c98b95e768e59343e7156e1/integration-tests/staking/delegate.go#L47)):*
> ```Go
> 	require.NotEmpty(t, validatorsResp.Validators)
> 
> 	valAddress, err := sdk.ValAddressFromBech32(validatorsResp.Validators[0].OperatorAddress)
> ```

Please ensure that you take one of the "main" validators, not the one you create in another test. That validator will be removed (as I suggested in another comment) so it might happen that you try to stake validator which doesn't exist anymore.


<!-- Sent from Reviewable.io -->

2022-09-30 07:43 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 11 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 189 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7ScBv9-l5-n9j8dPs:-NDCLOLd7xysBK-G7qSW:b-yu56ns) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/pkg/config/genesis/genesis.tmpl.json#L189)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

Is it really configurable per network? Seems like we are not going to change it much 
</blockquote></details>

I don't know. But I would prefer to keep everything which is not a default value there


<!-- Sent from Reviewable.io -->

2022-09-30 08:39 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-30 09:04 UTC, wojtek-coreum reviewed
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-30 09:48 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 11 of 14 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 18 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7TBv65uUG9eryMmm_:-NDCizUxADmBArhu5qag:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/create_validator.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please remove validator at the end of the test
</blockquote></details>

Done
___
*[`integration-tests/staking/delegate.go` line 37 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7OOcL5W4zikodMGNg:-NDCYzEF14WVRFGIqTTU:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/delegate.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see you still use the "Client" don't use it at all in any of your tests
</blockquote></details>

Done
___
*[`integration-tests/staking/undelegate.go` line 43 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7TrMDDhwc_512ps8V:-NDCmOVn6y7mfifnI0YN:ba4o5rf) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please ensure that you take one of the "main" validators, not the one you create in another test. That validator will be removed (as I suggested in another comment) so it might happen that you try to stake validator which doesn't exist anymore.
</blockquote></details>

Crust generates random validator addresses every time. Is there any right way to check if the validator is "main" or not? 
___
*[`pkg/config/genesis/genesis.tmpl.json` line 189 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7ScBv9-l5-n9j8dPs:-NDCmsWP5QRq8ltKTBfJ:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/pkg/config/genesis/genesis.tmpl.json#L189)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't know. But I would prefer to keep everything which is not a default value there
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-30 11:45 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/undelegate.go` line 85 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7PKMu-brgnobarGDL:-NDDCc0Z4tRXbMIE3qYC:b-tvpfcg) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

retry is the way to go, depending on `time.Sleep`  in tests is a bad design
</blockquote></details>

It would look overcomplicated in this particular case. I think sleeping (unbonding_time + 2 seconds) is good enough for this case. 


<!-- Sent from Reviewable.io -->

2022-09-30 12:38 UTC, wojtek-coreum reviewed
> Reviewed 2 of 3 files at r15, 1 of 1 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`integration-tests/staking/undelegate.go` line 43 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7TrMDDhwc_512ps8V:-NDDO_zM4OvlrNU6wcNP:b-367ciw) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L43)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

Crust generates random validator addresses every time. Is there any right way to check if the validator is "main" or not? 
</blockquote></details>

Maybe modify crust to set some specific moniker
___
*[`integration-tests/staking/undelegate.go` line 85 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7PKMu-brgnobarGDL:-NDDOWpSAZgg40hTgh2q:b-5bxh7q) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L85)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

It would look overcomplicated in this particular case. I think sleeping (unbonding_time + 2 seconds) is good enough for this case. 
</blockquote></details>

I disagree


<!-- Sent from Reviewable.io -->

2022-09-30 12:53 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/undelegate.go` line 20 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3E8fD785aSRq83yi-:-NDDS9sJAj3CX9DEGjV_:bqmjwcl) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv what we do with the staking, do we want to update the Deterministic model as well ?
</blockquote></details>

Added 
___
*[`integration-tests/staking/undelegate.go` line 85 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND7PKMu-brgnobarGDL:-NDDRaLX-_68rYzV1Eay:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/3823bc6009d0c8bf7c5e7e2f378b62cdd54b8fbe/integration-tests/staking/undelegate.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I disagree
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-30 12:55 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 48 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDDSAlY1bNsloUU1kks:-NDDSAlZB1SqJX2_AJrj:b4jc118) ([raw file](https://github.com/coreumfoundation/coreum/blob/c35743eafc1cd94fd6718c49e6e09497bd9556d4/integration-tests/staking/create_validator.go#L48)):*
> ```Go
> 		stakingtypes.NewDescription("a", "b", "c", "d", "e"),
> 		stakingtypes.NewCommissionRates(sdk.ZeroDec(), sdk.ZeroDec(), sdk.ZeroDec()),
> 		sdk.NewInt(1),
> ```

Please fund it enough so validator has at least 1 voting power (so you need to stake at least 1million)
___
*[`integration-tests/staking/create_validator.go` line 66 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDDSPrj3-NiEYTfSbeV:-NDDSPrj3-NiEYTfSbeW:b-hh4hdc) ([raw file](https://github.com/coreumfoundation/coreum/blob/c35743eafc1cd94fd6718c49e6e09497bd9556d4/integration-tests/staking/create_validator.go#L66)):*
> ```Go
> 	})
> 	require.NoError(t, err)
> 	require.Equal(t, validatorAmount, resp.Validator.Tokens)
> ```

and here, verify the voting power


<!-- Sent from Reviewable.io -->

2022-09-30 13:08 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 48 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDDSAlY1bNsloUU1kks:-NDDVkUXB2tvdZReEkbA:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/c35743eafc1cd94fd6718c49e6e09497bd9556d4/integration-tests/staking/create_validator.go#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please fund it enough so validator has at least 1 voting power (so you need to stake at least 1million)
</blockquote></details>

Done
___
*[`integration-tests/staking/create_validator.go` line 66 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDDSPrj3-NiEYTfSbeV:-NDDVV5o6S7ADvuWm9uI:b-o2z0sl) ([raw file](https://github.com/coreumfoundation/coreum/blob/c35743eafc1cd94fd6718c49e6e09497bd9556d4/integration-tests/staking/create_validator.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

and here, verify the voting power
</blockquote></details>

What is the correct way to verify the voting power in cosmos? Don't see such parameters in the Validator object 


<!-- Sent from Reviewable.io -->

2022-10-03 06:37 UTC, wojtek-coreum requested changes
> Reviewed 1 of 2 files at r21, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 66 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDDSPrj3-NiEYTfSbeV:-NDRXWYE8gTQX0KFJUHF:b6mbduc) ([raw file](https://github.com/coreumfoundation/coreum/blob/c35743eafc1cd94fd6718c49e6e09497bd9556d4/integration-tests/staking/create_validator.go#L66)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

What is the correct way to verify the voting power in cosmos? Don't see such parameters in the Validator object 
</blockquote></details>

I don't know if there is an on-chain way of doing this. But validator might be queried:

```
[wojciech@coreum ~]$ curl http://localhost:26657/status
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "8",
        "block": "11",
        "app": "0"
      },
      "id": "41e3ba4a2547f1a9c6323c11783a444574a6d2cc",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "coreum-devnet-1",
      "version": "0.34.19",
      "channels": "40202122233038606100",
      "moniker": "coredev-00",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "352ECCE47DA68D4D19175499FE0038EAB30102A88263C5A2DB85130AF3F1B7CD",
      "latest_app_hash": "605A6A858085B87E63A62FF377C467B3195A761AA3BD183CEBB7D0934365CEDB",
      "latest_block_height": "117",
      "latest_block_time": "2022-10-03T06:30:02.23712885Z",
      "earliest_block_hash": "D334793890C19CFD740AE437946AEEFAA5DA6E3A1113009BE3E85DD1702E4871",
      "earliest_app_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
      "earliest_block_height": "1",
      "earliest_block_time": "2022-10-03T06:26:26Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "2A7E6298D2BBAC1CC5F1B817D1FD6EC62121284F",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "cWS8xNGI6rqmNOaagDJvF+VEqjGjdz71X/GaYUAwjAA="
      },
      "voting_power": "1000" <----------------------
    }
  }
}
```

but obviously you are not starting a validator here.
In the comment inside protobuf they say: `Voting power can be calculated as total bonded shares
// multiplied by exchange rate`. So looks like it is not reported separately. Ignore my comment then.
___
*[`integration-tests/staking/create_validator.go` line 27 at r24](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDRYS1f8u_K00Zpa6R0:-NDRYS1g-uaj6jU1W85_:b-jewi13) ([raw file](https://github.com/coreumfoundation/coreum/blob/95e0bebe48c3ea81d8acda81e1ec4471c2849f5f/integration-tests/staking/create_validator.go#L27)):*
> ```Go
> 		1,
> 		validatorAmount,
> 	).Add(testing.ComputeNeededBalance(
> ```

What's the additional balance for?


<!-- Sent from Reviewable.io -->

2022-10-03 12:29 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/undelegate.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/200#-ND3FUR96Z0sclIBihnN:-NDSobJ_9jQxoCS6Lf8a:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/75de12e19eaf333f4cbafaceaeafb180e21837a5/integration-tests/staking/undelegate.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can get the delegation of the delegator to the validator and check that it exists
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-10-03 12:41 UTC, begmaroman reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/create_validator.go` line 66 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/200#-NDDSPrj3-NiEYTfSbeV:-NDSrL3dDPhLbJV6PvDB:b32w1t) ([raw file](https://github.com/coreumfoundation/coreum/blob/c35743eafc1cd94fd6718c49e6e09497bd9556d4/integration-tests/staking/create_validator.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't know if there is an on-chain way of doing this. But validator might be queried:

```
[wojciech@coreum ~]$ curl http://localhost:26657/status
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "8",
        "block": "11",
        "app": "0"
      },
      "id": "41e3ba4a2547f1a9c6323c11783a444574a6d2cc",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "coreum-devnet-1",
      "version": "0.34.19",
      "channels": "40202122233038606100",
      "moniker": "coredev-00",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "352ECCE47DA68D4D19175499FE0038EAB30102A88263C5A2DB85130AF3F1B7CD",
      "latest_app_hash": "605A6A858085B87E63A62FF377C467B3195A761AA3BD183CEBB7D0934365CEDB",
      "latest_block_height": "117",
      "latest_block_time": "2022-10-03T06:30:02.23712885Z",
      "earliest_block_hash": "D334793890C19CFD740AE437946AEEFAA5DA6E3A1113009BE3E85DD1702E4871",
      "earliest_app_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
      "earliest_block_height": "1",
      "earliest_block_time": "2022-10-03T06:26:26Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "2A7E6298D2BBAC1CC5F1B817D1FD6EC62121284F",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "cWS8xNGI6rqmNOaagDJvF+VEqjGjdz71X/GaYUAwjAA="
      },
      "voting_power": "1000" <----------------------
    }
  }
}
```

but obviously you are not starting a validator here.
In the comment inside protobuf they say: `Voting power can be calculated as total bonded shares
// multiplied by exchange rate`. So looks like it is not reported separately. Ignore my comment then.
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2022-10-03 14:25 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-10-04 06:26 UTC, wojtek-coreum approved these changes
> Reviewed 2 of 4 files at r25, 1 of 1 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2022-10-04 08:29 UTC, merged