FT Asset basic issuance
CoreumFoundation/coreum pull request #214
Opened 2022-10-06 09:02 UTC by dzmitryhil

* TX to issue FT asset
* Query to get FT asset
* FT asset minting and metadata registration
* Basing issuance integration test
* Deterministic gas for the asset issuance TX

2022-10-06 13:48 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 17 of 31 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhQ-XY124ibP3LB8e-:-NDhXnRf1tl5o0dL70J3:besmsh7) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/pkg/config/deterministic_gas.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Was it decided somehow? Now the cost is the same as the cost of vote. Shouldn't it be more expensive?
</blockquote></details>

It was the cost of the initial test, anyway, it will be updated since the current values will be extended with the new implementation part.
___
*[`proto/coreum/asset/v1/asset.proto` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRJpu-aTMH3d4hBRS:-NDhY5MVEFMWvf4qgtey:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

corresponds to
</blockquote></details>

Done.



_Code quote:_
```protobuf
 denom_name is the name of bank denom which corresponds the asset with the provided precision
```
___
*[`proto/coreum/asset/v1/asset.proto` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhROUM9s3FfO5VYgKn:-NDhY5brCafh5ZGTAKoe:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

corresponds to
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/asset.proto` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRk2fAaO_XOjqGEGD:-NDhY7QIBU6Jz405HjpI:b-i89qqy) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

could you elaborate?
</blockquote></details>

The code field name was taken from the doc, this might be BTC, ur USDT or what ever.
___
*[`proto/coreum/asset/v1/asset.proto` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRrpT-mOmspsSJs9M:-NDhYICmBJCqIFEXZXcs:biwkgzo) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L54)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would keep a string, it should be some more or less random string with a checksum, to prevent human errors. Otherwise it might be too easy to operate on wrong coin if someone manages many of them
</blockquote></details>

The randomizer in the blockchain is a hard task, that's why it's counter. 


<!-- Sent from Reviewable.io -->

2022-10-06 13:51 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 16 of 31 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRk2fAaO_XOjqGEGD:-NDhYor23Slbs6R6tyXH:b-vho3c9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The code field name was taken from the doc, this might be BTC, ur USDT or what ever.
</blockquote></details>

let's discuss after daily
___
*[`proto/coreum/asset/v1/asset.proto` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRrpT-mOmspsSJs9M:-NDhYuGxBd83rWavJQdG:bkmtlzo) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The randomizer in the blockchain is a hard task, that's why it's counter. 
</blockquote></details>

we could use deterministic way, like taking integer and computing sha, then converting t to bech32 (it contains checksum) or sth like that


<!-- Sent from Reviewable.io -->

2022-10-06 14:07 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 16 of 31 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRrpT-mOmspsSJs9M:-NDhbgPs78zzibbW-eX-:b-5kwd5h) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L54)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we could use deterministic way, like taking integer and computing sha, then converting t to bech32 (it contains checksum) or sth like that
</blockquote></details>

Why do we need it I don't understand? 


<!-- Sent from Reviewable.io -->

2022-10-06 14:07 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 16 of 31 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRk2fAaO_XOjqGEGD:-NDhbnBH3uUkCAfvn9qJ:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss after daily
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-10-10 13:44 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 3 of 35 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRk2fAaO_XOjqGEGD:-NE17y_7AA64CXrurpcc:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Updated.
___
*[`proto/coreum/asset/v1/asset.proto` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NDhRrpT-mOmspsSJs9M:-NE17v7xEZHXi5f2Z9wT:b8g2f98) ([raw file](https://github.com/coreumfoundation/coreum/blob/a966be5c138449bea08d81e3c531a166e528b9ac/proto/coreum/asset/v1/asset.proto#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need it I don't understand? 
</blockquote></details>

Updated with the new strategy.


<!-- Sent from Reviewable.io -->

2022-10-11 09:13 UTC, wojtek-coreum requested changes
> Reviewed 16 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 19 of 36 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/asset/v1/genesis.proto` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Ivqx6-wMXFaxcCXZ:-NE5Ivqx6-wMXFaxcCX_:b60r33y) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/genesis.proto#L12)):*
> ```protobuf
> message GenesisState {
>   // fungible_tokens keep the fungible token state
>   repeated FungibleTokenDefinition fungible_tokens  = 1 [(gogoproto.nullable) = false];
> ```

What do we need `FungibleTokenDefinition` for? Shouldn't `FungibleToken` be specified in genesis?


<!-- Sent from Reviewable.io -->

2022-10-11 09:14 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 19 of 36 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/genesis.proto` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Ivqx6-wMXFaxcCXZ:-NE5Jepe2tNGv-5MVyHN:bpw4g36) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/genesis.proto#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What do we need `FungibleTokenDefinition` for? Shouldn't `FungibleToken` be specified in genesis?
</blockquote></details>

This will be used for the state export. 


<!-- Sent from Reviewable.io -->

2022-10-11 10:19 UTC, wojtek-coreum requested changes
> Reviewed 1 of 31 files at r1, 11 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 31 of 36 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/client/cli/tx.go` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5WYXvCK23pNDcF9Ed:-NE5WYXwCg5cbc_JkIYf:b-c6zzf9) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/client/cli/tx.go#L35)):*
> ```Go
> }
> 
> // CmdTxIssueFungibleToken returns issue IssueFungibleTokenSettings cobra command.
> ```

remove `Settings`?
___
*[`x/asset/client/cli/tx.go` line 60 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5TxZaDWf5pZOjr-bE:-NE5TxZaDWf5pZOjr-bF:b7bw03f) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/client/cli/tx.go#L60)):*
> ```Go
> 			description := args[1]
> 			recipient := args[2]
> 			// is the recipient wasn't provided the signer is the recipient
> ```

is -> if
___
*[`x/asset/client/cli/tx.go` line 69 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5U2fa73oYDDRTE-3a:-NE5U2fbC19fmDIRBW3I:b-pgw9u8) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/client/cli/tx.go#L69)):*
> ```Go
> 			}
> 
> 			// the initial amount wasn't provided the amount is zero
> ```

if ...
___
*[`x/asset/keeper/keeper.go` line 44 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5VT9m8EKMFHN5gWCq:-NE5VT9nDn1uvW3_uAiF:b-t3y8a1) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/keeper/keeper.go#L44)):*
> ```Go
> 
> 	k.setFungibleTokenDenomMetadata(ctx, settings.Symbol, denom, settings.Description)
> 	if settings.InitialAmount.IsPositive() {
> ```

Minor: I would say this `if` should be inside `mintFungibleToken`
___
*[`x/asset/keeper/keeper.go` line 82 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5V5M66DN_4-exEGtR:-NE5V5M66DN_4-exEGtS:b-xl30ve) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/keeper/keeper.go#L82)):*
> ```Go
> 	metadata, found := k.bankKeeper.GetDenomMetaData(ctx, denom)
> 	if !found {
> 		return types.FungibleToken{}, sdkerrors.Wrapf(types.ErrFungibleTokenNotFound, "metadate for %s denom not found", denom)
> ```

metadate -> metadata
___
*[`x/asset/keeper/keeper.go` line 123 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Vw-i781LjYr68mn0:-NE5Vw-i781LjYr68mn1:b56gv24) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/keeper/keeper.go#L123)):*
> ```Go
> 
> 	if err := k.bankKeeper.SendCoinsFromModuleToAccount(ctx, types.ModuleName, recipient, coinsToMint); err != nil {
> 		return sdkerrors.Wrapf(err, "can't send mined coins from module %s to account %s", types.ModuleName, recipient.String())
> ```

mined -> minted
___
*[`x/asset/types/ft.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5WvoRCGNfj6tWiajA:-NE5WvoRCGNfj6tWiajB:b-v41sb3) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/ft.go#L20)):*
> ```Go
> // BuildFungibleTokenDenom builds the denom string from the symbol and issuer address.
> func BuildFungibleTokenDenom(symbol string, issuer sdk.AccAddress) string {
> 	return fmt.Sprintf("%s-%s", symbol, issuer)
> ```

I would still love to have some checksum there
___
*[`x/asset/types/msgs.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YQG713DS-JjHuTuS:-NE5YQG87fCML29Vwalm:btl9zcg) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L21)):*
> ```Go
> 	}
> 
> 	if len(msg.Symbol) == 0 || len(msg.Symbol) > maxSymbolLength {
> ```

what about limiting the set of allowed characters?
___
*[`x/asset/types/msgs.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Y9GJDnQY54YJGiTU:-NE5Y9GK4c2yXnFGeAyD:b1prhd) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L26)):*
> ```Go
> 
> 	if len(msg.Description) > maxDescriptionLength {
> 		return sdkerrors.Wrapf(ErrInvalidFungibleToken, "invalid description %s, the length must less than %d", msg.Description, maxDescriptionLength)
> ```

%s -> "%s" as description will contain spaces
___
*[`x/asset/types/msgs.go` line 33 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YN1W7Wt9mKrlhy3S:-NE5YN1W7Wt9mKrlhy3T:b-ysosdp) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L33)):*
> ```Go
> 	}
> 
> 	if msg.InitialAmount.IsNegative() {
> ```

what about adding `IsNil` here?


<!-- Sent from Reviewable.io -->

2022-10-11 12:15 UTC, miladz68 requested changes
> Reviewed 4 of 31 files at r1, 32 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/asset/issue.go` line 77 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5x9VuC_Jqp_pYBc9-:-NE5x9VuC_Jqp_pYBc90:byraxsc) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/integration-tests/asset/issue.go#L77)):*
> ```Go
> 	// query balance
> 	tokenBalanceRes, err := bankClient.Balance(ctx, &banktypes.QueryBalanceRequest{
> 		Address: issuer.String(),
> ```

we should also test for the case that issuer and recipient are different. 
___
*[`proto/coreum/asset/v1/asset.proto` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5RuMB7q7j7mvpsXlw:-NE5RuMB7q7j7mvpsXlx:b-qe5s7) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/asset.proto#L16)):*
> ```protobuf
> }
> 
> // FungibleToken is a full representation of the fungible token.
> ```

It is a little confusing to tell the difference between FungibleToken and FungibleTokenDefinition.
I see that FungibleToken is only used for querying, so maybe it can be moved to query.proto  and/or renamed to something less confusing ? let's discuss naming in the daily.
___
*[`proto/coreum/asset/v1/event.proto` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Pgqe8vmKr_BkFE00:-NE5Pgqe8vmKr_BkFE01:ba8wfez) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/event.proto#L10)):*
> ```protobuf
>   string denom = 1;
>   string issuer = 2;
>   string symbol = 3;
> ```

minted amount is useful info to have as well. 
___
*[`proto/coreum/asset/v1/tx.proto` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5wW9R9qYefkITMBHM:-NE5wW9R9qYefkITMBHN:b-8f3l8l) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/tx.proto#L31)):*
> ```protobuf
> 
> // MsgIssueFungibleTokenResponse defines message response for the IssueFungibleToken.
> message MsgIssueFungibleTokenResponse {}
> ```

I think denom can be returned here.
___
*[`x/asset/types/errors.go` line 9 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5xdsE5MSUpfoD2d4C:-NE5xdsE5MSUpfoD2d4D:b2oi3wf) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/errors.go#L9)):*
> ```Go
> var (
> 	// ErrInvalidFungibleToken defines the common error for the invalid fungible tokens.
> 	ErrInvalidFungibleToken = sdkerrors.Register(ModuleName, 1, "invalid fungible token")
> ```

I think this one is too generic, a more fine grained error would be better.
___
*[`x/asset/types/errors.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5xVwc8IJlnZsDIexE:-NE5xVwc8IJlnZsDIexF:b-t7t35z) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/errors.go#L11)):*
> ```Go
> 	ErrInvalidFungibleToken = sdkerrors.Register(ModuleName, 1, "invalid fungible token")
> 	// ErrFungibleTokenNotFound error for a fungible token not found in the store.
> 	ErrFungibleTokenNotFound = sdkerrors.Register(ModuleName, 2, "fungible token not found")
> ```

I think a generic not found is better than having not found error defined for each type.


<!-- Sent from Reviewable.io -->

2022-10-11 14:00 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/issue.go` line 77 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5x9VuC_Jqp_pYBc9-:-NE620rW5gIJPdOrHTKD:b-7of5kz) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/integration-tests/asset/issue.go#L77)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should also test for the case that issuer and recipient are different. 
</blockquote></details>

Agree, updated the test to have the custom recipient. 
___
*[`proto/coreum/asset/v1/asset.proto` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5RuMB7q7j7mvpsXlw:-NE64DteAkiSVSF47HlP:b-33l2d5) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/asset.proto#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is a little confusing to tell the difference between FungibleToken and FungibleTokenDefinition.
I see that FungibleToken is only used for querying, so maybe it can be moved to query.proto  and/or renamed to something less confusing ? let's discuss naming in the daily.
</blockquote></details>

We need the FungibleToken as a custom model used in the keeper. We can remove it from the proto if we don't need it, but my idea was to simplify the consumers life and provide them the full model they can reuse.
___
*[`proto/coreum/asset/v1/event.proto` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Pgqe8vmKr_BkFE00:-NE64ckT5Oc5QNy7Eu_j:b4nlw61) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/event.proto#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

minted amount is useful info to have as well. 
</blockquote></details>

Agree,  updated. Added all onfo we had on the issuance.
___
*[`proto/coreum/asset/v1/tx.proto` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5wW9R9qYefkITMBHM:-NE6GNuv2Z_Oig0nm0pU:b9nsdz1) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/proto/coreum/asset/v1/tx.proto#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think denom can be returned here.
</blockquote></details>

We don't retrun on the Msg, since the message will be execute later in the block
___
*[`x/asset/client/cli/tx.go` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5WYXvCK23pNDcF9Ed:-NE6JIT96LZlSVun-tiS:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/client/cli/tx.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

remove `Settings`?
</blockquote></details>

Done.



_Code quote:_
```Go
CmdTxIssueFungibleToken returns issue IssueFungibleTokenSettings cobra command.
```
___
*[`x/asset/client/cli/tx.go` line 60 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5TxZaDWf5pZOjr-bE:-NE6JKwWDyfGLsuAGjjP:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/client/cli/tx.go#L60)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

is -> if
</blockquote></details>

Done.



_Code quote:_
```Go
// is the recipient wasn't provided the signer is the recipient
```
___
*[`x/asset/client/cli/tx.go` line 69 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5U2fa73oYDDRTE-3a:-NE6JOYs97SNgT1_w5YS:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/client/cli/tx.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

if ...
</blockquote></details>

Done.



_Code quote:_
```Go
 the initial amount wasn't provided the amount is zero
```
___
*[`x/asset/keeper/keeper.go` line 44 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5VT9m8EKMFHN5gWCq:-NE6JaHR0oabDaTX2RJK:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/keeper/keeper.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: I would say this `if` should be inside `mintFungibleToken`
</blockquote></details>

Done
___
*[`x/asset/keeper/keeper.go` line 82 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5V5M66DN_4-exEGtR:-NE6JeWd68DbgDNclST3:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/keeper/keeper.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

metadate -> metadata
</blockquote></details>

Done.



_Code quote:_
```Go
metadate 
```
___
*[`x/asset/keeper/keeper.go` line 123 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Vw-i781LjYr68mn0:-NE6JjsB6TeiNaMDcDrM:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/keeper/keeper.go#L123)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

mined -> minted
</blockquote></details>

Done.
___
*[`x/asset/types/errors.go` line 9 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5xdsE5MSUpfoD2d4C:-NE6JmL30-EqFYr-N4fD:bdh62gj) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/errors.go#L9)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think this one is too generic, a more fine grained error would be better.
</blockquote></details>

I wrap this error, so it's create based on the wrapper info
___
*[`x/asset/types/errors.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5xVwc8IJlnZsDIexE:-NE6JtvF1EwQHyvstwwO:blopk9g) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/errors.go#L11)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think a generic not found is better than having not found error defined for each type.
</blockquote></details>

Not sure about that. Let's discuss. 



_Code quote:_
```Go
ErrFungibleTokenNotFound 
```
___
*[`x/asset/types/ft.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5WvoRCGNfj6tWiajA:-NE6JxUE9gTD3bRMcNps:b-6xg7n1) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/ft.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would still love to have some checksum there
</blockquote></details>

Got you, but that is the version we agreed :-)
___
*[`x/asset/types/msgs.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YQG713DS-JjHuTuS:-NE6K11I3bPywFc2PHJ9:b-dwflhp) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about limiting the set of allowed characters?
</blockquote></details>

Out of scope for that task, we agree to ask business first
___
*[`x/asset/types/msgs.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5Y9GJDnQY54YJGiTU:-NE6K9gN0HBh7bQbTc5o:b-2zknp5) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.g [...]

2022-10-11 15:16 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 27 of 37 files reviewed, 9 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/types/ft.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5WvoRCGNfj6tWiajA:-NE6b_UACEQAHHvz8yYC:bmr5d4) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/ft.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Got you, but that is the version we agreed :-)
</blockquote></details>

we can use crc-8 hex encoded to checksum the denom. 


<!-- Sent from Reviewable.io -->

2022-10-11 15:32 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 27 of 37 files reviewed, 9 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/ft.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5WvoRCGNfj6tWiajA:-NE6fAKnDVhCzc180Qrp:b-ljmepl) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/ft.go#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we can use crc-8 hex encoded to checksum the denom. 
</blockquote></details>

Updated. Now we have the crc-8 at the end.


<!-- Sent from Reviewable.io -->

2022-10-12 10:10 UTC, miladz68 requested changes
> Reviewed 10 of 10 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 38 of 39 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAf7boE8jkP1DDFn9J:-NEAf7boE8jkP1DDFn9K:bkv562x) ([raw file](https://github.com/coreumfoundation/coreum/blob/b5f0e5433fff4dca2371cf38b486d5b44724621b/.github/workflows/ci.yml#L46)):*
> ```YAML
>       - name: Lint, run unit tests and build
>         run: crust build lint/coreum test/coreum images --log-format=yaml
> # FIXME (dhil) will restored once we update the crust dependency
> ```

I don't see why we need to disable crust for this one !
___
*[`x/asset/types/ft.go` line 29 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAeI476tJcmx2caH_m:-NEAeI476tJcmx2caH_n:bfpnj38) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa32227deb19b85492858fb2ce3758ca0c9dbd91/x/asset/types/ft.go#L29)):*
> ```Go
> }
> 
> func checksum(data string) string {
> ```

I don't understand this checksum, let's discuss
___
*[`x/asset/types/ft_test.go` line 10 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAesuaCmsLEltePtsy:-NEAesuaCmsLEltePtsz:b-df99sv) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa32227deb19b85492858fb2ce3758ca0c9dbd91/x/asset/types/ft_test.go#L10)):*
> ```Go
> 
> 	"github.com/CoreumFoundation/coreum/x/asset/types"
> )
> ```

we also need a function for checksum validation and a test for it. that function should be used in our query. 


<!-- Sent from Reviewable.io -->

2022-10-12 11:29 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 38 of 39 files reviewed, 12 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAf7boE8jkP1DDFn9J:-NEAwxTYC9qVpUJvkJ1B:bl38p8e) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't see why we need to disable crust for this one !
</blockquote></details>

The genesis updated, so it's incompatible with the one crust creates now.
___
*[`x/asset/types/ft.go` line 29 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAeI476tJcmx2caH_m:-NEAx5hQ9sVbAgPWIS4T:bmcs4r7) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa32227deb19b85492858fb2ce3758ca0c9dbd91/x/asset/types/ft.go#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't understand this checksum, let's discuss
</blockquote></details>

What exactly isn't understandable? 
___
*[`x/asset/types/ft_test.go` line 10 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAesuaCmsLEltePtsy:-NEAwsgM9_Zwu2YlyMPO:b-xfsego) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa32227deb19b85492858fb2ce3758ca0c9dbd91/x/asset/types/ft_test.go#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we also need a function for checksum validation and a test for it. that function should be used in our query. 
</blockquote></details>

We test in here, so what tests do you need?


<!-- Sent from Reviewable.io -->

2022-10-12 11:36 UTC, wojtek-coreum requested changes
> Reviewed 9 of 10 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAf7boE8jkP1DDFn9J:-NEAyH-AAPIM-NUQ4HIm:b7xkp6v) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The genesis updated, so it's incompatible with the one crust creates now.
</blockquote></details>

You may support the transition period without disabling integration tests. Take a look: https://github.com/CoreumFoundation/coreum/commit/bfdcd8c45f9054d11584b727d3c37cca7666a18d#diff-f6137c0e22091e762f8fe224c9c0f158a207cec1a937cbccd67824cd43223776R133

line 133 in module.go
___
*[`integration-tests/index.go` line 17 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAuat74i63pV5tpFPW:-NEAuat74i63pV5tpFPX:b-kgjssy) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/integration-tests/index.go#L17)):*
> ```Go
> 	testSet := testing.TestSet{
> 		SingleChain: []testing.SingleChainSignature{
> 			asset.TestIssueBasicFungibleToken,
> ```

What does "Basic" mean here?
___
*[`integration-tests/testing/event.go` line 10 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAv2Pr3-TEXLENeyfv:-NEAv2Pr3-TEXLENeyfw:bk0ptkf) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/integration-tests/testing/event.go#L10)):*
> ```Go
> )
> 
> // FindTypedEvent finds the event in the list of events and returns the decoded
> ```

... the decoded <what?>
___
*[`x/asset/types/msgs.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YQG713DS-JjHuTuS:-NEAxbtc04yikIF3tdWX:b-8zw0cy) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Out of scope for that task, we agree to ask business first
</blockquote></details>

I insist on making decision now
___
*[`x/asset/types/msgs.go` line 33 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YN1W7Wt9mKrlhy3S:-NEAxrte96YdWcAHUDwu:bb7r2f0) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It can't nil here
</blockquote></details>

why?


<!-- Sent from Reviewable.io -->

2022-10-12 13:18 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAf7boE8jkP1DDFn9J:-NEBKl892LOWnHth3F5F:b-no05p7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You may support the transition period without disabling integration tests. Take a look: https://github.com/CoreumFoundation/coreum/commit/bfdcd8c45f9054d11584b727d3c37cca7666a18d#diff-f6137c0e22091e762f8fe224c9c0f158a207cec1a937cbccd67824cd43223776R133

line 133 in module.go
</blockquote></details>

Ok. Let's follow such approach. Updared.



_Code quote:_
```YAML
 - name: Integration tests
```
___
*[`integration-tests/index.go` line 17 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAuat74i63pV5tpFPW:-NEB9EM35RGI5gqe8F8n:baas7x8) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/integration-tests/index.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What does "Basic" mean here?
</blockquote></details>

Just that test covers the basic issuance
___
*[`integration-tests/testing/event.go` line 10 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAv2Pr3-TEXLENeyfv:-NEBBaYo60Aridn38939:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/integration-tests/testing/event.go#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

... the decoded <what?>
</blockquote></details>

Updated.



_Code quote:_
```Go
// FindTypedEvent finds the event in the list of events and returns the decoded
```
___
*[`x/asset/types/msgs.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YQG713DS-JjHuTuS:-NEB9Q_HCyzLhCVaDC8Y:b-rxbvzm) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I insist on making decision now
</blockquote></details>

Updated to foloow the denom validation + additional length check.
___
*[`x/asset/types/msgs.go` line 33 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NE5YN1W7Wt9mKrlhy3S:-NEBHGjQ-SNo0ty7C6x7:b-ncrq2r) ([raw file](https://github.com/coreumfoundation/coreum/blob/8c80921ceb98ad21ba401509a229a104330068de/x/asset/types/msgs.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why?
</blockquote></details>

I can't reproduce such state in the integration tests. Also haven't found similar checks in the SDK.
But can in unit test, so added the additional check.


<!-- Sent from Reviewable.io -->

2022-10-12 13:57 UTC, wojtek-coreum requested changes
> Reviewed 6 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 34 of 39 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/index.go` line 17 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAuat74i63pV5tpFPW:-NEBU-ip9VSonBUMCxKL:b-8u9sxa) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/integration-tests/index.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Just that test covers the basic issuance
</blockquote></details>

is there any non-basic?
___
*[`x/asset/types/msgs.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEBTen-AhA2-85AuI2O:-NEBTen-AhA2-85AuI2P:bwfd97y) ([raw file](https://github.com/coreumfoundation/coreum/blob/c82a1157fd19b93cbeb1d33b68b268f3ece74fb2/x/asset/types/msgs.go#L26)):*
> ```Go
> 
> 	if err := sdk.ValidateDenom(msg.Symbol); err != nil {
> 		return sdkerrors.Wrapf(ErrInvalidFungibleToken, "invalid symbol %s, the symbol must follow the rule: %s", msg.Symbol, sdk.DefaultCoinDenomRegex())
> ```

This will give incorrect message because length specified in this regex is incorrect for our case


<!-- Sent from Reviewable.io -->

2022-10-12 15:57 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 34 of 39 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/index.go` line 17 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEAuat74i63pV5tpFPW:-NEBuO707habOI70FJtR:bca3fzp) ([raw file](https://github.com/coreumfoundation/coreum/blob/1e5c786943362ce7a2a239db27e29a604169d8d9/integration-tests/index.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

is there any non-basic?
</blockquote></details>

Nope, that's just a test name :-) Since we will have more later. And that's just about simple issuance. 



_Code quote:_
```Go
TestIssueBasicFungibleToken
```
___
*[`x/asset/types/msgs.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEBTen-AhA2-85AuI2O:-NEBuHl2EjfI5fZ5weop:bno9mno) ([raw file](https://github.com/coreumfoundation/coreum/blob/c82a1157fd19b93cbeb1d33b68b268f3ece74fb2/x/asset/types/msgs.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This will give incorrect message because length specified in this regex is incorrect for our case
</blockquote></details>

We validate the length before that check. 


<!-- Sent from Reviewable.io -->

2022-10-13 06:50 UTC, wojtek-coreum reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 36 of 39 files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2022-10-13 06:50 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 36 of 39 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/types/msgs.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEBTen-AhA2-85AuI2O:-NEF5t-_6ivjmalbzhav:b-vmk3fu) ([raw file](https://github.com/coreumfoundation/coreum/blob/c82a1157fd19b93cbeb1d33b68b268f3ece74fb2/x/asset/types/msgs.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We validate the length before that check. 
</blockquote></details>

yes, but if length is ok, but regex fail we will print a regex saying that 128 characters are allowed


<!-- Sent from Reviewable.io -->

2022-10-13 07:04 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 33 of 39 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/msgs.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEBTen-AhA2-85AuI2O:-NEF9BJr5CQVQI0WWLFU:b-96jui3) ([raw file](https://github.com/coreumfoundation/coreum/blob/c82a1157fd19b93cbeb1d33b68b268f3ece74fb2/x/asset/types/msgs.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, but if length is ok, but regex fail we will print a regex saying that 128 characters are allowed
</blockquote></details>

See, we don't use the error text here. 


<!-- Sent from Reviewable.io -->

2022-10-13 08:37 UTC, miladz68 approved these changes
> Reviewed 7 of 11 files at r7, 2 of 2 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/ft.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEFTuhIBovCAWFaM-at:-NEFTuhIBovCAWFaM-au:b72pqk2) ([raw file](https://github.com/coreumfoundation/coreum/blob/bea41da7b4f1b22aba8f1382fdfef511815088e8/x/asset/types/ft.go#L29)):*
> ```Go
> }
> 
> func checksum(data string) string {
> ```

Just a reminder
we discussed to postpone checksum into a separate task


<!-- Sent from Reviewable.io -->

2022-10-13 08:41 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/ft.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEFTuhIBovCAWFaM-at:-NEFVClCATu4G3Lvz6HW:b-24caig) ([raw file](https://github.com/coreumfoundation/coreum/blob/bea41da7b4f1b22aba8f1382fdfef511815088e8/x/asset/types/ft.go#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Just a reminder
we discussed to postpone checksum into a separate task
</blockquote></details>

Right, we decided to return to it later, but now we use the current approach.


<!-- Sent from Reviewable.io -->

2022-10-13 12:08 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: 38 of 39 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/msgs.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEBTen-AhA2-85AuI2O:-NEGElvZ2klRLGUjJ8am:bnangb1) ([raw file](https://github.com/coreumfoundation/coreum/blob/c82a1157fd19b93cbeb1d33b68b268f3ece74fb2/x/asset/types/msgs.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

See, we don't use the error text here. 
</blockquote></details>

Updated with the new.



_Code quote:_
```Go
return sdkerrors.Wrapf(ErrInvalidFungibleToken, "invalid symbol %s, the symbol must follo
```


<!-- Sent from Reviewable.io -->

2022-10-13 12:10 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-10-13 13:41 UTC, wojtek-coreum requested changes
> Reviewed 1 of 32 files at r3, 1 of 10 files at r4, 1 of 2 files at r5, 3 of 11 files at r7, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/asset/client/cli/query_test.go` line 28 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEGZ4QE4Cw_sdnZW0Kn:-NEGZ4QE4Cw_sdnZW0Ko:b-tcuav6) ([raw file](https://github.com/coreumfoundation/coreum/blob/79c90c0b5e4205fc8625228a51987e83d4a9bdc5/x/asset/client/cli/query_test.go#L28)):*
> ```Go
> 	testNetwork := network.New(t)
> 
> 	// the denom must start from the latter
> ```

latter->letter
___
*[`x/asset/client/cli/query_test.go` line 72 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEGZVar-44Kk1--34-z:-NEGZVar-44Kk1--340-:bdntrvq) ([raw file](https://github.com/coreumfoundation/coreum/blob/79c90c0b5e4205fc8625228a51987e83d4a9bdc5/x/asset/client/cli/query_test.go#L72)):*
> ```Go
> 		return eventFungibleTokenIssued.Denom
> 	}
> 	requireT.Failf("event: %s not fount in the create fungible token response", eventFungibleTokenIssuedName)
> ```

fount -> found
___
*[`.github/workflows/ci.yml` line 46 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEGYIsj5V96JVzRnTxQ:-NEGYIsj5V96JVzRnTxR:bz0fh4r) ([raw file](https://github.com/coreumfoundation/coreum/blob/bea41da7b4f1b22aba8f1382fdfef511815088e8/.github/workflows/ci.yml#L46)):*
> ```YAML
>       - name: Lint, run unit tests and build
>         run: crust build lint/coreum test/coreum images --log-format=yaml
> # FIXME(dhil) remove once we update the crust
> ```

why? We agreed to not do this


<!-- Sent from Reviewable.io -->

2022-10-13 13:52 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/client/cli/query_test.go` line 28 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEGZ4QE4Cw_sdnZW0Kn:-NEGbWC7E0btrv4tEs1a:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/79c90c0b5e4205fc8625228a51987e83d4a9bdc5/x/asset/client/cli/query_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

latter->letter
</blockquote></details>

Done.



_Code quote:_
```Go
// the denom must start from the lat
```
___
*[`x/asset/client/cli/query_test.go` line 72 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEGZVar-44Kk1--34-z:-NEGbU4T8w0vo8QPMDy0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/79c90c0b5e4205fc8625228a51987e83d4a9bdc5/x/asset/client/cli/query_test.go#L72)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

fount -> found
</blockquote></details>

Done.



_Code quote:_
```Go
s not fount in the create fungible token response", eventFungible
```
___
*[`.github/workflows/ci.yml` line 46 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEGYIsj5V96JVzRnTxQ:-NEGb3qD2SJgfWwwVhpO:b1cidda) ([raw file](https://github.com/coreumfoundation/coreum/blob/bea41da7b4f1b22aba8f1382fdfef511815088e8/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why? We agreed to not do this
</blockquote></details>

Merged the master and it was on it. But I can uncomment now, since the crust is updated.
Done.


<!-- Sent from Reviewable.io -->

2022-10-13 13:54 UTC, wojtek-coreum approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-10-13 14:36 UTC, merged

2022-10-24 20:10 UTC, ysv reviewed
> Reviewed 3 of 31 files at r1, 13 of 32 files at r3, 6 of 10 files at r4, 1 of 2 files at r5, 3 of 11 files at r7, 2 of 2 files at r8, 2 of 3 files at r9, 1 of 1 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 17 unresolved discussions

___
*[`integration-tests/asset/issue.go` line 40 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFACNra6B1KI_37p1oF:-NFACNra6B1KI_37p1oG:b-2kwow9) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L40)):*
> ```Go
> 	msg := &assettypes.MsgIssueFungibleToken{
> 		Issuer:      issuer.String(),
> 		Symbol:      "BTC",
> ```

is it basic unit symbol or not ?
___
*[`integration-tests/asset/issue.go` line 55 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFACVxc2Ve5uigEeB02:-NFACVxc2Ve5uigEeB03:b-vo1k28) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L55)):*
> ```Go
> 
> 	require.NoError(t, err)
> 	evt := testing.FindTypedEvent(t, &assettypes.EventFungibleTokenIssued{}, res.Events)
> ```

I would prefer to change `FindTypedEvent` to use work similar to the way `json.Unmarshal`
```
func FindTypedEvent(t T, events []tmtypes.Event, event proto.Message) {
	eventName := proto.MessageName(event)
	for i := range events {
		if events[i].Type != eventName {
			continue
		}

		msg, err := sdk.ParseTypedEvent(events[i])
		require.NoError(t, err)

                // assign instead of returning msg
		event = msg
	}

	require.Failf(t, "%s event, not found in the events", eventName)
}

// Usage
var evt  assettypes.EventFungibleTokenIssued
testing.FindTypedEvent(t, &evt, res.Events)
```

it looks better because you don't need to cast type & looks more natural
___
*[`integration-tests/asset/issue.go` line 55 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAGIRy7f_EjGWdS-aO:-NFAGIRy7f_EjGWdS-aP:btq1fn9) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L55)):*
> ```Go
> 
> 	require.NoError(t, err)
> 	evt := testing.FindTypedEvent(t, &assettypes.EventFungibleTokenIssued{}, res.Events)
> ```

minor:
I don't really like abbreviation `evt` `evnt` looks much better for me
___
*[`proto/coreum/asset/v1/asset.proto` line 9 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAJSHCDMy9BTqv0V0M:-NFAJSHCDMy9BTqv0V0N:bccfw3y) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/proto/coreum/asset/v1/asset.proto#L9)):*
> ```protobuf
> 
> // FungibleTokenDefinition defines the fungible token settings to store.
> message FungibleTokenDefinition {
> ```

still don't like naming
I propose: `FungibleToken` & `FungibleTokenFull` but lets dicscuss first 
___
*[`x/asset/client/cli/query_test.go` line 60 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFARa8pBI7KpjOejKLD:-NFARa8pBI7KpjOejKLE:b-j8asqe) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/query_test.go#L60)):*
> ```Go
> 
> 	eventFungibleTokenIssuedName := proto.MessageName(&types.EventFungibleTokenIssued{})
> 	for i := range res.Events {
> ```

can't we reuse `func FindTypedEvent` here ?
___
*[`x/asset/client/cli/tx.go` line 38 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFARyBIEQV-5WGpzGKF:-NFARyBIEQV-5WGpzGKG:ba4htd3) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L38)):*
> ```Go
> func CmdTxIssueFungibleToken() *cobra.Command {
> 	cmd := &cobra.Command{
> 		Use:   "issue-ft [symbol] [description] [recipient_address] [initial_amount] --from [issuer]",
> ```

IMO the order should be the following:
1. symbol
2. recipient
3. initial amount
4. description

because description is the least important and could even become optional at some point
I'm also not sure about recipient. I would make it optional and sent to from by default
___
*[`x/asset/client/cli/tx.go` line 45 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFASUaN2dOaLKYcSNwS:-NFASUaN2dOaLKYcSNwT:b-7lji9b) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L45)):*
> ```Go
> 
> Example:
> $ %s tx asset issue-ft BTC "BTC Token" [recipient_address] 100000 --from [issuer]
> ```

to make it more user friendly:
`tx asset issue-ft WBTC "Wrapped Bitcoin" [recipient_address] 21000000 --from [issuer]`
___
*[`x/asset/client/cli/tx.go` line 57 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATYPpCbvsRT_C1gNd:-NFATYPpCbvsRT_C1gNe:b-hy1x6d) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L57)):*
> ```Go
> 
> 			issuer := clientCtx.GetFromAddress()
> 			symbol := args[0]
> ```

do we have any validation for symbol ?
___
*[`x/asset/client/cli/tx.go` line 65 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATAnDAWPayiWHSLsu:-NFATAnEDGIHuN-dcISv:bjkqgya) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L65)):*
> ```Go
> 					return sdkerrors.Wrap(err, "invalid recipient")
> 				}
> 			} else {
> ```

you can remove else and just keep `recipient = issuer.String()`
___
*[`x/asset/client/cli/tx.go` line 70 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATNG53HvNKnPefVaJ:-NFATNG53HvNKnPefVaK:bn6uaj7) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L70)):*
> ```Go
> 
> 			// if the initial amount wasn't provided the amount is zero
> 			initialAmount := sdk.ZeroInt()
> ```

do we have validation for initial amount to not be 0 somewhere ?
___
*[`x/asset/client/cli/tx_test.go` line 28 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATkHmDM9eVAaFzgKz:-NFATkHmDM9eVAaFzgL-:b-wb0bf8) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx_test.go#L28)):*
> ```Go
> 
> 	// the denom must start from the letter
> 	symbol := "l" + uuid.NewString()[:4]
> ```

minor:
I prefer to use some realistic value here like: BTC, ETH etc
Because later we will add a validation for this and it will brake this test
___
*[`x/asset/keeper/keeper.go` line 50 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAbJUk7GAeybyeO1RB:-NFAbJUk7GAeybyeO1RC:biemdh5) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/keeper/keeper.go#L50)):*
> ```Go
> 
> 	store := ctx.KVStore(k.storeKey)
> 	definition := types.FungibleTokenDefinition{
> ```

I'm just thinking if we really need to store issuer since it is inside denom & has a specific format sp could always be parse it from denom.
To discuss
___
*[`x/asset/keeper/keeper.go` line 73 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAUs-p8DBJr5EYqcyB:-NFAUs-p8DBJr5EYqcyC:b-k7az6l) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/keeper/keeper.go#L73)):*
> ```Go
> 
> // GetFungibleToken return the fungible token by its denom.
> func (k Keeper) GetFungibleToken(ctx sdk.Context, denom string) (types.FungibleToken, error) {
> ```

now I'm not sure that storing it separately is really a good idea because instead of 1 read we have 2 and data is split between modules. Might be discussed
___
*[`x/asset/keeper/keeper.go` line 112 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAVWBDBt-gcYOKYqUm:-NFAVWBDBt-gcYOKYqUn:b-6m281i) ([raw file](https://github.com/c [...]

2022-10-25 07:54 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: all files reviewed, 17 unresolved discussions

___
*[`integration-tests/asset/issue.go` line 40 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFACNra6B1KI_37p1oF:-NFCwN_c6SEWL_TI0n4A:bp36pr4) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it basic unit symbol or not ?
</blockquote></details>

This is the symbol to show. This will be used to form the denom name and will be visible on UI (al least we expect it)
___
*[`integration-tests/asset/issue.go` line 55 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFACVxc2Ve5uigEeB02:-NFCzjC_3s3PpoCTJbRG:b-koicfa) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L55)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would prefer to change `FindTypedEvent` to use work similar to the way `json.Unmarshal`
```
func FindTypedEvent(t T, events []tmtypes.Event, event proto.Message) {
	eventName := proto.MessageName(event)
	for i := range events {
		if events[i].Type != eventName {
			continue
		}

		msg, err := sdk.ParseTypedEvent(events[i])
		require.NoError(t, err)

                // assign instead of returning msg
		event = msg
	}

	require.Failf(t, "%s event, not found in the events", eventName)
}

// Usage
var evt  assettypes.EventFungibleTokenIssued
testing.FindTypedEvent(t, &evt, res.Events)
```

it looks better because you don't need to cast type & looks more natural
</blockquote></details>

Refactor it with the generics. 
The json.Marshal uses the reflection and checks the pointer types and so om with that style the function will be more complicated. 
___
*[`integration-tests/asset/issue.go` line 55 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAGIRy7f_EjGWdS-aO:-NFD-5fW5KyWjdIIHrHN:b-bbuayn) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L55)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I don't really like abbreviation `evt` `evnt` looks much better for me
</blockquote></details>

"evnt" doesn't  looks much better for me, refactored to full name -> "event"
___
*[`proto/coreum/asset/v1/asset.proto` line 9 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAJSHCDMy9BTqv0V0M:-NFD1ACd1WR-_wGgaRZS:bybcs3v) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/proto/coreum/asset/v1/asset.proto#L9)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

still don't like naming
I propose: `FungibleToken` & `FungibleTokenFull` but lets dicscuss first 
</blockquote></details>

"FungibleTokenFull" doesn't look better as well. I prefer to use the names without the prefixes or postfixes for full info and with for specific.
___
*[`x/asset/client/cli/query_test.go` line 60 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFARa8pBI7KpjOejKLD:-NFD1U6F6cvv3imvv2ZU:bi42sck) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/query_test.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can't we reuse `func FindTypedEvent` here ?
</blockquote></details>

Moved the testutills and refactored, now we use it.
___
*[`x/asset/client/cli/tx.go` line 38 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFARyBIEQV-5WGpzGKF:-NFD1eiTBEjDVoE9JfzB:b-u03ib9) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L38)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO the order should be the following:
1. symbol
2. recipient
3. initial amount
4. description

because description is the least important and could even become optional at some point
I'm also not sure about recipient. I would make it optional and sent to from by default
</blockquote></details>

The optional won't be so easy with that CLI. Since the params are required and flags are optional. 
Now we set the recipient as issuer in case the recipient is an empty string.
I'm ok with the order. Refactored.
___
*[`x/asset/client/cli/tx.go` line 45 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFASUaN2dOaLKYcSNwS:-NFD2_3R1ihPT8GWdWtQ:b-ept2ln) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to make it more user friendly:
`tx asset issue-ft WBTC "Wrapped Bitcoin" [recipient_address] 21000000 --from [issuer]`
</blockquote></details>

Updated with the text here and order from prev message.
___
*[`x/asset/client/cli/tx.go` line 57 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATYPpCbvsRT_C1gNd:-NFD2dOMCTMNY-gfNJmp:b-keqbd6) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L57)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we have any validation for symbol ?
</blockquote></details>

Yes we have: Check the ValidateBasic of the "MsgIssueFungibleToken"
___
*[`x/asset/client/cli/tx.go` line 65 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATAnDAWPayiWHSLsu:-NFD33rv30LyjHHHt7aU:biuurhm) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L65)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you can remove else and just keep `recipient = issuer.String()`
</blockquote></details>

This will break the logic, we set "recipient = issuer.String()" only in case the recipient wasn't provided
___
*[`x/asset/client/cli/tx.go` line 70 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATNG53HvNKnPefVaJ:-NFD3DLlDts6n6R70yDY:b-keqbd6) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we have validation for initial amount to not be 0 somewhere ?
</blockquote></details>

Yes we have: Check the ValidateBasic of the "MsgIssueFungibleToken"
___
*[`x/asset/client/cli/tx_test.go` line 28 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATkHmDM9eVAaFzgKz:-NFD3Ma868ixb_IuoZ1c:bmlmbai) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx_test.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I prefer to use some realistic value here like: BTC, ETH etc
Because later we will add a validation for this and it will brake this test
</blockquote></details>

I don't see a difference, but ok with your version as well. Updated.



_Code quote:_
```Go
"l"
```
___
*[`x/asset/keeper/keeper.go` line 50 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAbJUk7GAeybyeO1RB:-NFD3TVDECN-JF5yx8tf:by9i7u4) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/keeper/keeper.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm just thinking if we really need to store issuer since it is inside denom & has a specific format sp could always be p [...]

2022-10-25 10:07 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`integration-tests/asset/issue.go` line 55 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAGIRy7f_EjGWdS-aO:-NFDOfBi4rHJSQIGlF96:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L55)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

"evnt" doesn't  looks much better for me, refactored to full name -> "event"
</blockquote></details>

ok
___
*[`integration-tests/asset/issue.go` line 55 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFACVxc2Ve5uigEeB02:-NFDOfjQBF_rv-oUEHFj:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/integration-tests/asset/issue.go#L55)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Refactor it with the generics. 
The json.Marshal uses the reflection and checks the pointer types and so om with that style the function will be more complicated. 
</blockquote></details>

ok
___
*[`x/asset/client/cli/tx.go` line 38 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFARyBIEQV-5WGpzGKF:-NFDaP5iB7hdprt1D1hC:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The optional won't be so easy with that CLI. Since the params are required and flags are optional. 
Now we set the recipient as issuer in case the recipient is an empty string.
I'm ok with the order. Refactored.
</blockquote></details>

ok
___
*[`x/asset/client/cli/tx.go` line 57 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFATYPpCbvsRT_C1gNd:-NFDRnqQAbolW0W4a_px:b-x6j4hn) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/client/cli/tx.go#L57)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes we have: Check the ValidateBasic of the "MsgIssueFungibleToken"
</blockquote></details>

I see ok
___
*[`x/asset/types/ft.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEFTuhIBovCAWFaM-at:-NFDWFmy89cCJqq_f3FX:bpl2ad4) ([raw file](https://github.com/coreumfoundation/coreum/blob/bea41da7b4f1b22aba8f1382fdfef511815088e8/x/asset/types/ft.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We have a task to do it. So no need to have additional "TODO". 
</blockquote></details>

yes but it still attracts attention and TODO is like protection here to understand that it is not a final version
But anyways as you prefer
___
*[`x/asset/types/ft.go` line 15 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAa-Nz8zKKNKh2MnBQ:-NFDb-4aA2AE_M29i7t0:b2e48im) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/types/ft.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the alternative name?
</blockquote></details>

can't come up with a better name 
lets keep it for now maybe later we will change
___
*[`x/asset/types/ft_test.go` line 13 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NFAZqMH8ijJ8dLE3vN0:-NFDWg7RC_fOACKAlfkF:bamin25) ([raw file](https://github.com/coreumfoundation/coreum/blob/cbdb252f5aba08d4feead1333ac4f2521eb2bcbf/x/asset/types/ft_test.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, you can add a task to protect it, and we need to 
</blockquote></details>

already added to task


<!-- Sent from Reviewable.io -->

2022-10-28 13:47 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/214)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`x/asset/types/ft.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/214#-NEFTuhIBovCAWFaM-at:-NFT6bgh8ie57-LOjE2d:b-8b11j9) ([raw file](https://github.com/coreumfoundation/coreum/blob/bea41da7b4f1b22aba8f1382fdfef511815088e8/x/asset/types/ft.go#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes but it still attracts attention and TODO is like protection here to understand that it is not a final version
But anyways as you prefer
</blockquote></details>

Added



_Code quote:_
```Go
func checksum(data string) string {
```


<!-- Sent from Reviewable.io -->