Implement freeze functionality
CoreumFoundation/coreum pull request #237
Opened 2022-10-20 11:53 UTC by miladz68

2022-10-20 13:18 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @miladz68)

___
*[`proto/coreum/asset/v1/asset.proto` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpWQDa0I177bWuvB9R:-NEpWQDa0I177bWuvB9S:b-icv06e) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/asset.proto#L14)):*
> ```protobuf
>   string issuer = 1;
>   string denom = 2;
>   bool is_freezable = 3;
> ```

I woul go with the enum instead, which now included only "Freezeing".
But later will include the:

* Freezeing
* Minting
* Burning
* Whitelisting

With such approach you won't need to copy pasted the flags, and final object will be smaller.

Same comment relates to other proto files.
___
*[`proto/coreum/asset/v1/query.proto` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpXYCD1NRU_FRcD7-l:-NEpXYCD1NRU_FRcD7-m:b-rs63bg) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/query.proto#L42)):*
> ```protobuf
> }
>   
> message  QueryFrozenBalancesResponse {
> ```

It should support pagination both request and response. 
___
*[`proto/coreum/asset/v1/tx.proto` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpX7Fb83XFP40g0DgY:-NEpX7Fb83XFP40g0DgZ:b-5ov59b) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/tx.proto#L38)):*
> ```protobuf
> 
> message MsgFreezeFungibleToken {
>   FreezeAction action = 1;
> ```

I would discuss it, probably better to split the messages.
___
*[`proto/coreum/asset/v1/tx.proto` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpXG8xDo_ck216vB4t:-NEpXG8xDo_ck216vB4u:bl8nzt7) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/tx.proto#L39)):*
> ```protobuf
> message MsgFreezeFungibleToken {
>   FreezeAction action = 1;
>   string token_issuer = 2;
> ```

Let's stick to the same name as we have in the Issue msg.


<!-- Sent from Reviewable.io -->

2022-10-21 08:48 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil)

___
*[`proto/coreum/asset/v1/asset.proto` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpWQDa0I177bWuvB9R:-NEtVA1o-S1TPxajlshw:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/asset.proto#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I woul go with the enum instead, which now included only "Freezeing".
But later will include the:

* Freezeing
* Minting
* Burning
* Whitelisting

With such approach you won't need to copy pasted the flags, and final object will be smaller.

Same comment relates to other proto files.

</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/query.proto` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpXYCD1NRU_FRcD7-l:-NEthsl04Ebftg1QPUsP:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/query.proto#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It should support pagination both request and response. 
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/tx.proto` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpX7Fb83XFP40g0DgY:-NEthpcn4MlxbqWxUN7v:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/tx.proto#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would discuss it, probably better to split the messages.
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/tx.proto` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NEpXG8xDo_ck216vB4t:-NEti-AI4UoUdKvO1iVZ:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/4fabb7635119b1ac362213565d7aa4cda636bb25/proto/coreum/asset/v1/tx.proto#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's stick to the same name as we have in the Issue msg.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-01 09:58 UTC, dzmitryhil requested changes
You have missed the import/export genesis part. The freezing is final here, so you can start doing it. 

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NFmbQedAly-E3cMRtYC:b7u0rm9)* status: 30 of 31 files reviewed, 47 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/freeze.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmXGfA-lGPnWfcGNSE:-NFmXGfA-lGPnWfcGNSF:bincsel) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/integration-tests/asset/freeze.go#L1)):*
> ```Go
> package asset
> ```

It would logical then to rename it "freeze_keeper.go" and move the issuance part to the "issuance_keeper" and the "keeper.go" will be with just initalisation and some common functions.
@ysv  ?
___
*[`proto/coreum/asset/v1/asset.proto` line 9 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmTlGv7l9O7o6Uk_DH:-NFmTlGw1XDYnbYWYkPu:bcim0y1) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/asset.proto#L9)):*
> ```protobuf
> 
> enum FungibleTokenOption {
>   Freezable = 0 ;
> ```

Unnecessary space 
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhgbBgADzAMUNI0M_f:-NFmTxhh5kEjyln4E2Sh:b-3ftrr2) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/proto/coreum/asset/v1/event.proto#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Maybe `...TokenFrozen/Unfrozen` ?
</blockquote></details>

Agree. The event should show the result. 
___
*[`proto/coreum/asset/v1/event.proto` line 26 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmU4nQC9OJV2uIFmkH:-NFmU4nQC9OJV2uIFmkI:b-3z0gtb) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/event.proto#L26)):*
> ```protobuf
> message EvnetFungibleTokenFreeze {
>   string account = 1;
>   repeated cosmos.base.v1beta1.Coin coins = 2 [
> ```

We decided to allow feeze just one coin. Why do we have the coins here? Same comment for a similar event?
___
*[`x/asset/client/cli/query.go` line 88 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmabuV1wCPSPoOU7CC:-NFmabuV1wCPSPoOU7CD:bxx4xwg) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/client/cli/query.go#L88)):*
> ```Go
> 
> 			account := args[0]
> 			res, err := queryClient.FrozenBalances(cmd.Context(), &types.QueryFrozenBalancesRequest{
> ```

Pagination?
___
*[`x/asset/client/cli/tx.go` line 148 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFm_qF-29cYQiPEBSl7:-NFm_qF-29cYQiPEBSl8:brmnj0f) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/client/cli/tx.go#L148)):*
> ```Go
> 
> 			issuer := clientCtx.GetFromAddress()
> 			account := args[0]
> ```

Validate that address is correct. That ValidateBasic will do it, but the output will be hard to read. Same for the all tx and queries. 
Or at least check what is its output in case of invalid account.
___
*[`x/asset/keeper/freeze.go` line 12 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmb2Nq0GpNVuyjPVlc:-NFmb2Nq0GpNVuyjPVld:be40kud) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L12)):*
> ```Go
> 
> // FreezeKeeper defines an interface which can be used to freeze/unfreeze balances
> type FreezeKeeper interface {
> ```

I don't see the use of that interface. You embedded into both Msg and Query server interfaces which is wrong. So once you move those methods to the corresponding interfaces t that interface won't be used. 
___
*[`x/asset/keeper/freeze.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmVpmbBXl7RJU7ItEl:-NFmVpmbBXl7RJU7ItEm:b-83mqgx) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L41)):*
> ```Go
> 
> 	bz := k.cdc.MustMarshal(&coin)
> ```

It would be nice to have all key building functions in one place.
___
*[`x/asset/keeper/freeze.go` line 42 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmYCsL8pjnkctF_t8F:-NFmYCsL8pjnkctF_t8G:b-rs1x2p) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L42)):*
> ```Go
> 	bz := k.cdc.MustMarshal(&coin)
> 
> 	frozenStore.Set([]byte(coin.Denom), bz)
> ```

You don't increase for the "Freeze" but decrease for the "Unfreeze" why? :-) IMHO we should increase here as well. 
___
*[`x/asset/keeper/freeze.go` line 62 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmYs6h-xMSYEpxLlGG:-NFmYs6h-xMSYEpxLlGH:b-8qc6kw) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L62)):*
> ```Go
> func (k Keeper) GetFrozenBalance(ctx sdk.Context, addr sdk.AccAddress, denom string) sdk.Coin {
> 	frozenStore := k.getFrozenBalanceStore(ctx, addr)
> 	frozenBalance := sdk.NewCoin(denom, sdk.NewInt(0))
> ```

sdk.NewCoin(denom, sdk.NewInt(0)) -> sdk.Coin{}
___
*[`x/asset/keeper/freeze.go` line 107 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmZpaJD0AET8FVowOP:-NFmZpaJD0AET8FVowOQ:b-uiiop1) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L107)):*
> ```Go
> 	} else {
> 		bz := k.cdc.MustMarshal(&newFrozenBalance)
> 		frozenStore.Set([]byte(coin.Denom), bz)
> ```

This comment is more relevant to the entire sample, but probably we should keep the access to the store in one place.
We should discuss it with the team. But for your PR I'm ok with what we have. 
___
*[`x/asset/keeper/grpc_query.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmZ73jEy4iQkd9JWKe:-NFmZ73jEy4iQkd9JWKf:b-k183w4) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/grpc_query.go#L49)):*
> ```Go
> 		return nil, sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, "invalid account address")
> 	}
> 	balances := qs.keeper.GetFrozenBalances(ctx, account)
> ```

What is the purpose of the pagination if you get all coins?
___
*[`x/asset/types/asset.go` line 4 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmUo-r2p-bLhWvjeMC:-NFmUo-r2p-bLhWvjeMD:b-qmse1o) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/asset.go#L4)):*
> ```Go
> 
> // FTHasOption checks weather an option is enable on a list of token options
> func FTHasOption(options []FungibleTokenOption, option FungibleTokenOption) error {
> ```

You use it only in the keeper so it should live there.
___
*[`x/asset/types/keys.go` line 38 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmVU9Z8y9vij1lWo7z:-NFmVU9Z8y9vij1lWo8-:bsto1tl) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/keys.go#L38)):*
> ```Go
> // CreateFrozenBalancesPrefix creates the prefix for an account's balances.
> func CreateFrozenBalancesPrefix(addr []byte) []byte {
> 	return append(FrozenBalancesPrefix, address.MustLengthPrefix(addr)...)
> ```

Use "store.JoinKeys" instead.
___
*[`x/asset/types/msgs.go` line 52 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmWLBgEpuTf0zfXaqG:-NFmWLBgEpuTf0zfXaqH:b-42pqmy) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/msgs.go#L52)):*
> ```Go
> 
> // GetSigners returns the required signers of this message type
> func (msg Ms [...]

2022-11-01 16:40 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 3 of 34 files reviewed, 46 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFixHmB4jZ5ZKomuUsH:-NFo1tbu-Y5xc3TFnWMW:b9rzvtx) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What do you think about running coreum/x/bank/keeper/benchmark_test.go & compare to master to preliminary see performance degradation after freezing implementation ? 
</blockquote></details>

I did not see meaningful changes in performance

master branch
```
Benchmark100KDenomBankSend/test-single-send-8         	   74112	     20356 ns/op	   10659 B/op	     172 allocs/op
Benchmark100KDenomBankSend/test-100k-denom-send-8     	   55047	     23165 ns/op	   10982 B/op	     175 allocs/op

```


freeze branch
```
Benchmark100KDenomBankSend/test-single-send-8         	   62970	     22678 ns/op	   11946 B/op	     197 allocs/op
Benchmark100KDenomBankSend/test-100k-denom-send-8     	   43824	     24252 ns/op	   13509 B/op	     195 allocs/op
```

___


<!-- Sent from Reviewable.io -->

2022-11-02 11:21 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 3 of 34 files reviewed, 43 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 9 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmTlGv7l9O7o6Uk_DH:-NFs3rGX2ZSunKtiWHY5:b-r0rpjj) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/asset.proto#L9)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not seeing that
</blockquote></details>

You fixed it.


<!-- Sent from Reviewable.io -->

2022-11-02 11:32 UTC, dzmitryhil requested changes
@miladz68  what about that comment?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NFs6CNe4VEAgFSQcP5o:b349oz2)* status: 3 of 34 files reviewed, 32 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/freeze.go` line 62 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmYs6h-xMSYEpxLlGG:-NFs5KBo66aiuvHZHZ87:b-efawa9) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L62)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

remove this code 
</blockquote></details>

I still see that code. "frozenBalance := sdk.NewCoin(denom, sdk.NewInt(0))" 
___
*[`x/asset/types/msgs.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmWS6_0XvBAu6jYsY8:-NFs5vrWDN4YrmJ5n3bB:bt3tggx) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/msgs.go#L59)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean "msg.Coin.Validate()" in that case you won't need that custom validation you wrote. 


<!-- Sent from Reviewable.io -->

2022-11-02 11:44 UTC, miladz68 reviewed
I did not comment here, since I am not sure we have decided how to treat the genesis here yet. 
do you want to register core token here or not ?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NFs8BBX49Mzi4eqbEV3:b-umtmb)* status: all files reviewed, 32 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 71 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhgjfF2WgTrHREy8DK:-NFs92ZZ9_DFtPiC25CM:b7l1nnv) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/pkg/config/deterministic_gas.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think it is worth discussion with the team if we really want to split all msg types to FT & NFT because I'm not sure if we mad 100% decision here
</blockquote></details>

Let's dicuss 
___
*[`x/asset/keeper/freeze.go` line 62 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmYs6h-xMSYEpxLlGG:-NFs8V5J2Tv1yYyQCqfl:bvknodk) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L62)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I still see that code. "frozenBalance := sdk.NewCoin(denom, sdk.NewInt(0))" 
</blockquote></details>

yeah, I need to denom to be present inside the coin, even if the balance is zero.
___
*[`x/asset/types/msgs.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmWS6_0XvBAu6jYsY8:-NFs8mAj6oK7dGdtZsiH:b-76gqiz) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/msgs.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean "msg.Coin.Validate()" in that case you won't need that custom validation you wrote. 
</blockquote></details>

I don't get it. I do `msg.Coin.Validate` but the custom validation is doing more than that. 


<!-- Sent from Reviewable.io -->

2022-11-03 11:00 UTC, dzmitryhil requested changes
Nope. This is not about the core token. Once you save something in the store it should be exported to the genesis, and once you imported it back the state should be restored.  

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NFx7H4_5OrJoF8AXMGn:bvkso6j)* status: all files reviewed, 32 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/freeze.go` line 62 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmYs6h-xMSYEpxLlGG:-NFx8JCwAPC-cE5s7ThA:b-xg27tn) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L62)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yeah, I need to denom to be present inside the coin, even if the balance is zero.
</blockquote></details>

I don't get you. You "Unmarshal" the bytes to struct, the denom will be in the bytes. So what is the need to add in the "sdk.NewCoin(denom, sdk.NewInt(0))" ? It will be erased anyway. 
___
*[`x/asset/types/msgs.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmWS6_0XvBAu6jYsY8:-NFx7vIx8K4xArMDBkoc:b-y4v5x1) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/msgs.go#L59)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't get it. I do `msg.Coin.Validate` but the custom validation is doing more than that. 
</blockquote></details>

1) When you validate the coin you don't wrap the error, so it's hard to understand where it was
2) It makes no sense to validate the denom here. Since that validation was done on the creation, this one is just confusing. 


<!-- Sent from Reviewable.io -->

2022-11-03 18:45 UTC, ysv requested changes
I agree with Dmitry

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NFyOWsT9Kny3_NG7DBH:bt1duit)* status: all files reviewed, 14 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFixHmB4jZ5ZKomuUsH:-NFyOdzf9S2r-NrxRdvy:bb3betu) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I did not see meaningful changes in performance

master branch
```
Benchmark100KDenomBankSend/test-single-send-8         	   74112	     20356 ns/op	   10659 B/op	     172 allocs/op
Benchmark100KDenomBankSend/test-100k-denom-send-8     	   55047	     23165 ns/op	   10982 B/op	     175 allocs/op

```


freeze branch
```
Benchmark100KDenomBankSend/test-single-send-8         	   62970	     22678 ns/op	   11946 B/op	     197 allocs/op
Benchmark100KDenomBankSend/test-100k-denom-send-8     	   43824	     24252 ns/op	   13509 B/op	     195 allocs/op
```

</blockquote></details>

it is around 10% degradation but it is ok more or less
Thanks for checking this

___
___
*[`integration-tests/asset/freeze.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFi3GFoDfO85d8YBSl_:-NFyRs0zC__T7tjq8Cee:b-azoqzw) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/integration-tests/asset/freeze.go#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think it is possible. 
</blockquote></details>

it should be possible but ok I will keep it for another PR to not block this
___
*[`integration-tests/asset/freeze.go` line 92 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFiAPzZ0DuKN_Kq2O_x:-NFySTp259DNt-EO2xK8:b1qxuos) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/integration-tests/asset/freeze.go#L92)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

bank balance is not changed, the user will see the same balance from bank, but will not be able to spend the frozen portion. 
</blockquote></details>

I see
Probably we shouldn't change bank response to not break compatibility with other clients/wallets etc
But maybe it is a good idea to add a single query to get detailed info about asset balance e.g:

```
{
  balance: 10,
  frozen: 5, 
  whitelisted: 20
}
```

Resolving it here will add to asset issuance ticket
___
*[`integration-tests/asset/freeze.go` line 1 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmXGfA-lGPnWfcGNSE:-NFyOqqb06n1bnExzBic:b-7tdf7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/integration-tests/asset/freeze.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

agree
___
*[`pkg/config/deterministic_gas.go` line 71 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhgjfF2WgTrHREy8DK:-NFyTSWmEs6_mLMWQg6e:b-ectgmc) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/pkg/config/deterministic_gas.go#L71)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Let's dicuss 
</blockquote></details>

will discuss tomorrow on the call
___
*[`proto/coreum/asset/v1/asset.proto` line 8 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhq7FM3QTVE6yrFxKx:-NFyTasZ--Dq5h8_p7j5:b4qijrt) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/proto/coreum/asset/v1/asset.proto#L8)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have no preference here, I will use feature
I honestly think it makes no differnece, because no matter what name we give it, people have to know the whole use case to understand it. so both names are equally valid. 
</blockquote></details>

thanks
lets use feature as we agreed on the call
___
*[`proto/coreum/asset/v1/event.proto` line 6 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyZcH44XFMn9HWNpH1:-NFyZcH44XFMn9HWNpH2:bdkqv0i) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/event.proto#L6)):*
> ```protobuf
> import "gogoproto/gogo.proto";
> import "cosmos/base/v1beta1/coin.proto";
> import "coreum/asset/v1/asset.proto";
> ```

to be discussed on the call:

I've just thought that we call our module assets but we operate with tokens
Do you think it is fine ?
Maybe everything should be renamed to FungibleAsset etc ? Or module to tokens (don't like this approach)
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyTkbw5JDW2hxRmUxk:-NFyTkbw5JDW2hxRmUxl:b-f29dvs) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/event.proto#L24)):*
> ```protobuf
> }
> 
> message EventFungibleTokenFrozen {
> ```

Needs to be discussed if we really want to separate everything for FT & NFT because some of events will be exactly the same and at points where we operate with just a denom it might be beneficial to keep less types
___
*[`proto/coreum/asset/v1/query.proto` line 21 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFitG0C5Nh4chsugHEI:-NFy_3M8-hecp5yfr-n8:b-6owo2m) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/query.proto#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have not seen a convention, and we define it ourselves. 
feel free to provice recomendations. 
I personally think the second `assets` is redundant but decided not to touch it to conform with url provided by Dima. 
</blockquote></details>

I don't like REST because of this confusion
But in Dmitri's endpoint it sort of makes sense because we fetch asset but here I'm not sure

Lets discuss on the call I don't have good name
Another question are we going at all use REST endponts ?

The best I can come up with is:
`/coreum/asset/v1/fts/{denom}`
`/coreum/asset/v1/fts/{denom}/balances/frozen`
___
*[`proto/coreum/asset/v1/query.proto` line 20 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFymlQt4i7wd0PF-b8B:-NFymlQt4i7wd0PF-b8C:b-vl04v6) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/query.proto#L20)):*
> ```protobuf
>   }
> 
>   rpc FrozenBalances(QueryFrozenBalancesRequest) returns (QueryFrozenBalancesResponse) {
> ```

I thought a bit more and not sure if we really need to have a separate query for each feature because it is inconvenient for FE & adds too much queries to our end I would probably prefer to have a single one with all details:

```
{
  balance: 100,
  frozen: 10,
  whitelisted: 200 // name is subject to change
}
```
___
*[`proto/coreum/asset/v1/tx.proto` line 41 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhhKgl0TrH6EQDQird:-NFyaBQW34rJWshtA6eS:bvy4x21) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/proto/coreum/asset/v1/tx.proto#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

basically there is no way to extract the address from the signature and pass it down to the module. 
so the flow is that we define what are the expected signatures for the message, and cosmos sdk ensures that the signatures are valid. so we need this field to tell cosmos sdk which signatures must be present, and if this message is routed to the module, then we know that the signature is now passed. 
In cli it is not set by the user. the user decides the wallet with which to sign, and address is set automatically. 
</bloc [...]

2022-11-03 19:50 UTC, ysv requested changes
> Reviewed 1 of 1 files at r5, 24 of 29 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NFytWAjCB2jzKML4Ssg:bj04hw8) (no related file):*
Why did we decide to implement freezing/unfreezing using credit/debit approach instead of set approach ?
pros:

1. Here is the freezing implementation in xrpl https://xrpl.org/trustset.html
3. more realistic business cases. A real use-case is for issuer to freeze/unfreeze whole balance in 90%.
4. What is the behaviour if someone has balance: 90, frozen: 90 and then someone sends more tokens ? will the address be able to use it freely ?
5. Lets say that we frozen someones balance and then we want to unfreeze it fully I don't want to guess user frozen balance and unfreeze exactly 123.456 USDT I just want to set frozen to 0 and that is it
6. less tx types

___
___
*[`proto/coreum/asset/v1/query.proto` line 20 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFymlQt4i7wd0PF-b8B:-NFyoyGw1inciB9bNeWF:b72f2d4) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/query.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought a bit more and not sure if we really need to have a separate query for each feature because it is inconvenient for FE & adds too much queries to our end I would probably prefer to have a single one with all details:

```
{
  balance: 100,
  frozen: 10,
  whitelisted: 200 // name is subject to change
}
```
</blockquote></details>

meaning of this should be like full balances query
___
*[`x/asset/keeper/freeze.go` line 15 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyqbkTEYobPr1QWC_L:-NFyqbkTEYobPr1QWC_M:b-u4pqvl) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L15)):*
> ```Go
> // FreezeFungibleToken freezes specified token from the specified account
> func (k Keeper) FreezeFungibleToken(ctx sdk.Context, issuer sdk.AccAddress, addr sdk.AccAddress, coin sdk.Coin) error {
> 	frozenStore := k.frozenBalanceStore(ctx, addr)
> ```

minor:
move frozenStore :=  initialization right before its usage
___
*[`x/asset/keeper/freeze.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyqoLbDCGPKTv_O6Y0:-NFyqoLbDCGPKTv_O6Y1:bnfms1o) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L26)):*
> ```Go
> 	bankBalance := k.bankKeeper.GetBalance(ctx, addr, coin.Denom)
> 	if bankBalance.IsLT(newFrozenBalance) {
> 		return sdkerrors.Wrapf(sdkerrors.ErrInsufficientFunds, "%s is not available", coin)
> ```

error could be improved to smth like:
`account balance is less then desired frozen balance`
___
*[`x/asset/keeper/freeze.go` line 48 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyr9M9CQgw7dTyy3IM:-NFyr9M9CQgw7dTyy3IN:b-vec38g) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L48)):*
> ```Go
> 	frozenBalance := frozenStore.getFrozenBalance(coin.Denom)
> 	if frozenBalance.IsLT(coin) {
> 		return sdkerrors.Wrap(sdkerrors.ErrInsufficientFunds, "not enough frozen coins")
> ```

`frozen balance is less than desired unfrozen balance`
___
*[`x/asset/keeper/freeze.go` line 67 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyvVDP5gD704SisrpG:-NFyvVDP5gD704SisrpH:b2btqt4) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L67)):*
> ```Go
> 
> 	if ft.Issuer != issuer.String() {
> 		return sdkerrors.Wrap(sdkerrors.ErrUnauthorized, "only issuer is authorized to perform this operation")
> ```

`address is unauthorized to perform this action` to avoid issuer
___
*[`x/asset/keeper/issue.go` line 54 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyvrnFD-uZ_nHDsfNl:-NFyvrnFD-uZ_nHDsfNm:bjgcyvd) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/issue.go#L54)):*
> ```Go
> }
> 
> func (k Keeper) getFungibleTokenDefinition(ctx sdk.Context, denom string) (types.FungibleTokenDefinition, error) {
> ```

so this is added as minimalistic version of `GetFungibleToken` and should be used in most internal places for better performance ?
___
*[`x/asset/types/errors.go` line 17 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFywDvk8X6j3EM2xnW0:-NFywDvk8X6j3EM2xnW1:bvl3n60) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/types/errors.go#L17)):*
> ```Go
> 	ErrInvalidDenomChecksum = sdkerrors.Register(ModuleName, 4, "denom checksum is not valid")
> 	// ErrInvalidDenomFormat is returned when the provided denom does not match required format
> 	ErrInvalidDenomFormat = sdkerrors.Register(ModuleName, 5, "denom format is not valid")
> ```

minor:
IDK if we can have some sort of error details in cosmos because I would merge both of them into a single: InvalidDenom error and in details write either it is format or checksum etc
___
*[`x/asset/types/ft.go` line 41 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFz0QZk44gDaJJCyHto:-NFz0QZk44gDaJJCyHtp:b-5ovvmc) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/types/ft.go#L41)):*
> ```Go
> 
> // ValidateDenomChecksum ensures that the checksum value of user created denom is valid
> func ValidateDenomChecksum(denom string) error {
> ```

when I look into this code I don't feel confident about possible security cases
can you please add TODO here and think about possible issues when working on PR with more strict format of denom

1. I also think that we should use named regexp matching to extract parts of denom
2. we should have strict length of checksum also I guess

Add all of this to todo
___
*[`x/asset/types/msgs.go` line 93 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFz13bJ-wg4mXz0gz7j:-NFz13bJ-wg4mXz0gz7k:b-m3vdbq) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/types/msgs.go#L93)):*
> ```Go
> 
> // GetSigners returns the required signers of this message type
> func (msg MsgUnfreezeFungibleToken) GetSigners() []sdk.AccAddress {
> ```

minor:
so here we define this method and cosmos sdk verifies that `msg.issuer == tx.signer` ?
___
*[`x/asset/types/msgs_test.go` line 75 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFz1KsCAJZyabEAvygs:-NFz1KsCAJZyabEAvygt:bms9jra) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/types/msgs_test.go#L75)):*
> ```Go
> 			name: "valid msg",
> 			message: types.MsgFreezeFungibleToken{
> 				Issuer:  "cosmos1jgfmlcywhqwctenjeljs2huxw7l4p6apgaclyn",
> ```

why do we have cosmos everywhere but not core ?


<!-- Sent from Reviewable.io -->

2022-11-04 08:40 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 20 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NG0YvAzAUOJaXx06ZIr:b-7cy6he) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Why did we decide to implement freezing/unfreezing using credit/debit approach instead of set approach ?
pros:

1. Here is the freezing implementation in xrpl https://xrpl.org/trustset.html
3. more realistic business cases. A real use-case is for issuer to freeze/unfreeze whole balance in 90%.
4. What is the behaviour if someone has balance: 90, frozen: 90 and then someone sends more tokens ? will the address be able to use it freely ?
5. Lets say that we frozen someones balance and then we want to unfreeze it fully I don't want to guess user frozen balance and unfreeze exactly 123.456 USDT I just want to set frozen to 0 and that is it
6. less tx types

</blockquote></details>

we need to discuss it then, we said we want to freeze a portion of the balance, not the account. 

___
___
*[`proto/coreum/asset/v1/event.proto` line 6 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyZcH44XFMn9HWNpH1:-NG0ZTCdAsGzV75JLvBR:b-smssfy) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/event.proto#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to be discussed on the call:

I've just thought that we call our module assets but we operate with tokens
Do you think it is fine ?
Maybe everything should be renamed to FungibleAsset etc ? Or module to tokens (don't like this approach)


</blockquote></details>

I originally disliked the asset concept tbh. we have ft and nft, and we have some additional behavior applied on top of those. The name asset does not fit anywhere in that scheme. 
let's discuss at the call
___
*[`proto/coreum/asset/v1/query.proto` line 20 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFymlQt4i7wd0PF-b8B:-NG0m3zg84XGpteJv-g-:b5od37a) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/query.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

meaning of this should be like full balances query
</blockquote></details>

I also thought about it. but really the only query for balance is freezing. other features (white list, mint, burn) do not have a balance on them. 
___
*[`x/asset/keeper/freeze.go` line 62 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmYs6h-xMSYEpxLlGG:-NG0exBW0ndAeYCAPfXM:b3rduus) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/keeper/freeze.go#L62)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't get you. You "Unmarshal" the bytes to struct, the denom will be in the bytes. So what is the need to add in the "sdk.NewCoin(denom, sdk.NewInt(0))" ? It will be erased anyway. 
</blockquote></details>

if bz is nil, I need to have a coin returned with correct denom and amount initialized to zero.  I use in later calculations
___
*[`x/asset/keeper/freeze.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyqoLbDCGPKTv_O6Y0:-NG0c4yf9LufbMOUH2uB:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

error could be improved to smth like:
`account balance is less then desired frozen balance`
</blockquote></details>

Done.
___
*[`x/asset/keeper/freeze.go` line 48 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyr9M9CQgw7dTyy3IM:-NG0cNwn92pcEMUoPOwJ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`frozen balance is less than desired unfrozen balance`
</blockquote></details>

Done.
___
*[`x/asset/keeper/freeze.go` line 67 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyvVDP5gD704SisrpG:-NG0cizxEW5nlEGAF9Of:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`address is unauthorized to perform this action` to avoid issuer
</blockquote></details>

Done.
___
*[`x/asset/keeper/grpc_query.go` line 51 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFiiQ7BBIDjFcSfsCU9:-NG0fH4v4WQI7itr5x1Y:bcr3chm) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/x/asset/keeper/grpc_query.go#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

sorry but probably balances isn't the best option because it is confusing & can easily be mixed up with bank
</blockquote></details>

I doubt it is confusing. since the user knows they are querying for frozen balances, not the bank balances.
___
*[`x/asset/keeper/issue.go` line 54 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyvrnFD-uZ_nHDsfNl:-NG0fn68D0_6KzfKlmFy:b2nign6) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/issue.go#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so this is added as minimalistic version of `GetFungibleToken` and should be used in most internal places for better performance ?
</blockquote></details>

yes
___
*[`x/asset/keeper/keeper_test.go` line 127 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhocnd0yCuc3NlqH83:-NG0fzzo4pSSGIh_a-Gx:ba0fn3c) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/x/asset/keeper/keeper_test.go#L127)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes but literally put `core`. Even thought it will likely fail on regexp check or trying to get asset from store It is still an edge case in our system and we need to test it everywhere. Because if we forget some check we might freeze core unintentionally etc
</blockquote></details>

adding core will pass and the denom will be created. the regexp validation is not yet implemented. we may add that check to the test after we implement it ?
___
*[`x/asset/keeper/keeper_test.go` line 127 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFykqkHCYQPIuHy41PN:-NG0gIeAEkIvdBjIQjG7:b-n1hef7) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/keeper_test.go#L127)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

another thought came up:
Do we make validation of denom in ValidateBasic of msg ? Because we know it's expected format so we can validate it.
Then I prefer to have another test for real-like denom `btc-devcore123...` which passes this validation but fails on reading denom from keeper
</blockquote></details>

symbol validation is part of another task. we can discuss it after I make a PR for it after this one is merged. 
___
*[`x/asset/keeper/keeper_test.go` line 132 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyldNY0BqS-J4jWDJg:-NG0iKUf2UcmveBZ9bgC:brf2gfn) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/keeper_test.go#L132)):*
<detai [...]

2022-11-04 09:39 UTC, wojtek-coreum requested changes
> Reviewed 3 of 28 files at r3, 1 of 1 files at r5, 25 of 29 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 39 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/asset/freeze.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bCog4ZOobdQZCjSv:-NG0bCog4ZOobdQZCjSw:b-3gzoej) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L1)):*
> ```Go
> package asset
> ```

I miss another tests to verify that:
- non-freezable asset can't be frozen
- it's not possible to unfreeze more than is frozen
- user has balance of 500 and I freeze 400 first and then freeze 200 again, second operation fails
- user tries to issue some transaction but his non-frozen balance doesn't allow to cover tx fees
___
*[`integration-tests/asset/freeze.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0adfWBx_TLZE0sfOu:-NG0adfX4hpNWy90JC5S:bwks663) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L32)):*
> ```Go
> 	randomAddress := chain.GenAccount()
> 	requireT.NoError(chain.Faucet.FundAccounts(ctx,
> 		testing.NewFundedAccount(issuer, chain.NewCoin(sdk.NewInt(1000_000))),
> ```

@miladz68 @dzmitryhil @ysv 

Are we abandoning an assumption that we fund only the exact amount which is needed to cover the fees and transfers?
___
*[`integration-tests/asset/freeze.go` line 40 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0axnRDksERuFeTNNJ:-NG0axnRDksERuFeTNNK:b-xlw0h) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L40)):*
> ```Go
> 	msg := &assettypes.MsgIssueFungibleToken{
> 		Issuer:        issuer.String(),
> 		Symbol:        "BTC",
> ```

Minor: I would prefer to not use real-life names in tests. It's my personal taste so I'm not blocking here.
___
*[`integration-tests/asset/freeze.go` line 75 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bw8e0Rzp5-r19SNc:-NG0bw8e0Rzp5-r19SNd:b-lggeyf) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L75)):*
> ```Go
> 	)
> 	requireT.Error(err)
> 	assertT.True(sdkerrors.IsOf(err, sdkerrors.ErrUnauthorized))
> ```

Minor: IMO `sdkerrors.ErrUnauthorized.Is(err)` is a simpler syntax
___
*[`integration-tests/asset/freeze.go` line 81 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0cRN287WOqrzLI37c:-NG0cRN287WOqrzLI37d:b-x3zn72) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L81)):*
> ```Go
> 		Issuer:  issuer.String(),
> 		Account: recipient.String(),
> 		Coin:    sdk.NewCoin(denom, sdk.NewInt(500)),
> ```

Could you use the amount which not exactly a half of original sum, like 400 or 600? Otherwise we may not catch errors where e.g. `FrozenBalance` returns an unfrozen one instead accidentally.
___
*[`integration-tests/asset/freeze.go` line 143 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0dqUb2mO6wYzuqs2j:-NG0dqUc9arFxoUFMqFV:buidr3r) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L143)):*
> ```Go
> 
> 	// unfreeze 200 tokens and try send 250 tokens
> 	unFreezeMsg := &assettypes.MsgUnfreezeFungibleToken{
> ```

"unfreeze" is a single word, so no "unFreeze"
___
*[`integration-tests/asset/issue.go` line 59 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0eKL1BEJ86t1hJHMb:-NG0eKL1BEJ86t1hJHMc:b4iu9pn) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/issue.go#L59)):*
> ```Go
> 		Recipient:     msg.Recipient,
> 		InitialAmount: msg.InitialAmount,
> 		Features:      []assettypes.FungibleTokenFeature{},
> ```

Is it needed? Shouldn't `nil` be treated like an empty slice?
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyTkbw5JDW2hxRmUxk:-NG0f2EU-yNakY01KSrM:b-3p77n4) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/event.proto#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Needs to be discussed if we really want to separate everything for FT & NFT because some of events will be exactly the same and at points where we operate with just a denom it might be beneficial to keep less types
</blockquote></details>

My current position is that I prefer to separate everything instead of thinking what might be common and what not and later fix issues if we are wrong about those assumptions.
___
*[`proto/coreum/asset/v1/query.proto` line 20 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFymlQt4i7wd0PF-b8B:-NG0frLI3u1tYbDgTc-8:b-m5wie2) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/query.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

meaning of this should be like full balances query
</blockquote></details>

I agree. It's better to provide bank-like query providing additional information related to all the features of the token
___
*[`proto/coreum/asset/v1/tx.proto` line 41 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFygmCB7Pn6mB69K-q8:-NG0gYax3vRzfT-oIxxX:bzdz29f) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/tx.proto#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Since we agreed on permissions model today I think it makse sense to rename this field because later not only issuer will be able to do it
Maybe we should name it: `freezer` or smth like this ? I actually don't like freezer much because then we need unfreezer, whitelister etc. Maybe smth similar to `admin` in meaning

To be discussed
</blockquote></details>

Let's not mix concepts. For now we agreed that only issuer is an admin so let's stick to `issuer`. Otherwise in a year from now nobody will remember why we did it the other way. Once permissions are implemented we will adjust everything accordingly.
___
*[`x/asset/client/cli/query.go` line 71 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0hAkZDwsUYSAlLhGM:-NG0hAkZDwsUYSAlLhGN:b-xfyvy2) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/client/cli/query.go#L71)):*
> ```Go
> func CmdQueryFungibleTokenFrozenBalances() *cobra.Command {
> 	cmd := &cobra.Command{
> 		Use:   "ft-frozen-balances [account]",
> ```

Could we create separate scope `ft` for fungible-token-related commands? We have those `ft-` prefixes everywhere now. Might be a separate task.

Moreover, in queries we use `ft-*` but in txes we use `*-ft`
___
*[`x/asset/client/cli/query_test.go` line 45 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0hY4--Xf9yE_nY91l:-NG0hY4--Xf9yE_nY91m:bxtub52) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/client/cli/query_test.go#L45)):*
> ```Go
> 		Symbol:      symbol,
> 		Description: "",
> 		Features:    []types.FungibleTokenFeature{},
> ```

Is it needed?
___
*[`x/asset/client/cli/tx.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0kSVxDzetjhI8SJUk:-NG0kSVxDzetjhI8SJUl:bippke8) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/cl [...]

2022-11-04 13:17 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 39 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NG1S-SW9xW0vO-fIvqt:b-utrmo5) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need to discuss it then, we said we want to freeze a portion of the balance, not the account. 
</blockquote></details>

It was decided on the call that this use case will covered via `ban` feature
We should allow the frozen balance to go above the current balance. 

___
___
*[`pkg/config/deterministic_gas.go` line 71 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhgjfF2WgTrHREy8DK:-NG1drJK5tEcebdBpX4Q:bh8u5mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/pkg/config/deterministic_gas.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

will discuss tomorrow on the call
</blockquote></details>

Concluded in the call to keep them separated.


<!-- Sent from Reviewable.io -->

2022-11-07 12:10 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 30 of 34 files reviewed, 38 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/freeze.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0adfWBx_TLZE0sfOu:-NGGzY-hEG6x14FxyK45:blf47ys) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 @dzmitryhil @ysv 

Are we abandoning an assumption that we fund only the exact amount which is needed to cover the fees and transfers?
</blockquote></details>

Nope. You are right. The test should take just fixed amount required for the test.
___
*[`x/asset/types/msgs.go` line 59 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFmWS6_0XvBAu6jYsY8:-NGGzvMt5txvKpMjywWs:b20xhtp) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/x/asset/types/msgs.go#L59)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's dicsuss it on a call, it will be faster. 
</blockquote></details>

I still see the "ValidateDenom" here.


<!-- Sent from Reviewable.io -->

2022-11-07 12:11 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 38 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-08 12:27 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 21 of 38 files reviewed, 36 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NGHDO5A5TpFkhkzHWzN:bjqj4bd) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It was decided on the call that this use case will covered via `ban` feature
We should allow the frozen balance to go above the current balance. 
</blockquote></details>

It is now possible to set freeze amount higher than the current balance. also if unfreeze amount is less than the frozen balance, it will not error out, but set it to zero.

___
___
*[`integration-tests/asset/freeze.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bCog4ZOobdQZCjSv:-NGLCnJi7gFePUMQ1sYC:bqs6hvm) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I miss another tests to verify that:
- non-freezable asset can't be frozen
- it's not possible to unfreeze more than is frozen
- user has balance of 500 and I freeze 400 first and then freeze 200 again, second operation fails
- user tries to issue some transaction but his non-frozen balance doesn't allow to cover tx fees
</blockquote></details>

1. Done
2. it is now decided that it is possible. 
3. it is now decided if you unfreeze more the frozen balance, it should go to zero and should not error out. 
4. fees are covered via core, which is not freezable. 
___
*[`integration-tests/asset/freeze.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0adfWBx_TLZE0sfOu:-NGLrrLUEjd9jl-WB28g:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Nope. You are right. The test should take just fixed amount required for the test.
</blockquote></details>

Done.
___
*[`integration-tests/asset/freeze.go` line 81 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0cRN287WOqrzLI37c:-NGLszW_E-YAY6qMicp8:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L81)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you use the amount which not exactly a half of original sum, like 400 or 600? Otherwise we may not catch errors where e.g. `FrozenBalance` returns an unfrozen one instead accidentally.
</blockquote></details>

Done.
___
*[`integration-tests/asset/freeze.go` line 143 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0dqUb2mO6wYzuqs2j:-NGLt6Cs9psTzpJ3fP1i:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L143)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"unfreeze" is a single word, so no "unFreeze"
</blockquote></details>

Done.
___
*[`integration-tests/asset/issue.go` line 59 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0eKL1BEJ86t1hJHMb:-NGLtEIJ4wcaH1ggS05-:bd4yq1l) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/issue.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it needed? Shouldn't `nil` be treated like an empty slice?
</blockquote></details>

nil and empty slice are not equal in the eyes of the assert package, so the test fails
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyTkbw5JDW2hxRmUxk:-NGLtSq7268RajVQ7Yzs:bvgbx3h) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/event.proto#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

My current position is that I prefer to separate everything instead of thinking what might be common and what not and later fix issues if we are wrong about those assumptions.
</blockquote></details>

Decided to keep them separated for now. 
___
*[`proto/coreum/asset/v1/query.proto` line 21 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFitG0C5Nh4chsugHEI:-NGLuJzK4EdyDsxLUjQh:b2sanf2) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/query.proto#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like REST because of this confusion
But in Dmitri's endpoint it sort of makes sense because we fetch asset but here I'm not sure

Lets discuss on the call I don't have good name
Another question are we going at all use REST endponts ?

The best I can come up with is:
`/coreum/asset/v1/fts/{denom}`
`/coreum/asset/v1/fts/{denom}/balances/frozen`

</blockquote></details>

updated, please check. 
___
*[`proto/coreum/asset/v1/query.proto` line 20 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFymlQt4i7wd0PF-b8B:-NGLtYHRASGlRG4iGYxP:b-5xh48e) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/query.proto#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I agree. It's better to provide bank-like query providing additional information related to all the features of the token
</blockquote></details>

I think It was decided on the call not to provide it now. 
___
*[`proto/coreum/asset/v1/tx.proto` line 41 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFygmCB7Pn6mB69K-q8:-NGLuOldBsSD9Mn0wedG:bmgy1fs) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/tx.proto#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's not mix concepts. For now we agreed that only issuer is an admin so let's stick to `issuer`. Otherwise in a year from now nobody will remember why we did it the other way. Once permissions are implemented we will adjust everything accordingly.
</blockquote></details>

It was decided on the call to postpone this dicsussion
___
*[`x/asset/client/cli/query.go` line 71 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0hAkZDwsUYSAlLhGM:-NGM-vcl2Pi-lOw9fPTI:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/client/cli/query.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could we create separate scope `ft` for fungible-token-related commands? We have those `ft-` prefixes everywhere now. Might be a separate task.

Moreover, in queries we use `ft-*` but in txes we use `*-ft`
</blockquote></details>

Done.
___
*[`x/asset/client/cli/query_test.go` line 45 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0hY4--Xf9yE_nY91l:-NGM-wlS5wVqyws3mcuH:b-d65wl8) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/client/cli/query_test.go#L45)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

yeap, it will not pass the assertion otherwise. 
___
*[`x/asset/client/cli/tx.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0kSVxDzetjhI8SJUk:-NGM08Av7fkTGmOBC9LR:b-896fix) ([raw file](https://github.com/coreumfoundat [...]

2022-11-08 13:32 UTC, miladz68 reviewed
This is now done for the freezing
The part for the fungible tokens should be done in a separate task.

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NGMREFL9_q6gLrwQe_f:b-8k6jkp)* status: 21 of 39 files reviewed, 36 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-08 14:23 UTC, dzmitryhil reviewed
I would do it step by step. Since the developer of the future knows how to import and export in the best way. 

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237#-:-NGMb_IGB4_o_hBm5Ngk:b-6t5oz0)* status: 21 of 39 files reviewed, 35 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-08 14:23 UTC, dzmitryhil reviewed
> Reviewed 18 of 18 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 35 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-08 23:05 UTC, ysv requested changes
> Reviewed 2 of 29 files at r6, 1 of 3 files at r9, 18 of 18 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 27 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NGOGB3t2De7NASL60h1:b32wtd) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is now possible to set freeze amount higher than the current balance. also if unfreeze amount is less than the frozen balance, it will not error out, but set it to zero.
</blockquote></details>

ok

___
___
*[`integration-tests/asset/freeze.go` line 136 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOJB-kCggojMGBduuh:-NGOJB-kCggojMGBduui:bopwl19) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/integration-tests/asset/freeze.go#L136)):*
> ```Go
> 	assertT.True(sdkerrors.ErrUnauthorized.Is(err))
> 
> 	// freeze 600 tokens
> ```

fix/remove comment (outdated value 600 -> 400)
___
*[`integration-tests/asset/freeze.go` line 244 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOJMMB9hTQOBwW_IAo:-NGOJMMB9hTQOBwW_IAp:b-ndeda) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/integration-tests/asset/freeze.go#L244)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// unfreeze 400 tokens (frozen balance is 200), it should work and unfreeze up to 0
> ```

I thought that we decided that unfreeze should specify exact amount not bigger than current frozen balance. Or I skipped point when we changed this ?
___
*[`proto/coreum/asset/v1/query.proto` line 21 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFitG0C5Nh4chsugHEI:-NGOKO5q3SPis21g1pGj:b-ujbec9) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/query.proto#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

updated, please check. 
</blockquote></details>

I think it is ok for me (still don't like REST for this)

@wojtek-coreum @dzmitryhil does current naming makes sense for you ?
___
*[`proto/coreum/asset/v1/query.proto` line 39 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOKcao3LtTwOXWd9aO:-NGOKcao3LtTwOXWd9aP:b-ly0kgk) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/proto/coreum/asset/v1/query.proto#L39)):*
> ```protobuf
> }
> 
> message  QueryFrozenBalancesRequest {
> ```

minor: you have an extra whitespace here and in the next message definitions
___
*[`proto/coreum/asset/v1/tx.proto` line 41 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFygmCB7Pn6mB69K-q8:-NGOGqCm8cuMDmn3Rbsj:bx6tys0) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/proto/coreum/asset/v1/tx.proto#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It was decided on the call to postpone this dicsussion
</blockquote></details>

yes
I've created a separate task for this
We can merge it as it is for now
___
*[`x/asset/genesis_test.go` line 24 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOLhCMAz4Km_VlmX5_:-NGOLhCMAz4Km_VlmX5a:bbe78n) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/genesis_test.go#L24)):*
> ```Go
> 	assetKeeper := testApp.AssetKeeper
> 	issuer := sdk.AccAddress(ed25519.GenPrivKey().PubKey().Address())
> 	denom := types.BuildFungibleTokenDenom("ABC", issuer)
> ```

Can't we execute IssueFungibleToken instead of generating denom directly here ?
I think we should be able to run txs on simapp don't we ?

I think it makes sense to have multiple variants of tokens here (with freezing enabled & disabled) to fully test export/import.

I would probably do this using a similar approach as it is done in integration-tests.
So issue a real denom, freeze issued denom using msgs or by calling keeper & then export
Or it is too complicated ?

Because currently you directly operate with internal freezing things

If this is complicated to implement I will not insist much
___
*[`x/asset/genesis_test.go` line 28 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOMaRq-ay48jKLHexF:-NGOMaRq-ay48jKLHexG:bl1ujde) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/genesis_test.go#L28)):*
> ```Go
> 
> 	var balances []types.Balance
> 	for i := 0; i < 1; i++ {
> ```

minor:
Well since we already have loop here lets put something more interesting than 1 
Or it is complicated to assert ? if it is then ignore the comment
___
*[`x/asset/keeper/freeze.go` line 54 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOQ-HR0kmSyK15q92t:-NGOQ-HU1loHijzvfQMf:b-myh9ji) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/keeper/freeze.go#L54)):*
> ```Go
> 
> // SetFrozenBalances sets the frozen balances of a specified account
> func (k Keeper) SetFrozenBalances(ctx sdk.Context, addr sdk.AccAddress, coins sdk.Coins) {
> ```

do we have a test somewhere where we try to freeze & unfreeze literally 0 of some coin ?
I think it is worth adding as another edge case. I think that 0 shouln't be allowed WDYT ?
___
*[`x/asset/keeper/freeze.go` line 196 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOS-RF4nsKCYtQPwS8:-NGOS-RF4nsKCYtQPwS9:bkvxq75) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/keeper/freeze.go#L196)):*
> ```Go
> 
> // isFeatureEnabled checks weather a feature is present on a list of token features
> func isFeatureEnabled(features []types.FungibleTokenFeature, feature types.FungibleTokenFeature) error {
> ```

not-critical:
AFAIK It is common for this inquiry (`func isSmth...`) functions to return bool 
___
*[`x/asset/keeper/keeper_test.go` line 127 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFhocnd0yCuc3NlqH83:-NG1pCeP5g-Z5HnN_2av:b-u5hbmi) ([raw file](https://github.com/coreumfoundation/coreum/blob/8dfc5cad37c70ce6313d2271c10f073bd3884afd/x/asset/keeper/keeper_test.go#L127)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

adding core will pass and the denom will be created. the regexp validation is not yet implemented. we may add that check to the test after we implement it ?
</blockquote></details>

Add description to task in clickup
___
*[`x/asset/types/errors.go` line 17 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOTh0V36IYCZj9HJtC:-NGOTh0V36IYCZj9HJtD:b-42310c) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/types/errors.go#L17)):*
> ```Go
> 	ErrInvalidDenom = sdkerrors.Register(ModuleName, 4, "denom is not valid")
> 	// ErrInvalidKey is returned when the provided store key is invalid
> 	ErrInvalidKey = sdkerrors.Register(ModuleName, 5, "valid key")
> ```

-> "invalid key"
___
*[`x/asset/types/keys.go` line 38 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0qZGC76cKOrzo52Z_:-NGOTu2mEQN-EKtD-C_C:b-vlzeny) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/types/keys.go#L38)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is the standard cosmos way. The benefit is that when I need to extract the keys from the prefix (when doing full genesis export) I don't need to recreate another algorithm, I can use the function in the bank module. 
</blockquote></details>

does it mean we can use it everywhere instead of JoinKeysWithLength ?
___
*[`x/asse [...]

2022-11-09 08:21 UTC, dzmitryhil reviewed
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 27 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`proto/coreum/asset/v1/query.proto` line 21 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFitG0C5Nh4chsugHEI:-NGQTXsDB8ZQX0BBJO-h:b42xvry) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/query.proto#L21)):*
> /coreum/asset/v1/fts/{denom}
> /coreum/asset/v1/fts/{denom}/balances/frozen
This is ok. 


<!-- Sent from Reviewable.io -->

2022-11-09 13:50 UTC, wojtek-coreum requested changes
> Reviewed 11 of 18 files at r10, 3 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NGRdfnq9LLqPRD3G1rr:b4y9kgj) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

I would still say that unfreezing more than is frozen is a weird idea. I would prefer to be strict here to protect against possible mistakes in calculations done by someone who tries doing this.

___
___
*[`integration-tests/asset/freeze.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bCog4ZOobdQZCjSv:-NGRVvSy0RGfbVisqbCU:b-52vyy4) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

1. Done
2. it is now decided that it is possible. 
3. it is now decided if you unfreeze more the frozen balance, it should go to zero and should not error out. 
4. fees are covered via core, which is not freezable. 
</blockquote></details>

3. Now I see that we agreed to freeze more, but it should be tested then
___
*[`integration-tests/asset/freeze.go` line 106 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRXft7AxglNVvwMkO6:-NGRXft82Uc4N4n9Q4CP:b-ubeie1) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/integration-tests/asset/freeze.go#L106)):*
> ```Go
> 	unfreezableDenom := fungibleTokenIssuedEvt.Denom
> 
> 	// try to freeze unfreezable token
> ```

This part is independent, could we test it in another test?
___
*[`integration-tests/asset/freeze.go` line 118 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRXt0n5t_HPi2TyYyE:-NGRXt0n5t_HPi2TyYyF:b-jetagu) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/integration-tests/asset/freeze.go#L118)):*
> ```Go
> 		freezeMsg,
> 	)
> 	requireT.Error(err)
> ```

this is not needed, as the next line covers it
___
*[`proto/coreum/asset/v1/genesis.proto` line 20 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRYcmDCjNoPzJRnnHS:-NGRYcmE-oVaUWEaIobn:bu6q53t) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/proto/coreum/asset/v1/genesis.proto#L20)):*
> ```protobuf
> // Balance defines an account address and balance pair used in the bank module's
> // genesis state.
> message Balance {
> ```

Are you sure there is nothing to reuse from cosmos sdk? Cosmos already dumps balances in bank module somehow
___
*[`proto/coreum/asset/v1/query.proto` line 21 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFitG0C5Nh4chsugHEI:-NGRYxOH5OT1wkiTlgvL:bs8d14e) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/query.proto#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> /coreum/asset/v1/fts/{denom}
> /coreum/asset/v1/fts/{denom}/balances/frozen
This is ok. 
</blockquote></details>

I would drop `asset` part completely, but I think we decided to remove it later, in separate task
___
*[`x/asset/client/cli/tx.go` line 192 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRZd67EClAiEG__UbM:-NGRZd67EClAiEG__UbN:b36dc70) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/client/cli/tx.go#L192)):*
> ```Go
> func CmdTxUnfreezeFungibleToken() *cobra.Command {
> 	cmd := &cobra.Command{
> 		Use:   "ft unfreeze [account_address] [amount] --from [issuer]",
> ```

"ft" should not be here
___
*[`x/asset/keeper/freeze.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyqoLbDCGPKTv_O6Y0:-NGRZjo-3F9OADwPTU8X:b-gkbwfe) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It was decided to freeze up to zero, instead of giving error. 
</blockquote></details>

Didn't we change the decision today?
___
*[`x/asset/keeper/freeze.go` line 196 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOS-RF4nsKCYtQPwS8:-NGRbDU_4pvXs8GTEJQt:bq4q6oz) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/keeper/freeze.go#L196)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

chanaged
I prefer to sometimes return errors in such cases, because it allows to return different types of error depending on the conditions. returninng a bool might lose some failure information. maybe a better name could be found than isSm.. but I think it is a good name. 
</blockquote></details>

so you could rename function to `validateFeatureEnabled` and still return an error
___
*[`x/asset/keeper/freeze.go` line 115 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRc1wYD1QT5f_jkFej:-NGRc1wYD1QT5f_jkFek:b-d1qnei) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/keeper/freeze.go#L115)):*
> ```Go
> func (k Keeper) GetAccountsFrozenBalances(ctx sdk.Context, pagination *query.PageRequest) ([]types.Balance, *query.PageResponse, error) {
> 	frozenStore := k.frozenBalancesStore(ctx)
> 	balances := make([]types.Balance, 0)
> ```

this is just `var balances []types.Balance`
___
*[`x/asset/keeper/freeze.go` line 116 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRcKjg25TNUnLI12Q2:-NGRcKjg25TNUnLI12Q3:bum2q2f) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/keeper/freeze.go#L116)):*
> ```Go
> 	frozenStore := k.frozenBalancesStore(ctx)
> 	balances := make([]types.Balance, 0)
> 	mapAddressToBalancesIdx := make(map[string]int)
> ```

why not just putting this map into exported genesis? It should be correctly encoded to key-value (address: coins) pairs
___
*[`x/asset/keeper/freeze.go` line 120 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRbTOf7dIDFt2lbTD8:-NGRbTOf7dIDFt2lbTD9:b-6pn912) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/keeper/freeze.go#L120)):*
> ```Go
> 		address, err := types.AddressFromBalancesStore(key)
> 		if err != nil {
> 			k.Logger(ctx).With("key", key, "err", err).Error("failed to get address from frozen balances store")
> ```

If you return an error, logging should not be needed because error will be logged somewhere anyway. Error message should just contain all the important information
___
*[`x/asset/types/keys.go` line 38 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0qZGC76cKOrzo52Z_:-NGRczcvEjedmVLZ12Zy:b-8x2dxf) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/types/keys.go#L38)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think so, this is one is for prefixing with addresses, JoinKeysWithLength is more generic. 
</blockquote></details>

@ysv `address.MustLengthPrefix` is limited to 255 characters


<!-- Sent from Reviewable.io -->

2022-11-09 19:32 UTC, ysv requested changes
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NGSokrX-ip95_trKgCW:b-ew3kn1) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would still say that unfreezing more than is frozen is a weird idea. I would prefer to be strict here to protect against possible mistakes in calculations done by someone who tries doing this.
</blockquote></details>

I agree 
@miladz68 pls fix this

___
___
*[`integration-tests/asset/freeze.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bCog4ZOobdQZCjSv:-NGSoqkyBDOGRHfsFI2o:bn1a6nd) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

3. Now I see that we agreed to freeze more, but it should be tested then
</blockquote></details>

agree with Wojtek
___
*[`integration-tests/asset/freeze.go` line 244 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOJMMB9hTQOBwW_IAo:-NGSowCxCOZxsFILBIii:bu2et53) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/integration-tests/asset/freeze.go#L244)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well I think it was you that mentioned if unfreeze is more than balance, then it should just go to zero and not below zero. Do you prefer that to return error in this scenario ?
</blockquote></details>

as discussed on the call lets not allow to unfreeze more than balance
resolving this comment since we already have one requiring this change
___
*[`proto/coreum/asset/v1/query.proto` line 21 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFitG0C5Nh4chsugHEI:-NGSphxA-4_CiGBLvKao:b3duwa2) ([raw file](https://github.com/coreumfoundation/coreum/blob/fc7b36ef3f27fe62282085701f68817663d6659c/proto/coreum/asset/v1/query.proto#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would drop `asset` part completely, but I think we decided to remove it later, in separate task
</blockquote></details>

ok resolving
___
*[`x/asset/genesis_test.go` line 24 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOLhCMAz4Km_VlmX5_:-NGSq3AC2UjZWwMB2uhc:b-blhlbp) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/genesis_test.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Import/export is directly wokring with keepers and not transactions. to work with transactions you need up and running chain which requires genesis first. 
</blockquote></details>

I see
Can we call keeper's `IssueFungibleToken` and then `FreezeFungibleToken` (SetFrozenBalance is ok more or less also) so we have more realistic tests testing from outside and not calling internal asset module logic (`BuildFungibleTokenDenom`)
___
*[`x/asset/keeper/freeze.go` line 54 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOQ-HR0kmSyK15q92t:-NGSqT4RDR_vOSKBsF7o:bcz2ctc) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/keeper/freeze.go#L54)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

zero balances are automattically removed from the store in this function `frozenStore.setFrozenBalance(newFrozenBalance)` and setting a zero balance should be allowed, because it means removing that entry from store. 
</blockquote></details>

yes here it is fine
But it is nice to have unit/integration test where you submit msgFreeze with 0 TOKEN
Because it is another edge case as for me

I suggest to add it to `TestKeeper_FreezeUnfreeze` 
___
*[`x/asset/keeper/freeze.go` line 196 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOS-RF4nsKCYtQPwS8:-NGSqsNv1J8Go17B3akl:behn0o9) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/keeper/freeze.go#L196)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so you could rename function to `validateFeatureEnabled` and still return an error
</blockquote></details>

Both version isFeatureEnabled returning bool and validateFeatureEnabled returning error looks good for me


<!-- Sent from Reviewable.io -->

2022-11-10 07:00 UTC, wojtek-coreum reviewed
> Reviewed 1 of 6 files at r11.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-11-10 09:15 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 13 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFytWAjCB2jzKML4Ssf:-NGVbHuy80m3R0ZMnglh:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree 
@miladz68 pls fix this
</blockquote></details>

Done.

___
___
*[`integration-tests/asset/freeze.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bCog4ZOobdQZCjSv:-NGVbOJU9rLUQxlKQtXW:b-oybiii) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree with Wojtek
</blockquote></details>

it is tested on the keeper side. I think it is sufficient. 
___
*[`integration-tests/asset/freeze.go` line 106 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRXft7AxglNVvwMkO6:-NGVbYbI4fYODJHMYec7:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/integration-tests/asset/freeze.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This part is independent, could we test it in another test?
</blockquote></details>

Done
___
*[`integration-tests/asset/freeze.go` line 118 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRXt0n5t_HPi2TyYyE:-NGVbyQ_9rWQFfWM5ZDN:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/integration-tests/asset/freeze.go#L118)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this is not needed, as the next line covers it
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/genesis.proto` line 20 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRYcmDCjNoPzJRnnHS:-NGVcf-Y15sK7s0cPLc1:b-2cyn87) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/proto/coreum/asset/v1/genesis.proto#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Are you sure there is nothing to reuse from cosmos sdk? Cosmos already dumps balances in bank module somehow
</blockquote></details>

I copied this from bank module. I think copying is a better option here, since we may decide to customize this in future. Also if that proto is changed on cosmos side or is removed for any reason. then we are safer with copy. 
___
*[`x/asset/genesis_test.go` line 24 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOLhCMAz4Km_VlmX5_:-NGVd3Av8JY3SnRmm7ef:bq8ah33) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/genesis_test.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see
Can we call keeper's `IssueFungibleToken` and then `FreezeFungibleToken` (SetFrozenBalance is ok more or less also) so we have more realistic tests testing from outside and not calling internal asset module logic (`BuildFungibleTokenDenom`)
</blockquote></details>

Well I think the realistic test is to mimic the export/import behavior, which is to get state from keeper and generate json and put state to keeper from json. 
Anything more than that should be tested somewhere else. 
___
*[`x/asset/client/cli/tx.go` line 192 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRZd67EClAiEG__UbM:-NGVfQjn0dzJ-keVXFs8:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/client/cli/tx.go#L192)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"ft" should not be here
</blockquote></details>

Done.
___
*[`x/asset/keeper/freeze.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NFyqoLbDCGPKTv_O6Y0:-NGVfSAE4aJM0YgQ3Fr6:b-886gsx) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/x/asset/keeper/freeze.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Didn't we change the decision today?
</blockquote></details>

Fixed
___
*[`x/asset/keeper/freeze.go` line 54 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOQ-HR0kmSyK15q92t:-NGVj7h4-fdyoYOSvdd0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/keeper/freeze.go#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes here it is fine
But it is nice to have unit/integration test where you submit msgFreeze with 0 TOKEN
Because it is another edge case as for me

I suggest to add it to `TestKeeper_FreezeUnfreeze` 
</blockquote></details>

Done.
___
*[`x/asset/keeper/freeze.go` line 115 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRc1wYD1QT5f_jkFej:-NGVjPAgAZBQLHvfwbGn:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/keeper/freeze.go#L115)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this is just `var balances []types.Balance`
</blockquote></details>

Done.
___
*[`x/asset/keeper/freeze.go` line 116 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRcKjg25TNUnLI12Q2:-NGVjzax5op1VmWXGFTW:b-f7kxxb) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/keeper/freeze.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why not just putting this map into exported genesis? It should be correctly encoded to key-value (address: coins) pairs
</blockquote></details>

I think you mean to use `map[string]sdk.Coins` instead of `[]Balance`. It is possible but since it is convention to use protobuf for genesis, then that structure needs to be defined on genesis. 
___
*[`x/asset/keeper/freeze.go` line 120 at r11](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGRbTOf7dIDFt2lbTD8:-NGVl8sb4Nu0z13Ercq5:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c0c8c86834704e70b43ae824e5154e462703f2c4/x/asset/keeper/freeze.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If you return an error, logging should not be needed because error will be logged somewhere anyway. Error message should just contain all the important information
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-10 13:07 UTC, ysv requested changes
> Reviewed 16 of 17 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/asset/freeze.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NG0bCog4ZOobdQZCjSv:-NGW_tqd5ePrwjjvOtv3:b-cuyhqq) ([raw file](https://github.com/coreumfoundation/coreum/blob/69e93a1024d230303568fdf4f038865879b95026/integration-tests/asset/freeze.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is tested on the keeper side. I think it is sufficient. 
</blockquote></details>

ok for me
___
*[`x/asset/genesis_test.go` line 24 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGOLhCMAz4Km_VlmX5_:-NGW_yjw-Vfr18HD7jjY:bhc6vsb) ([raw file](https://github.com/coreumfoundation/coreum/blob/b46114585e72ee9a34b139afc7477f7ffe8f426e/x/asset/genesis_test.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Well I think the realistic test is to mimic the export/import behavior, which is to get state from keeper and generate json and put state to keeper from json. 
Anything more than that should be tested somewhere else. 
</blockquote></details>

okay we can keep it
___
*[`x/asset/keeper/freeze.go` line 53 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWcpWG1JtkWMWGM0w9:-NGWcpWG1JtkWMWGM0wA:bjwyeaf) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa35cfc206d82b7724d38d99093d9a664bcbf15/x/asset/keeper/freeze.go#L53)):*
> ```Go
> 	} else {
> 		return sdkerrors.Wrapf(sdkerrors.ErrInsufficientFunds,
> 			"freeze balance %s is more than the available frozen balance %s",
> ```

fix error message because first part is not "freeze balance" but more like unfreeze balance

I suggest smth like this (still not 100% satisfied):
`"unfreeze request %s is greater than frozen balance %s"`


<!-- Sent from Reviewable.io -->

2022-11-10 13:21 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/keeper/freeze.go` line 53 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWcpWG1JtkWMWGM0w9:-NGWgoFv5M83YAy3pgiC:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/1aa35cfc206d82b7724d38d99093d9a664bcbf15/x/asset/keeper/freeze.go#L53)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fix error message because first part is not "freeze balance" but more like unfreeze balance

I suggest smth like this (still not 100% satisfied):
`"unfreeze request %s is greater than frozen balance %s"`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-10 13:56 UTC, wojtek-coreum requested changes
> Reviewed 13 of 17 files at r12, 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWoo_c7l2bIx9n5fo1:-NGWoo_d2j1Q37DUVwwh:bhzsr66) (no related file):*
Please regenerate openapi `ignite generate openapi`

___
___
*[`integration-tests/asset/freeze.go` line 270 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWnLrt-vg7GVNNMjlI:-NGWnLruBMty5ycw43d2:bv5klou) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b8b31616519c13a590b9f732599529d086c49b8/integration-tests/asset/freeze.go#L270)):*
> ```Go
> 		unfreezeMsg,
> 	)
> 	requireT.True(sdkerrors.ErrInsufficientFunds.Is(err))
> ```

I don't think that `ErrInsufficientFunds` is a good error for this case


<!-- Sent from Reviewable.io -->

2022-11-10 14:22 UTC, wojtek-coreum reviewed
> Reviewed 1 of 6 files at r11, 2 of 17 files at r12, 1 of 2 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-10 17:23 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWoo_c7l2bIx9n5fo1:-NGWqjmF48QqBDt0-lGz:b-896fix) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please regenerate openapi `ignite generate openapi`
</blockquote></details>

Done.

___
___
*[`integration-tests/asset/freeze.go` line 270 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWnLrt-vg7GVNNMjlI:-NGXZD53C3r631DrES7W:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b8b31616519c13a590b9f732599529d086c49b8/integration-tests/asset/freeze.go#L270)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't think that `ErrInsufficientFunds` is a good error for this case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-11 08:08 UTC, wojtek-coreum requested changes
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/asset/freeze.go` line 270 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWnLrt-vg7GVNNMjlI:-NG_iV8R1nmViJCg3GWE:b-2m2xj0) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b8b31616519c13a590b9f732599529d086c49b8/integration-tests/asset/freeze.go#L270)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But new name and message is technically the same. "Not enough balance" make me thinking that I don't have enough tokens to pay for sth. Here it should explicitly mentioning frozen balance IMO


<!-- Sent from Reviewable.io -->

2022-11-11 08:08 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/asset/freeze.go` line 270 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/237#-NGWnLrt-vg7GVNNMjlI:-NG_itSAANPmJ1KssS_5:b-fhny1p) ([raw file](https://github.com/coreumfoundation/coreum/blob/4b8b31616519c13a590b9f732599529d086c49b8/integration-tests/asset/freeze.go#L270)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But new name and message is technically the same. "Not enough balance" make me thinking that I don't have enough tokens to pay for sth. Here it should explicitly mentioning frozen balance IMO
</blockquote></details>

but that is additional info attached to the error message 


<!-- Sent from Reviewable.io -->

2022-11-11 08:44 UTC, wojtek-coreum submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-11-11 09:22 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-11-11 09:43 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: 38 of 40 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-11 10:45 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r15, 3 of 3 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-11-11 10:45 UTC, merged