Min self delegation staking param
CoreumFoundation/coreum pull request #269
Opened 2022-11-24 06:40 UTC by dzmitryhil

* Add a parametrised min self delegation for the validators
* Add new customparams module to support custom params with the gov integration
* Extend the simapp with the simplified testing functions

2022-11-24 08:15 UTC, wojtek-coreum requested changes
> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/staking/staking.go` line 171 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcdAMp44hZEgvTixIQ:-NHcdAMp44hZEgvTixIR:bw1z1gc) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/integration-tests/staking/staking.go#L171)):*
> ```Go
> }
> 
> // TestValidatorMinParamsSelfDelegation checks validator mas set the self delegation below the limit.
> ```

mas -> may
___
*[`pkg/config/genesis/genesis.tmpl.json` line 260 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcdiq05FJxqc06fvIr:-NHcdiq11_ekI7oK3XqC:b-fehbav) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/pkg/config/genesis/genesis.tmpl.json#L260)):*
> ```JSON
>     },
>     "customparams": {
>       "staking_params": {
> ```

maybe just "staking"?
___
*[`proto/coreum/customparams/v1/params.proto` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcdwOg6ut0ASYwQnEz:-NHcdwOg6ut0ASYwQnF-:b-r3nn8a) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/proto/coreum/customparams/v1/params.proto#L10)):*
> ```protobuf
> 
> // StakingParams defines the set of additional staking params for the staking module wrapper.
> message StakingParams {
> ```

Minor: I would keep it in `wstaking` module and import from there but I'm not insisting.
And I think that names here and everywhere should reference `wstaking` not `staking`.
___
*[`proto/coreum/customparams/v1/params.proto` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHce3du5HGgmuQ_yBfs:-NHce3du5HGgmuQ_yBft:bond8hq) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/proto/coreum/customparams/v1/params.proto#L13)):*
> ```protobuf
>   // min_self_delegation is the validators global self declared minimum for delegation.
>   string min_self_delegation = 1 [
>     (gogoproto.moretags) = "yaml:\"min_self_delegation\"",
> ```

Please move gogoproto defs to the top. BTW, do yu know that gogoproto is deprecated for some time? It is not maintained anymore.
___
*[`testutil/simapp/simapp.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHceaup4Pm0DKLVqwa6:-NHceaup4Pm0DKLVqwa7:bm1a2cj) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/testutil/simapp/simapp.go#L46)):*
> ```Go
> }
> 
> // App is a simulation app wrapper.
> ```

oh, yet another wrapper ;-)
___
*[`testutil/simapp/simapp.go` line 94 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcevlV0gmYqPVvPCIo:-NHcevlV0gmYqPVvPCIp:b-ve4jgo) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/testutil/simapp/simapp.go#L94)):*
> ```Go
> 
> // GenAccount creates a new account and registers it in the App.
> func (s *App) GenAccount(ctx sdk.Context) (sdk.AccAddress, *secp256k1.PrivKey) {
> ```

I see account creation code at least in three places:
1. here
2. in testutils
3. in integration tests

Could we unite them somehow?
___
*[`x/customparams/types/key.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcfmpFBiyTMBdDDPIV:-NHcfmpFBiyTMBdDDPIW:b-mqg5nt) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/x/customparams/types/key.go#L14)):*
> ```Go
> 
> 	// CustomParamsStaking defines the params space key to store the staking custom params.
> 	CustomParamsStaking = "customparamsstaking"
> ```

Could we create one subspace for all the custom params and then another subspace inside that one for each module, instead of having separate top subspace for everything?
___
*[`x/wstaking/module_test.go` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcgZvq56LZAC2g_4AJ:-NHcgZvq56LZAC2g_4AK:b-2vemuo) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/x/wstaking/module_test.go#L16)):*
> ```Go
> // TestAppModuleOriginalStakingModule_GetConsensusVersion checks that the wrapped module still uses the save consensus version.
> func TestAppModuleOriginalStakingModule_GetConsensusVersion(t *testing.T) {
> 	stakingModule := staking.NewAppModule(&codec.AminoCodec{}, stakingkeeper.Keeper{}, authkeeper.AccountKeeper{}, bankkeeper.BaseKeeper{})
> ```

So here, you decided to check only ConsensusVersion, but as we discussed in the past it should be enough, right?


<!-- Sent from Reviewable.io -->

2022-11-24 08:36 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/staking.go` line 171 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcdAMp44hZEgvTixIQ:-NHck03L53ozsXX4ZIha:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/integration-tests/staking/staking.go#L171)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

mas -> may
</blockquote></details>

Done.



_Code quote:_
```Go
 checks validator mas set the self delegation below the
```
___
*[`pkg/config/genesis/genesis.tmpl.json` line 260 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcdiq05FJxqc06fvIr:-NHck2KF5EOmPtwgheAL:bd9rd7h) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/pkg/config/genesis/genesis.tmpl.json#L260)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe just "staking"?
</blockquote></details>

It looks more natural to me to say that this is the params.
___
*[`proto/coreum/customparams/v1/params.proto` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcdwOg6ut0ASYwQnEz:-NHckMrj-rizC-gxezoD:bsmbiv7) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/proto/coreum/customparams/v1/params.proto#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: I would keep it in `wstaking` module and import from there but I'm not insisting.
And I think that names here and everywhere should reference `wstaking` not `staking`.
</blockquote></details>

I got your point, but that's against the current module's strategy. I would keep it as is.
___
*[`proto/coreum/customparams/v1/params.proto` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHce3du5HGgmuQ_yBfs:-NHcks4q90WjgwhfeYaT:bx8fuak) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/proto/coreum/customparams/v1/params.proto#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please move gogoproto defs to the top. BTW, do yu know that gogoproto is deprecated for some time? It is not maintained anymore.
</blockquote></details>

Done. Nope, I didn't know that.
___
*[`testutil/simapp/simapp.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHceaup4Pm0DKLVqwa6:-NHckxFD-ZzXuANk22dj:b-1ncyfk) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/testutil/simapp/simapp.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

oh, yet another wrapper ;-)
</blockquote></details>

This one is different :-)
___
*[`testutil/simapp/simapp.go` line 94 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcevlV0gmYqPVvPCIo:-NHcl3UKA7D2XE0CB4qT:bkyxasn) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/testutil/simapp/simapp.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see account creation code at least in three places:
1. here
2. in testutils
3. in integration tests

Could we unite them somehow?
</blockquote></details>

But it's different. Here we add the new account to the simapp, in testutils we use it for the unit tests, in the integration tests we generate it to keep in the keystore. Just few lines are similar.  
___
*[`x/customparams/types/key.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcfmpFBiyTMBdDDPIV:-NHclPW9BRy1j7S3m3EQ:beqpso4) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/x/customparams/types/key.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could we create one subspace for all the custom params and then another subspace inside that one for each module, instead of having separate top subspace for everything?
</blockquote></details>

The subspace in the params keeper is flat. So to implement it we will have to go with our Params keeper. :-(
___
*[`x/wstaking/module_test.go` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcgZvq56LZAC2g_4AJ:-NHclmudAEDJ8DPt_B3F:bh7556u) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/x/wstaking/module_test.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So here, you decided to check only ConsensusVersion, but as we discussed in the past it should be enough, right?
</blockquote></details>

Yes, we didn't know how it was used, that's why I wrote 2 tests. But now we know that's the ConsensusVersion = migration version, so it's enough to test chust it. 


<!-- Sent from Reviewable.io -->

2022-11-24 08:52 UTC, wojtek-coreum approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/customparams/v1/params.proto` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHce3du5HGgmuQ_yBfs:-NHcohU46DRaGGs6kcAz:byupfnh) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/proto/coreum/customparams/v1/params.proto#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done. Nope, I didn't know that.
</blockquote></details>

https://github.com/gogo/protobuf

And this is very interesting video made by the author explaining why and how he failed on maintaining the project: https://www.youtube.com/watch?v=HTIltI0NuNg
___
*[`x/customparams/types/key.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcfmpFBiyTMBdDDPIV:-NHcpUyQChmNokg-LCr7:bvu7lhf) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/x/customparams/types/key.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The subspace in the params keeper is flat. So to implement it we will have to go with our Params keeper. :-(
</blockquote></details>

Another wrapper would be cool ;-)


<!-- Sent from Reviewable.io -->

2022-11-25 07:49 UTC, wojtek-coreum requested changes
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`testutil/network/network.go` line 131 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHhkesHDuQx5MLRtEcm:-NHhkesHDuQx5MLRtEcn:b-jhop75) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/testutil/network/network.go#L131)):*
> ```Go
> 	encoding := config.NewEncodingConfig(app.ModuleBasics)
> 
> 	var customParamsTypesState customparamstypes.GenesisState
> ```

It should not be written this way. Instead it should go to network config, and genesis should be generated from network config. This is exactly what network config is for.


<!-- Sent from Reviewable.io -->

2022-11-25 09:07 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/customparams/v1/params.proto` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHce3du5HGgmuQ_yBfs:-NHi0tJKEYrJUFtm4wmG:b-psf87j) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/proto/coreum/customparams/v1/params.proto#L13)):*
> ow he failed o
Oh, but we are blocked by the SDK :-(
___
*[`testutil/network/network.go` line 131 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHhkesHDuQx5MLRtEcm:-NHi1QLm0a7RhdmRCiDL:br971y0) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/testutil/network/network.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should not be written this way. Instead it should go to network config, and genesis should be generated from network config. This is exactly what network config is for.
</blockquote></details>

But we do the same for the integration testing, right? Here I extend the devnet config and, customize it, exactly the same as in the integration tests. 



_Code quote:_
```Go
var customParamsTypesState customparamstypes.GenesisState
```
___
*[`x/customparams/types/key.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHcfmpFBiyTMBdDDPIV:-NHi1f672Lvn2n8I2s1_:b-tyr3zr) ([raw file](https://github.com/coreumfoundation/coreum/blob/321195fba05c82ab741dcecc121316c3bbc40d6d/x/customparams/types/key.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Another wrapper would be cool ;-)
</blockquote></details>

It wouldn;t be the wrapper :-) New implementation. 


<!-- Sent from Reviewable.io -->

2022-11-26 10:05 UTC, ysv requested changes
> Reviewed 24 of 37 files at r1, 2 of 2 files at r2, 13 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk-h9q5pm0qJ2sX2nU:-NHk-h9q5pm0qJ2sX2nV:bclzl47) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/pkg/config/network.go#L67)):*
> ```Go
> 		customParamsConfig = CustomParamsConfig{
> 			Staking: CustomParamsStakingConfig{
> 				MinSelfDelegation: sdk.NewInt(20_000_000_000), // 20k core
> ```

could you remind me this value is confirmed with Reza
Isn't it ?
___
*[`x/asset/types/asset.pb.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk0iF6-zJ_7xFIxMV4:-NHk0iF6-zJ_7xFIxMV5:b-4wxu3c) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/asset/types/asset.pb.go#L1)):*
> ```Go
> // Code generated by protoc-gen-gogo. DO NOT EDIT.
> ```

this file was changed to executable I guess by mistake

![Screenshot 2022-11-25 at 19.22.46.png](https://files.reviewableusercontent.io/images/reviewable/19859122/63v2yyVS21nktgjx07uFQ1Rf/Screenshot%202022-11-25%20at%2019.22.46.png)
Screenshot 2022-11-25 at 19.22.46
___
*[`x/customparams/types/key.go` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk5JLM8arJYswRk7GN:-NHk5JLNDV5x3xUWQN34:b4faw05) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/key.go#L15)):*
> ```Go
> 	// CustomParamsStaking defines the params space key to store the staking custom params.
> 	CustomParamsStaking = "customparamsstaking"
> )
> ```

`CustomParamsStakingKey` ?
___
*[`x/customparams/types/params.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHjysO48HfzxtJNKvcl:-NHjysO48HfzxtJNKvcm:btrnnnm) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/params.go#L11)):*
> ```Go
> var (
> 	// ParamStoreKeyMinSelfDelegation defines the param key for the min_self_delegation param.
> 	ParamStoreKeyMinSelfDelegation = []byte("minselfdelegation")
> ```

So in result  this key is constructed of 3 parts sort of`customparams/staking/minselfdelegation` right ? 
___
*[`x/wstaking/module.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHjwtdq2g9t1_mXqlpC:-NHjwtdq2g9t1_mXqlpD:b9k4ct1) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/wstaking/module.go#L19)):*
> ```Go
> 	staking.AppModule
> 	stakingKeeper      stakingkeeper.Keeper
> 	customParamsKeeper customparamskeeper.Keeper
> ```

isn't it a common practice to define these via interfaces in expected_keepers including only needed methods ?

It probably doesn't make sense for `stakingkeeper.Keeper`  but customParamsKeeper is not needed here fully but only `GetStakingParams` method IMO


<!-- Sent from Reviewable.io -->

2022-11-28 07:59 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk-h9q5pm0qJ2sX2nU:-NHxAbNdDGHI9H1szXjL:bsngp0e) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/pkg/config/network.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

could you remind me this value is confirmed with Reza
Isn't it ?
</blockquote></details>

Yes, it was. 20k but let's double check it today. 
___
*[`x/asset/types/asset.pb.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk0iF6-zJ_7xFIxMV4:-NHxCWi44wcXW0qSoCCE:b-wsz416) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/asset/types/asset.pb.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this file was changed to executable I guess by mistake

![Screenshot 2022-11-25 at 19.22.46.png](https://files.reviewableusercontent.io/images/reviewable/19859122/63v2yyVS21nktgjx07uFQ1Rf/Screenshot%202022-11-25%20at%2019.22.46.png)
Screenshot 2022-11-25 at 19.22.46
</blockquote></details>

Right. Removed the executable fag now. 
___
*[`x/customparams/types/key.go` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk5JLM8arJYswRk7GN:-NHxCavD6BTK18aRMSlD:b-tpfy2k) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/key.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`CustomParamsStakingKey` ?
</blockquote></details>

The usual sdk convention is lowercase. 
___
*[`x/customparams/types/params.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHjysO48HfzxtJNKvcl:-NHxClhRAFOvjFrrr3Se:b-cza2pn) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/params.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

So in result  this key is constructed of 3 parts sort of`customparams/staking/minselfdelegation` right ? 
</blockquote></details>

The key is: "prams/customparamsstaking/minselfdelegation", since it's stored in the prams module. And we use the unique "customparamsstaking" subspace since we the subspace is flat. 
___
*[`x/wstaking/module.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHjwtdq2g9t1_mXqlpC:-NHxDGZUCpL9Jh1dt2ii:buafop7) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/wstaking/module.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

isn't it a common practice to define these via interfaces in expected_keepers including only needed methods ?

It probably doesn't make sense for `stakingkeeper.Keeper`  but customParamsKeeper is not needed here fully but only `GetStakingParams` method IMO
</blockquote></details>

Agree, better to do it that way. Updated.


<!-- Sent from Reviewable.io -->

2022-11-28 09:23 UTC, miladz68 reviewed
> Reviewed 26 of 37 files at r1, 2 of 2 files at r2, 13 of 14 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/customparams/keeper/genesis_test.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHxNmeO21QsUtiCWRAg:-NHxNmeO21QsUtiCWRAh:b-aiue7r) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/x/customparams/keeper/genesis_test.go#L19)):*
> ```Go
> 	ctx := testApp.BaseApp.NewContext(false, tmproto.Header{})
> 
> 	getState := types.GenesisState{
> ```

non-blocking
did you mean genState ?


<!-- Sent from Reviewable.io -->

2022-11-28 11:42 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/customparams/keeper/genesis_test.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHxNmeO21QsUtiCWRAg:-NHy1uhO7kZ8rx9bGxD5:bcppo66) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/x/customparams/keeper/genesis_test.go#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
did you mean genState ?
</blockquote></details>

Right, updated.



_Code quote:_
```Go
getState := types.GenesisState{
```


<!-- Sent from Reviewable.io -->

2022-11-28 11:44 UTC, ysv requested changes
> Reviewed 3 of 37 files at r1, 1 of 14 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk-h9q5pm0qJ2sX2nU:-NHy-Das-2FyzvaQCmK0:bq6i5za) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/pkg/config/network.go#L67)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, it was. 20k but let's double check it today. 
</blockquote></details>

okay
I will keep it unresolved for now
LMK once could be approved
___
*[`pkg/config/network.go` line 239 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHy1bM71n-zWXF7HgGM:-NHy1bM71n-zWXF7HgGN:byo0p58) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/pkg/config/network.go#L239)):*
> ```Go
> 	GovConfig            GovConfig
> 	StakingConfig        StakingConfig
> 	CustomParamsConfig   CustomParamsConfig
> ```

is it really needed here ?
AFAIK we put params here only if we need to customize them for different networks/integration-tests. But do we really need to change this one ?
___
*[`x/customparams/types/key.go` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk5JLM8arJYswRk7GN:-NHy-MdN4dlkZdo9Pw-J:b-itwev5) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/key.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The usual sdk convention is lowercase. 
</blockquote></details>

I mean variable name
CustomParamsStaking -> CustomParamsStakingKey/KeyCustomParamsStaking

I thought that it is a convention in SDK to identify that it is a key from storage
___
*[`x/wstaking/keeper/msg_server.go` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHy0U9M8mtAiq2vbk5s:-NHy0U9M8mtAiq2vbk5t:b-jg5m0v) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/x/wstaking/keeper/msg_server.go#L10)):*
> ```Go
> 	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"
> 
> 	customparamstypes "github.com/CoreumFoundation/coreum/x/wstaking/types"
> ```

I don't get the logic of naming it `customparamstypes`
Shouldn't it be smth like types/wstakingtypes


<!-- Sent from Reviewable.io -->

2022-11-28 11:44 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-11-28 12:07 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: 43 of 45 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk-h9q5pm0qJ2sX2nU:-NHy7YPZ1I--gH94ggT9:b-80tlqk) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/pkg/config/network.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

okay
I will keep it unresolved for now
LMK once could be approved
</blockquote></details>

Sure.
___
*[`pkg/config/network.go` line 239 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHy1bM71n-zWXF7HgGM:-NHy6HJF3CekkcX5CyCY:b-3hkvlv) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/pkg/config/network.go#L239)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it really needed here ?
AFAIK we put params here only if we need to customize them for different networks/integration-tests. But do we really need to change this one ?
</blockquote></details>

We put it if the default is not what we need. Now the default for the module is 1stake denom. That's why it's here, and I would go with that approach as well, since we might change it in the future as well, and it will be weird if we change the default of the module.
___
*[`x/customparams/types/key.go` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk5JLM8arJYswRk7GN:-NHy6jlu1chHzVGEvXWV:b-655j2i) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/key.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean variable name
CustomParamsStaking -> CustomParamsStakingKey/KeyCustomParamsStaking

I thought that it is a convention in SDK to identify that it is a key from storage
</blockquote></details>

For the params, we use the module name without the `Key`.  But if you consider it the right name we can use the `CustomParamsStakingKey` I'm ok with that. Confirm please.  
___
*[`x/wstaking/keeper/msg_server.go` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHy0U9M8mtAiq2vbk5s:-NHy73sY4_4MhZXKDEls:b-w6oav4) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/x/wstaking/keeper/msg_server.go#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't get the logic of naming it `customparamstypes`
Shouldn't it be smth like types/wstakingtypes
</blockquote></details>

Right, that's a copy-paste error, renamed.


<!-- Sent from Reviewable.io -->

2022-11-28 12:41 UTC, ysv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 239 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHy1bM71n-zWXF7HgGM:-NHyErGu-OVKpjRaMIlF:b-krgq6w) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/pkg/config/network.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We put it if the default is not what we need. Now the default for the module is 1stake denom. That's why it's here, and I would go with that approach as well, since we might change it in the future as well, and it will be weird if we change the default of the module.
</blockquote></details>

but we can just change it in `genesis.tmpl.json` to 20k as we do for all params which are network independent ?
___
*[`x/customparams/types/key.go` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHk5JLM8arJYswRk7GN:-NHyF94Y33XmpptlIUzZ:bc0beyh) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/x/customparams/types/key.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

For the params, we use the module name without the `Key`.  But if you consider it the right name we can use the `CustomParamsStakingKey` I'm ok with that. Confirm please.  
</blockquote></details>

I see then current is ok for me I think


<!-- Sent from Reviewable.io -->

2022-11-28 12:58 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 239 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHy1bM71n-zWXF7HgGM:-NHyIzLc7zMFrBz_LddX:b32axtc) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b843b9e8d8037c9b5abbd7880c2a08d5063af9e/pkg/config/network.go#L239)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but we can just change it in `genesis.tmpl.json` to 20k as we do for all params which are network independent ?
</blockquote></details>

Ok, but what about the "testNetwork()" the one we use for the integration test? If we set it to 20k we will need to spend it 20k per each validator creation (now its 10 core only). Now for example we add the different values in the "NetworkConfig struct {" if we modify them in that function.



_Code quote:_
```Go
CustomParamsConfig
```


<!-- Sent from Reviewable.io -->

2022-11-28 14:16 UTC, miladz68 submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-29 12:27 UTC, ysv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-11-29 13:13 UTC, ysv approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-11-29 13:25 UTC, wojtek-coreum requested changes
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

___
*[`integration-tests/testing/network.go` line 31 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NI2YKCq3p0iXdaKH88j:-NI2YKCq3p0iXdaKH88k:b1qcim2) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b7be184601d63a3bb222469cd83cb4fb948028/integration-tests/testing/network.go#L31)):*
> ```Go
> 	networkConfig.GenTxs = nil
> 
> 	networkConfig.CustomParamsConfig = config.CustomParamsConfig{
> ```

why do we override it?
___
*[`testutil/network/network.go` line 131 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHhkesHDuQx5MLRtEcm:-NI2Yr7O1GD-ewW-efE6:bzfqqcs) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/testutil/network/network.go#L131)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we do the same for the integration testing, right? Here I extend the devnet config and, customize it, exactly the same as in the integration tests. 
</blockquote></details>

In integration tests we modify the config object and generate json from that config. Here, instead of modifying config you unmarshal json, modify it and marshal back


<!-- Sent from Reviewable.io -->

2022-11-29 14:05 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum)

___
*[`integration-tests/testing/network.go` line 31 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NI2YKCq3p0iXdaKH88j:-NI2gFqbB3hKAujO5f3l:b-qdyryl) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b7be184601d63a3bb222469cd83cb4fb948028/integration-tests/testing/network.go#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why do we override it?
</blockquote></details>

To have 10nom as minimum by default we will have 20_000k
___
*[`testutil/network/network.go` line 131 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/269#-NHhkesHDuQx5MLRtEcm:-NI2gobVBliey2cndJXD:b-ooe3kl) ([raw file](https://github.com/coreumfoundation/coreum/blob/edbc5e65844776f6b5e24851235696bafc75e717/testutil/network/network.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In integration tests we modify the config object and generate json from that config. Here, instead of modifying config you unmarshal json, modify it and marshal back
</blockquote></details>

Right, Updarted now. Got your point.



_Code quote:_
```Go
encoding.Codec.MustUnmarshalJSON(genesisAppState[customparamstypes.ModuleName], &customParamsTypesState)
```


<!-- Sent from Reviewable.io -->

2022-11-29 14:07 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)



<!-- Sent from Reviewable.io -->

2022-11-29 14:17 UTC, merged