Implement NFT asset class creation and NFT minting
CoreumFoundation/coreum pull request #277
Opened 2022-12-01 10:27 UTC by dzmitryhil

2022-12-01 10:38 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: 0 of 32 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NICFWnL05OqZUjHoDfj:b-qj2fl4) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
> ```Go
> 
> var (
> 	// TODO(dhil) discuss with team the regex, probably we need uppercase as well, if yes what we do with the uniqueness?
> ```

@ysv @wojtek-coreum @miladz68 the comment to discuss. 
We should probably create an additional field `key` or `IDPrefix` which we can use instead. 
Or allow the Uppercase, and let users create "Class" and "claSS" at the same time from one account. 


<!-- Sent from Reviewable.io -->

2022-12-06 10:49 UTC, wojtek-coreum requested changes
> Reviewed 26 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: 26 of 32 files reviewed, 33 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 520 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIaqNF60i0E9cmOuhYa:-NIaqNF60i0E9cmOuhYb:b-xoa14l) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/app/app.go#L520)):*
> ```Go
> 	var skipGenesisInvariants = cast.ToBool(appOpts.Get(crisis.FlagSkipGenesisInvariants))
> 
> 	assetModule := asset.NewAppModule(appCodec, app.AssetKeeper, app.AssetNonFungibleTokenKeeper, app.BankKeeper)
> ```

Is the `app.AssetKeeper` ony about fungible token, or is there any common functionality?
___
*[`x/asset/keeper/msg_server.go` line 178 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawKZN1gMOOIv3vV4C:-NIawKZN1gMOOIv3vV4D:b7dwxz2) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L178)):*
> ```Go
> 		types.MintNonFungibleTokenSettings{
> 			Sender:  owner,
> 			ClassID: req.ClassId,
> ```

req.ClassID
___
*[`x/asset/keeper/msg_server.go` line 179 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawHGf5BM4lxdagCoL:-NIawHGf5BM4lxdagCoM:b-l6lqa8) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L179)):*
> ```Go
> 			Sender:  owner,
> 			ClassID: req.ClassId,
> 			ID:      req.Id,
> ```

req.ID
___
*[`x/asset/keeper/msg_server.go` line 180 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawMe8D_CAkAsAV6me:-NIawMe8D_CAkAsAV6mf:b-heovqh) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L180)):*
> ```Go
> 			ClassID: req.ClassId,
> 			ID:      req.Id,
> 			URI:     req.Uri,
> ```

req.URI
___
*[`x/asset/keeper/msg_server.go` line 181 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawORQ2xRrrKBhHLEB:-NIawORQ2xRrrKBhHLEC:b-p8j75n) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L181)):*
> ```Go
> 			ID:      req.Id,
> 			URI:     req.Uri,
> 			URIHash: req.UriHash,
> ```

req.URIHash
___
*[`x/asset/keeper/nft_keeper.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0E7P9rK04nCw1hLC:-NIb0E7P9rK04nCw1hLD:b-ij6tk3) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L45)):*
> ```Go
> 			"symbol %q already used for the address %q",
> 			settings.Symbol,
> 			settings.Creator.String(),
> ```

Possibly, you may remove `.String()` as it should be used under the hood
___
*[`x/asset/keeper/nft_keeper.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0pJ57anvuY7KIIbp:-NIb0pJ57anvuY7KIIbq:b32vvk) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L50)):*
> ```Go
> 
> 	if err := k.nftKeeper.SaveClass(ctx, nft.Class{
> 		Id:          id,
> ```

ID
___
*[`x/asset/keeper/nft_keeper.go` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0mxD8neiQWz7iE_-:-NIb0mxD8neiQWz7iE_0:b2nhpgn) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L54)):*
> ```Go
> 		Name:        settings.Name,
> 		Description: settings.Description,
> 		Uri:         settings.URI,
> ```

URI
___
*[`x/asset/keeper/nft_keeper.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0rBK-QEzbqkbER4-:-NIb0rBK-QEzbqkbER40:b-qgwi7f) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L55)):*
> ```Go
> 		Description: settings.Description,
> 		Uri:         settings.URI,
> 		UriHash:     settings.URIHash,
> ```

URIHash
___
*[`x/asset/keeper/nft_keeper.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1-hK4igaCcsdE_pk:-NIb1-hK4igaCcsdE_pl:brqfmox) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L58)):*
> ```Go
> 		Data:        settings.Data,
> 	}); err != nil {
> 		return "", sdkerrors.Wrap(types.ErrInvalidNonFungibleTokenClass, "can't save non-fungible token")
> ```

`err` should be included to understand why
___
*[`x/asset/keeper/nft_keeper.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1H4YEn9Ab9qGobnB:-NIb1H4ZA3xSEX6eLzpn:b32vvk) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L62)):*
> ```Go
> 
> 	if err := ctx.EventManager().EmitTypedEvent(&types.EventNonFungibleTokenClassCreated{
> 		Id:          id,
> ```

ID
___
*[`x/asset/keeper/nft_keeper.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1Igm0yxTojXaCMRl:-NIb1Igm0yxTojXaCMRm:b2nhpgn) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L67)):*
> ```Go
> 		Name:        settings.Name,
> 		Description: settings.Description,
> 		Uri:         settings.URI,
> ```

URI
___
*[`x/asset/keeper/nft_keeper.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1Kj2DcofpquRVzZ_:-NIb1Kj2DcofpquRVzZa:b-qgwi7f) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L68)):*
> ```Go
> 		Description: settings.Description,
> 		Uri:         settings.URI,
> 		UriHash:     settings.URIHash,
> ```

URIHash
___
*[`x/asset/keeper/nft_keeper.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1Nr0BE2C3ORwMtAX:-NIb1Nr0BE2C3ORwMtAY:brqfmox) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L70)):*
> ```Go
> 		UriHash:     settings.URIHash,
> 	}); err != nil {
> 		return "", sdkerrors.Wrap(types.ErrInvalidNonFungibleTokenClass, "can't emit event EventNonFungibleTokenClassCreated")
> ```

`err` should be included to understand why
___
*[`x/asset/keeper/nft_keeper.go` line 86 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1YqYA2X3Jl3t-wL-:-NIb1YqYA2X3Jl3t-wL0:b5suysd) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L86)):*
> ```Go
> 	}
> 
> 	classFound := k.nftKeeper.HasClass(ctx, settings.ClassID)
> ```

minor here and below, you could put function call directly to `if`, but I don't care much
___
*[`x/asset/keeper/nft_keeper.go` line 98 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1hlu0pSuVdf7hPBR:-NIb1hlv43c68_BfyYPf:b32vvk) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L98)):*
> ```Go
> 	err := k.nftKeeper.Mint(ctx, nft.NFT{
> 		ClassId: settings.ClassID,
> 		Id:      settings.ID,
> ```

ID
___
*[`x/asset/keeper/nft_keeper.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1jkp6ATx5X9_QQOo:-NIb1jkp6ATx5X9_QQOp:b2nhpgn) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L99)):*
> ```Go
> 		ClassId: settings.ClassID,
> 		Id:      settings.ID,
> 		Uri:     settings.URI,
> ```

URI
___
*[`x/asset/keeper/nft_keeper.go` line 100 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1lip0ERY5XSdQz2P:-NIb1lip0ERY5XSdQz2Q:b-qgwi7f) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b [...]

2022-12-08 10:15 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: 16 of 34 files reviewed, 16 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/msg_server.go` line 178 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawKZN1gMOOIv3vV4C:-NIlC1J_46rs7GZNIof9:b4gozi5) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L178)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But there should be a gogo instruction to tell how the name should look like
</blockquote></details>

You are right. `[(gogoproto.customname) = "ClassID"]`, updated for all fields you requested (for asset types). 
___
*[`x/asset/keeper/msg_server.go` line 179 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawHGf5BM4lxdagCoL:-NIlDi37Bd84-mPqeSpW:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L179)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/msg_server.go` line 180 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawMe8D_CAkAsAV6me:-NIlDkCg9JqbapNCNLuU:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L180)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/msg_server.go` line 181 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawORQ2xRrrKBhHLEB:-NIlDkti0loPOfWhuGB7:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L181)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0pJ57anvuY7KIIbp:-NIlDl_n5m9aKN6VMoh6:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L50)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0mxD8neiQWz7iE_-:-NIlDmJL89EDDI4coCLp:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0rBK-QEzbqkbER4-:-NIlDmwB-c24oO5gVl4U:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L55)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 62 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1H4YEn9Ab9qGobnB:-NIlDnYh7gjJpFpElVEF:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L62)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1Igm0yxTojXaCMRl:-NIlDo8o9R_AG6rnf3ly:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L67)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 68 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1Kj2DcofpquRVzZ_:-NIlDoe70VcAmYeiaEex:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 86 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1YqYA2X3Jl3t-wL-:-NIl9kQ569B856me7VaG:b-amtqd4) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L86)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You need only `if !k.nftKeeper.HasClass(ctx, settings.ClassID) {`
</blockquote></details>

Right :-) Updated



_Code quote:_
```Go
if classFound := k.nftKeeper.HasClass(ctx, settings.ClassID); !
```
___
*[`x/asset/keeper/nft_keeper.go` line 98 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1hlu0pSuVdf7hPBR:-NIlDppW1H8vSza0zfKu:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L98)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1jkp6ATx5X9_QQOo:-NIlDqKS5ziRGkmpBxlp:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 100 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1lip0ERY5XSdQz2P:-NIlDqts0QZWKyB2BfOj:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L100)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is generated code.
</blockquote></details>

Updated now.
___
*[`x/asset/keeper/nft_keeper.go` line 104 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1y4h6XRy9gUeN7bv:-NIl9ray9qTb1KtAceIa:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L104)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here `err` should be included in the message too
</blockquote></details>

Done
___
*[`x/asset/types/nft.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb-JRA403i1sP3w8f3:-NIl9zMY6CyOT54VWcuI:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Earlier I misunderstood the code,  you could simplify it to `classIDParts[1]`
</blockquote></details>

Done



_Code quote:_
```Go
 sdk.AccAddressFromBech32(classIDParts[len(classI
```


<!-- Sent from Reviewable.io -->

2022-12-08 11:04 UTC, miladz68 requested changes
> Reviewed 25 of 32 files at r1, 2 of 4 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 22 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/nft_mint.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIgR2m3AeosxC35PDuv:-NIgR2m3AeosxC35PDuw:b-fof7uy) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/integration-tests/asset/nft_mint.go#L46)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// mint new token in that class
> ```

we need a test to check that  only the creator of the class can mint new nfts 
___
*[`proto/coreum/asset/v1/tx.proto` line 81 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlHEer-OkNbedjFbPS:-NIlHEer-OkNbedjFbPT:bpkv3du) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/proto/coreum/asset/v1/tx.proto#L81)):*
> ```protobuf
> 
> // MsgCreateNonFungibleTokenClass defines message for the CreateNonFungibleTokenClass method.
> message MsgCreateNonFungibleTokenClass {
> ```

non-blocking
I know that I have discussed this before and it has been disapproved, but I like to mention it again here. 
I think it makes sense to look at this type as the nft definition + creation info to allow for logic reuse. I think it is work to re discuss it in the team.
___
*[`x/asset/keeper/msg_server.go` line 178 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawKZN1gMOOIv3vV4C:-NIl3oAY6fyeG4RzLsaH:bk1b54) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L178)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But there should be a gogo instruction to tell how the name should look like
</blockquote></details>

i don't think chaning the generated code is really beneficial. 
___
*[`x/asset/keeper/nft_keeper_test.go` line 58 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlM_q97Vf56kN1S9Rk:-NIlM_q97Vf56kN1S9Rl:b-jaxyk9) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/keeper/nft_keeper_test.go#L58)):*
> ```Go
> }
> 
> func TestNonFungibleTokenKeeper_MintNonFungibleToken(t *testing.T) {
> ```

Mint includes the createClass under the hood. so maybe the 2 tests can be merged. 
___
*[`x/asset/types/ft.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlN47c647371bHc7ny:-NIlN47c647371bHc7nz:b-6hxes7) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/ft.go#L38)):*
> ```Go
> 
> // BuildFungibleTokenDenom builds the denom string from the symbol and issuer address.
> func BuildFungibleTokenDenom(symbol string, issuer sdk.AccAddress) string {
> ```

I know that it is my code. but since you are refactoring, `symbol` should be renamed to either `prefix` or `subunit`
___
*[`x/asset/types/ft.go` line 39 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlNNpO3GTDxFdvI-sM:-NIlNNpO3GTDxFdvI-sN:b-v1ugto) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/ft.go#L39)):*
> ```Go
> // BuildFungibleTokenDenom builds the denom string from the symbol and issuer address.
> func BuildFungibleTokenDenom(symbol string, issuer sdk.AccAddress) string {
> 	return strings.ToLower(symbol) + denomSeparator + issuer.String()
> ```

non-blocking, since you are refactoring ...
strings.ToLower should be removed. it is part of the old logic, later we discussed to use subunits which only consists of lowercase anyway. 
___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NIlO3vB3b9AYKKDZUaS:b-g4fmj3) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @wojtek-coreum @miladz68 the comment to discuss. 
We should probably create an additional field `key` or `IDPrefix` which we can use instead. 
Or allow the Uppercase, and let users create "Class" and "claSS" at the same time from one account. 
</blockquote></details>

I don't get why we need it
___
*[`x/asset/types/nft.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIl4nQD9xtyQK5UscZl:-NIl4nQD9xtyQK5UscZm:bp5vb8w) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/x/asset/types/nft.go#L26)):*
> ```Go
> 
> // CreateNonFungibleTokenClassSettings is the model which represents the params for the non-fungible token class creation.
> type CreateNonFungibleTokenClassSettings struct {
> ```

let's ditch this type and use the protobuf instead
I think the same Idea on the FT side has not been beneficial. 
I know that it saves once on parsing the Creator address, but adds a new indirection which is just too much


<!-- Sent from Reviewable.io -->

2022-12-08 11:58 UTC, ysv requested changes
> Reviewed 13 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 29 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlaPoh-ubjF6PUTrnJ:-NIlaPoh-ubjF6PUTrnK:btdq795) (no related file):*
Publishing first batch of comments & continuing review

___
___
*[`integration-tests/asset/nft_class.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbw0uY2iUV6lc9RM3m:-NIbw0uY2iUV6lc9RM3n:b-55h3nq) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L32)):*
> ```Go
> 	// create new NFT class
> 	createMsg := &assettypes.MsgCreateNonFungibleTokenClass{
> 		Creator:     creator.String(),
> ```

I know that we had this discussion but IMO it should be `IssueNonFungibleTokenClass` to be more similar to FT

WDYT @wojtek-coreum @miladz68 @dzmitryhil ?
___
*[`integration-tests/asset/nft_class.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbwirzBQa8JqGqUVLO:-NIbwis-1ookB7W-OLG2:bthmvod) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L37)):*
> ```Go
> 		Description: "description",
> 		Uri:         "https://my-class-meta.int/1",
> 		UriHash:     "35b326a2b3b605270c26185c38d2581e937b2eae0418b4964ef521efe79cdf34",
> ```

I'm just interested is it a hash of URI or content stored by URI ?
___
*[`integration-tests/asset/nft_mint.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcB3LC4RkifTa_8_eP:-NIcB3LC4RkifTa_8_eQ:b-wk0l2s) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L36)):*
> ```Go
> 	createMsg := &assettypes.MsgCreateNonFungibleTokenClass{
> 		Creator: sender.String(),
> 		Symbol:  "nftsymbol",
> ```

it is a class so should be named accordingly IMO
___
*[`integration-tests/asset/nft_mint.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcBOV6EiaYpkB_tG7b:-NIcBOV6EiaYpkB_tG7c:b-zacfeo) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L50)):*
> ```Go
> 	mintMsg := &assettypes.MsgMintNonFungibleToken{
> 		Sender:  sender.String(),
> 		Id:      "id-1",
> ```

repeated too many times 
what about moving to a variable ?
___
*[`x/asset/client/cli/nft_mint_test.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIccFwA4zs3bh5Ro1Ak:-NIccFwA4zs3bh5Ro1Al:bslz4rx) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/client/cli/nft_mint_test.go#L23)):*
> ```Go
> 	ctx := validator.ClientCtx
> 
> 	args := []string{symbol, "NFT-name", "My NFT class description.", "my-uri", "my-hash"}
> ```

can you pls use more realistic names here pls

NFT-name -> class name
my-uri -> https://...
my-hash -> <real hash>
firstID -> smth like `nftid-1`
___
*[`pkg/store/string.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcBsuh3jV2Bl5BRKmb:-NIcBsuh3jV2Bl5BRKmc:b-kpx2m7) ([raw file](https://github.com/coreumfoundation/coreum/blob/43ac89e85c4bb6bdf705b0df33c7a06988583a6e/pkg/store/string.go#L1)):*
> ```Go
> // Package conv is copy of the sdk https://github.com/cosmos/cosmos-sdk/blob/2582f0aab7b2cbf66ade066fe570a4622cf0b098/internal/conv/string.go
> ```

why did we remove the comment
 it is still a copy of this package isn't it ?


<!-- Sent from Reviewable.io -->

2022-12-09 07:39 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 29 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlaPoh-ubjF6PUTrnJ:-NIpobtW-f5iiktNipty:b32w1t) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Publishing first batch of comments & continuing review
</blockquote></details>

Ok

___
___
*[`integration-tests/asset/nft_class.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbw0uY2iUV6lc9RM3m:-NIpjdA0-dC2E2w7tMDX:bbtkkoh) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I know that we had this discussion but IMO it should be `IssueNonFungibleTokenClass` to be more similar to FT

WDYT @wojtek-coreum @miladz68 @dzmitryhil ?
</blockquote></details>

 It was in the initial version. And the `creator` here because of it as well. 
___
*[`integration-tests/asset/nft_class.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbwirzBQa8JqGqUVLO:-NIpjzGe-dfMr6rR6VVV:b5qoj1u) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm just interested is it a hash of URI or content stored by URI ?
</blockquote></details>

It should be. 
___
*[`integration-tests/asset/nft_mint.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcB3LC4RkifTa_8_eP:-NIpkHV-2BoVRMVCyOUA:biib11l) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it is a class so should be named accordingly IMO
</blockquote></details>

Didn't get you. This class uses the symbol = "nftsymbol", what is the issue?



_Code quote:_
```Go
Symbol:  "nftsymbol",
```
___
*[`integration-tests/asset/nft_mint.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcBOV6EiaYpkB_tG7b:-NIpka0v8ZB7u8UsvR4T:bqhm9q4) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

repeated too many times 
what about moving to a variable ?
</blockquote></details>

Reused the same variable now.



_Code quote:_
```Go
// mint new token in that class
```
___
*[`integration-tests/asset/nft_mint.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIgR2m3AeosxC35PDuv:-NIpl-x1DSJK5HECPuEN:b-3serm6) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/integration-tests/asset/nft_mint.go#L46)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need a test to check that  only the creator of the class can mint new nfts 
</blockquote></details>

We have that test in the keeper.
___
*[`proto/coreum/asset/v1/tx.proto` line 81 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlHEer-OkNbedjFbPS:-NIpljuFCgFYfbByhPwj:b-uydnkd) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/proto/coreum/asset/v1/tx.proto#L81)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
I know that I have discussed this before and it has been disapproved, but I like to mention it again here. 
I think it makes sense to look at this type as the nft definition + creation info to allow for logic reuse. I think it is work to re discuss it in the team.
</blockquote></details>

I didn't get your point. Could you elaborate on it?
___
*[`x/asset/client/cli/nft_mint_test.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIccFwA4zs3bh5Ro1Ak:-NIpmzi7CAxEPa9_YQTx:b-bu91xm) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/client/cli/nft_mint_test.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you pls use more realistic names here pls

NFT-name -> class name
my-uri -> https://...
my-hash -> <real hash>
firstID -> smth like `nftid-1`
</blockquote></details>

Updated
___
*[`x/asset/keeper/msg_server.go` line 178 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawKZN1gMOOIv3vV4C:-NIpn18I27kzH3vtvxWU:b-xe1u5d) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L178)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

i don't think chaning the generated code is really beneficial. 
</blockquote></details>

It's not changing. This is how we can say it should be generated. 
___
*[`x/asset/keeper/nft_keeper_test.go` line 58 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlM_q97Vf56kN1S9Rk:-NIpnGHqBQBEvbTDWFqG:b-qeftp) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/keeper/nft_keeper_test.go#L58)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Mint includes the createClass under the hood. so maybe the 2 tests can be merged. 
</blockquote></details>

In the Mint we don't assert the created class. We will have more tests later where we will create the class, but just one will assert the created class - CreateClass test. 



_Code quote:_
```Go
MintNonFungibleToken(t *testing.T) {
```
___
*[`x/asset/types/ft.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlN47c647371bHc7ny:-NIpneHi-8f4Z_82dX0I:b-8ezbo2) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/ft.go#L38)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I know that it is my code. but since you are refactoring, `symbol` should be renamed to either `prefix` or `subunit`
</blockquote></details>

Agree, updated.



_Code quote:_
```Go
BuildFungibleTokenDenom(symbol string, issuer sdk.AccAddress) string {
```
___
*[`x/asset/types/ft.go` line 39 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlNNpO3GTDxFdvI-sM:-NIpnuV1DH_Rq_VkIxXt:b-dsnshb) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/ft.go#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking, since you are refactoring ...
strings.ToLower should be removed. it is part of the old logic, later we discussed to use subunits which only consists of lowercase anyway. 
</blockquote></details>

Agree, the same in the NFT func. Update.



_Code quote:_
```Go
strings.ToLower
```
___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NIpo-466jUd735akiVG:bgwhfog) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't get why we need it
</blockquote></details>

The symbol usually is UpperCase or AllCases
___
*[`x/asset/types/nft.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIl4nQD9xtyQK5UscZl:-NIpoMuQ1dmkzq1J5boY:b-wqcl8u) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/x/ [...]

2022-12-09 10:24 UTC, miladz68 reviewed
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 25 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/nft_class.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbw0uY2iUV6lc9RM3m:-NIqP28yDzDHioZLIZDm:b-ow9vja) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

 It was in the initial version. And the `creator` here because of it as well. 
</blockquote></details>

Yeap we agreed on CreateClass, but we can discuss it againg if you dislike it. 
___
*[`proto/coreum/asset/v1/tx.proto` line 81 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlHEer-OkNbedjFbPS:-NIqPIreCy41Q8H6Efy-:b-htbsq6) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/proto/coreum/asset/v1/tx.proto#L81)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get your point. Could you elaborate on it?
</blockquote></details>

I talking about having having a common message definition and reused it for class storage and creation. Maybe it will be easier to describe in the call. 
___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NIqOnN62MqSUeVblYXZ:bhtlkbi) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The symbol usually is UpperCase or AllCases
</blockquote></details>

I need more description to understand the problem, maybe we should discuss it in the call. 


<!-- Sent from Reviewable.io -->

2022-12-09 12:43 UTC, ysv requested changes
> Reviewed 11 of 32 files at r1, 15 of 15 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 33 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/asset/nft_mint.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcB3LC4RkifTa_8_eP:-NIle8158kZZyDh-vSR5:b3n6vbm) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it is a class so should be named accordingly IMO
</blockquote></details>

I mean value
___
*[`integration-tests/asset/nft_mint.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIgR2m3AeosxC35PDuv:-NIlfxVb7WnoxsSueMMU:b-8i4p3i) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/integration-tests/asset/nft_mint.go#L46)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need a test to check that  only the creator of the class can mint new nfts 
</blockquote></details>

very good point
___
*[`proto/coreum/asset/v1/event.proto` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlh9ezBldEy0_CiGN-:-NIlh9ezBldEy0_CiGN0:bh8q92u) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/proto/coreum/asset/v1/event.proto#L31)):*
> ```protobuf
> 
> // EventNonFungibleTokenClassCreated is emitted on MsgCreateNonFungibleTokenClass.
> message EventNonFungibleTokenClassCreated {
> ```

so events for NFT minting are defined in x/nft but they don't have anything for Class ?
That is strange
___
*[`proto/coreum/asset/v1/tx.proto` line 81 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlHEer-OkNbedjFbPS:-NImZPrW948BI7Ioj7-y:bx1ocvn) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/proto/coreum/asset/v1/tx.proto#L81)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
I know that I have discussed this before and it has been disapproved, but I like to mention it again here. 
I think it makes sense to look at this type as the nft definition + creation info to allow for logic reuse. I think it is work to re discuss it in the team.
</blockquote></details>

Frankly speaking I didn't get
___
*[`x/asset/client/cli/nft_tx.go` line 45 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIm_nC26A5AxMstmD-r:-NIm_nC26A5AxMstmD-s:b-p3kyqa) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/client/cli/nft_tx.go#L45)):*
> ```Go
> 
> Example:
> $ %s tx asset nft create-class abc "ABC Name" "ABC token description." metada-uri uri-hash --from [sender]
> ```

please use "real" data in examples

smth like:
- ABC token description -> ABC class description
- metadata-uri -> http://...
- uri-hash -> e000624
___
*[`x/asset/keeper/msg_server.go` line 169 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIqryfjAGCh1QPKWoq3:-NIqryfk8alogkE22TGQ:b-o2uv8n) ([raw file](https://github.com/coreumfoundation/coreum/blob/3000712759bbb0a4e8e835646abf545f95e90b19/x/asset/keeper/msg_server.go#L169)):*
> ```Go
> // MintNonFungibleToken mints non-fungible token.
> func (ms MsgServer) MintNonFungibleToken(ctx context.Context, req *types.MsgMintNonFungibleToken) (*types.EmptyResponse, error) {
> 	sdk.UnwrapSDKContext(ctx)
> ```

not neeeded line ?
___
*[`x/asset/keeper/msg_server.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIqrWdd1TZK7q1GW3_Q:-NIqrWdd1TZK7q1GW3_R:bqbwun2) ([raw file](https://github.com/coreumfoundation/coreum/blob/3000712759bbb0a4e8e835646abf545f95e90b19/x/asset/keeper/msg_server.go#L172)):*
> ```Go
> 	owner, err := sdk.AccAddressFromBech32(req.Sender)
> 	if err != nil {
> 		return nil, sdkerrors.Wrap(types.ErrInvalidFungibleToken, "invalid sender in MsgMintNonFungibleToken")
> ```

minor:
I don't think it is a good idea to hardcode `MsgCreateNonFungibleTokenClass`in error
Maybe you can probably use %T or remove it at all
___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NImlwrC3J-58I6qro90:b-yc78kz) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't get why we need it
</blockquote></details>

but doesn't it work properly now when you do this in `BuildFungibleTokenDenom` ?

```
return strings.ToLower(symbol) + denomSeparator + issuer.String()
```



_Code quote (from x/asset/types/ft.go):_
```Go
return strings.ToLower(symbol) + denomSeparator + issuer.String()
```
___
*[`x/asset/types/nft.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIl4nQD9xtyQK5UscZl:-NIqsHCQ5JX6dMUFD34C:bfn4c70) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/x/asset/types/nft.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure that we need the protobuf here, this is similar to method params, and we have it just because the amount of them is to high. But I'm OK to discuss it.
</blockquote></details>

I also don't like this structure but I'm not sure we can do smth better with it 
Lets discuss, maybe we can come up with smth 
___
*[`x/asset/types/nft.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlgSe_6HOFmBYlLp0R:-NIlgSe_6HOFmBYlLp0S:b-533mes) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft.go#L19)):*
> ```Go
> 	nftSymbolRegex    = regexp.MustCompile(nftSymbolRegexStr)
> 	// the regexp is same as for the nft module
> 	nftIDRegexStr = `^[a-zA-Z][a-zA-Z0-9/:-]{2,100}$`
> ```

I propose to make FT & NFT regex similar so it is not that confusing for users
I think we should at least allow:
- same list of symbols
- same length where possible/logical
___
*[`x/asset/types/nft_msgs_test.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NImml0bCXOAvbdxhMND:-NImml0bCXOAvbdxhMNE:bugkq9c) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft_msgs_test.go#L23)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	validaMessage := types.MsgCreateNonFungibleTokenClass{
> ```

validMessage
___
*[`x/asset/types/nft_msgs_test.go` line 34 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIqsXhp8S1wjIaXjvxh:-NIqsXhp8S1wjIaXjvxi:bwsz96v) ([raw file](https://github.com/coreumfoundation/coreum/blob/3000712759bbb0a4e8e835646abf545f95e90b19/x/asset/types/nft_msgs_test.go#L34)):*
> ```Go
> 	testCases := []struct {
> 		name          string
> 		messageFunc   func() *types.MsgCreateNonFungibleTokenClass
> ```

minor:
messageFunc -> editMsgFunc/changeMsgFunc
___
*[`x/asset/types/nft_msgs_test.go` line 57 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIqt7R43RlWdhmQn548:-NIqt7R43RlWdhmQn549:be9avlj) ([raw file](https://github.com/coreumfoundation/coreum/blob/3000712759bbb0a4e8e835646abf545f95e90b19/x/asset/types/nft_msgs_test.go#L57)):*
> ```Go
> 			messageFunc: func() *types.MsgCreateNonFungibleTokenClass {
> 				msg := validaMessage
> 				msg.Name = string(make([]byte, 129))
> ```

you can replace it with smth like. To not have string from empty bytes but some real non-empty text:

`strings.Repeat("n", 129)` 

same applies for all further test cases
___
*[`x/asset/types/nft_msgs_test.go` line 142 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/27 [...]

2022-12-09 12:51 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 31 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/asset/nft_class.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbw0uY2iUV6lc9RM3m:-NIqw-wM2ihahvWBIUdn:b-usc33p) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Yeap we agreed on CreateClass, but we can discuss it againg if you dislike it. 
</blockquote></details>

Lets discuss on the call
___
*[`integration-tests/asset/nft_class.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbwirzBQa8JqGqUVLO:-NIquPCI5aHD324dgCGO:bkd4i31) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It should be. 
</blockquote></details>

so is it `hash(URI)` or `hash(content)` ?
___
*[`integration-tests/asset/nft_mint.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcB3LC4RkifTa_8_eP:-NIqubis0LY2aaYhFGnB:b-ry7nz4) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean value
</blockquote></details>

well it looks like some value for NFT 
if you have symbol for class it is more likely to be "classsymbol"
___
*[`proto/coreum/asset/v1/tx.proto` line 81 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlHEer-OkNbedjFbPS:-NIqw3bo9aPQnxgsMZ9X:b-usc33p) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/proto/coreum/asset/v1/tx.proto#L81)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Frankly speaking I didn't get
</blockquote></details>

Lets discuss on the call
___
*[`x/asset/keeper/msg_server.go` line 178 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawKZN1gMOOIv3vV4C:-NIqvpi96M4NcaCyGM9i:bsju5z6) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L178)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's not changing. This is how we can say it should be generated. 
</blockquote></details>

agree with Wojtek
I prefer to have acronyms named properly (ID, HTTP, URL etc)
___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NIqvyDd98IQVi3Wmgso:b-usc33p) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but doesn't it work properly now when you do this in `BuildFungibleTokenDenom` ?

```
return strings.ToLower(symbol) + denomSeparator + issuer.String()
```
</blockquote></details>

Lets discuss on the call


<!-- Sent from Reviewable.io -->

2022-12-12 10:50 UTC, miladz68 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 29 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`x/asset/types/nft.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIl4nQD9xtyQK5UscZl:-NJ4x2588_E8Ej60tkYk:biuvetx) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/x/asset/types/nft.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also don't like this structure but I'm not sure we can do smth better with it 
Lets discuss, maybe we can come up with smth 
</blockquote></details>

It was decided in the call to keep this type. 


<!-- Sent from Reviewable.io -->

2022-12-12 11:08 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 29 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-12 12:09 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 29 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/nft_class.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbw0uY2iUV6lc9RM3m:-NJ4a2hc8EywbPx2lnmA:b-hw7ljp) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets discuss on the call
</blockquote></details>

Updated to the issuer.
___
*[`integration-tests/asset/nft_class.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbwirzBQa8JqGqUVLO:-NJ4a79eDePAgX3cJyDJ:b-vxj3m9) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so is it `hash(URI)` or `hash(content)` ?
</blockquote></details>

`hash(content)`
Update in all tests to `content-hash` in all tests.
___
*[`integration-tests/asset/nft_mint.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIcB3LC4RkifTa_8_eP:-NJ4adERBoTaQXQQe4Jr:b-prg4pu) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_mint.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well it looks like some value for NFT 
if you have symbol for class it is more likely to be "classsymbol"
</blockquote></details>

Updated to the ""NFTClassSymbol""



_Code quote:_
```Go
"nftsymbol"
```
___
*[`integration-tests/asset/nft_mint.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIgR2m3AeosxC35PDuv:-NJ4alUqEZPxGi7ZajWb:b-7tba37) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/integration-tests/asset/nft_mint.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

very good point
</blockquote></details>

Which exactly? We have that already. Why do we need to duplicate it? 
___
*[`proto/coreum/asset/v1/event.proto` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlh9ezBldEy0_CiGN-:-NJ4ay7J23uHECEnN1tr:b-m683ww) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/proto/coreum/asset/v1/event.proto#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so events for NFT minting are defined in x/nft but they don't have anything for Class ?
That is strange
</blockquote></details>

They have cassID.
___
*[`proto/coreum/asset/v1/tx.proto` line 81 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlHEer-OkNbedjFbPS:-NJ4b1zI4aJTlP1BhGcZ:b-ikvnac) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/proto/coreum/asset/v1/tx.proto#L81)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets discuss on the call
</blockquote></details>

Discussed and decided to go with the current approach.
___
*[`x/asset/client/cli/nft_tx.go` line 45 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIm_nC26A5AxMstmD-r:-NJ4bQrBCjYN-98uPH_J:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/client/cli/nft_tx.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

please use "real" data in examples

smth like:
- ABC token description -> ABC class description
- metadata-uri -> http://...
- uri-hash -> e000624
</blockquote></details>

Done.
___
*[`x/asset/keeper/msg_server.go` line 178 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIawKZN1gMOOIv3vV4C:-NJ4c79G3NYQIRQs-bC0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/msg_server.go#L178)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree with Wojtek
I prefer to have acronyms named properly (ID, HTTP, URL etc)
</blockquote></details>

Done.
___
*[`x/asset/keeper/msg_server.go` line 169 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIqryfjAGCh1QPKWoq3:-NJ4bgMk--n2uRTGcJVd:b-hn1ppj) ([raw file](https://github.com/coreumfoundation/coreum/blob/3000712759bbb0a4e8e835646abf545f95e90b19/x/asset/keeper/msg_server.go#L169)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not neeeded line ?
</blockquote></details>

Right, removed.



_Code quote:_
```Go
func (ms MsgServer) MintNonFungibleToken(ctx context.Context, req 
```
___
*[`x/asset/keeper/msg_server.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIqrWdd1TZK7q1GW3_Q:-NJ4c0064Ii-h4lbUuht:b-5lpcxr) ([raw file](https://github.com/coreumfoundation/coreum/blob/3000712759bbb0a4e8e835646abf545f95e90b19/x/asset/keeper/msg_server.go#L172)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I don't think it is a good idea to hardcode `MsgCreateNonFungibleTokenClass`in error
Maybe you can probably use %T or remove it at all
</blockquote></details>

Agree, removed the type from message.



_Code quote:_
```Go
in MsgMintNonFungibleToken
```
___
*[`x/asset/types/nft.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NICFWnL05OqZUjHoDfi:-NJ4d7ZU-MTlkU4Mzxju:b-i2jans) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/types/nft.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets discuss on the call
</blockquote></details>

As discussed we allow: [a-zA-Z][a-zA-Z0-9]{0,40} and save the lowecase symbol in the ID. 



_Code quote:_
```Go
regexp.MustCompile(nftSymbol
```
___
*[`x/asset/types/nft.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIl4nQD9xtyQK5UscZl:-NJ4dacsAfafzOUfZLZN:b-3vwwa1) ([raw file](https://github.com/coreumfoundation/coreum/blob/594a470ed80928410222134ed11548ebcfed943f/x/asset/types/nft.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also don't like this structure but I'm not sure we can do smth better with it 
Lets discuss, maybe we can come up with smth 
</blockquote></details>

Discussed, and decided to go with it.
___
*[`x/asset/types/nft.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlgSe_6HOFmBYlLp0R:-NJ4dNfgCNtu6XAPr-ng:br9umv8) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I propose to make FT & NFT regex similar so it is not that confusing for users
I think we should at least allow:
- same list of symbols
- same length where possible/logical
</blockquote></details>

I don't think we should combine them, they are separate so the change in one should affect the other.
___
*[`x/asset/types/nft_msgs_test.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NImml0bCXOAvbdxhMND:-NJ4djSt26SjguJHUY6b:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft_msgs_test.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

validMessage
</blockquote></details>

Done.



_Code quote:_
```Go
validaMessage
```
___
*[`x/asset/types/nft_msgs_test.go` line 34 at r4](https://reviewable.io/re [...]

2022-12-12 14:27 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 20 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/asset/keeper/issue.go` line 129 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJ5gFuNCStX16m078rP:-NJ5isLhDWIvQeq37UFw:b-bq08sm) ([raw file](https://github.com/coreumfoundation/coreum/blob/7bca160f62464579e15a1701b93fe8cd0cba14f4/x/asset/keeper/issue.go#L129)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@miladz68 WDYT ?
</blockquote></details>

do not pay attention
some reviewable issue here


<!-- Sent from Reviewable.io -->

2022-12-13 07:38 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/nft_class.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbwirzBQa8JqGqUVLO:-NJ9NgHPCB9MjF06ng4f:b-7wjwfd) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I actually didn't want to change it but just discuss. So if you can rollback it would be nice

I was just interested about the meaning of this field because the name is really confusing. It should be named smth like URIDataHash.
But I understand that it is a part of std module so we can do nothing about it.
is it correct ?
</blockquote></details>

Actually, we can name it in the way we like, but I would stick to the default names. What is regarding the rollback I like the current version more, because it's a test, and the hash can be any string even "my-data-hash".
___
*[`pkg/config/deterministic_gas.go` line 181 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJ5guB399ds2Gp9n8Vx:-NJ9OSeY3nUCHCtHHWvn:bx6e6zr) ([raw file](https://github.com/coreumfoundation/coreum/blob/5716ec9edc69b492ea1e87bd3d5b1c54f0fb4d45/pkg/config/deterministic_gas.go#L181)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do I understand it correctly
nft send has a single destination multiple nfts are not possible in a single msg like it is done in bank `[]sdk.Coin{}` 
</blockquote></details>

You can add multiple messages in the same transaction. 
___
*[`proto/coreum/asset/v1/event.proto` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlh9ezBldEy0_CiGN-:-NJ9OvsS6hcPByJwXuT6:bfw8r9m) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/proto/coreum/asset/v1/event.proto#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes they have classID but IMO that is strange that they have `EventMint` but don't have/emit events for class creation.
Do I understand everything correctly ?
</blockquote></details>

Right, there are just 3 events: `EventSend`, `EventMint`, `EventBurn`.
___
*[`x/asset/keeper/keeper_test.go` line 26 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJ5hie_3KKV9DMLabPj:-NJ9P4BnEAD-TpHMXSWS:b-wdl8pc) ([raw file](https://github.com/coreumfoundation/coreum/blob/675c09416cb5dc10ed7246838f0a717bb43e1adf/x/asset/keeper/keeper_test.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you set SDK config somehwere else now ?
Because address prefixes and coin type is set there and I thought it is needed or no ?
</blockquote></details>

Yes, in the simapp. 
___
*[`x/asset/types/nft.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlgSe_6HOFmBYlLp0R:-NJ9PeP20VfA7uADrnn-:buvwfrj) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't mean to combine them but it is going to be confusing for users when we allow slightly different characters for almost same things in FT & NFT
I don't insist on using the same regexp but making them similar as much as possible makes sense for me

Anyways I've crated a separate point in checklist for this so resolving this one
</blockquote></details>

`reClassIDString = `[a-zA-Z][a-zA-Z0-9/:-]{2,100}` This is the ClassID and NFTID validation from the NFT module. 
So is we want to make them the same we should update the FT. 



_Code quote:_
```Go
nftIDRegexStr = `^[a-zA-Z][a-zA-Z0-9/:-]{2,100}$`
```
___
*[`go.mod` line 14 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJ5g6fACQVuNYeghY9v:-NJ9PtbU9fM5iy66NtbM:btlfio0) ([raw file](https://github.com/coreumfoundation/coreum/blob/7bca160f62464579e15a1701b93fe8cd0cba14f4/go.mod#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it expected here ?
</blockquote></details>

That part is rolled back.


<!-- Sent from Reviewable.io -->

2022-12-13 12:40 UTC, wojtek-coreum requested changes
> Reviewed 1 of 6 files at r4, 9 of 29 files at r5, 13 of 14 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/asset/v1/tx.proto` line 95 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJATafS-0-uMbPtaTjn:-NJATafS-0-uMbPtaTjo:bbcpqec) ([raw file](https://github.com/coreumfoundation/coreum/blob/5716ec9edc69b492ea1e87bd3d5b1c54f0fb4d45/proto/coreum/asset/v1/tx.proto#L95)):*
> ```protobuf
> 
> // MsgIssueNonFungibleTokenClass defines message for the IssueNonFungibleTokenClass method.
> message MsgIssueNonFungibleTokenClass {
> ```

Please put NFT-specific messages below FT-specific ones
___
*[`x/asset/keeper/nft_keeper.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0pJ57anvuY7KIIbp:-NJAU7Jy6NphCxJueNvo:b-9jfqr3) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L50)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated now.
</blockquote></details>

Nope :-)
___
*[`x/asset/keeper/nft_keeper.go` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0mxD8neiQWz7iE_-:-NJAU9q-9X-0iyVfHCXN:bb710yj) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated now.
</blockquote></details>

Nope
___
*[`x/asset/keeper/nft_keeper.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0rBK-QEzbqkbER4-:-NJAUBIy5-f79RnlMhSO:bb7lgjf) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L55)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated now.
</blockquote></details>

nope
___
*[`x/asset/keeper/nft_keeper.go` line 98 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1hlu0pSuVdf7hPBR:-NJAUILW7igfLGh8ZNHa:bb7lgjf) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L98)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated now.
</blockquote></details>

nope
___
*[`x/asset/keeper/nft_keeper.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1jkp6ATx5X9_QQOo:-NJAUJkh3elgORva83Se:bb7lgjf) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated now.
</blockquote></details>

nope
___
*[`x/asset/keeper/nft_keeper.go` line 100 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1lip0ERY5XSdQz2P:-NJAUKrW6ZDvX5oCixtn:bb7lgjf) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L100)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated now.
</blockquote></details>

nope


<!-- Sent from Reviewable.io -->

2022-12-13 13:18 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`integration-tests/asset/nft_class.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIbwirzBQa8JqGqUVLO:-NJAceES2xtZP569kVxL:b-qdhggz) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/integration-tests/asset/nft_class.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, we can name it in the way we like, but I would stick to the default names. What is regarding the rollback I like the current version more, because it's a test, and the hash can be any string even "my-data-hash".
</blockquote></details>

ok lets keep it
___
*[`pkg/config/deterministic_gas.go` line 181 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJ5guB399ds2Gp9n8Vx:-NJAckEW5rhon6kwmRp2:bn9ljyh) ([raw file](https://github.com/coreumfoundation/coreum/blob/5716ec9edc69b492ea1e87bd3d5b1c54f0fb4d45/pkg/config/deterministic_gas.go#L181)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can add multiple messages in the same transaction. 
</blockquote></details>

ok
checked it it is impossible
___
*[`proto/coreum/asset/v1/event.proto` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlh9ezBldEy0_CiGN-:-NJAbV5W-RtX84R7a-jo:b-q00e4u) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/proto/coreum/asset/v1/event.proto#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, there are just 3 events: `EventSend`, `EventMint`, `EventBurn`.
</blockquote></details>

ok
that is strange from their side but ok
___
*[`x/asset/types/nft.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlgSe_6HOFmBYlLp0R:-NJAbkKg6RLFRwDEHRvD:bah77fh) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`reClassIDString = `[a-zA-Z][a-zA-Z0-9/:-]{2,100}` This is the ClassID and NFTID validation from the NFT module. 
So is we want to make them the same we should update the FT. 
</blockquote></details>

ok but `:` is not supported 


<!-- Sent from Reviewable.io -->

2022-12-13 13:19 UTC, ysv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/asset/keeper/nft_keeper.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0pJ57anvuY7KIIbp:-NJAcqFeCO-nhA7nj0jF:b-vundd9) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nope :-)
</blockquote></details>

I think that Dzmitry doesn't want to change std NFT module naming etc
While on our module it is changed


<!-- Sent from Reviewable.io -->

2022-12-13 13:54 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`proto/coreum/asset/v1/tx.proto` line 95 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJATafS-0-uMbPtaTjn:-NJAkYdJEzshL6jqJVh8:bqio0ic) ([raw file](https://github.com/coreumfoundation/coreum/blob/5716ec9edc69b492ea1e87bd3d5b1c54f0fb4d45/proto/coreum/asset/v1/tx.proto#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please put NFT-specific messages below FT-specific ones
</blockquote></details>

Updated, that was the merge result.



_Code quote:_
```protobuf
MsgIssueNonFungibleTokenClass 
```
___
*[`x/asset/keeper/nft_keeper.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0pJ57anvuY7KIIbp:-NJAkbirDXHqMD1Enip6:b-vwmu2) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think that Dzmitry doesn't want to change std NFT module naming etc
While on our module it is changed
</blockquote></details>

Right. That was our initial idea and I follow it.
___
*[`x/asset/keeper/nft_keeper.go` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0mxD8neiQWz7iE_-:-NJAkiTLB3fNiLFCJpC5:b-dnzfjq) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L54)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

I changed our model's but not the SDK's.
___
*[`x/asset/keeper/nft_keeper.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb0rBK-QEzbqkbER4-:-NJAko7gC_3VGp5qvltb:b-dnzfjq) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L55)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nope
</blockquote></details>

I changed our model's but not the SDK's.
___
*[`x/asset/keeper/nft_keeper.go` line 98 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1hlu0pSuVdf7hPBR:-NJAkonJ1Fy76SEFr5zx:b-dnzfjq) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nope
</blockquote></details>

I changed our model's but not the SDK's.
___
*[`x/asset/keeper/nft_keeper.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1jkp6ATx5X9_QQOo:-NJAkpRH9CA1sIrRdYHc:b-dnzfjq) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nope
</blockquote></details>

I changed our model's but not the SDK's.
___
*[`x/asset/keeper/nft_keeper.go` line 100 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIb1lip0ERY5XSdQz2P:-NJAkpze9Bt8PW3D4S85:b-dnzfjq) ([raw file](https://github.com/coreumfoundation/coreum/blob/df292b92ffe55b4288ac85db717cdb607f0c3f1b/x/asset/keeper/nft_keeper.go#L100)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nope
</blockquote></details>

I changed our model's but not the SDK's.
___
*[`x/asset/types/nft.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlgSe_6HOFmBYlLp0R:-NJAktkd9mc-dspiDpHq:b-q6b7t8) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok but `:` is not supported 
</blockquote></details>

Do you mean remove it here? 


<!-- Sent from Reviewable.io -->

2022-12-14 12:16 UTC, ysv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/types/nft.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NIlgSe_6HOFmBYlLp0R:-NJFYmtm1Muo0P4uk8vt:b143zqx) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad48ff7cb9ced6f1bbc59348e895ff38bfe06399/x/asset/types/nft.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you mean remove it here? 
</blockquote></details>

actually lets keep it
I have added a separate task to rewise this regexps later so we can do this in a single shot


<!-- Sent from Reviewable.io -->

2022-12-14 13:55 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-12-15 08:00 UTC, wojtek-coreum requested changes
> Reviewed 6 of 29 files at r5, 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`integration-tests/asset/nft_class.go` line 36 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJl4rU3PsU-bk7cdsc:-NJJl4rW1F492xeESmdh:b-76me21) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/integration-tests/asset/nft_class.go#L36)):*
> ```Go
> 		Name:        "name",
> 		Description: "description",
> 		URI:         "https://my-class-meta.int/1",
> ```

There is a convention to use `.invalid` domain for such cases
___
*[`integration-tests/asset/nft_mint.go` line 52 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJlP9U59qejGV4uPAn:-NJJlP9U59qejGV4uPAo:b-q5s0du) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/integration-tests/asset/nft_mint.go#L52)):*
> ```Go
> 		ID:      "id-1",
> 		ClassID: classID,
> 		URI:     "https://my-class-meta.int/1",
> ```

.invalid
___
*[`x/asset/client/cli/nft_mint_test.go` line 15 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJm29kAhzw8pbyAwzb:-NJJm29l3-JPQQs5Wx55:bvvwz5w) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/client/cli/nft_mint_test.go#L15)):*
> ```Go
> )
> 
> func TestCmdTxMintNonFungibleToken(t *testing.T) {
> ```

Why isn't it it in nft_tx_test.go?
___
*[`x/asset/client/cli/nft_mint_test.go` line 23 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJli1h-_AaPRiucAvJ:-NJJli1iA7V8ff1lEMo5:b-q5s0du) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/client/cli/nft_mint_test.go#L23)):*
> ```Go
> 	ctx := validator.ClientCtx
> 
> 	args := []string{symbol, "class name", "class description", "https://my-class-meta.int/1", "content-hash"}
> ```

.invalid
___
*[`x/asset/client/cli/nft_mint_test.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJloSX8upnOViC6N78:-NJJloSX8upnOViC6N79:b-32ypbi) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/client/cli/nft_mint_test.go#L29)):*
> ```Go
> 
> 	classID := types.BuildNonFungibleTokenClassID(symbol, validator.Address)
> 	args = []string{classID, "nft-1", "https://my-nft-meta.int/1", "9309e7e6e96150afbf181d308fe88343ab1cbec391b7717150a7fb217b4cf0a9"}
> ```

invalid
___
*[`x/asset/keeper/nft_keeper_test.go` line 35 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmRffDqjuz2TmWZYh:-NJJmRffDqjuz2TmWZYi:b-q5s0du) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L35)):*
> ```Go
> 		Symbol:      "Symbol",
> 		Description: "description",
> 		URI:         "https://my-class-meta.int/1",
> ```

.invalid
___
*[`x/asset/keeper/nft_keeper_test.go` line 57 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmYkY37TWp3KRz6ox:-NJJmYkZ7jqm6BrWby61:b-orsoln) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L57)):*
> ```Go
> 	settings.Symbol = "SYMBOL"
> 	_, err = nftKeeper.IssueClass(ctx, settings)
> 	requireT.True(types.ErrInvalidNonFungibleTokenClass.Is(err))
> ```

ErrInvalidInput from the other PR?
___
*[`x/asset/keeper/nft_keeper_test.go` line 83 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmfDj5HKEemvj5vLy:-NJJmfDj5HKEemvj5vLz:b-q5s0du) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L83)):*
> ```Go
> 		ClassID: classID,
> 		ID:      "my-id",
> 		URI:     "https://my-nft-meta.int/1",
> ```

.invalid
___
*[`x/asset/keeper/nft_keeper_test.go` line 106 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmlFE-vTmrvBYeJWJ:-NJJmlFE-vTmrvBYeJWK:b-wnotd9) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L106)):*
> ```Go
> 	// mint second NFT with the same ID
> 	err = nftKeeper.Mint(ctx, settings)
> 	requireT.True(types.ErrInvalidNonFungibleToken.Is(err))
> ```

ErrInvalidInput
___
*[`x/asset/types/nft_msgs_test.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmrwXCviGJFhFlLsC:-NJJmrwXCviGJFhFlLsD:b-q5s0du) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L29)):*
> ```Go
> 		Symbol:      "Symbol",
> 		Description: "description",
> 		URI:         "https://my.uri",
> ```

.invalid
___
*[`x/asset/types/nft_msgs_test.go` line 147 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJn2Uk-kiaeC16d3M2:-NJJn2UlEoOhaY4Q8Tge:b-q5s0du) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L147)):*
> ```Go
> 		ID:      "my-id",
> 		ClassID: "symbol-devcore172rc5sz2uclpsy3vvx3y79ah5dk450z5ruq2r5",
> 		URI:     "https://my.uri",
> ```

.invalid


<!-- Sent from Reviewable.io -->

2022-12-15 08:59 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/asset/nft_class.go` line 36 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJl4rU3PsU-bk7cdsc:-NJJzHENBggKTgWakHHo:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/integration-tests/asset/nft_class.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is a convention to use `.invalid` domain for such cases
</blockquote></details>

Updated.
___
*[`integration-tests/asset/nft_mint.go` line 52 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJlP9U59qejGV4uPAn:-NJK-EpO4u_XWX8ZK-ZJ:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/integration-tests/asset/nft_mint.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

.invalid
</blockquote></details>

Updated.
___
*[`x/asset/client/cli/nft_mint_test.go` line 15 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJm29kAhzw8pbyAwzb:-NJJzZEj1UIH1dnX7Q2Q:bpifrhe) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/client/cli/nft_mint_test.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why isn't it it in nft_tx_test.go?
</blockquote></details>

It's done with the reference to the `ft`. For the ft we have now separate file. But I would merge them all into one, and same for the implementation. (It's about your next task :-) )



_Code quote:_
```Go
TestCmdTxMintNonFungibleToken(t *testing.T) {
```
___
*[`x/asset/client/cli/nft_mint_test.go` line 23 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJli1h-_AaPRiucAvJ:-NJK-FhfDmCe0k7It5OH:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/client/cli/nft_mint_test.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

.invalid
</blockquote></details>

Updated.
___
*[`x/asset/client/cli/nft_mint_test.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJloSX8upnOViC6N78:-NJK-GW54SbNV1he34eK:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/client/cli/nft_mint_test.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

invalid
</blockquote></details>

Updated.
___
*[`x/asset/keeper/nft_keeper_test.go` line 35 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmRffDqjuz2TmWZYh:-NJK-HA22HYTHD7GpL72:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

.invalid
</blockquote></details>

Updated.
___
*[`x/asset/keeper/nft_keeper_test.go` line 57 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmYkY37TWp3KRz6ox:-NJK-J2gDygmsjaGtu01:bjcn9lb) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L57)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ErrInvalidInput from the other PR?
</blockquote></details>

Is it merged?
___
*[`x/asset/keeper/nft_keeper_test.go` line 83 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmfDj5HKEemvj5vLy:-NJK-L2S--brD6gnpaHv:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L83)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

.invalid
</blockquote></details>

Updated.
___
*[`x/asset/keeper/nft_keeper_test.go` line 106 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmlFE-vTmrvBYeJWJ:-NJK-LqcEcxGcUmGPeMM:bjcn9lb) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ErrInvalidInput
</blockquote></details>

Is it merged?
___
*[`x/asset/types/nft_msgs_test.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmrwXCviGJFhFlLsC:-NJK-NAp1ZIqMCj3NjTv:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

.invalid
</blockquote></details>

Updated.
___
*[`x/asset/types/nft_msgs_test.go` line 147 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJn2Uk-kiaeC16d3M2:-NJK-NkDCj-wg4vxJAdO:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

.invalid
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-12-15 11:10 UTC, miladz68 approved these changes
> Reviewed 11 of 29 files at r5, 12 of 14 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-15 12:14 UTC, wojtek-coreum requested changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil)

___
*[`x/asset/keeper/nft_keeper_test.go` line 57 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmYkY37TWp3KRz6ox:-NJKh3Kz7rlZoNI7UrCX:b-dfw8jb) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L57)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it merged?
</blockquote></details>

will be in a moment :)
___
*[`x/asset/types/nft_msgs_test.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmrwXCviGJFhFlLsC:-NJKhEto7SgZdzzi5dSn:bb7lgjf) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

nope
___
*[`x/asset/types/nft_msgs_test.go` line 147 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJn2Uk-kiaeC16d3M2:-NJKhAkYEfP5MLgOOZTL:bb7lgjf) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L147)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

nope


<!-- Sent from Reviewable.io -->

2022-12-15 12:29 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum)

___
*[`x/asset/types/nft_msgs_test.go` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmrwXCviGJFhFlLsC:-NJKkccr6N71khNlAMbB:b-78gfje) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Now yes.
___
*[`x/asset/types/nft_msgs_test.go` line 147 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJn2Uk-kiaeC16d3M2:-NJKkeAuDRrUm8YDiJjR:b-78gfje) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/types/nft_msgs_test.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Now yes.


<!-- Sent from Reviewable.io -->

2022-12-15 12:31 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)



<!-- Sent from Reviewable.io -->

2022-12-15 14:56 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: 17 of 36 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/nft_keeper_test.go` line 57 at r9](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJJmYkY37TWp3KRz6ox:-NJLHEQ91fwW0rdbvnAn:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/89fe1005be4e3279446d0392e404b29624616a27/x/asset/keeper/nft_keeper_test.go#L57)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

will be in a moment :)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-15 15:11 UTC, wojtek-coreum requested changes
> Reviewed 19 of 19 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`x/asset/types/errors.go` line 23 at r12](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJLJxwsDFjD702hE5fE:-NJLJxwt-HfaYyoFiTsC:b-s1tdtp) ([raw file](https://github.com/coreumfoundation/coreum/blob/e01e8bcf1a427e024823751eb554cb7e89a60580/x/asset/types/errors.go#L23)):*
> ```Go
> 	ErrWhitelistedLimitExceeded = sdkerrors.Register(ModuleName, 7, "whitelisted limit exceeded")
> 	// ErrInvalidID is returned when the provided id is not of valid format
> 	ErrInvalidID = sdkerrors.Register(ModuleName, 11, "id format is not valid")
> ```

should be 8


<!-- Sent from Reviewable.io -->

2022-12-15 15:11 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/asset/types/errors.go` line 23 at r12](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJLJxwsDFjD702hE5fE:-NJLKror7egPD9sAOv54:bx3iq6m) ([raw file](https://github.com/coreumfoundation/coreum/blob/e01e8bcf1a427e024823751eb554cb7e89a60580/x/asset/types/errors.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

should be 8
</blockquote></details>

Addressed



_Code quote:_
```Go
	ErrInvalidID = sdkerrors.R
```


<!-- Sent from Reviewable.io -->

2022-12-15 15:17 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)



<!-- Sent from Reviewable.io -->

2022-12-15 15:29 UTC, miladz68 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 19 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277#-:-NJLOnfyAyeewCvwkEyr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`pkg/config/deterministic_gas.go` line 115 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJLOG7W6fiRhW7drsNg:-NJLOG7W6fiRhW7drsNh:b-wdnzne) ([raw file](https://github.com/coreumfoundation/coreum/blob/f31d18aff606afe46559da0717a9b01d25d1130d/pkg/config/deterministic_gas.go#L115)):*
> ```Go
> //
> //nolint:funlen // it doesn't make sense to split entries
> func (dgr DeterministicGasRequirements) GasRequiredByMessage(msg sdk.Msg) (uint64, bool) { //nolint:gocyclo // team decided to have flat structure
> ```

non-blocking
I had to google it to know why it is needed. 
Maybe add comment that it happens because of too many switch case statements. 


<!-- Sent from Reviewable.io -->

2022-12-15 15:37 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/277)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`pkg/config/deterministic_gas.go` line 115 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/277#-NJLOG7W6fiRhW7drsNg:-NJLQdxC0VfLOOnUxEy7:b-m02umr) ([raw file](https://github.com/coreumfoundation/coreum/blob/f31d18aff606afe46559da0717a9b01d25d1130d/pkg/config/deterministic_gas.go#L115)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
I had to google it to know why it is needed. 
Maybe add comment that it happens because of too many switch case statements. 
</blockquote></details>

Oh, I guess that's the dev responsibility to google it once :-)


<!-- Sent from Reviewable.io -->

2022-12-15 15:38 UTC, merged