Implemented asset burn rate
CoreumFoundation/coreum pull request #284
Opened 2022-12-07 12:52 UTC by miladz68

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/coreum/284)

2022-12-08 08:19 UTC, wojtek-coreum requested changes
> Reviewed 16 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 16 of 19 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkk7zBA3beJbBC6Qde:-NIkk7zBA3beJbBC6Qdf:b-5314do) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/asset.proto#L23)):*
> ```protobuf
>   // burn_rate is a number between 0 and 1 which will be multiplied by send amount to determine
>   // burn_amount. This value will be burnt on top of the send amount.
>   float burn_rate = 4;
> ```

we should use `sdk.Dec` type for this
___
*[`proto/coreum/asset/v1/asset.proto` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkChr4osn2aiYfzrk:-NIkkChr4osn2aiYfzrl:b-5314do) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/asset.proto#L40)):*
> ```protobuf
>   // burn_rate is a number between 0 and 1 which will be multiplied by send amount to determine
>   // burn_amount. This value will be burnt on top of the send amount.
>   float burn_rate = 9;
> ```

we should use `sdk.Dec` type for this
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkEfj7d1bQ05WP2BG:-NIkkEfj7d1bQ05WP2BH:b-5314do) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/event.proto#L24)):*
> ```protobuf
>   string description = 8;
>   repeated FungibleTokenFeature features = 9;
>   float burn_rate = 10;
> ```

we should use `sdk.Dec` type for this
___
*[`proto/coreum/asset/v1/tx.proto` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkGSO3jsRzFKzclPH:-NIkkGSO3jsRzFKzclPI:b-5314do) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/tx.proto#L52)):*
> ```protobuf
>   // burn_rate is a number between 0 and 1 which will be multiplied by send amount to determine
>   // burn_amount. This value will be burnt on top of the send amount.
>   float burn_rate = 9;
> ```

we should use `sdk.Dec` type for this
___
*[`x/asset/client/cli/tx.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkOScEQ_umXQx2Tfl:-NIkkOScEQ_umXQx2Tfm:bnigaex) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L24)):*
> ```Go
> const (
> 	featuresFlag = "features"
> 	burnRateFlag = "burn_rate"
> ```

burn-rate
___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NIkkMCd7YDSEt3kyRxw:bqenjvd) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
> ```Go
> 	sort.Strings(allowedFeatures)
> 	cmd := &cobra.Command{
> 		Use:   "issue [symbol] [recipient_address] [initial_amount] [description] --from [issuer] --features=" + strings.Join(allowedFeatures, ","+"burn_rate=0.12"),
> ```

--burn-rate
___
*[`x/asset/client/cli/tx.go` line 125 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkTsf2FIp9NeWzQwR:-NIkkTsf2FIp9NeWzQwS:b-m40cif) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L125)):*
> ```Go
> 			}
> 
> 			burnRate, err := cmd.Flags().GetFloat32(burnRateFlag)
> ```

read string and convert to sdk.Dec
___
*[`x/asset/client/cli/tx.go` line 156 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkl1C83DuMCroZc25R:-NIkl1C83DuMCroZc25S:bpeppye) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L156)):*
> ```Go
> 	}
> 	cmd.Flags().StringSlice(featuresFlag, []string{}, "Features to be enabled on fungible token. e.g --features="+strings.Join(allowedFeatures, ","))
> 	cmd.Flags().Float32(burnRateFlag, 0, "Burn rate indicates the rate at which coins will be burned on top of the send amount in every send action. must be between 0 and 1.")
> ```

must -> Must
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklao29ZqnOBgRHUFB:-NIklao29ZqnOBgRHUFC:b-h7k4vf) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
> ```Go
> 		if ft.BurnRate > 0 && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String() {
> 			coinsToBurn := ft.CalculateBurnCoin(coin)
> 			err = k.burnFungibleToken(ctx, coinsToBurn, fromAddress)
> ```

`IsSendAllowed` is a bad place to take any final action. Burning should happen only in `SendCoins` of wbank's keeper
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklyyZ1yjayaKOGlLT:-NIklyyZ1yjayaKOGlLU:bi56rrq) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
> ```Go
> 		if ft.BurnRate > 0 && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String() {
> 			coinsToBurn := ft.CalculateBurnCoin(coin)
> 			err = k.burnFungibleToken(ctx, coinsToBurn, fromAddress)
> ```

let's not mix scopes: `err :=`
___
*[`x/asset/keeper/keeper.go` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkmU9B5QuaeA0iUm0j:-NIkmU9B5QuaeA0iUm0k:b-4va2gc) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L60)):*
> ```Go
> 
> // InterceptInputOutputCoins extends InputOutputCoins method of the bank keeper
> func (k Keeper) InterceptInputOutputCoins(ctx sdk.Context, inputs []banktypes.Input, outputs []banktypes.Output) error {
> ```

IMO `IsSendAllowed` should be merged into this code. Because single send is a sepcial case of sending with many inoputs and outputs.
___
*[`x/asset/types/ft.go` line 121 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIknJbXCm1zDp9KTB4J:-NIknJbXCm1zDp9KTB4K:bkthqsm) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L121)):*
> ```Go
> 
> // CalculateBurnCoin returns the coins to be burned
> func (ftd FungibleTokenDefinition) CalculateBurnCoin(coin sdk.Coin) sdk.Coin {
> ```

This must be redone to use sdk.Dec.
Example from our testing framework:

```go
                // Ceil().RoundInt() is here to be compatible with the sdk's TxFactory
		// https://github.com/cosmos/cosmos-sdk/blob/ff416ee63d32da5d520a8b2d16b00da762416146/client/tx/factory.go#L223
		amt := options.GasPrice.Mul(sdk.NewDec(int64(gas))).Ceil().RoundInt()
```

Cosmos SDK delivers functions like `sdk.NewDecWithPrec()` and similar to define precision for Dec


<!-- Sent from Reviewable.io -->

2022-12-09 08:43 UTC, dzmitryhil requested changes
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 16 of 19 files reviewed, 23 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/burn_rate.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpufLY2uvANGWvG00M:-NIpufLY2uvANGWvG00N:bsd7ilc) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L53)):*
> ```Go
> 		Recipient:     issuer.String(),
> 		InitialAmount: sdk.NewInt(1000),
> 		Features:      []assettypes.FungibleTokenFeature{},
> ```

Why do you need to provide an empty list here?
___
*[`integration-tests/asset/burn_rate.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq-Ze3-y2BGIiBtiRu:-NIq-Ze3-y2BGIiBtiRv:b-yrhuxi) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L53)):*
> ```Go
> 		Recipient:     issuer.String(),
> 		InitialAmount: sdk.NewInt(1000),
> 		Features:      []assettypes.FungibleTokenFeature{},
> ```

@ysv Don't we need any feature here?
___
*[`integration-tests/asset/burn_rate.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIputHU8i7FxV3s_MoQ:-NIputHU8i7FxV3s_MoR:b-puwa7z) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L69)):*
> ```Go
> 	denom := fungibleTokenIssuedEvents[0].Denom
> 
> 	// send from issuer to recipient 1 (burn must not apply)
> ```

I would propose updating comment "recipient 1" -> "recipient1" (same for the following comment), since it's a reference to a variable. 
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkEfj7d1bQ05WP2BG:-NIpp2Lv29g2wGsnJlGd:b-8ayu6x) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/event.proto#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we should use `sdk.Dec` type for this
</blockquote></details>

Agree
___
*[`x/asset/client/cli/burn_rate_test.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpwDSUB0ln8yavEgl5:-NIpwDSUB0ln8yavEgl6:b-b7wdp4) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/burn_rate_test.go#L24)):*
> ```Go
> )
> 
> func TestBurnRate(t *testing.T) {
> ```

Actually, such tests are not really needed since you do them in the integration tests. IMHO the responsibility of the CLI test is just to check that all params are passed and TX is executed. So in your case you cam issue and check that event contains the rate. 
___
*[`x/asset/keeper/burn_rate_test.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpy9aTChiA1RL5Uu-I:-NIpy9aTChiA1RL5Uu-J:b-ea55mg) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L30)):*
> ```Go
> 		},
> 		{
> 			rate:     0.01,
> ```

My understanding was different. We agreed to round to differently,  `round(1.1) = 2`. @ysv @wojtek-coreum correct me if I'm wrong please.
___
*[`x/asset/keeper/burn_rate_test.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0jgP3-cRc9fF5dTy:-NIq0jgP3-cRc9fF5dTz:b-2b73q) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L65)):*
> ```Go
> }
> 
> func TestKeeper_BurnRate_BankSend(t *testing.T) {
> ```

Why do we have the test for the `BankSend`, but don't have it for the `Intercept`?
___
*[`x/asset/keeper/keeper.go` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkmU9B5QuaeA0iUm0j:-NIq-sLz9JQaRig-Phey:bxhpz9c) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L60)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO `IsSendAllowed` should be merged into this code. Because single send is a sepcial case of sending with many inoputs and outputs.
</blockquote></details>

But that logic is different from what we aligned on! 
___
*[`x/asset/types/errors.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0zVq9T1PPD64AC14:-NIq0zVq9T1PPD64AC15:bz0jq7f) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/errors.go#L27)):*
> ```Go
> 	ErrGloballyFrozen = sdkerrors.Register(ModuleName, 9, "token is globally frozen")
> 	// ErrInvalidBurnRate is returned when the provided symbol is not of valid format
> 	ErrInvalidBurnRate = sdkerrors.Register(ModuleName, 10, "burn rate is not valid")
> ```

Do you really need to have a specific error for it? Is it not enough to use "ErrInvalidFungibleToken" ?
___
*[`x/asset/types/ft.go` line 114 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0H4g0ztDHBL84Ykr:-NIq0H4g0ztDHBL84Yks:b2hhvts) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L114)):*
> ```Go
> func ValidateBurnRate(burnRate float32) error {
> 	if burnRate < 0 || burnRate > 1 {
> 		return sdkerrors.Wrap(ErrInvalidBurnRate, "burn rate is not within acceptable rate")
> ```

`rate` or `range` ?
___
*[`x/asset/types/ft.go` line 123 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpxR5I8Q3g0ok9hZfR:-NIpxR5J20imTSKhz5qO:bz8cdn8) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L123)):*
> ```Go
> func (ftd FungibleTokenDefinition) CalculateBurnCoin(coin sdk.Coin) sdk.Coin {
> 	if ftd.BurnRate > 1 {
> 		panic("burn rate cannot be bigger than 1")
> ```

Didn't get why you need that panic here. This values is > 1 by it's definition. 
___
*[`x/asset/types/ft.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpxal9BlV4o9DSZSrz:-NIpxal9BlV4o9DSZSs-:b-q56p94) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L127)):*
> ```Go
> 
> 	// limit precision to 4 decimal places
> 	burnRateStr := fmt.Sprintf("%.4f", ftd.BurnRate)
> ```

That logic should be updated once you migrate to `sdk.Dec` so you will be able to use `sdk.Int` and `sdk.Dec` instead of big.*.
___
*[`x/wbank/types/expected_keepers.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpyhrIBeBjCcQtK0iE:-NIpyhrIBeBjCcQtK0iF:b4fv1z8) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/wbank/types/expected_keepers.go#L11)):*
> ```Go
> type FungibleTokenProvider interface {
> 	IsSendAllowed(ctx sdk.Context, fromAddress, toAddress sdk.AccAddress, coins sdk.Coins) error
> 	InterceptInputOutputCoins(ctx sdk.Context, inputs []banktypes.Input, outputs []banktypes.Output) error
> ```

Why do we call this func `InterceptInputOutputCoins` but another`IsSendAllowed` if in both we burn coins?



_Code quote:_
```Go
InterceptInputOutputCoins
```


<!-- Sent from Reviewable.io -->

2022-12-09 11:39 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 10 of 19 files reviewed, 23 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/burn_rate.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpufLY2uvANGWvG00M:-NIqa1un-K-anmou8u8Y:b-j6l5aa) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L53)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need to provide an empty list here?
</blockquote></details>

we don't need it, but I prefer to be explicit. Because the empty list is there, you noticed that there are no features there and asked the later question whether that is correct. 
___
*[`integration-tests/asset/burn_rate.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIputHU8i7FxV3s_MoQ:-NIqcQccETP4SEjj2OTQ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L69)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would propose updating comment "recipient 1" -> "recipient1" (same for the following comment), since it's a reference to a variable. 
</blockquote></details>

Done.
___
*[`x/asset/client/cli/tx.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkOScEQ_umXQx2Tfl:-NIqcrgkBpetcs6RIEkN:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

burn-rate
</blockquote></details>

Done.
___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NIqd7_P7Vlr6QxosSvT:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

--burn-rate
</blockquote></details>

Done.
___
*[`x/asset/client/cli/tx.go` line 156 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkl1C83DuMCroZc25R:-NIqdDNZAmTl8xJv9sMr:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L156)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

must -> Must
</blockquote></details>

Done.
___
*[`x/asset/keeper/burn_rate_test.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpy9aTChiA1RL5Uu-I:-NIqdKOy9MZCzcX85Hog:bgd5m6d) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

My understanding was different. We agreed to round to differently,  `round(1.1) = 2`. @ysv @wojtek-coreum correct me if I'm wrong please.
</blockquote></details>

and also round 0.1 to 1 ? always round up regardless
___
*[`x/asset/keeper/burn_rate_test.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0jgP3-cRc9fF5dTy:-NIqdXk6CeLaglABQnqA:b-u42d98) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we have the test for the `BankSend`, but don't have it for the `Intercept`?
</blockquote></details>

there a separate task for multi send
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklao29ZqnOBgRHUFB:-NIqdklr24omlGGEF8rz:btmhgrj) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`IsSendAllowed` is a bad place to take any final action. Burning should happen only in `SendCoins` of wbank's keeper
</blockquote></details>

I disagree, all logic regarding asset should live in asset module. We just need to rename IsSendAllowed, to InterceptSendCoin 
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklyyZ1yjayaKOGlLT:-NIqe75a04u5BsOsNZjE:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's not mix scopes: `err :=`
</blockquote></details>

Done.
___
*[`x/asset/keeper/keeper.go` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkmU9B5QuaeA0iUm0j:-NIqeD-89MqiKg0rur3I:bdv2w2o) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L60)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But that logic is different from what we aligned on! 
</blockquote></details>

let's discuss on a call
___
*[`x/asset/types/ft.go` line 114 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0H4g0ztDHBL84Ykr:-NIqesnr7T49c5t-tcAZ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L114)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`rate` or `range` ?
</blockquote></details>

Done.
___
*[`x/asset/types/ft.go` line 123 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpxR5I8Q3g0ok9hZfR:-NIqexIm5iBKagemKvut:ba3dfob) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get why you need that panic here. This values is > 1 by it's definition. 
</blockquote></details>

Removed
___
*[`x/wbank/types/expected_keepers.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpyhrIBeBjCcQtK0iE:-NIqf4uC4TMXEA81KWyo:bkhcphj) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/wbank/types/expected_keepers.go#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we call this func `InterceptInputOutputCoins` but another`IsSendAllowed` if in both we burn coins?
</blockquote></details>

Will rename
___
*[`x/asset/client/cli/burn_rate_test.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpwDSUB0ln8yavEgl5:-NIqcYwdE6bpA3krwbh8:bqog80t) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/burn_rate_test.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, such tests are not really needed since you do them in the integration tests. IMHO the responsibility of the CLI test is just to check that all params are passed and TX is executed. So in your case you cam issue and check that event contains the rate. 
</blockquote></details>

Agreed
___
*[`x/asset/types/errors.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0zVq9T1PPD64AC14:-NIqekPl4xiErkLAvdSp:ba3dfob) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/errors.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you really need t [...]

2022-12-12 07:21 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 4 of 25 files reviewed, 23 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/burn_rate.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq-Ze3-y2BGIiBtiRu:-NJ4C0FG3aZWD3MZ5GEb:b-l28epj) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L53)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv Don't we need any feature here?
</blockquote></details>

burn rate is not a flag, it was decided in a call with reza to have it as a standalone value. 
___
*[`proto/coreum/asset/v1/asset.proto` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkk7zBA3beJbBC6Qde:-NJ4C99Z5mebR2zBUbF6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/asset.proto#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we should use `sdk.Dec` type for this
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/asset.proto` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkChr4osn2aiYfzrk:-NJ4C9Q1BxbAb1fufcbA:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/asset.proto#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we should use `sdk.Dec` type for this
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkEfj7d1bQ05WP2BG:-NJ4CACy2HcOEgPCdySX:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/event.proto#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done.
___
*[`proto/coreum/asset/v1/tx.proto` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkGSO3jsRzFKzclPH:-NJ4CB3IBUhSZmK0HU1y:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/proto/coreum/asset/v1/tx.proto#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we should use `sdk.Dec` type for this
</blockquote></details>

Done.
___
*[`x/asset/client/cli/tx.go` line 125 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkTsf2FIp9NeWzQwR:-NJ4CD6q-OBUFrFhmNUL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

read string and convert to sdk.Dec
</blockquote></details>

Done.
___
*[`x/asset/types/ft.go` line 121 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIknJbXCm1zDp9KTB4J:-NJ4CGjb5jjdz3NxdbE4:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L121)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This must be redone to use sdk.Dec.
Example from our testing framework:

```go
                // Ceil().RoundInt() is here to be compatible with the sdk's TxFactory
		// https://github.com/cosmos/cosmos-sdk/blob/ff416ee63d32da5d520a8b2d16b00da762416146/client/tx/factory.go#L223
		amt := options.GasPrice.Mul(sdk.NewDec(int64(gas))).Ceil().RoundInt()
```

Cosmos SDK delivers functions like `sdk.NewDecWithPrec()` and similar to define precision for Dec
</blockquote></details>

Done.
___
*[`x/asset/types/ft.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpxal9BlV4o9DSZSrz:-NJ4CKM47b-MwVZt_kBu:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/ft.go#L127)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That logic should be updated once you migrate to `sdk.Dec` so you will be able to use `sdk.Int` and `sdk.Dec` instead of big.*.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-12 08:24 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 4 of 25 files reviewed, 13 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/burn_rate_test.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIpy9aTChiA1RL5Uu-I:-NJ4J17I4SCQAoWFvscm:bb28w0a) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

and also round 0.1 to 1 ? always round up regardless
</blockquote></details>

Got it now. Resolved.
___
*[`x/asset/keeper/burn_rate_test.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0jgP3-cRc9fF5dTy:-NJ4JB-E-_ChHOXkoLQf:bj6nsk9) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L65)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

there a separate task for multi send
</blockquote></details>

Share please a link for it


<!-- Sent from Reviewable.io -->

2022-12-12 10:12 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 4 of 25 files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/burn_rate_test.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq0jgP3-cRc9fF5dTy:-NJ4oSol02rqO_1WTTCp:b2b3ugt) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/burn_rate_test.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Share please a link for it
</blockquote></details>

https://app.clickup.com/t/38g6zxd


<!-- Sent from Reviewable.io -->

2022-12-12 12:34 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 4 of 25 files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-12 12:34 UTC, dzmitryhil approved these changes
> Reviewed 3 of 19 files at r1, 4 of 9 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-12 19:39 UTC, ysv requested changes
> Reviewed 4 of 19 files at r1, 4 of 9 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 21 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/asset/burn_rate.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIq-Ze3-y2BGIiBtiRu:-NJ58peKB4_gYFlXFx_W:btvq5ru) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/asset/burn_rate.go#L53)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

burn rate is not a flag, it was decided in a call with reza to have it as a standalone value. 
</blockquote></details>

no it is not needed 
Milad is right
___
*[`integration-tests/asset/burn_rate.go` line 160 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5sgXx-0EFCg_LNAdK:-NJ5sgXy2M7-oWXmA0Fe:bhcwj13) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/burn_rate.go#L160)):*
> ```Go
> }
> 
> func assertCoinDistribution(ctx context.Context, clientCtx tx.ClientContext, t testing.T, denom string, dist map[*sdk.AccAddress]int64) {
> ```

very smart helper I like that it check everything in a single call

mionor:
another option for name is `assertBalances/assertCoinBalances`
Or you use this because you assert not only balances but also total supply ?
___
*[`integration-tests/asset/burn_rate.go` line 160 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5spAkCL3nE2-fIor4:-NJ5spAkCL3nE2-fIor5:b8mzdt1) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/burn_rate.go#L160)):*
> ```Go
> }
> 
> func assertCoinDistribution(ctx context.Context, clientCtx tx.ClientContext, t testing.T, denom string, dist map[*sdk.AccAddress]int64) {
> ```

why do we need `*sdk.AccAddress` but not `sdk.AccAddress` ?



_Code quote:_
```Go
*sdk.AccAddress
```
___
*[`integration-tests/asset/issue.go` line 40 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ58xsi3yaD8E8DcKTg:-NJ58xsi3yaD8E8DcKTh:b-nprmji) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/issue.go#L40)):*
> ```Go
> 		Recipient:     recipient.String(),
> 		InitialAmount: sdk.NewInt(777),
> 		BurnRate:      sdk.NewDec(0),
> ```

you specified it to be explicitly but in general a default values is 0 am I right ?
___
*[`x/asset/client/cli/tx.go` line 132 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5uEJw1Vn_POQc6haT:-NJ5uEJw1Vn_POQc6haU:b-awhihu) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/client/cli/tx.go#L132)):*
> ```Go
> 			if len(burnRateStr) > 0 {
> 				burnRate, err = sdk.NewDecFromStr(burnRateStr)
> 				if err != nil || len(burnRateStr) > 6 {
> ```

`len(burnRateStr) > 6`

is it the best way to check this ?
I would check `burnRate` as decimal not string
___
*[`x/asset/keeper/burn_rate_test.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5ujSf-uUO_8xRqiTd:-NJ5ujSf-uUO_8xRqiTe:b-vqwh0p) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L19)):*
> ```Go
> 
> func TestKeeperCalculateBurnCoin(t *testing.T) {
> 	testCases := []struct {
> ```

minor:
From the first check I didn't get meaning of fields 
I suggest smth more specific:

```golang
burn_rate string // or maybe you can use sdk.Dec ?
send_amount int64
burn_amount int64
```
___
*[`x/asset/keeper/burn_rate_test.go` line 109 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5v_yJ7Aa6hJAQuxW0:-NJ5v_yJ7Aa6hJAQuxW1:bpig7nl) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L109)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	receiver := sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address())
> ```

as far as I recall we name it recipient in most tests ?
___
*[`x/asset/keeper/burn_rate_test.go` line 122 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5vNB89lPCV3XsW7v1:-NJ5vNB9CpXjtRUL-cN4:bhsaggh) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L122)):*
> ```Go
> 	})
> 
> 	// send from issuer to recipient to another account (burn must apply)
> ```

fix comment
send from recipient1 to recipient2 
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklao29ZqnOBgRHUFB:-NJ5wDYw98ovWlgU9jzr:b249g8x) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I disagree, all logic regarding asset should live in asset module. We just need to rename IsSendAllowed, to InterceptSendCoin 
</blockquote></details>

don't like the way it is strcutured now also
At least burn logic should be moved to a separate func
But final solution might be discussed on a call
___
*[`x/asset/types/ft.go` line 116 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5wbpM24WkGm1IsRq7:-NJ5wbpM24WkGm1IsRq8:b-6p2axf) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/types/ft.go#L116)):*
> ```Go
> 	}
> 
> 	if burnRate.LT(sdk.NewDec(0)) || burnRate.GT(sdk.NewDec(1)) {
> ```

it is not enough
What about validating e.g `0.000000001` here ?

we have to do this here and probably remove this validation on cli step 
___
*[`x/wbank/keeper/keeper.go` line 86 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ6q6Di1mhoBiMMNX5T:-NJ6q6Di1mhoBiMMNX5U:bpstm0j) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/wbank/keeper/keeper.go#L86)):*
> ```Go
> // SendCoins is a BaseKeeper SendCoins wrapped method.
> func (k BaseKeeperWrapper) SendCoins(ctx sdk.Context, fromAddr, toAddr sdk.AccAddress, amt sdk.Coins) error {
> 	if err := k.ftProvider.InterceptSendCoins(ctx, fromAddr, toAddr, amt); err != nil {
> ```

maybe we should redo this in a way similar to hooks in cosmos module ?


<!-- Sent from Reviewable.io -->

2022-12-13 11:48 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 21 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-13 13:21 UTC, wojtek-coreum requested changes
> Reviewed 4 of 9 files at r2, 14 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/asset/issue.go` line 40 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ58xsi3yaD8E8DcKTg:-NJAYwwFBZYSn7vbGYZJ:b-ofem57) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/issue.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you specified it to be explicitly but in general a default values is 0 am I right ?
</blockquote></details>

probably default value contains nil big int internally
___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NJAZf848PFkYfSEV2hf:b-avs6) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But it should be `--burn-rate=0.12`. Now it is used as separator for features
___
*[`x/asset/client/cli/tx.go` line 132 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5uEJw1Vn_POQc6haT:-NJA_4wjAZktRqIQbVlo:b-xx1c3e) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/client/cli/tx.go#L132)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`len(burnRateStr) > 6`

is it the best way to check this ?
I would check `burnRate` as decimal not string
</blockquote></details>

Why 6?
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklao29ZqnOBgRHUFB:-NJA_I8v8cr9VFf6KFHA:bn9ukvj) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

don't like the way it is strcutured now also
At least burn logic should be moved to a separate func
But final solution might be discussed on a call
</blockquote></details>

method with name starting with `Is` should not modify the state, it is counterintuitive. But I see that you renamed it
___
*[`x/asset/keeper/keeper.go` line 33 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAciAb2jVAxz2TJ54O:-NJAciAb2jVAxz2TJ54P:bkxam0a) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/keeper.go#L33)):*
> ```Go
> // InterceptSendCoins checks that a transfer request is allowed or not
> func (k Keeper) InterceptSendCoins(ctx sdk.Context, fromAddress, toAddress sdk.AccAddress, coins sdk.Coins) error {
> 	if err := k.areCoinsSpendable(ctx, fromAddress, coins); err != nil {
> ```

I whitelist PR (it was merged) I redone this logic significantly. Please merge those changes.
___
*[`x/asset/keeper/keeper.go` line 47 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJA_X-HDckSqAF4q1Cx:-NJA_X-JEaBu-MLueIN1:b-1r2wy2) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/keeper.go#L47)):*
> ```Go
> 		}
> 
> 		if !ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String() {
> ```

I think `IsPositive()` already covers `IsNil()`
___
*[`x/asset/keeper/keeper.go` line 77 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAbL9l4qaHrjC1as8_:-NJAbL9m28DNTA8Iu0Bj:b-18okzl) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/keeper.go#L77)):*
> ```Go
> 			}
> 
> 			if !ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != inAddress.String() {
> ```

Same thing about IsNil and IsPositive
___
*[`x/asset/types/ft.go` line 117 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAbcAIB2ToW-kPPg60:-NJAbcAIB2ToW-kPPg61:b-tcao1t) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/types/ft.go#L117)):*
> ```Go
> 
> 	if burnRate.LT(sdk.NewDec(0)) || burnRate.GT(sdk.NewDec(1)) {
> 		return sdkerrors.Wrap(ErrInvalidFungibleToken, "burn rate is not within acceptable range")
> ```

`ErrInvalidFungibleToken` is not the right error type for this
___
*[`x/asset/types/ft.go` line 126 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAbwxtC4qem7mu7Ogf:-NJAbwxu0UwD1Nv-OTrL:b-hxqbu2) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/types/ft.go#L126)):*
> ```Go
> func (ftd FungibleTokenDefinition) CalculateBurnCoin(coin sdk.Coin) sdk.Coin {
> 	// limit precision to 4 decimal places
> 	burnRateStr := fmt.Sprintf("%.4f", ftd.BurnRate)
> ```

ftd.BurnRate is of type sdk.Dec so this kind of conversion won't work. Why isn't it used directly?
___
*[`x/asset/types/errors.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAd5QLDX7ZE2nQaUr6:-NJAd5QM7tcIj_DylL3u:b-6hc1wl) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/types/errors.go#L27)):*
> ```Go
> 	ErrGloballyFrozen = sdkerrors.Register(ModuleName, 9, "token is globally frozen")
> 	// ErrInvalidBurnRate is returned when the provided symbol is not of valid format
> 	ErrInvalidBurnRate = sdkerrors.Register(ModuleName, 10, "burn rate is not valid")
> ```

why is it removed?


<!-- Sent from Reviewable.io -->

2022-12-13 13:50 UTC, dzmitryhil reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-13 13:51 UTC, wojtek-coreum requested changes
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NJAk86K0ya0doioF7YV:b-5cn7av) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But it should be `--burn-rate=0.12`. Now it is used as separator for features
</blockquote></details>

still " --" is missing


<!-- Sent from Reviewable.io -->

2022-12-14 12:51 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 5 of 26 files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/burn_rate.go` line 160 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5sgXx-0EFCg_LNAdK:-NJAVCsD3OvMILNfYYt4:b-995o2z) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/burn_rate.go#L160)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

very smart helper I like that it check everything in a single call

mionor:
another option for name is `assertBalances/assertCoinBalances`
Or you use this because you assert not only balances but also total supply ?
</blockquote></details>

the second sentence is correct, we assert the total distribution of the coin here. 
___
*[`integration-tests/asset/burn_rate.go` line 160 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5spAkCL3nE2-fIor4:-NJAVNof6mjGqBgZKz5v:bupq5ee) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/burn_rate.go#L160)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we need `*sdk.AccAddress` but not `sdk.AccAddress` ?
</blockquote></details>

sdk.AccAddress is []byte which does not implement a method to drive the key for the map (I don't remember the name of the method). but the pointer to it does. The downside of using this approach is that if you have the same address in 2 different objects, they will be represented differently in the map, the upside is that it is much simpler. 
___
*[`integration-tests/asset/issue.go` line 40 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ58xsi3yaD8E8DcKTg:-NJAW9sz6Z-Fdg3S9qvx:b-da93fd) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/issue.go#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

probably default value contains nil big int internally
</blockquote></details>

not exactly, the default value is nil. as wojtek mentioned
___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NJFcubk-c5SfJTn0U9L:b3xj0ku) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

still " --" is missing
</blockquote></details>

wtf, fixed. 
___
*[`x/asset/client/cli/tx.go` line 132 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5uEJw1Vn_POQc6haT:-NJAWGRF9tyWneDKPemX:b-zfwq03) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/client/cli/tx.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why 6?
</blockquote></details>

removed as discssed
___
*[`x/asset/keeper/burn_rate_test.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5ujSf-uUO_8xRqiTd:-NJAWh4QE3e2i8z0Wpa6:bdxxwtn) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
From the first check I didn't get meaning of fields 
I suggest smth more specific:

```golang
burn_rate string // or maybe you can use sdk.Dec ?
send_amount int64
burn_amount int64
```

</blockquote></details>

I can make sdk.Dec types either from string or from float. If I drive it from float there will be some left over values (i.e 0.1 in float is not exactly 0.1 in math), so it is not an option
___
*[`x/asset/keeper/burn_rate_test.go` line 109 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5v_yJ7Aa6hJAQuxW0:-NJAarNc3fF6qI6T7XbV:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L109)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as far as I recall we name it recipient in most tests ?
</blockquote></details>

Done.
___
*[`x/asset/keeper/burn_rate_test.go` line 122 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5vNB89lPCV3XsW7v1:-NJAb2Qs2-holSiGZG1o:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L122)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fix comment
send from recipient1 to recipient2 
</blockquote></details>

Done.
___
*[`x/asset/keeper/keeper.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIklao29ZqnOBgRHUFB:-NJFcWvI03GoJsZoJa_y:b340yyf) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

method with name starting with `Is` should not modify the state, it is counterintuitive. But I see that you renamed it
</blockquote></details>

Fixed and discussed. 
___
*[`x/asset/keeper/keeper.go` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkmU9B5QuaeA0iUm0j:-NJFdXiMBHTnXz5pMEkT:bpt5nx8) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L60)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss on a call
</blockquote></details>

I tried to do it here, but it makes calculating burn rate very complicated. let's postpone this for future, maybe the next PR.
___
*[`x/asset/keeper/keeper.go` line 33 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAciAb2jVAxz2TJ54O:-NJFcHFe9QrRFlX7Jh7q:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/keeper.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I whitelist PR (it was merged) I redone this logic significantly. Please merge those changes.
</blockquote></details>

Done.
___
*[`x/asset/keeper/keeper.go` line 47 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJA_X-HDckSqAF4q1Cx:-NJFcIGDCtViEaNcmwWF:b-yxfciv) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/keeper.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think `IsPositive()` already covers `IsNil()`
</blockquote></details>

no it doesn't. 
___
*[`x/asset/keeper/keeper.go` line 77 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJAbL9l4qaHrjC1as8_:-NJAiPuJ9OffizrLnjD2:b-esu7fr) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/keeper.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Same thing about IsNil and IsPositive
</blockquote></details>

they are both needed.
___
*[`x/asset/types/ft.go` line 116 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5wbpM24WkGm1IsRq7:-NJAglX_5OIakPDGIl3c:b2tm4lw) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/types/ft.go#L116)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it is not enough
What about validating e.g `0.000000001` here ?

we have to do this here and probably remove this validation on cli step 
</bl [...]

2022-12-14 13:08 UTC, ysv requested changes
> Reviewed 11 of 16 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 14 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/asset/issue.go` line 40 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ58xsi3yaD8E8DcKTg:-NJFZBqC6pHjb5UQxlVC:be569uy) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/integration-tests/asset/issue.go#L40)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

not exactly, the default value is nil. as wojtek mentioned
</blockquote></details>

I see
ok for me
___
*[`x/asset/client/cli/tx.go` line 132 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5uEJw1Vn_POQc6haT:-NJFZGioEmnBV61mnOBx:ba4z0uz) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/client/cli/tx.go#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

removed as discssed
</blockquote></details>

yeah it looks magical so I prefer to validate it properly
now it is revmoed so resolving the comment
___
*[`x/asset/client/cli/tx.go` line 134 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFgaEu7XFEoXakBOf8:-NJFgaEu7XFEoXakBOf9:bbbm4iz) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/client/cli/tx.go#L134)):*
> ```Go
> 				burnRate, err = sdk.NewDecFromStr(burnRateStr)
> 				if err != nil {
> 					return errors.Wrapf(err, "burn rate must be a float value between 0 and 1, with max 4 decimal places")
> ```

well I'm not sure it is good to specify details like 4 decimal places here because the actuall validation is done on a different place.
Here it will likely fail because of invalid decimal format or empty string so I think that is what you should show to the user.
And ValidateBasic should handle logic & error for non 0-1 range numbers and more than 4 decimal
___
*[`x/asset/keeper/burn_rate_test.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5ujSf-uUO_8xRqiTd:-NJFjsByEjJ15OXRmpUd:b7xfjux) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I can make sdk.Dec types either from string or from float. If I drive it from float there will be some left over values (i.e 0.1 in float is not exactly 0.1 in math), so it is not an option
</blockquote></details>

ok string is ok for me
what about better names ?
___
*[`x/asset/keeper/burn_rate_test.go` line 24 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFZmBWEGZCfxEEGfOC:-NJFZmBWEGZCfxEEGfOD:b-m3lai7) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e892c6a5f69b159ea4d313c17145fb8649c6274/x/asset/keeper/burn_rate_test.go#L24)):*
> ```Go
> 	}{
> 		{
> 			rate: "0",
> ```

please add a few other cases:
`1.0002`
`1.00023`
`0.12345`
`0.00` not sure if needed

another test case should be smth like this
`0.1 e-18`
`0.1 e-19`
to test what happens if smn uses a numb outide of sdk.Decimal
___
*[`x/asset/keeper/burn_rate_test.go` line 58 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFZhNQ-Am0CH7-qcTi:-NJFZhNQ-Am0CH7-qcTj:b-xcmc89) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e892c6a5f69b159ea4d313c17145fb8649c6274/x/asset/keeper/burn_rate_test.go#L58)):*
> ```Go
> 			assertT := assert.New(t)
> 			rate := sdk.MustNewDecFromStr(tc.rate)
> 			err := types.ValidateBurnRate(rate)
> ```

why do we have this test in keeper if we actually test func from `types` ?
___
*[`x/asset/keeper/burn_rate_test.go` line 85 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFh6qd98cJ1BMblvCJ:-NJFh6qd98cJ1BMblvCK:b-ehdpo5) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/burn_rate_test.go#L85)):*
> ```Go
> 		},
> 		{
> 			rate:     "0.01",
> ```

can you also add a few test cases with some interesting numbers for rate (not only use 10 in some power):
e.g
rate: 1.0
rate: 0.1234
rate: 0.0003
___
*[`x/asset/keeper/keeper.go` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkmU9B5QuaeA0iUm0j:-NJFihc_BaWfhH8TeK0W:bxc67ze) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L60)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I tried to do it here, but it makes calculating burn rate very complicated. let's postpone this for future, maybe the next PR.
</blockquote></details>

do you mean to handle single bankSend & multisend in the same way ?
add todo ?
___
*[`x/asset/keeper/keeper.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFhqvEA6d9EjVuYKDo:-NJFhqvEA6d9EjVuYKDp:b-g4j48s) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/keeper.go#L47)):*
> ```Go
> 			return err
> 		}
> 		if !ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String() {
> ```

I don't like that we have this long if here with all burnRate logic
can we move this to some separate func ?
I like the way it is done for CoinSpendable/Receivable in a single func call we should do the same for burning

abstract:
```
if err : = applyBurnRate(...) {
  return err
}
```

optionaly:
also moving this check to a separate func is a good ideal IMO & we can reuse it in input_otput:

`!ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String()`


<!-- Sent from Reviewable.io -->

2022-12-14 13:47 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: 22 of 26 files reviewed, 14 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/client/cli/tx.go` line 134 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFgaEu7XFEoXakBOf8:-NJFnMGxCT1Thdmm3Mw1:ba3dfob) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/client/cli/tx.go#L134)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well I'm not sure it is good to specify details like 4 decimal places here because the actuall validation is done on a different place.
Here it will likely fail because of invalid decimal format or empty string so I think that is what you should show to the user.
And ValidateBasic should handle logic & error for non 0-1 range numbers and more than 4 decimal
</blockquote></details>

Removed
___
*[`x/asset/keeper/burn_rate_test.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJ5ujSf-uUO_8xRqiTd:-NJFqI1Q76aB5-ou3txl:b9dwwjd) ([raw file](https://github.com/coreumfoundation/coreum/blob/26833511b87bf2fe1d18b46d804f8fb706991191/x/asset/keeper/burn_rate_test.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok string is ok for me
what about better names ?
</blockquote></details>

gotcha, fixed the namings. I agree they were not clear.
___
*[`x/asset/keeper/burn_rate_test.go` line 24 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFZmBWEGZCfxEEGfOC:-NJFpgue7eINU3JUX786:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e892c6a5f69b159ea4d313c17145fb8649c6274/x/asset/keeper/burn_rate_test.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

please add a few other cases:
`1.0002`
`1.00023`
`0.12345`
`0.00` not sure if needed

another test case should be smth like this
`0.1 e-18`
`0.1 e-19`
to test what happens if smn uses a numb outide of sdk.Decimal
</blockquote></details>

Done.
___
*[`x/asset/keeper/burn_rate_test.go` line 58 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFZhNQ-Am0CH7-qcTi:-NJFpwc74W0K463YVV2-:b-ctf0cb) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e892c6a5f69b159ea4d313c17145fb8649c6274/x/asset/keeper/burn_rate_test.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we have this test in keeper if we actually test func from `types` ?
</blockquote></details>

that is a good point, moved to types package.
___
*[`x/asset/keeper/burn_rate_test.go` line 85 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFh6qd98cJ1BMblvCJ:-NJFrOrU8VQ5YTmoD9sD:b-lw3j1f) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/burn_rate_test.go#L85)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you also add a few test cases with some interesting numbers for rate (not only use 10 in some power):
e.g
rate: 1.0
rate: 0.1234
rate: 0.0003
</blockquote></details>

added more cases
___
*[`x/asset/keeper/keeper.go` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkmU9B5QuaeA0iUm0j:-NJFs8iu-fl0m0zJL969:b-7xcabw) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/keeper/keeper.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you mean to handle single bankSend & multisend in the same way ?
add todo ?
</blockquote></details>

Yes
I will add TODO
___
*[`x/asset/keeper/keeper.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFhqvEA6d9EjVuYKDo:-NJFr_02DD98UmlKxRDw:bhg6p0o) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/keeper.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like that we have this long if here with all burnRate logic
can we move this to some separate func ?
I like the way it is done for CoinSpendable/Receivable in a single func call we should do the same for burning

abstract:
```
if err : = applyBurnRate(...) {
  return err
}
```

optionaly:
also moving this check to a separate func is a good ideal IMO & we can reuse it in input_otput:

`!ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String()`
</blockquote></details>

i tried that but the logic is not really reusable between send and send many so will end up having 2 of such functions which is even uglier. I think we might be able to abstract and reuse that logic once we pin down the correct implementation for send many as well. 


<!-- Sent from Reviewable.io -->

2022-12-14 22:29 UTC, ysv requested changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/keeper/keeper.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFhqvEA6d9EjVuYKDo:-NJGvHOi0GmTST_LwAao:b-3ok775) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/keeper.go#L47)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

i tried that but the logic is not really reusable between send and send many so will end up having 2 of such functions which is even uglier. I think we might be able to abstract and reuse that logic once we pin down the correct implementation for send many as well. 
</blockquote></details>

okay
I actually don't mind if `applyBurnRate` handles only single send functionality
I at least don't like to have this long & burn logic specific if `!ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String()` in high level func 
___
*[`x/asset/types/ft_test.go` line 189 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJGxpQCD2UB-1DEZBDl:-NJGxpQCD2UB-1DEZBDm:bidkbkr) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/ft_test.go#L189)):*
> ```Go
> 		},
> 		{
> 			rate:    "0.0000000000000000001",
> ```

so this case fails on this step I guess ?
`sdk.NewDecFromStr(in)`

while all other on `types.ValidateBurnRate(rate)`
___
*[`x/asset/types/ft_test.go` line 200 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJHk1ug3Ftu0FCh1Hy8:-NJHk1ug3Ftu0FCh1Hy9:b6qk22x) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/ft_test.go#L200)):*
> ```Go
> 		}
> 
> 		err = types.ValidateBurnRate(rate)
> ```

non-blocking:
I probably have a stupid question or skip smth but I can't get why we need to import types to call this func if it is within the same pkg ?
Why just `err  = ValidateBurnRate(rate)` doesn't work


<!-- Sent from Reviewable.io -->

2022-12-15 07:44 UTC, wojtek-coreum requested changes
> Reviewed 1 of 17 files at r3, 9 of 16 files at r5, 8 of 12 files at r6, 2 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NJJhWh44OXvogmCxJ7C:b-h7a2xb) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

wtf, fixed. 
</blockquote></details>

and space before "--" :D
___
*[`x/asset/client/cli/tx.go` line 134 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJhhI1-hIFUjIM87DF:-NJJhhI1-hIFUjIM87DG:bwv92g2) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/client/cli/tx.go#L134)):*
> ```Go
> 				burnRate, err = sdk.NewDecFromStr(burnRateStr)
> 				if err != nil {
> 					return errors.Wrapf(err, "invalid burn_rate")
> ```

burn_rate -> burn rate, as this is presented to the user
___
*[`x/asset/keeper/keeper.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFhqvEA6d9EjVuYKDo:-NJJiMsy0sQwMMky6O1o:box2dzp) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/keeper.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

okay
I actually don't mind if `applyBurnRate` handles only single send functionality
I at least don't like to have this long & burn logic specific if `!ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String()` in high level func 
</blockquote></details>

I would move this entire piece to `k.burnFungibleToken`



_Code quote:_
```Go
k.burnFungibleToken
```
___
*[`x/asset/types/errors.go` line 13 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJiq6f9uujcvGQRZbm:-NJJiq6gDuFNJ8MBfjVn:blix466) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/errors.go#L13)):*
> ```Go
> 	ErrFungibleTokenNotFound = sdkerrors.Register(ModuleName, 2, "fungible token not found")
> 	// ErrFeatureNotActive is returned when an operation is performed on a token which is missing a required feature
> 	ErrFeatureNotActive = sdkerrors.Register(ModuleName, 3, "token feature is not active")
> ```

Minor: Do we want to recalculate numbers or we don't care?
___
*[`integration-tests/index.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJjQQED02fhq3ThTTd:-NJJjQQED02fhq3ThTTe:bxjr7oo) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/index.go#L35)):*
> ```Go
> 				asset.TestFreezeUnfreezableFungibleToken,
> 				asset.TestGloballyFreezeFungibleToken,
> 				asset.TestBurnRateFungibleToken,
> ```

What happened to this test?


<!-- Sent from Reviewable.io -->

2022-12-15 08:18 UTC, wojtek-coreum requested changes
> Reviewed 1 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/asset/burn_rate.go` line 27 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJphvmEtKlMQ6w60tF:-NJJphvn38vN_3MN779G:b-cqkbhd) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L27)):*
> ```Go
> 			Messages: []sdk.Msg{
> 				&assettypes.MsgIssueFungibleToken{},
> 				&assettypes.MsgIssueFungibleToken{},
> ```

Test issues only one ft
___
*[`integration-tests/asset/burn_rate.go` line 34 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJq4ffEburF7NnoeS2:-NJJq4fg-lKWPJcqiX_y:bm5refb) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L34)):*
> ```Go
> 			Messages: []sdk.Msg{
> 				&banktypes.MsgSend{},
> 				&banktypes.MsgSend{},
> ```

second time recipient1 uses multi send
___
*[`integration-tests/asset/burn_rate.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJqaeW7zsjF1qtzGYC:-NJJqaeW7zsjF1qtzGYD:b13rcxs) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L128)):*
> ```Go
> 
> 	// multi send from recipient1 to issuer and recipient2
> 	// (burn must apply to both transfers. will be fixed later to apply to one transfer)
> ```

IMO it should be fixed in this PR
___
*[`integration-tests/asset/burn_rate.go` line 174 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJr-pO4Uj8HP0eAjR8:-NJJr-pO4Uj8HP0eAjR9:b-rp5qn9) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L174)):*
> ```Go
> 	supply, err := bankClient.SupplyOf(ctx, &banktypes.QuerySupplyOfRequest{Denom: denom})
> 	requireT.NoError(err)
> 	requireT.EqualValues(sdk.NewCoin(denom, sdk.NewInt(total)).String(), supply.Amount.String())
> ```

This won't work, because you don't consider burned portion which was sent to the module. So you should define expected remaining part somehow in addition to the list of accounts, or add address of the module to the list probably.


<!-- Sent from Reviewable.io -->

2022-12-15 08:23 UTC, wojtek-coreum requested changes
> Reviewed 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/keeper/burn_rate_test.go` line 24 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJrTHY83Bg6S9rmt8q:-NJJrTHY83Bg6S9rmt8r:blqvvci) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/keeper/burn_rate_test.go#L24)):*
> ```Go
> 		burnAmount int64
> 	}{
> 		{
> ```

please add a case when sendAmount = 0
___
*[`x/asset/keeper/burn_rate_test.go` line 167 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJs1VKAjYvsgn_zfEJ:-NJJs1VKAjYvsgn_zfEK:b-s493jm) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/keeper/burn_rate_test.go#L167)):*
> ```Go
> }
> 
> type bankAssertion struct {
> ```

why not a function like in integration test? And I think we could share this helper between both test types
___
*[`x/asset/types/ft_test.go` line 200 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJHk1ug3Ftu0FCh1Hy8:-NJJsNBn0Sv-ksmDK5Xw:bpt5a5w) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/ft_test.go#L200)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

non-blocking:
I probably have a stupid question or skip smth but I can't get why we need to import types to call this func if it is within the same pkg ?
Why just `err  = ValidateBurnRate(rate)` doesn't work
</blockquote></details>

because package on top of test file is `types_test`, not `types`


<!-- Sent from Reviewable.io -->

2022-12-15 09:04 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/errors.go` line 13 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJiq6f9uujcvGQRZbm:-NJK0inn4xCm1rbQXOyI:b-ms1nl0) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/errors.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: Do we want to recalculate numbers or we don't care?
</blockquote></details>

Right we need to do it


<!-- Sent from Reviewable.io -->

2022-12-15 09:10 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/asset/burn_rate.go` line 27 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJphvmEtKlMQ6w60tF:-NJK26juBzU8IFJ6nGLz:bt2vr1b) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Test issues only one ft
</blockquote></details>

Fixed.
___
*[`integration-tests/asset/burn_rate.go` line 34 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJq4ffEburF7NnoeS2:-NJJyAkg8t42-OLolUTc:bu9rla1) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

second time recipient1 uses multi send
</blockquote></details>

removed this one, funding for the multisend happens next to broadcast.
___
*[`integration-tests/asset/burn_rate.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJqaeW7zsjF1qtzGYC:-NJJyLhP8jIdMKXKhA8F:bosus0l) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO it should be fixed in this PR
</blockquote></details>

there is a different task for it. but we can discuss it in the daily if you insist
___
*[`integration-tests/asset/burn_rate.go` line 174 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJr-pO4Uj8HP0eAjR8:-NJJynDI1nufHI8cn1N1:bydrddp) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L174)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This won't work, because you don't consider burned portion which was sent to the module. So you should define expected remaining part somehow in addition to the list of accounts, or add address of the module to the list probably.
</blockquote></details>

we don't send to the module and keep it there, we send it there and burn it, so it does not exist anymore. 
___
*[`x/asset/client/cli/tx.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NIkkMCd7YDSEt3kyRxv:-NJK-Kdp0QJfVGKUwZN6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/x/asset/client/cli/tx.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

and space before "--" :D
</blockquote></details>

Done.
___
*[`x/asset/client/cli/tx.go` line 134 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJhhI1-hIFUjIM87DF:-NJK-Qft6zm1DOeZYLfF:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/client/cli/tx.go#L134)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

burn_rate -> burn rate, as this is presented to the user
</blockquote></details>

Done.
___
*[`x/asset/keeper/burn_rate_test.go` line 24 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJrTHY83Bg6S9rmt8q:-NJK-fDx9zw0rkP6E4Dw:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/keeper/burn_rate_test.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please add a case when sendAmount = 0
</blockquote></details>

Done.
___
*[`x/asset/keeper/burn_rate_test.go` line 167 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJs1VKAjYvsgn_zfEJ:-NJK-lm35BuHOOjAT-xb:b-2wgg0v) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/keeper/burn_rate_test.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why not a function like in integration test? And I think we could share this helper between both test types
</blockquote></details>

if we make it a function we need to pass 3 more parameters on every call. 
we cannot easily merge them it since one of them is using keeprs to collect info and the other one is using grpc clients.
___
*[`x/asset/keeper/keeper.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFhqvEA6d9EjVuYKDo:-NJK10HT0-iqXTj_6w6i:bv9gz3t) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/keeper.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would move this entire piece to `k.burnFungibleToken`
</blockquote></details>

@ysv Done
@wojtek-coreum I don't think that is the best place to put it, I think burn fungible token should be limited to getting a coin and simply burning it. 
___
*[`x/asset/types/ft_test.go` line 189 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJGxpQCD2UB-1DEZBDl:-NJK1QQmBCBEX4-zXyrH:b5pzz20) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/ft_test.go#L189)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so this case fails on this step I guess ?
`sdk.NewDecFromStr(in)`

while all other on `types.ValidateBurnRate(rate)`
</blockquote></details>

that is correct 
___
*[`x/asset/types/ft_test.go` line 200 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJHk1ug3Ftu0FCh1Hy8:-NJK1_Ro9L7kGyFlI0_u:b-f70gws) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/ft_test.go#L200)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

because package on top of test file is `types_test`, not `types`
</blockquote></details>

wojtek is on point. 
___
*[`integration-tests/index.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJjQQED02fhq3ThTTd:-NJK1p5q66Fi2kHLGKWS:b-vp73h0) ([raw file](https://github.com/coreumfoundation/coreum/blob/445cb0dc5aa3559f9761d05f93113a85aa659895/integration-tests/index.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What happened to this test?
</blockquote></details>

conflict resolution problem. re-added



_Code quote:_
```Go
asset.TestBurnRateFungibleToken
```


<!-- Sent from Reviewable.io -->

2022-12-15 11:25 UTC, ysv requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/asset/burn_rate.go` line 128 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJJqaeW7zsjF1qtzGYC:-NJKVqRO4xiOoveQ5Jfb:bo50dl2) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/integration-tests/asset/burn_rate.go#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

there is a different task for it. but we can discuss it in the daily if you insist
</blockquote></details>

but we have a separate task to do this because it has  complex logic which we didn't observe when starting this task so it wasn't included in the estimation
___
*[`x/asset/keeper/keeper.go` line 47 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJFhqvEA6d9EjVuYKDo:-NJKVbUhA55WxoqosYF5:b-puifih) ([raw file](https://github.com/coreumfoundation/coreum/blob/eeccc738c301bc54b8db4a7cc4f3219957162a3a/x/asset/keeper/keeper.go#L47)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv Done
@wojtek-coreum I don't think that is the best place to put it, I think burn fungible token should be limited to getting a coin and simply burning it. 
</blockquote></details>

but I don't see this if logic in applyBurnRate now

`!ft.BurnRate.IsNil() && ft.BurnRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String()`
___
*[`x/asset/types/ft_test.go` line 200 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/284#-NJHk1ug3Ftu0FCh1Hy8:-NJKWREy87JTXdrX2zLY:bamepp4) ([raw file](https://github.com/coreumfoundation/coreum/blob/2aba908dc67b1e1c8c4d858dbfd3bfd352407fdd/x/asset/types/ft_test.go#L200)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

wojtek is on point. 
</blockquote></details>

I see
I skipped this


<!-- Sent from Reviewable.io -->

2022-12-15 12:08 UTC, wojtek-coreum approved these changes
> Reviewed 5 of 6 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/284)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-12-15 13:16 UTC, merged