POC for the integration tests with the default testing framework
CoreumFoundation/coreum pull request #285
Opened 2022-12-08 05:36 UTC by dzmitryhil

2022-12-08 07:48 UTC, wojtek-coreum requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgtclAlS8xLPe2IkV:-NIkgtclAlS8xLPe2IkW:bnc15y1) (no related file):*
I have to say that it is much better than I initially thought it might be.
Let's try to fix inconvenience with running upgrade test separately.

___
___
*[`integration-tests/index.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkenrn2aB9nACrm2Cw:-NIkenrn2aB9nACrm2Cx:b-9crxi4) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L46)):*
> ```Go
> 
> // Command to run the integration tests: go test -v --tags=integration -parallel 5 ./... --log-format=yaml
> func init() {
> ```

why not using `TestMain`?
___
*[`integration-tests/index.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkf74kAWxJT6y6VhIQ:-NIkf74kAWxJT6y6VhIR:b-e9wy4q) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L101)):*
> ```Go
> 	t.Cleanup(cancel)
> 
> 	return ctx, chain
> ```

Maybe we could have our `ctx` object which extends `context.Context` and provided additional methods?
Or maybe we should store `chain` inside `ctx`?
___
*[`integration-tests/upgrade/upgrade.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkfjMFBFOPPzD7z9SY:-NIkfjMGDLL1w1yQGGN2:bzeem9l) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/upgrade/upgrade.go#L1)):*
> ```Go
> //go:build integration_upgrade
> ```

This means that we will have to compile two test binaries. One for `integration` tag, second for `integration_upgrade` to be able to run upgrade test separately. Is there any better way of saying that this test should b executed first, before others?
___
*[`integration-tests/bank/send_test.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgZFk9wA1pilxP7Dp:-NIkgZFk9wA1pilxP7Dq:b-k925v2) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/send_test.go#L27)):*
> ```Go
> 	t.Parallel()
> 
> 	// FIXME(dhil) Additionally we can rename integration-tests -> integration-tests
> ```

I don't understand "integration-tests -> integration-tests" part because both sides are identical
___
*[`integration-tests/bank/send_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgfzY7WlCAOkIxGfu:-NIkgfzY7WlCAOkIxGfv:b-n741e4) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/send_test.go#L28)):*
> ```Go
> 
> 	// FIXME(dhil) Additionally we can rename integration-tests -> integration-tests
> 	// and move integration-tests/testing to integration-tests root  to simplify the imports
> ```

The idea is that stuff in `integration-tests/testing` is potentially reusable for integration tests in other repos, and eventually moved to a common one.


<!-- Sent from Reviewable.io -->

2022-12-08 12:39 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgtclAlS8xLPe2IkV:-NIljoz7AiXHEJEeDWtD:bb74ce2) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I have to say that it is much better than I initially thought it might be.
Let's try to fix inconvenience with running upgrade test separately.
</blockquote></details>

Sure

___
___
*[`integration-tests/index.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkenrn2aB9nACrm2Cw:-NIliQmI7A2FacDq7nZy:b-4ljurg) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why not using `TestMain`?
</blockquote></details>

 TestMain is just one big test, here we don't run the tests so they can be launched separately. 
___
*[`integration-tests/index.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkf74kAWxJT6y6VhIQ:-NIlimB054lG_dSwVDkN:bi7zihk) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L101)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe we could have our `ctx` object which extends `context.Context` and provided additional methods?
Or maybe we should store `chain` inside `ctx`?
</blockquote></details>

Not sure, I would even perefer to remove the logger form that context :-) But it's already used. Also the chain is used in all tests, so it make not sense to put
___
*[`integration-tests/upgrade/upgrade.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkfjMFBFOPPzD7z9SY:-NIliJ243tsvnu3M9vXL:b-t93vjb) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/upgrade/upgrade.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This means that we will have to compile two test binaries. One for `integration` tag, second for `integration_upgrade` to be able to run upgrade test separately. Is there any better way of saying that this test should b executed first, before others?
</blockquote></details>

We won't use the binaries at all, we will use the default `go test` command. 
___
*[`integration-tests/bank/send_test.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgZFk9wA1pilxP7Dp:-NIlhs13A4FxT_3K2UJN:bo57u15) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/send_test.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand "integration-tests -> integration-tests" part because both sides are identical
</blockquote></details>

Oh :-) integration-tests -> integration
___
*[`integration-tests/bank/send_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgfzY7WlCAOkIxGfu:-NIliCRM5sPQHXwpkj-k:btej6j) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/send_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The idea is that stuff in `integration-tests/testing` is potentially reusable for integration tests in other repos, and eventually moved to a common one.
</blockquote></details>

Right, but the imports looks confusing becasue of that


<!-- Sent from Reviewable.io -->

2022-12-09 10:54 UTC, miladz68 requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqW4BP7FBQOfGOwh9m:-NIqW4BP7FBQOfGOwh9n:b-g7edx9) (no related file):*
It looks good, but I have a question/suggestion
have we considered using this
```
github.com/stretchr/testify/suite
```

___
___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NIqTziHDJ1jbmQrdnBN:bk8l3jf) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
> ```Go
> 
> // stringsFlag allows setting a value multiple times to collect a list, as in -I=val1 -I=val2.
> type stringsFlag []string
> ```

non-blocking
maybe we can use pflag, then we will not need this code ? since we are using pflag everywhere else, then it sounds like a good idea. 
I think I remember something about go tests using std flags to provide some values, but that is ok, since we can wrap std flags into pflag with `flag.CommandLine.AddGoFlagSet(goflag.CommandLine)`
___
*[`integration-tests/index.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkenrn2aB9nACrm2Cw:-NIqRdmv11RpyYqMIA4G:bypka52) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

 TestMain is just one big test, here we don't run the tests so they can be launched separately. 
</blockquote></details>

But they can still be launched separately if we use TestMain


<!-- Sent from Reviewable.io -->

2022-12-09 15:08 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqW4BP7FBQOfGOwh9m:-NIrPdq0AKV3BdkrNMlV:bnjgvpf) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It looks good, but I have a question/suggestion
have we considered using this
```
github.com/stretchr/testify/suite
```
</blockquote></details>

As I explaind it will lead to more code.

___
___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NIrPoZz0GFIMCB6PoHZ:b-lugjn8) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
maybe we can use pflag, then we will not need this code ? since we are using pflag everywhere else, then it sounds like a good idea. 
I think I remember something about go tests using std flags to provide some values, but that is ok, since we can wrap std flags into pflag with `flag.CommandLine.AddGoFlagSet(goflag.CommandLine)`
</blockquote></details>

Actually we can but as @wojtek-coreum mentioned it tean decided to go with that flag lib.
___
*[`integration-tests/index.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkenrn2aB9nACrm2Cw:-NIrQUP2Ba8r_3QkVAHB:bk8eoib) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L46)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

But they can still be launched separately if we use TestMain
</blockquote></details>

We don't need the TestMain  at all.


<!-- Sent from Reviewable.io -->

2022-12-12 10:47 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 7 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NJ4vzqO8opzcbaCJGT1:b-bxyn8i) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually we can but as @wojtek-coreum mentioned it tean decided to go with that flag lib.
</blockquote></details>

Feel free to resolve this since this is non-blocking
But as far as I remember we (in a team discussion) decided to go with pflag, at least that is what we have done in faucet repo


<!-- Sent from Reviewable.io -->

2022-12-12 10:47 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 7 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NJ4wX8X3A-XgCEdUMYP:bhkcq9i) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Feel free to resolve this since this is non-blocking
But as far as I remember we (in a team discussion) decided to go with pflag, at least that is what we have done in faucet repo
</blockquote></details>

let's review that decision quickly in the daily 


<!-- Sent from Reviewable.io -->

2022-12-12 11:38 UTC, ysv requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgtclAlS8xLPe2IkV:-NIr5ivT9O1sdnlsy84B:byqxr7k) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

I also like this approach more than what we had before

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ575zyDc7toIyUVGnl:-NJ575zyDc7toIyUVGnm:bnbzk5i) (no related file):*
are there a log of changes required on crust side to make it work ?

___
___
*[`integration-tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ56QwU88k2Dij68eAu:-NJ56QwU88k2Dij68eAv:b-ibjkaj) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L1)):*
> ```Go
> //go:build integration
> ```

probably file should be renamed now since it is not index anymore ?
smth like `tests.go` or `test_main.go` 
___
*[`integration-tests/index.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ55sRZDcmFoW4xQW8O:-NJ55sRZDcmFoW4xQW8P:bwpvz6g) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L92)):*
> ```Go
> 
> // NewTestingContext returns the configured chain and new context for the integration tests.
> func NewTestingContext(t *testing.T) (context.Context, coreumtesting.Chain) {
> ```

it would be nice to move this helper func to `testing`

Because then we would need to import only `integration-tests/testing` everywhere and index.go should contain only test initialization. Because currently everything depends on everything

I understand that you use & initialize global variable `chain` here and that is the problem but maybe there is a way 
___
*[`integration-tests/index.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkf74kAWxJT6y6VhIQ:-NJ53zbM7sFEpvJqFjyI:bgbdiiv) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L101)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure, I would even perefer to remove the logger form that context :-) But it's already used. Also the chain is used in all tests, so it make not sense to put
</blockquote></details>

I agree with Wojtek that ideomatic way would be to store logger & chain in context and then fetch them from `ctx` in this func
But I don't see a way to achieve this nicely in testing pkg provided by go so I'm not sure
___
*[`integration-tests/bank/gas_test.go` line 234 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIr2yt14q6GUEGDLcWE:-NIr2yt14q6GUEGDLcWF:bstn5fb) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/gas_test.go#L234)):*
> ```Go
> // TestMultiSendDeterministicGasManyCoins checks that transfer takes the higher deterministic amount of gas when more coins are transferred
> func TestMultiSendDeterministicGasManyCoins(t *testing.T) {
> 	t.Parallel()
> ```

minor:
is there a way to make them `Parallel` by default ?

On the other hand it is nice that we can define this per tests because then we should be able to run some tests not in parallel E.g I would make `TestValidatorCRUDAndStaking` non-parallel since it changes some params and then reverts them


<!-- Sent from Reviewable.io -->

2022-12-12 11:44 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`integration-tests/index.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkf74kAWxJT6y6VhIQ:-NJ58dZS7EN_AzFojT3L:b-dekeb1) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L101)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Wojtek that ideomatic way would be to store logger & chain in context and then fetch them from `ctx` in this func
But I don't see a way to achieve this nicely in testing pkg provided by go so I'm not sure
</blockquote></details>

I actually thought that we can pass ctx inside testing.T but seems that it is not possible


<!-- Sent from Reviewable.io -->

2022-12-12 12:33 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgtclAlS8xLPe2IkV:-NJ5JnL0AlEIA6j0s0YW:bmyrv97) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also like this approach more than what we had before
</blockquote></details>

Cools :-)

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ575zyDc7toIyUVGnl:-NJ5F-TK-hu0kpDBSG1O:b-xe1fdu) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

are there a log of changes required on crust side to make it work ?
</blockquote></details>

Nope, it's similar to what we do now for normal tests, example is in the code
```bash
go test -v --tags=integration -parallel 5 ./... --log-format=yaml
```

___
___
*[`integration-tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ56QwU88k2Dij68eAu:-NJ5FM4e-bb7RI-ZQYdl:b7a6yu4) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

probably file should be renamed now since it is not index anymore ?
smth like `tests.go` or `test_main.go` 
</blockquote></details>

That should work I guess. 
___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NJ5FUyK405V78AtIpIm:b-r537u) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's review that decision quickly in the daily 
</blockquote></details>

Actually we can include it to the full implementation since it's a POC.
___
*[`integration-tests/index.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ55sRZDcmFoW4xQW8O:-NJ5F__jAjOCXFgHTus9:b-gmzlbt) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it would be nice to move this helper func to `testing`

Because then we would need to import only `integration-tests/testing` everywhere and index.go should contain only test initialization. Because currently everything depends on everything

I understand that you use & initialize global variable `chain` here and that is the problem but maybe there is a way 
</blockquote></details>

I would move all form testing to the root :-)
___
*[`integration-tests/index.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkf74kAWxJT6y6VhIQ:-NJ5Fe-k6hyc1CXA7XdP:b-81la7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L101)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I actually thought that we can pass ctx inside testing.T but seems that it is not possible
</blockquote></details>

Right
___
*[`integration-tests/bank/gas_test.go` line 234 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIr2yt14q6GUEGDLcWE:-NJ5JSja9E7_vXlExXxw:b-p5l292) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/gas_test.go#L234)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
is there a way to make them `Parallel` by default ?

On the other hand it is nice that we can define this per tests because then we should be able to run some tests not in parallel E.g I would make `TestValidatorCRUDAndStaking` non-parallel since it changes some params and then reverts them

</blockquote></details>

Sure, check the command I presented in the first comment. It's a usual unit test so all features are supported. 


<!-- Sent from Reviewable.io -->

2022-12-13 12:30 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NJAS-nVAsi-TCy8pHAk:b-mhiv3d) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually we can include it to the full implementation since it's a POC.
</blockquote></details>

The problem was that `go test` uses `flag` package
___
*[`integration-tests/index.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkenrn2aB9nACrm2Cw:-NJAS7g8CqgJMfZLZKrN:bvpcjwj) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We don't need the TestMain  at all.
</blockquote></details>

TestMain is not a test, it's a `main`-like function for `go test`. I don't care much so I'm resolving this
___
*[`integration-tests/upgrade/upgrade.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkfjMFBFOPPzD7z9SY:-NJASirYDFu3L9LLxQZ0:bdhpb9w) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/upgrade/upgrade.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We won't use the binaries at all, we will use the default `go test` command. 
</blockquote></details>

The original idea was to not compile anything in `znet`


<!-- Sent from Reviewable.io -->

2022-12-13 13:50 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NJAjxixAO4Xls7Is5zu:b-p3svoi) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The problem was that `go test` uses `flag` package
</blockquote></details>

Oh, so we probably need to keep it, not mix them up. 
___
*[`integration-tests/upgrade/upgrade.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkfjMFBFOPPzD7z9SY:-NJAjnoL-C3d268AYUJE:b-h7lx78) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/upgrade/upgrade.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The original idea was to not compile anything in `znet`
</blockquote></details>

Got you, but we already run the tests that way from the `crust` I don't see a big different with that tests.


<!-- Sent from Reviewable.io -->

2022-12-13 14:14 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ575zyDc7toIyUVGnl:-NJAmmn15sbQgHuJg5VN:b-81la7d) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so this is the only change ?
we just need to change `crust znet test` command as far as I got


</blockquote></details>

Right

___
___
*[`integration-tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ56QwU88k2Dij68eAu:-NJAmq4g1qf4ZZfam57m:brmc2la) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls rename it accordingly then )
</blockquote></details>

Hm... Technically I see now that it's not the `test_main.go` it's index to read the CLI. So I like `intex.go` more.
___
*[`integration-tests/index.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ55sRZDcmFoW4xQW8O:-NJAo8ZJEckVDMAxS4f1:bggbpdl) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we should also decide on `testing` folder on this PR also so there are no unclear parts left

I probably prefer to have it in ./integration-tests/testing but ./integration-tests/ is also ok for me.
If I'm not mistaken the idea was to have ./integration-tests/testing separately so other projects could import it. IDK if it is still applicable.

By the way testing/types.go is not needed anymore

@wojtek-coreum @miladz68 WDYT we should do with testing ?
</blockquote></details>

But, first no one use it, second what is the problem to use the `integration-tests` directly?
___
*[`integration-tests/index.go` line 101 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkf74kAWxJT6y6VhIQ:-NJAoNlWBOVLr_NX5i7M:brw6rl6) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L101)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not ideal but ok for me to keep it as it is now
but @wojtek-coreum if you have any better idea for this we can discuss 
</blockquote></details>

I don't :-)  
___
*[`integration-tests/upgrade/upgrade.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkfjMFBFOPPzD7z9SY:-NJAohDt-Wp0sXWre64a:beldecn) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/upgrade/upgrade.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but if we can run it using `crust znet test` and remove `crust build/integration` I don't mind actually 
Or there is a problem to do this ?
Maybe there is because we should compile it in docker but I don't remember actually 
</blockquote></details>

That's exactly what we will do.
___
*[`integration-tests/bank/gas_test.go` line 234 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIr2yt14q6GUEGDLcWE:-NJAoUV03xMPqWOxfSC-:b31ob8p) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/gas_test.go#L234)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
can you please add todo to disable parallel in `TestValidatorCRUDAndStaking` so we don't forget it ?
</blockquote></details>

Why do we need it ? We already have the protection on the chain level. So it will be executed in parallel and will be blocked on the voting. 


<!-- Sent from Reviewable.io -->

2022-12-14 12:55 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ56QwU88k2Dij68eAu:-NJB4_W_3yWZqH5mI7av:b-dzcgx9) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Hm... Technically I see now that it's not the `test_main.go` it's index to read the CLI. So I like `intex.go` more.
</blockquote></details>

We decided to call it `init.go`
___
*[`integration-tests/index.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIqTziHDJ1jbmQrdnBM:-NJB50KZCSTnCnIaA-oH:b-e652zv) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Oh, so we probably need to keep it, not mix them up. 
</blockquote></details>

If it's possible we should use the pflag
___
*[`integration-tests/index.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ55sRZDcmFoW4xQW8O:-NJB5tjQB57kkXzMQmLb:b-twvqdq) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L92)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But, first no one use it, second what is the problem to use the `integration-tests` directly?
</blockquote></details>

We decided to rename `integration-tests` -> `integration` and move all form `testing` to it.
___
*[`integration-tests/bank/gas_test.go` line 234 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIr2yt14q6GUEGDLcWE:-NJB7oEp3Uy8x0KEteyn:b-41odcw) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/gas_test.go#L234)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need it ? We already have the protection on the chain level. So it will be executed in parallel and will be blocked on the voting. 
</blockquote></details>

We decided to go with the parallel for that test


<!-- Sent from Reviewable.io -->

2022-12-14 13:16 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ56QwU88k2Dij68eAu:-NJFldCe4uQEUiYTxr8o:b-tyopqj) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We decided to call it `init.go`
</blockquote></details>

but lets rename it here then ?
___
*[`integration-tests/index.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ55sRZDcmFoW4xQW8O:-NJFli4D3a8GHUJtRtDv:bbevcfg) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L92)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We decided to rename `integration-tests` -> `integration` and move all form `testing` to it.
</blockquote></details>

will you do this in current PR ?


<!-- Sent from Reviewable.io -->

2022-12-14 13:40 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ56QwU88k2Dij68eAu:-NJFr5Qr4AIqGM5g7kp0:brureoq) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but lets rename it here then ?
</blockquote></details>

It's renamed in the implemetation (finalisation)
___
*[`integration-tests/index.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NJ55sRZDcmFoW4xQW8O:-NJFrA9e-8v5cfQ5mKQy:b7fag84) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/index.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

will you do this in current PR ?
</blockquote></details>

Nope in new.


<!-- Sent from Reviewable.io -->

2022-12-14 22:30 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-15 08:08 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/285)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/upgrade/upgrade.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkfjMFBFOPPzD7z9SY:-NJJoW2u6SEv-6Jk7ZkS:b-rfaprr) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/upgrade/upgrade.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> The original idea was to not compile anything in znet

why did we decide to not do this ?
I'm waiting for @wojtek-coreum to continue discussion on this
</blockquote></details>

The idea was that building of everything is handled by crust, and znet only executes stuff. Let's say that I have integration tests but implementation doesn't work. So I must fix cored and run `znet test` many times. If znet builds tests every time it is slower.
___
*[`integration-tests/bank/send_test.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/285#-NIkgZFk9wA1pilxP7Dp:-NJJoMaW2Su_I8ody8Kw:b-bh19yr) ([raw file](https://github.com/coreumfoundation/coreum/blob/331bacc0e57bca5c4b48739a9de5566881fe6207/integration-tests/bank/send_test.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Oh :-) integration-tests -> integration
</blockquote></details>

so please fix it


<!-- Sent from Reviewable.io -->

2022-12-15 09:00 UTC, closed without merging