Split ft and nft into separate modules
CoreumFoundation/coreum pull request #300
Opened 2022-12-16 16:24 UTC by wojtek-coreum

2022-12-16 16:25 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 0 of 85 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJQkN1KBUY2wHfMaQDE:-NJQkN1L7EU3fNLEHw7z:bcaemho) (no related file):*
I recommend to do it commit by commit

___


<!-- Sent from Reviewable.io -->

2022-12-19 12:19 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 0 of 85 files reviewed, 10 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeCf0oCS4rVA5CnsnB:-NJeCf0oCS4rVA5CnsnC:b-9bxt2c) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/pkg/config/deterministic_gas.go#L31)):*
> ```Go
> 		AssetFTGloballyUnfreeze:    5000,
> 		AssetFTSetWhitelistedLimit: 35000,
> 		AssetNFTIssueClass:         20000,
> ```

Extra line is needed here
___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJeITJ6DywpqyjlWuGn:b-p9rs22) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
> ```Go
> }
> 
> // NewAppModuleBasic return the asset AppModuleBasic.
> ```

Check the comments of that module and ft as well, some of them are note relevant since they are about asset module, which we don't have anymore. 
___
*[`integration-tests/assetft/burn.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeBLNn-6zC2B6RbMfb:-NJeBLNn-6zC2B6RbMfc:bnhaxj3) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/integration-tests/assetft/burn.go#L29)):*
> ```Go
> 		chain.Faucet.FundAccountsWithOptions(ctx, issuer, testing.BalancesOptions{
> 			Messages: []sdk.Msg{
> 				&types.MsgIssue{},
> ```

Let's keep the import for the intagration tests with the `moduletypes` pattern, similar as we do it the other packages.
___
*[`proto/coreum/asset/ft/v1/event.proto` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeDgpGCug8u0OqxBfe:-NJeDgpH2GKNleU037x-:b-vszlkf) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/event.proto#L31)):*
> ```protobuf
> message EventFrozenAmountChanged {
>   string account = 1;
>   cosmos.base.v1beta1.Coin previous_amount = 2 [(gogoproto.nullable) = false];
> ```

This is not regarding that PR, bu anyway.

@ysv @wojtek-coreum @miladz68  I see now that we use in the `EventFrozenAmountChanged` `prev_amount` Coin but in the `WhitelistedAmountChanged` it `denom` + `Int`. Maybe the pattern should be the sammint(ctx sdk.Context, ft types.TokenDefinition, am
___
*[`x/asset/ft/client/cli/freeze_test.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeBgh_BJHSCQ8IL4JC:-NJeBgha-Bl6PGpGrJbn:b-m3kwpr) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/client/cli/freeze_test.go#L15)):*
> ```Go
> )
> 
> func TestFreeze(t *testing.T) {
> ```

How about merge all tx test to`tx_test.go` file, same for the `query`. Since now we have a lot of files with just one test.
@ysv @wojtek-coreum @miladz68  ? (and same for the both packages).
___
*[`x/asset/ft/keeper/issue.go` line 235 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeF7LTBrusRqyxBbjL:-NJeF7LTBrusRqyxBbjM:b-bswtqn) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/keeper/issue.go#L235)):*
> ```Go
> }
> 
> func (k Keeper) mint(ctx sdk.Context, ft types.TokenDefinition, amount sdk.Int, recipient sdk.AccAddress) error {
> ```

Guys, @miladz68 @ysv @wojtek-coreum  we chose the logic by which a function is located in a files, since I don't understand that logic now. For example `mint` and `burn` are in the `keeper.go` however `freeze` in a separate file `freeze.go`.
___
*[`x/asset/ft/types/keys.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeHoBPA5vdJQfJ7RMO:-NJeHoBPA5vdJQfJ7RMP:bi1uy6s) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/types/keys.go#L12)):*
> ```Go
> const (
> 	// ModuleName defines the module name
> 	ModuleName = "assetft"
> ```

Can we use a separotr here? Or don't use it in the CLI ? Becase in the CLI we use `asset-ft`.
Same is related to the nft.
___
*[`x/asset/ft/wasm/wasm.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeH6ux6_9br64ZJdMr:-NJeH6uyDgtZk_uNbHF1:bfli88r) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/wasm/wasm.go#L18)):*
> ```Go
> 	var res []sdk.Msg
> 	for msgType, msg := range messages {
> 		if msgType == "MsgIssue" {
> ```

Is the message name `common` for all modules or it leaves under `assetft` space in terms of wasm ?
Same question for the queries. Becase if the hander shares the common space the prefixed should be kept. 
___
*[`x/asset/nft/keeper/keeper.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeJ6UK-V6QpDgvajgI:-NJeJ6UK-V6QpDgvajgJ:bdhkpmi) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/keeper/keeper.go#L70)):*
> ```Go
> 		URIHash:     settings.URIHash,
> 	}); err != nil {
> 		return "", sdkerrors.Wrapf(types.ErrInvalidInput, "can't emit event EventNonFungibleTokenClassIssued: %s", err)
> ```

Outdated message.


<!-- Sent from Reviewable.io -->

2022-12-20 08:10 UTC, miladz68 requested changes
> Reviewed 85 of 85 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 13 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeDgpGCug8u0OqxBfe:-NJiChtl8GK51M_-P7U_:bn9gbkx) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/event.proto#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is not regarding that PR, bu anyway.

@ysv @wojtek-coreum @miladz68  I see now that we use in the `EventFrozenAmountChanged` `prev_amount` Coin but in the `WhitelistedAmountChanged` it `denom` + `Int`. Maybe the pattern should be the sammint(ctx sdk.Context, ft types.TokenDefinition, am
</blockquote></details>

I understand the reasoning that since in freeze we increment and in whitelist we just set the value, the events are different and reflect that. But I agree with Dima that providing the previous value is a valuable piece of information. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJiDz8R9VTezs0Cz9Gk:-NJiDz8R9VTezs0Cz9Gl:b-o3gj3p) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/tx.proto#L38)):*
> ```protobuf
>   rpc GloballyUnfreeze(MsgGloballyUnfreeze) returns (EmptyResponse);
> 
>   // SetWhitelistedLimit sets the limit of how many tokens account may hold
> ```

`an account may hold` or `each account may hold` or `a specific account may hold`
___
*[`x/asset/ft/client/cli/freeze_test.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeBgh_BJHSCQ8IL4JC:-NJiF0xa-ad-GE7m_Vty:b-qxcn1t) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/client/cli/freeze_test.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about merge all tx test to`tx_test.go` file, same for the `query`. Since now we have a lot of files with just one test.
@ysv @wojtek-coreum @miladz68  ? (and same for the both packages).
</blockquote></details>

I Think the opposite and I prefer to remove tx_test and query_test and have one file for every specific functionality that we are testing. But I agree that we should choose one approach and stick to it. 
___
*[`x/asset/ft/client/cli/query.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJiO6DWDF_nzGRe2siE:-NJiO6DX1IlUdhD-IvKb:b-i1xa8d) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/client/cli/query.go#L35)):*
> ```Go
> 
> // CmdQueryToken return the QueryToken cobra command.
> func CmdQueryToken() *cobra.Command {
> ```

non-blocking
while you are at it, consider that maybe CmdQueryTokenInfo or CmdQueryTokenDetails could be a better name.
___
*[`x/asset/ft/keeper/issue.go` line 235 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeF7LTBrusRqyxBbjL:-NJiPSdUCjhauD7nkEjC:b-zhjh9a) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/keeper/issue.go#L235)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Guys, @miladz68 @ysv @wojtek-coreum  we chose the logic by which a function is located in a files, since I don't understand that logic now. For example `mint` and `burn` are in the `keeper.go` however `freeze` in a separate file `freeze.go`.
</blockquote></details>

burn as the helper function (i.e it is dumb function that gets a value and and address and burns it) should live in keeper.go, since it is reused between functionalities. but Burn which is exposed to outside world and enforces bussiness logic should live in burn.go.
___
*[`x/asset/nft/client/cli/tx.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJiVTah3ez_E5p4FpBB:-NJiVTah3ez_E5p4FpBC:bakn1nb) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/client/cli/tx.go#L91)):*
> ```Go
> 
> Example:
> $ %s tx asset-nft mint abc-devcore1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8 id1 https://my-nft-meta.invalid/1 e000624 --from [sender]
> ```

can we have it as `asset nft` instead of `asset-nft` ?
I guess it will involve some work in module.go GetTxCmd but how much work will it be ?


<!-- Sent from Reviewable.io -->

2022-12-20 09:38 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/types/keys.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeHoBPA5vdJQfJ7RMO:-NJisvKmBEVOSX49B3EU:bn5f819) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/types/keys.go#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can we use a separotr here? Or don't use it in the CLI ? Becase in the CLI we use `asset-ft`.
Same is related to the nft.
</blockquote></details>

Here we can't because comos sdk allows alpahunmerical characters only
___
*[`x/asset/ft/wasm/wasm.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeH6ux6_9br64ZJdMr:-NJit3-79OKfKw06Pen0:bld96p6) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/wasm/wasm.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is the message name `common` for all modules or it leaves under `assetft` space in terms of wasm ?
Same question for the queries. Becase if the hander shares the common space the prefixed should be kept. 
</blockquote></details>

it is common, we need prefixes but it's a different PR I think
___
*[`x/asset/nft/client/cli/tx.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJiVTah3ez_E5p4FpBB:-NJitIpB4Pom9AvLtT3i:b-pi2ctn) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/client/cli/tx.go#L91)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

can we have it as `asset nft` instead of `asset-nft` ?
I guess it will involve some work in module.go GetTxCmd but how much work will it be ?
</blockquote></details>

To do that we would need some common "asset" module which creates a root command and imports commands for fts and nfts


<!-- Sent from Reviewable.io -->

2022-12-20 10:15 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeCf0oCS4rVA5CnsnB:-NJj-ikO7hjLU92ygyzs:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/pkg/config/deterministic_gas.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Extra line is needed here
</blockquote></details>

Done.
___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJj0llb1GNk6cow-lre:b-i2vbsv) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check the comments of that module and ft as well, some of them are note relevant since they are about asset module, which we don't have anymore. 
</blockquote></details>

WDYM exactly here?
___
*[`integration-tests/assetft/burn.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeBLNn-6zC2B6RbMfb:-NJj-V8h6P1g979nAl7O:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/integration-tests/assetft/burn.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's keep the import for the intagration tests with the `moduletypes` pattern, similar as we do it the other packages.
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJiDz8R9VTezs0Cz9Gk:-NJj-xUa9964u3W20Aws:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/tx.proto#L38)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

`an account may hold` or `each account may hold` or `a specific account may hold`
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeJ6UK-V6QpDgvajgI:-NJj0uza8mOczxsyIFdw:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/keeper/keeper.go#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Outdated message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-20 11:55 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 66 of 85 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJjNR1W61Stc4ZG7-9v:b-4vdtyd) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WDYM exactly here?
</blockquote></details>

 return the `asset` AppModuleBasic but that is `nftasset`.



_Code quote:_
```Go
 return the asset AppModuleBasic.
```
___
*[`proto/coreum/asset/ft/v1/event.proto` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeDgpGCug8u0OqxBfe:-NJjN2-P-WAN2eMLi13K:bc1sjhr) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/event.proto#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I understand the reasoning that since in freeze we increment and in whitelist we just set the value, the events are different and reflect that. But I agree with Dima that providing the previous value is a valuable piece of information. 
</blockquote></details>

@ysv could you plz capture it in a task, and I'll resolve that thread
___
*[`x/asset/ft/client/cli/freeze_test.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeBgh_BJHSCQ8IL4JC:-NJjNCEp0hTHNrmOg_mR:b-xfi0gw) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/client/cli/freeze_test.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I Think the opposite and I prefer to remove tx_test and query_test and have one file for every specific functionality that we are testing. But I agree that we should choose one approach and stick to it. 
</blockquote></details>

@ysv could you plz capture it in a task to discuss, and I'll resolve that thread
___
*[`x/asset/ft/keeper/issue.go` line 235 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeF7LTBrusRqyxBbjL:-NJjNG7Q44PylkzI7E_j:b-xfi0gw) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/keeper/issue.go#L235)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

burn as the helper function (i.e it is dumb function that gets a value and and address and burns it) should live in keeper.go, since it is reused between functionalities. but Burn which is exposed to outside world and enforces bussiness logic should live in burn.go.
</blockquote></details>

@ysv could you plz capture it in a task to discuss, and I'll resolve that thread
___
*[`x/asset/ft/wasm/wasm.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeH6ux6_9br64ZJdMr:-NJjNKjQ4Mi8KwpwL2De:budgf6i) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/wasm/wasm.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it is common, we need prefixes but it's a different PR I think
</blockquote></details>

But you have already renamed it from correct.
___
*[`x/asset/nft/keeper/keeper.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeJ6UK-V6QpDgvajgI:-NJjNXVUCD_CFOaNvwD4:b8bbpjo) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/keeper/keeper.go#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't see the update.


<!-- Sent from Reviewable.io -->

2022-12-20 11:55 UTC, dzmitryhil reviewed
> Reviewed 66 of 85 files at r1, 15 of 15 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-20 13:27 UTC, miladz68 approved these changes
> Reviewed 15 of 15 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-20 14:06 UTC, ysv requested changes
> Reviewed 71 of 85 files at r1, 15 of 15 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeDgpGCug8u0OqxBfe:-NJjkuxsCm9YizUTw8U-:b-t9490b) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/event.proto#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv could you plz capture it in a task, and I'll resolve that thread
</blockquote></details>

added 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 48 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjm1702i6zhuSVoKNX:-NJjm1702i6zhuSVoKNY:b-20l635) ([raw file](https://github.com/coreumfoundation/coreum/blob/f6e8f1480bea1d49077afc985bc1553ab4c2bb72/proto/coreum/asset/ft/v1/query.proto#L48)):*
> ```protobuf
> // QueryTokenResponse is response type for the Query/Token RPC method.
> message QueryTokenResponse {
>   Token token = 1 [(gogoproto.nullable) = false];
> ```

`FungitbleToken/FT`
___
*[`proto/coreum/asset/ft/v1/token.proto` line 33 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJfh7or-GxWpFHMbOn5:-NJfh7or-GxWpFHMbOn6:b-jjufgb) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/token.proto#L33)):*
> ```protobuf
> 
> // Token is a full representation of the fungible token.
> message Token {
> ```

I don't like name Token separately. I prefer to use FungibleToken in such places

`ft.FungibleToken/ft.FungibleTokenDefinition` seems better for me
Same for events
___
*[`x/asset/ft/client/cli/freeze_test.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeBgh_BJHSCQ8IL4JC:-NJjmjxiBbyXU2LdmkmJ:bb7f2mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/client/cli/freeze_test.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv could you plz capture it in a task to discuss, and I'll resolve that thread
</blockquote></details>

done
___
*[`x/asset/ft/client/cli/query_test.go` line 51 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjntXM45evyknzMFVI:-NJjntXM45evyknzMFVJ:bhnya6d) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/x/asset/ft/client/cli/query_test.go#L51)):*
> ```Go
> }
> 
> func issueFungibleToken(requireT *require.Assertions, ctx client.Context, symbol, subunit, precision string, testNetwork *network.Network) string {
> ```

in such places I would keep `issueFT` because just issue doesnt' have enought context
___
*[`x/asset/ft/keeper/issue.go` line 235 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeF7LTBrusRqyxBbjL:-NJjoQcp3uw5ND4VsXK8:bb7f2mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/keeper/issue.go#L235)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv could you plz capture it in a task to discuss, and I'll resolve that thread
</blockquote></details>

done
___
*[`x/asset/ft/types/errors.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjogss3wh1Jta1Vg12:-NJjogss3wh1Jta1Vg13:bighg0f) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/x/asset/ft/types/errors.go#L11)):*
> ```Go
> 	ErrInvalidInput = sdkerrors.Register(ModuleName, 1, "invalid input")
> 	// ErrFungibleTokenNotFound error for a fungible token not found in the store.
> 	ErrFungibleTokenNotFound = sdkerrors.Register(ModuleName, 2, "fungible token not found")
> ```

FT or FungibleToken
___
*[`x/asset/ft/types/ft.go` line 33 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjoniGAv4UVzVr4ZTi:-NJjoniGAv4UVzVr4ZTj:be6fu9m) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/x/asset/ft/types/ft.go#L33)):*
> ```Go
> 
> // IssueFungibleTokenSettings is the model which represents the params for the fungible token issuance.
> type IssueFungibleTokenSettings struct {
> ```

I propose to keep IssueFTSettings here
___
*[`x/asset/ft/types/keys.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjouLz8K5leRFlMEKv:-NJjouLz8K5leRFlMEKw:b-ciut73) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/x/asset/ft/types/keys.go#L27)):*
> ```Go
> var (
> 	// FungibleTokenKeyPrefix defines the key prefix for the fungible token.
> 	FungibleTokenKeyPrefix = []byte{0x01}
> ```

I would keep FT or FungibleToken but not just Token


<!-- Sent from Reviewable.io -->

2022-12-20 15:09 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-20 15:23 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`proto/coreum/asset/ft/v1/query.proto` line 48 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjm1702i6zhuSVoKNX:-NJk77rL0Jy9QOxTBeNk:b-mxu0fa) ([raw file](https://github.com/coreumfoundation/coreum/blob/f6e8f1480bea1d49077afc985bc1553ab4c2bb72/proto/coreum/asset/ft/v1/query.proto#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`FungitbleToken/FT`
</blockquote></details>

what for? We are already inside FT namespace


<!-- Sent from Reviewable.io -->

2022-12-21 07:19 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/query.proto` line 48 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjm1702i6zhuSVoKNX:-NJnXwr903GYFx7ur1Vh:bjtvs8z) ([raw file](https://github.com/coreumfoundation/coreum/blob/f6e8f1480bea1d49077afc985bc1553ab4c2bb72/proto/coreum/asset/ft/v1/query.proto#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what for? We are already inside FT namespace
</blockquote></details>

that was the major point of the refactor to not call it FungibleToken. 


<!-- Sent from Reviewable.io -->

2022-12-21 07:53 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 8 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-21 11:27 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-21 12:07 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 56 of 85 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJoTCae-A_eFc9yM5Op:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

 return the `asset` AppModuleBasic but that is `nftasset`.
</blockquote></details>

Done.



_Code quote:_
```Go
// NewAppModuleBasic return the asset AppModuleBasic.
```
___
*[`proto/coreum/asset/ft/v1/query.proto` line 48 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjm1702i6zhuSVoKNX:-NJoUBZx63rc0YaoQMOs:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f6e8f1480bea1d49077afc985bc1553ab4c2bb72/proto/coreum/asset/ft/v1/query.proto#L48)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that was the major point of the refactor to not call it FungibleToken. 
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/token.proto` line 33 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJfh7or-GxWpFHMbOn5:-NJoUCwj-ULXhQFGFAN0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/proto/coreum/asset/ft/v1/token.proto#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like name Token separately. I prefer to use FungibleToken in such places

`ft.FungibleToken/ft.FungibleTokenDefinition` seems better for me
Same for events
</blockquote></details>

Done.
___
*[`x/asset/ft/types/errors.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjogss3wh1Jta1Vg12:-NJoSoqT2o9bFFG_fniJ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/x/asset/ft/types/errors.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

FT or FungibleToken
</blockquote></details>

Done.
___
*[`x/asset/ft/types/keys.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJjouLz8K5leRFlMEKv:-NJoTzRT51_eUzNAzuEN:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/x/asset/ft/types/keys.go#L27)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would keep FT or FungibleToken but not just Token
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 12:19 UTC, ysv submitted a review, later dismissed
> Reviewed 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-21 12:19 UTC, dzmitryhil reviewed
> Reviewed 29 of 29 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 80 of 85 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJobyXR4143qxz_VOIO:b-k3fwlv) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same for all comments in that file and in the same in ft module.


<!-- Sent from Reviewable.io -->

2022-12-21 12:20 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 80 of 85 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/wasm/wasm.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeH6ux6_9br64ZJdMr:-NJobykG7cLwpClte5u1:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/ft/wasm/wasm.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But you have already renamed it from correct.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 12:20 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 80 of 85 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-12-21 12:25 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: 78 of 85 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJodAJuAFDXl1M0i4Rf:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same for all comments in that file and in the same in ft module.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 12:27 UTC, miladz68 approved these changes
> Reviewed 29 of 29 files at r4, 5 of 5 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)



<!-- Sent from Reviewable.io -->

2022-12-21 12:32 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/asset/nft/module.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/300#-NJeITJ6DywpqyjlWuGm:-NJof0jm0xeIagCjjcu1:b-vr4p06) ([raw file](https://github.com/coreumfoundation/coreum/blob/0b2426609623f0aee5c50665ab5f89a4d0056186/x/asset/nft/module.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it.



_Code quote:_
```Go
 Name returns the asset module's name.
```


<!-- Sent from Reviewable.io -->

2022-12-21 12:35 UTC, dzmitryhil reviewed
> Reviewed 5 of 5 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-21 12:36 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2022-12-21 12:43 UTC, merged