enforce rules of ft asset in multisend
CoreumFoundation/coreum pull request #321
Opened 2022-12-30 10:57 UTC by miladz68

2022-12-30 13:45 UTC, wojtek-coreum reviewed
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-02 09:13 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlg5XfBQgUUnQVJ-qF:-NKlg5XfBQgUUnQVJ-qG:bwl5n6a) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L6)):*
> ```Go
> 	"fmt"
> 	"testing"
> ```

If the `target code` is located in the `keeper.go` file the test code should follow the same naming `keeper_test` otherwise it's hard to map such files.
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlYeu40ajt99skHrUD:-NKlYeu57tts0PFB0Z8p:b85fl9v) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L33)):*
> ```Go
> // BeforeSendCoins checks that a transfer request is allowed or not
> func (k Keeper) BeforeSendCoins(ctx sdk.Context, fromAddress, toAddress sdk.AccAddress, coins sdk.Coins) error {
> 	return k.BeforeInputOutputCoins(
> ```

I would propose to have the `private` func here instead of calling `BeforeInputOutputCoins`, because it's look unnatural that Hook calls Hook.
And also in that case both hooks can be located one after another, which gives better readability for that file.
___
*[`x/asset/ft/keeper/keeper.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlZ32e40fAn8b5wqY_:-NKlZ32e40fAn8b5wqYa:b-lakpuq) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L41)):*
> ```Go
> 
> // MultiSendIterationInfo is used to gather information about multi send, and will be used to calculate
> // burn_rate and send_commission_rate must be calculate in multi send
> ```

be calculate -> be calculated
___
*[`x/asset/ft/keeper/keeper.go` line 64 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlh9l86gr6-mFPo115:-NKlh9l86gr6-mFPo116:b-64zjy) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L64)):*
> ```Go
> 	if burnAmount.IsPositive() {
> 		for sendAccount, sendAmount := range info.NonIssuerSenders {
> 			burnShare := burnAmount.Mul(sdk.NewDecFromInt(sendAmount)).Quo(sdk.NewDecFromInt(info.NonIssuerInputSum)).Ceil().RoundInt()
> ```

Is the `.Ceil().RoundInt()` different from `TruncateInt()` ?
___
*[`x/asset/ft/keeper/keeper.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlaY4d9HrhqUA2bh8S:-NKlaY4d9HrhqUA2bh8T:bj0c8ba) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L82)):*
> ```Go
> 
> func (k Keeper) iterateInputOutputs(ctx sdk.Context, inputs []banktypes.Input, outputs []banktypes.Output) (map[string]MultiSendIterationInfo, error) {
> 	iterationMap := map[string]MultiSendIterationInfo{}
> ```

Optional: I would create maps with the `make()` the advantage is that the style of the maps creation remains the same no matter you use zero or non zero allocation for it. Same comment for all maps allocated in that file.
___
*[`x/asset/ft/keeper/keeper.go` line 84 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKl_H-Y5HXsrkYm9WVi:-NKl_H-Y5HXsrkYm9WVj:b-ohn0s4) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L84)):*
> ```Go
> 	iterationMap := map[string]MultiSendIterationInfo{}
> 	iterateCoin := func(coin sdk.Coin, address sdk.AccAddress, isInput bool) error {
> 		ft, err := k.GetTokenDefinition(ctx, coin.Denom)
> ```

It would be better to cache the definitions in the map `[denom]FTDefinition`.  Because even having the same denom, for the coins distribution, you will get it from the storage each time in the loop. The cache be a part of your `iterateCoin` method and might looks like this:

```go
	tokenDefinitions := make(map[string]types.FTDefinition, 0)
	iterateCoin := func(coin sdk.Coin, address sdk.AccAddress, isInput bool) error {
		ft, ok := tokenDefinitions[coin.Denom]
		var err error
		if !ok {
			ft, err = k.GetTokenDefinition(ctx, coin.Denom)
			if types.ErrFTNotFound.Is(err) {
				return nil
			}
			tokenDefinitions[coin.Denom] = ft
		}
		...
```

Also you can return that map from the func, to use later in the `BeforeInputOutputCoins` in the part:
```
for _, coin := range out.Coins {
			ft, err := k.GetTokenDefinition(ctx, coin.Denom)
```.
```

___
*[`x/asset/ft/keeper/keeper.go` line 99 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKliFik75D2VKjtRPTi:-NKliFik75D2VKjtRPTj:b-2prthf) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L99)):*
> ```Go
> 				NonIssuerInputSum:  sdk.NewInt(0),
> 				NonIssuerOutputSum: sdk.NewInt(0),
> 				NonIssuerSenders:   map[string]sdk.Int{},
> ```

Just for your info, you can use the `map[*sdk.AccAddress]sdk.Int{},` for the key. In that case, it will let you to remove few lines of the code.
___
*[`x/asset/ft/keeper/keeper.go` line 105 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKldplT7dM3gnPdbrNa:-NKldplT7dM3gnPdbrNb:blp3a1q) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L105)):*
> ```Go
> 		}
> 
> 		//nolint:nestif // I could not find a way to fix the complexity here without sacrificing performance
> ```

It's archivable if you move the content of your `if/else` to functions. In that case even readability is better.

```go
		if isInput {
			info, err = k.fillInputs(ctx, coin, address, info, ft)
			if err != nil {
				return err
			}
		}  else {
			info, err = k.fillOutputs(ctx, coin, address, info, ft)
			if err != nil {
				return err
			}
		}

		iterationMap[ft.Denom] = info
```
Optional: I would actually remove the `else` and duplicate the `iterationMap[ft.Denom] = info + retrun`  but that's just a style comment.


<!-- Sent from Reviewable.io -->

2023-01-02 09:13 UTC, dzmitryhil reviewed
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-02 10:15 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlg5XfBQgUUnQVJ-qF:-NKlxvdLAGNIqSMvZRYN:b-tn32t0) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If the `target code` is located in the `keeper.go` file the test code should follow the same naming `keeper_test` otherwise it's hard to map such files.
</blockquote></details>

@ysv @wojtek-coreum WDYT ?
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlYeu40ajt99skHrUD:-NKlxAyZADpyalgq0mf-:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would propose to have the `private` func here instead of calling `BeforeInputOutputCoins`, because it's look unnatural that Hook calls Hook.
And also in that case both hooks can be located one after another, which gives better readability for that file.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlZ32e40fAn8b5wqY_:-NKlrker3YbUyph5-MBS:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

be calculate -> be calculated
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 64 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlh9l86gr6-mFPo115:-NKlryu5B8w0Qavxiis9:bwyqje4) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L64)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is the `.Ceil().RoundInt()` different from `TruncateInt()` ?
</blockquote></details>

Truncate drops precision, and will always round down, we need round up. 
___
*[`x/asset/ft/keeper/keeper.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlaY4d9HrhqUA2bh8S:-NKltoCo5hhfiBxsk6OR:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Optional: I would create maps with the `make()` the advantage is that the style of the maps creation remains the same no matter you use zero or non zero allocation for it. Same comment for all maps allocated in that file.
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 84 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKl_H-Y5HXsrkYm9WVi:-NKluRhkExivN79alRYc:b-eg5xm2) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be better to cache the definitions in the map `[denom]FTDefinition`.  Because even having the same denom, for the coins distribution, you will get it from the storage each time in the loop. The cache be a part of your `iterateCoin` method and might looks like this:

```go
	tokenDefinitions := make(map[string]types.FTDefinition, 0)
	iterateCoin := func(coin sdk.Coin, address sdk.AccAddress, isInput bool) error {
		ft, ok := tokenDefinitions[coin.Denom]
		var err error
		if !ok {
			ft, err = k.GetTokenDefinition(ctx, coin.Denom)
			if types.ErrFTNotFound.Is(err) {
				return nil
			}
			tokenDefinitions[coin.Denom] = ft
		}
		...
```

Also you can return that map from the func, to use later in the `BeforeInputOutputCoins` in the part:
```
for _, coin := range out.Coins {
			ft, err := k.GetTokenDefinition(ctx, coin.Denom)
```.
```

</blockquote></details>

Actually a new map is not needed. I just need to first check the map and then fetch the FTDefinition. 
Done
___
*[`x/asset/ft/keeper/keeper.go` line 99 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKliFik75D2VKjtRPTi:-NKlupzhEqh8XuwjgbUX:b-28i92d) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Just for your info, you can use the `map[*sdk.AccAddress]sdk.Int{},` for the key. In that case, it will let you to remove few lines of the code.
</blockquote></details>

`*sdk.AccAddress` is not good enough in this context, since they will produce different keys for the hash map when they represent the same account address. In other words `*sdk.Accress` can be different keys on the map, when their string representation might be equal. 
___
*[`x/asset/ft/keeper/keeper.go` line 105 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKldplT7dM3gnPdbrNa:-NKlwjNuCQD3_JNxWfKk:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L105)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's archivable if you move the content of your `if/else` to functions. In that case even readability is better.

```go
		if isInput {
			info, err = k.fillInputs(ctx, coin, address, info, ft)
			if err != nil {
				return err
			}
		}  else {
			info, err = k.fillOutputs(ctx, coin, address, info, ft)
			if err != nil {
				return err
			}
		}

		iterationMap[ft.Denom] = info
```
Optional: I would actually remove the `else` and duplicate the `iterationMap[ft.Denom] = info + retrun`  but that's just a style comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-02 14:15 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-03 07:14 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlYeu40ajt99skHrUD:-NKqRWzgCxoVQcUgszJw:b-kooytn) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually the name on the new method is not so correct, since you can that method for both sends.
</blockquote></details>

any suggestions ?


<!-- Sent from Reviewable.io -->

2023-01-03 07:44 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlYeu40ajt99skHrUD:-NKq__Fi954u4RHiw1ZN:b-9jfqr3) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

any suggestions ?
</blockquote></details>

Nope :-)



_Code quote:_
```Go
beforeInputOutputCoins
```


<!-- Sent from Reviewable.io -->

2023-01-04 08:45 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlg5XfBQgUUnQVJ-qF:-NKvxDLX0t-Pn7CAjHL9:bdpegve) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L6)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv @wojtek-coreum WDYT ?
</blockquote></details>

seems reasonable
___
*[`x/asset/ft/keeper/keeper.go` line 57 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvrD-x5EJxcNj_szlm:-NKvrD-x5EJxcNj_szln:b11d8nq) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L57)):*
> ```Go
> 
> // CalculateBurnRateAndCommissionShares returns the burn coins and commission coins
> func (info MultiSendIterationInfo) CalculateBurnRateAndCommissionShares() (map[string]sdk.Int, map[string]sdk.Int) {
> ```

this functio n could be rewritten to sth like

```
 CalculateBurnRateAndCommissionShares(rate sdk.Dec) map[string]sdk.Int
```

because two sections are identical, the only difference is in the rate used for calculation
___
*[`x/asset/ft/keeper/keeper.go` line 69 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvqlus8kItRHDWmW8d:-NKvqlutDrCanzFPoCGa:b-9hfb7o) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L69)):*
> ```Go
> 	if burnAmount.IsPositive() {
> 		for sendAccount, sendAmount := range info.NonIssuerSenders {
> 			burnShare := burnAmount.Mul(sdk.NewDecFromInt(sendAmount)).Quo(sdk.NewDecFromInt(info.NonIssuerInputSum)).Ceil().RoundInt()
> ```

Minor: I would remove `burnShare` variable. It doesn't add anything, same for `commissionShare` below.
___
*[`x/asset/ft/keeper/keeper.go` line 86 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvuXN-4u-oqGKW_F0T:-NKvuBdO03Yb-7vp3r7t:brqzwny) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L86)):*
> ```Go
> }
> 
> func (k Keeper) fillInputs(ctx sdk.Context, address sdk.AccAddress, info MultiSendIterationInfo, coin sdk.Coin) error {
> ```

`info` must be a pointer here, otherwise you update a copy (affects `info.NonIssuerInputSum` only), which does not take effect on original value passed to this function
___
*[`x/asset/ft/keeper/keeper.go` line 106 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvujQw2thB9WTaYKWM:-NKvujQxETlRzwA4YgZZ:b-k4pg6b) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L106)):*
> ```Go
> }
> 
> func (k Keeper) fillOutputs(ctx sdk.Context, address sdk.AccAddress, info MultiSendIterationInfo, coin sdk.Coin) error {
> ```

`info` must be a pointer here, otherwise you update a copy (affects `info..NonIssuerOutputSum`), which does not take effect on original value passed to this function
___
*[`x/asset/ft/keeper/keeper.go` line 157 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvsDUS60FRa2QuAdjN:-NKvsDUS60FRa2QuAdjO:b2qbz3o) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L157)):*
> ```Go
> 		}
> 
> 		iterationMap[info.FT.Denom] = info
> ```

This line might be moved to `if !ok {` block if `iterationMap` stores pointers, which is more or less required to resolve my other comments above
___
*[`x/asset/ft/keeper/keeper.go` line 225 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvw39g-_0JHGXxt8gO:-NKvw39g-_0JHGXxt8gP:bty2o28) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L225)):*
> ```Go
> 		}
> 	}
> ```

after charging burn rate and send commission, `isCoinSendable` done in `fillInputs` might no longer be valid due to possible lower non-frozen balance available after transferring those fees
___
*[`x/asset/ft/keeper/keeper.go` line 241 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvvyuEDlJCRBymJjDv:-NKvvyuF9rbOvaXq67Ce:br7u09m) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L241)):*
> ```Go
> 			}
> 
> 			if err := k.isCoinReceivable(ctx, outAddress, ft, coin.Amount); err != nil {
> ```

Is it needed? It was already done in `fillOutputs`


<!-- Sent from Reviewable.io -->

2023-01-04 10:06 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlg5XfBQgUUnQVJ-qF:-NKw0I2c321uP3uctDCH:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L6)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

seems reasonable
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKlYeu40ajt99skHrUD:-NKsB9la5-dEpsFlpo_2:bwiyssj) ([raw file](https://github.com/coreumfoundation/coreum/blob/547af7b8231e5112ef018bb7f6e2e1a89233d1de/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Nope :-)
</blockquote></details>

applyFeatures name was chosen, add additional comments to describe why it is there. 
___
*[`x/asset/ft/keeper/keeper.go` line 69 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvqlus8kItRHDWmW8d:-NKw1Wm5DPQFl0bthjRo:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: I would remove `burnShare` variable. It doesn't add anything, same for `commissionShare` below.
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 86 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvuXN-4u-oqGKW_F0T:-NKw39LhCfaUM1MEc7Of:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L86)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`info` must be a pointer here, otherwise you update a copy (affects `info.NonIssuerInputSum` only), which does not take effect on original value passed to this function
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 106 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvujQw2thB9WTaYKWM:-NKw38c3Ekj4YLP-5oar:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`info` must be a pointer here, otherwise you update a copy (affects `info..NonIssuerOutputSum`), which does not take effect on original value passed to this function
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 157 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvsDUS60FRa2QuAdjN:-NKw90GJ7rzm0PyAQr17:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L157)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This line might be moved to `if !ok {` block if `iterationMap` stores pointers, which is more or less required to resolve my other comments above
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 225 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvw39g-_0JHGXxt8gO:-NKwE_GM2jXnPAnR6AFp:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L225)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

after charging burn rate and send commission, `isCoinSendable` done in `fillInputs` might no longer be valid due to possible lower non-frozen balance available after transferring those fees
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 241 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKvvyuEDlJCRBymJjDv:-NKwEbiM-TQPX7KE8trB:ba3dfob) ([raw file](https://github.com/coreumfoundation/coreum/blob/12609162e55c12beccdfe9c868469a85d4dad173/x/asset/ft/keeper/keeper.go#L241)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it needed? It was already done in `fillOutputs`
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2023-01-04 10:32 UTC, wojtek-coreum reviewed
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 127 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKwJy_J5KYUQDY0Zwy7:-NKwJy_J5KYUQDY0Zwy8:btmte6p) ([raw file](https://github.com/coreumfoundation/coreum/blob/7211c246b301f765cc56853df3f9db3e3ee8ba21/x/asset/ft/keeper/keeper.go#L127)):*
> ```Go
> 				Receivers:          make(map[string]sdk.Int),
> 			}
> 			iterationMap[info.FT.Denom] = info
> ```

To make it work `iterationMap` must store pointers. Otherwise `info` and map store two different copies
___
*[`x/asset/ft/keeper/keeper.go` line 208 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKwKQ30BlnmTrPF7sC8:-NKwKQ30BlnmTrPF7sC9:be57rg6) ([raw file](https://github.com/coreumfoundation/coreum/blob/7211c246b301f765cc56853df3f9db3e3ee8ba21/x/asset/ft/keeper/keeper.go#L208)):*
> ```Go
> 		}
> 
> 		// we need to check restraints after the burn_rate and send_commission_rate is applied
> ```

is -> are


<!-- Sent from Reviewable.io -->

2023-01-04 10:49 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 127 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKwJy_J5KYUQDY0Zwy7:-NKwORrQ8e095_94Zeoo:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/7211c246b301f765cc56853df3f9db3e3ee8ba21/x/asset/ft/keeper/keeper.go#L127)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To make it work `iterationMap` must store pointers. Otherwise `info` and map store two different copies
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper.go` line 208 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NKwKQ30BlnmTrPF7sC8:-NKwOZpr3YDX78WN5_jL:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/7211c246b301f765cc56853df3f9db3e3ee8ba21/x/asset/ft/keeper/keeper.go#L208)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

is -> are
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-04 10:59 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-04 15:28 UTC, dzmitryhil approved these changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-06 08:27 UTC, dzmitryhil approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-06 12:52 UTC, ysv requested changes
> Reviewed 1 of 3 files at r5, 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @silverspase)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NL67m9C7lGhwFpRH1iK:-NL67m9C7lGhwFpRH1iL:bxd6uha) (no related file):*
Adding first small batch of minor comments
Will continue review

___
___
*[`x/asset/ft/keeper/keeper.go` line 73 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NL1BfOi-bqmxBZ3GPGz:-NL1BfOi-bqmxBZ3GPH-:b-i2yszp) ([raw file](https://github.com/coreumfoundation/coreum/blob/5684a6c6c776faa81f4f6d173138b06f16029cc7/x/asset/ft/keeper/keeper.go#L73)):*
> ```Go
> // MultiSendIterationInfo is used to gather information about multi send, and will be used to calculate
> // burn_rate and send_commission_rate must be calculated in multi send
> type MultiSendIterationInfo struct {
> ```

doesn't need to be exposed outside of keeper pkg ?
should we rename to `multiSendIterationInfo` ?
___
*[`x/asset/ft/keeper/keeper.go` line 84 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NL1GA1o4oajafh8U1hf:-NL1GA1o4oajafh8U1hg:b-ilhftj) ([raw file](https://github.com/coreumfoundation/coreum/blob/5684a6c6c776faa81f4f6d173138b06f16029cc7/x/asset/ft/keeper/keeper.go#L84)):*
> ```Go
> // CalculateRateShares returns the burn coins and commission coins
> func (info MultiSendIterationInfo) CalculateRateShares(rate sdk.Dec) map[string]sdk.Int {
> 	var minNonIssuerIOAmount sdk.Int
> ```

could be simplified to 1 if
```
minNonIssuerIOAmount := info.NonIssuerInputSum
if info.NonIssuerOutputSum.LT(minNonIssuerIOAmount) {
  minNonIssuerIOAmount = info.NonIssuerOutputSum
}
```


<!-- Sent from Reviewable.io -->

2023-01-09 09:45 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-11 16:37 UTC, ysv requested changes
> Reviewed 1 of 4 files at r1, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWgImY9SJw_fVfqvBH:-NLWgImY9SJw_fVfqvBI:bhnls5e) (no related file):*
I have reviewed implementation fully the only part which is left is tests will continue on them on the next iteration

___
___
*[`x/asset/ft/keeper/multisend_logic.go` line 12 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLW_m_M7eEWZMYGG5rQ:-NLW_m_M7eEWZMYGG5rR:b-4va1vk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L12)):*
> ```Go
> 
> // AccAmount is a paring between Account and Amount
> type AccAmount struct {
> ```

1. I propose to rename this structure to `AccOperation`/`BankOperation` (both input & output are acc/bank operations). 

2. and rename  `groupByDenomContainer` -> `groupedByDenomBankOperations`


and then rename all vars in funcs accordingly: `input/outputOperationsByDenom`, `input/outputOperation` etc.
___
*[`x/asset/ft/keeper/multisend_logic.go` line 31 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWXFpIB8Ui5cXtATNK:-NLWXFpIB8Ui5cXtATNL:ba6fjq7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L31)):*
> ```Go
> }
> 
> type groupByDenomContainer map[string]map[string]sdk.Int
> ```

(comment with renaming is also related to this)

I propose to change this structure to :
```
type groupByDenomContainer map[string][]AccAmount
```

reasons:

1. I don't like to have nested maps I think it makes things too complicated & unreadable

2. Later we need this structure in flattened format only and we use nested map only to make filtering simpler. But we can iterate though array each time instead of getting value by key. It will not bring a lot of overhead

3. less "custom" structures needed & AccAmount is reused everywhere

4. minor: this solution requires less code
___
*[`x/asset/ft/keeper/multisend_logic.go` line 33 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWX-EbCCYQY5BroGmB:-NLWX-Ec93nfkAwYLZ2Z:bohh1vd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L33)):*
> ```Go
> type groupByDenomContainer map[string]map[string]sdk.Int
> 
> func (g groupByDenomContainer) add(address string, coins sdk.Coins) {
> ```

nice decisions to add this method it makes everything more clear :thumbsup: 
___
*[`x/asset/ft/keeper/multisend_logic.go` line 35 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWYJKe-xIH2M0ZEoEt:-NLWYJKe-xIH2M0ZEoEu:b-p2k619) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L35)):*
> ```Go
> func (g groupByDenomContainer) add(address string, coins sdk.Coins) {
> 	for _, coin := range coins {
> 		io, ok := g[coin.Denom]
> ```

lets rename io variable. Too similar to IO (probably not needed if we change structure accoring to previous comments)
___
*[`x/asset/ft/keeper/multisend_logic.go` line 72 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWZDiG43-s2E3bimF1:-NLWZDiG43-s2E3bimF2:brtauj2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L72)):*
> ```Go
> 		}
> 
> 		outputAmounts := outputAmounts[denom]
> ```

`outputAmounts` conflicts with func arg `outputAmounts`
___
*[`x/asset/ft/keeper/multisend_logic.go` line 83 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWcqpGBxXzElYTM9hQ:-NLWcqpGBxXzElYTM9hR:bamdet8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L83)):*
> ```Go
> 		commissionShares := CalculateRateShares(ftd.SendCommissionRate, ftd.Issuer, inputAmounts, outputAmounts)
> 		for _, commissionShare := range commissionShares {
> 			if err := k.burn(ctx, commissionShare.Account, ftd, commissionShare.Amount); err != nil {
> ```

you burn twice but here you should use `k.SendCoinsToAccount`
___
*[`x/asset/ft/keeper/multisend_logic.go` line 128 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWecyv1Z1phZAlt4Cq:-NLWecyv1Z1phZAlt4Cr:b-8mqb3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L128)):*
> ```Go
> 		for _, inpAmount := range inputAmounts {
> 			if inpAmount.Account.String() != issuer {
> 				burnAmount := rate.MulInt(minNonIssuer).Mul(sdk.NewDecFromInt(inpAmount.Amount)).QuoInt(inputSumNonIssuer).Ceil().RoundInt()
> ```

everything looks good but can you also add comment with logic of this calculation here. 
It could be a long comment (probably smth similar to what we have in clickup) & Having a few examples would be beneficial

Actually current calculation is the simplest IMO so basicly formula is:
`rate * amount * min(sumInputsNonIssuer, sumOutputsNonIssuer) / sumInputsNonIssuer`

so basicly discout here is applied only if sumInputsNonIssuer < sumOutputsNonIssuer
___
*[`x/asset/ft/keeper/multisend_logic.go` line 128 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWfsnZBOZk7e5LlcP2:-NLWfsnZBOZk7e5LlcP3:b-k2x7xb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L128)):*
> ```Go
> 		for _, inpAmount := range inputAmounts {
> 			if inpAmount.Account.String() != issuer {
> 				burnAmount := rate.MulInt(minNonIssuer).Mul(sdk.NewDecFromInt(inpAmount.Amount)).QuoInt(inputSumNonIssuer).Ceil().RoundInt()
> ```

does it make sense to change order of operations here so we do all multiplications with ints first then multiply by decimal and then divide:
`min_non_issuer * amount * rate / sum_inputs_non-Issuer`

or it could overflow int used b cosmos
___
*[`x/asset/ft/keeper/multisend_logic.go` line 129 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWdqO5E9DAaJIMuurJ:-NLWdqO5E9DAaJIMuurK:b-rvjmje) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L129)):*
> ```Go
> 			if inpAmount.Account.String() != issuer {
> 				burnAmount := rate.MulInt(minNonIssuer).Mul(sdk.NewDecFromInt(inpAmount.Amount)).QuoInt(inputSumNonIssuer).Ceil().RoundInt()
> 				shares = append(shares, AccAmount{Account: inpAmount.Account, Amount: burnAmount})
> ```

lets avoid using burn word here since burn & commission are 2 different functionalities amd we don't want to mix them


<!-- Sent from Reviewable.io -->

2023-01-12 07:37 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: 5 of 6 files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/multisend_logic.go` line 1 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLZr7ZK9ZsKi2r02xfV:-NLZr7ZK9ZsKi2r02xfW:b-r2n1f4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L1)):*
> ```Go
> package keeper
> ```

Let's remove `logic` postfix from the file. All we do is `logic` :-)
___
*[`x/asset/ft/keeper/multisend_logic.go` line 35 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWYJKe-xIH2M0ZEoEt:-NLZtJQOCN30szikPa4A:b-xoxz0z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets rename io variable. Too similar to IO (probably not needed if we change structure accoring to previous comments)
</blockquote></details>

Agree, had the same feeling.
___
*[`x/asset/ft/keeper/multisend_logic.go` line 83 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWcqpGBxXzElYTM9hQ:-NLZtZV75Myim6zpdsKV:b-rlyh0q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L83)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you burn twice but here you should use `k.SendCoinsToAccount`
</blockquote></details>

And the tests don't pass, which is good. Could you please check that the case is covered in the tests and they don't pass because of that.



_Code quote:_
```Go
if err := k.burn(ctx, commissionShar
```
___
*[`x/asset/ft/keeper/multisend_logic.go` line 104 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLZrYud0zqUsMJGRJvU:-NLZrYud0zqUsMJGRJvV:b-ugqkkf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L104)):*
> ```Go
> }
> 
> // CalculateRateShares calculates how the burn amount should be split between different parties
> ```

The method is common for the `burning` and `commision`, fix the comment plz.
___
*[`x/asset/ft/keeper/multisend_logic.go` line 128 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWfsnZBOZk7e5LlcP2:-NLZsGBf9_WZ4wqMgpuR:bnk06an) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L128)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it make sense to change order of operations here so we do all multiplications with ints first then multiply by decimal and then divide:
`min_non_issuer * amount * rate / sum_inputs_non-Issuer`

or it could overflow int used b cosmos
</blockquote></details>

In general this is a good rule. The decision should be always last to have better precision.


<!-- Sent from Reviewable.io -->

2023-01-12 14:02 UTC, dzmitryhil reviewed
> Reviewed 4 of 4 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: all files reviewed, 9 unresolved discussions (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-12 14:52 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: all files reviewed, 9 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`x/asset/ft/keeper/multisend_logic.go` line 31 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLWXFpIB8Ui5cXtATNK:-NLaSfj-2MdJvlS44lcn:bcedeg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f74828fc6bfa4d5e9b1804899af3ed9c425d617/x/asset/ft/keeper/multisend_logic.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I need this nested map to check for duplicates, otherwise I will need to re-introduce IOPut struct that you had, and also another function to first merge the the accounts, and then group by denom. that adds about 50 lines of code, and 4 additional iterations over the lists. it will also make the next change, which is `add` function impossible. 

let's talk this in quick call.  
</blockquote></details>

Define a type alias for map[string]Int to indicate Balances, it will make the code more readable. 


<!-- Sent from Reviewable.io -->

2023-01-12 17:40 UTC, ysv requested changes
> Reviewed 3 of 4 files at r11, 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/321)* status: 5 of 6 files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`x/asset/ft/keeper/keeper_test.go` line 462 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLavbHh2rkJNoPC8VQo:-NLavbHh2rkJNoPC8VQp:b-5lklbm) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L462)):*
> ```Go
> 		{
> 			rate:    "0.5",
> 			issuer:  issuer,
> ```

should we drop this field since it is the same everywhere ?
___
*[`x/asset/ft/keeper/keeper_test.go` line 466 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLayY4iE6d4ppToruiu:-NLayY4iE6d4ppToruiv:b-exqzbf) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L466)):*
> ```Go
> 			shares:  map[string]int64{},
> 		},
> 		{
> ```

another test cases to be added:

1. test rounding of small numbers
```
		{
			rate:   "0.1",
			issuer: issuer,
			senders: map[string]int64{
				account[0]: 1,
				account[1]: 2,
				account[2]: 9,
			},
			receivers: map[string]int64{
				accounts[0]: 12,
			},
			shares: map[string]int64{
                                account[0]: 1,
				account[1]: 1,
				account[2]: 1,
                  },
		},

```

2. test huge numbers. Since we have multiplication of amount * sum(amounts) I'm afraid of int overflow. Smth like this: (note 5 * 10^14 is expected total supply of core)
```
		{
			rate:   "0.01",
			issuer: issuer,
			senders: map[string]int64{
				account[0]: 100 * 10^14,
				account[1]: 300 * 10 ^ 15,
				account[2]: 500 * 10^16,
			},
			...
		},

```

3. trick in this test is that we have tricky numbers and the same amount sent to issuer in input & output so this numbers shouldn't cause any rounding in calculations
```
		{
			rate:   "0.01",
			issuer: issuer,
			senders: map[string]int64{
				issuer: 2100,
				account[0]: 1100,
				account[1]: 1700,
				account[2]: 1900,
			},
			receivers: map[string]int64{
				issuer: 2100,
                                account[0]: 300,
                                account[1]: 1100,
                                account[2]: 3300,
			},
			shares: map[string]int64{
                                account[0]: 11,
				account[1]: 17,
				account[2]: 19,
                  },
		},

```
4. test of high rate `rate: "0.99"` or 0.9
___
*[`x/asset/ft/keeper/keeper_test.go` line 485 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLb0w9W-JI_YXDkblNG:-NLb0w9W-JI_YXDkblNH:b1vuroz) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L485)):*
> ```Go
> 			},
> 			receivers: map[string]int64{
> 				accounts[0]: 5,
> ```

minor: I would advice to use positive indexes of array for senders and negative for receivers so you have more or less realistic cases:
```
			senders: map[string]int64{
				accounts[1]: 400,
				accounts[2]: 600,
			},
			receivers: map[string]int64{
				accounts[-1]: 500,
				accounts[-2]: 500,
			},
```

doesn't affect much but makes them more relaistic
___
*[`x/asset/ft/keeper/keeper_test.go` line 619 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLb2zEY2EpF7qY_9VJs:-NLb2zEY2EpF7qY_9VJt:b-ot8n5u) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L619)):*
> ```Go
> 	ba := newBankAsserter(ctx, t, bankKeeper)
> 
> 	// issue 3 tokens
> ```

you issue & use just 2
___
*[`x/asset/ft/keeper/multisend.go` line 11 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLanwZ22gQkusV_UO7b:-NLanwZ22gQkusV_UO7c:b-jc9gck) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L11)):*
> ```Go
> 
> func (k Keeper) applyFeatures(ctx sdk.Context, inputs []banktypes.Input, outputs []banktypes.Output) error {
> 	inputGroup := make(groupedByDenomAccountBalances)
> ```

minor: groupedInputs & groupedOutputs ?
___
*[`x/asset/ft/keeper/multisend.go` line 16 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLapP6M7oQY0eIrLKlH:-NLapP6M7oQY0eIrLKlI:b3b9ozk) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L16)):*
> ```Go
> 	}
> 
> 	outputGroup := make(groupedByDenomAccountBalances)
> ```

minor: 
Just a question from me.
What is the benefit of using make over `:=` or `var` ?
___
*[`x/asset/ft/keeper/multisend.go` line 24 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLamztIApM6S0H6tF36:-NLamztJ6ZgO1ahQYj4S:b-ozqcbu) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L24)):*
> ```Go
> }
> 
> type accountBalanceMap map[string]sdk.Int
> ```

it is not really a balance.
I would name it `accountOperationMap` & what is more you name this ops later
and the next type `groupedByDenomAccountOperations`
___
*[`x/asset/ft/keeper/multisend.go` line 30 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLanmna2mjbaYcAqwCV:-NLanmna2mjbaYcAqwCW:b-w0sx9z) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L30)):*
> ```Go
> func (g groupedByDenomAccountBalances) add(address string, coins sdk.Coins) {
> 	for _, coin := range coins {
> 		entry, ok := g[coin.Denom]
> ```

minor: entry is too general. What about `accountBalances`
___
*[`x/asset/ft/keeper/multisend.go` line 64 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLaoWHH2pmcYFqWuK0J:-NLaoWHIEsEAbOTRbz9f:bvyq8a8) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L64)):*
> ```Go
> 		for account, amount := range commissionShares {
> 			coins := sdk.NewCoins(sdk.NewCoin(ftd.Denom, amount))
> 			issuer := sdk.MustAccAddressFromBech32(ftd.Issuer)
> ```

minor: the same issuer is 'calculated' n times in the loop. What about moving it into outer loop ?
___
*[`x/asset/ft/keeper/multisend.go` line 87 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLatrJn5U5EQ8PldBlJ:-NLatrJn5U5EQ8PldBlK:bvc87xj) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L87)):*
> ```Go
> 
> // CalculateRateShares calculates how the burn or commission share amount should be split between different parties
> func CalculateRateShares(rate sdk.Dec, issuer string, inOps, outOps accountBalanceMap) map[string]sdk.Int {
> ```

should this method be exposed ?
___
*[`x/asset/ft/keeper/multisend.go` line 88 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/321#-NLaq1XqA5cVnm3_p94P:-NLaq1XqA5cVnm3_p94Q:b-hq9g0d) ([raw file](https://github.com/coreumfoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L88)):*
> ```Go
> // CalculateRateShares calculates how the burn or commission share amount should be split between different parties
> func CalculateRateShares(rate sdk.Dec, issuer string, inOps, outOps accountBalanceMap) map[string]sdk.Int {
> 	// The algorithm is as following. we first get the minimum of total inputs and outputs which are not
> ```

I suggest to improve the comment. Maybe we should move it to beginning of file

```
Since burning & send commission are not applied when sending to/from FT issuer we can't simply apply original burn rate or send commission rate when bank multisend with issuer in inputs or outputs.
To recalculate new adjusted amount we split whole "commission" between all non-issuer senders proportionally to amount t [...]

2023-01-13 06:24 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: 5 of 6 files reviewed, 15 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`x/asset/ft/keeper/keeper_test.go` line 590 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLdmML23pXdvL8qqO__:-NLdmML23pXdvL8qqO_a:b-3m4vp4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L590)):*
> ```Go
> 		t.Run(name, func(t *testing.T) {
> 			assertT := assert.New(t)
> 			issuer := sdk.MustAccAddressFromBech32(tc.issuer)
> ```

How about do it once ?


<!-- Sent from Reviewable.io -->

2023-01-13 06:24 UTC, dzmitryhil reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68 and @silverspase)



<!-- Sent from Reviewable.io -->

2023-01-13 08:49 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 462 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLavbHh2rkJNoPC8VQo:-NLds3n4CceOuWFeEBut:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L462)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we drop this field since it is the same everywhere ?
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_test.go` line 466 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLayY4iE6d4ppToruiu:-NLeB9tU98fecmdhCkmh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L466)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

another test cases to be added:

1. test rounding of small numbers
```
		{
			rate:   "0.1",
			issuer: issuer,
			senders: map[string]int64{
				account[0]: 1,
				account[1]: 2,
				account[2]: 9,
			},
			receivers: map[string]int64{
				accounts[0]: 12,
			},
			shares: map[string]int64{
                                account[0]: 1,
				account[1]: 1,
				account[2]: 1,
                  },
		},

```

2. test huge numbers. Since we have multiplication of amount * sum(amounts) I'm afraid of int overflow. Smth like this: (note 5 * 10^14 is expected total supply of core)
```
		{
			rate:   "0.01",
			issuer: issuer,
			senders: map[string]int64{
				account[0]: 100 * 10^14,
				account[1]: 300 * 10 ^ 15,
				account[2]: 500 * 10^16,
			},
			...
		},

```

3. trick in this test is that we have tricky numbers and the same amount sent to issuer in input & output so this numbers shouldn't cause any rounding in calculations
```
		{
			rate:   "0.01",
			issuer: issuer,
			senders: map[string]int64{
				issuer: 2100,
				account[0]: 1100,
				account[1]: 1700,
				account[2]: 1900,
			},
			receivers: map[string]int64{
				issuer: 2100,
                                account[0]: 300,
                                account[1]: 1100,
                                account[2]: 3300,
			},
			shares: map[string]int64{
                                account[0]: 11,
				account[1]: 17,
				account[2]: 19,
                  },
		},

```
4. test of high rate `rate: "0.99"` or 0.9
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_test.go` line 485 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLb0w9W-JI_YXDkblNG:-NLeJOBj0dp3kUwGG9s6:b-j40lue) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L485)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: I would advice to use positive indexes of array for senders and negative for receivers so you have more or less realistic cases:
```
			senders: map[string]int64{
				accounts[1]: 400,
				accounts[2]: 600,
			},
			receivers: map[string]int64{
				accounts[-1]: 500,
				accounts[-2]: 500,
			},
```

doesn't affect much but makes them more relaistic
</blockquote></details>

negative indexes are not allowed, i used random addresses for receivers to achieve the same thing. 
___
*[`x/asset/ft/keeper/keeper_test.go` line 590 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLdmML23pXdvL8qqO__:-NLeCKZPAYgbwLKa8EJd:blj9ecj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L590)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about do it once ?
</blockquote></details>

removed this
___
*[`x/asset/ft/keeper/keeper_test.go` line 619 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLb2zEY2EpF7qY_9VJs:-NLeCT_jErJFY07_Fllj:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/keeper_test.go#L619)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you issue & use just 2
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/multisend.go` line 11 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLanwZ22gQkusV_UO7b:-NLeCbm-5SSLdKpFKjN5:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: groupedInputs & groupedOutputs ?
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/multisend.go` line 16 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLapP6M7oQY0eIrLKlH:-NLeCeMVDYFtfmFvUkWd:bt5mr1w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: 
Just a question from me.
What is the benefit of using make over `:=` or `var` ?
</blockquote></details>

make and `:=` initialize the map, while var leaves it as nil. there is no actual benefit though. Dima commented that he prefers make, I personally prefer `:=` 
___
*[`x/asset/ft/keeper/multisend.go` line 24 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLamztIApM6S0H6tF36:-NLeDGP7Ebl6yr2f9Vui:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it is not really a balance.
I would name it `accountOperationMap` & what is more you name this ops later
and the next type `groupedByDenomAccountOperations`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/multisend.go` line 30 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLanmna2mjbaYcAqwCV:-NLeDMGd3DtG1PHV_loA:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: entry is too general. What about `accountBalances`
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/multisend.go` line 64 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLaoWHH2pmcYFqWuK0J:-NLeF9Ei150MPkU_Qx-X:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: the same issuer is 'calculated' n times in the loop. What about moving it into outer loop ?
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/multisend.go` line 87 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLatrJn5U5EQ8PldBlJ:-NLeFB-P8jfYobMC4CMV:bn5ez89) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L87)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should this method be exposed ?
</blockquote></details>

I only need it for tests. 
___
*[`x/asset/ft/keeper/multisend.go` line 88 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLaq1XqA5cVnm3_p94P:-NLeGLsi6KLH4PqB8Krc:bkddnm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L88)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I sug [...]

2023-01-13 12:40 UTC, dzmitryhil reviewed
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: all files reviewed, 11 unresolved discussions (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-13 13:49 UTC, ysv approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`x/asset/ft/keeper/multisend.go` line 16 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/321#-NLapP6M7oQY0eIrLKlH:-NLfNagJ3wVwPOTY_n1D:b-chey27) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8358bd5f34b2d392cb4e7103eace8e31bcf60ca3/x/asset/ft/keeper/multisend.go#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

make and `:=` initialize the map, while var leaves it as nil. there is no actual benefit though. Dima commented that he prefers make, I personally prefer `:=` 
</blockquote></details>

I also prefer := I think unless we have specific size but ok


<!-- Sent from Reviewable.io -->

2023-01-13 14:39 UTC, dzmitryhil approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-01-13 15:02 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-01-13 15:03 UTC, merged