implemented nft freezing
CoreumFoundation/coreum pull request #347
Opened 2023-01-17 13:38 UTC by miladz68

2023-01-18 11:53 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 0 of 28 files reviewed, 25 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 540 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3eE41BwWcFVNtGv72:-NM3eE41BwWcFVNtGv73:bx2tcn7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L540)):*
> ```Go
> 	requireT := require.New(t)
> 	issuer := chain.GenAccount()
> 	receiver1 := chain.GenAccount()
> ```

Minor: `receiver` -> `recipient`. 
___
*[`integration-tests/modules/assetnft_test.go` line 572 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3f7h_A-bw-DJ2Jq9x:-NM3f7h_A-bw-DJ2Jq9y:bd7twc5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L572)):*
> ```Go
> 		ctx,
> 		chain.ClientContext.WithFromAddress(issuer),
> 		chain.TxFactory().WithGas(chain.GasLimitByMsgs(issueMsg)),
> ```

No need to that gas for the message which are already tested (same comment for all such messages, Issue, Mint, Burn).
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3YIsE1N0s0sbfYAAK:-NM3YIsE1N0s0sbfYAAL:b8ymvwi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
> ```Go
> 
> // JoinKeysWithLengthMany is similar to JoinKeysWithLength but gets a list of keys and prefixes all of them
> func JoinKeysWithLengthMany(keys ...[]byte) []byte {
> ```

Actually you can rename it to the `JoinKeysWithLength` and remove previous `JoinKeysWithLength`. 
But move the comment here please.
___
*[`pkg/store/key.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3Y_Rd8HfsX4X1yH8E:-NM3Y_Rd8HfsX4X1yH8F:bbieqzv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L46)):*
> ```Go
> 			return compositeKey
> 		}
> 		if bzLen > maxKeyLen {
> ```

Why that length is the max?  And why panic?
___
*[`pkg/store/key.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3awj91FUejdt8Hh_x:-NM3awj91FUejdt8Hh_y:bunshd6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L58)):*
> ```Go
> 
> // ParseJoinKeysWithLengthMany parses all the length prefixed keys, put together by JoinKeysWithLengthMany
> func ParseJoinKeysWithLengthMany(key []byte) [][]byte {
> ```

`ParseJoinedKeys` ?
___
*[`pkg/store/key.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3aF7d7SHGIfr4buIg:-NM3aF7e5FBTZ_b0SkjZ:b-7c0cm2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L66)):*
> ```Go
> 	startBound := 1
> 	for {
> 		addrLen := key[startBound-1]
> ```

Why addrLen ?
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3VIUm7oyNXqRJ1p26:-NM3VIUm7oyNXqRJ1p27:b-eoembn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/genesis.proto#L20)):*
> ```protobuf
> }
> 
> message FrozenNFT {
> ```

Maybe we can call it `ClassNFTs` to reuse later?



_Code quote:_
```protobuf
FrozenNFT
```
___
*[`proto/coreum/asset/nft/v1/query.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_LN3DrW1DeWP_Eyn:-NM3_LN3DrW1DeWP_Eyo:b-fbdlp9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L17)):*
> ```protobuf
>     option (google.api.http).get = "/coreum/asset/nft/v1/classes/{id}";
>   }
> ```

Do we need get frozen by call with the pagination?
___
*[`proto/coreum/asset/nft/v1/query.proto` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3gQarAVe2EtsqRape:-NM3gQarAVe2EtsqRapf:b-ya42rl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L19)):*
> ```protobuf
> 
>   // Frozen queries to check if an NFT is frozen or not.
>   rpc Frozen (QueryFrozenRequest) returns (QueryFrozenResponse) {
> ```

Actually, as a user, I would prefer to query full NFT info. So, probably we don't need that query and CLI as well, but need the query with full NFT info including the whitelisting in the future. It can be even moved to a separate task.
@ysv , @miladz68 ?
___
*[`proto/coreum/asset/nft/v1/query.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3VaM6ElRhVnW9bWlY:-NM3VaM6ElRhVnW9bWlZ:b-dxoilb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L20)):*
> ```protobuf
>   // Frozen queries to check if an NFT is frozen or not.
>   rpc Frozen (QueryFrozenRequest) returns (QueryFrozenResponse) {
>     option (google.api.http).get = "/coreum/asset/nft/v1/nfts/{id}/frozen";
> ```

The URL seems wrong.

That might be a valid example:`/coreum/asset/nft/v1/classes/{class_id}/nfts/{id}/frozen`

But pay attention that `[(gogoproto.customname) = "ClassID"];` won't work, because the `(google.api.http)` ignores it.
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 22 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3W4jL3qB80g3Vd7eU:-NM3W4jL3qB80g3Vd7eV:b-4geq25) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/tx.proto#L22)):*
> ```protobuf
>   // Burn burns the existing non-fungible token in the class.
>   rpc Burn(MsgBurn) returns (EmptyResponse);
>   // Freeze freezes an nft, if such feature is enabled on it, so it cannot be sent
> ```

Let's not add info about the features, let's just keep the action desription.
___
*[`x/asset/nft/client/cli/tx_test.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3gtqE5j-KlkbaMrln:-NM3gtqE5j-KlkbaMrlo:brm34gx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/client/cli/tx_test.go#L48)):*
> ```Go
> 	testNetwork := network.New(t)
> 
> 	symbol := "nft" + uuid.NewString()[:4]
> ```

I would propose you to move the issuance and mint to separate func, similar like we did in the FT, since you need to issue quite often for almost each CLI test.
___
*[`x/asset/nft/keeper/freezing_store.go` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3XDUu4SqKiHmpH_w-:-NM3XDUu4SqKiHmpH_w0:b-kuiqy5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L12)):*
> ```Go
> )
> 
> func newFreezingFeatureStore(kvstore sdk.KVStore) nftFreezingStore {
> ```

Why did you go here with the approach different from theft? IMO better to follow the same.
That code won't reduce the duplication since you will have to the similar for the whitesisting.
___
*[`x/asset/nft/keeper/freezing_store.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_dXn-donK6t83zHn:-NM3_dXn-donK6t83zHo:b-pz6n6d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L23)):*
> ```Go
> 
> func (s nftFreezingStore) freeze(classID, nftID string) {
> 	s.store.Set(s.genCompositeKey(classID, nftID), []byte{0x1})
> ```

[]byte{0x1} should be moved to the contant, and you can use `[]byte{0x00}` instead.
___
*[`x/asset/nft/keeper/freezing_store.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3Xdah22PcV7ecDvcY:-NM3Xdah22PcV7ecDvcZ:b-cwlu32) ([raw [...]

2023-01-18 11:54 UTC, dzmitryhil reviewed
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 25 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-18 18:22 UTC, ysv requested changes
> Reviewed 27 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 36 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 572 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3f7h_A-bw-DJ2Jq9x:-NM567ctDTM4nFPAKbv9:b-tiaxxh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L572)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

No need to that gas for the message which are already tested (same comment for all such messages, Issue, Mint, Burn).
</blockquote></details>

didn't get your comment



_Code quote:_
```Go
tx.BroadcastTx
```
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4x7LL8Kl8kQenhkMB:-NM4x7LL8Kl8kQenhkMC:b-t0c1sd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
> ```Go
> 
> // JoinKeysWithLengthMany is similar to JoinKeysWithLength but gets a list of keys and prefixes all of them
> func JoinKeysWithLengthMany(keys ...[]byte) []byte {
> ```

I thought that we deprecated this method and will not use it at all
Or there is finally a use case for it in NFTs ?
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3YIsE1N0s0sbfYAAK:-NM4yT0jD6kaZz1JbvFj:b2nw81y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually you can rename it to the `JoinKeysWithLength` and remove previous `JoinKeysWithLength`. 
But move the comment here please.
</blockquote></details>

I agree lets keep 1 version
___
*[`pkg/store/key.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3Y_Rd8HfsX4X1yH8E:-NM4xxKc4W1t7eBz1nUd:bmun2bh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why that length is the max?  And why panic?
</blockquote></details>

probably because of limitation in cosmos sdk store ?
But I agree using panic here is not a good option
___
*[`pkg/store/key_test.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4yiSfE2jnyMrd1AFR:-NM4yiSfE2jnyMrd1AFS:b3b5s4u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key_test.go#L42)):*
> ```Go
> }
> 
> func TestJoinKeysWithLengthMany(t *testing.T) {
> ```

not enough tests IMO
___
*[`proto/coreum/asset/nft/v1/event.proto` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4zF4b5uaOG_pDegWx:-NM4zF4b5uaOG_pDegWy:b-uvo7qg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/event.proto#L25)):*
> ```protobuf
>   string class_id = 1;
>   string id       = 2;
>   string owner    = 3;
> ```

in FTs we use `string account = 1;` I propose to keep the name
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3VIUm7oyNXqRJ1p26:-NM4zKBI9kWCtJwjnpd6:b-fobayn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/genesis.proto#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Maybe we can call it `ClassNFTs` to reuse later?
</blockquote></details>

I agree 
I think we can possibly reuse it for whitelisting e.g
___
*[`proto/coreum/asset/nft/v1/query.proto` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3gQarAVe2EtsqRape:-NM4ze9u7_Gb1BBQarpT:becwtdc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, as a user, I would prefer to query full NFT info. So, probably we don't need that query and CLI as well, but need the query with full NFT info including the whitelisting in the future. It can be even moved to a separate task.
@ysv , @miladz68 ?
</blockquote></details>

Needs discussion
___
*[`proto/coreum/asset/nft/v1/query.proto` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4ztIKBMdIxunzzy08:-NM4ztIKBMdIxunzzy09:b3vgv8f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L34)):*
> ```protobuf
> }
> 
> message QueryFrozenRequest {
> ```

IMO this type is very reusable since it is sort of global NFT ID. I propose to name it smth like `GlobalNFTID` and reuse this type everywhere (e.g in genesis  `repeated FrozenNFT frozen_nfts = 3 [(gogoproto.nullable) = false];` also in a lot of funcs we pass these ids as 2 separate args while logically they are a single thingy)

But I'm sure that other use cases for it will appear soon if they are not there yet
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 22 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3W4jL3qB80g3Vd7eU:-NM5-pjP0l98rLizLvMb:b-dusdh8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/tx.proto#L22)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's not add info about the features, let's just keep the action desription.
</blockquote></details>

also nft -> NFT ?
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM500Ay-iRsjZXeFu8E:-NM500Ay-iRsjZXeFu8F:b-oteou0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/tx.proto#L51)):*
> ```protobuf
> 
> // MsgBurn defines message for the Burn method.
> message MsgBurn {
> ```

that is so unfortunate that we have 3 identical structs
Isn't it possible to define one and reuse it.
Like in golang:
```
type A struct {
}

type a1 = A
type a2 = A
...
```
___
*[`x/asset/nft/keeper/freezing_store.go` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3XDUu4SqKiHmpH_w-:-NM51jJk31SG7lVnqup2:bxzqwnn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L12)):*
> theft

initially didn't get which `theft` you are talking about :sweat_smile: 



I we will probably not be able to make the same trick as we did for FT since here structure for freeze (classID,nftID) vs whitelist(classID,nftID,address) is different
___
*[`x/asset/nft/keeper/freezing_store.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_dXn-donK6t83zHn:-NM51vK412eu3PvdCVHc:bb6h61l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

[]byte{0x1} should be moved to the contant, and you can use `[]byte{0x00}` instead.
</blockquote></details>

100%
___
*[`x/asset/nft/keeper/freezing_store.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3Xdah22PcV7ecDvcY:-NM52Mpw10gqgehRapdG:b-zew1zd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L60)):*
<details><summary><i>Previously, dzmi [...]

2023-01-19 08:03 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 36 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 572 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3f7h_A-bw-DJ2Jq9x:-NM81zz2D7bYy9fdRiTK:b3ad6v8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L572)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

didn't get your comment
</blockquote></details>

No need to `test` that


<!-- Sent from Reviewable.io -->

2023-01-19 13:26 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 12 of 30 files reviewed, 35 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 540 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3eE41BwWcFVNtGv72:-NM8RIZb3dpktPgwfO4d:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L540)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Minor: `receiver` -> `recipient`. 
</blockquote></details>

Done
___
*[`integration-tests/modules/assetnft_test.go` line 572 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3f7h_A-bw-DJ2Jq9x:-NM8RT7kD63XoDHPP3g5:b-3yg3ge) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L572)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

No need to `test` that
</blockquote></details>

But we are not testing that 
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3YIsE1N0s0sbfYAAK:-NM8RxoK2K_Bfn8H070w:bchsdi2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree lets keep 1 version
</blockquote></details>

let's discuss after the daily. 
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4x7LL8Kl8kQenhkMB:-NM8S1Ha26mkbWogp2u5:bnr1t75) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought that we deprecated this method and will not use it at all
Or there is finally a use case for it in NFTs ?
</blockquote></details>

Well I can think about different ways of doing this, but the old methods used in FT, will not cut it here. 
___
*[`pkg/store/key.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3Y_Rd8HfsX4X1yH8E:-NM8Su761mTxH_8ZDebs:b-tmdpnk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

probably because of limitation in cosmos sdk store ?
But I agree using panic here is not a good option
</blockquote></details>

the max length is 255 since that is the maximum value you can store in single byte. There is also a comment saying this. And Panic is here, since this problem should be handled before we deploy a binary. we should never get to this if statement, and if we do, panic seems a reasonable response. 
___
*[`pkg/store/key.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3awj91FUejdt8Hh_x:-NM8ToxX1iIQd7SMTt10:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`ParseJoinedKeys` ?
</blockquote></details>

Done.
___
*[`pkg/store/key.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3aF7d7SHGIfr4buIg:-NM8TvZ8BJYQwvUb6VaZ:b-v7wpl0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L66)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why addrLen ?
</blockquote></details>

renamed to KeyLen
___
*[`pkg/store/key_test.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4yiSfE2jnyMrd1AFR:-NM8U9J4Bq9ST3TVYiwJ:bdgw3je) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key_test.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not enough tests IMO
</blockquote></details>

We can add more tests once we decide we want to go with this approach. 
___
*[`proto/coreum/asset/nft/v1/event.proto` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4zF4b5uaOG_pDegWx:-NM8UJEV05_SVoQbgmw1:b-dnrqka) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/event.proto#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

in FTs we use `string account = 1;` I propose to keep the name
</blockquote></details>

I think we should not try to unify FTs and NFTs. The nft module is using owner, so we should try to stay close to the nft module, and not to asset/ft. 
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3VIUm7oyNXqRJ1p26:-NM8UufB65tJrFZqu7iT:b-fxtz21) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/genesis.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree 
I think we can possibly reuse it for whitelisting e.g
</blockquote></details>

We will not be able to reuse it for whitelisting as we have discussed. I think let's move forward and if we see that the structure can be reused, we can refactor.
___
*[`proto/coreum/asset/nft/v1/query.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_LN3DrW1DeWP_Eyn:-NM8VL1X4XF7yTQxy5aG:bumk7ws) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need get frozen by call with the pagination?
</blockquote></details>

I cannot think of a use case.
___
*[`proto/coreum/asset/nft/v1/query.proto` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3gQarAVe2EtsqRape:-NM99tmx7dizofFFy1rw:b-5e5lsu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Needs discussion
</blockquote></details>

let's discuss
___
*[`proto/coreum/asset/nft/v1/query.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3VaM6ElRhVnW9bWlY:-NM8XAvJ-4HM8Evuyffq:bxvskdn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The URL seems wrong.

That might be a valid example:`/coreum/asset/nft/v1/classes/{class_id}/nfts/{id}/frozen`

But pay attention that `[(gogoproto.customname) = "ClassID"];` won't work, because the `(google.api.http)` ignores it.
</blockquote></details>

good catch, Fixed.
___
*[`proto/coreum/asset/nft/v1/query.proto` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4ztIKBMdIxunzzy08:-NM8XKEmB7QWAIkZYupq:bdxb9u8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO this type is very reusable since it is sort of global NFT ID. I propose to name it smth like `GlobalNFTID` and reuse this type everywhere (e.g in genesis  `repeated FrozenNFT frozen_nfts = 3 [(gogoproto.nullable) = false];` also in a lot  [...]

2023-01-20 08:15 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 12 of 30 files reviewed, 23 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 572 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3f7h_A-bw-DJ2Jq9x:-NMDCavD6riWQUgVwmp5:b-1c7rpg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L572)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

But we are not testing that 
</blockquote></details>

Check the `TestAssetFTIssue`, `TestAssetFTMint`, and `TestAssetFTBurn` tests. 



_Code quote:_
```Go
		chain.TxFactory().WithGas(chain.GasLimitByMsgs(issueMsg)),
```
___
*[`integration-tests/modules/assetnft_test.go` line 533 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDEbLm0Kzs2jqsoQjU:-NMDEbLn4GcYe_2UbONV:b-r5jcdi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0683a226a5ad9ff6ed3e9d7f5aaf1e4e2f330800/integration-tests/modules/assetnft_test.go#L533)):*
> ```Go
> 
> // TestAssetNFTFreeze tests non-fungible token freezing.
> func TestAssetNFTFreeze(t *testing.T) {
> ```

Add the test for the `Queries` here as well, because the keeper can be written correctly, but the mistake might be in the Query server.
___
*[`x/asset/nft/keeper/keeper.go` line 258 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3YsDd4rs88xi_kq5z:-NMDDVbEAXdQ946gGM1_:b-kb5m82) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/keeper.go#L258)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But you still have the AllFrozen, let's better remove it and pass the `query.MaxLimit` from the genesis.
___
*[`x/asset/nft/keeper/keeper_test.go` line 374 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3dFfM7u0LDpnw1Zms:-NMDEK5y7XrGteH4glfr:b-biqkji) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/keeper_test.go#L374)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Tests aded. 
</blockquote></details>

My part is resolved. 
@ysv check yours.


<!-- Sent from Reviewable.io -->

2023-01-20 08:16 UTC, dzmitryhil reviewed
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 23 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-20 10:21 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 22 of 30 files reviewed, 23 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 572 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3f7h_A-bw-DJ2Jq9x:-NMDQIfkBav9KEQaJ3b_:b-sfhr4x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/integration-tests/modules/assetnft_test.go#L572)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check the `TestAssetFTIssue`, `TestAssetFTMint`, and `TestAssetFTBurn` tests. 
</blockquote></details>

Yes we test them there, but we are not testing gas used for mint here. Here we only check gas used for freeze/unfreeze, which we should do 
___
*[`integration-tests/modules/assetnft_test.go` line 533 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDEbLm0Kzs2jqsoQjU:-NMDPJNqEJvxPwnHZiWz:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0683a226a5ad9ff6ed3e9d7f5aaf1e4e2f330800/integration-tests/modules/assetnft_test.go#L533)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Add the test for the `Queries` here as well, because the keeper can be written correctly, but the mistake might be in the Query server.
</blockquote></details>

Done.
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3YIsE1N0s0sbfYAAK:-NMDY75cBT_cLlzQ_XwR:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss after the daily. 
</blockquote></details>

Done
___
*[`pkg/store/key.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4x7LL8Kl8kQenhkMB:-NMDadYJ8xPoHMTGy3MJ:b-4txl9t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Well I can think about different ways of doing this, but the old methods used in FT, will not cut it here. 
</blockquote></details>

we agreed on the call to keep a version of that function, since it is not needed
___
*[`pkg/store/key.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3Y_Rd8HfsX4X1yH8E:-NMDajzhBPiCV6O9tJUa:bhcck8o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key.go#L46)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the max length is 255 since that is the maximum value you can store in single byte. There is also a comment saying this. And Panic is here, since this problem should be handled before we deploy a binary. we should never get to this if statement, and if we do, panic seems a reasonable response. 
</blockquote></details>

Discussed on the call 
___
*[`pkg/store/key_test.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4yiSfE2jnyMrd1AFR:-NMDaoFQ5Ob_JQuD6bIU:b1nwm4k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key_test.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

We can add more tests once we decide we want to go with this approach. 
</blockquote></details>

added a few more. propose more scenarios if you can think of any. 
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3VIUm7oyNXqRJ1p26:-NMDawg48jMbIqs8tKd-:bg5si5k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/genesis.proto#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

We will not be able to reuse it for whitelisting as we have discussed. I think let's move forward and if we see that the structure can be reused, we can refactor.
</blockquote></details>

Discussed in the call, we decided not to change anything here. 
___
*[`proto/coreum/asset/nft/v1/query.proto` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4ztIKBMdIxunzzy08:-NMDb7Uw1VUuMd9kGk8u:b-4gicfn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/query.proto#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree with this, I called it NFTUniqueID, and then we decided to remove it after we discussed it with Dima. but needs discussion. 
</blockquote></details>

Decided not to this on the call. 
___
*[`x/asset/nft/keeper/keeper.go` line 258 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3YsDd4rs88xi_kq5z:-NMDSywA2wF3ktEIgfdR:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/keeper.go#L258)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But you still have the AllFrozen, let's better remove it and pass the `query.MaxLimit` from the genesis.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper_test.go` line 374 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3dFfM7u0LDpnw1Zms:-NMDT4JK-cOTBDa-yvRc:b-amlf8d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/keeper_test.go#L374)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

My part is resolved. 
@ysv check yours.
</blockquote></details>

@ysv please check. 
___
*[`x/asset/nft/keeper/freezing_store.go` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3XDUu4SqKiHmpH_w-:-NMDbDgp8W8UKnEe2OfN:b-bqzchy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L12)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is a simple abstraction to store and load freezing flag. If we don't have this abstraction, then we will have to these actions inside the functions. 
</blockquote></details>

removed the structure as we discussed on the call. 


<!-- Sent from Reviewable.io -->

2023-01-20 11:19 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 22 of 30 files reviewed, 16 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/event.proto` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4zF4b5uaOG_pDegWx:-NMDtikE-WvP7a1ZovY3:byxjkzr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/event.proto#L25)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we should not try to unify FTs and NFTs. The nft module is using owner, so we should try to stay close to the nft module, and not to asset/ft. 
</blockquote></details>

I agree with @miladz68 the owner is better here.


<!-- Sent from Reviewable.io -->

2023-01-20 11:43 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 22 of 30 files reviewed, 21 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 17 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDyW3k4B61VSrKtGF3:-NMDyW3k4B61VSrKtGF4:b5r3mbq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/proto/coreum/asset/nft/v1/genesis.proto#L17)):*
> ```protobuf
>   // class_definitions keep the non-fungible token class definitions state
>   repeated ClassDefinition class_definitions = 2 [(gogoproto.nullable) = false];
>   repeated FrozenNFT frozen_nfts = 3 [(gogoproto.nullable) = false];
> ```

How about add the `go name` as `FrozenNFTs`, since the after the code generation current it `FrozenNfts`.
___
*[`x/asset/nft/client/cli/query_test.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDw-t317JK1CocAMuE:-NMDw-t317JK1CocAMuF:b-llasne) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/client/cli/query_test.go#L58)):*
> ```Go
> }
> 
> func stringify[S fmt.Stringer](s S, _ int) string {
> ```

Why do you need that func if you use it just once?
___
*[`x/asset/nft/keeper/keeper.go` line 223 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDxu1p3ixxHcTzIRMS:-NMDxu1p3ixxHcTzIRMT:bjdyb5a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/keeper/keeper.go#L223)):*
> ```Go
> 		return err
> 	}
> 	store := prefix.NewStore(ctx.KVStore(k.storeKey), types.NFTFreezingKeyPrefix)
> ```

Can you simplify it and add the ` types.NFTFreezingKeyPrefix` in the `CreateFreezingKey`? Same comment for their such palces.
___
*[`x/asset/nft/types/keys.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDvN-93kJ1HwrjeR3o:-NMDvN-93kJ1HwrjeR3p:b-d8w19d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/types/keys.go#L45)):*
> ```Go
> 	parsedKeys, err := store.ParseLengthPrefixedKeys(key)
> 	if err != nil {
> 		return
> ```

Why do you ignore it?
___
*[`x/asset/nft/types/msgs_test.go` line 309 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDz3Oo-JRmkJFEfXZv:-NMDz3Oo-JRmkJFEfXZw:b-5fk4h8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/types/msgs_test.go#L309)):*
> ```Go
> }
> 
> //nolint:dupl // we simply don't care
> ```

Let's not add such comment :-) Same for other tests.
___
*[`x/asset/nft/keeper/freezing_store.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_dXn-donK6t83zHn:-NMDwS_I1rFOulkt4OSf:bmhc2xp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

bytes cannot be assigned as constants in go. 
0x00 has been traditionally equivalent to false. using 0x00 to indicate true value will only lead to confusion, without any benefits. 
</blockquote></details>

Sure we need variable not constant. :-)
But what regards the `0x00 ` I'm ok with `0x01` as well, but we need to go with same in FT and NFT.


<!-- Sent from Reviewable.io -->

2023-01-23 11:57 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/types/keys.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDvN-93kJ1HwrjeR3o:-NMTU79h3MdYuK7LlXA9:b-n7lx4v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/types/keys.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

actually it is not clear here if it is ignored or named return value assigned here or new err variable created

`parsedKeys, err := store.ParseLengthPrefixedKeys(key)`

That is why I insist on not using named return values
</blockquote></details>

We shoudn't ignore that err, better to wrap and return.


<!-- Sent from Reviewable.io -->

2023-01-23 12:33 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 18 of 36 files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/store/key.go` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMEKUwn57k6t5BH32cM:-NMSxo4L2tINy0dSjFvB:bbxexnf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/pkg/store/key.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what does `bzLen` mean ? 
maybe keyLen ?
</blockquote></details>

bzLen the wording the comsos sdk is using for similar code. it stands for `byteslength`
I will use keyLen as you suggested. 
___
*[`pkg/store/key.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMEKM1u-1e8nAAtbjuF:-NMSyTpE-9Jp3IW-gQHA:bjm914z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/pkg/store/key.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
having index of empty key might be beneficial here
</blockquote></details>

I think not. Empty key have no value. AT least I cannot think of a use case for it. so we should avoid that. 
___
*[`pkg/store/key_test.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4yiSfE2jnyMrd1AFR:-NMTL-AjDL6Tygpk0xcd:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/pkg/store/key_test.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

- add scenario with 256 bytes in a single key. expectError: true
- key which starts & ends with number
- multiple long keys e.g  3*254 bytes
</blockquote></details>

Done.
___
*[`proto/coreum/asset/nft/v1/event.proto` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM4zF4b5uaOG_pDegWx:-NMT72QdEAgECvCZ9z08:b6fyvtl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/proto/coreum/asset/nft/v1/event.proto#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets then use owner if FTs also ?
Or you mean that freezing is logically different ?
</blockquote></details>

It is logically different as you mentioned. in FT the token cannot have an owner, but an account have have a balance of FT token. but NFT token has an owner. 
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 17 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDyW3k4B61VSrKtGF3:-NMTMXyCEdgjrjcwZos4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/proto/coreum/asset/nft/v1/genesis.proto#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about add the `go name` as `FrozenNFTs`, since the after the code generation current it `FrozenNfts`.
</blockquote></details>

Done.
___
*[`x/asset/nft/client/cli/query_test.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDw-t317JK1CocAMuE:-NMTNSvJBq5ZNayVaOfr:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/client/cli/query_test.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

probably not needed
</blockquote></details>

Done.
___
*[`x/asset/nft/client/cli/tx_test.go` line 62 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NME7oIl-3t9-UP94g5d:-NMTORmv4TPY4Vj00lQ2:b-f2n23) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/client/cli/tx_test.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this nosnakecase is so annoying. Should we disable it ?

I have checked and this linter is deprecated
</blockquote></details>

let's disable it, but it will belong to another task. 
___
*[`x/asset/nft/keeper/keeper.go` line 223 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDxu1p3ixxHcTzIRMS:-NMTP2yq91WeMgRjk1xh:b7al52t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/keeper/keeper.go#L223)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can you simplify it and add the ` types.NFTFreezingKeyPrefix` in the `CreateFreezingKey`? Same comment for their such palces.
</blockquote></details>

My thinking is that you create a prefix store with a simple prefix, and use a key to store/get the value. it might be more code but I think it is simpler to reason about than doing both operations in single function.
___
*[`x/asset/nft/keeper/keeper_test.go` line 358 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3c9Rn5np-M8L_t6Yb:-NMTXNt00cYIvb1ErVVH:b-46dp74) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/keeper_test.go#L358)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't see the changes in other files

can you pls check them ?

![Screenshot 2023-01-20 at 13.07.42.png](https://files.reviewableusercontent.io/images/reviewable/19859122/Ap4bd11Df6pJMDIXoUJgU9PC/Screenshot%202023-01-20%20at%2013.07.42.png)
Screenshot 2023-01-20 at 13.07.42
</blockquote></details>

I thought you only meant the code I introduced in this PR. I will look into all files. 
___
*[`x/asset/nft/keeper/keeper_test.go` line 355 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NME8v571qzJDjbPj7uc:-NMTX1Oo1kIgQNal2L75:b6b01b5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/keeper/keeper_test.go#L355)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does this work ?
 IsFrozen returns `bool & error` isn't it ?
</blockquote></details>

It works, maybe bacause True fuctions accepts 2 args and the second one is variardic. Anyways, fixed it. 
___
*[`x/asset/nft/types/keys.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDvN-93kJ1HwrjeR3o:-NMTY1PG3bBHvgvf8Ah0:bydwnbi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/types/keys.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We shoudn't ignore that err, better to wrap and return.
</blockquote></details>

Removed named return. 
___
*[`x/asset/nft/types/msgs_test.go` line 309 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDz3Oo-JRmkJFEfXZv:-NMTYYGHDk4ioG6sf5K9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/types/msgs_test.go#L309)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I absolutely agree 
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/freezing_store.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_dXn-donK6t83zHn:-NMTZ9uN477eTiCYmNI5:b7mmhww) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

then pls make change on FT also we have to follow the same logic. Lets assinge cost to 0x01 there also
</blockquote></details>

I honestly see no benefit in defining a global variable that will only be used once, But I will do this. regarding the FT part. I will raise another PR to merge it quickly and include it in the testnet release.


<!-- Sent from Reviewable.io -->

2023-01-23 13:17 UTC, ysv requested changes
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/store/key.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMEKM1u-1e8nAAtbjuF:-NMTk7GN5yQJdE5Pmw3d:bank97h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/pkg/store/key.go#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think not. Empty key have no value. AT least I cannot think of a use case for it. so we should avoid that. 
</blockquote></details>

immature:
I mean in error we could mention index of key which is empty probably makes it easier to debug

`errors.New("received empty key on index %v", i)`
___
*[`x/asset/nft/keeper/keeper_test.go` line 358 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3c9Rn5np-M8L_t6Yb:-NMTl07u2NHuDC15QdeS:b2nid0f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/keeper_test.go#L358)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I thought you only meant the code I introduced in this PR. I will look into all files. 
</blockquote></details>

thx
___
*[`x/asset/nft/types/keys.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMTl6Vz5Nv9eWocmjjG:-NMTl6Vz5Nv9eWocmjjH:bb2rz7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dc729736fe3d5beab17f71640084987d085adbdb/x/asset/nft/types/keys.go#L51)):*
> ```Go
> 		return "", "", err
> 	}
> 	classID := string(parsedKeys[0])
> ```

variables are not needed now
`return string(parsedKeys[0]), parsedKeys[1] ...`
___
*[`x/asset/nft/keeper/freezing_store.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_dXn-donK6t83zHn:-NMTlQa0DQXmcB91ONWe:b6wemjn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L23)):*
> I honestly see no benefit in defining a global variable that will only be used once

you should use it at least twice:
1. when you set it
2. when you check if NFT is frozen. You should compare value from store & value in const

So I insist on moving it to a const


<!-- Sent from Reviewable.io -->

2023-01-23 14:00 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 34 of 36 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/store/key.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMEKM1u-1e8nAAtbjuF:-NMTrpjW4bm0ohmDjYlu:b-k7fn93) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/pkg/store/key.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

immature:
I mean in error we could mention index of key which is empty probably makes it easier to debug

`errors.New("received empty key on index %v", i)`
</blockquote></details>

Good idea. Done
___
*[`x/asset/nft/types/keys.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMTl6Vz5Nv9eWocmjjG:-NMTrwZoCnAnHqj0IGQ8:bcwh9k8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dc729736fe3d5beab17f71640084987d085adbdb/x/asset/nft/types/keys.go#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

variables are not needed now
`return string(parsedKeys[0]), parsedKeys[1] ...`
</blockquote></details>

but some where we should mention which one is which. 
___
*[`x/asset/nft/keeper/freezing_store.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NM3_dXn-donK6t83zHn:-NMTs9Ix-Xb3VM8BqXk3:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5610db659be60609ac086a126f0ef5f79e5a52dd/x/asset/nft/keeper/freezing_store.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> I honestly see no benefit in defining a global variable that will only be used once

you should use it at least twice:
1. when you set it
2. when you check if NFT is frozen. You should compare value from store & value in const

So I insist on moving it to a const
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-24 09:29 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 223 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMDxu1p3ixxHcTzIRMS:-NMY5ncM1FFLWpkM7k39:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4b5679c3354492abf931bc11782b9d0d493a0ba0/x/asset/nft/keeper/keeper.go#L223)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get about simpler. You will have the one method to return you the key, all such methods are in the keys.go file, so it's easy to see how we use the sore, all in one please.
</blockquote></details>

Done.
___
*[`x/asset/nft/types/keys.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMTl6Vz5Nv9eWocmjjG:-NMY5ySSBQZ4A-3z1JmD:b-z9im9h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dc729736fe3d5beab17f71640084987d085adbdb/x/asset/nft/types/keys.go#L51)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but some where we should mention which one is which. 
</blockquote></details>

Done as requested. 


<!-- Sent from Reviewable.io -->

2023-01-24 15:16 UTC, ysv approved these changes
> Reviewed 1 of 2 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/nft/types/keys.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMTl6Vz5Nv9eWocmjjG:-NMZLEMYCfw52pZBc8eZ:b-jf1v91) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dc729736fe3d5beab17f71640084987d085adbdb/x/asset/nft/types/keys.go#L51)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done as requested. 
</blockquote></details>

I see what you mean
It probably makes sense to add comment 
but non-blocking for me so as you prefer


<!-- Sent from Reviewable.io -->

2023-01-25 07:58 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/nft/keeper/keeper.go` line 225 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMbruim93g2PslUL6e6:-NMbuXBWBJI9DDT4YH14:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9094677cc65f20ff48d595c04ff5b3a5ab11bd9/x/asset/nft/keeper/keeper.go#L225)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`outside of` -> `outside`
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 308 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/347#-NMbpkll3OlJw0XqCnRv:-NMbuza_1ne1Z2SQt8Xf:b-1viq2a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9094677cc65f20ff48d595c04ff5b3a5ab11bd9/x/asset/nft/keeper/keeper.go#L308)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`Also the original ` -> `Also, the original 
</blockquote></details>

But that `,` would be a wrong punctuation. The sentence just follows the `Also` word, and it is meaningfully distinct. 


<!-- Sent from Reviewable.io -->

2023-01-25 10:38 UTC, ysv approved these changes
> Reviewed 3 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-01-25 10:47 UTC, merged