added docs to describe asset ft behavior
CoreumFoundation/coreum pull request #351
Opened 2023-01-18 11:51 UTC by miladz68

2023-01-18 12:39 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3k1rdBwJ7RmhpFxhE):*
@ysv @miladz68 Guys, but what about the spec in the way we have it for the feemodel? Do we want to have the same later or this one is final?
___
*[`x/asset/ft/spec/README.md` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3kGzx3D-b6a5ksJ6P:-NM3kGzx3D-b6a5ksJ6Q:blhik4b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L2)):*
> ```Markdown
> # Overview
> This module called `assetft` is responsible to provide tokenization features for the fungible token part, described in Coreum's whitepaper. There is also another module under development called `assetnft` which is responsible for the NFT part of asset tokenization. 
> ```

IMO, we don't need that reference `described in Coreum's whitepaper`. Same for the `nft` we don't need it to be mentioned it here.



_Code quote:_
```Markdown
described in Coreum's whitepaper
```
___
*[`x/asset/ft/spec/README.md` line 4 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3kTZvDoDIXg2DnVlk:-NM3kTZvDoDIXg2DnVll:biqgn7p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L4)):*
> ```Markdown
> This module called `assetft` is responsible to provide tokenization features for the fungible token part, described in Coreum's whitepaper. There is also another module under development called `assetnft` which is responsible for the NFT part of asset tokenization. 
> 
> Here in this doc we will provide the detailed behavior of fungible tokens as they are implemented. Please note that at the time of writing this doc, the behavior described here is closer to the implementation than the whitepaper and if there are differences, the behavior described here should be considered correct. This doc will describe transaction types and their behavior. For the fields and their meaning used in transactions please consult the proto files in `coreum/proto/coreum/asset/ft`.
> ```

Why do we need to keep so many `warnings`, let's just describe how the module works without warnings and references.
___
*[`x/asset/ft/spec/README.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3ku_95lJ7v6QgQ2f8:-NM3ku_95lJ7v6QgQ2f9:bx3ordv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L6)):*
> ```Markdown
> Here in this doc we will provide the detailed behavior of fungible tokens as they are implemented. Please note that at the time of writing this doc, the behavior described here is closer to the implementation than the whitepaper and if there are differences, the behavior described here should be considered correct. This doc will describe transaction types and their behavior. For the fields and their meaning used in transactions please consult the proto files in `coreum/proto/coreum/asset/ft`.
> 
> Here is the list of the transactions provided by this module, we will discuss each of them separately. 
> ```

Let's replace the `discuss` to something else.



_Code quote:_
```Markdown
we will discuss
```
___
*[`x/asset/ft/spec/README.md` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3l8lYBLq7pICVlt3Q:-NM3l8lZ99i1kV93DtEH:bvifm17) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L15)):*
> ```Markdown
> 
> # Interaction with bank module, introducing wbank module
> Since Coreum is based on Cosmos SDK, We should mention that Cosmos SDK provides the native bank module which is responsible to track fungible token creation and balances for each account. But this module does not allow anyone to create a fungible token, mint/burn it, and also does not allow for other features such as freezing and whitelisting. To work around this issue we have wrapped the `bank` module into the wbank module. 
> ```

You wrapped the bank into "`", so probably the `wbank` should be also wrapped.



_Code quote:_
```Markdown
wbank
```
___
*[`x/asset/ft/spec/README.md` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lLNoDBFLI0A_H439:-NM3lLNoDBFLI0A_H43A:b-2hleo6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L17)):*
> ```Markdown
> Since Coreum is based on Cosmos SDK, We should mention that Cosmos SDK provides the native bank module which is responsible to track fungible token creation and balances for each account. But this module does not allow anyone to create a fungible token, mint/burn it, and also does not allow for other features such as freezing and whitelisting. To work around this issue we have wrapped the `bank` module into the wbank module. 
> 
> In `wbank` module we wrap the Send method of the `bank` module and intercept it with `BeforeSend` functions provided by `assetft` module. This allows `assetft` module to inject custom logic into bank's `Send` method and reject some transaction if whitelisting or freezing criteria is not met.
> ```

Not just `Send`
___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lTPjBUlY-O9yABhb:-NM3lTPjBUlY-O9yABhc:bgfign4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
> ```Markdown
> In a nutshell, `assetft` module interacts with `wbank` which in turn wraps the original `bank` module.
> 
> This structure allows to reuse the code provided by Cosmos SDK, and also reuse the infrastructure that the community provides (e.g explorers and wallets), but the downside is that the data regarding for each fungible token must be split and stored in 2 different places. It is apparent in the query structure. For example you want to query for frozen balances of a fungible token you need to query the `assetft` module but to get total supply, you must query the `bank` module. 
> ```

Let's not mention the downside. We should mention the downside only if the users must understand it, here is just an implementation detail.
___
*[`x/asset/ft/spec/README.md` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3m4-39dj8AuEX5cGc:-NM3m4-39dj8AuEX5cGd:buz36qv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L30)):*
> ```Markdown
> All the information provided at the time of issuance is immutable and cannot be changed later.
> 
> #### Issuance fee
> ```

I would add the `Issuance fee` after the explanation of the `issuance body`, since it's and effect of the issuance. 



_Code quote:_
```Markdown
Issuance fee
```
___
*[`x/asset/ft/spec/README.md` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3mIBVA4P5XuGsP7Fn:-NM3mIBVA4P5XuGsP7Fo:b-w0wqd5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L31)):*
> ```Markdown
> 
> #### Issuance fee
> Whenever a user wants to issue a fungible token, they have to pay some extra money as issuance fee, which is calculated on type of tx execution fee and will be burnt.
> ```

You need to add that it's managed by the gov.
___
*[`x/asset/ft/spec/README.md` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3mPLi4Cj5dh7hu6A4:-NM3mPLi4Cj5dh7hu6A5:b-583olp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L35)):*
> ```Markdown
> 
> #### Denom naming, Symbol and Precision
> The way that denom i [...]

2023-01-18 12:39 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-18 13:55 UTC, pgoos requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 23 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 4 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3wQay061Bxpf_hD90:-NM3wQay061Bxpf_hD91:bbcz1b3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L4)):*
> ```Markdown
> This module called `assetft` is responsible to provide tokenization features for the fungible token part, described in Coreum's whitepaper. There is also another module under development called `assetnft` which is responsible for the NFT part of asset tokenization. 
> 
> Here in this doc we will provide the detailed behavior of fungible tokens as they are implemented. Please note that at the time of writing this doc, the behavior described here is closer to the implementation than the whitepaper and if there are differences, the behavior described here should be considered correct. This doc will describe transaction types and their behavior. For the fields and their meaning used in transactions please consult the proto files in `coreum/proto/coreum/asset/ft`.
> ```

I don't like this sentence `Please note that at the time of writing this doc, the behavior described here is closer to the implementation than the whitepaper and if there are differences, the behavior described here should be considered correct.` Why do we need to have misalignments at all? The whitepaper should be updated as well.



_Code quote:_
```Markdown
Please note that at the time of writing this doc, the behavior described here is closer to the implementation than the whitepaper and if there are differences, the behavior described here should be considered correct.
```
___
*[`x/asset/ft/spec/README.md` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3x0lZ8ZUyLdIlVHIu:-NM3x0lZ8ZUyLdIlVHIv:b-v41enx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L15)):*
> ```Markdown
> 
> # Interaction with bank module, introducing wbank module
> Since Coreum is based on Cosmos SDK, We should mention that Cosmos SDK provides the native bank module which is responsible to track fungible token creation and balances for each account. But this module does not allow anyone to create a fungible token, mint/burn it, and also does not allow for other features such as freezing and whitelisting. To work around this issue we have wrapped the `bank` module into the wbank module. 
> ```

`responsible to track` should be `responsible for tracking`
___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM48rNU7xz7n4NHz5SA:-NM48rNU7xz7n4NHz5SB:bdb9ihk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
> ```Markdown
> In a nutshell, `assetft` module interacts with `wbank` which in turn wraps the original `bank` module.
> 
> This structure allows to reuse the code provided by Cosmos SDK, and also reuse the infrastructure that the community provides (e.g explorers and wallets), but the downside is that the data regarding for each fungible token must be split and stored in 2 different places. It is apparent in the query structure. For example you want to query for frozen balances of a fungible token you need to query the `assetft` module but to get total supply, you must query the `bank` module. 
> ```

`regarding for` should be just `regarding`
This sentence doesn't sound good `For example you want to query for frozen balances of a fungible token you need to query the `assetft` module but to get total supply, you must query the `bank` module.`
How about: For example, if you want to query for frozen balances of a fungible token, you need to query the `assetft` module but if you want to get the total supply, you must query the `bank` module.


<!-- Sent from Reviewable.io -->

2023-01-19 09:33 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 22 unresolved discussions (waiting on @dzmitryhil, @pgoos, @wojtek-coreum, and @ysv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3k1rdBwJ7RmhpFxhE):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 Guys, but what about the spec in the way we have it for the feemodel? Do we want to have the same later or this one is final?
</blockquote></details>

I argued that having it in that format brings no real value. 
___
*[`x/asset/ft/spec/README.md` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3kGzx3D-b6a5ksJ6P:-NM7vqQ5AFFRVVaX894h:b-5un61v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO, we don't need that reference `described in Coreum's whitepaper`. Same for the `nft` we don't need it to be mentioned it here.
</blockquote></details>

The point of mentioning them is to describe the thought process on how we got here.
___
*[`x/asset/ft/spec/README.md` line 4 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3wQay061Bxpf_hD90:-NM7wZ5J3fg7-dNhZGjS:ba3dfob) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L4)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

I don't like this sentence `Please note that at the time of writing this doc, the behavior described here is closer to the implementation than the whitepaper and if there are differences, the behavior described here should be considered correct.` Why do we need to have misalignments at all? The whitepaper should be updated as well.
</blockquote></details>

Removed
___
*[`x/asset/ft/spec/README.md` line 4 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3kTZvDoDIXg2DnVlk:-NM7wZuX3sLmbYXSe43Z:bx20t13) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L4)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need to keep so many `warnings`, let's just describe how the module works without warnings and references.
</blockquote></details>

Removed that sentence
___
*[`x/asset/ft/spec/README.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3ku_95lJ7v6QgQ2f8:-NM7yDu5De2DnH3EF7AT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's replace the `discuss` to something else.
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3l8lYBLq7pICVlt3Q:-NM7yJzO3BCOD9KmiE7_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You wrapped the bank into "`", so probably the `wbank` should be also wrapped.
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3x0lZ8ZUyLdIlVHIu:-NM8-M086XOQbYetP5s-:b-a6qtf7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

`responsible to track` should be `responsible for tracking`
</blockquote></details>

Done, Great catch
___
*[`x/asset/ft/spec/README.md` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lLNoDBFLI0A_H439:-NM84yuHAu9X_-CsdBns:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not just `Send`
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lTPjBUlY-O9yABhb:-NM850FQ7i_TUKMwxXbV:b-cdfw7g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's not mention the downside. We should mention the downside only if the users must understand it, here is just an implementation detail.
</blockquote></details>

The doc is intended for developers mostly those that will join us, they need to understand it. I don't think we should structure this doc to be exposed to end users. 
___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM48rNU7xz7n4NHz5SA:-NM86vCoEcvM1-iwXjNt:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

`regarding for` should be just `regarding`
This sentence doesn't sound good `For example you want to query for frozen balances of a fungible token you need to query the `assetft` module but to get total supply, you must query the `bank` module.`
How about: For example, if you want to query for frozen balances of a fungible token, you need to query the `assetft` module but if you want to get the total supply, you must query the `bank` module.
</blockquote></details>

Done
___
*[`x/asset/ft/spec/README.md` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3m4-39dj8AuEX5cGc:-NM8BJxKDZjxneBvrSRW:b-bxorjj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would add the `Issuance fee` after the explanation of the `issuance body`, since it's and effect of the issuance. 
</blockquote></details>

This is duplicate comment
___
*[`x/asset/ft/spec/README.md` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3mIBVA4P5XuGsP7Fn:-NM88UOk-i79DqXmsmfT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You need to add that it's managed by the gov.
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3mPLi4Cj5dh7hu6A4:-NM88Xst7-POBNMYYon7:b-886gsx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L35)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why `Denom` is uppercase here?
</blockquote></details>

Fixed
___
*[`x/asset/ft/spec/README.md` line 37 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3m_BN5IYcoFKk83jq:-NM8BO5d5O71THIaiZdb:bdbnrz4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would add the `Issuance fee` after the explanation of the `issuance body`, since it's and effect of the issuance.
</blockquote></details>

but the is no [...]

2023-01-20 07:56 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @miladz68, @pgoos, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3kGzx3D-b6a5ksJ6P:-NMD98lXDWngb4bVo3VI:bxkofo6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The point of mentioning them is to describe the thought process on how we got here.
</blockquote></details>

But that doc is the FT doc, it isn't the doc about all tokens we support.
___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lTPjBUlY-O9yABhb:-NMD9SHh5GSb5xjlyQPf:b-6cy0ik) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The doc is intended for developers mostly those that will join us, they need to understand it. I don't think we should structure this doc to be exposed to end users. 
</blockquote></details>

But it isn't a downside, it's just an implementation detail. And we shouldn't pay attention to it.
___
*[`x/asset/ft/spec/README.md` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sHbw5M31nACoLolm:-NMDA6An04JDxcaEAErE:bypqa59) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L63)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It contains the basic use case, which is duplicate but in shorter form, and also it contains edge cases which is not described.
</blockquote></details>

I still don't like the use cases, here. This is a technical doc, so the use cases should be somewhere outside in the coreum doc web-site for example.
___
*[`x/asset/ft/spec/README.md` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sug771_B4NPa-3Wm:-NMDAOW5688hKMV7u1uL:b-rkr89w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It contains the basic use case, which is duplicate but in shorter form, and also it contains edge cases which is not described.
</blockquote></details>

Same opinin as in the `Freeze/Unfreeze`


<!-- Sent from Reviewable.io -->

2023-01-20 07:56 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @pgoos, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-20 08:51 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @pgoos, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3kGzx3D-b6a5ksJ6P:-NMDN061AHnfL_n2wwlk:b-hfpv0l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But that doc is the FT doc, it isn't the doc about all tokens we support.
</blockquote></details>

removed
___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lTPjBUlY-O9yABhb:-NMDM-uzBxIao0o-f9wu:b-o78xd1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But it isn't a downside, it's just an implementation detail. And we shouldn't pay attention to it.
</blockquote></details>

Removed the word `downside` and I did some rewording, please take a look again. the fact that some part of information lives in bank module and some in asset ft module is not an implementation detail, but is part of the interface we expose to the outside world, I prefer to keep mentioning of this information here. 
___
*[`x/asset/ft/spec/README.md` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sHbw5M31nACoLolm:-NMDMchr2WGozs40iYit:b-llldbf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I still don't like the use cases, here. This is a technical doc, so the use cases should be somewhere outside in the coreum doc web-site for example.
</blockquote></details>

This is the the expected behavior of the module. That is the main point of having this doc and the task. 


<!-- Sent from Reviewable.io -->

2023-01-20 10:24 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @pgoos, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sug771_B4NPa-3Wm:-NMDhF0Q5VkYUK192ULQ:blflphx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L80)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same opinin as in the `Freeze/Unfreeze`
</blockquote></details>

lets dicsus there then. 


<!-- Sent from Reviewable.io -->

2023-01-20 11:44 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @miladz68, @pgoos, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3lTPjBUlY-O9yABhb:-NMDzVj7-3r9Qpjjs7P4:b-2lkko1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Removed the word `downside` and I did some rewording, please take a look again. the fact that some part of information lives in bank module and some in asset ft module is not an implementation detail, but is part of the interface we expose to the outside world, I prefer to keep mentioning of this information here. 
</blockquote></details>

Now better
___
*[`x/asset/ft/spec/README.md` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sHbw5M31nACoLolm:-NMDzXyX8STUzWT910tw:bqhbu80) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L63)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is the the expected behavior of the module. That is the main point of having this doc and the task. 
</blockquote></details>

@ysv ?
___
*[`x/asset/ft/spec/README.md` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sug771_B4NPa-3Wm:-NMDzZiTEgTkW9nwq_sQ:bb74ce2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

lets dicsus there then. 
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2023-01-23 09:35 UTC, pgoos requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 20 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMSyivtDvTqIhE1yRzT:-NMSyivtDvTqIhE1yRzU:bup75ak) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f717aab618dcce23299cdd8c774bab690d841fa9/x/asset/ft/spec/README.md#L20)):*
> ```Markdown
> 
> 
> This structure allows to reuse the code provided by Cosmos SDK, and also reuse the infrastructure that the community provides (e.g explorers and wallets) It is apparent in the query structure. And it also leads to the fact that some of the information regarding fungible tokens will exists in the `assetft` module and some in the `bank` module. For example, if you want to query for frozen balances of a fungible token, you need to query the `assetft` module but if you want to get the total supply, you must query the bank module.
> ```

should be `will exist`



_Code quote:_
```Markdown
some of the information regarding fungible tokens will exists
```


<!-- Sent from Reviewable.io -->

2023-01-23 09:38 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @pgoos, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 20 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMSyivtDvTqIhE1yRzT:-NMSzMp9-LZb7_AL-M03:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f717aab618dcce23299cdd8c774bab690d841fa9/x/asset/ft/spec/README.md#L20)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

should be `will exist`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-23 09:39 UTC, pgoos approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-:-NMSzoudBH1uwtrmeKT2:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-01-23 10:22 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/asset/ft/spec/README.md` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3sHbw5M31nACoLolm:-NMT7gUS4y9nIIoIisEU:b-djal3p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv ?
</blockquote></details>

I like wording here and the way freezing is structured part by part in this section `Here is the description of`. 
Maybe we should put `For example if the issuer freezes 1000 ABC tokens...` after this part but I'm not sure
mostly ok for me
___
*[`x/asset/ft/spec/README.md` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMT70GB-g0UfJ6ekF_m:-NMT70GB-g0UfJ6ekF_n:b-lgu3qs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L70)):*
> ```Markdown
> - The user can only send their tokens in excess of the frozen amount.
> - The user can receive tokens regardless of frozen limitation.
> - The user can send their tokens to the issuer regardless of frozen limitation.
> ```

this one is not relevant as we decided recently please also check other parts where this mentioned
e.g global freeze


<!-- Sent from Reviewable.io -->

2023-01-23 12:45 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMT70GB-g0UfJ6ekF_m:-NMTdsXx9vEcw0tiRr2f:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f8194dc99b8b9234e7b8003a7ee19b2b6f246d4/x/asset/ft/spec/README.md#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this one is not relevant as we decided recently please also check other parts where this mentioned
e.g global freeze
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-23 12:46 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 22 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/ft/spec/README.md` line 4 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMT_ff3Cf8fNdwh5Ki3:-NMT_ff3Cf8fNdwh5Ki4:btnrokf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L4)):*
> ```Markdown
> This module called `assetft` is responsible for providing tokenization features for the fungible token. 
> 
> Here in this doc we will provide the detailed behavior of fungible tokens as they are implemented. For the fields used in transactions and their meanings please consult the proto files in `coreum/proto/coreum/asset/ft`.
> ```

make the path a link maybe?
___
*[`x/asset/ft/spec/README.md` line 17 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTa2n38SnNtowqjct1:-NMTa2n38SnNtowqjct2:b-1z0q12) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L17)):*
> ```Markdown
> Since Coreum is based on Cosmos SDK, We should mention that Cosmos SDK provides the native bank module which is responsible for tracking fungible token creation and balances for each account. But this module does not allow anyone to create a fungible token, mint/burn it, and also does not allow for other features such as freezing and whitelisting. To work around this issue we have wrapped the `bank` module into the `wbank` module. 
> 
> In `wbank` module we wrap all the send related  methods of the `bank` module and intercept them with `BeforeSend` and `BeforeInputOutput` functions provided by `assetft` module. This allows `assetft` module to inject custom logic into interceptor functions and reject some transaction if whitelisting or freezing criteria is not met. 
> ```

... criteria are not met, or ... criterion is not met
___
*[`x/asset/ft/spec/README.md` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTaPTx3RrxKdJtzmks:-NMTaHbL6hSNNKPZA-75:b-106i7v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L20)):*
> ```Markdown
> 
> 
> This structure allows to reuse the code provided by Cosmos SDK, and also reuse the infrastructure that the community provides (e.g explorers and wallets) It is apparent in the query structure. And it also leads to the fact that some of the information regarding fungible tokens will exist in the `assetft` module and some in the `bank` module. For example, if you want to query for frozen balances of a fungible token, you need to query the `assetft` module but if you want to get the total supply, you must query the bank module.
> ```

. (dot) after "(e.g explorers and wallets)". (dot) after "(e.g explorers and wallets)"
___
*[`x/asset/ft/spec/README.md` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTaZol8bzxOo0Dy6_s:-NMTaZol8bzxOo0Dy6_t:b9hjxbn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L20)):*
> ```Markdown
> 
> 
> This structure allows to reuse the code provided by Cosmos SDK, and also reuse the infrastructure that the community provides (e.g explorers and wallets) It is apparent in the query structure. And it also leads to the fact that some of the information regarding fungible tokens will exist in the `assetft` module and some in the `bank` module. For example, if you want to query for frozen balances of a fungible token, you need to query the `assetft` module but if you want to get the total supply, you must query the bank module.
> ```

What does "It is apparent in the query structure." mean?
___
*[`x/asset/ft/spec/README.md` line 28 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTb7H52w_Asu6UCgf7:-NMTb7H52w_Asu6UCgf8:b-oe7ofp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L28)):*
> ```Markdown
> # Token Interactions 
> ## Issue
> Coreum provides a decentralized platform which allows everyone to tokenize their assets. Although the functionality of fungible token creation and minting is present in the original `bank` module of Cosmos SDK, it is not exposed to the end users, and it is only possible to create new fungible tokens via either the governance or IBC. The Issue method described here, makes it possible for everyone to create a fungible token and manage its supplies. When the issuer issues a token, they specify the initial total supply which will be delivered to the issuers account address.
> ```

issuer's account address
___
*[`x/asset/ft/spec/README.md` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTbeIkEFnvbl6lt8GN:-NMTbeIkEFnvbl6lt8GO:b-6l2qdk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L33)):*
> ```Markdown
> 
> #### Denom naming, Symbol and Precision
> The way that denom is created is that the user provides a name for their subunit, and the denom for the token, which is the main identifier of the token, will be created by appending the subunit with the issuer address separated with a dash (subunit-address). The user also provides the symbol and precision which will only be used for display purposes and will be stored in bank modules metadata field.
> ```

"appending the subunit with the issuer address"

I think it should be
"appending the issuer addres to the subunit"

or

"joining the subunit and the issuer address"
___
*[`x/asset/ft/spec/README.md` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTc1WZEV39izr0BtJ4:-NMTc1WZEV39izr0BtJ5:b-wrxt1k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L33)):*
> ```Markdown
> 
> #### Denom naming, Symbol and Precision
> The way that denom is created is that the user provides a name for their subunit, and the denom for the token, which is the main identifier of the token, will be created by appending the subunit with the issuer address separated with a dash (subunit-address). The user also provides the symbol and precision which will only be used for display purposes and will be stored in bank modules metadata field.
> ```

"bank module's metadata field"
___
*[`x/asset/ft/spec/README.md` line 35 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTc6et45QVr524bGdW:-NMTc6et45QVr524bGdX:bbr7f6e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L35)):*
> ```Markdown
> The way that denom is created is that the user provides a name for their subunit, and the denom for the token, which is the main identifier of the token, will be created by appending the subunit with the issuer address separated with a dash (subunit-address). The user also provides the symbol and precision which will only be used for display purposes and will be stored in bank modules metadata field.
> 
> For example to represent bitcoin on Coreum, once could choose satoshi as subunit, BTC as Symbol and 8 as precision. It means that if the issuer address is core1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8 then the denom will be `satoshi-devcore1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8` and since we have chosen BTC as symbol and 8 as precision, it will follow that (1 BTC = 10^8 `satoshi-devcore1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8`)
> ```

bitcoin -> Bitcoin
___
*[`x/asset/ft/spec/README.md` line 35 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTcC27-XrdC2HKspxT:-NMTcC27-XrdC2HKspxU:by2y3bg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2 [...]

2023-01-23 13:39 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 21 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/ft/spec/README.md` line 4 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMT_ff3Cf8fNdwh5Ki3:-NMTngnmE_pwStddG9I4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

make the path a link maybe?
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 17 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTa2n38SnNtowqjct1:-NMTnjTQ2BnygnyfNvKU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

... criteria are not met, or ... criterion is not met
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTaPTx3RrxKdJtzmks:-NMTh-Gi4_17V0gV-hm7:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

. (dot) after "(e.g explorers and wallets)". (dot) after "(e.g explorers and wallets)"
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTaZol8bzxOo0Dy6_s:-NMThBw45p69-XEntrXv:b-iz0639) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What does "It is apparent in the query structure." mean?
</blockquote></details>

The sentence should come after the next sentence. But I think it cab be removed. 
___
*[`x/asset/ft/spec/README.md` line 28 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTb7H52w_Asu6UCgf7:-NMThVBt1LGiESBkeG5c:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

issuer's account address
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTbeIkEFnvbl6lt8GN:-NMTiw0WA-k9e-_Py6OB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"appending the subunit with the issuer address"

I think it should be
"appending the issuer addres to the subunit"

or

"joining the subunit and the issuer address"
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTc1WZEV39izr0BtJ4:-NMTj0wEEG-SpL_YaOrV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"bank module's metadata field"
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 35 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTc6et45QVr524bGdW:-NMTjDrR6LzZpV00rkJU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

bitcoin -> Bitcoin
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 35 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTcC27-XrdC2HKspxT:-NMTjE4n1gxGHhSzvXrY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

once -> someone or one
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 35 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTcQ72EHiT0oiObA25:-NMTjIwrEVMo6yI2fsgc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

satoshi-devcore1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8 -> satoshi-core1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 38 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTcdLRC9GPLzGWU3mh:-NMTjMt_3vPeN0s55omt:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

a detail description -> a detailed description
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 46 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTclmrDcwGd74BEwGN:-NMTjR5T-DeH7x539yXY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This values -> This value
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 46 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTcuXc2jVm_x7EWI5G:-NMTjYab01D2jiV5tmiS:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The tokens to be burnt value are -> The tokens to be burnt are
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 46 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTcz_i2BTtC867w-tk:-NMTkn_j6JOWPNXJCz14:b-d14saq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

by multiplying the transfer amount -> by multiplying the transfered amount
</blockquote></details>

I want to reference the `amout to be transferred`, so `transfer amount` is better than `transferred amount`. To be very picky, we should write `by multiplying the amount to be transferred` but it does not read nice.  
___
*[`x/asset/ft/spec/README.md` line 52 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTdGsI9oMWIxzr2tjL:-NMTnmGb1elQD23LRKdb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

 which is calculated on type of ->  which is calculated on top of
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 55 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTdTRx-C2GrSS2b5wo:-NMTlqcJ0nxhh45D_W_U:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L55)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

issuer's account address
</blockquote></details>

Done.
___
* [...]

2023-01-23 13:52 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMTt_vABIJggNnDPQrU:btw8thb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

added punctuation to make it clear. 
</blockquote></details>

but still it should be "will not be higher than", no?


<!-- Sent from Reviewable.io -->

2023-01-23 14:06 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMTwq9ED-J4MSUeJyRx:b-siq49m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but still it should be "will not be higher than", no?
</blockquote></details>

I see that I have missed a "be" there. 


<!-- Sent from Reviewable.io -->

2023-01-23 17:11 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3k1rdBwJ7RmhpFxhE):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, resolving this one.
</blockquote></details>

if you resolve it then I'm blocking because changes are needed IMO


<!-- Sent from Reviewable.io -->

2023-01-24 08:43 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NM3k1rdBwJ7RmhpFxhE):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if you resolve it then I'm blocking because changes are needed IMO
</blockquote></details>

@ysv Added Abstract and Concep sections. the rest is not part of the task, and should be done in a separate task. 


<!-- Sent from Reviewable.io -->

2023-01-24 15:26 UTC, ysv reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-01-25 13:17 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMd3pzQCmcpBH7Z6VE4:b-n8hyoo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see that I have missed a "be" there. 
</blockquote></details>

is "that" instead of "than" a correct wording?


<!-- Sent from Reviewable.io -->

2023-01-25 13:29 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMd6fR_BdeupnCFnbLF:b-794fhw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

is "that" instead of "than" a correct wording?
</blockquote></details>

Done, you are correct.


<!-- Sent from Reviewable.io -->

2023-01-25 13:31 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMd72Cl16U_kRHwgpN9:bghy5rw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done, you are correct.
</blockquote></details>

Change wasn't pushed


<!-- Sent from Reviewable.io -->

2023-01-25 13:38 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMd8Zt9BZO6aW96s5Ah:b-rs1tnf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Change wasn't pushed
</blockquote></details>

I don't know why it does not show the changes here, maybe you can check this one  in github ?


<!-- Sent from Reviewable.io -->

2023-01-25 13:43 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

___
*[`x/asset/ft/spec/README.md` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/351#-NMTeRTPAFrE5gEB48_2:-NMd9ocL7Lb3RYn-xnrE:br9e1cu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/198de145ec2e198d7c3e2b80d605969fe84a4b40/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't know why it does not show the changes here, maybe you can check this one  in github ?
</blockquote></details>

now I see it


<!-- Sent from Reviewable.io -->

2023-01-26 10:23 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2023-01-26 10:52 UTC, merged