implemented NFT whitelisting
CoreumFoundation/coreum pull request #364
Opened 2023-01-25 11:22 UTC by miladz68

2023-01-27 10:27 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmR7cN26f-ME_1WoEH:-NMmjERz--aZDdsyYzn-:bsmdo6a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/proto/coreum/asset/nft/v1/genesis.proto#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We use the `FrozenNFT` but `Whitelisted` why?
</blockquote></details>

it is NFTs that get frozen, but the accounts that get whitelisted. the full name for this, would be `WhitelistedAccountsForNFTs` or `WhitelistedAccounts`
___
*[`proto/coreum/asset/nft/v1/query.proto` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmRMmjAuhWR5uFNrzk:-NMmk90BCWKQAXrQYcx-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/proto/coreum/asset/nft/v1/query.proto#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update the comment please, since not clear not, whitelisted for what?
</blockquote></details>

Done.
___
*[`x/asset/nft/genesis_test.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmTIIN0gZZEu1nC6v1:-NMmkOIKEagGB7UWaWWH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/genesis_test.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't use assert the `Whitelisted` and BTW the `frozen` ?
</blockquote></details>

Done.
___
*[`x/asset/nft/client/cli/query.go` line 118 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmRhkU-mMFPcTwADz2:-NMmkVB0CxhSZJ32fZvy:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/client/cli/query.go#L118)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`frozen` ?
</blockquote></details>

Done.
___
*[`x/asset/nft/client/cli/tx_test.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmRoAR8WmmVQOrLZ0N:-NMmko7eEH_gSXqQGK6Z:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/client/cli/tx_test.go#L145)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`frozen` ?
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 473 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmSZW6CRGquB7GLyd8:-NMmkyoS7kQTjhSSFfBH:b-20n19j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/keeper/keeper.go#L473)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we really need to add such comment? We have many such methods, but don't add that comment.
</blockquote></details>

I think it is a reasonable comment. 


<!-- Sent from Reviewable.io -->

2023-01-30 09:28 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmR7cN26f-ME_1WoEH:-NN0_IIH71Wf-V_j6NJV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/proto/coreum/asset/nft/v1/genesis.proto#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Then let's call it `WhitelistedNFTAccounts` or similar.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 09:35 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: 20 of 25 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/genesis_test.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmTIIN0gZZEu1nC6v1:-NN10uK6BAVLU_C3ee27:b-oe1hte) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/genesis_test.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't see it still. I mean check that the state is loaded, similar like we do for the definition.
</blockquote></details>

My  bad. Now, added. 


<!-- Sent from Reviewable.io -->

2023-01-30 21:27 UTC, ysv requested changes
> Reviewed 16 of 25 files at r1, 4 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 721 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3ZVvp3PG0POouZQli:-NN3ZVvp3PG0POouZQlj:b-te6hk9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/integration-tests/modules/assetnft_test.go#L721)):*
> ```Go
> 
> 	requireT.NoError(
> 		chain.Faucet.FundAccountsWithOptions(ctx, issuer, integrationtests.BalancesOptions{
> ```

I suggest to add here extra amount of NFT minting price. It is 0 now but might change in the future and tests will fail then
___
*[`proto/coreum/asset/nft/v1/event.proto` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2TZKP3CcSQeg92nAt:-NN2TZKP3CcSQeg92nAu:b-vxmlye) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/event.proto#L40)):*
> ```protobuf
> }
> 
> message EventUnwhitelisted {
> ```

don't really like the word `Unwhitelist`
Maybe we can replace it with smth else ?
 AddedToWhitelist & RemovedFromWhitelist. Other options ?

Maybe lets discuss ?
___
*[`proto/coreum/asset/nft/v1/query.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2QCXv7Q7ftsrgH9kN:-NN2QCXv7Q7ftsrgH9kO:bl6qo65) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/query.proto#L24)):*
> ```protobuf
> 
>   // Whitelisted queries to check if an account is whitelited to hold an NFT or not.
>   rpc Whitelisted (QueryWhitelistedRequest) returns (QueryWhitelistedResponse) {
> ```

I think we should also have a query for whitelisted NFTs on an account in the same way as we  query whitelisted balances in FTs
I mean to add index action but not only show single
___
*[`x/asset/nft/keeper/keeper.go` line 473 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmSZW6CRGquB7GLyd8:-NN3UPLQBoFoEbo66DWA:bx8l3j5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/keeper/keeper.go#L473)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we don't do it for other methods. IMO or for all of for nothing, here I would cote for nothing. 
</blockquote></details>

since it is already written I don't mind to keep it
But as you prefer
___
*[`x/asset/nft/keeper/keeper.go` line 435 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2V2uzCfmAdNt-EySB:-NN2V2uzCfmAdNt-EySC:b-4wvf31) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L435)):*
> ```Go
> 
> // Unwhitelist removes an account from the whitelisted list of accounts for the NFT
> func (k Keeper) Unwhitelist(ctx sdk.Context, classID, nftID string, sender, account sdk.AccAddress) error {
> ```

` Unwhitelist` & ` Whitelist` are identical except this `k.SetWhitelisting(ctx, classID, nftID, account, false)`

Can we somehow refactor to avoid code dupl ?
___
*[`x/asset/nft/keeper/keeper.go` line 462 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2VQwpAQHwUV4fR2FB:-NN2VQwpAQHwUV4fR2FC:bgtg4je) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L462)):*
> ```Go
> // IsWhitelisted checks to see if an account is whitelisted for an NFT
> func (k Keeper) IsWhitelisted(ctx sdk.Context, classID, nftID string, account sdk.AccAddress) (bool, error) {
> 	store := ctx.KVStore(k.storeKey)
> ```

minor: store could be moved to be initialized before return so it is more logical
___
*[`x/asset/nft/keeper/keeper.go` line 496 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3Vy3o4jLvt-HmgOUR:-NN3Vy3o4jLvt-HmgOUS:b-pf9sr4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L496)):*
> ```Go
> 	}
> 	mp := make(map[nftUniqueID][]string, 0)
> 	pageRes, err := query.Paginate(store, q, func(key, value []byte) error {
> ```

to be 100% correct we should probably check that value is equal to `whitelistedNFTStoreValue` because that is the only case when we consider smth to be frozen
By the way I think this check should be addded to other places also (freezing in NFT & glob freezing in NFT)
___
*[`x/asset/nft/keeper/keeper.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3VjpQ14kBvyGWYEqp:-NN3VjpQ14kBvyGWYEqq:bbn5ihr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L506)):*
> ```Go
> 		}
> 		accountString := account.String()
> 		mp[uniqueID] = append(mp[uniqueID], accountString)
> ```

do we really need all these gymnastics ?
Is it really possible for it to be not unique since it is a key in store ?
___
*[`x/asset/nft/keeper/keeper_test.go` line 464 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3X0oXEa8w-PkazsC2:-NN3X0oY2ulecs9KK7D3:baavb5k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L464)):*
> ```Go
> 
> 	nftParams := types.Params{
> 		MintFee: sdk.NewInt64Coin(constant.DenomDev, 0),
> ```

I suggest to not set 0 here
___
*[`x/asset/nft/keeper/keeper_test.go` line 466 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3WvQG911CvojazRzS:-NN3WvQG911CvojazRzT:b-z8r64f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L466)):*
> ```Go
> 		MintFee: sdk.NewInt64Coin(constant.DenomDev, 0),
> 	}
> 	assetNFTKeeper.SetParams(ctx, nftParams)
> ```

is it a good practice to change params ? I think they might be used in other tests also & I think that changing global state isn't really nice idea
___
*[`x/asset/nft/keeper/keeper_test.go` line 491 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3XMFX726Dng1sqnkT:-NN3XMFX726Dng1sqnkU:b-v3yu8n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L491)):*
> ```Go
> 	// mint NFT
> 	requireT.NoError(assetNFTKeeper.Mint(ctx, settings), sdkerrors.ErrInsufficientFunds)
> 	nftID := settings.ID
> ```

`requireT.NoError` but you specify an error 
___
*[`x/asset/nft/keeper/keeper_test.go` line 584 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3XhmmEwiTOTpb9Skr:-NN3XhmmEwiTOTpb9Sks:b-ojmvjg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L584)):*
> ```Go
> 
> 	// try whitelist account, it should fail
> 	recipient := sdk.AccAddress(ed25519.GenPrivKey().PubKey().Address())
> ```

I suggest to not mint class first and test whitelisting for non existing class and then for non existing NFT
___
*[`x/asset/nft/keeper/msg_server.go` line 155 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3Xun27D8srxLTuJ0q:-NN3Xun27D8srxLTuJ0r:bypxlqg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/msg_server.go#L155)):*
> ```Go
> 
> // Unwhitelist removes an account from the whitelisted list of accounts for the NFT
> func (ms MsgServer) Unwhitelist(ctx context.Context, req *types.MsgUnwhitelist) (*types.EmptyResponse, error) {
> ```

again these 2 methods are almost identical. I think we should merge them on keeper level & we can keep 2 funcs here
___
*[`x/asset/nft/types/keys.go` line 79 at r3](https:/ [...]

2023-01-31 08:43 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 721 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3ZVvp3PG0POouZQli:-NN5lcN-4wkZUhhsJOBU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/integration-tests/modules/assetnft_test.go#L721)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to add here extra amount of NFT minting price. It is 0 now but might change in the future and tests will fail then
</blockquote></details>

Done.
___
*[`proto/coreum/asset/nft/v1/event.proto` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2TZKP3CcSQeg92nAt:-NN5le8Z9SlG_GaMlIMp:b-ii983r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/event.proto#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

don't really like the word `Unwhitelist`
Maybe we can replace it with smth else ?
 AddedToWhitelist & RemovedFromWhitelist. Other options ?

Maybe lets discuss ?
</blockquote></details>

let's discuss. 
But I think WhitelistRemoved and WhitelistAdded are OK. even the current name seems OK. 
___
*[`proto/coreum/asset/nft/v1/query.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2QCXv7Q7ftsrgH9kN:-NN5qCBO8vnLUXKiJ7GP:b-sxogzl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/query.proto#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we should also have a query for whitelisted NFTs on an account in the same way as we  query whitelisted balances in FTs
I mean to add index action but not only show single
</blockquote></details>

we discussed this before and agreed to let other indexers take care of this, and add queries later if we wish. 
___
*[`x/asset/nft/keeper/keeper.go` line 435 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2V2uzCfmAdNt-EySB:-NN5r5Q70mCrfjx6oMvA:b-yaiw8z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L435)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

` Unwhitelist` & ` Whitelist` are identical except this `k.SetWhitelisting(ctx, classID, nftID, account, false)`

Can we somehow refactor to avoid code dupl ?

</blockquote></details>

I did something similar in FTs, and other guys commented to have these two actions completely separate. 
___
*[`x/asset/nft/keeper/keeper.go` line 462 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2VQwpAQHwUV4fR2FB:-NN5ru2UER7ayXiRoXay:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L462)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: store could be moved to be initialized before return so it is more logical
</blockquote></details>

Done
___
*[`x/asset/nft/keeper/keeper.go` line 496 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3Vy3o4jLvt-HmgOUR:-NN5sxiyDg8sZCCsDVkk:b-pzvlx2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L496)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to be 100% correct we should probably check that value is equal to `whitelistedNFTStoreValue` because that is the only case when we consider smth to be frozen
By the way I think this check should be addded to other places also (freezing in NFT & glob freezing in NFT)
</blockquote></details>

Added a check.
___
*[`x/asset/nft/keeper/keeper.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3VjpQ14kBvyGWYEqp:-NN5t8Ny59HX208fjE82:b-brhjzu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L506)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need all these gymnastics ?
Is it really possible for it to be not unique since it is a key in store ?
</blockquote></details>

we need to group them differently. in store they are stored as one key formed from 3 fields, but in genesis file they are stored as 1 key formed from 2 fields and the other field is a list. 
___
*[`x/asset/nft/keeper/keeper_test.go` line 464 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3X0oXEa8w-PkazsC2:-NN5ueUJDTtIvM8d1_ab:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L464)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to not set 0 here
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper_test.go` line 466 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3WvQG911CvojazRzS:-NN5vP8v8fEq8rrtZ_4p:bv5u3rc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L466)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it a good practice to change params ? I think they might be used in other tests also & I think that changing global state isn't really nice idea
</blockquote></details>

keeper tests that are using simapp, are isolated tests and changing values in one tests does not affect other test. 
___
*[`x/asset/nft/keeper/keeper_test.go` line 491 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3XMFX726Dng1sqnkT:-NN5vlCp7IghGYcK62ju:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L491)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`requireT.NoError` but you specify an error 
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper_test.go` line 584 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3XhmmEwiTOTpb9Skr:-NN5wilc5fdj3beEOt7T:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L584)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to not mint class first and test whitelisting for non existing class and then for non existing NFT
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/msg_server.go` line 155 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3Xun27D8srxLTuJ0q:-NN5wpg-0ysaWappAAJz:bcz1173) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/msg_server.go#L155)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

again these 2 methods are almost identical. I think we should merge them on keeper level & we can keep 2 funcs here
</blockquote></details>

let's discuss on the other comment. 
___
*[`x/asset/nft/types/keys.go` line 79 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3YF6d3DPVlsDYeo5g:-NN5x1Vu7PQ0ouTzW-hQ:b4nc258) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/types/keys.go#L79)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

composed -> decomposed ?
</blockquote></details>

`composed of [...]

2023-01-31 11:15 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: 21 of 25 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 473 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NMmSZW6CRGquB7GLyd8:-NN6SEFb9UAL0U9LzOXf:bss4a1x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/100ece134b1750b3acc1c8ca8f45592aebc22095/x/asset/nft/keeper/keeper.go#L473)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need the redundant comment? It's the same to have an unused function. :-)
</blockquote></details>

Removed 


<!-- Sent from Reviewable.io -->

2023-01-31 23:11 UTC, ysv requested changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/event.proto` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2TZKP3CcSQeg92nAt:-NN95R30BRK71y9ZU08Z:b4s5z57) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/event.proto#L40)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss. 
But I think WhitelistRemoved and WhitelistAdded are OK. even the current name seems OK. 
</blockquote></details>

lets discuss on the call
___
*[`proto/coreum/asset/nft/v1/query.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2QCXv7Q7ftsrgH9kN:-NN93nNkDKUl574PJeDp:b-yosjt4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/query.proto#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we discussed this before and agreed to let other indexers take care of this, and add queries later if we wish. 
</blockquote></details>

but does this query requires additional store ?
Because I thought we can support it with current key structure
if no lets discuss, but IMO it is a part of MVP
___
*[`x/asset/nft/keeper/keeper.go` line 435 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2V2uzCfmAdNt-EySB:-NN944YqDQqyIKRGsSyG:b2pxiya) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L435)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I did something similar in FTs, and other guys commented to have these two actions completely separate. 
</blockquote></details>

I also did the same of FT and got such a comment
Ok lets keep it separated then (
___
*[`x/asset/nft/keeper/keeper.go` line 496 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3Vy3o4jLvt-HmgOUR:-NN94Ogw1Y-E4lPka0o9:b2tvc38) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L496)):*
> By the way I think this check should be addded to other places also (freezing in NFT & glob freezing in NFT)

pls check other places mentioned
___
*[`x/asset/nft/keeper/keeper.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3VjpQ14kBvyGWYEqp:-NN94evp36XUGkbbB-Nq:b4b5he8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L506)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need to group them differently. in store they are stored as one key formed from 3 fields, but in genesis file they are stored as 1 key formed from 2 fields and the other field is a list. 
</blockquote></details>

But I didn't get why can't we just use this slice right away to avoid the second for ?

`whitelisted := make([]types.WhitelistedNFTAccounts, 0, len(mp))`
___
*[`x/asset/nft/keeper/keeper_test.go` line 466 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3WvQG911CvojazRzS:-NN94uwY1uuNG8C9a8VC:bvvf04t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L466)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

keeper tests that are using simapp, are isolated tests and changing values in one tests does not affect other test. 
</blockquote></details>

I see then it is ok
So is it isolated in a scope of function or whole package ?


<!-- Sent from Reviewable.io -->

2023-02-01 08:14 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3VjpQ14kBvyGWYEqp:-NNB10qW2h5ydL3ZcTKz:b-88f3d4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L506)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

But I didn't get why can't we just use this slice right away to avoid the second for ?

`whitelisted := make([]types.WhitelistedNFTAccounts, 0, len(mp))`
</blockquote></details>

we need to group all whitelisted accounts based on NFT ID, so we need to put into a map first to first group them and then flatten it into a list. 
___
*[`x/asset/nft/keeper/keeper_test.go` line 466 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3WvQG911CvojazRzS:-NNB1Hsw-p0dFL9zdHSe:b-hsqva0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L466)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see then it is ok
So is it isolated in a scope of function or whole package ?
</blockquote></details>

the test itself. Actually it is isolated at object level. Everytime you call simapp.New() you get an object with its in memory storage. 


<!-- Sent from Reviewable.io -->

2023-02-02 14:28 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: 24 of 25 files reviewed, 6 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2QCXv7Q7ftsrgH9kN:-NNBmVyu7KJIeojopmMG:b8vwmrs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/query.proto#L24)):*
> we discussed this before and agreed to let other indexers take care of this, and add queries later if we wish.
Add Query to list all whitelisted accounts for an NFT.
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 80 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NNBlEaE8MXpqO9WdTCB:-NNBlEaE8MXpqO9WdTCC:bd1hh7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f8722d4ec4a9f5275c664cb1027366e9832c1cc2/proto/coreum/asset/nft/v1/tx.proto#L80)):*
> ```protobuf
>  }
> 
>  message MsgUnwhitelist {
> ```

Rename to AddToWhitelist.
___
*[`x/asset/nft/keeper/keeper.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3VjpQ14kBvyGWYEqp:-NNBn2135SQmUuWK_Cea:bhcck92) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper.go#L506)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need to group all whitelisted accounts based on NFT ID, so we need to put into a map first to first group them and then flatten it into a list. 
</blockquote></details>

Discussed on the call.


<!-- Sent from Reviewable.io -->

2023-02-02 19:16 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: 24 of 25 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN2QCXv7Q7ftsrgH9kN:-NNIYlaq2v5wQ-2cAbx4:byng3hv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/proto/coreum/asset/nft/v1/query.proto#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

> we discussed this before and agreed to let other indexers take care of this, and add queries later if we wish.
Add Query to list all whitelisted accounts for an NFT.
</blockquote></details>

pls add this query
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 80 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NNBlEaE8MXpqO9WdTCB:-NNIYpYUCgTQYghzCYdC:biiwzgq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f8722d4ec4a9f5275c664cb1027366e9832c1cc2/proto/coreum/asset/nft/v1/tx.proto#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Rename to AddToWhitelist.
</blockquote></details>

Waiting for renaming
___
*[`x/asset/nft/keeper/keeper_test.go` line 466 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/364#-NN3WvQG911CvojazRzS:-NNIYj7uCxDlFuhKE7dC:bsfa9i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/868ee9c8231b51e206cbfdcce79f8cf1b0b6ca8a/x/asset/nft/keeper/keeper_test.go#L466)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the test itself. Actually it is isolated at object level. Everytime you call simapp.New() you get an object with its in memory storage. 
</blockquote></details>

I see then ok


<!-- Sent from Reviewable.io -->

2023-02-02 19:17 UTC, ysv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-02-06 23:28 UTC, ysv approved these changes
> Reviewed 6 of 12 files at r7, 17 of 17 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-02-08 07:44 UTC, ysv approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-02-08 08:49 UTC, merged