Added docs to the NFT module
CoreumFoundation/coreum pull request #412
Opened 2023-02-27 10:48 UTC by miladz68

2023-02-27 12:56 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/412)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/spec/README.md` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/412#-NPHwGD39ckzhCN1TnHo:-NPHwGD39ckzhCN1TnHp:bigasfo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dcc5ea7e3bd2b609a2bd554ec0a9e07d51db983d/x/asset/nft/spec/README.md#L24)):*
> ```Markdown
> NFT tokens come with a set of features that the issuer can specify at the time of issuing a class, and then in some cases configured on each NFT level later.
> 
> here is the list of features:
> ```

here -> Here


<!-- Sent from Reviewable.io -->

2023-03-01 08:25 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/spec/README.md` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/412#-NPHwGD39ckzhCN1TnHo:-NPRGk6R1hV-tz-xvNDj:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dcc5ea7e3bd2b609a2bd554ec0a9e07d51db983d/x/asset/nft/spec/README.md#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

here -> Here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-02 07:20 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-02 12:42 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/412)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/nft/spec/README.md` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/412#-NPX9uOg55Pml9KQkZlR:-NPXKtTlCfC4WO6mncc8:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a0cd0e3a0e786ca7f3ff905a988cbefb86a30d12/x/asset/nft/spec/README.md#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's also add the information about the queries, that for the queries it's expected to use the original NFT module.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-02 13:03 UTC, pgoos commented on x/asset/nft/spec/README.md
> +This feature is related to the DEX, and if it is enable, every time that an NFT is traded on the DEX, a percentage of the the traded value is sent to the issuer as royalty fee.
typo: `if it is enable` -> `if it is enabled`

2023-03-03 07:53 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

___
*[`x/asset/nft/spec/README.md` line 54 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/412#-NPHUHhlKzK_y2DaqnlI-r3-54:-NPaSX0t0esofFZWLkLJ:b-95txdl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/798be397565df0ee2eacc27dfff307e080bb6bc7/x/asset/nft/spec/README.md#L54)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

typo: `if it is enable` -> `if it is enabled`
</blockquote></details>


Done


<!-- Sent from Reviewable.io -->

2023-03-09 15:58 UTC, pgoos approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/412#-:-NQ6570i2wvXXpK66Ttw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-09 16:32 UTC, merged