Milad/re enable ibc
CoreumFoundation/coreum pull request #483
Opened 2023-05-03 09:36 UTC by miladz68

2023-05-04 11:17 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: 0 of 10 files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 164 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSViq4bwk1KFuoLsU:-NUaSViq4bwk1KFuoLsV:bqm3yqj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/chain.go#L164)):*
> ```Go
> 	ClientContext     client.Context
> 	GRPCAddress       string
> 	GaiaClientContext client.Context
> ```

Can you use the `GaiaContext GaiaContext` here as well?
___
*[`integration-tests/init.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSfUL9GDtrq1DF-NU:-NUaSfUL9GDtrq1DF-NV:bix5a9k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L70)):*
> ```Go
> 	flag.BoolVar(&runUnsafe, "run-unsafe", false, "run unsafe tests for example ones related to governance")
> 	flag.StringVar(&gaiaAddress, "gaia-address", "localhost:9080", "Address of gaia node started by znet")
> 	flag.StringVar(&gaiaChannelID, "gaia-channel-id", "channel-0", "gaia ibc channel-id started by znet")
> ```

Same question as before, is it possible to get it dynamically by the chainID ? If - yes we don't need that arg here.
___
*[`integration-tests/init.go` line 162 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaT2Em-jad4Tv2oFLP:-NUaT2Em-jad4Tv2oFLQ:bdo5tzs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L162)):*
> ```Go
> 
> // GetChain returns the configured chain.
> func GetChain() Chain {
> ```

That function looks like a workaround. Remove the `TestMain` and you won't need that function. 
___
*[`integration-tests/ibc/main_test.go` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQL8QALAuYivQFMHb:-NUaQL8QALAuYivQFMHc:b-c58f7i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L17)):*
> ```Go
> )
> 
> func TestMain(m *testing.M) {
> ```

Can we avoid the usage of `TestMain`? IMO it's tough to read such code when you don't see that you start the test from some function that isn't called in the test.  IMO better to start the test with the execution of the AwaitChannels().
___
*[`integration-tests/ibc/main_test.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQoJE2qBPS5knm2V5:-NUaQoJE2qBPS5knm2V6:b-lq4a2g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L18)):*
> ```Go
> 
> func TestMain(m *testing.M) {
> 	// it normally takes 70 seconds to stablish channels for the first time
> ```

`stablish` - typo.
___
*[`integration-tests/ibc/main_test.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQvmd8uxUfnyT5AtE:-NUaQvmd8uxUfnyT5AtF:b8wqcl0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L51)):*
> ```Go
> 		// currently we only expect gaia channel so the count should be 1
> 		// TODO: increase the expected value to 2 after we add osmosis
> 		if expectedOpenChannels == 1 {
> ```

Can we get info about the chain's channel? In that case, instead of doing the count assertion you could pass the chainID for example, and wait until it's ready. I guess it should be possible by getting the channel's client. Also in that case you won't miss the addition of a new chain.
___
*[`integration-tests/ibc/main_test.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaRbQl88Q6zWp13IQo:-NUaRbQl88Q6zWp13IQp:b-2mieqw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L58)):*
> ```Go
> 	})
> 	if err != nil {
> 		panic(err)
> ```

Better to return the error here and add the `require.NoError`
___
*[`integration-tests/ibc/transfer_test.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTHE44rjOMFxkRTYC:-NUaTHE44rjOMFxkRTYD:bvi6x9w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L44)):*
> ```Go
> 		TimeoutHeight: ibcclienttypes.Height{
> 			RevisionNumber: 1,
> 			RevisionHeight: 10000000, // TODO: calculate this value
> ```

What does the content mean?
___
*[`integration-tests/ibc/transfer_test.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTfEbA4eSt7kTOXFc:-NUaTfEbA4eSt7kTOXFd:blvmxwj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L54)):*
> ```Go
> 	_, err = client.BroadcastTx(
> 		ctx,
> 		chain.ClientContext.WithFromAddress(sender).WithBroadcastMode(flags.BroadcastBlock),
> ```

Do you need the `.WithBroadcastMode(flags.BroadcastBlock)`? It's already set in the into, right? 


<!-- Sent from Reviewable.io -->

2023-05-04 11:18 UTC, dzmitryhil reviewed
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-05 13:07 UTC, ysv submitted a review, later dismissed
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 164 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSViq4bwk1KFuoLsU:-NUfx1Zq-XdEYIRgtaN1:b-cyotcp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/chain.go#L164)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can you use the `GaiaContext GaiaContext` here as well?
</blockquote></details>

I don't like that we add IBC specific stuff into chain which is used in all integration tests
I really prefer to move it to be only defined inside integration-tests/ibc ?
___
*[`integration-tests/gaia.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxHJ25PDojcJP7F8A:-NUfxHJ25PDojcJP7F8B:blzpb6e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/gaia.go#L1)):*
> ```Go
> package integrationtests
> ```

same. We should find a way to move it to integration-tests/ibc 
___
*[`integration-tests/helpers.go` line 22 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxQr-DRh5aZP5Sczx:-NUfxQr-DRh5aZP5Sczy:b-kbkkwb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/helpers.go#L22)):*
> ```Go
> // the given prefix.
> func GenRandomAddress(prefix string) (string, error) {
> 	privateKey := secp256k1.GenPrivKey()
> ```

minor: do you really need this variabe
___
*[`integration-tests/init.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxUjQ9JGkn2IqhpWQ:-NUfxUjQ9JGkn2IqhpWR:b-q14bhj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L60)):*
> ```Go
> 		stakerMnemonics                          stringsFlag
> 		runUnsafe                                bool
> 		gaiaAddress, gaiaChainID, gaiaChannelID  string
> ```

we should find a way to move it to IBC
___
*[`integration-tests/init.go` line 162 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaT2Em-jad4Tv2oFLP:-NUfxbFx9YXy7o0hQO7Q:bw5wk5w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L162)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That function looks like a workaround. Remove the `TestMain` and you won't need that function. 
</blockquote></details>

neither looks good for me
___
*[`integration-tests/ibc/main_test.go` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQL8QALAuYivQFMHb:-NUfxdLu-M4ZyjaRVAw4:b-nw1ghf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can we avoid the usage of `TestMain`? IMO it's tough to read such code when you don't see that you start the test from some function that isn't called in the test.  IMO better to start the test with the execution of the AwaitChannels().
</blockquote></details>

I 100% agree with this approach.

But taking it even further I propose to move this to crust & I have a plan on how to make it work properly. Lets discuss on the call
___
*[`integration-tests/ibc/main_test.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQvmd8uxUfnyT5AtE:-NUfxsa26REzUooczXwS:b-zcxm8h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L51)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can we get info about the chain's channel? In that case, instead of doing the count assertion you could pass the chainID for example, and wait until it's ready. I guess it should be possible by getting the channel's client. Also in that case you won't miss the addition of a new chain.
</blockquote></details>

would be nice but I'm not sure if it is possible
Waiting for an input from Milad
___
*[`integration-tests/ibc/main_test.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaRbQl88Q6zWp13IQo:-NUfxy0j6Gqj4uVRHUPV:bb6h61l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Better to return the error here and add the `require.NoError`
</blockquote></details>

100%
___
*[`integration-tests/ibc/transfer_test.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUg0NGsEnW-HYw_sZ0U:-NUg0NGsEnW-HYw_sZ0V:bba7nad) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

leaving this comment for myself 
still reviewing this file
___
*[`integration-tests/ibc/transfer_test.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTHE44rjOMFxkRTYC:-NUfzXmF4F_5r6c8cwV3:b-l8l7r9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What does the content mean?
</blockquote></details>

same question
___
*[`integration-tests/ibc/transfer_test.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfztCa-Ml3m7Is4UEf:-NUfztCa-Ml3m7Is4UEg:bpfu4y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L84)):*
> ```Go
> 	ibcAmount := ibctransfertypes.GetTransferCoin(ibctransfertypes.PortID, channelID, sendCoin.Denom, sendCoin.Amount)
> 	require.NoError(t, err)
> 	assert.EqualValues(t, ibcAmount.String(), balancesRecipient.Balances[0].String())
> ```

IMO it is more reasonable to assert that `sendCoin` is equal to balance
___
*[`integration-tests/ibc/transfer_test.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUg-Du_34GaaCbLZ7g1:-NUg-Du_34GaaCbLZ7g2:b-9zguv5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L84)):*
> ```Go
> 	ibcAmount := ibctransfertypes.GetTransferCoin(ibctransfertypes.PortID, channelID, sendCoin.Denom, sendCoin.Amount)
> 	require.NoError(t, err)
> 	assert.EqualValues(t, ibcAmount.String(), balancesRecipient.Balances[0].String())
> ```

to get balance from slice of coins it is better to use  `balancesRecipient.Balances.AmountOf(denom)` IMO


<!-- Sent from Reviewable.io -->

2023-05-05 14:45 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 164 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSViq4bwk1KFuoLsU:-NUgMaIe35b_PiK8kLkv:b-jyzj5y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/chain.go#L164)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like that we add IBC specific stuff into chain which is used in all integration tests
I really prefer to move it to be only defined inside integration-tests/ibc ?
</blockquote></details>

discussed earlier
___
*[`integration-tests/gaia.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxHJ25PDojcJP7F8A:-NUgMvVv00qMFBh1QH_z:b-ewjvha) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/gaia.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same. We should find a way to move it to integration-tests/ibc 
</blockquote></details>

discused in call. 
___
*[`integration-tests/helpers.go` line 22 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxQr-DRh5aZP5Sczx:-NUgB-Kk1RbjoZU4_FVM:b-25gsu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/helpers.go#L22)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: do you really need this variabe
</blockquote></details>

it is a good abstraction to have. not really needed. it is just 2 lines of code.
___
*[`integration-tests/init.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxUjQ9JGkn2IqhpWQ:-NUgMyqz1Srd9T_TF5xI:bhz8ayc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we should find a way to move it to IBC
</blockquote></details>

discussed in the call. 
___
*[`integration-tests/init.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSfUL9GDtrq1DF-NU:-NUgBFbqAkruXc15WFV8:b-drz6gm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same question as before, is it possible to get it dynamically by the chainID ? If - yes we don't need that arg here.
</blockquote></details>

Agreed. Will do
___
*[`integration-tests/init.go` line 162 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaT2Em-jad4Tv2oFLP:-NUgBbDZEzOqemKDX-Sv:bvqgti0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L162)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

neither looks good for me
</blockquote></details>

If I remove TestMain, how can I wait for the channels to come online. 
___
*[`integration-tests/ibc/main_test.go` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQL8QALAuYivQFMHb:-NUgBjrl3jzH9esJ9G9p:b-3glmgh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I 100% agree with this approach.

But taking it even further I propose to move this to crust & I have a plan on how to make it work properly. Lets discuss on the call
</blockquote></details>

Agreed. 
___
*[`integration-tests/ibc/main_test.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQvmd8uxUfnyT5AtE:-NUgByBuD4WxD6aE87gN:be998li) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

would be nice but I'm not sure if it is possible
Waiting for an input from Milad
</blockquote></details>

Agreed as before. it was decided to keep await with a todo to remove after crust is updated to account for it.
___
*[`integration-tests/ibc/main_test.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaRbQl88Q6zWp13IQo:-NUgCGfU5ERTryaWXBhm:bqog80t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

100%
</blockquote></details>

Agreed
___
*[`integration-tests/ibc/transfer_test.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTHE44rjOMFxkRTYC:-NUgL1Ax2PyTUD_9YXF9:b-153l7t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same question
</blockquote></details>

Try to this here.
___
*[`integration-tests/ibc/transfer_test.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTfEbA4eSt7kTOXFc:-NUgLAE157XFoYEY-gqQ:bx9f9oe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you need the `.WithBroadcastMode(flags.BroadcastBlock)`? It's already set in the into, right? 
</blockquote></details>

will remove it
___
*[`integration-tests/ibc/transfer_test.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfztCa-Ml3m7Is4UEf:-NUgMEo_DBTW0oW2yoP7:b-5a48v2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L84)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO it is more reasonable to assert that `sendCoin` is equal to balance
</blockquote></details>

maybe call `ibcAmount` `expectedIBCCoin`
also check to see if there is a way to get the ibc denom name and call `AmountOf`
___
*[`integration-tests/ibc/transfer_test.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUg-Du_34GaaCbLZ7g1:-NUgMZ4XECO42i9XhL74:b-z46wo9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L84)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to get balance from slice of coins it is better to use  `balancesRecipient.Balances.AmountOf(denom)` IMO
</blockquote></details>

discussed above


<!-- Sent from Reviewable.io -->

2023-05-08 11:33 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 164 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSViq4bwk1KFuoLsU:-NUuCC9c-sOrpyZt3Amo:b-mrgzuk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/chain.go#L164)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

discussed earlier
</blockquote></details>

we decided to keep it. 
___
*[`integration-tests/gaia.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxHJ25PDojcJP7F8A:-NUuCDw1AU1BEN2ZsdM0:b-onnwvj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/gaia.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

discused in call. 
</blockquote></details>

we decided to keep it as it is. 
___
*[`integration-tests/init.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfxUjQ9JGkn2IqhpWQ:-NUuNlGf0HEAlyWMzCn3:buls8et) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L60)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

discussed in the call. 
</blockquote></details>

we decided not to do it.
___
*[`integration-tests/init.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaSfUL9GDtrq1DF-NU:-NUuZ0GwANo9s_i8gvpL:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L70)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Agreed. Will do
</blockquote></details>

Done
___
*[`integration-tests/init.go` line 162 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaT2Em-jad4Tv2oFLP:-NUuZ2Wy7eEjNJs6qKZC:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/init.go#L162)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If I remove TestMain, how can I wait for the channels to come online. 
</blockquote></details>

Done
___
*[`integration-tests/ibc/main_test.go` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQL8QALAuYivQFMHb:-NUuZ6QZ5SeB5_CQWvjB:bul9m2u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Agreed. 
</blockquote></details>

Done, according to the diccussion we had on the call. 
___
*[`integration-tests/ibc/main_test.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaQoJE2qBPS5knm2V5:-NUtrEmn9pFuL-tM5rwo:b-3x32g8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`stablish` - typo.
</blockquote></details>

but there is not a typo !?
___
*[`integration-tests/ibc/main_test.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaRbQl88Q6zWp13IQo:-NUuZUYW4MYT4O9Ee2HR:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/main_test.go#L58)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Done
___
*[`integration-tests/ibc/transfer_test.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUg0NGsEnW-HYw_sZ0U:-NUtrLA7A0pkeZvFMZL2:b32wtd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

leaving this comment for myself 
still reviewing this file
</blockquote></details>

ok
___
*[`integration-tests/ibc/transfer_test.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTHE44rjOMFxkRTYC:-NUttUTB6lG14wBtw9HH:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Try to this here.
</blockquote></details>

Done
___
*[`integration-tests/ibc/transfer_test.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUaTfEbA4eSt7kTOXFc:-NUttYhv02sa8KWC5ryk:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L54)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

will remove it
</blockquote></details>

Done
___
*[`integration-tests/ibc/transfer_test.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUfztCa-Ml3m7Is4UEf:-NUuAxqF4JpoK2lREj1H:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L84)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

maybe call `ibcAmount` `expectedIBCCoin`
also check to see if there is a way to get the ibc denom name and call `AmountOf`
</blockquote></details>

done
___
*[`integration-tests/ibc/transfer_test.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NUg-Du_34GaaCbLZ7g1:-NUuAz3O9VQGisaCa_ho:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e7034f5342193bb70b7e80e4035d8e0b3d94bf1a/integration-tests/ibc/transfer_test.go#L84)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

discussed above
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-05-08 12:00 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-08 15:32 UTC, ysv reviewed
> Reviewed 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-05-09 08:30 UTC, dzmitryhil approved these changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-05-10 11:26 UTC, wojtek-coreum requested changes
> Reviewed 5 of 10 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`.github/workflows/ci.yml` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4LMBp9hDFXO1zTye-:-NV4LMBqCmmVaMQNOeBt:b-8zoomp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/.github/workflows/ci.yml#L19)):*
> ```YAML
>           "build", 
>           "integration tests coreum-modules", 
>           # "integration tests coreum-upgrade", 
> ```

why is it blocked?
___
*[`integration-tests/init.go` line 124 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4MNEa9DESDGkz5gKE:-NV4MNEa9DESDGkz5gKF:b-rmv9g3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/init.go#L124)):*
> ```Go
> 	}
> 
> 	gaiaCtx := client.NewContext(client.DefaultContextConfig(), app.ModuleBasics).
> ```

Using `app.ModuleBasics` is not a good idea as it contains modules not used by gaia
___
*[`integration-tests/ibc/helpers.go` line 34 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4OdfJ8iFinkKFdR0p:-NV4OdfJ8iFinkKFdR0q:b-chvaip) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/ibc/helpers.go#L34)):*
> ```Go
> 
> 	ibcChannelClient := ibcchanneltypes.NewQueryClient(clientCtx)
> 	var gaiaChannelID string
> ```

change it to sth like `readyChannels := map[string]struct{}{}`


<!-- Sent from Reviewable.io -->

2023-05-10 11:59 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4LMBp9hDFXO1zTye-:-NV4S5mmC9EuA5cPhcoS:beqgamb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it blocked?
</blockquote></details>

It's blocked since we need to implement multi step upgrade first. We decided to comment it now, and in the ` multi step upgrade` restore it.
___
*[`integration-tests/init.go` line 124 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4MNEa9DESDGkz5gKE:-NV4SOjY3MDNxoAFGvxX:bis219i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/init.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Using `app.ModuleBasics` is not a good idea as it contains modules not used by gaia
</blockquote></details>

Right, it's not precise, but good enough for your goals. Better to import the gaia as a dependency but I wouldn't do it until we find real need for it and keep the current approach.
___
*[`integration-tests/ibc/helpers.go` line 34 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4OdfJ8iFinkKFdR0p:-NV4WiFK03IhxkgZv639:b7ox2cq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/ibc/helpers.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

change it to sth like `readyChannels := map[string]struct{}{}`
</blockquote></details>

I didn't get how it will help, you need the particular chainID mapped to the particular chain.


<!-- Sent from Reviewable.io -->

2023-05-10 12:10 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @silverspase)

___
*[`.github/workflows/ci.yml` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4LMBp9hDFXO1zTye-:-NV4Ym8Z-uo6rtUbEUUS:b-951lz5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's blocked since we need to implement multi step upgrade first. We decided to comment it now, and in the ` multi step upgrade` restore it.
</blockquote></details>

But does this PR breaks the existing upgrade test? If yes, why?
___
*[`integration-tests/init.go` line 124 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4MNEa9DESDGkz5gKE:-NV4Yvjr3k3QIP_2ZbIV:b-9a4nbk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/init.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, it's not precise, but good enough for your goals. Better to import the gaia as a dependency but I wouldn't do it until we find real need for it and keep the current approach.
</blockquote></details>

I mean that maybe we should include only modules which are required for our operations. It's a client so it doesn't need to include everything. I guess that only auth module is required for transfers to work.
___
*[`integration-tests/ibc/helpers.go` line 34 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4OdfJ8iFinkKFdR0p:-NV4ZGMa1bvYQ5QTkOrC:b5s0ffe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/ibc/helpers.go#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get how it will help, you need the particular chainID mapped to the particular chain.
</blockquote></details>

I mean that comment below says:

```
		// currently we only expect gaia channel so the count should be 1
		// TODO: increase the expected value to 2 after we add osmosis
```

but entire logic here is hardcoded to support gaia only.


<!-- Sent from Reviewable.io -->

2023-05-10 13:42 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4LMBp9hDFXO1zTye-:-NV4sTESEcaoeU1nBxkr:bnxnmtt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But does this PR breaks the existing upgrade test? If yes, why?
</blockquote></details>

Explained
___
*[`integration-tests/init.go` line 124 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4MNEa9DESDGkz5gKE:-NV4sUD91qHY-l3NZK0H:b-xbl2da) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/init.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean that maybe we should include only modules which are required for our operations. It's a client so it doesn't need to include everything. I guess that only auth module is required for transfers to work.
</blockquote></details>

Decided to keep it as is
___
*[`integration-tests/ibc/helpers.go` line 34 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/483#-NV4OdfJ8iFinkKFdR0p:-NV4tUVFD8rbZxbNA-nK:bbkrsot) ([raw file](https://github.com/CoreumFoundation/coreum/blob/00983851ef2cb8a564d296a892c49803042a16ca/integration-tests/ibc/helpers.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean that comment below says:

```
		// currently we only expect gaia channel so the count should be 1
		// TODO: increase the expected value to 2 after we add osmosis
```

but entire logic here is hardcoded to support gaia only.
</blockquote></details>

Remvoed the comment


<!-- Sent from Reviewable.io -->

2023-05-10 13:42 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-10 13:42 UTC, dzmitryhil submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-10 14:10 UTC, dzmitryhil approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-11 06:22 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-11 06:47 UTC, merged