Handle whitelisting and freezing for successful IBC transfers
CoreumFoundation/coreum pull request #499
Opened 2023-05-19 11:52 UTC by wojtek-coreum

2023-05-22 08:16 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 293 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1ViaW-NqlMKEt4Ib1:-NW1ViaXDY52_mrnturL:btyccnt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/integration-tests/ibc/asset_ft_test.go#L293)):*
> ```Go
> 
> 	sendCoin := sdk.NewCoin(denom, sdk.NewInt(1000))
> 	halfCoin := sdk.NewCoin(denom, sdk.NewInt(500))
> ```

I would call it frozenCoin or similar, to highlight the purpose.
___
*[`integration-tests/ibc/asset_ft_test.go` line 476 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1WSSs7pUIKcp_Q1In:-NW1WSSs7pUIKcp_Q1Io:bkoy9s8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/integration-tests/ibc/asset_ft_test.go#L476)):*
> ```Go
> 
> 	// send coins back to coreum, it should fail
> 	_, err = gaiaChain.ExecuteIBCTransfer(ctx, gaiaRecipient, ibcSendCoin, coreumChain.ChainContext, coreumIssuer)
> ```

I would propose here to send to the issuer and normal account as well.
___
*[`integration-tests/ibc/asset_ft_test.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1WdTT90VxbK8FW6i7:-NW1WdTT90VxbK8FW6i8:b7h0u5b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/integration-tests/ibc/asset_ft_test.go#L506)):*
> ```Go
> 	requireT.NoError(coreumChain.AwaitForBalance(ctx, coreumIssuer, sendCoin))
> }
> ```

What about the additional test to send to the blocked address on the peer chain?
___
*[`x/asset/ft/keeper/before_send_test.go` line 316 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1SykgAfTHIreLdJcu:-NW1SykgAfTHIreLdJcv:b-fsgb5w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/02a8289afe132b0b973aacc7dd972eb1a63563c7/x/asset/ft/keeper/before_send_test.go#L316)):*
> ```Go
> 		},
> 		{
> 			name: "issuer_sender_ibc_escrow_sender_ibc_escrow_receiver",
> ```

What was the reason to remvoe that test?
___
*[`x/wibc/info.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1PYoI-s1m3E7eDvDI:-NW1PYoI-s1m3E7eDvDJ:bl1wfdw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L1)):*
> ```Go
> package wibc
> ```

I would call the file, `trace` and struct `Info` -> `PackageTrace` (same for the methods). So it would be the `wibc.PackageTrace`. Which is more precise IMO.
___
*[`x/wibc/info.go` line 48 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1Rxd024cMFrTBLt88:-NW1Rxd024cMFrTBLt89:bnyy1qn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L48)):*
> ```Go
> 
> // NewInfoMiddleware returns new info middleware.
> func NewInfoMiddleware(module porttypes.IBCModule, action Action) InfoMiddleware {
> ```

IMO it's better to have the constructor method, just after the type declaration, not before. 
___
*[`x/wibc/info.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1RuNuEvxMIp3zook8:-NW1RuNuEvxMIp3zook9:bx0tkln) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L56)):*
> ```Go
> 
> // InfoMiddleware adds information about IBC port and channel of the received packet to the context.
> type InfoMiddleware struct {
> ```

Why don't you use the embeded struct here? You could remove a lot of methods in that case. 
___
*[`x/wibc/info.go` line 105 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1UeeDAavTVeI1yx5_:-NW1UeeDAavTVeI1yx5a:b8b52lh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L105)):*
> ```Go
> 
> // OnAcknowledgementPacket simply calls the implementation of the wrapped module.
> func (im InfoMiddleware) OnAcknowledgementPacket(ctx sdk.Context, packet channeltypes.Packet, acknowledgement []byte, relayer sdk.AccAddress) error {
> ```

Could you please explain why don't we need to intercept the `OnAcknowledgementPacket` and `OnTimeoutPacket` for the case when an account was unwhitelisted and then the transfer ibc tx is rolled back.
___
*[`x/wibctransfer/types/action.go` line 7 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1QxhnDSVQ1pIzWuub:-NW1QxhnDSVQ1pIzWuuc:b-j9o9j8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibctransfer/types/action.go#L7)):*
> ```Go
> const (
> 	// ActionOut is used when IBC transfer to another chain is initialized by executing ibctransfertypes.MsgTransfer message.
> 	ActionOut wibc.Action = "ibcTransferOut"
> ```

IMO it's not very clear when the enum is defined in one package but, the values are in different. They should be near otherwise no need ti use the enum. 


<!-- Sent from Reviewable.io -->

2023-05-22 08:17 UTC, dzmitryhil reviewed
> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-22 10:16 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 506 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1WdTT90VxbK8FW6i7:-NW1wWQDCX3-fhZ0RSA0:b-i3dnaq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/integration-tests/ibc/asset_ft_test.go#L506)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the additional test to send to the blocked address on the peer chain?
</blockquote></details>

Failing IBC transfer tests will be added in another PR
___
*[`x/asset/ft/keeper/before_send_test.go` line 316 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1SykgAfTHIreLdJcu:-NW1wdc35rOG88yHZ6kE:bprz86p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/02a8289afe132b0b973aacc7dd972eb1a63563c7/x/asset/ft/keeper/before_send_test.go#L316)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What was the reason to remvoe that test?
</blockquote></details>

Because the situation where escrow address sends funds to escrow address is impossible. There is no such logic in IBC module.
___
*[`x/wibc/info.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1RuNuEvxMIp3zook8:-NW1wybG9ImfEI57l3Rc:bgecyp4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you use the embeded struct here? You could remove a lot of methods in that case. 
</blockquote></details>

Because in that case this logic would work only with transfer module
___
*[`x/wibc/info.go` line 105 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1UeeDAavTVeI1yx5_:-NW1x86W3EPDq4w5pR82:b-cvrwqn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L105)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why don't we need to intercept the `OnAcknowledgementPacket` and `OnTimeoutPacket` for the case when an account was unwhitelisted and then the transfer ibc tx is rolled back.
</blockquote></details>

We need to do this. Failing IBC transfers will be supported in the next PR.
___
*[`x/wibctransfer/types/action.go` line 7 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1QxhnDSVQ1pIzWuub:-NW1xFXIAj0e7_UNLHSR:b-ko4xjd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibctransfer/types/action.go#L7)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO it's not very clear when the enum is defined in one package but, the values are in different. They should be near otherwise no need ti use the enum. 
</blockquote></details>

The logic for intercepting the transfer is common to any IBC module but actions are specific to the module.


<!-- Sent from Reviewable.io -->

2023-05-22 10:48 UTC, miladz68 requested changes
> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 708 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW20ojnCT0bAKqtwvZ5:-NW20ojnCT0bAKqtwvZ6:b-iev9cm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/asset/ft/keeper/keeper.go#L708)):*
> ```Go
> }
> 
> func isIBCAction(ctx sdk.Context, action wibc.Action) bool {
> ```

I think having 2 function is more reasonable here than having 2 enum types. 
the 2 functions can be called. `isTokenReceive` and `isTokenSend`, or something better could be found. 

I think the most accurate naming is `isIBCTokenTransferOut` and `isIBCPacketIn`
___
*[`x/wibc/info.go` line 43 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW21fVSAjuXcH23slPQ:-NW21fVT5qRhvqwix2kY:b-waxobq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L43)):*
> ```Go
> 
> // WithGOInfo stores IBC info inside GO context.
> func WithGOInfo(ctx context.Context, info Info) context.Context {
> ```

This function is used once inside module.
firstly I think it should not be defined, since it is only used once. if you disagree, at least it should not be exported
also it should Go, not GO
___
*[`x/wibc/info.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW22SBt3D40OUrMkijR:-NW22SBt3D40OUrMkijS:bp9wq5l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L58)):*
> ```Go
> type InfoMiddleware struct {
> 	module porttypes.IBCModule
> 	action Action
> ```

I don't think the action should be part of the struct. just use it directly in OnRecvPacket


<!-- Sent from Reviewable.io -->

2023-05-22 11:32 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/wibc/info.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW22SBt3D40OUrMkijR:-NW2DrOhD4vjNzaNQEAq:b6b69sj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L58)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think the action should be part of the struct. just use it directly in OnRecvPacket
</blockquote></details>

I don't understand this comment


<!-- Sent from Reviewable.io -->

2023-05-22 12:44 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 10 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/wibc/info.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW22SBt3D40OUrMkijR:-NW2Tj5I-uUeNIlYZZmo:bposvyw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand this comment
</blockquote></details>

you introduce action into the struct and keep it there. you later used it in `onRecvPacket` method. the only acceptable value to be used on that function is `ActionIn`. instead of passing it to the struct and then pass it to the method, just the value directly in `onRecvPacket` method. 


<!-- Sent from Reviewable.io -->

2023-05-22 18:01 UTC, ysv requested changes
> Reviewed 8 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper.go` line 708 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW20ojnCT0bAKqtwvZ5:-NW3TBsA2LwYt8f31gCG:bowlggb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/asset/ft/keeper/keeper.go#L708)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think having 2 function is more reasonable here than having 2 enum types. 
the 2 functions can be called. `isTokenReceive` and `isTokenSend`, or something better could be found. 

I think the most accurate naming is `isIBCTokenTransferOut` and `isIBCPacketIn`
</blockquote></details>

I agree with Milad's idea here
We should expose as abstract interface from wibc module as possible without defining internals of how/what is stored inside context

IMO proper methods to be exposed by wibc is (like Milad mentioned):
```
func isIBCTokenTransferOut(ctx sdk.Context) bool {}
func isIBCTokenTransferIn(ctx sdk.Context) bool {}
```

& things like GetInfo, Info etc are internal stuff
___
*[`x/wibc/info.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW2UgMTAQfC05UR4tBz:-NW2UgMTAQfC05UR4tC-:b-bmc2vn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L1)):*
> ```Go
> package wibc
> ```

also I disagree with `wibc` name here
You don't really wrap/override whole IBC module but just introduce a middleware to inject additional info
___
*[`x/wibc/info.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1RuNuEvxMIp3zook8:-NW2VdBa9pnTkb3tJs5w:b-d73uya) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please elaborate a bit on it, I didn't get it.
</blockquote></details>

I'm not sure if this  approach will work but it is a good option & worth trying IMO

Upd:
Tried locally Seems to be working fine for me:
```
// InfoMiddleware adds information about IBC port and channel of the received packet to the context.
type InfoMiddleware struct {
	porttypes.IBCModule
	action Action
}
```
This way you don't need to copy all methods but only ones which are overridden 
___
*[`x/wibc/info.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW22SBt3D40OUrMkijR:-NW3_ywoAAuZn2eGxTpC:b95extv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L58)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you introduce action into the struct and keep it there. you later used it in `onRecvPacket` method. the only acceptable value to be used on that function is `ActionIn`. instead of passing it to the struct and then pass it to the method, just the value directly in `onRecvPacket` method. 
</blockquote></details>

I agree with Milad don't see a point to store `action Action` inside `InfoMiddleware`
___
*[`x/wibctransfer/keeper/keeper.go` line 23 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW3adbi8OS3hvOJpt1E:-NW3adbi8OS3hvOJpt1F:brivdkc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibctransfer/keeper/keeper.go#L23)):*
> ```Go
> 
> // NewKeeper returns a new Wrapper instance.
> func NewKeeper(
> ```

NewKeeper method returns Wrapper. I think either method or structure should be renamed

what about  smth like `TransferKeeperWrapper` ?

At least inside wbank we had this kind of naming convention 
___
*[`x/wibctransfer/types/action.go` line 7 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1QxhnDSVQ1pIzWuub:-NW3bOLg3xbvWfebiUd_:bww0ggf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibctransfer/types/action.go#L7)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In that case, the Action should be either string or interface. 
</blockquote></details>

I tend to agree with Dzmitry
Feels like we should put the whole thingy into a single module or do smth else with it

Lets discuss


<!-- Sent from Reviewable.io -->

2023-05-23 07:12 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: 4 of 13 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/before_send_test.go` line 316 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1SykgAfTHIreLdJcu:-NW6Pofi-0Boi4W4Rtuo:b5d4fqo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/02a8289afe132b0b973aacc7dd972eb1a63563c7/x/asset/ft/keeper/before_send_test.go#L316)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the case of when I send back coins from the chain and the destination is the escrow address?
</blockquote></details>

then the source is not escrow
___
*[`x/asset/ft/keeper/keeper.go` line 708 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW20ojnCT0bAKqtwvZ5:-NW6R3td3wOMLEXdzjG2:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/asset/ft/keeper/keeper.go#L708)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Milad's idea here
We should expose as abstract interface from wibc module as possible without defining internals of how/what is stored inside context

IMO proper methods to be exposed by wibc is (like Milad mentioned):
```
func isIBCTokenTransferOut(ctx sdk.Context) bool {}
func isIBCTokenTransferIn(ctx sdk.Context) bool {}
```

& things like GetInfo, Info etc are internal stuff
</blockquote></details>

Done.
___
*[`x/wibctransfer/keeper/keeper.go` line 23 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW3adbi8OS3hvOJpt1E:-NW6RGmj7LWPIVKUcKua:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibctransfer/keeper/keeper.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

NewKeeper method returns Wrapper. I think either method or structure should be renamed

what about  smth like `TransferKeeperWrapper` ?

At least inside wbank we had this kind of naming convention 
</blockquote></details>

Done.
___
*[`x/wibc/info.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1PYoI-s1m3E7eDvDI:-NW6RIjFDF2C0NpPmUH4:b-6b78t0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would call the file, `trace` and struct `Info` -> `PackageTrace` (same for the methods). So it would be the `wibc.PackageTrace`. Which is more precise IMO.
</blockquote></details>

I redone it completely
___
*[`x/wibc/info.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW2UgMTAQfC05UR4tBz:-NW6RMHQ7Qm_wsk_YchZ:b-6b78t0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

also I disagree with `wibc` name here
You don't really wrap/override whole IBC module but just introduce a middleware to inject additional info
</blockquote></details>

I redone it completely
___
*[`x/wibc/info.go` line 43 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW21fVSAjuXcH23slPQ:-NW6RTgZ0u4rUGrEQO6V:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L43)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This function is used once inside module.
firstly I think it should not be defined, since it is only used once. if you disagree, at least it should not be exported
also it should Go, not GO
</blockquote></details>

Done.
___
*[`x/wibc/info.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1RuNuEvxMIp3zook8:-NW6Rdu76TNEyjmWeOw_:b-4djp47) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L56)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm not sure if this  approach will work but it is a good option & worth trying IMO

Upd:
Tried locally Seems to be working fine for me:
```
// InfoMiddleware adds information about IBC port and channel of the received packet to the context.
type InfoMiddleware struct {
	porttypes.IBCModule
	action Action
}
```
This way you don't need to copy all methods but only ones which are overridden 
</blockquote></details>

I redone this completely
___
*[`x/wibc/info.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW22SBt3D40OUrMkijR:-NW6RjIo0n9v4x1aRaGT:b-4djp47) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibc/info.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Milad don't see a point to store `action Action` inside `InfoMiddleware`
</blockquote></details>

I redone this completely
___
*[`x/wibctransfer/types/action.go` line 7 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1QxhnDSVQ1pIzWuub:-NW6Ro3x2nWyWg8-O68Z:b-4djp47) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/x/wibctransfer/types/action.go#L7)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I tend to agree with Dzmitry
Feels like we should put the whole thingy into a single module or do smth else with it

Lets discuss
</blockquote></details>

I redone this completely


<!-- Sent from Reviewable.io -->

2023-05-23 07:18 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: 3 of 14 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 476 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW1WSSs7pUIKcp_Q1In:-NW6TJLZ683CE9v2OACE:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60e9bbb8c337201e4f3f09c4b91b1be95988daa2/integration-tests/ibc/asset_ft_test.go#L476)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would propose here to send to the issuer and normal account as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-23 11:07 UTC, dzmitryhil requested changes
> Reviewed 3 of 9 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/wibctransfer/middleware.go` line 37 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7FJx7Ay2pSWHIbelF:-NW7FJx7Ay2pSWHIbelG:b5vtu1o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/wibctransfer/middleware.go#L37)):*
> ```Go
> 
> // IsDirectionOut returns true if context is tagged with an outgoing transfer.
> func IsDirectionOut(ctx sdk.Context) bool {
> ```

IMO both `func IsDirectionOut(ctx sdk.Context) bool {` and `func IsDirectionIn(ctx sdk.Context) bool {` should be in the `types/direction.go`.


<!-- Sent from Reviewable.io -->

2023-05-23 11:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/wibctransfer/middleware.go` line 37 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7FJx7Ay2pSWHIbelF:-NW7J52iCe3iH2PIsk4r:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/wibctransfer/middleware.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO both `func IsDirectionOut(ctx sdk.Context) bool {` and `func IsDirectionIn(ctx sdk.Context) bool {` should be in the `types/direction.go`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-23 11:49 UTC, ysv requested changes
> Reviewed 3 of 9 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/ibc/asset_ft_test.go` line 154 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7QXO5DbiR7xmym3XG:-NW7QXO5DbiR7xmym3XH:bvao5u8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/269eb8664427206b28cefa69f8b266e55aeba9eb/integration-tests/ibc/asset_ft_test.go#L154)):*
> ```Go
> 	)
> }
> ```

IMO one missing test case is IBC send to escrow
Should we add it in this PR or later ?
___
*[`integration-tests/ibc/asset_ft_test.go` line 384 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7Q9af9FvAccY8UfEW:-NW7Q9af9FvAccY8UfEX:b51r4ja) ([raw file](https://github.com/CoreumFoundation/coreum/blob/269eb8664427206b28cefa69f8b266e55aeba9eb/integration-tests/ibc/asset_ft_test.go#L384)):*
> ```Go
> 	coreumToGaiaEscrowAddress := ibctransfertypes.GetEscrowAddress(ibctransfertypes.PortID, coreumToGaiaChannelID)
> 
> 	freezeMsg := &assetfttypes.MsgFreeze{
> ```

more realistic case is to send to escrow first and after this freeze because issuer is unlikely to freeze balance with 0

This should affect test much but makes it more realistic
___
*[`x/asset/ft/keeper/before_send.go` line 138 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7Nm9W8jLnBfkDWbFr:-NW7Nm9W8jLnBfkDWbFs:bre39dd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/269eb8664427206b28cefa69f8b266e55aeba9eb/x/asset/ft/keeper/before_send.go#L138)):*
> ```Go
> 		return nil
> 	}
> 	if wibctransfertypes.IsDirectionIn(ctx) {
> ```

minor: merge with previous if `rate.IsNil() || !rate.IsPositive() ||  wibctransfertypes.IsDirectionIn(ctx)` ?
___
*[`x/asset/ft/keeper/before_send.go` line 138 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7O-CECuV7n_l1mFYM:-NW7O-CECuV7n_l1mFYN:b33qb9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/269eb8664427206b28cefa69f8b266e55aeba9eb/x/asset/ft/keeper/before_send.go#L138)):*
> ```Go
> 		return nil
> 	}
> 	if wibctransfertypes.IsDirectionIn(ctx) {
> ```

DirectionIn here means coming into coreum chain right ?
___
*[`x/asset/ft/keeper/before_send_test.go` line 350 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7MotWEAyA7dpOj7kF:-NW7MotWEAyA7dpOj7kG:b-rgeub4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/asset/ft/keeper/before_send_test.go#L350)):*
> ```Go
> 			}
> 			if _, exists := tc.receivers[ibcEscrowAddress]; exists {
> 				ctx = wibctransfertypes.WithDirection(ctx, wibctransfertypes.DirectionOut)
> ```

if you define both here DirectionOut will override DirectionIn right ?

what will happen if someone sends IBC transfer to escrow account ?
___
*[`x/wibctransfer/middleware.go` line 42 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7KAGm26LdVQqnD2PQ:-NW7KAGm26LdVQqnD2PR:b-sgn2k2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/wibctransfer/middleware.go#L42)):*
> ```Go
> 		return false
> 	}
> 	return d == types.DirectionOut
> ```

`return ok && direction == types.DirectionOut`
___
*[`x/wibctransfer/keeper/keeper.go` line 42 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7LT8qAgP1N4t1WmfD:-NW7LT8qAgP1N4t1WmfE:bdr5urz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/wibctransfer/keeper/keeper.go#L42)):*
> ```Go
> func (k TransferKeeperWrapper) Transfer(goCtx context.Context, msg *ibctransfertypes.MsgTransfer) (*ibctransfertypes.MsgTransferResponse, error) {
> 	//nolint:contextcheck // it is fine to produce the context this way
> 	return k.Keeper.Transfer(sdk.WrapSDKContext(types.WithDirection(sdk.UnwrapSDKContext(goCtx), types.DirectionOut)), msg)
> ```

non-blocking:
I would probably split this into 2 lines:
1. init new context
2. return & call to transfer

Looks a bit overcomplicated
___
*[`x/wibctransfer/types/direction.go` line 14 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7Lm3S65_GA2GQitJN:-NW7Lm3S65_GA2GQitJO:btf5ig8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/wibctransfer/types/direction.go#L14)):*
> ```Go
> const (
> 	// DirectionOut is used when IBC transfer to another chain is initialized by executing ibctransfertypes.MsgTransfer message.
> 	DirectionOut Direction = "ibcTransferOut"
> ```

question: these values `ibcTransferOut` & `ibcTransferIn` are fully defined by you right ? 
they are not from IBC module 
___
*[`x/wibctransfer/types/direction.go` line 16 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7OJrW29H9QP9EjkDT:-NW7OJrW29H9QP9EjkDU:b-e4qz3o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/269eb8664427206b28cefa69f8b266e55aeba9eb/x/wibctransfer/types/direction.go#L16)):*
> ```Go
> 	DirectionOut Direction = "ibcTransferOut"
> 	// DirectionIn is used when incoming IBC transfer comes to the target chain.
> 	DirectionIn Direction = "ibcTransferIn"
> ```

maybe to simplify it we should define direction relating it to escrow account:

EscrowDirectionIn - funds incoming to escrow acc
EscrowDirectionOut - funds outgoing from escrow acc

I find it a bit simpler to understand. WDYT ?


<!-- Sent from Reviewable.io -->

2023-05-23 12:58 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: 11 of 14 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 138 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7Nm9W8jLnBfkDWbFr:-NW7fBX8C9YP2CoqtUtL:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/x/asset/ft/keeper/before_send.go#L138)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: merge with previous if `rate.IsNil() || !rate.IsPositive() ||  wibctransfertypes.IsDirectionIn(ctx)` ?
</blockquote></details>

Done
___
*[`x/wibctransfer/middleware.go` line 42 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7KAGm26LdVQqnD2PQ:-NW7fZsIA-9I891ySPhy:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/wibctransfer/middleware.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`return ok && direction == types.DirectionOut`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-23 16:46 UTC, ysv requested changes
> Reviewed 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/ibc/asset_ft_test.go` line 154 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7QXO5DbiR7xmym3XG:-NW8VCaP-_FIZVUwk3ck:b-ikwhzb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/integration-tests/ibc/asset_ft_test.go#L154)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We don't need it IMO. Escrow address in this case is like any other account. BC doesn't even know it's an escrow account.
</blockquote></details>

IMO it is reasonable to make sure that DirectionOut overrides DirectionIn but not vice versa
Also it is edge case which is important to test
___
*[`integration-tests/ibc/asset_ft_test.go` line 384 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7Q9af9FvAccY8UfEW:-NW8TvvM0MPcegkmbGzq:b-1kkv1i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/integration-tests/ibc/asset_ft_test.go#L384)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The test case here verifies that when funds go back to our chain the transfer succeeds despite the fact that escrow address is frozen. It doesn't matter when the freezing is done.
</blockquote></details>

yes but is just more realistic scenario
___
*[`x/asset/ft/keeper/before_send_test.go` line 350 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7MotWEAyA7dpOj7kF:-NW8UN42-aXTtRAaRHzg:b-n2xrvb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/asset/ft/keeper/before_send_test.go#L350)):*
> in that case escrow address is treated like any other account

Do you have a proper place to put this as comment ? That DirectionOut will override DirectionIn
___
*[`x/wibctransfer/types/direction.go` line 16 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7OJrW29H9QP9EjkDT:-NW8Ug5n7QgSj3YdCuOQ:b-hqgtqi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/x/wibctransfer/types/direction.go#L16)):*
Ok, then I suggest to improve comments here a bit to mention Coreum so it is more clear
 
> DirectionIn is used when incoming IBC transfer comes to the target chain.
 when IBC transfer comes from peer chain to Coreum

> DirectionOut is used when IBC transfer to another chain is initialized by executing ibctransfertypes.MsgTransfer message.

when IBC transfer from Coreum to another chain


<!-- Sent from Reviewable.io -->

2023-05-23 16:47 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/wibctransfer/types/direction.go` line 16 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7OJrW29H9QP9EjkDT:-NW8VSyj0vZs-JFKETYK:b57kvvb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/x/wibctransfer/types/direction.go#L16)):*
> DirectionIn is used when incoming IBC transfer comes to the target chain.  

when IBC transfer comes from peer chain to Coreum


<!-- Sent from Reviewable.io -->

2023-05-24 09:12 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 154 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7QXO5DbiR7xmym3XG:-NWC-60m2fkGLFgVrD-A:b2ckulz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/integration-tests/ibc/asset_ft_test.go#L154)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO it is reasonable to make sure that DirectionOut overrides DirectionIn but not vice versa
Also it is edge case which is important to test
</blockquote></details>

Let's discuss after daily
___
*[`integration-tests/ibc/asset_ft_test.go` line 384 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7Q9af9FvAccY8UfEW:-NWC0AvI-AieH1nF17gr:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/integration-tests/ibc/asset_ft_test.go#L384)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes but is just more realistic scenario
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send_test.go` line 350 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7MotWEAyA7dpOj7kF:-NWC0FfT41Va4tzCNzcp:b-7qossy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/asset/ft/keeper/before_send_test.go#L350)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> in that case escrow address is treated like any other account

Do you have a proper place to put this as comment ? That DirectionOut will override DirectionIn
</blockquote></details>

It's not like DirectionOut overrides DirectionIn. When IBC transfer is received then the receiver is treated like a normal address and all the ft features are applied normally.
___
*[`x/wibctransfer/types/direction.go` line 16 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7OJrW29H9QP9EjkDT:-NWC0tZP8ZQj2-sdVoq4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/x/wibctransfer/types/direction.go#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> DirectionIn is used when incoming IBC transfer comes to the target chain.  

when IBC transfer comes from peer chain to Coreum
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-24 09:20 UTC, ysv requested changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/ibc/asset_ft_test.go` line 154 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7QXO5DbiR7xmym3XG:-NWC2gvO2IMohyffVWOn:b32wtd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c0cb2714c82da1e204470f63df1358aa99ac720/integration-tests/ibc/asset_ft_test.go#L154)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's discuss after daily
</blockquote></details>

ok
___
*[`x/asset/ft/keeper/before_send_test.go` line 350 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7MotWEAyA7dpOj7kF:-NWC2VZhBYfNy4ipPF5C:b-mb9a97) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/asset/ft/keeper/before_send_test.go#L350)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not like DirectionOut overrides DirectionIn. When IBC transfer is received then the receiver is treated like a normal address and all the ft features are applied normally.
</blockquote></details>

Lets discuss after daily also


<!-- Sent from Reviewable.io -->

2023-05-24 10:06 UTC, miladz68 approved these changes
> Reviewed 3 of 9 files at r4, 3 of 6 files at r5, 2 of 4 files at r8, 2 of 3 files at r9, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-05-24 10:51 UTC, dzmitryhil approved these changes
> Reviewed 2 of 4 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-05-26 07:57 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`x/asset/ft/keeper/before_send_test.go` line 350 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7MotWEAyA7dpOj7kF:-NWM2I54B0k-0H-Dzh-v:b-4ki57j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/asset/ft/keeper/before_send_test.go#L350)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets discuss after daily also
</blockquote></details>

Lets change test to not mention escrow but have a flag to define if it is IBC transfer or not


<!-- Sent from Reviewable.io -->

2023-05-26 12:20 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`x/asset/ft/keeper/before_send_test.go` line 350 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NW7MotWEAyA7dpOj7kF:-NWN-HLQAvDyd5-Y9JIR:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb4be94667b26645f2b62d1d4e44b9036f4965eb/x/asset/ft/keeper/before_send_test.go#L350)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets change test to not mention escrow but have a flag to define if it is IBC transfer or not
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-29 08:55 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r12, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-29 08:55 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-29 11:53 UTC, ysv requested changes
> Reviewed 1 of 1 files at r12, 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 191 at r18](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NWbL8Sg53y7UiWolTsj:-NWbL8Sg53y7UiWolTsk:blw0k8z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2d0f1491bbe018010baefcf29064044e9afed0f/integration-tests/chain.go#L191)):*
> ```Go
> 	)
> 
> 	return txRes, err
> ```

do you really need to have access to err in tests ?

because I thought the idea is to pass t into such helper functions & make assertions inside eg `ExecuteIBCTransfer`
___
*[`integration-tests/ibc/asset_ft_test.go` line 242 at r18](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NWbLQhL5W5O5udTKVxt:-NWbLQhL5W5O5udTKVxu:bhj9g89) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2d0f1491bbe018010baefcf29064044e9afed0f/integration-tests/ibc/asset_ft_test.go#L242)):*
> ```Go
> func TestIBCAssetFTFreezing(t *testing.T) {
> 	t.Parallel()
> 	t.Helper()
> ```

but it is not a helper but a real test, no ?
___
*[`integration-tests/ibc/asset_ft_test.go` line 336 at r18](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NWbLWptASS6JUCMf9U_:-NWbLWptASS6JUCMf9Ua:bhj9g89) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2d0f1491bbe018010baefcf29064044e9afed0f/integration-tests/ibc/asset_ft_test.go#L336)):*
> ```Go
> func TestEscrowAddressIsResistantToFreezingAndWhitelisting(t *testing.T) {
> 	t.Parallel()
> 	t.Helper()
> ```

but it is not a helper but a real test, no ?


<!-- Sent from Reviewable.io -->

2023-05-29 12:03 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`integration-tests/chain.go` line 191 at r18](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NWbL8Sg53y7UiWolTsj:-NWbNMo567ZIMuaaiy2W:b-e3aeco) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2d0f1491bbe018010baefcf29064044e9afed0f/integration-tests/chain.go#L191)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you really need to have access to err in tests ?

because I thought the idea is to pass t into such helper functions & make assertions inside eg `ExecuteIBCTransfer`
</blockquote></details>

Yes I really need it. In case of freezing I need to know that transfer failed without exiting the test
___
*[`integration-tests/ibc/asset_ft_test.go` line 242 at r18](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NWbLQhL5W5O5udTKVxt:-NWbNvk90QzrfWEusrfJ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2d0f1491bbe018010baefcf29064044e9afed0f/integration-tests/ibc/asset_ft_test.go#L242)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but it is not a helper but a real test, no ?
</blockquote></details>

Done.
___
*[`integration-tests/ibc/asset_ft_test.go` line 336 at r18](https://reviewable.io/reviews/CoreumFoundation/coreum/499#-NWbLWptASS6JUCMf9U_:-NWbNvQv1Sx97xNJdawz:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2d0f1491bbe018010baefcf29064044e9afed0f/integration-tests/ibc/asset_ft_test.go#L336)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but it is not a helper but a real test, no ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 09:26 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-31 09:19 UTC, miladz68 approved these changes
> Reviewed 2 of 3 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-31 09:27 UTC, dzmitryhil approved these changes
> Reviewed 1 of 1 files at r12, 2 of 3 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-05-31 09:38 UTC, merged