PoC: Delayed message for enabling IBC
CoreumFoundation/coreum pull request #510
Opened 2023-05-24 16:54 UTC by wojtek-coreum

2023-05-26 08:21 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 515 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzKug9wIsZ1QnZ7Nu:-NWLzKug9wIsZ1QnZ7Nv:bnes6fi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/app/app.go#L515)):*
> ```Go
> 
> 	delayRouter := delaytypes.NewRouter()
> 	delayRouter.RegisterMessage(&assetfttypes.MsgEnableIBCExecutor{}, assetfttypes.NewEnableIBCHandler(enableIBCKeeper))
> ```

Looks like a part of the constructor function.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzp1AELTp7pZBfJEd:-NWLzp1B0cBtGXEm0Rd_:b-x3ghju) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/pkg/config/genesis/genesis.tmpl.json#L31)):*
> ```JSON
>           "amount": "10000000"
>         },
>         "ibc_decision_timeout": "{{ .IBCDecisionTimeout }}",
> ```

@miladz68 @ysv 
IMO the timeouts should be generic for all features. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM2Dxg3vl2CrMkypka:-NWM2Dxg3vl2CrMkypkb:bvbv6ki) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ad0b04ee563e967efed1425424865f993bfdb79/proto/coreum/asset/ft/v1/tx.proto#L39)):*
> ```protobuf
> 
>   // SetWhitelistedLimit sets the limit of how many tokens a specific account may hold.
>   rpc SetWhitelistedLimit(MsgSetWhitelistedLimit) returns (EmptyResponse);
> ```

Why did you remove the `SetWhitelistedLimit`?
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr36w4v31roNu8Z8g:-NWLr36w4v31roNu8Z8h:bbkqmt5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/proto/coreum/asset/ft/v1/upgradev3.proto#L1)):*
> ```protobuf
> syntax = "proto3";
> ```

Why the file is called upgrade`V3` ?
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr9iRD6d6ux2OzTGT:-NWLr9iRD6d6ux2OzTGU:b-4zodl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
> ```protobuf
> 
> // MsgEnableIBCRequest means that sender wants to enable IBC for the token.
> message MsgEnableIBCRequest {
> ```

@ysv @miladz68 
Is it IBC specific, don't we want to make it more generic? IMO it should be generic from the very beginning, but in the handler depending on the Feature you might handle it differently. 
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLrF2H0unR_Q1dKGbh:-NWLrF2H0unR_Q1dKGbi:b-gro6pz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/proto/coreum/asset/ft/v1/upgradev3.proto#L16)):*
> ```protobuf
> 
> // MsgEnableIBCExecutor is executed by the delay module when it's time to enable IBC.
> message MsgEnableIBCExecutor {
> ```

What is the advantage of such design, comparing to the direct keeper call?
___
*[`x/asset/ft/keeper/upgradev3.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM3EziAldwSp_q1jsF:-NWM3EziAldwSp_q1jsG:bp03p4m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/asset/ft/keeper/upgradev3.go#L17)):*
> ```Go
> )
> 
> var ibcEnablePrefix = []byte("upgradev3ibcenable")
> ```

This is temp right?
___
*[`x/asset/ft/keeper/upgradev3.go` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM3IL212mO6Vwg-_Ty:-NWM3IL212mO6Vwg-_Tz:bn04v5w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/asset/ft/keeper/upgradev3.go#L25)):*
> ```Go
> 
> // EnableIBCKeeper provides functionality required by v3 upgrade.
> type EnableIBCKeeper struct {
> ```

IMO it should be a part of the current keeper, I don't see an advantage of having additional keeper. And if you make it more generic, you will leek much better.
___
*[`x/delay/module.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwfPw1Neu8d_tCdl-:-NWLwfPw1Neu8d_tCdl0:b-7obh0v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/module.go#L114)):*
> ```Go
> // ExportGenesis returns the exported genesis state as raw bytes for the delay module.
> func (am AppModule) ExportGenesis(ctx sdk.Context, cdc codec.JSONCodec) json.RawMessage {
> 	return nil
> ```

Leaving 
___
*[`x/delay/module.go` line 125 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvsLc8UiTEOlCc_ml:-NWLvsLc8UiTEOlCc_mm:b-p197be) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/module.go#L125)):*
> ```Go
> // EndBlock returns the end blocker for the delay module.
> func (am AppModule) EndBlock(ctx sdk.Context, _ abci.RequestEndBlock) []abci.ValidatorUpdate {
> 	msgs, err := am.keeper.MessagesToExecute(ctx)
> ```

IMO better to iterate and execute message one by one: read, execute, remove. 
___
*[`x/delay/module.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwFhQAFgd291PXcUR:-NWLwFhQAFgd291PXcUS:bhseco1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/module.go#L133)):*
> ```Go
> 		handler := am.router.Handler(m.Message)
> 		if handler == nil {
> 			panic(errors.Errorf("no handler for message %s found", proto.MessageName(m.Message)))
> ```

You shouldn't panic IMO, you should just skip such message. 
___
*[`x/delay/keeper/keeper.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvZrW7WEutfmV9NQz:-NWLvZrW7WEutfmV9NR-:b-ebdnth) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/keeper/keeper.go#L37)):*
> ```Go
> 
> // DelayMessage stores a message to be executed later.
> func (k Keeper) DelayMessage(ctx sdk.Context, id string, msg proto.Message, delay time.Duration) error {
> ```

Do you think we should rely on the id or generate it?
___
*[`x/delay/keeper/keeper.go` line 40 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLtnmn6HKQrgrDiPZj:-NWLtnmo2zBDReHjMR5-:b69we99) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/keeper/keeper.go#L40)):*
> ```Go
> 	execTime := ctx.BlockTime().Add(delay).Unix()
> 	if execTime < 0 {
> 		panic("there were no blockchains before 1970-01-01")
> ```

Why do you panic here and in the next function?
___
*[`x/delay/keeper/keeper.go` line 77 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvShSAizx3-PT3aks:-NWLvShSAizx3-PT3akt:b-yw3bku) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/keeper/keeper.go#L77)):*
> ```Go
> 	for ; iter.Valid(); iter.Next() {
> 		key := iter.Key()
> 		if len(key) < 8 {
> ```

Could you please explain the `8` usage in that keeper. 


<!-- Sent from Reviewable.io -->

2023-05-26 08:26 UTC, dzmitryhil reviewed
> Reviewed 23 of 26 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-26 08:26 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 14 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-05-26 08:31 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMANRa4yEnrG7fPWzm:-NWMANRa4yEnrG7fPWzn:bwehvaf) (no related file):*

Review that module please as well co compare your solution and this one: https://github.com/osmosis-labs/osmosis/tree/main/x/epochs

___
___
*[`x/delay/types/router.go` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMAksk7p37QY0c8m1s:-NWMAksk7p37QY0c8m1t:bpjh52p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05790cad2f74c1d857408ca1a45ded695e566ffe/x/delay/types/router.go#L45)):*
> ```Go
> // Handler returns a handler for a given message.
> func (rtr *router) Handler(msg proto.Message) Handler {
> 	msgName := proto.MessageName(msg)
> ```

What is the protection against Authz execution ?


<!-- Sent from Reviewable.io -->

2023-05-26 11:41 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 26 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 515 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzKug9wIsZ1QnZ7Nu:-NWMm80SCMZd7WSQVW0m:b-s3umnj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L515)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Looks like a part of the constructor function.
</blockquote></details>

I don't understand. govRouter is initialized the same way in app.go
___
*[`pkg/config/genesis/genesis.tmpl.json` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzp1AELTp7pZBfJEd:-NWMmEu_8YbZnQRdeyRG:b-obctl4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/pkg/config/genesis/genesis.tmpl.json#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@miladz68 @ysv 
IMO the timeouts should be generic for all features. 
</blockquote></details>

I don't think so. We should decide feature by feature. After applying the upgrade and once all the timeouts pass those params should be removed by the next upgrade
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM2Dxg3vl2CrMkypka:-NWMm_ah472R11T-MSNh:b20q5di) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6af0c870ace9e43487f7053664a0a69f989d0c81/proto/coreum/asset/ft/v1/tx.proto#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why did you remove the `SetWhitelistedLimit`?
</blockquote></details>

whoa... so that's why all the CIs failed :)
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr36w4v31roNu8Z8g:-NWMnKjj1GDAQgWfneVv:bbnio48) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the file is called upgrade`V3` ?
</blockquote></details>

Oh, we didn't apply v2 so far, right?
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr9iRD6d6ux2OzTGT:-NWMnf-M-31yscHZKXFd:b-78o0ys) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 
Is it IBC specific, don't we want to make it more generic? IMO it should be generic from the very beginning, but in the handler depending on the Feature you might handle it differently. 
</blockquote></details>

I don't see a point in making one-shot actions generic. This is "fire and forget" type of thing.
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLrF2H0unR_Q1dKGbh:-NWMo0xC95bm2b_mtGdx:bqxlw9x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the advantage of such design, comparing to the direct keeper call?
</blockquote></details>

This is a standard way how cosmos handles stuff like messages, proposals and invariants. Data container is defined to be stored in the store and when it is a time to take the action handler for that object is taken from some router and executed.
___
*[`x/asset/ft/keeper/upgradev3.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM3EziAldwSp_q1jsF:-NWMoNy77xlFuZKaXJN2:bslexy8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/asset/ft/keeper/upgradev3.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is temp right?
</blockquote></details>

yes, once all the timeouts pass it will be removed. That's why name is not like `0x03` because the vaue should never be reused accidentally.
___
*[`x/asset/ft/keeper/upgradev3.go` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM3IL212mO6Vwg-_Ty:-NWMoZZNBV0O-M7vRXUR:b-ak8bm3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/asset/ft/keeper/upgradev3.go#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO it should be a part of the current keeper, I don't see an advantage of having additional keeper. And if you make it more generic, you will leek much better.
</blockquote></details>

I want to clearly indicate what code should be removed in the next upgrade. Other way might be to use some standardized comment format like `// remove-in: v4`
___
*[`x/delay/module.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwfPw1Neu8d_tCdl-:-NWMopgABwkGqD0Ia8EU:b3kre) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L114)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Leaving 
</blockquote></details>

?
___
*[`x/delay/module.go` line 125 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvsLc8UiTEOlCc_ml:-NWMqz1w2Km9BirHHdWi:b-uelt8m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L125)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO better to iterate and execute message one by one: read, execute, remove. 
</blockquote></details>

That was the first version but then I found that each time store must be created in keeper. Not a big deal but this way must work too.
___
*[`x/delay/module.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwFhQAFgd291PXcUR:-NWMowQp1ia0d8RfM02a:byla5yt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L133)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You shouldn't panic IMO, you should just skip such message. 
</blockquote></details>

No. If error is returned here it means sth went really wrong meaning that blockchain might be left in some weird state leading to serious problems. 
___
*[`x/delay/keeper/keeper.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvZrW7WEutfmV9NQz:-NWMpDSZ3TC2iykxImtm:be82iab) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you think we should rely on the id or generate it?
</blockquote></details>

Each delayed message must contain unique id because otherwise there is no way to store all of the messages added in the same block. 
In the particular case of the IBC we could just take the hash of the message but I don't know if it might work in all the future cases.
___
*[`x/delay/keeper/keeper.go` line 40 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLtnmn6HKQrgrDiPZj:-NWMpsZY9KCHIM0Lccyh:b-bc2zm8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you panic here and in the next function?
</ [...]

2023-05-26 11:47 UTC, ysv requested changes
> Reviewed 23 of 26 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 26 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`app/app.go` line 118 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMkvqX3zNOr6eLYG1a:-NWMkvqX3zNOr6eLYG1b:bk7z5xi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L118)):*
> ```Go
> 	customparamskeeper "github.com/CoreumFoundation/coreum/x/customparams/keeper"
> 	customparamstypes "github.com/CoreumFoundation/coreum/x/customparams/types"
> 	"github.com/CoreumFoundation/coreum/x/delay"
> ```

My initial idea was to have this delay logic inside assetft. Similar to the way it is implemented inside gov. So we have a queue of pending migrations and once time is achieved we execute them.

I am not sure defining this module is beneficial but might be. 

Lets discuss
___
*[`app/app.go` line 515 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzKug9wIsZ1QnZ7Nu:-NWMlPQX9jzdJJwSHQBk:b-opaa3j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L515)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Looks like a part of the constructor function.
</blockquote></details>

I would even say one of constructors of assetft should somehow register it

needs discussion
___
*[`app/app.go` line 719 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMmB0KEv525uKr4dSO:-NWMmB0KEv525uKr4dSP:belk065) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L719)):*
> ```Go
> 		appupgradev1.NewV1Upgrade(app.mm, app.configurator, ChosenNetwork, app.AssetNFTKeeper),
> 		appupgradev2.NewV2Upgrade(app.mm, app.configurator),
> 		appupgradev3.NewV3Upgrade(app.mm, app.configurator),
> ```

why do we need a separate upgrade for this one ?
I think the plan was to put everything inside v2 which is kind of in progress upgrade now
___
*[`pkg/config/genesis/genesis.tmpl.json` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzp1AELTp7pZBfJEd:-NWMnI2R4eElRmTGUxPZ:b-t37tmp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/pkg/config/genesis/genesis.tmpl.json#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@miladz68 @ysv 
IMO the timeouts should be generic for all features. 
</blockquote></details>

Probably they should be generic (both params) for all future upgrades. 
On the other hand I see some pros defining them separately but IMO it overcomplicates the process too much. 

If we decide to define them separately at least they should be grouped
```
decision_timeouts: {
  v1: 100,
  v2: 1000
}
```
___
*[`pkg/config/genesis/genesis.tmpl.json` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMqcSj255uZ-PagPsA:-NWMqcSj255uZ-PagPsB:bwsx8i9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/pkg/config/genesis/genesis.tmpl.json#L31)):*
> ```JSON
>           "amount": "10000000"
>         },
>         "ibc_decision_timeout": "{{ .IBCDecisionTimeout }}",
> ```

where is the logic for decision_timeout handled ?
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr9iRD6d6ux2OzTGT:-NWMqnBu7h_B9fJ977-P:b-tiiup4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see a point in making one-shot actions generic. This is "fire and forget" type of thing.
</blockquote></details>

yes, I agree with Dzmitry.
 IMO msg should be smth like:

```
message MsgUpgradeToV2 {
  string denom
  ibc bool // not sure. Maybe there should be a structure inside to define values for each feature
}
```

All upgrade messages should have similar structure. Also It should be possible to not only Enable IBC but also disable it explicitly
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMrloE2LsfnnkjPJZe:-NWMrloE2LsfnnkjPJZf:bycqltc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
> ```protobuf
> 
> // MsgEnableIBCRequest means that sender wants to enable IBC for the token.
> message MsgEnableIBCRequest {
> ```

where do you verify that this message could be executed only once ?
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMryW088c3MMWfZN-2:-NWMryW088c3MMWfZN-3:b-e0ltsp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
> ```protobuf
> 
> // MsgEnableIBCRequest means that sender wants to enable IBC for the token.
> message MsgEnableIBCRequest {
> ```

In all places we shouldn't mention EnableIBC directly (funcs, keepers etc). It should be Upgrade which might contain different things not only IBC


<!-- Sent from Reviewable.io -->

2023-05-26 11:47 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 26 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-05-26 11:57 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 26 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMANRa4yEnrG7fPWzm:-NWMszR2C9On9QMOVn9W:b-8ep8yo) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Review that module please as well co compare your solution and this one: https://github.com/osmosis-labs/osmosis/tree/main/x/epochs
</blockquote></details>

The difference which might be important is that they execute hooks in the begin blocker, while I do it in the end blocker.

___
___
*[`app/app.go` line 118 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMkvqX3zNOr6eLYG1a:-NWMtCYjB3rRa_jBiAyR:b-9hizas) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L118)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

My initial idea was to have this delay logic inside assetft. Similar to the way it is implemented inside gov. So we have a queue of pending migrations and once time is achieved we execute them.

I am not sure defining this module is beneficial but might be. 

Lets discuss
</blockquote></details>

Later on we will have the same thing required in nfts. 
___
*[`app/app.go` line 515 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzKug9wIsZ1QnZ7Nu:-NWMudL53Vy6VZsM4Q_f:blhdftd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L515)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would even say one of constructors of assetft should somehow register it

needs discussion
</blockquote></details>

Configuring one component in the constructor of another one is a bad idea. This stuff should be done in common place where both objects are constructed, app.go in our case.
___
*[`app/app.go` line 719 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMmB0KEv525uKr4dSO:-NWMtRMO7BGHFbFpZLpn:b-amx0o1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L719)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we need a separate upgrade for this one ?
I think the plan was to put everything inside v2 which is kind of in progress upgrade now
</blockquote></details>

yea, I missed that we already have an upgrade (v2) for the next release. Will merge them.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzp1AELTp7pZBfJEd:-NWMtcE6A7_-gTMeIKSv:b-cq92bh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/pkg/config/genesis/genesis.tmpl.json#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Probably they should be generic (both params) for all future upgrades. 
On the other hand I see some pros defining them separately but IMO it overcomplicates the process too much. 

If we decide to define them separately at least they should be grouped
```
decision_timeouts: {
  v1: 100,
  v2: 1000
}
```
</blockquote></details>

The definition should not be per upgrade but per case. It might happen that in the same upgrade we have two types of messages to execute and timeout might be different.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMqcSj255uZ-PagPsA:-NWMu1TyA4LSpe9AQwkV:bev1uh8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/pkg/config/genesis/genesis.tmpl.json#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

where is the logic for decision_timeout handled ?
</blockquote></details>

https://github.com/CoreumFoundation/coreum/blob/wojtek/delay/x/asset/ft/keeper/upgradev3.go#L50
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMrloE2LsfnnkjPJZe:-NWMuRNs8nnwCbJUXBQY:bev1uic) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

where do you verify that this message could be executed only once ?
</blockquote></details>

https://github.com/CoreumFoundation/coreum/blob/wojtek/delay/x/asset/ft/keeper/upgradev3.go#L69


<!-- Sent from Reviewable.io -->

2023-05-26 12:08 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 26 files reviewed, 21 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/delay/module.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwfPw1Neu8d_tCdl-:-NWMxCNV0WTzVfewyLqd:blapvr4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L114)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

?
</blockquote></details>

Oh, the end has disapered.  :-)

Leaving that comment in order not to forget to implement it. 


<!-- Sent from Reviewable.io -->

2023-05-26 12:09 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr9iRD6d6ux2OzTGT:-NWMxjwP1lwhvh1lFlz9:b2o0z3d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes, I agree with Dzmitry.
 IMO msg should be smth like:

```
message MsgUpgradeToV2 {
  string denom
  ibc bool // not sure. Maybe there should be a structure inside to define values for each feature
}
```

All upgrade messages should have similar structure. Also It should be possible to not only Enable IBC but also disable it explicitly
</blockquote></details>

let's discuss it


<!-- Sent from Reviewable.io -->

2023-05-29 08:53 UTC, miladz68 reviewed
> Reviewed 2 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 25 of 26 files reviewed, 22 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/module.go` line 154 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWagPhx0Pc9Yorqa5T7:-NWagPhx0Pc9Yorqa5T8:b-xnbj0e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/x/asset/ft/module.go#L154)):*
> ```Go
> 
> 	err := cfg.RegisterMigration(types.ModuleName, 1, func(ctx sdk.Context) error {
> 		params := am.keeper.GetParams(ctx)
> ```

move it into a separate function called migrationv1, we also need a migration to  enable IBC on all existing tokens.


<!-- Sent from Reviewable.io -->

2023-05-29 10:26 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 25 of 26 files reviewed, 28 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`app/app.go` line 118 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMkvqX3zNOr6eLYG1a:-NWaZOpH8eymytvnuJbA:b-80gfmk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L118)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Later on we will have the same thing required in nfts. 
</blockquote></details>

decided to keep delay
___
*[`app/app.go` line 515 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWa_XB-Bxah49gWYvY-:-NWa_XB-Bxah49gWYvY0:b-c187wi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/app/app.go#L515)):*
> ```Go
> 
> 	delayRouter := delaytypes.NewRouter()
> 	delayRouter.RegisterMessage(&assetfttypes.MsgEnableIBCExecutor{}, assetfttypes.NewEnableIBCHandler(enableIBCKeeper))
> ```

rename: RegisterHandler
___
*[`app/app.go` line 515 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWab8wb459mQKXnO2rY:-NWab8wc7LdqDus8An2T:b-aymj07) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/app/app.go#L515)):*
> ```Go
> 
> 	delayRouter := delaytypes.NewRouter()
> 	delayRouter.RegisterMessage(&assetfttypes.MsgEnableIBCExecutor{}, assetfttypes.NewEnableIBCHandler(enableIBCKeeper))
> ```

lets get rid of Msg in name here because it is not really a message
___
*[`proto/coreum/asset/ft/v1/params.proto` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWad-1AB7i-dYevTEDI:-NWad-1AB7i-dYevTEDJ:bux7l69) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/proto/coreum/asset/ft/v1/params.proto#L20)):*
> ```protobuf
> 
>   // ibc_decision_timeout defines the end of the decision period for enabling IBC
>   google.protobuf.Timestamp ibc_decision_timeout = 2 [
> ```

```
token_upgrade_decision_timeout: time.Date
token_upgrade_grace_period: 7d
```
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr9iRD6d6ux2OzTGT:-NWar2vtBNSg9ziAUN1M:bpkm77h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss it
</blockquote></details>

```
message MsgTokenUpgradeV1 {
  string denom
  bool ibc_enabled
}
```
needs confirmation from Reza
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 16 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWaxLqa0Z8BCv1Vr7c3:-NWaxLqa0Z8BCv1Vr7c4:bwqcnwo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/proto/coreum/asset/ft/v1/upgradev3.proto#L16)):*
> ```protobuf
> 
> // MsgEnableIBCExecutor is executed by the delay module when it's time to enable IBC.
> message MsgEnableIBCExecutor {
> ```

`ExecuteTokenUpgradeV1`
___
*[`x/asset/ft/module.go` line 153 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWah_4y-WH6Kb0TNvvN:-NWah_4y-WH6Kb0TNvvO:bvia5yf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/x/asset/ft/module.go#L153)):*
> ```Go
> 	types.RegisterQueryServer(cfg.QueryServer(), keeper.NewQueryService(am.keeper))
> 
> 	err := cfg.RegisterMigration(types.ModuleName, 1, func(ctx sdk.Context) error {
> ```

move it to the same place as in nft module
___
*[`x/asset/ft/keeper/upgradev3.go` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM3IL212mO6Vwg-_Ty:-NWaxh-j0Tb86h8-EKyz:b-5y3x15) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/asset/ft/keeper/upgradev3.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I want to clearly indicate what code should be removed in the next upgrade. Other way might be to use some standardized comment format like `// remove-in: v4`
</blockquote></details>

decided on the call to move to a separate file but keep the same keeper
___
*[`x/asset/ft/types/codec.go` line 21 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWayxIZDEwDlTtBFjr2:-NWayxIZDEwDlTtBFjr3:b-aokm68) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fda834c795ff6664eaa539f4d0c316a2a7e32318/x/asset/ft/types/codec.go#L21)):*
> ```Go
> 		&MsgSetWhitelistedLimit{},
> 		&MsgEnableIBCRequest{},
> 		&MsgEnableIBCExecutor{},
> ```

try to remove `MsgEnableIBCExecutor` type registration since it is not really a message
___
*[`x/delay/module.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwfPw1Neu8d_tCdl-:-NWazwaQEebpGl5iDj3S:b-s4x3a6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L114)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Oh, the end has disapered.  :-)

Leaving that comment in order not to forget to implement it. 
</blockquote></details>

needs to be implementedd
___
*[`x/delay/module.go` line 125 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvsLc8UiTEOlCc_ml:-NWb02bm1H63XlcS4s6G:b-88oef8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

That was the first version but then I found that each time store must be created in keeper. Not a big deal but this way must work too.
</blockquote></details>

call keeper form EndBlocker here (as discussed on the call)
___
*[`x/delay/keeper/keeper.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvZrW7WEutfmV9NQz:-NWb0OsX9SDxKHEFdGA9:byououq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Each delayed message must contain unique id because otherwise there is no way to store all of the messages added in the same block. 
In the particular case of the IBC we could just take the hash of the message but I don't know if it might work in all the future cases.
</blockquote></details>

using denom here which is already unique
___
*[`x/delay/keeper/keeper.go` line 40 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLtnmn6HKQrgrDiPZj:-NWb0pCmEJ8bDXhxT4Iw:b-yhoduz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because for negative values, the magic of `binary.BigEndian` would produce bad results.
</blockquote></details>

lets return error here
___
*[`x/delay/keeper/keeper.go` line 77 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvShSAizx3-PT3aks:-NWb1-1z9gno11LFUTZn:bi6urh9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

key is made of two components:
- big-endian encoded 8-byte uint64
- followed by id string

If there are no at least 8 bytes it means state is broken
</blockquote></details>

return error
___
*[`x/delay/keeper/keeper.go` line 70 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWb0rkT3sx2s8N2HQQ1:-NWb0rkT3sx2s8N2HQQ2:b-yhoduz) ([raw file](https://github.c [...]

2023-05-30 09:08 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 25 of 26 files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 515 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLzKug9wIsZ1QnZ7Nu:-NWfmjZBE3akLG0Gp4aD:bs7cmqs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/app/app.go#L515)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Configuring one component in the constructor of another one is a bad idea. This stuff should be done in common place where both objects are constructed, app.go in our case.
</blockquote></details>

We decided to keep it like it is
___
*[`app/app.go` line 515 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWa_XB-Bxah49gWYvY-:-NWfnIBy0BC5e9Ex_0dO:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/app/app.go#L515)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

rename: RegisterHandler
</blockquote></details>

Done.
___
*[`app/app.go` line 515 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWab8wb459mQKXnO2rY:-NWftvduCB3w14H20-AH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/app/app.go#L515)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets get rid of Msg in name here because it is not really a message
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLr9iRD6d6ux2OzTGT:-NWfu3QtCCjmVu-A3HK-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

```
message MsgTokenUpgradeV1 {
  string denom
  bool ibc_enabled
}
```
needs confirmation from Reza
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWMryW088c3MMWfZN-2:-NWfu73YEjjEyvi1-5C-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/proto/coreum/asset/ft/v1/upgradev3.proto#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

In all places we shouldn't mention EnableIBC directly (funcs, keepers etc). It should be Upgrade which might contain different things not only IBC
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 16 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWaxLqa0Z8BCv1Vr7c3:-NWfuAVi1yskQDE5TRIi:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/proto/coreum/asset/ft/v1/upgradev3.proto#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`ExecuteTokenUpgradeV1`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/upgradev3.go` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWM3IL212mO6Vwg-_Ty:-NWfuI1PCa8H1q-aY0Ej:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/asset/ft/keeper/upgradev3.go#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

decided on the call to move to a separate file but keep the same keeper
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 10:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 6 of 33 files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWad-1AB7i-dYevTEDI:-NWg28gx-pnBlz0F3hTm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/proto/coreum/asset/ft/v1/params.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

```
token_upgrade_decision_timeout: time.Date
token_upgrade_grace_period: 7d
```
</blockquote></details>

Done.
___
*[`x/asset/ft/module.go` line 153 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWah_4y-WH6Kb0TNvvN:-NWg3Yxq0rIKiGqi3chS:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/x/asset/ft/module.go#L153)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

move it to the same place as in nft module
</blockquote></details>

Done.
___
*[`x/delay/module.go` line 125 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvsLc8UiTEOlCc_ml:-NWg5mtb0P9WIEDH4OSx:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L125)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

call keeper form EndBlocker here (as discussed on the call)
</blockquote></details>

Done.
___
*[`x/delay/module.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwFhQAFgd291PXcUR:-NWg5yX43n5-sWi9ezdI:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L133)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No. If error is returned here it means sth went really wrong meaning that blockchain might be left in some weird state leading to serious problems. 
</blockquote></details>

Done
___
*[`x/delay/keeper/keeper.go` line 40 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLtnmn6HKQrgrDiPZj:-NWg60cS0rmWoI4h4dpV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets return error here
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 77 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLvShSAizx3-PT3aks:-NWg63MP8FnTpr_9Bo27:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/keeper/keeper.go#L77)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

return error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 70 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWb0rkT3sx2s8N2HQQ1:-NWg62A62Fkjj2NJxnAc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/x/delay/keeper/keeper.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets return error here
</blockquote></details>

Done.
___
*[`x/delay/types/router.go` line 48 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWb1alnEoOgpNpFoZKw:-NWg77h-3QZcHsIMM3C2:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/x/delay/types/router.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

try to return error here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 13:09 UTC, miladz68 reviewed
> Reviewed 12 of 26 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 11 of 15 files at r5, 14 of 15 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 29 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/legacy/v1/params.go` line 16 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWgJWj08Dwxn7sNJDHM:-NWgJWj08Dwxn7sNJDHN:bgtgw6a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/asset/ft/legacy/v1/params.go#L16)):*
> ```Go
> 
> // MigrateParams migrates asset ft params state from v1 to v2.
> func MigrateParams(ctx sdk.Context, keeper Keeper) error {
> ```

shouldn't it be called `MigrateV1toV2` or just `Migrate` ?
___
*[`x/asset/ft/keeper/upgradev3.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWfkwcy7dN5FsylFGYe:-NWfkwcy7dN5FsylFGYf:b-lgknl6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/x/asset/ft/keeper/upgradev3.go#L51)):*
> ```Go
> 	params := k.keeper.GetParams(ctx)
> 	if ctx.BlockTime().After(params.IbcDecisionTimeout) {
> 		return sdkerrors.Wrapf(sdkerrors.ErrUnauthorized, "it is no longer possible IBC")
> ```

the sentence in error code, seems not complete.


<!-- Sent from Reviewable.io -->

2023-05-31 10:12 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 38 files reviewed, 29 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/types/codec.go` line 21 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWayxIZDEwDlTtBFjr2:-NWlHqaKAhJzOy4yyRyZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3ecebc0205869205757cdd92137a4cc91d5f611a/x/asset/ft/types/codec.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

try to remove `MsgEnableIBCExecutor` type registration since it is not really a message
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 10:17 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 38 files reviewed, 28 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/provider.go` line 197 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHksw2926nwyilUSw:-NWlHksw2926nwyilUSx:b-1m7p83) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/provider.go#L197)):*
> ```Go
> 		Gov                         GovConfig
> 		CustomParamsConfig          CustomParamsConfig
> 		TokenUpgradeDecisionTimeout string
> ```

IMO it should be a part of the addition struct, for example AssetFTConfig. 
___
*[`pkg/config/genesis/genesis.tmpl.json` line 32 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHSXz3zed8MCyZ3WI:-NWlHSXz3zed8MCyZ3WJ:btzgnhu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/genesis/genesis.tmpl.json#L32)):*
> ```JSON
>         },
>         "token_upgrade_decision_timeout": "{{ .TokenUpgradeDecisionTimeout }}",
>         "token_upgrade_grace_period": "604800s"
> ```

Why  the `token_upgrade_decision_timeout` is configurable, but `token_upgrade_grace_period` isn't?
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 43 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlDnAF-YdRkE-lvYNg:-NWlDnAF-YdRkE-lvYNh:b-6wnxw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/proto/coreum/asset/ft/v1/tx.proto#L43)):*
> ```protobuf
> 
>   // TokenUpgradeV1 upgrades token to version V1.
>   rpc TokenUpgradeV1(MsgTokenUpgradeV1) returns (EmptyResponse);
> ```

@miladz68 @wojtek-coreum  @ysv maybe it should be somthing like `UpgradeTokenV1` and message `UpgradeTokenV1`, since all other calls are names as actions.
___
*[`x/asset/ft/legacy/v1/params.go` line 16 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlIHIIBcKBBrNrCt02:-NWlIHIIBcKBBrNrCt03:bpjopq0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/x/asset/ft/legacy/v1/params.go#L16)):*
> ```Go
> 
> // MigrateParams migrates asset ft params state from v1 to v2.
> func MigrateParams(ctx sdk.Context, keeper Keeper) error {
> ```

If it's not POC, unit tests are required. 
___
*[`x/delay/keeper/keeper.go` line 42 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlEQFK3ek8dZN6yjHV:-NWlEQFK3ek8dZN6yjHW:b-augbtu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/delay/keeper/keeper.go#L42)):*
> ```Go
> 	}
> 
> 	key := make([]byte, 8, 8+len(id))
> ```

If it's not the POC than all keys creation should be in the types/keys.go 
___
*[`x/delay/keeper/keeper.go` line 61 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlElp67qKYp-PvcOZX:-NWlElp67qKYp-PvcOZY:bxm872f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/delay/keeper/keeper.go#L61)):*
> ```Go
> 
> // ExecuteDelayedItems executes delayed logic.
> func (k Keeper) ExecuteDelayedItems(ctx sdk.Context) error {
> ```

If it's not a POC that the unit tests should for all methods. 
___
*[`x/delay/keeper/keeper.go` line 81 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlExZ74HIM8JbYoR5t:-NWlExZ74HIM8JbYoR5u:b-3z15o4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/delay/keeper/keeper.go#L81)):*
> ```Go
> 		// due to the order of items returned by the iterator, if we find that execution time is after
> 		// the current block time, then there is no reason to iterate further
> 		execTime := binary.BigEndian.Uint64(key[:8])
> ```

That part should be extractd to keys.go as function together with the length check. 
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlIlEk-M-ylhaueOPM:-NWlIlEk-M-ylhaueOPN:b-x1ebq4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03ee497d0bcf2e04fca80ba2319117040ab149d8/proto/coreum/asset/ft/v1/upgradev3.proto#L3)):*
> ```protobuf
> syntax = "proto3";
> package coreum.asset.ft.v1;
> ```

We can call that file token_upgrade. Since we are not going to support multiple upgrades at the same time. Or you can even move the `Msg` to `tx` and `DelayedTokenUpgradeV1` to token.
___
*[`x/asset/ft/keeper/upgradev1.go` line 24 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlFZVKAEzA825YS5hJ:-NWlFZVKAEzA825YS5hK:b-w1f6ed) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/asset/ft/keeper/upgradev1.go#L24)):*
> ```Go
> 
> // StoreDelayedUpgradeV1 stores request for upgrading token to V1.
> func (k Keeper) StoreDelayedUpgradeV1(ctx sdk.Context, sender sdk.AccAddress, denom string, ibcEnabled bool) error {
> ```

The code with the upgrade struct is pending right? 
___
*[`x/asset/ft/keeper/upgradev1.go` line 66 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlFmu01ZG9HukmssWP:-NWlFmu01ZG9HukmssWQ:bbhd3fr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c8df9499abc6f9717bc96b34e7684f9a20f7b3a7/x/asset/ft/keeper/upgradev1.go#L66)):*
> ```Go
> 	}
> 
> 	err = k.delayKeeper.DelayExecution(ctx, "assetft-ibcenable-"+denom, data, params.TokenUpgradeGracePeriod)
> ```

Let's move it to function with the meaningful name, for example 
```
GetTokenUpgradeID(version, denom string) {
  return fmt.Sprintf("%s-%s-%s", types.ModuleName, version, denom)
} 

```
And I would propose to create a V1 constant and use it. 
___
*[`x/asset/ft/keeper/upgradev1.go` line 16 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlGzet0AeWIX3vDrD3:-NWlGzet0AeWIX3vDrD4:bdd3dtg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/x/asset/ft/keeper/upgradev1.go#L16)):*
> ```Go
> )
> 
> var upgradeV1Prefix = []byte("upgradev1")
> ```

If it's not a POC than all keys manipulation should be in the keys.go and let's use bytes keys.
___
*[`x/asset/ft/keeper/upgradev1.go` line 78 at r10](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHFka6oKWdlQGZYX8:-NWlHFka6oKWdlQGZYX9:bpjopq0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c97a99ec7407298f7ef6cd1e3a9723ce503408e5/x/asset/ft/keeper/upgradev1.go#L78)):*
> ```Go
> 
> // UpgradeTokenToV1 upgrades token to version V1.
> func (k Keeper) UpgradeTokenToV1(ctx sdk.Context, data *types.DelayedTokenUpgradeV1) error {
> ```

If it's not POC, unit tests are required. 
___
*[`x/asset/ft/types/upgradev3.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlIZmBEgl6Lu8-GoKa:-NWlIZmBEgl6Lu8-GoKb:b-nt8xl3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03ee497d0bcf2e04fca80ba2319117040ab149d8/x/asset/ft/types/upgradev3.go#L1)):*
> ```Go
> package types
> ```

We can call that file token_upgrade. Since we are not going to support multiple upgrades at the same time. 


<!-- Sent from Reviewable.io -->

2023-05-31 10:24 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 38 files reviewed, 28 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 32 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHSXz3zed8MCyZ3WI:-NWlJODx9daeDaEpavMC:b-wrdvws) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/genesis/genesis.tmpl.json#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why  the `token_upgrade_decision_timeout` is configurable, but `token_upgrade_grace_period` isn't?
</blockquote></details>

Because `token_upgrade_decision_timeout` is computed based on genesis time, while `token_upgrade_grace_period` is an independent value
___
*[`x/asset/ft/keeper/upgradev1.go` line 24 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlFZVKAEzA825YS5hJ:-NWlKBFVEt193b5B515X:b3kre) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/asset/ft/keeper/upgradev1.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The code with the upgrade struct is pending right? 
</blockquote></details>

?
___
*[`x/asset/ft/keeper/upgradev1.go` line 16 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlGzet0AeWIX3vDrD3:-NWlJr-C2cLIoX-_BLMC:bux9qk2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/x/asset/ft/keeper/upgradev1.go#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If it's not a POC than all keys manipulation should be in the keys.go and let's use bytes keys.
</blockquote></details>

for this case the key should be bound strictly to this upgrade. Otherwise the byte value might be accidentally reused in the future. The solution could be to keep this key forever, but what for?
___
*[`x/asset/ft/types/upgradev3.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlIZmBEgl6Lu8-GoKa:-NWlKLTNCyMpJ4jHn74K:b-40atlv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03ee497d0bcf2e04fca80ba2319117040ab149d8/x/asset/ft/types/upgradev3.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can call that file token_upgrade. Since we are not going to support multiple upgrades at the same time. 
</blockquote></details>

I still prefer to have v1 in the name. We may start working on v2 even before v1 is finished on mainnet, despite the fact that they won't live together at the same time there.


<!-- Sent from Reviewable.io -->

2023-05-31 10:51 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 24 of 38 files reviewed, 28 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/delay/keeper/keeper.go` line 42 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlEQFK3ek8dZN6yjHV:-NWlOGRNCa6_WS-yntW_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/delay/keeper/keeper.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If it's not the POC than all keys creation should be in the types/keys.go 
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 81 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlExZ74HIM8JbYoR5t:-NWlONNq8PcLk72cZf-m:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/delay/keeper/keeper.go#L81)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That part should be extractd to keys.go as function together with the length check. 
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/upgradev1.go` line 66 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlFmu01ZG9HukmssWP:-NWlO51K0ifInUOooeN0:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c8df9499abc6f9717bc96b34e7684f9a20f7b3a7/x/asset/ft/keeper/upgradev1.go#L66)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's move it to function with the meaningful name, for example 
```
GetTokenUpgradeID(version, denom string) {
  return fmt.Sprintf("%s-%s-%s", types.ModuleName, version, denom)
} 

```
And I would propose to create a V1 constant and use it. 
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/upgradev1.go` line 16 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlGzet0AeWIX3vDrD3:-NWlQ5BCB94JYqn5JQoV:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/x/asset/ft/keeper/upgradev1.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

for this case the key should be bound strictly to this upgrade. Otherwise the byte value might be accidentally reused in the future. The solution could be to keep this key forever, but what for?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-31 12:54 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 22 of 43 files reviewed, 28 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/delay/module.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwfPw1Neu8d_tCdl-:-NWlrzoH2urLvoMLzXO9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L114)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

needs to be implementedd
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-05 11:59 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 22 of 44 files reviewed, 23 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 37 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAQ0S153T8LHVZUvLo:-NXAQ0S153T8LHVZUvLp:bpbm6w6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/go.mod#L37)):*
> ```XML
> 	google.golang.org/genproto v0.0.0-20230223222841-637eb2293923
> 	google.golang.org/grpc v1.53.0
> 	google.golang.org/protobuf v1.28.2-0.20220831092852-f930b1dc76e8
> ```

Why do we need that change?
___
*[`pkg/config/genesis/genesis.tmpl.json` line 32 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHSXz3zed8MCyZ3WI:-NXANt9EDyQmQGOrssfn:bibbbk5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/genesis/genesis.tmpl.json#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because `token_upgrade_decision_timeout` is computed based on genesis time, while `token_upgrade_grace_period` is an independent value
</blockquote></details>

IMO we can simplify it. We don't need the upgrade when we initiate the chain, because all features are already allowed. That's why initially in the default params you can set the decision timeout to 0. So you won't need to pass the genetic time to the keeper constructor and add the methods where you extract it.
___
*[`x/delay/types/keys.go` line 26 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAPVsGCx4OUiimvsWZ:-NXAPVsGCx4OUiimvsW_:b4oxx91) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/x/delay/types/keys.go#L26)):*
> ```Go
> var DelayedItemKeyPrefix = []byte{0x01}
> 
> const uint64Length = 8
> ```

Would it be more convenient to call it timestamLength?
___
*[`x/asset/ft/keeper/upgradev1.go` line 95 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAMpejDmdkWo93migy:-NXAMpejDmdkWo93migz:b-v9cpz4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/x/asset/ft/keeper/upgradev1.go#L95)):*
> ```Go
> 
> 	version := k.GetVersion(ctx, data.Denom)
> 	if version.Version < upgradeV1Version {
> ```

Why do we need that check?
___
*[`x/asset/ft/types/upgradev1.go` line 30 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAP8bL3iPxtRM1xoC1:-NXAP8bL3iPxtRM1xoC2:bhikfg4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/x/asset/ft/types/upgradev1.go#L30)):*
> ```Go
> 
> // UpgradeV1Keeper defines methods required to update tokens to V1.
> type UpgradeV1Keeper interface {
> ```

I would call he file token upgrade as well as structs/interface here since it looks like the module upgrade when you open the package. 


<!-- Sent from Reviewable.io -->

2023-06-05 11:59 UTC, dzmitryhil reviewed
> Reviewed 1 of 1 files at r4, 8 of 15 files at r5, 10 of 15 files at r6, 2 of 3 files at r7, 6 of 13 files at r8, 1 of 3 files at r9, 2 of 7 files at r12, 9 of 12 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 23 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-06 06:40 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 43 of 45 files reviewed, 23 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`go.mod` line 37 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAQ0S153T8LHVZUvLo:-NXEOk6L-t2znKmDKsZw:b-1bj4zh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/go.mod#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need that change?
</blockquote></details>

No idea. We don't use in the code directly but `go mod tidy`  is happy about putting it there
___
*[`x/asset/ft/keeper/upgradev1.go` line 95 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAMpejDmdkWo93migy:-NXEOEhE4hfQCN8JLCBo:b-dp86jw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/x/asset/ft/keeper/upgradev1.go#L95)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need that check?
</blockquote></details>

To upgrade token to v1 only if it is in v0.


<!-- Sent from Reviewable.io -->

2023-06-06 13:05 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 37 of 48 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 64 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXFhRVR55xFAbzdibO7:-NXFmfnO-oiPENMcZwmc:bttqlep) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/proto/coreum/asset/ft/v1/token.proto#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I still don't understand the reasoning for storing these as a separate structure & under separate key in store. Why can't we use TokenDefinition for this ?
</blockquote></details>

@dzmitryhil I tend to agree with that. One additional int in the token definition shouldn't affect the performance
___
*[`x/asset/ft/keeper/upgradev1_test.go` line 32 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXFkwav2pZm_m6ZbOpJ:-NXFn_xi89W4JZFznyZf:b-5xc7hf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgradev1_test.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it ok that we hardcoded this date here 
Will test will still work after this date 

</blockquote></details>

We are already after this date and test works :)
___
*[`proto/coreum/asset/ft/v1/upgradev1.proto` line 17 at r16](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXEumSjDg42L1gfw_ov:-NXFn9ml509j1yg-aUHg:b-5694lj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c8c87ee97845705c516d609cb724fb2a9b53c57f/proto/coreum/asset/ft/v1/upgradev1.proto#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we store timestamp of when upgrade is applied here or it is done inside delay module ?
when you import into genesis how do you know expected execution ts ?
</blockquote></details>

It is done by the `delay`. When `delay` imports and exports the genesis it stores the timestamp there.


<!-- Sent from Reviewable.io -->

2023-06-07 08:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 31 of 50 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/delay/keeper/keeper.go` line 61 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlElp67qKYp-PvcOZX:-NXJyGaE1emYf8xgUdvd:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/delay/keeper/keeper.go#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If it's not a POC that the unit tests should for all methods. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-07 12:54 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 31 of 50 files reviewed, 19 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 37 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAQ0S153T8LHVZUvLo:-NXKun4u7gpocMZiPrV4:b-690c9p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/go.mod#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No idea. We don't use in the code directly but `go mod tidy`  is happy about putting it there
</blockquote></details>

I guess the ignite intrigues it.
___
*[`proto/coreum/asset/ft/v1/token.proto` line 64 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXFhRVR55xFAbzdibO7:-NXKv0dV-kPR4p4accg2:bxcti3q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/proto/coreum/asset/ft/v1/token.proto#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@dzmitryhil I tend to agree with that. One additional int in the token definition shouldn't affect the performance
</blockquote></details>

Then I'm ok with that as well.


<!-- Sent from Reviewable.io -->

2023-06-08 15:22 UTC, ysv requested changes
> Reviewed 2 of 15 files at r5, 2 of 15 files at r6, 1 of 3 files at r7, 2 of 13 files at r8, 1 of 7 files at r12, 4 of 12 files at r13, 1 of 4 files at r14, 1 of 2 files at r15, 4 of 12 files at r16, 5 of 9 files at r17, 5 of 5 files at r18, 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 20 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 64 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXFhRVR55xFAbzdibO7:-NXQaLd024QjJfn07CIE:b7evaom) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/proto/coreum/asset/ft/v1/token.proto#L64)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Then I'm ok with that as well.
</blockquote></details>

lets merge them then
___
*[`x/asset/ft/module.go` line 38 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQTh-X6SD2JIBO_nwl:-NXQTh-X6SD2JIBO_nwm:b-d7ko36) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/asset/ft/module.go#L38)):*
> ```Go
> type AppModuleBasic struct {
> 	cdc         codec.BinaryCodec
> 	genesisTime time.Time
> ```

I don't get the meaning of this attribute
Why do we need genesis time inside FT module ?
___
*[`x/delay/genesis_test.go` line 79 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQXFPGE9fsa2ZnqqW6:-NXQXFPGE9fsa2ZnqqW7:b-3mtsiv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/genesis_test.go#L79)):*
> ```Go
> }
> 
> func ignoreCache(item types.DelayedItem) types.DelayedItem {
> ```

what is the logic behind `ignoreCache` ?
___
*[`x/delay/module.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWLwFhQAFgd291PXcUR:-NXQXV8m3FWxoSXYNuhV:b-7th5gw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/181173b01eab88460b41a8f570d392366a00117c/x/delay/module.go#L133)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

panic is still here
___
*[`x/delay/types/genesis.go` line 24 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQYl1c0hiOuJMIp82p:-NXQYl1c0hiOuJMIp82q:b-ehbbjf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/types/genesis.go#L24)):*
> ```Go
> 	}
> 	if di.ExecutionTime.Unix() < 0 {
> 		return errors.New("there were no blockchains before 1970-01-01")
> ```

there were no for sure )

but error is not explicit it is better to tell: "execution time is less than 1970...`
___
*[`x/delay/types/keys.go` line 26 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAPVsGCx4OUiimvsWZ:-NXQ_0YW6l1HXsoOgGLn:b3ksf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/x/delay/types/keys.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Would it be more convenient to call it timestamLength?
</blockquote></details>

d
___
*[`x/delay/types/keys.go` line 29 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQ_ciF2vVownSdYWQz:-NXQ_ciF2vVownSdYWR-:b7ykwp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/types/keys.go#L29)):*
> ```Go
> 
> // CreateDelayedItemKey creates key for delayed item.
> func CreateDelayedItemKey(id string, t time.Time) ([]byte, error) {
> ```

I am not sure I understand this logic 100%. Could you explain and put comment somewhere

But what will happen if 2 objects are delayed to be executed at exactly the same time ?
Pls add test for such cased
___
*[`x/delay/types/keys.go` line 36 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQZ7nY0zHM_FX_-Ltq:-NXQZ7nY0zHM_FX_-Ltr:b-js3ryv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/types/keys.go#L36)):*
> ```Go
> 	execTime := t.Unix()
> 	if execTime < 0 {
> 		return nil, errors.New("there were no blockchains before 1970-01-01")
> ```

same comment as before 
error is not explicit it is better to tell: "execution time is less than 1970...`
___
*[`proto/coreum/asset/ft/v1/upgradev1.proto` line 17 at r16](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXEumSjDg42L1gfw_ov:-NXQaQVc1Gjn-fE5XRAd:b-tkbg6q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c8c87ee97845705c516d609cb724fb2a9b53c57f/proto/coreum/asset/ft/v1/upgradev1.proto#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It is done by the `delay`. When `delay` imports and exports the genesis it stores the timestamp there.
</blockquote></details>

found it after further review thx
___
*[`x/asset/ft/types/upgradev1.go` line 30 at r14](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXAP8bL3iPxtRM1xoC1:-NXQWP8Q7Lb4DrzvG0PT:b-ybkg9o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c7468414cc627d28721e123d716c604a3efc8e96/x/asset/ft/types/upgradev1.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would call he file token upgrade as well as structs/interface here since it looks like the module upgrade when you open the package. 
</blockquote></details>

I tend to agree


<!-- Sent from Reviewable.io -->

2023-06-09 09:17 UTC, dzmitryhil reviewed
> Reviewed 1 of 2 files at r15, 8 of 12 files at r16, 8 of 9 files at r17, 5 of 5 files at r18, 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-06-09 14:45 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 49 of 50 files reviewed, 20 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/provider.go` line 197 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHksw2926nwyilUSw:-NXVbCYOAkD2o4mi_DUF:b2d4jan) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/provider.go#L197)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree
we can keep structure more or less similar to genesis
</blockquote></details>

remove this field
___
*[`pkg/config/genesis/genesis.tmpl.json` line 32 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHSXz3zed8MCyZ3WI:-NXVZ-1V4TTJL7k5t9ZB:bhd0aj1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/genesis/genesis.tmpl.json#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't get this discussion
</blockquote></details>

Set it to 0000-00-00T00:00:00.00Z
___
*[`proto/coreum/asset/ft/v1/token.proto` line 64 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXFhRVR55xFAbzdibO7:-NXVb_GY0pwLMEnp-CoQ:b-59kibq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/proto/coreum/asset/ft/v1/token.proto#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets merge them then
</blockquote></details>

let's merge
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 43 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlDnAF-YdRkE-lvYNg:-NXVbc3n24pKfSFFIKVf:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/proto/coreum/asset/ft/v1/tx.proto#L43)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes I agree
</blockquote></details>

agree
___
*[`x/asset/ft/legacy/v1/params.go` line 16 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWgJWj08Dwxn7sNJDHM:-NXVb1sO1-L6rgVzGGz-:b8hmtiz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a9c8826eb1f0c8252654e5b07acc9db1d7508a55/x/asset/ft/legacy/v1/params.go#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm ok with current name
</blockquote></details>

please resolve
___
*[`proto/coreum/asset/ft/v1/upgradev3.proto` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlIlEk-M-ylhaueOPM:-NXVaSPeCfLIhbgcJsm4:b-59kibq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03ee497d0bcf2e04fca80ba2319117040ab149d8/proto/coreum/asset/ft/v1/upgradev3.proto#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss it
</blockquote></details>

let's merge


<!-- Sent from Reviewable.io -->

2023-06-13 11:08 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 30 of 58 files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 64 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXFhRVR55xFAbzdibO7:-NXoRM_HBhZ5dZjkcgD9:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/proto/coreum/asset/ft/v1/token.proto#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's merge
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-13 13:51 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 23 of 59 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/provider.go` line 197 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHksw2926nwyilUSw:-NXozsGt5iRQN0bdyEii:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/provider.go#L197)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I still see it.
</blockquote></details>

Done.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 32 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NWlHSXz3zed8MCyZ3WI:-NXozxLA5saATeQXMUeQ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/pkg/config/genesis/genesis.tmpl.json#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check please whether I've pushed the changes. 
</blockquote></details>

Done.
___
*[`x/delay/types/genesis.go` line 24 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQYl1c0hiOuJMIp82p:-NXp-nGe9VCDL3jY_SKU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/types/genesis.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

there were no for sure )

but error is not explicit it is better to tell: "execution time is less than 1970...`
</blockquote></details>

Done.
___
*[`x/delay/types/keys.go` line 36 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQZ7nY0zHM_FX_-Ltq:-NXp-ox18boHx7OMo-Bm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/types/keys.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same comment as before 
error is not explicit it is better to tell: "execution time is less than 1970...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-14 08:00 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 22 of 59 files reviewed, 32 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 321 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsaFfnEVwPK3WtVdLC:-NXssOGaA7ktlOjyGhpD:b-jnzead) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/integration-tests/upgrade/ft.go#L321)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you use the slice here?
</blockquote></details>

I don't understand the question
___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXssYPi6UX86DpBQC-W:b-k73ipl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why we need an additional type for it?
</blockquote></details>

If params struct changes (fields are added, removed etc.), during the upgrade you need to read existing data to old structure, copy data to new structure and write the new structure. Otherwise cosmos panics even if the upgrade just adds new field,
___
*[`x/asset/ft/keeper/keeper.go` line 215 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXseb5w80Ti11F2dsd_:-NXst68b4NXYImmwptEa:bfbu6lt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/x/asset/ft/keeper/keeper.go#L215)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need that logic? Why can't we just set the version to `1` for all new tokens?
</blockquote></details>

It's for the case when we need to replace the binary before the upgrade. If you all swear that it won't happen, then I may remove it.
___
*[`x/asset/ft/keeper/upgrade.go` line 1 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsgD4i54C_4Dh1qsju:-NXstXPj6SLnKuEfpEev:b-dgis1x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgrade.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we have two files`upgrade.go` and `upgradev1.go` ? And in general the name should be `token_upgrade` in order not to mix it with the module upgrade. 
</blockquote></details>

`upgrade.go` contains code common to all the upgrades, `upgradev1.go` contains code specific to v1.
___
*[`x/asset/ft/types/params.go` line 13 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmFj20TriKU2cYPet:-NXsu7EP232F6lCFwX08:b-7zi8tj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/x/asset/ft/types/params.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This constant belongs to the upgrade now. 
</blockquote></details>

WDYM?
___
*[`x/asset/ft/types/params.go` line 85 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmWtVAOLDAO0C2Wza:-NXsuB3c8ZAvJbclFtNn:b-tu6vju) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/x/asset/ft/types/params.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the validation is empty and not testes for that parm?
</blockquote></details>

because all the values are valid, we decided to use `0000-00-00T00:00:00.000Z` value in default genesis
___
*[`x/delay/keeper/keeper_test.go` line 20 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsp8CI57fJgTk_Qoem:-NXsuctM-Qaoo1FXKugb:bkua1te) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/x/delay/keeper/keeper_test.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you use the token upgrade struct for the test?
</blockquote></details>

1. to not create dependency between modules
2. handler for that type is already registered in app.go
___
*[`x/asset/ft/keeper/upgradev1.go` line 49 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXshv2m1YOlkJDLF42l:-NXstoxN11zzGgfAstIw:b3rougz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f4a178b1045962492ef04965b3af07ed24fee10/x/asset/ft/keeper/upgradev1.go#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you do it before the `if err := k.SetPendingVersion(ctx, denom, upgradeV1Version)`, so you could not use the `k.ClearPendingVersion(ctx, denom)` in that if.
</blockquote></details>

Because `SetPendingVersion` returns an error if pending upgrade already exists. If it's too confusing then I may create two separate functions for checking and setting.


<!-- Sent from Reviewable.io -->

2023-06-14 13:00 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 13 of 67 files reviewed, 19 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 321 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsaFfnEVwPK3WtVdLC:-NXtvjrC5NvL5hcw0OIs:b-364die) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/integration-tests/upgrade/ft.go#L321)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand the question
</blockquote></details>

`requireT.Equals([]{assetfttypes.Feature_minting, assetfttypes.Feature_freezing .... }, resp.Token.Features)`
___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXtxsWG9aeiIu696QmC:b-fs1c9i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If params struct changes (fields are added, removed etc.), during the upgrade you need to read existing data to old structure, copy data to new structure and write the new structure. Otherwise cosmos panics even if the upgrade just adds new field,
</blockquote></details>

Have you checked how it's done in the SDK upgrades?
___
*[`x/asset/ft/keeper/keeper.go` line 215 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXseb5w80Ti11F2dsd_:-NXty8pb2VTD0JtK8h7A:b8jv6n2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/keeper/keeper.go#L215)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's for the case when we need to replace the binary before the upgrade. If you all swear that it won't happen, then I may remove it.
</blockquote></details>

What is the case when we need to replace the binary before the upgrade? I don't know such cases.
___
*[`x/asset/ft/types/params.go` line 13 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmFj20TriKU2cYPet:-NXtz-ur164BLUTcMOhU:b-2bzs2y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/types/params.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

I mean you use it in the upgrade only so no need to keep it in the `params.go`.
___
*[`x/asset/ft/types/params.go` line 85 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmWtVAOLDAO0C2Wza:-NXtz6zoAphtfbkiYlRW:bcfet3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/types/params.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

because all the values are valid, we decided to use `0000-00-00T00:00:00.000Z` value in default genesis
</blockquote></details>

But how about checking the type?
___
*[`x/asset/ft/keeper/token_upgrade.go` line 27 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXtyfbN1ajM6snDfeSq:-NXtyfbN1ajM6snDfeSr:b-g3blc4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/71ea6a946b035bef5d9ab5aace37309bf2185936/x/asset/ft/keeper/token_upgrade.go#L27)):*
> ```Go
> func (k Keeper) ExportPendingTokenUpgrades(ctx sdk.Context) ([]types.PendingTokenUpgrade, error) {
> 	store := prefix.NewStore(ctx.KVStore(k.storeKey), types.PendingTokenUpgradeKeyPrefix)
> 	versions := []types.PendingTokenUpgrade{}
> ```

var versions []types.PendingTokenUpgrade
___
*[`x/asset/ft/keeper/token_upgrade.go` line 65 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXtyYtU8-LChazDBgzS:-NXtyYtU8-LChazDBgzT:b-k0exn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/71ea6a946b035bef5d9ab5aace37309bf2185936/x/asset/ft/keeper/token_upgrade.go#L65)):*
> ```Go
> // ClearPendingVersion clears pending version marker.
> func (k Keeper) ClearPendingVersion(ctx sdk.Context, denom string) {
> 	prefix.NewStore(ctx.KVStore(k.storeKey), types.PendingTokenUpgradeKeyPrefix).Delete([]byte(denom))
> ```

Use the `types.CreatePendingTokenUpgradeKey(denom)` here as well.
___
*[`x/asset/ft/keeper/upgrade.go` line 1 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsgD4i54C_4Dh1qsju:-NXtyGT45qyJC66w6dzk:b2w2cfv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgrade.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`upgrade.go` contains code common to all the upgrades, `upgradev1.go` contains code specific to v1.
</blockquote></details>

We can keep the v1 and common logic in single `token_upgrade` file I don't see any need to have one more. 


<!-- Sent from Reviewable.io -->

2023-06-14 13:09 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 13 of 67 files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXu-uSLA_tlTvItG6K4:b-xi6zf1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have you checked how it's done in the SDK upgrades?
</blockquote></details>

Yes, they have versioned structures too
___
*[`x/asset/ft/keeper/keeper.go` line 215 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXseb5w80Ti11F2dsd_:-NXu0-772QI6nP_1_kXy:b62i1wf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/keeper/keeper.go#L215)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the case when we need to replace the binary before the upgrade? I don't know such cases.
</blockquote></details>

Any fuckup which might happen in the meantime
___
*[`x/asset/ft/types/params.go` line 13 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmFj20TriKU2cYPet:-NXu0K6EATjS20wD2V9N:bsb6x47) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/types/params.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean you use it in the upgrade only so no need to keep it in the `params.go`.
</blockquote></details>

No, I use it to initialize default genesis params too
___
*[`x/asset/ft/types/params.go` line 85 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmWtVAOLDAO0C2Wza:-NXu0P3E0KXWNCPMjvmj:b-3h1758) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/types/params.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But how about checking the type?
</blockquote></details>

Now I have validation there because cosmos panics if date is before 0001-01-01
___
*[`x/asset/ft/keeper/token_upgrade.go` line 27 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXtyfbN1ajM6snDfeSq:-NXu09AHB5yViYlcea5T:b-e8p9cx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/71ea6a946b035bef5d9ab5aace37309bf2185936/x/asset/ft/keeper/token_upgrade.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

var versions []types.PendingTokenUpgrade
</blockquote></details>

then linter will complain about uninitialized slice
___
*[`x/asset/ft/keeper/upgrade.go` line 1 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsgD4i54C_4Dh1qsju:-NXu04NB8hKeQS5Owy38:b-5e5lsu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgrade.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can keep the v1 and common logic in single `token_upgrade` file I don't see any need to have one more. 
</blockquote></details>

let's discuss


<!-- Sent from Reviewable.io -->

2023-06-14 14:22 UTC, miladz68 requested changes
> Reviewed 5 of 13 files at r8, 1 of 3 files at r9, 1 of 7 files at r12, 7 of 12 files at r13, 1 of 4 files at r14, 1 of 2 files at r15, 7 of 12 files at r16, 8 of 9 files at r17, 5 of 5 files at r18, 3 of 4 files at r19, 1 of 1 files at r20, 7 of 12 files at r21, 1 of 2 files at r22, 1 of 1 files at r23, 7 of 18 files at r24, 7 of 16 files at r25, 24 of 28 files at r27, 1 of 1 files at r28, 4 of 4 files at r29, 3 of 3 files at r30, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 1 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXuGQ7Z6Yw1qBqj2Bfa:-NXuGQ7Z6Yw1qBqj2Bfb:bao19g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/71ea6a946b035bef5d9ab5aace37309bf2185936/pkg/config/genesis/genesis.v1.tmpl.json#L1)):*
> ```JSON
> {
> ```

I think we should try to find a way to avoid this. 


<!-- Sent from Reviewable.io -->

2023-06-15 07:59 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 62 of 68 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 321 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsaFfnEVwPK3WtVdLC:-NXxlC4M9wlaAw8VagQh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/integration-tests/upgrade/ft.go#L321)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`requireT.Equals([]{assetfttypes.Feature_minting, assetfttypes.Feature_freezing .... }, resp.Token.Features)`
</blockquote></details>

Done.
___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 1 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXuGQ7Z6Yw1qBqj2Bfa:-NXxlDnMDODvzqbgFfAo:b-ti1rx0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8f41e79aa9908cec3ee757e26983b6c657b17beb/pkg/config/genesis/genesis.v1.tmpl.json#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we should try to find a way to avoid this. 
</blockquote></details>

Any ideas are welcomed. The only other I have is to run `init` command, and then read the json and modify it according to our needs. But as you already know I highly dislike that concept.  If this is the only alternative than I prefer to have separate templates. This is very similar to hardcoded jsons for mainnet and testnet, so here we have hardcoded templates for versions of devnet. You prepare it once, push and forget.
___
*[`x/delay/types/keys.go` line 47 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXso0YfEq6d9iY4G6y9:-NXy3LdD43LqcOcs0ZAH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/delay/types/keys.go#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO that func worth separate unit tests.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/token_upgrade.go` line 65 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXtyYtU8-LChazDBgzS:-NXxm5pA8QS1CCrY_wym:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8f41e79aa9908cec3ee757e26983b6c657b17beb/x/asset/ft/keeper/token_upgrade.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use the `types.CreatePendingTokenUpgradeKey(denom)` here as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-15 08:18 UTC, miladz68 requested changes
> Reviewed 6 of 6 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 1 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXuGQ7Z6Yw1qBqj2Bfa:-NXy7Ppe3N4fBXoPyXZY:bsxb6r4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8f41e79aa9908cec3ee757e26983b6c657b17beb/pkg/config/genesis/genesis.v1.tmpl.json#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Any ideas are welcomed. The only other I have is to run `init` command, and then read the json and modify it according to our needs. But as you already know I highly dislike that concept.  If this is the only alternative than I prefer to have separate templates. This is very similar to hardcoded jsons for mainnet and testnet, so here we have hardcoded templates for versions of devnet. You prepare it once, push and forget.
</blockquote></details>

I prefer what you mentioned to this separate templates idea. 


<!-- Sent from Reviewable.io -->

2023-06-15 08:19 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 67 of 68 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 1 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXuGQ7Z6Yw1qBqj2Bfa:-NXy7qqm7ldz4cDp4jL8:bu7hes9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8f41e79aa9908cec3ee757e26983b6c657b17beb/pkg/config/genesis/genesis.v1.tmpl.json#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I prefer what you mentioned to this separate templates idea. 
</blockquote></details>

I know :-) let's discuss after daily


<!-- Sent from Reviewable.io -->

2023-06-15 08:21 UTC, miladz68 requested changes
> Reviewed 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 1 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXuGQ7Z6Yw1qBqj2Bfa:-NXy8GLl-GOM9vbvr0ij:bb74ce2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8f41e79aa9908cec3ee757e26983b6c657b17beb/pkg/config/genesis/genesis.v1.tmpl.json#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I know :-) let's discuss after daily
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2023-06-15 08:55 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 12 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXyFH5z8JbI4Isy17RT:b-87udtq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, they have versioned structures too
</blockquote></details>

I've checked the staking, and they don't use the additional protos for it. 
___
*[`x/asset/ft/keeper/keeper.go` line 215 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXseb5w80Ti11F2dsd_:-NXyFXW4ArMNM1tI8DCF:b-7qdg91) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/keeper/keeper.go#L215)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Any fuckup which might happen in the meantime
</blockquote></details>

IMO `Any` is not a reson.  IF you see a reason, then let's handle it, if don't let's remove it.  
___
*[`x/asset/ft/types/params.go` line 13 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsmFj20TriKU2cYPet:-NXyFoUf2d-nxKmYXWI2:b-t9hunk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/x/asset/ft/types/params.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, I use it to initialize default genesis params too
</blockquote></details>

Actually not. But I see that you have moved it.


<!-- Sent from Reviewable.io -->

2023-06-15 10:46 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 65 of 68 files reviewed, 11 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXyeBCt9SBKh3IbwWvQ:b818caj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

https://github.com/cosmos/cosmos-sdk/blob/release/v0.45.x/x/staking/legacy/v034/types.go

You may see `Params` struct is defined there. They didn't use proto for this, just defined it manually.
I decided to use proto to have unmarshaller generated  for free.
</blockquote></details>

IMO their approach is better. And keeping the single Params struct in the code. 


<!-- Sent from Reviewable.io -->

2023-06-15 10:59 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 65 of 68 files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXyhM0f9O1mzwQFf3X5:b-atg80j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO their approach is better. And keeping the single Params struct in the code. 
</blockquote></details>

But then I need to deal with unmarshaling from proto manually or copy that code


<!-- Sent from Reviewable.io -->

2023-06-15 11:47 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 62 of 69 files reviewed, 11 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXys32N0xjnYuBqyfPa:b-4lc15t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But then I need to deal with unmarshaling from proto manually or copy that code
</blockquote></details>

But why do you need props if there are no proto in the SDK example you shared?


<!-- Sent from Reviewable.io -->

2023-06-15 12:28 UTC, ysv requested changes
> Reviewed 1 of 12 files at r21, 1 of 2 files at r22, 4 of 18 files at r24, 4 of 16 files at r25, 13 of 28 files at r27, 3 of 6 files at r32, 1 of 1 files at r33, 1 of 3 files at r34, 3 of 5 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyuSad7FfWrZm1QDqQ:-NXyuSad7FfWrZm1QDqR:b-7orkq2) (no related file):*
I kinda disagree with PR title. It is not about delayed message for enabling IBC it is just impl detail
I would call it "Implement TokenUpgrade flow for FT"

___
___
*[`x/asset/ft/types/params.go` line 15 at r35](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyxaMz2Pl11Ln0qonA:-NXyxaMz2Pl11Ln0qonB:b3km1r0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ef6c63c3a1b47d7ef03ad3d8d736bcf76bdac597/x/asset/ft/types/params.go#L15)):*
> ```Go
> 
> // DefaultTokenUpgradeDecisionTimeout is the timeout for a decision to upgrade the token.
> var DefaultTokenUpgradeDecisionTimeout = time.Date(1, 1, 1, 0, 0, 0, 0, time.UTC)
> ```

could you remind how `DefaultParams()` is used ?
Because as I see this value is used only there
___
*[`x/asset/ft/types/params.go` line 82 at r35](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyy3iD1IgXc4vsOSIS:-NXyy3iD1IgXc4vsOSIT:b-2sgytg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ef6c63c3a1b47d7ef03ad3d8d736bcf76bdac597/x/asset/ft/types/params.go#L82)):*
> ```Go
> }
> 
> func validateTokenUpgradeDecisionTimeout(i interface{}) error {
> ```

why should it be interface but not time.Time if TokenUpgradeDecisionTimeout is time.Time
___
*[`x/asset/ft/types/token.go` line 229 at r35](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyz6OP23MF1lNLjhQL:-NXyz6OP23MF1lNLjhQM:b-pszy8k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ef6c63c3a1b47d7ef03ad3d8d736bcf76bdac597/x/asset/ft/types/token.go#L229)):*
> ```Go
> func NewTokenUpgradeV1Handler(keeper TokenUpgradeV1Keeper) delaytypes.Handler {
> 	return func(ctx sdk.Context, data proto.Message) error {
> 		return keeper.UpgradeTokenToV1(ctx, data.(*DelayedTokenUpgradeV1))
> ```

should we make type casting & return error if !ok ?
___
*[`x/delay/genesis_test.go` line 79 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQXFPGE9fsa2ZnqqW6:-NXyzSP-9ZQXOMqWaZZH:b-jddza9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/genesis_test.go#L79)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`codectypes.Any` stores some cached data in private field causing assertions to fail
</blockquote></details>

`newDelayedItemIgnoringCache` / `newDelayedItemNoCache` ?
___
*[`x/delay/keeper/keeper_test.go` line 87 at r35](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXz-JMpBh9Ltlw0QPro:-NXz-JMpBh9Ltlw0QPrp:b90c4nq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ef6c63c3a1b47d7ef03ad3d8d736bcf76bdac597/x/delay/keeper/keeper_test.go#L87)):*
> ```Go
> 
> 	requireT.NoError(delayKeeper.DelayExecution(ctx, "delayed-value1", delayed1, time.Second))
> 	requireT.Error(delayKeeper.DelayExecution(ctx, "delayed-value1", delayed1, time.Second))
> ```

error because of the same key & time right ?
what if key is the same but time is differnt ? add this test case ?


<!-- Sent from Reviewable.io -->

2023-06-15 12:28 UTC, miladz68 reviewed
> Reviewed 2 of 3 files at r34, 5 of 5 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-06-15 15:03 UTC, miladz68 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-15 15:09 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 211 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXygSen1t15k4WMim-u:-NXzRYDz2beAFFpg8uwP:bfq2krx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/integration-tests/modules/assetft_test.go#L211)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is why I assign received version to expected version - to make test working with any token version we have now or might have in the future
</blockquote></details>

let's create a constant for current version and assign it in tests instead of received value
___
*[`integration-tests/upgrade/ft.go` line 126 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyn7QH76QfUUMNYkyh:-NXzab0s629ak3tpI5Bk:bu4wwfw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/integration-tests/upgrade/ft.go#L126)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I like test done here. 
They are quite clear and cover most cases.

Suggestion from my end is to split them into multiple funcs because this one has almost 300 lines

what could be done:

```
func (ft *ftTest) After(t *testing.T) {
  ft.testIssuingNewTokenAndUpgrade()
  ft.testUpgradingV0Token()
  // ...
}
```
</blockquote></details>

yep, I will do it
___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 1 at r31](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXuGQ7Z6Yw1qBqj2Bfa:-NXzSQXm2EAN53UxQov5:b83pizl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8f41e79aa9908cec3ee757e26983b6c657b17beb/pkg/config/genesis/genesis.v1.tmpl.json#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Let's keep it like this and refactor it separately
___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NXzTBGU-FOy6GG_CLJY:b-r19ehv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I like the way it is done in staking in terms of moving it to a separate `legacy` director
As for marshalling I'm not sure
</blockquote></details>

Let's copy the generated code to legacy, let's check how they do it in v0.47
Maybe they read the params directly from the params module
___
*[`proto/coreum/asset/ft/v1/token.proto` line 63 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyqIAM0ArCUBAfreSQ:-NXzVHan1xfGPdJhX7lv:b-itakou) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/proto/coreum/asset/ft/v1/token.proto#L63)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would not return it for users right now
keeping in TokenDefinition is ok but I'm not sure about exposing to users now
</blockquote></details>

let's remove
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 110 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyqZqE6EYpCDFp0Bti:-NXzVPsj9r7j6CiAeq8k:b-ita8as) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/proto/coreum/asset/ft/v1/tx.proto#L110)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same as here `rpc UpgradeTokenV1(MsgTokenUpgradeV1) returns (EmptyResponse);`
I think it should be named `MsgUpgradeTokenV1` since in all msgs we have verb first `MsgSetWhitelistedLimit` `MsgFreeze` etc
</blockquote></details>

let's rename
___
*[`x/asset/ft/keeper/keeper.go` line 73 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXys2TU34ENNwRcMXhD:-NXzVUec3nLgeTdzagz8:bedplps) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/x/asset/ft/keeper/keeper.go#L73)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this method is never called.
and why do we need this method ? We will never have to set v1 params
</blockquote></details>

yep, let's remove
___
*[`x/asset/ft/keeper/keeper_test.go` line 35 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXysexB1_qfMXjmPuGW:-NXzWRm23UIW-vPV-zEL:b-1fus9s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/x/asset/ft/keeper/keeper_test.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The value set in DefaultParams is used in generated default genesis json. I don't know why it is set here like this, and it's unrelated to this PR :-)
</blockquote></details>

it's ok
___
*[`x/asset/ft/types/token.go` line 229 at r35](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyz6OP23MF1lNLjhQL:-NXzZ-ZR54rHgFvKq9cK:b-yntd4y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ef6c63c3a1b47d7ef03ad3d8d736bcf76bdac597/x/asset/ft/types/token.go#L229)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

it's fine
___
*[`x/delay/genesis_test.go` line 79 at r19](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXQXFPGE9fsa2ZnqqW6:-NXzZ3_QCWRJck6kupYM:b-ita8as) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5e98aa82b989a5766f7428f1d8452b6db27a6da/x/delay/genesis_test.go#L79)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`newDelayedItemIgnoringCache` / `newDelayedItemNoCache` ?
</blockquote></details>

let's rename
___
*[`x/asset/ft/keeper/upgrade.go` line 1 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsgD4i54C_4Dh1qsju:-NXzY6BW25QhzotPNSHz:bmtobmo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgrade.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss
</blockquote></details>

let's keep it as is


<!-- Sent from Reviewable.io -->

2023-06-16 09:38 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 45 of 69 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 12 at r26](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXsdB7d-oVCBdRrHnfC:-NY2ZMn1BRV6YGOIauMs:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a21ce11d46329ac2e75f7d90f408380eaa60ec2/proto/coreum/asset/ft/v1/params.proto#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's copy the generated code to legacy, let's check how they do it in v0.47
Maybe they read the params directly from the params module
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-16 10:28 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 45 of 69 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 211 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXygSen1t15k4WMim-u:-NY2jjrjETpj8BaUJXZN:bq4d717) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/integration-tests/modules/assetft_test.go#L211)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I changed it in nit tests but integration tests it must stay like this so they work with both versions


<!-- Sent from Reviewable.io -->

2023-06-16 11:21 UTC, miladz68 approved these changes
> Reviewed 14 of 16 files at r36, 1 of 1 files at r37, 9 of 9 files at r38, 1 of 1 files at r39, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-16 11:23 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 22 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 19 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2sJPJ-AtTki3dQD7K:-NY2sJPKD4TS_jnEpSZj:bkii0p3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/proto/coreum/asset/ft/v1/params.proto#L19)):*
> ```proto
>   ];
> 
>   // ibc_decision_timeout defines the end of the decision period for enabling IBC
> ```

wrong comment
___
*[`proto/coreum/asset/ft/v1/params.proto` line 26 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2sOTPAqn4mrc9QgNu:-NY2sOTPAqn4mrc9QgNv:bkii0p3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/proto/coreum/asset/ft/v1/params.proto#L26)):*
> ```proto
>   ];
> 
>   // ibc_grace_period defines the period after which IBC is effectively enabled
> ```

wrong comment
___
*[`x/asset/ft/keeper/keeper.go` line 139 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2tKMc4JqqugxZ956H:-NY2tKMc4JqqugxZ956I:bllucmg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/keeper.go#L139)):*
> ```Go
> // Issue issues new fungible token and returns it's denom.
> func (k Keeper) Issue(ctx sdk.Context, settings types.IssueSettings) (string, error) {
> 	return k.IssueVersioned(ctx, settings, types.CurrentTokenVersion)
> ```

Not clear why do you need both `Issue` and `IssueVersioned` why can't you just use the version in the `Issue`?
___
*[`x/asset/ft/keeper/msg_server.go` line 196 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2u1SYAj8ek_Z1x7-0:-NY2u1SYAj8ek_Z1x7-1:b-de2a7s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/msg_server.go#L196)):*
> ```Go
> 	}
> 
> 	err = ms.keeper.StoreDelayedTokenUpgradeV1(ctx, sender, req.Denom, req.IbcEnabled)
> ```

Minor: I would call it `AddDelayedTokenUpgradeV1`, since when you see the `Store` seems you just directly interact with the Store.
___
*[`x/asset/ft/types/token.go` line 32 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2spX16ZqG-h-8_58C:-NY2spX16ZqG-h-8_58D:bcrmn49) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/types/token.go#L32)):*
> ```Go
> const (
> 	// CurrentTokenVersion is the version of the token produced by the current version of the app.
> 	CurrentTokenVersion = 1
> ```

Why do you use two constants `const tokenUpgradeV1Version = 1` and this one? IMO you should use only the `CurrentTokenVersion`.
___
*[`x/asset/ft/keeper/token_upgradev1.go` line 39 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2qe12-AhQ8bsA7yIt:-NY2qe12-AhQ8bsA7yIu:bzdixj3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/token_upgradev1.go#L39)):*
> ```Go
> 
> 	if def.Version >= tokenUpgradeV1Version {
> 		return errors.Errorf("denom %s has been already upgraded to v1", denom)
> ```

Why don't you wrap errors into the SDK errors here and in other places as well and don't check the errors in the integration tests as `ErrorIs` ? IMO all keeper errors should be wrapped in the errors separated by errors/error types we already have. Check please all errors with `errors.Errorf` and wrap them. 
@miladz68 @ysv WDYT (BTW there are already in master the errors which are not wrapped but should be IMO).
___
*[`x/asset/ft/keeper/upgradev1.go` line 21 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2uU2a7Io10kFf9lea:-NY2uU2a7Io10kFf9leb:b-x2el5r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgradev1.go#L21)):*
> ```Go
> 
> // DelayKeeper defines methods required from the delay keeper.
> type DelayKeeper interface {
> ```

That interface should be localed in the `expected_keepers` file.


<!-- Sent from Reviewable.io -->

2023-06-16 11:43 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 64 of 71 files reviewed, 22 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/params.proto` line 19 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2sJPJ-AtTki3dQD7K:-NY2wyF52pDiR64U9PVK:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/proto/coreum/asset/ft/v1/params.proto#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

wrong comment
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/params.proto` line 26 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2sOTPAqn4mrc9QgNu:-NY2x5Td0HX0VgMPD6a-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/proto/coreum/asset/ft/v1/params.proto#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

wrong comment
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 139 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2tKMc4JqqugxZ956H:-NY2xAa70o4tRviCNkBE:bbrytp7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/keeper.go#L139)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not clear why do you need both `Issue` and `IssueVersioned` why can't you just use the version in the `Issue`?
</blockquote></details>

For unit test I need to issue a token with version 0
___
*[`x/asset/ft/keeper/msg_server.go` line 196 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2u1SYAj8ek_Z1x7-0:-NY2xvrBDbK3wlGEAIbq:b-8611rr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/msg_server.go#L196)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Minor: I would call it `AddDelayedTokenUpgradeV1`, since when you see the `Store` seems you just directly interact with the Store.
</blockquote></details>

I have a general problem with the name of that method. Because it might be delayed or might be not. If ibc_enabled is false then the action is immediate. If ibc_enabled is true the action is delayed
___
*[`x/asset/ft/types/token.go` line 32 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2spX16ZqG-h-8_58C:-NY3--4vDfwIEaROUgXX:b-2emltl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/types/token.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you use two constants `const tokenUpgradeV1Version = 1` and this one? IMO you should use only the `CurrentTokenVersion`.
</blockquote></details>

`tokenUpgradeV1Version` just stores the version upgrade v1 action should upgrade the token to.
`CurrentTokenVersion` stores the version used by newly issued tokens.
They might not necessarily be the same. If we work on upgrade to v2 while v1 is still in progress `CurrentTokenVersion` will be changed to 2 but `tokenUpgradeV1Version` will stay the same
___
*[`x/asset/ft/keeper/token_upgradev1.go` line 39 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2qe12-AhQ8bsA7yIt:-NY2zxcu9axsmdtaAeZn:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/token_upgradev1.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you wrap errors into the SDK errors here and in other places as well and don't check the errors in the integration tests as `ErrorIs` ? IMO all keeper errors should be wrapped in the errors separated by errors/error types we already have. Check please all errors with `errors.Errorf` and wrap them. 
@miladz68 @ysv WDYT (BTW there are already in master the errors which are not wrapped but should be IMO).
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/upgradev1.go` line 21 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2uU2a7Io10kFf9lea:-NY2yPflA8idzDyZIYJp:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd56c616ab2b4de658bdfba9caa6915eb9d825ba/x/asset/ft/keeper/upgradev1.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That interface should be localed in the `expected_keepers` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-16 11:52 UTC, ysv requested changes
> Reviewed 13 of 16 files at r36, 1 of 1 files at r37, 7 of 9 files at r38, 1 of 1 files at r39, 7 of 7 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 211 at r34](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXygSen1t15k4WMim-u:-NY3-KsPDfvbwlfcF1ND:bgiulwf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5f5116c9feee318ae295dafa269f6d056e2eeeee/integration-tests/modules/assetft_test.go#L211)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I changed it in nit tests but integration tests it must stay like this so they work with both versions
</blockquote></details>

but lets do the same here as in unit tests. Why can't we use types.CurrentTokenVersion

if no then lets define a const inside this file and use it here

```
const currentTokenVersion := 1

// inside test
Version:            currentTokenVersion
```
___
*[`x/asset/ft/keeper/token_upgradev1.go` line 39 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2qe12-AhQ8bsA7yIt:-NY30SW8DszYCtdPXoOQ:b-s8c12y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/token_upgradev1.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

yes I think at some point we stopped doing this
Lets add to backlog and discuss


<!-- Sent from Reviewable.io -->

2023-06-16 12:12 UTC, ysv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)



<!-- Sent from Reviewable.io -->

2023-06-16 12:12 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/before_send_test.go` line 20 at r9](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NXyrn1d1buqxnx1RBLF:-NY34DaO8swd131yS4Uu:byr4flj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/002dae9706a2a9c1b214a6df7a8a7e8b0668b90f/x/asset/ft/keeper/before_send_test.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@dzmitryhil asked me to remove this stuff as I touched the ft keeper and it was some leftover not used anywhere
</blockquote></details>

Right.
___
*[`x/asset/ft/keeper/msg_server.go` line 196 at r39](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY2u1SYAj8ek_Z1x7-0:-NY34Ny7Bu4KvvmodQV_:bd96uml) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b097253c6b969c6636eaa7ac1a30814b0a9922c/x/asset/ft/keeper/msg_server.go#L196)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I have a general problem with the name of that method. Because it might be delayed or might be not. If ibc_enabled is false then the action is immediate. If ibc_enabled is true the action is delayed
</blockquote></details>

But the `Add` word looks good anyways. 
___
*[`x/asset/ft/legacy/v1/params.go` line 25 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35mpJ5kOgjjZbYiW2:-NY35mpJ5kOgjjZbYiW3:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/legacy/v1/params.go#L25)):*
> ```Go
> 	ftSubspace, ok := paramsKeeper.GetSubspace(types.ModuleName)
> 	if !ok {
> 		return errors.New("params subspace does not exist")
> ```

should be sdk error
___
*[`x/asset/ft/types/params.go` line 61 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35TnM6T5CdcMG3sMv:-NY35TnM6T5CdcMG3sMw:b-3zv3h4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L61)):*
> ```Go
> 	fee, ok := i.(sdk.Coin)
> 	if !ok {
> 		return errors.Errorf("invalid parameter type: %T", i)
> ```

should be sdk error (I know that's prev code bu if you are updating that file better to update it as well) 
___
*[`x/asset/ft/types/params.go` line 64 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35TdSEj4RHdLF2iS9:-NY35TdSEj4RHdLF2iSA:b-3zv3h4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L64)):*
> ```Go
> 	}
> 	if fee.IsNil() || !fee.IsValid() {
> 		return errors.New("issue fee must be a non-negative value")
> ```

should be sdk error (I know that's prev code bu if you are updating that file better to update it as well) 
___
*[`x/asset/ft/types/params.go` line 72 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35TKu0CPgRdr67Sz4:-NY35TKu0CPgRdr67Sz5:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L72)):*
> ```Go
> 	decisionTimeout, ok := i.(time.Time)
> 	if !ok {
> 		return errors.Errorf("invalid parameter type: %T", i)
> ```

should be sdk error
___
*[`x/asset/ft/types/params.go` line 75 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35RS1Ax2WTmWqEunc:-NY35RS1Ax2WTmWqEund:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L75)):*
> ```Go
> 	}
> 	if decisionTimeout.Before(DefaultTokenUpgradeDecisionTimeout) {
> 		return errors.Errorf("decision timeout cannot be set before %s", DefaultTokenUpgradeDecisionTimeout)
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 58 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY365B5-okYLRwq9OV7:-NY365B5-okYLRwq9OV8:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L58)):*
> ```Go
> 	store := ctx.KVStore(k.storeKey)
> 	if store.Has(key) {
> 		return errors.Errorf("delayed item is already stored under the key, id: %s", id)
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 63 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY365mO5ZHSaT1uhmgE:-NY365mO5ZHSaT1uhmgF:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L63)):*
> ```Go
> 	dataAny, err := codectypes.NewAnyWithValue(data)
> 	if err != nil {
> 		return errors.WithStack(err)
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 68 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY3668sAa-INYE4-4BK:-NY3668sAa-INYE4-4BL:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L68)):*
> ```Go
> 	b, err := k.cdc.Marshal(dataAny)
> 	if err != nil {
> 		return errors.Wrap(err, "marshaling delayed item failed")
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 98 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY367XB9OWFMXwnyvZy:-NY367XB9OWFMXwnyvZz:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L98)):*
> ```Go
> 		dataAny := &codectypes.Any{}
> 		if err := k.cdc.Unmarshal(iter.Value(), dataAny); err != nil {
> 			return errors.Wrap(err, "decoding delayed message failed")
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 103 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY367peBJ7q5kelKb6m:-NY367peBJ7q5kelKb6n:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L103)):*
> ```Go
> 		var data codec.ProtoMarshaler
> 		if err := k.cdc.UnpackAny(dataAny, &data); err != nil {
> 			return errors.Wrap(err, "unpacking delayed message failed")
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 124 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY368IqEDZp5QYOjPnR:-NY368IqEDZp5QYOjPnS:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L124)):*
> ```Go
> 		var data codec.ProtoMarshaler
> 		if err := k.registry.UnpackAny(i.Data, &data); err != nil {
> 			return errors.WithStack(err)
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 146 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY369g09vMkOStNC5oJ:-NY369g09vMkOStNC5oK:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L146)):*
> ```Go
> 		data := &codectypes.Any{}
> 		if err := k.cdc.Unmarshal(value, data); err != nil {
> 			return errors.WithStack(err)
> ```

should be sdk error
___
*[`x/delay/keeper/keeper.go` line 159 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY3690GEQZR3PaZSaNc:-NY3690GEQZR3PaZSaNd:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L159)):*
> ```Go
> 
> 	if err != nil {
> 		return nil, errors.WithStack(err)
> ```

should be sdk error
___
*[`x/delay/types/keys.go` line 31 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY36NTR7R8Lj-YfiK_T:-NY36NTR7R8Lj-YfiK_U:b-czsqmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/types/keys.go#L31)):*
> ```Go
> func CreateDelayedItemKey(id string, t time.Time) ([]byte, error) {
> 	if id == "" {
> 		return nil, errors.New("id cannot be empty")
> ```

should be sdk error
___
*[`x/delay/types/keys.go` line 36 at  [...]

2023-06-16 12:14 UTC, miladz68 submitted a review, later dismissed
> Reviewed 7 of 7 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: all files reviewed, 17 unresolved discussions (waiting on @silverspase and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-06-16 12:36 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 64 of 72 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/legacy/v1/params.go` line 25 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35mpJ5kOgjjZbYiW2:-NY3Ad0aDS4Qk8MQYKJi:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/legacy/v1/params.go#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/asset/ft/types/params.go` line 61 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35TnM6T5CdcMG3sMv:-NY3B7bz8NOCxc5v0Opr:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error (I know that's prev code bu if you are updating that file better to update it as well) 
</blockquote></details>

Done.
___
*[`x/asset/ft/types/params.go` line 64 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35TdSEj4RHdLF2iS9:-NY3B81k-Jx7aTg2qmk8:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L64)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error (I know that's prev code bu if you are updating that file better to update it as well) 
</blockquote></details>

Done.
___
*[`x/asset/ft/types/params.go` line 72 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35TKu0CPgRdr67Sz4:-NY3B8lt-xwaNjecPwcw:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L72)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/asset/ft/types/params.go` line 75 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY35RS1Ax2WTmWqEunc:-NY3B9Rm0l7KGnK4cCUB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/asset/ft/types/params.go#L75)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 58 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY365B5-okYLRwq9OV7:-NY39Fj-EnpPk6bJhPT4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 63 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY365mO5ZHSaT1uhmgE:-NY39HPb-2_xnzZPG_-X:b4gceaf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

NewAnyWithValue already returns sdk error
___
*[`x/delay/keeper/keeper.go` line 68 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY3668sAa-INYE4-4BK:-NY3BB78EKMunbah3hGB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 98 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY367XB9OWFMXwnyvZy:-NY39LFi574TsXrsZzkT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L98)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 103 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY367peBJ7q5kelKb6m:-NY39MbED3doRyPcq-f4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L103)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 124 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY368IqEDZp5QYOjPnR:-NY39NOh9d6m_FIrBP9w:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 146 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY369g09vMkOStNC5oJ:-NY39Oec2yqmzAY-5BXD:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L146)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/keeper/keeper.go` line 159 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY3690GEQZR3PaZSaNc:-NY39Tbr9Rvi2vdMAb87:bmg5br8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/keeper/keeper.go#L159)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

err returned from pagination is already an sdkerror
___
*[`x/delay/types/keys.go` line 31 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY36NTR7R8Lj-YfiK_T:-NY3A2Kf7vBIefikJ9qU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/types/keys.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/types/keys.go` line 36 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY36NshEbW08I5m9KIs:-NY3A2ka28pt69LcDlku:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/types/keys.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.
___
*[`x/delay/types/keys.go` line 49 at r40](https://reviewable.io/reviews/CoreumFoundation/coreum/510#-NY36OD42BmaPjhEpb4-:-NY3A6vs-eMerXsFY0p7:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2d712414f9ef65bc72549239a6f303eebb4de4d3/x/delay/types/keys.go#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

should be sdk error
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-16 12:41 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: 61 of 72 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-16 13:41 UTC, ysv approved these changes
> Reviewed 1 of 2 files at r41, 7 of 7 files at r42, 2 of 3 files at r43, 1 of 1 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/510)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-06-16 13:59 UTC, merged