new coreum_wasm_sdk features (version upgrade) and integration tests
CoreumFoundation/coreum pull request #536
Opened 2023-06-26 14:21 UTC by keyleu

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/coreum/536)

2023-06-27 07:13 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/testdata/wasm/ft/package/coreum-wasm-sdk/.gitignore` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvgJfYAfaRG_4vWC2B:-NYvgJfYAfaRG_4vWC2C:b-htblx4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9c8f997ee63ff9cd021283741085652677af9594/integration-tests/modules/testdata/wasm/ft/package/coreum-wasm-sdk/.gitignore#L1)):*
> ```ignore
> .idea
> ```

It's possible to import the crate from the git, that's how you can tests that the SDK is valid. Could you please do it and remove the copy, since not clear now what will be left.


<!-- Sent from Reviewable.io -->

2023-06-27 07:15 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvhCyHDlsiSapFodMm:-NYvhCyHDlsiSapFodMn:bjg2bak) (no related file):*
IMO it's a bad idea to mix up those 2 PRs. Not it is'n clear what to review :-( 
It would be nice to separate them. 

___


<!-- Sent from Reviewable.io -->

2023-06-27 08:05 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvhCyHDlsiSapFodMm:-NYvs5ex9QYixg935HuW:b-nbqp4f) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO it's a bad idea to mix up those 2 PRs. Not it is'n clear what to review :-( 
It would be nice to separate them. 
</blockquote></details>

base64 is only like 2 lines of code in query.go

___
___
*[`integration-tests/modules/testdata/wasm/ft/package/coreum-wasm-sdk/.gitignore` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvgJfYAfaRG_4vWC2B:-NYvshqK8PANA45H8_0x:bef2val) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9c8f997ee63ff9cd021283741085652677af9594/integration-tests/modules/testdata/wasm/ft/package/coreum-wasm-sdk/.gitignore#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's possible to import the crate from the git, that's how you can tests that the SDK is valid. Could you please do it and remove the copy, since not clear now what will be left.
</blockquote></details>

ok will do that


<!-- Sent from Reviewable.io -->

2023-06-27 08:15 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvhCyHDlsiSapFodMm:-NYvv-Py9ga4jD7srC6Y:b1vn85y) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

base64 is only like 2 lines of code in query.go
</blockquote></details>

still want me to separate them?

___


<!-- Sent from Reviewable.io -->

2023-06-27 08:16 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvhCyHDlsiSapFodMm:-NYvv3NODqdO01BrGngr:b-rizdvo) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

still want me to separate them?
</blockquote></details>

But better to split it anyways, for the git history and PRs consistency.

___


<!-- Sent from Reviewable.io -->

2023-06-27 08:27 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYvhCyHDlsiSapFodMm:-NYvxZG_3MDSQU1B6Ij4:b-3b28zm) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But better to split it anyways, for the git history and PRs consistency.
</blockquote></details>

done, removed the base64 changes from here and separated in different PR

___


<!-- Sent from Reviewable.io -->

2023-06-27 09:35 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 27 files reviewed, 6 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/contract.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYw72AD3wnZPG5wxbnn:-NYw72AD3wnZPG5wxbno:bpq1vys) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/contract.go#L1)):*
> ```Go
> package modules
> ```

This file make sence, only if it's located in the `modules/testdata/wasm`, but if you do it that way update it for IBC tests as well.  But not sure that this file is needed at all. 
___
*[`integration-tests/modules/contract.go` line 14 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYw6g7ECFkgmY4OkHh5:-NYw6g7ECFkgmY4OkHh6:b-f2ii0p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/contract.go#L14)):*
> ```Go
> 	//nolint
> 	//go:embed testdata/wasm/ft/artifacts/ft.wasm
> 	FTWASM []byte
> ```

Why the FT is uppercase but bft is lower?
___
*[`integration-tests/modules/wasm_test.go` line 1172 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYwAdTyBOoFK8RS9H9r:-NYwAdTyBOoFK8RS9H9s:b-4fr5ze) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/wasm_test.go#L1172)):*
> ```Go
> 	royaltyRate := sdk.MustNewDecFromStr("0.1")
> 	dataString := "data"
> 	databytes, err := base64.StdEncoding.DecodeString(dataString)
> ```

Rename that var plz to `dataBase64Bytes` or similar since it collides with the `dataBytes` variable.
___
*[`integration-tests/modules/wasm_test.go` line 1172 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYwAujBAqRAz0Ffwebb:-NYwAujBAqRAz0Ffwebc:b-xkbtwh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/wasm_test.go#L1172)):*
> ```Go
> 	royaltyRate := sdk.MustNewDecFromStr("0.1")
> 	dataString := "data"
> 	databytes, err := base64.StdEncoding.DecodeString(dataString)
> ```

Not clear why do you need to Decode the string here.  If the fix with the decode/encode on the handler level is correct no extra decoding is needed. Right?


<!-- Sent from Reviewable.io -->

2023-06-27 10:14 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 28 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/contract.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYw72AD3wnZPG5wxbnn:-NYwLAmcA466RR1_xYuy:b-cioo6v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/contract.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This file make sence, only if it's located in the `modules/testdata/wasm`, but if you do it that way update it for IBC tests as well.  But not sure that this file is needed at all. 
</blockquote></details>

Will modify as agreed
___
*[`integration-tests/modules/contract.go` line 14 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYw6g7ECFkgmY4OkHh5:-NYwHRFw2eWhB_MpynkF:b-tw34sk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/contract.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the FT is uppercase but bft is lower?
</blockquote></details>

like we discussed, it's for upgrades.
___
*[`integration-tests/modules/wasm_test.go` line 1172 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYwAdTyBOoFK8RS9H9r:-NYwHU5PDbj9Maz6o7kp:b-penbeh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/wasm_test.go#L1172)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Rename that var plz to `dataBase64Bytes` or similar since it collides with the `dataBytes` variable.
</blockquote></details>

will move to the other PR and rename
___
*[`integration-tests/modules/wasm_test.go` line 1172 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NYwAujBAqRAz0Ffwebb:-NYwL5HQ6AgSjXoV6WDL:b-g4aojm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ceae60be3f812a3d2dbbfcd07618a108bb7f0580/integration-tests/modules/wasm_test.go#L1172)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not clear why do you need to Decode the string here.  If the fix with the decode/encode on the handler level is correct no extra decoding is needed. Right?
</blockquote></details>

It's for the test class that we compare with, like discussed.


<!-- Sent from Reviewable.io -->

2023-06-27 11:17 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-28 07:18 UTC, wojtek-coreum requested changes
> Reviewed 11 of 27 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 10 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/wasm_test.go` line 24 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-nNvM9P5sq6XQ66wx:-NZ-nNvM9P5sq6XQ66wy:b2pblu9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/ibc/wasm_test.go#L24)):*
> ```Go
> 	"github.com/CoreumFoundation/coreum-tools/pkg/retry"
> 	integrationtests "github.com/CoreumFoundation/coreum/integration-tests"
> 	ibc "github.com/CoreumFoundation/coreum/integration-tests/ibc/testdata/wasm"
> ```

I think `ibc` alias is misleading. Better keep the original `wasm` or `ibcwasm` if there is a conflict
___
*[`integration-tests/ibc/testdata/wasm/contract.go` line 12 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-ndNjD5qCRr2SVmK2:-NZ-ndNjD5qCRr2SVmK3:btvwu0k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/ibc/testdata/wasm/contract.go#L12)):*
> ```Go
> 	//nolint
> 	//go:embed ibc-transfer/artifacts/ibc_transfer.wasm
> 	IbcTransferWASM []byte
> ```

Here and below: Ibc -> IBC
___
*[`integration-tests/modules/wasm_test.go` line 22 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-nv0V1p0LbXkCweGb:-NZ-nv0V1p0LbXkCweGc:behle4a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/modules/wasm_test.go#L22)):*
> ```Go
> 
> 	integrationtests "github.com/CoreumFoundation/coreum/integration-tests"
> 	modules "github.com/CoreumFoundation/coreum/integration-tests/modules/testdata/wasm"
> ```

modules -> moduleswasm
___
*[`integration-tests/modules/testdata/wasm/ft/Cargo.toml` line 36 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-oIvh8rc4njCpU_Wp:-NZ-oIvh8rc4njCpU_Wq:b-q5jf9z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/modules/testdata/wasm/ft/Cargo.toml#L36)):*
> ```TOML
> cw2 = "1.1.0"
> thiserror = "1.0.40"
> coreum-wasm-sdk = { git = "https://github.com/CoreumFoundation/coreum-wasm-sdk", branch = "keyne/upgrade-token-msg" }
> ```

Please leave a `FIXME (keyne): description` so we know that it should be changed to version later
___
*[`integration-tests/upgrade/ft.go` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-rDRf6xuqZmLRMKlW:-NZ-rDRf6xuqZmLRMKlX:b-hhzlb8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L34)):*
> ```Go
> //nolint:tagliatelle
> type ibcEnabledBodyFTRequest struct {
> 	IbcEnabled bool `json:"ibc_enabled"`
> ```

IBCEnabled
___
*[`integration-tests/upgrade/ft.go` line 169 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-pP0SDbqlIYUFTswM:-NZ-pP0SDbqlIYUFTswN:b8pa9pi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L169)):*
> ```Go
> 			assetfttypes.Feature_whitelisting,
> 		},
> 		BurnRate:           burnRate.String(),
> ```

You don't need burn rate and send commission rate for this test
___
*[`integration-tests/upgrade/ft.go` line 212 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-p_c60eCBgND8kjKU:-NZ-p_c71-_k_ozz71w_:b-7ropln) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L212)):*
> ```Go
> 		InitialAmount:      issuanceAmount.String(),
> 		Description:        "my wasm fungible token",
> 		BurnRate:           burnRate.String(),
> ```

ditto
___
*[`integration-tests/upgrade/ft.go` line 681 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-q3n78I20oHkOgFs8:-NZ-q3n78I20oHkOgFs9:b-whs7vl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L681)):*
> ```Go
> 	txf := chain.TxFactory().WithSimulateAndExecute(true)
> 	const gracePeriod = 15 * time.Second
> 	chain.Governance.UpdateParams(ctx, t, "Propose changing TokenUpgradeGracePeriod in the assetft module",
> ```

You don't need it. It has been already done by the other method in the test. What you can do, you may move that logic to a separate method so it is explicitly visible as a separate step inside `After`
___
*[`integration-tests/upgrade/ft.go` line 716 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-qvwl5ClXfAaVnOBu:-NZ-qvwl5ClXfAaVnOBv:b-e06vy5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L716)):*
> ```Go
> 	case <-ctx.Done():
> 		return
> 	case <-time.After(gracePeriod + 2*time.Second):
> ```

As described above, waiting might be done once for all the tests in the common method updating the grace period
___
*[`x/wasm/handler/query.go` line 447 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-rNxKCPrc6VMX3Y_n:-NZ-rNxKCPrc6VMX3Y_o:bbffvg8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/x/wasm/handler/query.go#L447)):*
> ```Go
> 			}
> 
> 			if nftClassesRes.Classes == nil {
> ```

why? using `len` returns 0 if slice is nil, so it covers both cases - 0 length and nil


<!-- Sent from Reviewable.io -->

2023-06-28 08:12 UTC, miladz68 requested changes
> Reviewed 11 of 27 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 13 unresolved discussions (waiting on @keyleu, @silverspase, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 55 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-zE_658H1cFF2Xvim:-NZ-zE_7AXvrxybE_H1R:bimyqaj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/go.mod#L55)):*
> ```XML
> 	github.com/bgentry/speakeasy v0.1.1-0.20220910012023-760eaf8b6816 // indirect
> 	github.com/btcsuite/btcd/btcec/v2 v2.3.2 // indirect
> 	github.com/cenkalti/backoff/v4 v4.1.3 // indirect
> ```

I don't understand why we need these go mod updates if we are only writing handlers and integration tests. 
___
*[`integration-tests/ibc/wasm_test.go` line 28 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-zcwtAcvGtFNcW0Lf:-NZ-zcwtAcvGtFNcW0Lg:bw6wut0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c85c6067fe8bc0767b596e545656752fea1ab1d5/integration-tests/ibc/wasm_test.go#L28)):*
> ```Go
> var (
> 	//go:embed testdata/wasm/ibc-transfer/artifacts/ibc_transfer.wasm
> 	ibcTransferWASM []byte
> ```

I think it was perfectly fine to embed the binaries here, introducing the new pacakge seems redundant to me. 
___
*[`integration-tests/modules/wasm_test.go` line 31 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-zqFiBmWErMB8uIQD:-NZ-zqFiBmWErMB8uIQE:bt4mycp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c85c6067fe8bc0767b596e545656752fea1ab1d5/integration-tests/modules/wasm_test.go#L31)):*
> ```Go
> var (
> 	//go:embed testdata/wasm/bank-send/artifacts/bank_send.wasm
> 	bankSendWASM []byte
> ```

same comment as before, I don't think this is an improvement 
___
*[`integration-tests/upgrade/ft.go` line 681 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-q3n78I20oHkOgFs8:-NZ02z-E-CnGkMMs6epv:bxycfmg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L681)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need it. It has been already done by the other method in the test. What you can do, you may move that logic to a separate method so it is explicitly visible as a separate step inside `After`
</blockquote></details>

great point


<!-- Sent from Reviewable.io -->

2023-06-28 08:53 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 55 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-zE_658H1cFF2Xvim:-NZ07SeFChbMjpBUWxc4:ba914qr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/go.mod#L55)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't understand why we need these go mod updates if we are only writing handlers and integration tests. 
</blockquote></details>

They were updated when I ran go get.
___
*[`integration-tests/ibc/wasm_test.go` line 24 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-nNvM9P5sq6XQ66wx:-NZ07viF8NAN5wjVcifG:b-esumli) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/ibc/wasm_test.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think `ibc` alias is misleading. Better keep the original `wasm` or `ibcwasm` if there is a conflict
</blockquote></details>

changed to ibcwasm
___
*[`integration-tests/ibc/wasm_test.go` line 28 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-zcwtAcvGtFNcW0Lf:-NZ06CRe1UUx_brwZA51:bink6zd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c85c6067fe8bc0767b596e545656752fea1ab1d5/integration-tests/ibc/wasm_test.go#L28)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it was perfectly fine to embed the binaries here, introducing the new pacakge seems redundant to me. 
</blockquote></details>

Sure, maybe we can discuss with the team? Dima asked me to be consistent but the modules package but I can roll it back if team agrees.
___
*[`integration-tests/ibc/testdata/wasm/contract.go` line 12 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-ndNjD5qCRr2SVmK2:-NZ089O7AQ7v0AnKIp0n:b-n9tkhd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/ibc/testdata/wasm/contract.go#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and below: Ibc -> IBC
</blockquote></details>

changed
___
*[`integration-tests/modules/wasm_test.go` line 22 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-nv0V1p0LbXkCweGb:-NZ08SneAgoONCSM01nN:b-n9tkhd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/modules/wasm_test.go#L22)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

modules -> moduleswasm
</blockquote></details>

changed
___
*[`integration-tests/modules/wasm_test.go` line 31 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-zqFiBmWErMB8uIQD:-NZ08TMo2fGevTlPpB0r:bnj36y0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c85c6067fe8bc0767b596e545656752fea1ab1d5/integration-tests/modules/wasm_test.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

same comment as before, I don't think this is an improvement 
</blockquote></details>

we can discuss it
___
*[`integration-tests/modules/testdata/wasm/ft/Cargo.toml` line 36 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-oIvh8rc4njCpU_Wp:-NZ08Zjg0047bnCvYxjq:bajlbho) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/modules/testdata/wasm/ft/Cargo.toml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please leave a `FIXME (keyne): description` so we know that it should be changed to version later
</blockquote></details>

Yes, this will probably be fixed today when we merge the upgrade of wasm-sdk which is already ready.
___
*[`integration-tests/upgrade/ft.go` line 34 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-rDRf6xuqZmLRMKlW:-NZ08opYDI26WONmID1o:bukgyp0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IBCEnabled
</blockquote></details>

This is how it is defined in the protobuf files... I rather not change this in this task, unless you want me  to change protobuf definitions.
___
*[`integration-tests/upgrade/ft.go` line 169 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-pP0SDbqlIYUFTswM:-NZ09p2V7iqCnHeNJ9xn:b-hfpv0l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L169)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need burn rate and send commission rate for this test
</blockquote></details>

removed
___
*[`integration-tests/upgrade/ft.go` line 212 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-p_c60eCBgND8kjKU:-NZ09pXm0BSPCdX_fQGQ:b-hfpv0l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L212)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

removed
___
*[`integration-tests/upgrade/ft.go` line 681 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-q3n78I20oHkOgFs8:-NZ0Bw9P5-8B05C-dBLo:bwv6vz3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L681)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

great point
</blockquote></details>

Right, took it to a separa
___
*[`integration-tests/upgrade/ft.go` line 716 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-qvwl5ClXfAaVnOBu:-NZ0CB7c9rUGQBNrXx7y:b64b7ma) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/upgrade/ft.go#L716)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As described above, waiting might be done once for all the tests in the common method updating the grace period
</blockquote></details>

waiting needs to be done after we issue the upgrade. Each method issues an upgrade so we need to wait after we issue that upgrade.
___
*[`x/wasm/handler/query.go` line 447 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-rNxKCPrc6VMX3Y_n:-NZ06oBN3c0LUCUIAw3-:ba741at) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/x/wasm/handler/query.go#L447)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why? using `len` returns 0 if slice is nil, so it covers both cases - 0 length and nil
</blockquote></details>

I did it so originally too then realized if I do it like this it won't return the pagination information (Total = 0).
In any case the length is checked afterwards in the loop so it's not an issue.


<!-- Sent from Reviewable.io -->

2023-06-28 09:31 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 7 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/testdata/wasm/ft/Cargo.toml` line 36 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-oIvh8rc4njCpU_Wp:-NZ0KZLR-Vmlp6-6T1UX:b1o54vz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/modules/testdata/wasm/ft/Cargo.toml#L36)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Yes, this will probably be fixed today when we merge the upgrade of wasm-sdk which is already ready.
</blockquote></details>

but leave the fixme anyway in case "probably" won't happen
___
*[`integration-tests/upgrade/ft.go` line 518 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0K-ihD1fBJ86CIPwh:-NZ0K-ihD1fBJ86CIPwi:b-g9bhpf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd4aa1876144d77ce794874681301ba4f6f8f6ca/integration-tests/upgrade/ft.go#L518)):*
> ```Go
> 
> 	// setting grace period to some small value
> 	const gracePeriod = 15 * time.Second
> ```

this constant might be moved to the top of the file (to define a global one for entire code)
___
*[`integration-tests/upgrade/ft.go` line 668 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0K7Yj5NK8vn5CAHkC:-NZ0K7Yj5NK8vn5CAHkD:b-2guby3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd4aa1876144d77ce794874681301ba4f6f8f6ca/integration-tests/upgrade/ft.go#L668)):*
> ```Go
> 	ctx, chain := integrationtests.NewCoreumTestingContext(t)
> 	txf := chain.TxFactory().WithSimulateAndExecute(true)
> 	const gracePeriod = 15 * time.Second
> ```

same here
___
*[`integration-tests/upgrade/ft.go` line 774 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0KFc5DsK7et49zpEm:-NZ0KFc5DsK7et49zpEn:b-2guby3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd4aa1876144d77ce794874681301ba4f6f8f6ca/integration-tests/upgrade/ft.go#L774)):*
> ```Go
> func (ft *ftTest) changeGracePeriod(t *testing.T) {
> 	ctx, chain := integrationtests.NewCoreumTestingContext(t)
> 	const gracePeriod = 15 * time.Second
> ```

same here


<!-- Sent from Reviewable.io -->

2023-06-28 10:36 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 27 of 32 files reviewed, 7 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/testdata/wasm/ft/Cargo.toml` line 36 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ-oIvh8rc4njCpU_Wp:-NZ0ZsdsEmqPQG1D7yuL:bv4teq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c322436425cfa54e73925fd624539feeff34597/integration-tests/modules/testdata/wasm/ft/Cargo.toml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but leave the fixme anyway in case "probably" won't happen
</blockquote></details>

already upgraded to 0.1.3 and modified cargo. 
___
*[`integration-tests/upgrade/ft.go` line 518 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0K-ihD1fBJ86CIPwh:-NZ0ZvuEEUNmG5T1Cf8R:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd4aa1876144d77ce794874681301ba4f6f8f6ca/integration-tests/upgrade/ft.go#L518)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this constant might be moved to the top of the file (to define a global one for entire code)
</blockquote></details>

done
___
*[`integration-tests/upgrade/ft.go` line 668 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0K7Yj5NK8vn5CAHkC:-NZ0ZwUQ5rFu5lOA8jW4:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd4aa1876144d77ce794874681301ba4f6f8f6ca/integration-tests/upgrade/ft.go#L668)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done
___
*[`integration-tests/upgrade/ft.go` line 774 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0KFc5DsK7et49zpEm:-NZ0Zx4f8gnsKsZ666HE:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd4aa1876144d77ce794874681301ba4f6f8f6ca/integration-tests/upgrade/ft.go#L774)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-06-28 11:39 UTC, wojtek-coreum requested changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 4 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 28 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ0nEfF34NCY91ld8I6:-NZ0nEfF34NCY91ld8I7:b-eyyf6e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/116cecaa5e201771e0f1df6ee26b16c4e5bd4351/integration-tests/upgrade/ft.go#L28)):*
> ```Go
> 
> const (
> 	// tx.
> ```

this comment might be removed


<!-- Sent from Reviewable.io -->

2023-06-28 11:43 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-28 13:28 UTC, miladz68 reviewed
> Reviewed 3 of 4 files at r7, 4 of 5 files at r8, 3 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 31 of 32 files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-28 13:50 UTC, miladz68 approved these changes
> Reviewed 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-28 13:55 UTC, dzmitryhil submitted a review, later dismissed
> Reviewed 8 of 27 files at r1, 10 of 12 files at r2, 1 of 1 files at r3, 2 of 5 files at r5, 3 of 4 files at r7, 4 of 5 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-28 15:00 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-29 06:23 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 28 of 32 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1177 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4oMOb5C-3MUP9RXQE:-NZ4oMOb5C-3MUP9RXQF:b-9b8g6f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/modules/wasm_test.go#L1177)):*
> ```Go
> 		data[i] = uint8(i)
> 	}
> 	encodedData := base64.StdEncoding.EncodeToString(data)
> ```

You don't need the for. Why you do the `make([]byte, 256)` it will fill the bytes slice with the default byte values. 


<!-- Sent from Reviewable.io -->

2023-06-29 06:30 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: 28 of 32 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-29 06:52 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 170 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4v32j1izjiWVPguQb:-NZ4v32j1izjiWVPguQc:b37o5x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/upgrade/ft.go#L170)):*
> ```Go
> 		},
> 		BurnRate:           burnRate.String(),
> 		SendCommissionRate: sendCommissionRate.String(),
> ```

I don't think it should be needed. We have many unit and integration tests where those values are skipped and they work.
___
*[`integration-tests/upgrade/ft.go` line 212 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4vBzOBcWn1Sj0gnQ6:-NZ4vBzOBcWn1Sj0gnQ7:b-7ropln) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/upgrade/ft.go#L212)):*
> ```Go
> 		InitialAmount:      issuanceAmount.String(),
> 		Description:        "my wasm fungible token",
> 		BurnRate:           burnRate.String(),
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-06-29 08:05 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 170 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4v32j1izjiWVPguQb:-NZ5Aa4Q7bZ8GyLuAzLo:bhd1eg7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/upgrade/ft.go#L170)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't think it should be needed. We have many unit and integration tests where those values are skipped and they work.
</blockquote></details>

If you don't add them you get an error, they are not optional.
___
*[`integration-tests/upgrade/ft.go` line 212 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4vBzOBcWn1Sj0gnQ6:-NZ5AzHOE8Z4QPgniUIr:bnj7hl0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/upgrade/ft.go#L212)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

same as above


<!-- Sent from Reviewable.io -->

2023-06-29 08:11 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1177 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4oMOb5C-3MUP9RXQE:-NZ5CBxlB7MVjkKiwnGq:b-dw8k1c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/modules/wasm_test.go#L1177)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need the for. Why you do the `make([]byte, 256)` it will fill the bytes slice with the default byte values. 
</blockquote></details>

without the for it provides the same byte value for each element in the vector (0x0). What I want is all the possible byte values.


<!-- Sent from Reviewable.io -->

2023-06-29 08:17 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 170 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4v32j1izjiWVPguQb:-NZ5DYpE0Dwz-KF8Z1h-:b-iirll4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/upgrade/ft.go#L170)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

If you don't add them you get an error, they are not optional.
</blockquote></details>

The error comes from the wasm handler. It throws an ABCI error.


<!-- Sent from Reviewable.io -->

2023-06-29 08:45 UTC, miladz68 approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-29 09:08 UTC, wojtek-coreum approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 170 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/536#-NZ4v32j1izjiWVPguQb:-NZ5PA8a77onSW04qxrm:b-pfd6j2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/072a83cd5d07ecd8a7ddf538a9bb5d4d2202d0b3/integration-tests/upgrade/ft.go#L170)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

The error comes from the wasm handler. It throws an ABCI error.
</blockquote></details>

ah I see, because we pass that message to smart contract to be executed from there. Okay.


<!-- Sent from Reviewable.io -->

2023-06-29 09:08 UTC, wojtek-coreum approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/536)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-29 09:11 UTC, merged