added migrations for NFT data created by smart contracts
CoreumFoundation/coreum pull request #553
Opened 2023-07-03 16:03 UTC by miladz68

2023-07-04 10:38 UTC, wojtek-coreum reviewed
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-05 11:04 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: 5 of 9 files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/testdata/wasm/nft.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_aWIG6IwI4no8-irc:-NZ_aWIG6IwI4no8-ird:b29jjh1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/modules/testdata/wasm/nft.go#L1)):*
> ```Go
> package modules
> ```

Update the master please there are changes in that folder.

@wojtek-coreum @ysv Probably we should update that part in the future and move all contract clients to the contrast folder. 
___
*[`integration-tests/upgrade/nft.go` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_a7b62wUirk_yqDlw:-NZ_a7b62wUirk_yqDlx:b-zfxmi1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L2)):*
> ```Go
> //go:build integrationtests
> ```

BTW @wojtek-coreum @miladz68 Why that file is not `_test.go` so for the ft ?
___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-NZ_hH1a85VmbbCjwa2I:bcrpdoc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
> ```Go
> 
> 	// we need to double encode to simulate the situation when the handler did not work correctly.
> 	encodedBytesString := base64.StdEncoding.EncodeToString(data)
> ```

Didn't get that part, why do we need to Encode if the 1.0.0 will do it?
When you issue from the contract the contract should save the encoded version for the v 1.0.0 right?
___
*[`x/asset/nft/module.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_f-NE2soBRW8NwGSI:-NZ_f-NE2soBRW8NwGSJ:bncwrmj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/module.go#L109)):*
> ```Go
> 	cdc codec.Codec,
> 	keeper keeper.Keeper,
> 	nftKeeper nftkeeper.Keeper,
> ```

Probably you could return the nft keeper from the asset nft keeper for the migration and don't update the module part?
But if you will use the wasm keeper for the address then you can keep it as is since the module will be updated anyways. 
___
*[`x/asset/nft/keeper/migrations.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_bGzm0XiAm3vrQrBW:-NZ_bGznBZ8qJOBEJRyv:b-g136dl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/keeper/migrations.go#L13)):*
> ```Go
> type Migrator struct {
> 	keeper    Keeper
> 	nftKeeper nftkeeper.Keeper
> ```

Update to the interface.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dOmt-80vXIo8ne3d:-NZ_dOmt-80vXIo8ne3e:bqwk1b8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L16)):*
> ```Go
> )
> 
> func isSmartContractAddress(address sdk.AccAddress) bool {
> ```

I would check the keeper instead, I wouldn't trust the length.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dk2e8gBjdNxwRrWF:-NZ_dk2e8gBjdNxwRrWG:b5rzq6t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L38)):*
> ```Go
> 
> 		if class.Data != nil {
> 			class.Data, err = convertAnyToDecodedAny(class.GetData())
> ```

Why do you use the `class.GetData()` here but `class.Data` in the if?
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dzbI5uwnc7wzIZ0N:-NZ_dzbI5uwnc7wzIZ0O:bj8trng) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L68)):*
> ```Go
> func convertAnyToDecodedAny(input *codectypes.Any) (*codectypes.Any, error) {
> 	var oldDataByes types.DataBytes
> 	err := proto.Unmarshal(input.GetValue(), &oldDataByes)
> ```

What if the type is not `var oldDataByes types.DataBytes` ? Is it possible to get the type from input to compare and skip if it is different?
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fnTi4AragleLY83d:-NZ_fnTi4AragleLY83e:b-hijzc8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L28)):*
> ```Go
> 	requireT := require.New(t)
> 	simapp.FlagEnabledValue = true
> 	_, db, dir, logger, _, err := simapp.SetupSimulation("goleveldb-app-sim", "Simulation")
> ```

Whyd do you use the cosmos simapp why not our simapp (same) ?
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fxCr8Hpa4dJTiPTd:-NZ_fxCr8Hpa4dJTiPTe:b-8ygne4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L31)):*
> ```Go
> 	requireT.NoError(err, "simulation setup failed")
> 
> 	t.Cleanup(func() {
> ```

You don't need it if you use our simapp.
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_g3T3DK5lU35D2Mie:-NZ_g3T3DK5lU35D2Mif:b-6xij8d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L38)):*
> ```Go
> 
> 	encoding := config.NewEncodingConfig(app.ModuleBasics)
> 	network, err := config.NetworkConfigByChainID(constant.ChainIDDev)
> ```

You don't need it if you use our simapp (same of other lines).
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_gOCOCedPD6OmlB32:-NZ_gOCP8YXnq_pqxDsw:b-a4g1f2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L74)):*
> ```Go
> 			nftID:  "nft1",
> 			assertion: func(t *testing.T, class nft.Class, nft nft.NFT, data []byte) {
> 				requireT := require.New(t)
> ```

You don't need to create a new instance for each test so the `t *testing.T ` can be remove as well from the params.


<!-- Sent from Reviewable.io -->

2023-07-05 12:03 UTC, wojtek-coreum requested changes
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/nft.go` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_a7b62wUirk_yqDlw:-NZ_qeAa41oPup8l7cS0:b-nwx4tu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

BTW @wojtek-coreum @miladz68 Why that file is not `_test.go` so for the ft ?
</blockquote></details>

no special reason, it might be renamed
___
*[`integration-tests/upgrade/nft.go` line 341 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_u78c5QdSwx19Ph5U:-NZ_u78c5QdSwx19Ph5V:b-z77err) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L341)):*
> ```Go
> //nolint:funlen // this is test case and breaking it up will reduce readability
> func (n *nftWasmDataTest) Before(t *testing.T) {
> 	t.Parallel()
> ```

Don't do this. Before and After are not called in separate `t` so you are changing the upper `t` here.
___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-NZ_uRcC8KqIJ0t-wpXJ:bq7hyqq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get that part, why do we need to Encode if the 1.0.0 will do it?
When you issue from the contract the contract should save the encoded version for the v 1.0.0 right?
</blockquote></details>

I also don't get it
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_rRLlCLfjVanz9A8G:-NZ_rRLlCLfjVanz9A8H:byodte6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L13)):*
> ```Go
> 
> 	"github.com/CoreumFoundation/coreum/x/asset/nft/types"
> 	"github.com/CoreumFoundation/coreum/x/nft/keeper"
> ```

please import it as `nftkeeper` because it comes from different module
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dOmt-80vXIo8ne3d:-NZ_qqqL76iKlpVcmULV:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would check the keeper instead, I wouldn't trust the length.
</blockquote></details>

agree
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_rFVQ-JHgGezOBlC4:-NZ_rFVQ-JHgGezOBlC5:b-auxkx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L20)):*
> ```Go
> }
> 
> // MigrateWasmCreatedNFTData migrates all the NFT data created by smart contracts.
> ```

please describe what you are fixing as it is not so obvious case
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_tJLM9d_96nlE9CRM:-NZ_srIj1-5l5nF0TxYA:b6cqbdj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L48)):*
> ```Go
> 		}
> 
> 		nfts := nftKeeper.GetNFTsOfClass(ctx, cd.ID)
> ```

There might be tons of nfts, no? What about using sth similar to `IterateAllClassDefinitions`, so not all of them are loaded into memory at the same time?
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dzbI5uwnc7wzIZ0N:-NZ_sQsm4INq7QYZc3t2:b4r07oe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What if the type is not `var oldDataByes types.DataBytes` ? Is it possible to get the type from input to compare and skip if it is different?
</blockquote></details>

Actually in this case it can't be because it is the only format wasm contracts may use
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fnTi4AragleLY83d:-NZ_td9o-ExjLb2YEWQk:b-jqqx81) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Whyd do you use the cosmos simapp why not our simapp (same) ?
</blockquote></details>

I would ask different question: Why do you use simapp at all? Woudl be simpler to take keepers, put invalid data there, call migration & check that after that state is fixed.


<!-- Sent from Reviewable.io -->

2023-07-05 12:57 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-06 12:21 UTC, dzmitryhil requested changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-06 13:04 UTC, wojtek-coreum reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-07 06:17 UTC, wojtek-coreum approved these changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-07 13:07 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/nft/module.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_f-NE2soBRW8NwGSI:-NZkSNsbEswg4eLDGhx_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/module.go#L109)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Probably you could return the nft keeper from the asset nft keeper for the migration and don't update the module part?
But if you will use the wasm keeper for the address then you can keep it as is since the module will be updated anyways. 
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/migrations.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_bGzm0XiAm3vrQrBW:-NZfJbOXALXnabuFyHeZ:b-fsewi0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/keeper/migrations.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update to the interface.
</blockquote></details>

I guess the best approach will be to define the interface on the migration package and expect an interface there, instead of here. 
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_rRLlCLfjVanz9A8G:-NZed4KD8L6iZxqovWs-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please import it as `nftkeeper` because it comes from different module
</blockquote></details>

Done.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dOmt-80vXIo8ne3d:-NZfJnXR2i9tgN4bQttL:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_rFVQ-JHgGezOBlC4:-NZedePC57C0Xf-nGU2P:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please describe what you are fixing as it is not so obvious case
</blockquote></details>

Done.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dk2e8gBjdNxwRrWF:-NZedmz561tZnz2X5qc_:bt2vr1b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you use the `class.GetData()` here but `class.Data` in the if?
</blockquote></details>

Fixed.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_tJLM9d_96nlE9CRM:-NZeMzL4--5BBRdGAJYL:bzhvrcu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There might be tons of nfts, no? What about using sth similar to `IterateAllClassDefinitions`, so not all of them are loaded into memory at the same time?
</blockquote></details>

we need to load only those NFTs the issuer of which is the smart contract, so we need to get the classes for each one as well. this way it iterates less data, as opposed to getting every NFT.
___
*[`x/asset/nft/legacy/v1/wasm_data.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_dzbI5uwnc7wzIZ0N:-NZeNKCd6joUJ60BU-UM:b-tcrold) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Actually in this case it can't be because it is the only format wasm contracts may use
</blockquote></details>

Agreed with wojtek. that is the only valid format at this point. 
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fnTi4AragleLY83d:-NZkSQYuA49pHLz2_A41:b-m751wt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would ask different question: Why do you use simapp at all? Woudl be simpler to take keepers, put invalid data there, call migration & check that after that state is fixed.
</blockquote></details>

Refactored not to use the custom simapp
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fxCr8Hpa4dJTiPTd:-NZkSVSI8wdmgU9Mu6Jb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need it if you use our simapp.
</blockquote></details>

Done.
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_g3T3DK5lU35D2Mie:-NZkSW1B34JXSxS2LVjW:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need it if you use our simapp (same of other lines).
</blockquote></details>

Done.
___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_gOCOCedPD6OmlB32:-NZeNZBdD82CGVrWvDSJ:bkml13z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L74)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need to create a new instance for each test so the `t *testing.T ` can be remove as well from the params.
</blockquote></details>

using it for each instance produces better failure logs, and you will know exactly in which test the failure has happend.
___
*[`integration-tests/modules/testdata/wasm/nft.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_aWIG6IwI4no8-irc:-NZeUMaTEcVqpUH0_H5m:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/modules/testdata/wasm/nft.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update the master please there are changes in that folder.

@wojtek-coreum @ysv Probably we should update that part in the future and move all contract clients to the contrast folder. 
</blockquote></details>

Done.
___
*[`integration-tests/upgrade/nft.go` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_a7b62wUirk_yqDlw:-NZeVDfl6QZVoP7wtRCZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L2)):*
<details><summary [...]

2023-07-10 07:15 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/nft.go` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_a7b62wUirk_yqDlw:-NZycB_w8FytPgMcn3l7:b-232ce5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Update the `ft.go` as well, please. 
___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-NZyc_-8Dvh6bhldO_Jq:b-kfvznv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Removed the comment, left over from the old implementation. 
</blockquote></details>

But The issue is not in the comment. From what I understand if you save the "data"  without encoding from wasm contract now (v 1.0.0) that data will be uncodded to `base64`, right @keyleu ? So you don't need to encode it here.


<!-- Sent from Reviewable.io -->

2023-07-10 07:54 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-10 10:30 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @silverspase, and @ysv)

___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fnTi4AragleLY83d:-NZzKgTn4vLLxr70tAPV:bxeptsy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but why do we need simapp at all?
</blockquote></details>

we need simapp to get the initialized keepers and work with them. you also use the simapp to get the keepers ft tests. it is simpler to get the keepers from the simapp than to initialize them yourself. 
___
*[`integration-tests/upgrade/nft.go` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_a7b62wUirk_yqDlw:-NZzLDae7_W4aSOe4IvV:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update the `ft.go` as well, please. 
</blockquote></details>

Done
___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-NZzKHeNAj4x5A6i307J:bax22ct) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But The issue is not in the comment. From what I understand if you save the "data"  without encoding from wasm contract now (v 1.0.0) that data will be uncodded to `base64`, right @keyleu ? So you don't need to encode it here.
</blockquote></details>

there is still one layer of decoding done the smart contract entry point. so I need to decode it here.


<!-- Sent from Reviewable.io -->

2023-07-10 10:55 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @keyleu, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-NZzRLRE3m33LMthtHSw:bkc60pi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

there is still one layer of decoding done the smart contract entry point. so I need to decode it here.
</blockquote></details>

Let's discuss it, today. 


<!-- Sent from Reviewable.io -->

2023-07-10 10:58 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @silverspase, and @ysv)

___
*[`x/asset/nft/legacy/v1/wasm_data_test.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_fnTi4AragleLY83d:-NZzRqbWBxUkdL4-s7uo:b-y6q23d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/x/asset/nft/legacy/v1/wasm_data_test.go#L28)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need simapp to get the initialized keepers and work with them. you also use the simapp to get the keepers ft tests. it is simpler to get the keepers from the simapp than to initialize them yourself. 
</blockquote></details>

I see, ok


<!-- Sent from Reviewable.io -->

2023-07-10 11:31 UTC, keyleu reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-NZzYzJo5PcXZJ7KZzns:bdewbjz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss it, today. 
</blockquote></details>

Yes, Let's discuss today. It's a bit confusing. Basically the contract entry point reads a Binary, so it's expecting a Base64 encoded array of data.

Then when we issue / query, it encodes/decode data, that's why the handler does the encoding/decoding.

This encoding is just for the contract to read the information correctly. If we wanted to skip this step we would define the entry point of the contract as a Vec[u8] instead of Binary.


<!-- Sent from Reviewable.io -->

2023-07-11 07:15 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-11 07:47 UTC, wojtek-coreum submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-11 08:38 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

___
*[`integration-tests/upgrade/nft.go` line 366 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/553#-NZ_hH1a85VmbbCjwa2H:-N_35MxkAIwSjGpZPRGH:bxoof57) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08031250d116999295abaed4ef4674d733ed0f07/integration-tests/upgrade/nft.go#L366)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Yes, Let's discuss today. It's a bit confusing. Basically the contract entry point reads a Binary, so it's expecting a Base64 encoded array of data.

Then when we issue / query, it encodes/decode data, that's why the handler does the encoding/decoding.

This encoding is just for the contract to read the information correctly. If we wanted to skip this step we would define the entry point of the contract as a Vec[u8] instead of Binary.
</blockquote></details>

Discussed in the daily and decided to keep it. 


<!-- Sent from Reviewable.io -->

2023-07-11 10:58 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-12 07:46 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-07-12 07:46 UTC, merged