DEX documentation - high-level concepts
CoreumFoundation/coreum pull request #588
Opened 2023-07-31 10:50 UTC by wojtek-coreum

2023-07-31 12:58 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nag0k9P5dKSlXpW7la-:-Nag0k9P5dKSlXpW7la0:bi4x9ji) (no related file):*
Haven't finished review fully
Posting part 1

___
___
*[`x/dex/spec/README.md` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nafgw4VDMm0ZWTtahee:-Nafgw4VDMm0ZWTtahef:b-1w5pb5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L1)):*
> ```Markdown
> # DEX
> ```

mark this file as WIP ?
___
*[`x/dex/spec/README.md` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafcyRKB-mMTOiAWAle:-NafcyRKB-mMTOiAWAlf:byl7aky) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L9)):*
> ```Markdown
> Coreum DEX is based on order books. Each trading pair defines its order book - which is defined by two sequences of orders, one grouping buy orders, the other one grouping sell orders.
> 
> Whenever the lowest price offered by any sell order is lower than the highest price offered by any buy order, the match exists and tokens might be exchanged.
> ```

lower than or equal
___
*[`x/dex/spec/README.md` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nafd4-H-H0t0Izv4Q_f:-Nafd4-H-H0t0Izv4Q_g:bdeh48p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L9)):*
> ```Markdown
> Coreum DEX is based on order books. Each trading pair defines its order book - which is defined by two sequences of orders, one grouping buy orders, the other one grouping sell orders.
> 
> Whenever the lowest price offered by any sell order is lower than the highest price offered by any buy order, the match exists and tokens might be exchanged.
> ```

in the end add "and vice versa" ?
___
*[`x/dex/spec/README.md` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafdMkd-IZJKNRGKzps:-NafdMkd-IZJKNRGKzpt:b9br7nc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L11)):*
> ```Markdown
> Whenever the lowest price offered by any sell order is lower than the highest price offered by any buy order, the match exists and tokens might be exchanged.
> 
> Trading pair (and its order book) is described by two tokens: base token and quote token. The quote token is used to define the price of the base token.
> ```

`uaaa/ubbb` vs `ubbb/uaaa` are these 2 different pairs or the same one ?
 since we want to trade anything to anything 

I don't insist on addressing this fully right now but at least todo is needed
___
*[`x/dex/spec/README.md` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nafdthd27Bs0iYixX0v:-Nafdthd27Bs0iYixX0w:b-mrz5vm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L27)):*
> ```Markdown
> ### Order book representation
> 
> The commonly used representation of an order book is the stack of two lists sorted by order price, the upper one containing sell orders and the lower one containing buy orders.
> ```

`sorted by order price`

should also be sorted by creation time/block ?
___
*[`x/dex/spec/README.md` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafeQZy1cPhMph12a-m:-NafeQZy1cPhMph12a-n:b-x166bz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L31)):*
> ```Markdown
> Example: This is the hypothetical `uaaa/ubbb` order book:
> 
> | Amount `[uaaa]` | Sell price `[ubbb/uaaa]` | Buy price `[ubbb/uaaa]` | Explanation |                                                                                
> ```

have we fully decided to define order using price & amount to buy/sell ?

Because I still consider approach when we define it by amount_to_spend & amount_to_receive pair
___
*[`x/dex/spec/README.md` line 78 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NaffJjBARzBHNXPej9t:-NaffJjBARzBHNXPej9u:btbv4p5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L78)):*
> ```Markdown
> 
> Arranging orders this way, makes it possible to verify easily if match between orders is possible.
> If the top record on the sell side has the price lower than or equal to the price in the top record on buy side it means
> ```

I partially disagree with this state
I match should happen such orders are not added to order tables


<!-- Sent from Reviewable.io -->

2023-07-31 14:54 UTC, ysv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nag0k9P5dKSlXpW7la-:-NagQuvE--nXMhIWPeIJ:b-w34u8s) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Haven't finished review fully
Posting part 1
</blockquote></details>

finalized

Decent start :thumbsup: 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQvf_28lu-IxApt8S:-NagQvf_28lu-IxApt8T:b7kud5j) (no related file):*
There are a few places where Reza's input is needed
But I suggest we just mark them with smth like TBD (to be defined) and merge it 

Later we can resolve them in batches

___
___
*[`x/dex/spec/README.md` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagNuQy3-AJPi5J_mm5:-NagNuQz48oRmFA_cbbS:b-mjitqg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L97)):*
> ```Markdown
> The same way, buy order offering higher price is placed earlier in the buying queue than existing orders offering lower price.
> 
> It is important to note, that in case order is updated (amount or price are changed), its time priority is recalculated.
> ```

nit: I'm not sure we are planning to implement updating of orders at least on the first iteration. Do you think we should ?

But I'm ok to keep this descr here
___
*[`x/dex/spec/README.md` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQmSc0GLrVI6e6UOS:-NagQmSc0GLrVI6e6UOT:b-l94zye) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L103)):*
> ```Markdown
> with the same price.
> 
> ## Order matching
> ```

this section covers limit orders
But what about market orders

Again I suggest to leave it in todo
___
*[`x/dex/spec/README.md` line 122 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagOQemDC246Qu0rsze:-NagOQemDC246Qu0rszf:b94wneu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L122)):*
> ```Markdown
> | 300                  | 15                       | 50                  |  10                     |
> 
> Because sell price is higher than the buy price, nothing can be done. New buy order comes:
> ```

Just I'm not sure it is correct visual representation to add such orders to orderbook
At least I vizualize it differently & I think it is worth clarifying before implementation

lets discuss
___
*[`x/dex/spec/README.md` line 435 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQN8P8khWEtEv6f0p:-NagQN8Q0hN7lxkd_0do:b2b7q2a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L435)):*
> ```Markdown
> In case of sell orders we must lock:
> - amount of base tokens specified in the order
> - all the fees (e.g. burn rate, commission rate) related to the base token
> ```

needs to be confirmed with Reza
I'm not sure the way it is supposed to work
___
*[`x/dex/spec/README.md` line 448 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQb6z2Ig82ETqfNR3:-NagQb6z2Ig82ETqfNR4:bb6731) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L448)):*
> ```Markdown
> To limit the amount of data stored in the order books, orders should be rejected under some circumstances:
> - order should be rejected immediately, when placed, if the offered price is too far from the currently traded one
> - each order should have a maximum lifetime, to prune it from the order book if it is not executed for some time
> ```

not sure about this also


<!-- Sent from Reviewable.io -->

2023-08-01 08:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 122 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagOQemDC246Qu0rsze:-NakCTmqEo6RHWn-N-ut:b1xim0j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L122)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please propose your visualization, otherwise this comment is not helpful (according to our discussion related to quality of comments in PRs :-) ). I like this visualization because:
- at the end of the day, this is exactly what we need to store - two sorted lists
- it's definitely the optimal solution - algorithm reads and compares only two records at a time, it's not possible to do anything better
- it's similar to other well known algorithms like quick sort

Maybe the confusion is that those two tables are written here in the form of a single one, but markdown does not allow to put two tables next to each other.
</blockquote></details>

Maybe you are thinking about the visualization where sell orders go from the top in the first column and buy orders go from the bottom in the second column, and if they overlap reduction might be done. I considered it but after thinking about decided that it's more complicated to describe the mechanics using this model.

Here it's simple, you just say: compare values in the first row


<!-- Sent from Reviewable.io -->

2023-08-01 09:08 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQvf_28lu-IxApt8S:-NakLV03AkordKvt2cGK:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

There are a few places where Reza's input is needed
But I suggest we just mark them with smth like TBD (to be defined) and merge it 

Later we can resolve them in batches

</blockquote></details>

Done.

___
___
*[`x/dex/spec/README.md` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nafgw4VDMm0ZWTtahee:-NakITIG5PkSJhpeXU6b:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

mark this file as WIP ?
</blockquote></details>

Done.
___
*[`x/dex/spec/README.md` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafcyRKB-mMTOiAWAle:-NakIY8V27AdP03g_0_v:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L9)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lower than or equal
</blockquote></details>

Done.
___
*[`x/dex/spec/README.md` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQmSc0GLrVI6e6UOS:-NakLQc3AVK2efal4f0t:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L103)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Market order is a simple extension of the limit order. In limit order there are two conditions for stopping the processing:
- price
- amount

For market order there is only one condition: amount. I will add it to the document.
</blockquote></details>

Done.
___
*[`x/dex/spec/README.md` line 448 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQb6z2Ig82ETqfNR3:-NakLpgg3VwDfP8PtXDr:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L448)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not sure about this also
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 13:10 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @keyleu, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafdMkd-IZJKNRGKzps:-Nal8ucr1h7epmSzqlWG:bhgigl7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The 2 books are here to simplify the fetching since we will fetch from the xtop always. 
</blockquote></details>

I don't get this discussion. If people want to trade on both order books then why should we care? There is a reason why e.g. on forex there is EURUSD pair but there is no USDEUR. The reason is mathematical: considering that there are no fees, if EURUSD doubles, then USDEUR drops by 50%. It means that if market is volatile I could "buy" same amount on both pairs and always win. It's possible because most of the forex brokers are market makers which means transactions done there are purely virtual. They protect against it by:
- trading one pair only
- introducing fees

But we are not market makers. On our DEX orders are real and these are people who decide if the particular pair should exist or not. If, for any stupid reason, people trade both using BTCETH and ETHBTC then it's not our business to deny them.
___
*[`x/dex/spec/README.md` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafeQZy1cPhMph12a-m:-NalAPL3DNpJgLwy0Dor:b7u5243) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L31)):*
> You need common denominator only for 2 elements which are compared at specific point of time

Exactly, and how do I know which 2 elements should be processed at specific point of time, without reading all of them and updating nominators to know which one is highest/lowest?
___
*[`x/dex/spec/README.md` line 78 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NaffJjBARzBHNXPej9t:-NalC0K0EyG-Zjdu4kJ6:b-hmohze) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L78)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but it effect implementation

Such orders never become part of orderbook
</blockquote></details>

No, it doesn't affect implementation. It's the mental model describing how the idea works. 
___
*[`x/dex/spec/README.md` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQmSc0GLrVI6e6UOS:-NalCJm5DQNJ8ykX3Y_P:bxytes9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L103)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Market order is a simple extension of the limit order

Not really
The problem is that we don't know the amount which should be locked on user acc. 
E.g in limit order amount to be locked is equal to price*buy_amount. But here we are not able to estimate it fully.
The only limitation is full balance of users. Should we lock it fully ? I'm not sure
</blockquote></details>

No, we know what to lock. If user wants to buy the base token, he must put some quote amount in the order (and we lock it).
If user wants to sell the base token he must put the base amount in the order (and we lock it).
___
*[`x/dex/spec/README.md` line 53 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal6yzD2JMqBabX0k4T:-NalAudkCUwFdwy-0sVs:b-lxnroe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L53)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The order key should also include the timestamp to prioritize the orders with the same price but different `add time`.
</blockquote></details>

This is described later. As already commented somewhere else -> I'm progressing from simple ideas to complex ones over the doc
___
*[`x/dex/spec/README.md` line 54 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal9KQWEGIRkf8UiJRh:-NalBvnx2oYn_hRb1lYs:babuvvc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

BTW what about the order books sequence? How do we order them?
</blockquote></details>

We don't need it


<!-- Sent from Reviewable.io -->

2023-08-03 08:53 UTC, miladz68 reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @keyleu, @vertex451, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-08-03 12:02 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nauu7zc-E6hSNOqCn0X:-Nauu7zc-E6hSNOqCn0Y:bfgzatn) (no related file):*
Could you please double check that all features mentioned in white-paper are addressed or TODO added or discarded as team's decission

E.g right now I don't see synthetic orderbook mentioned but it is very important IMO

___
___
*[`x/dex/spec/README.md` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafdMkd-IZJKNRGKzps:-NautHou2SXmJ9RghmBJ:b-b1o0kv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't get this discussion. If people want to trade on both order books then why should we care? There is a reason why e.g. on forex there is EURUSD pair but there is no USDEUR. The reason is mathematical: considering that there are no fees, if EURUSD doubles, then USDEUR drops by 50%. It means that if market is volatile I could "buy" same amount on both pairs and always win. It's possible because most of the forex brokers are market makers which means transactions done there are purely virtual. They protect against it by:
- trading one pair only
- introducing fees

But we are not market makers. On our DEX orders are real and these are people who decide if the particular pair should exist or not. If, for any stupid reason, people trade both using BTCETH and ETHBTC then it's not our business to deny them.
</blockquote></details>

On the call we decided to not have mirror pairs

So we should get rid of buy/sell, base/quote terms everywhere IMO
___
*[`x/dex/spec/README.md` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafeQZy1cPhMph12a-m:-NaurQ5u1KOT_XMpoyHD:bwihoxq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> You need common denominator only for 2 elements which are compared at specific point of time

Exactly, and how do I know which 2 elements should be processed at specific point of time, without reading all of them and updating nominators to know which one is highest/lowest?
</blockquote></details>

I still don't see any issues with it
Lets discuss
___
*[`x/dex/spec/README.md` line 78 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NaffJjBARzBHNXPej9t:-NauscUP5ukHlYGC27j1:b7g6srh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L78)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, it doesn't affect implementation. It's the mental model describing how the idea works. 
</blockquote></details>

Lets discuss
___
*[`x/dex/spec/README.md` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQmSc0GLrVI6e6UOS:-Nausji87OzYEt4xrKL3:b-5ex5fm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L103)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, we know what to lock. If user wants to buy the base token, he must put some quote amount in the order (and we lock it).
If user wants to sell the base token he must put the base amount in the order (and we lock it).
</blockquote></details>

do you mean that user should specify amount he wants to spend not amount he wants to get ?
___
*[`x/dex/spec/README.md` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal5dG1718k2NjHbqAE:-NaurYwu3VqDnxB5PcS-:bxw3giq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure that `Sell price` and `Buy price` are the correct names, probably `Ask Amount`, and `Bid Amount` and Direction or something like that.
</blockquote></details>


Since we agree to not have mirror pairs we should completely avoid buy/sell terms IMO
Also direction is not needed. 
To define any order you just need 2 properties:
- amount you pay
- amount you want to get

Direction is not needed
___
*[`x/dex/spec/README.md` line 53 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal6yzD2JMqBabX0k4T:-NaurzBuDFw3lb41pymL:bs8vvjy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L53)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is described later. As already commented somewhere else -> I'm progressing from simple ideas to complex ones over the doc
</blockquote></details>

since both me & Dzmitry had this comment I think it is reasonable to mention time here.
You don't need to cover time logic fully here. Maybe just referencing ordering logic section defined onwards makes sense
___
*[`x/dex/spec/README.md` line 54 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal9KQWEGIRkf8UiJRh:-NausWUH6xjzSYSD1H4-:b-gbpsqs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L54)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We don't need it
</blockquote></details>

I didn't get the question 
Do you mean order of orderbooks ?
___
*[`x/dex/spec/README.md` line 103 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal7gSp51ZLwHHnKTDa:-Naut2mp2sgTPgKdJa7-:b-jc2ar6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L103)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we should add ad confirm the limits for `Order matching` on the design phase since from what I see now we need at least 2. 
* `Max orders per block` - how many orders we execute max in the end blocker
* `Max full blocks` -  how many blocks in a row we allow to reach `Max orders per block` once we reach that threshold, we don't accept new orders.

That's important since it will influence the throughput, so might be critical for the entire design. 
</blockquote></details>

Maybe, but it depends on benchmark results I would say
And to get them we need the implementation


<!-- Sent from Reviewable.io -->

2023-08-03 12:38 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nauu7zc-E6hSNOqCn0X:-NavMwErCgmjCYVxU3HS:b4eaxmz) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Could you please double check that all features mentioned in white-paper are addressed or TODO added or discarded as team's decission

E.g right now I don't see synthetic orderbook mentioned but it is very important IMO
</blockquote></details>

The only missed thing is indirect order execution. Synthetic orderbook is not mentioned in the whitepaper. I will add it if you explain what it is.

___
___
*[`x/dex/spec/README.md` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafdMkd-IZJKNRGKzps:-NavN9-V2wF1jC0D_GXS:bi2zdeq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

On the call we decided to not have mirror pairs

So we should get rid of buy/sell, base/quote terms everywhere IMO

</blockquote></details>

IMO they should stay here as this section explains how the order book works, and this is how it works. Later on I explain how orders are stored and processed without the concept of order book but leaving the ability of generating them in presentation layers.
___
*[`x/dex/spec/README.md` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NafeQZy1cPhMph12a-m:-NavNS8I61PIiNCKUCIB:b-pdz9mj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I still don't see any issues with it
Lets discuss
</blockquote></details>

Then, present the algorithm please
___
*[`x/dex/spec/README.md` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NagQmSc0GLrVI6e6UOS:-NavO0YRBmrn0kYGwpFt:bj6cley) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f6ca80dbfdaaec21f44eebcadf6669597c5f6e14/x/dex/spec/README.md#L103)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you mean that user should specify amount he wants to spend not amount he wants to get ?
</blockquote></details>

Yes, because otherwise locking is not possible. You don't say how many bananas you want to buy, you say how much you want to spend on bananas, and then you get as many bananas as possible for that amount. I know that it works in reversed order on traditional exchanges.
___
*[`x/dex/spec/README.md` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal5dG1718k2NjHbqAE:-NavNXvM15P8WspU4CCj:b-eavnof) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>


Since we agree to not have mirror pairs we should completely avoid buy/sell terms IMO
Also direction is not needed. 
To define any order you just need 2 properties:
- amount you pay
- amount you want to get

Direction is not needed
</blockquote></details>

Discussing in another thread already
___
*[`x/dex/spec/README.md` line 103 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal7gSp51ZLwHHnKTDa:-NavOsU7AgtyAeavzygu:bfr5k4j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L103)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Maybe, but it depends on benchmark results I would say
And to get them we need the implementation
</blockquote></details>

I don't think we should define them now. They might be added at any time. Algorithms described in the docs does not depend on this decision.


<!-- Sent from Reviewable.io -->

2023-08-03 12:51 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 53 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal6yzD2JMqBabX0k4T:-NavRvrf4NRPT-umv-PA:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L53)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

since both me & Dzmitry had this comment I think it is reasonable to mention time here.
You don't need to cover time logic fully here. Maybe just referencing ordering logic section defined onwards makes sense
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-04 10:34 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 702 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NavOgD-0U6IjlwbcPjy:-Nb-5RwX4Yb1LWOregI9:bb7s07l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/927184d88cb19602f220148a5cc676334067c946/x/dex/spec/README.md#L702)):*
> So you mean that instead of `uaaa/ubbb` we will use uint and store mapping separately  
> And once order is created we check if index exists inside mapping and add/increment it if needed. Do I understand it correctl

yes


> Will we create these indexes separately for mirror pairs ?  
> Is possible that `uaaa/ubbb` = 1 & `ubbb/uaaa` = 100 ?
> Or you meant that each denom has index ? `uaaa` = 1 & `ubbb` = 2 ?

> Or you meant that each denom has index ? `uaaa` = 1 & `ubbb` = 2 ?

yes, this is what I mean. Creating index per pair is not possible because later I describe transient queue prefix, where denoms must be sorted by their sequences


<!-- Sent from Reviewable.io -->

2023-08-07 07:11 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @keyleu, @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/README.md` line 54 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal9KQWEGIRkf8UiJRh:-NbDpDHIEPcb_AjwOosJ:b7lijjo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't get the question 
Do you mean order of orderbooks ?
</blockquote></details>

I mean we have multiple pairs,  from what pair we start the end-blocker?


<!-- Sent from Reviewable.io -->

2023-08-07 07:41 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @keyleu, @miladz68, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 54 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-Nal9KQWEGIRkf8UiJRh:-NbDwKSS73RUbcOb7t8X:b-yqh6cd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9ab4f4325e7c741f31e48aba98e621db5f2fcd0c/x/dex/spec/README.md#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean we have multiple pairs,  from what pair we start the end-blocker?
</blockquote></details>

Whatever the first one is in FIFO


<!-- Sent from Reviewable.io -->

2023-08-07 07:56 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @keyleu, @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/README.md` line 31 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbDvxy3-_8MtOHHV1lp:-NbDvxy3-_8MtOHHV1lq:b-bwuebw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L31)):*
> ```Markdown
> Example: This is the hypothetical `uaaa/ubbb` order book:
> 
> | Amount `[uaaa]` | Sell price `[ubbb/uaaa]` | Buy price `[ubbb/uaaa]` | Explanation |                                                                                
> ```

I would keep that table as `Amount sell` `Amount buy` and instead on having 3 columns keept 2.  Or keep 2 tables as you will have on the chan later, that give better understanding IMO. 
___
*[`x/dex/spec/README.md` line 647 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbDx_9oChVMu3kSz0Qh:-NbDx_9p8Zt2yKFkTlTV:b-4nwaz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L647)):*
> ```Markdown
> ## Order rejection
> 
> To limit the amount of data stored in the order books, orders should be rejected under some circumstances:
> ```

Not sure about all those rules.
___
*[`x/dex/spec/README.md` line 749 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbDycAL-0YEtKwkyPI2:-NbDycAL-0YEtKwkyPI3:b-bohnis) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L749)):*
> ```Markdown
> the whole part, the second one to encode the decimal part.
> 
> For the whole part we may use the full scope of `uint64`, `0..18_446_744_073_709_551_615`, resulting in maximum number
> ```

Could you please explain why we are limited by the `uint64` and can't use `big` numbers?
___
*[`x/dex/spec/README.md` line 782 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbDzF2FA3zOPfYLJnS0:-NbDzF2FA3zOPfYLJnS1:b-6zwfvb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L782)):*
> ```Markdown
> ### Transient order key
> 
> When orders are collected by the message handlers, they are added to the transient FIFO queue to be processed
> ```

What is the purpose of the transient store here? Is it faster?


<!-- Sent from Reviewable.io -->

2023-08-07 07:59 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 749 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbDycAL-0YEtKwkyPI2:-NbE-K_t05mJJQBDEL1D:b-rt7cvd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L749)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why we are limited by the `uint64` and can't use `big` numbers?
</blockquote></details>

The price must have the same number of bytes for all the records
___
*[`x/dex/spec/README.md` line 782 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbDzF2FA3zOPfYLJnS0:-NbE-P1GBJ0AylpB6JAK:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L782)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the purpose of the transient store here? Is it faster?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-08-07 09:26 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @vertex451, and @ysv)

___
*[`x/dex/spec/README.md` line 756 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/588#-NbEJK1r8rTlB0rMOOfo:-NbEJK1r8rTlB0rMOOfp:b-ttvs4w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b020dfb8c1204d1ccfe561410c397a0e3b76020/x/dex/spec/README.md#L756)):*
> ```Markdown
> This system gives us the ability to store numbers in the scope `0.0000000000000000000..18446744073709551615.9999999999999999999`,
> using 16 bytes. Take a note that maybe (this is huge "maybe" because I didn't do the full analysis) we could use the magic of
> `float64` and store the price as a mantissa and exponent, using only 8 bytes at the same time. I may figure it out, but
> ```

Let's use sign+exponent+mantissa in decimal system


<!-- Sent from Reviewable.io -->

2023-08-08 10:58 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @keyleu, @miladz68, @vertex451, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-08-11 06:27 UTC, miladz68 reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 4 unresolved discussions (waiting on @keyleu, @vertex451, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-08-11 06:44 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @vertex451, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-08-11 09:18 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/588)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @vertex451)



<!-- Sent from Reviewable.io -->

2023-08-11 09:38 UTC, merged