Draft: Update cosmos SDK to v0.47.4
CoreumFoundation/coreum pull request #592
Opened 2023-08-07 11:09 UTC by dzmitryhil

* Update cosmos SDK to v0.47.4
* Update wasm SDK to v0.40.1
* Update  github.com/gogo/protobuf to github.com/cosmos/gogoproto
* Update and replace legacy SDK libs with new ones (math, errors)
* Fix unit tests
* Fix integration tests that are compatible with the SDK
* Leave `FIXME` comments for the parts which should be fixed

2023-08-08 07:40 UTC, miladz68 requested changes
> Reviewed 5 of 192 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbJ4WWY5zcGeBryxC3G:b-ssqkib) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
> ```XML
> go 1.20
> 
> // FIXME(v47-dependencies): check that we need all of those replaces
> ```

I am getting this error when building cored with crust 
```
/home/milad/go/pkg/mod/cosmossdk.io/tools/rosetta@v0.2.1/lib/errors/errors.go:12:2: ambiguous import: found package github.com/coinbase/rosetta-sdk-go/types in multiple modules:
	github.com/coinbase/rosetta-sdk-go v0.7.9 (/home/milad/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.7.9/types)
	github.com/coinbase/rosetta-sdk-go/types v1.0.0 (/home/milad/go/pkg/mod/github.com/coinbase/rosetta-sdk-go/types@v1.0.0)
```
could you share your go.work file if you have it ?
___
*[`.github/workflows/ci-v0.47-migration.yml` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIy1SZ2LgQdnhF5cN1:-NbIy1SZ2LgQdnhF5cN2:b-jmgtv2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/.github/workflows/ci-v0.47-migration.yml#L1)):*
> ```YAML
> name: ci
> ```

why do we need the file re name ?


<!-- Sent from Reviewable.io -->

2023-08-08 12:06 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 19 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`config.yml` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIrSCXCWuQ0E4DfhFj:-NbJn9kQEaEjo7mVuvle:b6mk0s5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/config.yml#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what is it for? This file is not referenced anywhere
</blockquote></details>

Without that file the new version of the ignite, compatible with v0.47.x SDK doesn't work.
___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbJnzqNAynsuEVdnh-V:b-t785rs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am getting this error when building cored with crust 
```
/home/milad/go/pkg/mod/cosmossdk.io/tools/rosetta@v0.2.1/lib/errors/errors.go:12:2: ambiguous import: found package github.com/coinbase/rosetta-sdk-go/types in multiple modules:
	github.com/coinbase/rosetta-sdk-go v0.7.9 (/home/milad/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.7.9/types)
	github.com/coinbase/rosetta-sdk-go/types v1.0.0 (/home/milad/go/pkg/mod/github.com/coinbase/rosetta-sdk-go/types@v1.0.0)
```
could you share your go.work file if you have it ?
</blockquote></details>

You need to use the `dzmitryhil/update-v0.47-migration-to-v2-compatible` crust branch. Later I'll change it to `update-v0.47-migration-to-v2` once we merge it.
___
*[`.github/workflows/ci-v0.47-migration.yml` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIy1SZ2LgQdnhF5cN1:-NbJoRZ9-K-S5MTKIL-0:bfmi518) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/.github/workflows/ci-v0.47-migration.yml#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why do we need the file re name ?
</blockquote></details>

We need it as tepm CI, before we merge it to that master
___
*[`app/amino_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIshD53LaJmpkvo_Nh:-NbJoaYbB3YAzIUw9V4S:b-xdlvbp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why isn't this test defined inside each module to specifically test messages from that module. Doing it globally doesn't make sense as it creates yet another global place to keep in mind.
</blockquote></details>

That test is test from the master. And the idea of it is to check all messages, so that's why it's in the app.
___
*[`app/amino_test.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIsYYqDz318eeNqsuI:-NbJol-P4DLtXTWM_6Rf:b-b7bk2p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

should messages from our modules be added here?
</blockquote></details>

Check prev comment.
___
*[`integration-tests/ibc/asset_ft_test.go` line 153 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIxU21BhHitQwKKRsV:-NbJopKhD3ieGgysYnHK:bk7i0bf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/ibc/asset_ft_test.go#L153)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: I like the previous form more
</blockquote></details>

The prev form was removed (depricated) from the SDK. 
___
*[`integration-tests/modules/bank_test.go` line 765 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIyAN-8gNhlT9EPZPP:-NbJoy7b-Fy30RsxZjSf:b-njaob1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/modules/bank_test.go#L765)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you explain this change. This test was expected to succeed and after the change you expect it fails. Why?
</blockquote></details>

In the new SDK version it's prohibited to use multiple senders for the multisend.
___
*[`integration-tests/modules/wasm_test.go` line 381 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIycP64gUxrl8KGn_T:-NbJp7fc9cErxsIncGa0:bh9i99b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/modules/wasm_test.go#L381)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what does the linter complain about?
</blockquote></details>

Usage of depricated method. 
___
*[`pkg/client/context.go` line 368 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIzILtBm1C4nPFID-O:-NbJpEHG6m1tzGCIXXTx:bxb37z3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/client/context.go#L368)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

How both RPC and GRPC clients are supported now?
</blockquote></details>

Updated. I expected that new SDK client handles it, but I was wrong. 
___
*[`pkg/client/context.go` line 374 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIzUUy90ek5g7tafGv:-NbJr_nu0VVk6ivYh-gE:bty37wj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/client/context.go#L374)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is the cancelable `ctx` correctly supported inside the original `Invoke` now?
</blockquote></details>

For the GRPC - yes, for the PRC - not. Updated to support.
___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ-IDECVhH8stZZKZL:-NbJqWdc08pL-WkWl3qK:boxshnh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/config/genesis/genesis.v1.tmpl.json#L84)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

v1 template is used with `v1.0.0` binary, so I think it should to be touched
</blockquote></details>

Agree, restored.
___
*[`x/asset/ft/client/cli/tx_test.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ0hPO0F_vIlHbrbD2:-NbJvdfT-IvX9QUof2gP:bqhxcwj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/x/asset/ft/client/cli/tx_test.go#L93)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Isn't `"677"` simpler?
</blockquote></details>

That's the prev value.


<!-- Sent from Reviewable.io -->

2023-08-08 12:13 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: 188 of 192 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbK30Ti4VEfZpWIlOpr:b-7gl9hj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You need to use the `dzmitryhil/update-v0.47-migration-to-v2-compatible` crust branch. Later I'll change it to `update-v0.47-migration-to-v2` once we merge it.
</blockquote></details>

tried it, but same error. 


<!-- Sent from Reviewable.io -->

2023-08-08 12:14 UTC, miladz68 reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-08-08 12:19 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbK4Vfn4Vk3Cz7rpGyU:bhlfp53) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

tried it, but same error. 
</blockquote></details>

But CI passes. 
___
*[`app/app.go` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ84eW7ZtVR20SrphR:-NbK3YNs9AZzec-jfckP:blqgm79) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/app.go#L166)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

DefaultMessageValidator enforces that we only have 1 tx in genesis and it is a create validator tx. but in devnet we have multiple validators at genesis. add todo to provide the correct message validator and and a follow up task not to forget it. 
</blockquote></details>

We don't use the method for the devenet. And don't use it in general, so I would propose to keep it as is until we face real use-case and understand how it should work. 
___
*[`app/app.go` line 212 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJGI7N6niRMCC4ogd-:-NbK3JAKATFfVtnhk3-W:b-o5yp5o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/app.go#L212)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking reminder
we should not forget to add the group module here. 
</blockquote></details>

We have task for it. 
___
*[`pkg/client/context.go` line 373 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ_tg624vNX0a_0UZv:-NbK3sba7CjEoz3O-wA6:b-worxri) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/client/context.go#L373)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see that fall back to rpc, in case grpc is not present is handled by cosmos sdk now.
I think we can start embedding the original context in our context now, and we will not need to repeat all the `With` function. 
</blockquote></details>

We need it, they don't respect the go context for the RPC calls. 
___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJgsu2-N2zuk7X23Fr:-NbK4J5Y0AaPPjzKW9Zm:bynkc9d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/config/genesis/genesis.v3.tmpl.json#L8)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

just checking. 
I am guessing that time_iota_ms is completely removed from v47.
</blockquote></details>

Based on sources - yes.
___
*[`testutil/network/network.go` line 127 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJitLY86oUgTbBSgW0:-NbK4O_1DE6prNc8bHc7:bpp91c4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/testutil/network/network.go#L127)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why are we randomizing chain-id ?
</blockquote></details>

That's the standard pattern. And also I gues for the simapp home folder. 
___
*[`x/asset/ft/keeper/grpc_query.go` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJnqrg-yJWlZ1qQCpj:-NbK1gtN0C9doJwbGj0P:b5n13yu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/x/asset/ft/keeper/grpc_query.go#L6)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

as commented befored, I think cosmoserrors already covers sdkerrors. 
</blockquote></details>

Some of `cosmoserrors` methods are deprecated, the methods you mention.
___
*[`x/asset/nft/module.go` line 186 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJtWMN8sm3XJrOq8eF:-NbK2yB8-e8tvYamyrPC:bj7u1sc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/x/asset/nft/module.go#L186)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non blocking, 
why should we try to be compatible in simulations API ?  may be we should add a todo to fix the decrepated API usage instead of trying to be backwards compatible ? 
</blockquote></details>

Agree, added to FIXME task.
___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ-IDECVhH8stZZKZL:-NbK4ZODAjTcr05eCpHt:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/config/genesis/genesis.v1.tmpl.json#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, restored.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-08 13:28 UTC, miladz68 requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ84eW7ZtVR20SrphR:-NbKJxDq2mlOY5Ugy-c6:b-x2z8a0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/app.go#L166)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We don't use the method for the devenet. And don't use it in general, so I would propose to keep it as is until we face real use-case and understand how it should work. 
</blockquote></details>

I guess it will be used to validate genesis, so If we run validate genesis command it will fail ?
___
*[`integration-tests/modules/bank_test.go` line 765 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIyAN-8gNhlT9EPZPP:-NbKKBxr6mdg_C0x2N7r:b-n8faf0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/modules/bank_test.go#L765)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In the new SDK version it's prohibited to use multiple senders for the multisend.
</blockquote></details>

it will make our life simpler. we should create a task to make before_send simpler. 


<!-- Sent from Reviewable.io -->

2023-08-08 14:07 UTC, ysv requested changes
> Reviewed 5 of 192 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJgarIEiLVhK1q2TAb:-NbJgarIEiLVhK1q2TAc:b-v3d3pi) (no related file):*
do we have a branch in crust which should be used ?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbKTIprDCFxzRV6u5TZ:-NbKTIpsAXxrgNZJfnhw:b-l3tgic) (no related file):*
Posting first part of comments & continuing the review

___
___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbJgVcBAM3PczWDDfTX:b-9skbmm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am getting this error when building cored with crust 
```
/home/milad/go/pkg/mod/cosmossdk.io/tools/rosetta@v0.2.1/lib/errors/errors.go:12:2: ambiguous import: found package github.com/coinbase/rosetta-sdk-go/types in multiple modules:
	github.com/coinbase/rosetta-sdk-go v0.7.9 (/home/milad/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.7.9/types)
	github.com/coinbase/rosetta-sdk-go/types v1.0.0 (/home/milad/go/pkg/mod/github.com/coinbase/rosetta-sdk-go/types@v1.0.0)
```
could you share your go.work file if you have it ?
</blockquote></details>

same for me 
but I guess different version of  lib-wasm is needed

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/jpzpyPHJiT7VLOAxIR3_F1Tc/image.png)
___
*[`.github/workflows/ci-v0.47-migration.yml` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIy1SZ2LgQdnhF5cN1:-NbJfpHU4RowfkKVfomQ:bzcaof9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/.github/workflows/ci-v0.47-migration.yml#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why do we need the file re name ?
</blockquote></details>

Same question 
___
*[`app/amino_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIshD53LaJmpkvo_Nh:-NbJfyNX-7jNWautWmk6:b6dmyu1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why isn't this test defined inside each module to specifically test messages from that module. Doing it globally doesn't make sense as it creates yet another global place to keep in mind.
</blockquote></details>

but do we want to create a folders & test file for each module ?

I completely disagree. Current approach is ok
___
*[`app/amino_test.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIsYYqDz318eeNqsuI:-NbJgD4912ezQSLsk0Ob:b-e4ttmk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

should messages from our modules be added here?
</blockquote></details>

vice versa they are expected to support legacy amino
___
*[`app/upgrade/v2/upgrade.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbK3X3-8FQxYoMY45CS:-NbK3X30D7IRXHdoiWCt:b-ir0oco) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/upgrade/v2/upgrade.go#L27)):*
> ```Go
> 		StoreUpgrades: storetypes.StoreUpgrades{
> 			Added: []string{
> 				ibcexported.StoreKey,
> ```

I think we should leave a todo to remove this upgrade
IMO it is highly likely that this upgrade will not work properly with IBC v7

And we don't need it once mainnet is updated
___
*[`pkg/client/context.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJkaNKEFVEhC_Wv78z:-NbJkaNKEFVEhC_Wv79-:b-364b3r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/client/context.go#L84)):*
> ```Go
> 	config    ContextConfig
> 	clientCtx client.Context
> 	awaitTx   bool
> ```

This is a feature introduced by us right ?
___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 143 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJm4-a5JKxg2Ds0jdl:-NbJm4-a5JKxg2Ds0jdm:b-41hy8h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/config/genesis/genesis.v3.tmpl.json#L143)):*
> ```JSON
>         "burn_vote_quorum": false,
>         "burn_proposal_deposit_prevote": false,
>         "burn_vote_veto": true
> ```

do we have a task to check what these 3 new params mean ?
___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 231 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJmAcjCrn0Th25z2y7:-NbJmAcjCrn0Th25z2y8:bn9oi63) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/pkg/config/genesis/genesis.v3.tmpl.json#L231)):*
> ```JSON
>         "historical_entries": 10000,
>         "bond_denom": "{{ .Denom }}",
>         "min_commission_rate": "0.000000000000000000"
> ```

we should decide about value here.
do we have a task for this ?
___
*[`testutil/simapp/account.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJrpUcCP82RWN9PFA9:-NbJrpUcCP82RWN9PFAA:bkb5b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/testutil/simapp/account.go#L24)):*
> ```Go
> }
> 
> func addTestAddrs(s *App, ctx sdk.Context, accNum int, accAmt sdkmath.Int, strategy GenerateAccountStrategy) []sdk.AccAddress {
> ```

nit: why did you rename to s ?


<!-- Sent from Reviewable.io -->

2023-08-09 06:34 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`app/amino_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIshD53LaJmpkvo_Nh:-NbNxtb_Dm1YRdcqvFoy:b-9ytl0h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I have the same opinion. 
</blockquote></details>

I mean that tests verifying that messages are compatible with amino codec should live in the appropriate folder of each module in the `x/module_name/sth`. I don't get why all the messages of all the modules are aggregated in the top package.
___
*[`app/amino_test.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIsYYqDz318eeNqsuI:-NbNyGk--7seUK4JDzeq:b-de9c1k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

No - they don't support legacy amino and that's expected by us.
</blockquote></details>

IIRC we had to add amino support to be able to use multisig, no?
___
*[`integration-tests/ibc/asset_ft_test.go` line 153 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIxU21BhHitQwKKRsV:-NbNzhDN1u4PnA9TOQy9:b-7f1a32) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/ibc/asset_ft_test.go#L153)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The prev form was removed (depricated) from the SDK. 
</blockquote></details>

Funny, from time to time they accidentally implement sth useful, and then remove it
___
*[`integration-tests/modules/bank_test.go` line 765 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIyAN-8gNhlT9EPZPP:-NbNzzZnE36bSucuCad5:b-xl2ux5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/modules/bank_test.go#L765)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, added to the umbrella task.
</blockquote></details>

Do we have a test to test multisend with one sender?
___
*[`pkg/client/context.go` line 49 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbNyhbxCQxJzTh8pV8i:-NbNyhbxCQxJzTh8pV8j:bflizv5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/260ce1805bedf44a97fff91cba2e125fd5a711a2/pkg/client/context.go#L49)):*
> ```Go
> type failingInterfaceRegistry struct{}
> 
> // errCodecNotSet is return by failingInterfaceRegistry in case there are attempt to decode
> ```

- is returned
- - there is an attempt
___
*[`pkg/client/context.go` line 423 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbNyyd8B3BylgqGMCvi:-NbNyyd8B3BylgqGMCvj:b-qragvd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/260ce1805bedf44a97fff91cba2e125fd5a711a2/pkg/client/context.go#L423)):*
> ```Go
> // NewStream implements the grpc ClientConn.NewStream method.
> func (c Context) NewStream(ctx context.Context, desc *grpc.StreamDesc, method string, opts ...grpc.CallOption) (grpc.ClientStream, error) {
> 	if c.RPCClient() != nil {
> ```

I think this `if` should not exist. Do it with GRPC if available or return error.
___
*[`testutil/simapp/account.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJrpUcCP82RWN9PFA9:-NbNzSln5BZrd9Tr1AFQ:b-mk2drr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/testutil/simapp/account.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Because we use `func (s *App)` for the App methods. 
</blockquote></details>

why do we use `s` there? :D
___
*[`x/asset/ft/client/cli/tx_test.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ0hPO0F_vIlHbrbD2:-NbO-8J-DogWP_mVeyeW:bk8zytu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/x/asset/ft/client/cli/tx_test.go#L93)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That's the prev value.
</blockquote></details>

I mean writing `sdkmath.NewInt(677).String()` is a complicated way of saying `"677"`


<!-- Sent from Reviewable.io -->

2023-08-09 08:57 UTC, miladz68 requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

___
*[`app/app.go` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ84eW7ZtVR20SrphR:-NbOVbpA6iukvfbdx8v6:b85fe7s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/app.go#L166)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It might be used for the `gentxs` to form genesis. 
</blockquote></details>

could you add a todo to checkout it out later please ?


<!-- Sent from Reviewable.io -->

2023-08-09 10:15 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/amino_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIshD53LaJmpkvo_Nh:-NbOlIb46M6ELaidPWzK:b-horodh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean that tests verifying that messages are compatible with amino codec should live in the appropriate folder of each module in the `x/module_name/sth`. I don't get why all the messages of all the modules are aggregated in the top package.
</blockquote></details>

What about message for which we don't have a module? SDK messages for example?
___
*[`app/amino_test.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIsYYqDz318eeNqsuI:-NbOlTByCU9FEy58QIp5:bl6l1cg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IIRC we had to add amino support to be able to use multisig, no?
</blockquote></details>

For the SDK we can't without fork. 
___
*[`app/app.go` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ84eW7ZtVR20SrphR:-NbOlr7u5W7SHiq7IVo4:bv8rry5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/app.go#L166)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

could you add a todo to checkout it out later please ?
</blockquote></details>

OK, added. 
___
*[`integration-tests/ibc/asset_ft_test.go` line 153 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIxU21BhHitQwKKRsV:-NbOm2Jc4jA4ukhjSfrU:b2nh4j5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/ibc/asset_ft_test.go#L153)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Funny, from time to time they accidentally implement sth useful, and then remove it
</blockquote></details>

:-)
___
*[`integration-tests/modules/bank_test.go` line 765 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIyAN-8gNhlT9EPZPP:-NbOm8WZ41BzP0_TWr_m:b-mo45jp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/modules/bank_test.go#L765)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we have a test to test multisend with one sender?
</blockquote></details>

Yes and even more that one. 
___
*[`pkg/client/context.go` line 49 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbNyhbxCQxJzTh8pV8i:-NbOmEduCAz4KnBhVF0y:b-s778bj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/260ce1805bedf44a97fff91cba2e125fd5a711a2/pkg/client/context.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

- is returned
- - there is an attempt
</blockquote></details>

SDK copy.

Updated.
___
*[`pkg/client/context.go` line 423 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbNyyd8B3BylgqGMCvi:-NbOmRWz7iMKi5y_Hqw-:b-lxs8x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/260ce1805bedf44a97fff91cba2e125fd5a711a2/pkg/client/context.go#L423)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think this `if` should not exist. Do it with GRPC if available or return error.
</blockquote></details>

This is for the furue upgrade in case they add the stream support for the RPC.
___
*[`testutil/simapp/account.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJrpUcCP82RWN9PFA9:-NbOm_28-bjT19sYrp8V:b5zt2ia) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/testutil/simapp/account.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why do we use `s` there? :D
</blockquote></details>

It was `s` before :-) 
`s` - `simaApp`, the name is taken from the SDK.
___
*[`x/asset/ft/client/cli/tx_test.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ0hPO0F_vIlHbrbD2:-NbOmm-FEW8p9n92NxPg:b-jx9o34) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/x/asset/ft/client/cli/tx_test.go#L93)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean writing `sdkmath.NewInt(677).String()` is a complicated way of saying `"677"`
</blockquote></details>

We can, but that's the orginal tests, and I don't refactor them in the current PR :-)


<!-- Sent from Reviewable.io -->

2023-08-09 11:41 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: 190 of 192 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbKTIprDCFxzRV6u5TZ:-NbP3E4EBkfCRZqScL1t:bp1vek7) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

finished

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJgarIEiLVhK1q2TAb:-NbP4AvI4rtut5_-LpXW:b-dm5bzz) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, checl the ci-v0.47-migration.yml github workflow. 
For now I use `dzmitryhil/update-v0.47-migration-to-v2-compatible` later it will be `v0.47-migration-to-v2`
</blockquote></details>

I see ok.
Now it was built successfuly for me

IMO this is worth mentioning in PR description in case someone wants to build it

___
___
*[`app/amino_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIshD53LaJmpkvo_Nh:-NbP4gMg5ubuMCjqqQbH:b-dzggfz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about message for which we don't have a module? SDK messages for example?
</blockquote></details>

I don't see a reason to make in so complicated
The idea here is similar to deterministic gas pkg.
And there we iterate through all messages from a single place. 

The idea if this test is protection agains ourselves to make sure we properly implement amino for our messages & skip explicitly if it is not needed
___
*[`app/upgrade/v2/upgrade.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbK3X3-8FQxYoMY45CS:-NbP3HIc8ccGAydzhwAq:b3m753k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/upgrade/v2/upgrade.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But this is not relevant to the v0.47 upgrade, isn't it?
</blockquote></details>

well as side effect of this change upgrade might be broken
and since it is not needed now (mainnet & testnet upgraded) we don't need to fix it but just removing is ok

To not keep broken code in repo


<!-- Sent from Reviewable.io -->

2023-08-09 11:46 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: 190 of 192 files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbP5Y0m7f_bdcgHOLO_:b-6nq5nc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's updated in the `dzmitryhil/update-v0.47-migration-to-v2-compatible` branch. 
</blockquote></details>

works for me now
___
*[`app/amino_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIshD53LaJmpkvo_Nh:-NbP5aIe3gDz_PwjpA7I:blrkw3a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/amino_test.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't see a reason to make in so complicated
The idea here is similar to deterministic gas pkg.
And there we iterate through all messages from a single place. 

The idea if this test is protection agains ourselves to make sure we properly implement amino for our messages & skip explicitly if it is not needed

</blockquote></details>

I'm 100% ok with the current version
___
*[`app/upgrade/v2/upgrade.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbK3X3-8FQxYoMY45CS:-NbP613mDZp1Ge3aOIjG:b-2wmc1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/upgrade/v2/upgrade.go#L27)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well as side effect of this change upgrade might be broken
and since it is not needed now (mainnet & testnet upgraded) we don't need to fix it but just removing is ok

To not keep broken code in repo
</blockquote></details>

not critical for me
So if you wish we can resolve and keep as is
___
*[`integration-tests/ibc/asset_ft_test.go` line 153 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbIxU21BhHitQwKKRsV:-NbP69wa-Ay5c3XaTKSj:bi02v4b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/integration-tests/ibc/asset_ft_test.go#L153)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

:-)
</blockquote></details>

lol, also preferred prev version
___
*[`testutil/simapp/account.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJrpUcCP82RWN9PFA9:-NbP6Sny776r6g3F9h-7:b32wtd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/testutil/simapp/account.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It was `s` before :-) 
`s` - `simaApp`, the name is taken from the SDK.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-08-09 11:59 UTC, wojtek-coreum requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`app/upgrade/v2/upgrade.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbK3X3-8FQxYoMY45CS:-NbP9UiR3I_9gdij4G5N:b-tx3smi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/upgrade/v2/upgrade.go#L27)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not critical for me
So if you wish we can resolve and keep as is
</blockquote></details>

I agree, v1 is dead, we will never come back to it
___
*[`pkg/client/context.go` line 423 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbNyyd8B3BylgqGMCvi:-NbP8q1eCLcSP_92t3SY:b7j51go) ([raw file](https://github.com/CoreumFoundation/coreum/blob/260ce1805bedf44a97fff91cba2e125fd5a711a2/pkg/client/context.go#L423)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is for the furue upgrade in case they add the stream support for the RPC.
</blockquote></details>

But if I have both clients configured in context, then it will always fail


<!-- Sent from Reviewable.io -->

2023-08-09 12:22 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJgarIEiLVhK1q2TAb:-NbPD2w5BK-LJcWfD6qe:b-8ezbo2) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see ok.
Now it was built successfuly for me

IMO this is worth mentioning in PR description in case someone wants to build it
</blockquote></details>

Agree, updated.

___
___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbJ4WWY5zcGeBryxC3F:-NbPDJFc6x3kUDnckv8I:btojbfq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/go.mod#L5)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

works for me now
</blockquote></details>

Great.
___
*[`app/upgrade/v2/upgrade.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbK3X3-8FQxYoMY45CS:-NbPDP8Y1ZN4Q77SOhDa:b-ux5j8a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/upgrade/v2/upgrade.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I agree, v1 is dead, we will never come back to it
</blockquote></details>

I can remove/update it. But we have a separate task for the upgrade fix, so in the scope of it it make sense to remove/update anything here. So you know why you do it and you know what was before. 
___
*[`pkg/client/context.go` line 423 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbNyyd8B3BylgqGMCvi:-NbPEo_1D2N_WwE2a9L0:buavyg2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/260ce1805bedf44a97fff91cba2e125fd5a711a2/pkg/client/context.go#L423)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But if I have both clients configured in context, then it will always fail
</blockquote></details>

Got you, updated the order. Decide to keep the RPC nil check to return better error. 


<!-- Sent from Reviewable.io -->

2023-08-09 13:28 UTC, miladz68 approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-08-09 13:30 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: all files reviewed, 2 unresolved discussions (waiting on @vertex451 and @ysv)



<!-- Sent from Reviewable.io -->

2023-08-09 19:35 UTC, ysv approved these changes
> Reviewed 175 of 192 files at r1, 3 of 4 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/592)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

___
*[`app/upgrade/v2/upgrade.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/592#-NbK3X3-8FQxYoMY45CS:-NbQmwCWElSmPTNUhlkj:b-kc2bcl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e1976361003cea2beb0db078b0952b7f1dc5806/app/upgrade/v2/upgrade.go#L27)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I can remove/update it. But we have a separate task for the upgrade fix, so in the scope of it it make sense to remove/update anything here. So you know why you do it and you know what was before. 
</blockquote></details>

ok, I would leave a TODO here


<!-- Sent from Reviewable.io -->

2023-08-10 07:40 UTC, merged