New feature allowing to disable sending FT to smart contracts
CoreumFoundation/coreum pull request #684
Opened 2023-10-25 07:24 UTC by wojtek-coreum

# Description

There are 4 entry points now, which are handled to detect if sender or recipient is a smart contract:
- single send in bank keeper
- multi send in bank keeper
- handler of messages executed by smart contract
- smart contract instantiation

In those entry points, addresses are added to appropriate list in context (senders or recipients) and then interested parties may verify if sender or recipient exists in the list, meaning that this is smart contract.

It might happen that one address is handled by two entry points. For example, if previously instantiated smart contract is executed with coins attached, the address of smart contract will be marked in two places:
- WASM token transferrer
- bank keeper

In this PR, smart contract instantiation is rejected if its address already exists. Otherwise, funds could be sent there in advance, before contract instantiation.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2023-10-25 12:16 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 0 of 32 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 573 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahYm_DpE607T5xHI3:-NhahYm_DpE607T5xHI4:bkt80fd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/app/app.go#L573)):*
> ```Go
> 
> 	wasmOpts := []wasmkeeper.Option{
> 		wasmkeeper.WithAcceptedAccountTypesOnContractInstantiation(),
> ```

The wasm is so flexible :-) 
___
*[`integration-tests/contracts/ibc/contract.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhai0WNCcZQ3Enx_wMy:-Nhai0WNCcZQ3Enx_wMz:bjm2ymv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/ibc/contract.go#L21)):*
> ```Go
> 
> // EmptyPayload represents empty payload.
> var EmptyPayload = must.Bytes(json.Marshal(struct{}{}))
> ```

This file is for the embedding only, move that variable to the tests folder. 
___
*[`integration-tests/contracts/modules/authz.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhaibq8A2lOymtVGimz:-Nhaibq8A2lOymtVGin-:bsh4rlj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz.go#L15)):*
> ```Go
> func AuthZExecuteTransferRequest(address string, amount sdk.Coin) json.RawMessage {
> 	return must.Bytes(json.Marshal(map[string]map[string]interface{}{
> 		"transfer": {
> ```

We use structs for all such payloads (here and for the next function and for the `bank-send.go`). 
___
*[`integration-tests/contracts/modules/authz/src/contract.rs` line 52 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhaiIXy-gLAtlTBNbkh:-NhaiIXy-gLAtlTBNbki:bwtgzxm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz/src/contract.rs#L52)):*
> ```XML
>     deps: DepsMut,
>     env: Env,
>     address: String,
> ```

What was the reason to change it?
___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-NhahmzX5EnPXvI-HAQ8:b-ht0rfi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
> ```proto
>   whitelisting = 3;
>   ibc = 4;
>   sending_to_smart_contracts_blocked = 5;
> ```

@miladz68 @ysv Are you OK with that name? Any better name for the feature?
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-NhakBBeBmou-lvy1YxH:b-5q8tjc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
> ```Go
> package wasm
> ```

IMO that file confuses more than gives. Better to follow the current way with the expected keepers.
___
*[`x/wasm/types/purpose.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhajjNa7OqyyFfZDyq-:-NhajjNa7OqyyFfZDyq0:btmce7e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L28)):*
> ```Go
> 
> // IsSendingSmartContract returns true if address is the smart contract sending funds.
> func IsSendingSmartContract(ctx sdk.Context, addr string) bool {
> ```

Do we really need both `IsSendingSmartContract` and `IsTriggeredBySmartContract`?
___
*[`x/wasm/types/purpose.go` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakfrK5pGi_OQqSLCc:-NhakfrK5pGi_OQqSLCd:byoz03v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L33)):*
> ```Go
> 
> // IsReceivingSmartContract returns true if address is the smart contract receiving funds.
> func IsReceivingSmartContract(ctx sdk.Context, addr string) bool {
> ```

You use that With and Is in the assetft only, why is it located here?
___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-NhagxR414WAPxAoInag:b9a4av8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
> ```Go
> }
> 
> func add(ctx sdk.Context, addr string, key interface{}) sdk.Context {
> ```

Could you please explain why you need a map here and in the `has`?


<!-- Sent from Reviewable.io -->

2023-10-25 12:22 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 0 of 32 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/wasm/types/purpose.go` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakfrK5pGi_OQqSLCc:-Nham-He7Wnr39Ckc-0d:b-bz1ox9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You use that With and Is in the assetft only, why is it located here?
</blockquote></details>

In general, if it is possible not to use the context keys for the logic and call the wasm keeper directly, better to do it that way.


<!-- Sent from Reviewable.io -->

2023-10-25 12:42 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 0 of 32 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/contracts/modules/authz.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhaibq8A2lOymtVGimz:-NhapFv_Ex7kbxzxe_-D:b-gz8r35) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We use structs for all such payloads (here and for the next function and for the `bank-send.go`).
</blockquote></details>

but this is used in one place only so I don't see that struct to be beneficial
___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-NhapZjb76qioMG8WQV9:bodcejs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@miladz68 @ysv Are you OK with that name? Any better name for the feature?
</blockquote></details>

Ah, forgot to rename it to "disallowing_smart_contracts" proposed by Reza. Will do it.
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-NhaplGq0ScOdZswSy-m:b-nsq6ep) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO that file confuses more than gives. Better to follow the current way with the expected keepers.
</blockquote></details>

We take the same approach in IBC modules
___
*[`x/wasm/types/purpose.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhajjNa7OqyyFfZDyq-:-Nhaprbd6vCCgDHK6TuX:bljt85h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we really need both `IsSendingSmartContract` and `IsTriggeredBySmartContract`?
</blockquote></details>

yes, we do :-). The fact that operation is triggered by the smart contract doesn't mean that it is a sender or recipient.
___
*[`x/wasm/types/purpose.go` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakfrK5pGi_OQqSLCc:-NhaqQNi2tW3IlXcl0zj:b4ytsjh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In general, if it is possible not to use the context keys for the logic and call the wasm keeper directly, better to do it that way.
</blockquote></details>

It is located here because it relates to smart contract. The same way, similar functions for IBC are kept inside wibc module.
___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-Nhaq_QS6OVpeu-J1s8V:b-u6odda) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why you need a map here and in the `has`?
</blockquote></details>

There might be many recipients and many senders, so I need to store multiple addresses. And then I want to check if articular address is the sender/recipient or not. So map is a natural choice.


<!-- Sent from Reviewable.io -->

2023-10-26 07:50 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 0 of 33 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/contracts/ibc/contract.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhai0WNCcZQ3Enx_wMy:-NhevgkMDXeCaddeC_al:b24ers5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/ibc/contract.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This file is for the embedding only, move that variable to the tests folder.
</blockquote></details>

Moved it to `payload.go` All the payload-generating functions are in `module` package.
___
*[`integration-tests/contracts/modules/authz/src/contract.rs` line 52 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhaiIXy-gLAtlTBNbkh:-NhewGia7hundbKWJaMQ:b-hlmhaa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz/src/contract.rs#L52)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What was the reason to change it?
</blockquote></details>

To make it compatible with what we have inside `bank-send` contract
___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-NhexfJP-jSpLrLZoqKj:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ah, forgot to rename it to "disallowing_smart_contracts" proposed by Reza. Will do it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-26 08:55 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 0 of 33 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/contracts/modules/authz.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhaibq8A2lOymtVGimz:-NhfAxRc6Vz-qnnpiQ0J:b-ge1nyd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but this is used in one place only so I don't see that struct to be beneficial
</blockquote></details>

Similar as other tests, we use them in the tests only. @miladz68 @ysv  WHYT ?
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-NhfBBc-7X3_4ZpJjRXh:b-ihybje) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We take the same approach in IBC modules
</blockquote></details>

So I don't like it in both :-) 
@miladz68 @ysv WDYT ? 


<!-- Sent from Reviewable.io -->

2023-10-26 09:07 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 0 of 33 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/contracts/modules/authz.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhaibq8A2lOymtVGimz:-NhfDbb37U8hQHfc1T6H:b-9dbhlf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Similar as other tests, we use them in the tests only. @miladz68 @ysv  WHYT ?
</blockquote></details>

Nope, take a look at `simple-state.go`. I just follow that idea.
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-NhfDmdP6YdXNq_7IPHY:b-z5xa7v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So I don't like it in both :-) 
@miladz68 @ysv WDYT ?
</blockquote></details>

But this is the only way. IBC wrappers are the only place where we know we deal with IBC transfer.
WASM wrappers are the only places where we know we deal with smart contract. We discussed long time ago that tagging context is the only way.


<!-- Sent from Reviewable.io -->

2023-10-27 07:41 UTC, miladz68 approved these changes
> Reviewed 22 of 32 files at r1, 8 of 9 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

___
*[`integration-tests/contracts/modules/authz.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhaibq8A2lOymtVGimz:-Nhk3-YKBFtT6wKyU3ao:b26fq3k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nope, take a look at `simple-state.go`. I just follow that idea.
</blockquote></details>

using map is ok here IMO. 
___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-Nhk3KRP1ujODO0RcNPd:b8brknh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

it would be better if we remove the `ing`
`disallow_smart_contracts `
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-Nhk3mcc6Oh57IvPXf3m:b-13fpo9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But this is the only way. IBC wrappers are the only place where we know we deal with IBC transfer.
WASM wrappers are the only places where we know we deal with smart contract. We discussed long time ago that tagging context is the only way.
</blockquote></details>

yes, `helpers.go` is not a good name there. the keeper can be moved to expected_keepers


<!-- Sent from Reviewable.io -->

2023-10-27 09:48 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-NhkX0du0xHOl8h5RFpk:b-q3ahjk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it would be better if we remove the `ing`
`disallow_smart_contracts `
</blockquote></details>

but wasn't tht a rule that we want to keep -ing? On the other hand we don't use ibcing :-)


<!-- Sent from Reviewable.io -->

2023-10-27 11:01 UTC, miladz68 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-NhkmrBRDljGwPdATs86:b659mwd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but wasn't tht a rule that we want to keep -ing? On the other hand we don't use ibcing :-)
</blockquote></details>

I think we abandaned that rule with`ibc` .


<!-- Sent from Reviewable.io -->

2023-10-27 11:11 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 32 of 34 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-Nhkp8uz83Ug33K9iQ9q:b-rzik0e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yes, `helpers.go` is not a good name there. the keeper can be moved to expected_keepers
</blockquote></details>

how to name that file then?


<!-- Sent from Reviewable.io -->

2023-10-27 11:56 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 32 of 34 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-NhkzQEQ9p_9F_QGqgqw:b-s303h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we abandaned that rule with`ibc` .
</blockquote></details>

Agree with @wojtek-coreum 


<!-- Sent from Reviewable.io -->

2023-10-30 12:03 UTC, miladz68 approved these changes
> Reviewed 1 of 2 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-Ni-SYp0ElVIrIQcYhnm:b8odtcl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

how to name that file then?
</blockquote></details>

I honestly don't have a good name.
`address.go` is an option. or it can live inside `query.go`


<!-- Sent from Reviewable.io -->

2023-10-30 13:43 UTC, ysv requested changes
> Reviewed 20 of 32 files at r1, 3 of 9 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`docs/static/openapi.json` line 7029 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-PKUE9FI6QaB0k9Jc:-Ni-PKUE9FI6QaB0k9Jd:b-92akx0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/docs/static/openapi.json#L7029)):*
> ```JSON
>         "whitelisting",
>         "ibc",
>         "disallowing_smart_contracts"
> ```

what about `block_smart_contracts` ?
___
*[`integration-tests/contracts/modules/authz.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Nhaibq8A2lOymtVGimz:-Ni-Q1UQBK4SRmRZVyU1:b-9zc162) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/integration-tests/contracts/modules/authz.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

using map is ok here IMO.
</blockquote></details>

don't have strong preference
Both are ok. 

probably would be nice to stick to a single usage everywhere
___
*[`integration-tests/ibc/asset_ft_test.go` line 143 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-RCACDTEa--GbFCIh:-Ni-RCAG7_xZZptbp1pJ:b-qrl23x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/ibc/asset_ft_test.go#L143)):*
> ```Go
> 		SendCommissionRate: sdk.MustNewDecFromStr("0.2"),
> 		Features: []assetfttypes.Feature{
> 			assetfttypes.Feature_disallowing_smart_contracts,
> ```

nit:
is this feature really necessary in all the tests where you added it ?
`assetfttypes.Feature_disallowing_smart_contracts`
___
*[`integration-tests/modules/assetft_test.go` line 5229 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-h4qs4r2uc_YhZx_z:-Ni-h4qs4r2uc_YhZxa-:bpezd1e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/assetft_test.go#L5229)):*
> ```Go
> // TestAssetFTMintingAndSendingOnBehalfOfIssuingSmartContractIsPossibleEvenIfSmartContractsAreBlocked verifies that it is possible
> // to use authz to mint and send the token on behalf of the issuing smart contract if smart contracts are blocked.
> func TestAssetFTMintingAndSendingOnBehalfOfIssuingSmartContractIsPossibleEvenIfSmartContractsAreBlocked(t *testing.T) {
> ```

so here you grant authz permissions to send & mint on behalf of smart contract to another acc and then try to use it ?
___
*[`integration-tests/modules/assetft_test.go` line 5363 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-hUPj9Zsnaf-nAqGE:-Ni-hUPj9Zsnaf-nAqGF:b-38l06k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/assetft_test.go#L5363)):*
> ```Go
> 
> // TestAssetFTSendingTokensFromRegularAccountBySmartContractUsingAuthZIsDenied verifies that it is forbidden to execute authz
> // message to transfer coins by smart contraxct from regular account if smart contracts are blocked.
> ```

nit:
`contraxct`
___
*[`integration-tests/modules/wasm_test.go` line 1685 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-iRIlCm7ZmY6sLW-S:-Ni-iRIlCm7ZmY6sLW-T:b-xet74e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/wasm_test.go#L1685)):*
> ```Go
> // TestWASMContractInstantiationIsRejectedIfThereAreTokensOnItsAccount verifies that smart contract instantiation
> // is rejected if account exists.
> func TestWASMContractInstantiationIsRejectedIfAccountExists(t *testing.T) {
> ```

as far as I understand, here you predict account addr by salt

But what happens if you don't specify salt ? Is it generated randomly each time or users will face failing constantly requests ?
___
*[`proto/coreum/asset/ft/v1/token.proto` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhahmzX5EnPXvI-HAQ7:-Ni-omrV0qUPUV_LD7-v:bvtp1bl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/proto/coreum/asset/ft/v1/token.proto#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree with @wojtek-coreum
</blockquote></details>

IMO block_smart_contracts or blocking_smart_contracts is reasonable
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-Ni-kTCV-kXU2BuydZh5:b8rnav9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I honestly don't have a good name.
`address.go` is an option. or it can live inside `query.go`
</blockquote></details>

don't like the name either 
address.go is better or putting to expected_keepers.go also ok

But I'm not sure if initial Dima's comment about this
Lets discuss 
___
*[`x/wasm/handler/message.go` line 15 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-kFOJEku1h4fLI8ZU:-Ni-kFOJEku1h4fLI8ZV:b9gyr4w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L15)):*
> ```Go
> 	assetfttypes "github.com/CoreumFoundation/coreum/v3/x/asset/ft/types"
> 	assetnfttypes "github.com/CoreumFoundation/coreum/v3/x/asset/nft/types"
> 	"github.com/CoreumFoundation/coreum/v3/x/wasm/types"
> ```

when we wrap module we usually prefix it with `w` (wstaking, wbank etc)

shouldn't we do the same for wasm `wwasm` :sweat_smile:  ?
___
*[`x/wasm/handler/message.go` line 261 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-lkfkA24w9_v_5bqR:-Ni-lkfl-876Sdp8N7GI:bmhglrb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L261)):*
> ```Go
> 
> // DispatchMsg sets smart contract sender in the context, in case the executed message handlers sends tokens from the smart contract account.
> func (m *MessengerWrapper) DispatchMsg(
> ```

lets discuss I need explanation here
___
*[`x/wasm/types/prunner.go` line 10 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-mD9P0oM5pzvcaci-:-Ni-mD9P0oM5pzvcaci0:b4mu30j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/types/prunner.go#L10)):*
> ```Go
> // AccountPruner implements wasm's account pruner in a way causing smart contract instantiation to be rejected if
> // account exists.
> type AccountPruner struct{}
> ```

lets discuss 
___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-Ni-neuz-Ep0UYfBRQVM:b-p3y7wy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There might be many recipients and many senders, so I need to store multiple addresses. And then I want to check if articular address is the sender/recipient or not. So map is a natural choice.
</blockquote></details>

I also had similar confusion here
Maybe add comment to func and rename ? E.g `addAddr` / `addAddrToKey`

same for has
___
*[`x/wasm/types/purpose.go` line 29 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-nBSQ4NneshzqHrKp:-Ni-nBSR2p_kTziymJ3R:b-leou5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/types/purpose.go#L29)):*
> ```Go
> // IsSendingSmartContract returns tru [...]

2023-10-31 07:57 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-Ni3jAYl8S9tbeIzTj1Q:b-ar1c7y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

don't like the name either 
address.go is better or putting to expected_keepers.go also ok

But I'm not sure if initial Dima's comment about this
Lets discuss
</blockquote></details>

Agree, let's discuss.


<!-- Sent from Reviewable.io -->

2023-10-31 08:16 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 11 unresolved discussions (waiting on @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 143 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-RCACDTEa--GbFCIh:-Ni3mENW1kbaDT8g-pjj:b-ib382x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/ibc/asset_ft_test.go#L143)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit:
is this feature really necessary in all the tests where you added it ?
`assetfttypes.Feature_disallowing_smart_contracts`
</blockquote></details>

I think so, to ensure that this new feature does not accidentally block other functionalities.
___
*[`integration-tests/modules/assetft_test.go` line 5229 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-h4qs4r2uc_YhZx_z:-Ni3mPA584sacIaEpSh4:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/assetft_test.go#L5229)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so here you grant authz permissions to send & mint on behalf of smart contract to another acc and then try to use it ?
</blockquote></details>

yes
___
*[`integration-tests/modules/wasm_test.go` line 1685 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-iRIlCm7ZmY6sLW-S:-Ni3mZU_7BGqy6D4jOrn:b-39mpbi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/wasm_test.go#L1685)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as far as I understand, here you predict account addr by salt

But what happens if you don't specify salt ? Is it generated randomly each time or users will face failing constantly requests ?
</blockquote></details>

If you don't, error is returned saying that you must do it
___
*[`x/wasm/handler/message.go` line 15 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-kFOJEku1h4fLI8ZU:-Ni3mnAN8IqkryWd-W0_:b-m1bb39) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

when we wrap module we usually prefix it with `w` (wstaking, wbank etc)

shouldn't we do the same for wasm `wwasm` :sweat_smile:  ?
</blockquote></details>

we don't rap anything there, we just collect wasm-related functions and types
___
*[`x/wasm/types/purpose.go` line 29 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-nBSQ4NneshzqHrKp:-Ni3n-VfBVfgg-R-Y2Nc:bkyqxxt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/types/purpose.go#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the difference between these 2 ?

`return ctx.Value(smartContractSenderKey{}) != nil` 

vs

`return has(ctx, addr, smartContractSenderKey{})`
</blockquote></details>

`return ctx.Value(smartContractSenderKey{}) != nil` if context has been tagged with any sender
``return has(ctx, addr, smartContractSenderKey{})`` is true if context has been tagged with concrete sender


<!-- Sent from Reviewable.io -->

2023-10-31 08:27 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2023-10-31 08:27 UTC, miladz68 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2023-10-31 11:30 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 9 unresolved discussions (waiting on @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 1685 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-iRIlCm7ZmY6sLW-S:-Ni4U_cu3xI5ZERtBBXV:bj98eja) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/wasm_test.go#L1685)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If you don't, error is returned saying that you must do it
</blockquote></details>

but in current master we don't pass salt.
Lets discuss

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/9SNTFIdIuiTb7vVwMqP2oa2S/image.png)
___
*[`x/wasm/handler/message.go` line 15 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-kFOJEku1h4fLI8ZU:-Ni4UkpiEdbMDTc7JxmS:brsjcj7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we don't rap anything there, we just collect wasm-related functions and types
</blockquote></details>

I see, makes sense
But isn't x/wasm confusing or you think it is ok ?
___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-Ni4UutW05DDHef0w5YB:b-po9zy8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also had similar confusion here
Maybe add comment to func and rename ? E.g `addAddr` / `addAddrToKey`

same for has
</blockquote></details>

check my prev comment pls


<!-- Sent from Reviewable.io -->

2023-10-31 16:02 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 9 unresolved discussions (waiting on @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 1685 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-iRIlCm7ZmY6sLW-S:-Ni5T560A8VgqzJ_-6Z6:b-ovzsn4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/wasm_test.go#L1685)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This PR changes message type from `MsgInstantiateContract` to `MsgInstantiateContract2`
</blockquote></details>

I see 
Would be nice to understand how salt generation happens in `MsgInstantiateContract`
Lets have a quick discussion 
___
*[`x/wasm/handler/message.go` line 15 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-kFOJEku1h4fLI8ZU:-Ni5T0TGEOzdDOQiXRDB:bo84e0m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

For me it's ok
</blockquote></details>

for me more or less ok
But lets discuss quickly


<!-- Sent from Reviewable.io -->

2023-11-02 12:28 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`docs/static/openapi.json` line 7029 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-PKUE9FI6QaB0k9Jc:-NiEwUza9pFNDPYO5DSo:br1t84g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/docs/static/openapi.json#L7029)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about `block_smart_contracts` ?
</blockquote></details>

okay `block_smart_contracts`
___
*[`integration-tests/modules/wasm_test.go` line 1685 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-iRIlCm7ZmY6sLW-S:-NiExTUi0N7Q26HKJfLs:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/integration-tests/modules/wasm_test.go#L1685)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see 
Would be nice to understand how salt generation happens in `MsgInstantiateContract`
Lets have a quick discussion
</blockquote></details>

Done.
___
*[`x/wasm/helpers.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhakBBeBmou-lvy1YxG:-NiEy37FDBiADE3igwO6:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/helpers.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, let's discuss.
</blockquote></details>

Done.
___
*[`x/wasm/handler/message.go` line 15 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-kFOJEku1h4fLI8ZU:-NiEyGrX8iPdF6fNCU3H:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

for me more or less ok
But lets discuss quickly
</blockquote></details>

Done.
___
*[`x/wasm/handler/message.go` line 261 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-lkfkA24w9_v_5bqR:-NiF-0ey0N2HagpFgXWF:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/handler/message.go#L261)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets discuss I need explanation here
</blockquote></details>

Done.
___
*[`x/wasm/types/prunner.go` line 10 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-mD9P0oM5pzvcaci-:-NiF-2sj6TFukHEeWzye:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/types/prunner.go#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets discuss
</blockquote></details>

Done.
___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-NiF-BvF4qhq9ntR8ZT8:bf0uhyn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

check my prev comment pls
</blockquote></details>

Let's explain why many addresses are stored
___
*[`x/wasm/types/transferrer.go` line 22 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-Ni-oJ3x4zRK6uH2AamA:-NiF-HNWEM6UAUX2-KEC:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/757877439e897e39f6604397eefd4ef27292bbf4/x/wasm/types/transferrer.go#L22)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we need this ?
lets discuss pls
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 15:34 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-NiFegUjCyWzzVsnDJKA:b-yaytwj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's explain why many addresses are stored
</blockquote></details>

pls add comment & I will resolve


<!-- Sent from Reviewable.io -->

2023-11-03 06:54 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 30 of 34 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/wasm/types/purpose.go` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/684#-NhagxR414WAPxAoInaf:-NiIxXAx6w5XjabgadMR:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9494d385807d02131c08d5bc192843419547a68/x/wasm/types/purpose.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls add comment & I will resolve
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-03 08:19 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: 24 of 34 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2023-11-03 09:49 UTC, ysv approved these changes
> Reviewed 2 of 4 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/684)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2023-11-03 11:17 UTC, merged