Create limit order and store it in the transient queue
CoreumFoundation/coreum pull request #793
Opened 2024-03-19 11:52 UTC by wojtek-coreum

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2024-03-20 06:41 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 695 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPSnJUD0RWKjPREVAu:-NtPSnJUD0RWKjPREVAv:b-21p2yy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/app/app.go#L695)):*
> ```Go
> 		appCodec,
> 		keys[dextypes.StoreKey],
> 		tkeys[feemodeltypes.TransientStoreKey],
> ```

Wrong `feemodeltypes.TransientStoreKey` store key.
___
*[`x/deterministicgas/config.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPTdx9DrRJqZpjqbn4:-NtPTdx9DrRJqZpjqbn5:bej154s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/deterministicgas/config.go#L104)):*
> ```Go
> 		// dex
> 		// FIXME (wojtek): gas values are taken our of nowhere
> 		MsgToMsgURL(&dextypes.MsgCreateLimitOrder{}): constantGasFunc(10_000),
> ```

I guess you can add just one TODO to re-estimate all messages at the end.
___
*[`x/dex/keeper/keeper.go` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPW19_AM4-_XYAjwC8:-NtPW19_AM4-_XYAjwC9:b-q628j1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L43)):*
> ```Go
> }
> 
> // StoreTransientOrder stores order in the transient queue to be processed by the end blocker.
> ```

Is the end-blocker out of scope for that PR? Because without the end-blocker I can only guess what will you do with the transient store. 
___
*[`x/dex/keeper/keeper.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWSKjDdXegdDzbK3U:-NtPWSKjDdXegdDzbK3V:bgs6zk0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L86)):*
> ```Go
> }
> 
> func (k Keeper) nextDenomSequence(ctx sdk.Context) uint64 {
> ```

nit: With the current code style that method should be after `denomSequence`. 
___
*[`x/dex/keeper/keeper.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPZIrX7Wj5XgsTjCee:-NtPZIrX7Wj5XgsTjCef:b5e8x7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L87)):*
> ```Go
> 
> func (k Keeper) nextDenomSequence(ctx sdk.Context) uint64 {
> 	store := ctx.TransientStore(k.storeKey)
> ```

I guess the first step should be the order book creation because you won't need the denom transient queue in that case, all denoms will be registered before the order creation. 
___
*[`x/dex/keeper/keeper.go` line 108 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWsECCaMWyIiXxKBp:-NtPWsECCaMWyIiXxKBq:bjgmf0z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L108)):*
> ```Go
> }
> 
> func (k Keeper) denomSequence(ctx sdk.Context, denom string) uint64 {
> ```

IMO the method name is not clear. Could you please update it, because that method might access the store but looks like not.


<!-- Sent from Reviewable.io -->

2024-03-20 07:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 695 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPSnJUD0RWKjPREVAu:-NtPjpGK6NkiC9HLoR4b:b-b4f4ea) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/app/app.go#L695)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Wrong `feemodeltypes.TransientStoreKey` store key.
</blockquote></details>

whoa, Done
___
*[`x/dex/keeper/keeper.go` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPW19_AM4-_XYAjwC8:-NtPk7i6EM4leplat5FV:b-daekq8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is the end-blocker out of scope for that PR? Because without the end-blocker I can only guess what will you do with the transient store.
</blockquote></details>

yes, that is a separate task
___
*[`x/dex/keeper/keeper.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPZIrX7Wj5XgsTjCee:-NtPkOcIENqSWCP4laiP:bcpo9aj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I guess the first step should be the order book creation because you won't need the denom transient queue in that case, all denoms will be registered before the order creation.
</blockquote></details>

There is nothing like "order book creation". Order book exists implicitly when there are orders to match
___
*[`x/dex/keeper/keeper.go` line 108 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWsECCaMWyIiXxKBp:-NtPktsH118XdrwkX5FO:b-jtrh1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L108)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO the method name is not clear. Could you please update it, because that method might access the store but looks like not.
</blockquote></details>

normally I would call it `getDenomSequence`, but golang conventions say that `get` should be avoided


<!-- Sent from Reviewable.io -->

2024-03-21 07:03 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: 0 of 27 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`x/dex/keeper/keeper.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPZIrX7Wj5XgsTjCee:-NtUoR5jB0XgDlYxZru7:b-h8env5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is nothing like "order book creation". Order book exists implicitly when there are orders to match
</blockquote></details>

But why do you need to generate the denom index if it not exist?
___
*[`x/dex/keeper/keeper.go` line 108 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWsECCaMWyIiXxKBp:-NtUoXOd8yqXYeOqYgaM:bn5wcoe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L108)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

normally I would call it `getDenomSequence`, but golang conventions say that `get` should be avoided
</blockquote></details>

Is it's `get` I'm ok, but we generate or get.


<!-- Sent from Reviewable.io -->

2024-03-21 08:24 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: 0 of 27 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`x/dex/keeper/keeper.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPZIrX7Wj5XgsTjCee:-NtV5mGTEWqBz-Tm8C17:b-8zggjr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But why do you need to generate the denom index if it not exist?
</blockquote></details>

To store the order under the correct key. https://github.com/CoreumFoundation/coreum/tree/master/x/dex/spec#transient-order-key
___
*[`x/dex/keeper/keeper.go` line 108 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWsECCaMWyIiXxKBp:-NtV66aX-gDisy1DiAEY:b867qmb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L108)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it's `get` I'm ok, but we generate or get.
</blockquote></details>

We get, and generate if the item does not exist


<!-- Sent from Reviewable.io -->

2024-03-26 13:00 UTC, ysv requested changes
> Reviewed 5 of 26 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: 7 of 27 files reviewed, 8 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`app/app.go` line 294 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuL7NC4cVYHa9toE4S:-NtuL7ND6NC6wXKk4wAj:blwr19u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/app/app.go#L294)):*
> ```Go
> 	CustomParamsKeeper customparamskeeper.Keeper
> 	DelayKeeper        delaykeeper.Keeper
> 	DexKeeper          dexkeeper.Keeper
> ```

DEX is acronym and we use uppercase for acronyms usually (NFT, FT), should we do the same here ?
___
*[`proto/coreum/dex/v1/orders.proto` line 10 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuPBF25z4_Lk1kQNB4:-NtuPBF25z4_Lk1kQNB5:b-9sj3eu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/orders.proto#L10)):*
> ```proto
> option (gogoproto.goproto_getters_all) = false;
> 
> // MsgIssue defines message to issue new fungible token.
> ```

nit: fix comment
___
*[`proto/coreum/dex/v1/tx.proto` line 17 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuLXHMChYKiibcBC1N:-NtuLXHMChYKiibcBC1O:biepli8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L17)):*
> ```proto
> 
> // MsgIssue defines message to issue new fungible token.
> message MsgCreateLimitOrder {
> ```

will we have different message for limit & market orders only ?
What about StopLimit, StopMarket, OCO, Trailing stop (in the future) will we define all of them separately ?

E.g stop limit & stop market are almost same and I'm not sure if we need to have separate type of each of them. Except this we have different execution rules good_till_time (current version),  Fill or kill etc. Will we create separate messages for these also ?
___
*[`proto/coreum/dex/v1/tx.proto` line 18 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuPbNC-um1dDTpXTlh:-NtuPbNC-um1dDTpXTli:b-z4mqe9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L18)):*
> ```proto
> // MsgIssue defines message to issue new fungible token.
> message MsgCreateLimitOrder {
>   string owner = 1;
> ```

we usually name this field sender
Shall we do the same here ?
___
*[`proto/coreum/dex/v1/tx.proto` line 19 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuQ1YX2BI6IeslE83e:-NtuQ1YX2BI6IeslE83f:bivv6dk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L19)):*
> ```proto
> message MsgCreateLimitOrder {
>   string owner = 1;
>   cosmos.base.v1beta1.Coin offered_amount = 2 [(gogoproto.nullable) = false];
> ```

I don't think offered gives more context here. I would name this field just `amount`.
___
*[`proto/coreum/dex/v1/tx.proto` line 20 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuQALrCqbOpVKKwCSX:-NtuQALrCqbOpVKKwCSY:bs3o7gu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L20)):*
> ```proto
>   string owner = 1;
>   cosmos.base.v1beta1.Coin offered_amount = 2 [(gogoproto.nullable) = false];
>   cosmos.base.v1beta1.DecCoin sell_price = 3 [(gogoproto.nullable) = false];
> ```

question:
so I specify amount and price is specified per each subunit of amount.

So total I expect to get is amount*sell_price ?
___
*[`x/dex/client/cli/tx.go` line 46 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuQyf52fj0AKz85HoI:-NtuQyf52fj0AKz85HoJ:brlldrr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/client/cli/tx.go#L46)):*
> ```Go
> 
> Example:
> $ %s tx %s create-limit-order 10wsatoshi 123.12wwei --from [issuer]
> ```

`--from sender or owner`

pls check other places
___
*[`x/dex/keeper/keeper.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuRjNqCqoBbvWTMaCE:-NtuRjNqCqoBbvWTMaCF:bff1kjl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L58)):*
> ```Go
> 	}
> 
> 	tStore := ctx.TransientStore(k.transientStoreKey)
> ```

how do you order Orders which are in the same block ? Which has higher priority here & insider matching ?


<!-- Sent from Reviewable.io -->

2024-03-26 13:01 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: 7 of 27 files reviewed, 9 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuqMAsBERrR2xN5NPb:-NtuqMAsBERrR2xN5NPc:b-iypfzm) (no related file):*
partially reviewed

___


<!-- Sent from Reviewable.io -->

2024-03-26 16:30 UTC, ysv requested changes
> Reviewed 17 of 26 files at r1, 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_vI97B-2IDcUoa6P:-Ntv_vI97B-2IDcUoa6Q:b-5irf8m) (no related file):*
I think we will need a call to discuss some of the comments 

___
___
*[`x/dex/keeper/keeper.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWSKjDdXegdDzbK3U:-NtvVafm9rEd8VABYf_H:b-irlfa1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L86)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: With the current code style that method should be after `denomSequence`.
</blockquote></details>

why ?)
___
*[`x/dex/keeper/keeper.go` line 108 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWsECCaMWyIiXxKBp:-NtvWZb08NKPEc35tp7b:b4n858x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L108)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We get, and generate if the item does not exist
</blockquote></details>

I tend to agree with Dima here
Either `getOrGenerate...` or maybe `createDenomSequence`
___
*[`x/dex/keeper/keeper.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvX-ek0P3bSeZk3EZ1:-NtvX-el9SwyHGMWg1IO:b-26n21s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L45)):*
> ```Go
> // StoreTransientOrder stores order in the transient queue to be processed by the end blocker.
> func (k Keeper) StoreTransientOrder(ctx sdk.Context, order Order) error {
> 	denom1Seq, denom2Seq := k.denomTransientSequences(ctx, order.DenomOffered(), order.DenomRequested())
> ```

do I understand it correctly that you have a single transient queue for all orders not separate one per market ?
___
*[`x/dex/keeper/keeper.go` line 59 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvXoDa6yd8PvQgczob:-NtvXoDa6yd8PvQgczoc:btyb2op) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L59)):*
> ```Go
> 
> 	tStore := ctx.TransientStore(k.transientStoreKey)
> 	tStore.Set(types.CreateOrderTransientQueueKey(denom1Seq, denom2Seq, orderSeq), bz)
> ```

why do we need denom1Seq & denom2Seq in transient queue key ? 
I thought that orderSeq is already unique ?
___
*[`x/dex/keeper/keeper.go` line 108 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvYYqS8eying9jYqAP:-NtvYYqS8eying9jYqAQ:b-guzens) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L108)):*
> ```Go
> }
> 
> func (k Keeper) denomTransientSequences(ctx sdk.Context, denom1, denom2 string) (uint64, uint64) {
> ```

if this is only BE think I would prefer to compare denom sequences instead.
So flow is: first you get denomSequence1 and 2 and then swap them if needed.
Because number comparison is more straightforward & efficient.

If FE is going to user this logic also then lets keep strings
___
*[`x/dex/types/errors.go` line 12 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvZV3-BeKYx2FQBmSU:-NtvZV3-BeKYx2FQBmSV:b-8yrigk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/errors.go#L12)):*
> ```Go
> 
> 	// ErrInvalidCoin defines the error for the invalid coin.
> 	ErrInvalidCoin = sdkerrors.Register(ModuleName, 2, "invalid coin")
> ```

nit: doesn't this error exist in standard cosmos skd ?
Seems to be common
___
*[`x/dex/types/keys.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_Oib-fzwQXNgT08Q:-Ntv_Oib-fzwQXNgT08R:b-a5xvmh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L26)):*
> ```Go
> var (
> 	OrderTransientSequenceKey = []byte{0x00}
> 	OrderTransientQueueKey    = []byte{0x01}
> ```

what is the difference between these 2 ?



_Code quote:_
```Go
	OrderTransientSequenceKey = []byte{0x00}
	OrderTransientQueueKey    = []byte{0x01}
```
___
*[`x/dex/types/keys.go` line 27 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_RjzEAHBQFhll6Sc:-Ntv_RjzEAHBQFhll6Sd:bdit9m9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L27)):*
> ```Go
> 	OrderTransientSequenceKey = []byte{0x00}
> 	OrderTransientQueueKey    = []byte{0x01}
> 	DenomSequenceKey          = []byte{0x02}
> ```

question: this one stores last sequence only, correct ?
___
*[`x/dex/types/keys.go` line 28 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_1nHC4Ghrbb_RbUN:-Ntv_1nI4b3plP3YxqHA:b-es9lvy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L28)):*
> ```Go
> 	OrderTransientQueueKey    = []byte{0x01}
> 	DenomSequenceKey          = []byte{0x02}
> 	DenomMappingKey           = []byte{0x03}
> ```

nit: not 100% clear name I would name it DenomToSequenceMappingKey
Same for methods
___
*[`x/dex/types/msgs.go` line 32 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_bn55kZCgkoWJXAG:-Ntv_bn55kZCgkoWJXAH:bloctjb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/msgs.go#L32)):*
> ```Go
> func (m MsgCreateLimitOrder) ValidateBasic() error {
> 	if _, err := sdk.AccAddressFromBech32(m.Owner); err != nil {
> 		return sdkerrors.Wrapf(cosmoserrors.ErrInvalidAddress, "invalid issuer %s", m.Owner)
> ```

pls check all copy-past places


<!-- Sent from Reviewable.io -->

2024-03-27 07:01 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/dex/v1/tx.proto` line 17 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuLXHMChYKiibcBC1N:-NtyfwMe2p76_f2aLGsM:buay8ea) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

will we have different message for limit & market orders only ?
What about StopLimit, StopMarket, OCO, Trailing stop (in the future) will we define all of them separately ?

E.g stop limit & stop market are almost same and I'm not sure if we need to have separate type of each of them. Except this we have different execution rules good_till_time (current version),  Fill or kill etc. Will we create separate messages for these also ?
</blockquote></details>

It depends on the feature I guess. If one is just an extension of the existing logic we will probably extend the existing message. If logic is very different, then we will introduce a new one.
___
*[`proto/coreum/dex/v1/tx.proto` line 20 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuQALrCqbOpVKKwCSX:-NtygBHl0vCDPoB6reBY:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

question:
so I specify amount and price is specified per each subunit of amount.

So total I expect to get is amount*sell_price ?
</blockquote></details>

yes
___
*[`x/dex/keeper/keeper.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvX-ek0P3bSeZk3EZ1:-NtygDzI84FMBsaMyble:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do I understand it correctly that you have a single transient queue for all orders not separate one per market ?
</blockquote></details>

yes
___
*[`x/dex/keeper/keeper.go` line 58 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuRjNqCqoBbvWTMaCE:-NtygIzY5atq8YgGPtHi:bl6gw5p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

how do you order Orders which are in the same block ? Which has higher priority here & insider matching ?
</blockquote></details>

they are ordered by `orderSeq`, so the first gets the priority
___
*[`x/dex/keeper/keeper.go` line 59 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvXoDa6yd8PvQgczob:-NtygRYkEkrJ58oOzNjW:b-73767j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we need denom1Seq & denom2Seq in transient queue key ? 
I thought that orderSeq is already unique ?
</blockquote></details>

to process orders belonging to the same order book together, to keep only one order book in the memory at a time
___
*[`x/dex/keeper/keeper.go` line 108 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvYYqS8eying9jYqAP:-Ntygg5v2J_5E2fnMdsi:b-5wxe9a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L108)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if this is only BE think I would prefer to compare denom sequences instead.
So flow is: first you get denomSequence1 and 2 and then swap them if needed.
Because number comparison is more straightforward & efficient.

If FE is going to user this logic also then lets keep strings
</blockquote></details>

yes, I already changed this in the second PR: https://github.com/CoreumFoundation/coreum/blob/wojtek/dex-order-matching/x/dex/types/keys.go#L57
___
*[`x/dex/types/keys.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_Oib-fzwQXNgT08Q:-NtyhEiM9kxPdMf6lkr-:b9uxayg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the difference between these 2 ?
</blockquote></details>

sequence key stores the latest generated order sequence (1, 2, 3...)
queue key stores the transient queue (list of orders to process in the endblocker)
___
*[`x/dex/types/keys.go` line 27 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_RjzEAHBQFhll6Sc:-NtyhVD14Twcufg8-73_:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L27)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

question: this one stores last sequence only, correct ?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-03-27 09:21 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtzCZCz8CDSAOvmfw_m:-NtzCZCz8CDSAOvmfw_n:busbyaw) (no related file):*
@ysv 
I addressed your comments in the second PR: https://reviewable.io/reviews/CoreumFoundation/coreum/795
I think it might be better to review that one, because many pieces were moved.

___
___
*[`app/app.go` line 294 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuL7NC4cVYHa9toE4S:-Ntz8AGz-aoHrjdiky7h:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/app/app.go#L294)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

DEX is acronym and we use uppercase for acronyms usually (NFT, FT), should we do the same here ?
</blockquote></details>

Done.
___
*[`proto/coreum/dex/v1/tx.proto` line 18 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuPbNC-um1dDTpXTlh:-Ntz8RzG4_YZhzuGvNsc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we usually name this field sender
Shall we do the same here ?
</blockquote></details>

Done.
___
*[`proto/coreum/dex/v1/tx.proto` line 19 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuQ1YX2BI6IeslE83e:-Ntz8T308jZYpzEBdffV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't think offered gives more context here. I would name this field just `amount`.
</blockquote></details>

Done.
___
*[`x/dex/client/cli/tx.go` line 46 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuQyf52fj0AKz85HoI:-Ntz8d4S2EE45wQ4_KhX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/client/cli/tx.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`--from sender or owner`

pls check other places
</blockquote></details>

Done.
___
*[`x/dex/types/errors.go` line 12 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvZV3-BeKYx2FQBmSU:-Ntz90_3AJYtVnyIgETS:b67lln3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/errors.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: doesn't this error exist in standard cosmos skd ?
Seems to be common
</blockquote></details>

there is one for "invalid coins", but we have only one coin here
___
*[`x/dex/types/msgs.go` line 32 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_bn55kZCgkoWJXAG:-NtzCULUEeSRjknP3yYS:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/msgs.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls check all copy-past places
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-27 15:14 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtzCZCz8CDSAOvmfw_m:-Nu-SKuf1SEMk6sYz4kd:b-c6agit) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv 
I addressed your comments in the second PR: https://reviewable.io/reviews/CoreumFoundation/coreum/795
I think it might be better to review that one, because many pieces were moved.
</blockquote></details>

how do we continue working on these 2 PRs ?
shall we merge them or smth else ?

___
___
*[`proto/coreum/dex/v1/tx.proto` line 17 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtuLXHMChYKiibcBC1N:-Nu-TLbh8gep-hSz84OM:b-leax72) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/proto/coreum/dex/v1/tx.proto#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It depends on the feature I guess. If one is just an extension of the existing logic we will probably extend the existing message. If logic is very different, then we will introduce a new one.
</blockquote></details>

keeping this topic open
I will make a quick research & lets discuss it after
___
*[`x/dex/keeper/keeper.go` line 59 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvXoDa6yd8PvQgczob:-Nu-RF5N6W-0xGh3aJsu:b2vskbk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L59)):*
> to keep only one order book in the memory at a time
Idea is clear but I don't understand why we need these 2 sequences in transient queue.

I thought that idea of transient queue is to just temporary store orders before matching.
So basically what is useful for us here is just queue functionality and we just need some unique key. As far as I understand, you anyways should read order before matching fully so we can keep denom1Seq, denom2Seq inside bz, don't we ?
___
*[`x/dex/types/keys.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_Oib-fzwQXNgT08Q:-Nu-T-U99wYF2AQaYsI2:b-jgh97x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

sequence key stores the latest generated order sequence (1, 2, 3...)
queue key stores the transient queue (list of orders to process in the endblocker)
</blockquote></details>

`OrderTransientSequenceKey` - but is it really transient sequence key ? Because this sequence will be used everywhere so it global ID for order. I would name it: OrderLastSequenceKey
___
*[`x/dex/types/keys.go` line 27 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_RjzEAHBQFhll6Sc:-Nu-So6D9wJEdiWRhq3R:bwnp3hj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes
</blockquote></details>

nit: I would name it DenomLastSequenceKey 


<!-- Sent from Reviewable.io -->

2024-03-28 08:38 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtzCZCz8CDSAOvmfw_m:-Nu3CK6tCepvBIV6eX-B:bitni6l) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

how do we continue working on these 2 PRs ?
shall we merge them or smth else ?
</blockquote></details>

I think it's better to ignore this one and focus on the other. I may rebase that one on top of master

___


<!-- Sent from Reviewable.io -->

2024-03-28 08:40 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/dex/keeper/keeper.go` line 59 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvXoDa6yd8PvQgczob:-Nu3CXZ3D4td0keJK2bj:bggtmvu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> to keep only one order book in the memory at a time
Idea is clear but I don't understand why we need these 2 sequences in transient queue.

I thought that idea of transient queue is to just temporary store orders before matching.
So basically what is useful for us here is just queue functionality and we just need some unique key. As far as I understand, you anyways should read order before matching fully so we can keep denom1Seq, denom2Seq inside bz, don't we ?
</blockquote></details>

Yes, transient queue is a temporary one. Where orders are sorted by:
- order book
- order sequence

They are sorted by order book to process one order book at a time, to store temporary data in RAM for one order book a t a time only, to just save resources


<!-- Sent from Reviewable.io -->

2024-03-28 08:43 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/dex/types/keys.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-Ntv_Oib-fzwQXNgT08Q:-Nu3DGeAEHfG0DPv3yst:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/types/keys.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`OrderTransientSequenceKey` - but is it really transient sequence key ? Because this sequence will be used everywhere so it global ID for order. I would name it: OrderLastSequenceKey
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 11:00 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/dex/keeper/keeper.go` line 59 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvXoDa6yd8PvQgczob:-Nu3ge_g4a4FsmLdcXFQ:bfzuqsm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, transient queue is a temporary one. Where orders are sorted by:
- order book
- order sequence

They are sorted by order book to process one order book at a time, to store temporary data in RAM for one order book a t a time only, to just save resources
</blockquote></details>

this will not work properly with cross-orderbook matching because order from AAA/BBB might affect other orderbooks AAA/CCC & CCC/BBB. So IMO we should strictly order it by sequence.

Except this, we will probably have some kind of limit of orders that we process in a single end blocker and IMO we should strictly sort them by order sequence for in such case.


<!-- Sent from Reviewable.io -->

2024-03-29 09:32 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/dex/keeper/keeper.go` line 59 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtvXoDa6yd8PvQgczob:-Nu8YMUfEMZwpwll5Tqb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1e272d1247102302ddcd3c8f95c21b8e4b910cf/x/dex/keeper/keeper.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this will not work properly with cross-orderbook matching because order from AAA/BBB might affect other orderbooks AAA/CCC & CCC/BBB. So IMO we should strictly order it by sequence.

Except this, we will probably have some kind of limit of orders that we process in a single end blocker and IMO we should strictly sort them by order sequence for in such case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 13:03 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/793)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/dex/keeper/keeper.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/793#-NtPWSKjDdXegdDzbK3U:-NuOk3tq0thqv4ac9NiJ:b-o6hwq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ced7c79271fa7b84405247e0b0ab928fee0636a1/x/dex/keeper/keeper.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why ?)
</blockquote></details>

The function you call should be below the place you call it.


<!-- Sent from Reviewable.io -->

2024-04-10 08:03 UTC, closed without merging