Allow NFT data modification
CoreumFoundation/coreum pull request #800
Opened 2024-04-10 11:51 UTC by dzmitryhil

# Description

Allow NFT data modification

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2024-04-15 11:52 UTC, miladz68 requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-NvWOVEH4pDLCydHc9SW:b-1hid50) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
> ```proto
> 
> // MsgUpdateData defines message to update the dynamic data.
> message MsgUpdateData {
> ```

possible collision with UpdateClassData, so maybe UpdateNFTData ? WDYT ?
___
*[`x/asset/nft/client/cli/tx.go` line 275 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvW7V1L9QF6CjUfKVAR:-NvW7V1L9QF6CjUfKVAS:b-hoofdk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L275)):*
> ```Go
> 			ID := args[1]
> 
> 			data, err := getDataFromFile(cmd)
> ```

you should make the assertion that the returned proto type is dynamic. 
___
*[`x/asset/nft/client/cli/tx.go` line 281 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWLgG0Eu11K5b-_IRN:-NvWLgG0Eu11K5b-_IRO:b-ifxmrw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L281)):*
> ```Go
> 
> 			var dataDynamicIndexedItems []types.DataDynamicIndexedItem
> 			if err := json.Unmarshal(data, &dataDynamicIndexedItems); err != nil {
> ```

we should not mix json unmarshalling with proto unmarshalling. I am guessing unmarshalling a list of proto definitions is the issue here. in that case, we should parse the entire update proto message. 
___
*[`x/asset/nft/keeper/keeper.go` line 1160 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWNwFPEFrWJDRGZDeu:-NvWNwFPEFrWJDRGZDev:b8r5rol) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/keeper/keeper.go#L1160)):*
> ```Go
> // TODO: probably we should path naming `is` -> `validate` here and for all similar.
> // The `is` funcs should rerun bool not error.
> func (k Keeper) isNFTUpdatable(ctx sdk.Context, classID, nftID string) error {
> ```

isNFTUpdatable only checks for freezing, and is not a reusable functions. the check can be done inside the update function itself.
___
*[`x/asset/nft/keeper/keeper_test.go` line 232 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWV0nzCFEaIuAP5VL2:-NvWV0nzCFEaIuAP5VL3:b-6xeps) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/keeper/keeper_test.go#L232)):*
> ```Go
> }
> 
> func TestKeeper_Update(t *testing.T) {
> ```

_Update => _UpdateNFTData


<!-- Sent from Reviewable.io -->

2024-04-15 16:18 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-NvX62-h9GvvN5SfDynn:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

possible collision with UpdateClassData, so maybe UpdateNFTData ? WDYT ?
</blockquote></details>

Agree, updated.
___
*[`x/asset/nft/client/cli/tx.go` line 275 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvW7V1L9QF6CjUfKVAR:-NvXUanV7NrB4AjgN_2a:b-vx6bs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L275)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you should make the assertion that the returned proto type is dynamic.
</blockquote></details>

I don't need it since the `ValidateBasic` will do it.
___
*[`x/asset/nft/client/cli/tx.go` line 281 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWLgG0Eu11K5b-_IRN:-NvXUl17Djoze8x9FJIC:b-csxgj6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L281)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should not mix json unmarshalling with proto unmarshalling. I am guessing unmarshalling a list of proto definitions is the issue here. in that case, we should parse the entire update proto message.
</blockquote></details>

And what is the issue with it? Check the `DataDynamicIndexedItem` in contains the json tags. 
___
*[`x/asset/nft/keeper/keeper.go` line 1160 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWNwFPEFrWJDRGZDeu:-NvXV5gz3Q1UiRy76_mK:balc0us) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/keeper/keeper.go#L1160)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

isNFTUpdatable only checks for freezing, and is not a reusable functions. the check can be done inside the update function itself.
</blockquote></details>

We can duplicate that code. In the `isNFTSendable` and inside the update function, but IMO the current way is better.
___
*[`x/asset/nft/keeper/keeper_test.go` line 232 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWV0nzCFEaIuAP5VL2:-NvXVLFCCnQhUMVfx9Df:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/keeper/keeper_test.go#L232)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

_Update => _UpdateNFTData
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 08:34 UTC, masihyeganeh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 17 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-:-Nva13q2E0KRGFfqzIwY:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-16 10:01 UTC, ysv requested changes
> Reviewed 7 of 17 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-NvX5Rjv9WB73c53eZAY:b-a67wo1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, updated.
</blockquote></details>

I think it was our convention to not use NFT. So if nothing is specified then it is NFT, for everything else (e.g Class) it should be specified explicitly

Didn't we agree to name it like this ?
___
*[`x/asset/nft/client/cli/tx.go` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvX5xMZ35eKeqqYZysC:-NvX5xMZ35eKeqqYZysD:b-x4xiu9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L36)):*
> ```Go
> 	DataTypeFlag    = "data-type"
> 	// data types.
> 	DataTypeBytes   = "bytes"
> ```

bytes and dynamic doesn't sound like enumeration of similar things.
Maybe we should use constant or const or const-bytes instead ?



_Code quote:_
```Go
bytes
```
___
*[`x/asset/nft/client/cli/tx.go` line 792 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaFjpW53iVgz4DwUgt:-NvaFjpX1ZHomIyr3XcJ:b-t64w4z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/client/cli/tx.go#L792)):*
> ```Go
> }
> 
> func getDataFromFile(cmd *cobra.Command) ([]byte, error) {
> ```

nit: read is probably better word here



_Code quote:_
```Go
get
```
___
*[`x/asset/nft/keeper/keeper.go` line 382 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaGDklEPJvX3J-l2Cs:-NvaGDkm5P_meXubbYOq:b-ace1i1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L382)):*
> ```Go
> 		return sdkerrors.Wrapf(types.ErrNFTNotFound, "nft with classID:%s and ID:%s not found", classID, id)
> 	}
> 	if storedNFT.Data.TypeUrl != "/"+proto.MessageName((*types.DataDynamic)(nil)) {
> ```

there is better method for this e.g: `sdk.MsgTypeURL(&authtypes.MsgUpdateParams{})`



_Code quote:_
```Go
proto.MessageName((*types.DataDynamic)(nil))
```
___
*[`x/asset/nft/keeper/keeper.go` line 843 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaHJOn-rYh-UrLP1-4:-NvaHJOn-rYh-UrLP1-5:bdkvza3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L843)):*
> ```Go
> 	item types.DataDynamicItem,
> ) (bool, error) {
> 	for _, editor := range item.Editors {
> ```

nit: I would write the logic here differently. This version seems more straightforward for me

```
senderRoles := []string{}
if classDefinition.IsIssuer(sender) {
  senderRoles = append(senderRoles, types.DataEditor_admin)
}

if owner.String() == sender.String() {
  senderRoles = append(senderRoles, types.DataEditor_owner)
}

if lo.Some(item.Editors, senderRoles) { // check if any of sender roles is included in editors
  return true, nil
}

return false, sdkerrors...
```

does your logic handles properly case when admin is owner of an item and tries to update data ? Do you have test for this
___
*[`x/asset/nft/keeper/keeper.go` line 1158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJ0AW6OsyMyMgsgNV:-NvaJ0AW6OsyMyMgsgNW:b-jxshfy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L1158)):*
> ```Go
> }
> 
> // TODO: probably we should path naming `is` -> `validate` here and for all similar.
> ```

I agree with this todo. IMO func starting with is should return bool
___
*[`x/asset/nft/types/msgs_test.go` line 432 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJyFkCsW96Q1GlOyL:-NvaJyFkCsW96Q1GlOyM:b-mak86i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/msgs_test.go#L432)):*
> ```Go
> 	}
> 
> 	for _, testCase := range testCases {
> ```

do we have test for too big data with DataDynamic
___
*[`x/asset/nft/types/token.go` line 214 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaLO5S-ShsYuDBAX09:-NvaLO5S-ShsYuDBAX0A:b-z0gyis) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L214)):*
> ```Go
> 
> 	for i, item := range dataDynamic.Items {
> 		usedEditors := make(map[DataEditor]struct{}, 0)
> ```

nit: I would prefer lo.FindDuplicates (same way as in other place). 
___
*[`x/asset/nft/types/token.go` line 218 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaKd9K2n7JyF3cIkpk:-NvaKd9L3i4mJT3DEByU:b-6035cr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L218)):*
> ```Go
> 			_, exists := DataEditor_name[int32(editor)]
> 			if !exists {
> 				return sdkerrors.Wrapf(ErrInvalidInput, "non-existing data editor provided: %d", editor)
> ```

Should we validate everything and then return all errors ? or returning first one happened is fine here ?

I mean that validation might fail in multiple places
___
*[`x/asset/nft/types/token.go` line 218 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaKspa0xdWjyM74KQD:-NvaKspa0xdWjyM74KQE:b-ks7oop) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L218)):*
> ```Go
> 			_, exists := DataEditor_name[int32(editor)]
> 			if !exists {
> 				return sdkerrors.Wrapf(ErrInvalidInput, "non-existing data editor provided: %d", editor)
> ```

do we need to specify number of item in which validation failed to be more user friendly ?


<!-- Sent from Reviewable.io -->

2024-04-16 10:55 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-NvaV9cE3ePPqijKDkF3:bqz0zb3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think it was our convention to not use NFT. So if nothing is specified then it is NFT, for everything else (e.g Class) it should be specified explicitly

Didn't we agree to name it like this ?
</blockquote></details>

But see, you can't mint class, right? But can update data of class and NFT, IMO update NFT data is better name here.
___
*[`x/asset/nft/client/cli/tx.go` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvX5xMZ35eKeqqYZysC:-NvaVRlDBycZ125S7K7m:b-lv8w8e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

bytes and dynamic doesn't sound like enumeration of similar things.
Maybe we should use constant or const or const-bytes instead ?
</blockquote></details>

The name here is similar to the name in the proto. DataBytes and DataDynamic. 
___
*[`x/asset/nft/client/cli/tx.go` line 792 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaFjpW53iVgz4DwUgt:-NvaVayJCGnwDvfpKasL:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/client/cli/tx.go#L792)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: read is probably better word here
</blockquote></details>

Done
___
*[`x/asset/nft/keeper/keeper.go` line 382 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaGDklEPJvX3J-l2Cs:-NvaVfDs5RnKZTBhgjy5:beo8giw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L382)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

there is better method for this e.g: `sdk.MsgTypeURL(&authtypes.MsgUpdateParams{})`
</blockquote></details>

DataBytes and DataDynamic are not sdk.Msg, but that func expects the sdk.Msg.
___
*[`x/asset/nft/keeper/keeper.go` line 843 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaHJOn-rYh-UrLP1-4:-NvaWPu2Bkc_D_HQOgk5:b-uxnzzn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L843)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I would write the logic here differently. This version seems more straightforward for me

```
senderRoles := []string{}
if classDefinition.IsIssuer(sender) {
  senderRoles = append(senderRoles, types.DataEditor_admin)
}

if owner.String() == sender.String() {
  senderRoles = append(senderRoles, types.DataEditor_owner)
}

if lo.Some(item.Editors, senderRoles) { // check if any of sender roles is included in editors
  return true, nil
}

return false, sdkerrors...
```

does your logic handles properly case when admin is owner of an item and tries to update data ? Do you have test for this
</blockquote></details>

But it uses more iterations. And as for me, not simpler. 
___
*[`x/asset/nft/keeper/keeper.go` line 1158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJ0AW6OsyMyMgsgNV:-NvaW_IF1J9Q_vqy-nQH:bqazs6v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L1158)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with this todo. IMO func starting with is should return bool
</blockquote></details>

Let's probably create the task to revise them and update? Since it's out of scope for that PR.
___
*[`x/asset/nft/types/msgs_test.go` line 432 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJyFkCsW96Q1GlOyL:-NvaWjMd2opYHY8Lm7Jc:b-oibudn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/msgs_test.go#L432)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we have test for too big data with DataDynamic
</blockquote></details>

Yes. `valid_msg_with_max_data_size` covers it, since we validate `any` data size.
___
*[`x/asset/nft/types/token.go` line 214 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaLO5S-ShsYuDBAX09:-NvaWyOF4_LGJrEKTsRd:b1vgpri) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L214)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I would prefer lo.FindDuplicates (same way as in other place).
</blockquote></details>

The difference with the `lo.FindDuplicates` is that the current func covers 2 use cases:

* `non-existing data editor provided`
* `duplicated dynamic data editor`

So if you use the `lo.FindDuplicates` you will have to write `non-existing data editor provided` anyway. 
___
*[`x/asset/nft/types/token.go` line 218 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaKd9K2n7JyF3cIkpk:-NvaXI33CUD8wLdFCQYX:bvjmi1b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L218)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Should we validate everything and then return all errors ? or returning first one happened is fine here ?

I mean that validation might fail in multiple places
</blockquote></details>

Fail fast is the best approach for the code, otherwise, the code will be complicated. 
___
*[`x/asset/nft/types/token.go` line 218 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaKspa0xdWjyM74KQD:-NvaXP4K9AZ9_NqePVuc:buvfu2n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L218)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we need to specify number of item in which validation failed to be more user friendly ?
</blockquote></details>

For `non-existing data editor` - not, since we get that error only if someone tries to ignore the proto.


<!-- Sent from Reviewable.io -->

2024-04-17 09:36 UTC, ysv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvfPGeU2HSKKh7HJtDI:-NvfPGeV-D7oleMPDUIC:b7n8e7g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/689a01dd2e2ece438a670d9d77caee05970a3225/.github/workflows/ci.yml#L26)):*
> ```YAML
>         ]
>         include:
> # # FIXME(dzmitryhil) - expected proto breaking change, will be fixed after the merge
> ```

why do we have proto-breaking change ?
Or it is because some protos were merged to master before ?
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-NvfNQem-VTiEImuLevZ:b-oszna2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But see, you can't mint class, right? But can update data of class and NFT, IMO update NFT data is better name here.
</blockquote></details>

yes I'm not insisting to change it right away, but more to discuss

Because It is different from the convention we were following before

e.g: MsgMint, MsgBurn, MsgFreeze/MsgUnfreeze, MsgAddToWhitelist etc.
All of them don't mention NFT. We actually never mention it and for class we always do it
```
service Msg {
  // IssueClass creates new non-fungible token class.
  rpc IssueClass(MsgIssueClass) returns (EmptyResponse);
  // Mint mints new non-fungible token in the class.
  rpc Mint(MsgMint) returns (EmptyResponse);
  // Burn burns the existing non-fungible token in the class.
  rpc Burn(MsgBurn) returns (EmptyResponse);
  // Freeze freezes an NFT
  rpc Freeze(MsgFreeze) returns (EmptyResponse);
  // Unfreeze removes the freeze effect already put on an NFT
  rpc Unfreeze(MsgUnfreeze) returns (EmptyResponse);
  // AddToWhitelist sets the account as whitelisted to hold the NFT
  rpc AddToWhitelist(MsgAddToWhitelist) returns (EmptyResponse);
  // RemoveFromWhitelist removes an account from whitelisted list of the NFT
  rpc RemoveFromWhitelist(MsgRemoveFromWhitelist) returns (EmptyResponse);
  // AddToClassWhitelist adds account as whitelist for all the NFTs in the class
  // NOTE: class whitelist does not affect the individual nft whitelisting.
  rpc AddToClassWhitelist(MsgAddToClassWhitelist) returns (EmptyResponse);
  // RemoveFromClassWhitelist removes account as whitelist for the entire class
  // NOTE:
  // class whitelist does not affect the individual nft whitelisting.
  // ie. if specific whitelist is granted for an NFT, that whitelist will
  // still be valid, ater we add and remove it from the class whitelist.
  rpc RemoveFromClassWhitelist(MsgRemoveFromClassWhitelist) returns (EmptyResponse);
  // ClassFreeze freezes all NFTs of a class held by an account.
  rpc ClassFreeze(MsgClassFreeze) returns (EmptyResponse);
  // ClassUnfreeze removes class-freeze on an account for an NFT class.
  // NOTE:
  // class unfreeze does not affect the individual nft freeze.
  rpc ClassUnfreeze(MsgClassUnfreeze) returns (EmptyResponse);
  // UpdateParams is a governance operation that sets the parameters of the module.
  // NOTE: all parameters must be provided.
  rpc UpdateParams(MsgUpdateParams) returns (EmptyResponse);
}
```

Maybe lets discuss after daily
___
*[`x/asset/nft/keeper/keeper.go` line 843 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaHJOn-rYh-UrLP1-4:-NvfONxbAiXFu5AFjy1d:b-hheoxt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L843)):*
ok, I'm ok to keep logic

> does your logic handles properly case when admin is owner of an item and tries to update data ? Do you have test for this

what about this ?
___
*[`x/asset/nft/keeper/keeper.go` line 1158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJ0AW6OsyMyMgsgNV:-NvfO_rW4hXCmAHpxzB-:bdzawsm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L1158)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's probably create the task to revise them and update? Since it's out of scope for that PR.
</blockquote></details>

i'm ok, pls add to backlog
___
*[`x/asset/nft/types/token.go` line 218 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaKd9K2n7JyF3cIkpk:-NvfOqFu8lqmKKuUHmyy:b-iznhz1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L218)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Fail fast is the best approach for the code, otherwise, the code will be complicated.
</blockquote></details>

for code yes 
but not always for user experience 


<!-- Sent from Reviewable.io -->

2024-04-17 11:21 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvfPGeU2HSKKh7HJtDI:-Nvfj5_sAf3FJEaCCLzm:b1mh3zc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/689a01dd2e2ece438a670d9d77caee05970a3225/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we have proto-breaking change ?
Or it is because some protos were merged to master before ?
</blockquote></details>

Right, because some protos were merged to master and now I change them.
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-NvfjCxv69Yv7cm5AJfA:b2w55ez) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes I'm not insisting to change it right away, but more to discuss

Because It is different from the convention we were following before

e.g: MsgMint, MsgBurn, MsgFreeze/MsgUnfreeze, MsgAddToWhitelist etc.
All of them don't mention NFT. We actually never mention it and for class we always do it
```
service Msg {
  // IssueClass creates new non-fungible token class.
  rpc IssueClass(MsgIssueClass) returns (EmptyResponse);
  // Mint mints new non-fungible token in the class.
  rpc Mint(MsgMint) returns (EmptyResponse);
  // Burn burns the existing non-fungible token in the class.
  rpc Burn(MsgBurn) returns (EmptyResponse);
  // Freeze freezes an NFT
  rpc Freeze(MsgFreeze) returns (EmptyResponse);
  // Unfreeze removes the freeze effect already put on an NFT
  rpc Unfreeze(MsgUnfreeze) returns (EmptyResponse);
  // AddToWhitelist sets the account as whitelisted to hold the NFT
  rpc AddToWhitelist(MsgAddToWhitelist) returns (EmptyResponse);
  // RemoveFromWhitelist removes an account from whitelisted list of the NFT
  rpc RemoveFromWhitelist(MsgRemoveFromWhitelist) returns (EmptyResponse);
  // AddToClassWhitelist adds account as whitelist for all the NFTs in the class
  // NOTE: class whitelist does not affect the individual nft whitelisting.
  rpc AddToClassWhitelist(MsgAddToClassWhitelist) returns (EmptyResponse);
  // RemoveFromClassWhitelist removes account as whitelist for the entire class
  // NOTE:
  // class whitelist does not affect the individual nft whitelisting.
  // ie. if specific whitelist is granted for an NFT, that whitelist will
  // still be valid, ater we add and remove it from the class whitelist.
  rpc RemoveFromClassWhitelist(MsgRemoveFromClassWhitelist) returns (EmptyResponse);
  // ClassFreeze freezes all NFTs of a class held by an account.
  rpc ClassFreeze(MsgClassFreeze) returns (EmptyResponse);
  // ClassUnfreeze removes class-freeze on an account for an NFT class.
  // NOTE:
  // class unfreeze does not affect the individual nft freeze.
  rpc ClassUnfreeze(MsgClassUnfreeze) returns (EmptyResponse);
  // UpdateParams is a governance operation that sets the parameters of the module.
  // NOTE: all parameters must be provided.
  rpc UpdateParams(MsgUpdateParams) returns (EmptyResponse);
}
```

Maybe lets discuss after daily
</blockquote></details>

Let's discuss today.
___
*[`x/asset/nft/keeper/keeper.go` line 843 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaHJOn-rYh-UrLP1-4:-Nvfjk00DwbD4f5JBWin:b-l04xd4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L843)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok, I'm ok to keep logic

> does your logic handles properly case when admin is owner of an item and tries to update data ? Do you have test for this

what about this ?
</blockquote></details>

Yes it handles it. Extended tests with `negative_admin_update_prohibited_item` test-case.
___
*[`x/asset/nft/keeper/keeper.go` line 1158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJ0AW6OsyMyMgsgNV:-NvfmRJX1WiepHsFjJOg:b-s51red) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/keeper/keeper.go#L1158)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

i'm ok, pls add to backlog
</blockquote></details>

https://app.clickup.com/t/86887d87j
___
*[`x/asset/nft/types/token.go` line 218 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaKd9K2n7JyF3cIkpk:-NvfmUep4afN5utwDGtm:b-gcalf1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31165f182645a7bd7cd0f28e464bda1a2ef6159a/x/asset/nft/types/token.go#L218)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

for code yes 
but not always for user experience
</blockquote></details>

IMO for that case we don't need it.


<!-- Sent from Reviewable.io -->

2024-04-17 12:14 UTC, miladz68 requested changes
> Reviewed 11 of 14 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/client/cli/tx.go` line 281 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWLgG0Eu11K5b-_IRN:-NvfxyNX4o3rpnfE6dfB:bg4uve9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L281)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

And what is the issue with it? Check the `DataDynamicIndexedItem` in contains the json tags.
</blockquote></details>

ordering of items is not guranteed in json. and most of the time, the proto files are generated programatically, it is only logical to use one encoding and not mix them. 
___
*[`x/asset/nft/keeper/keeper.go` line 1160 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWNwFPEFrWJDRGZDeu:-NvfyXle4-ZTAHM4Ee30:b6g1pxh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/keeper/keeper.go#L1160)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can duplicate that code. In the `isNFTSendable` and inside the update function, but IMO the current way is better.
</blockquote></details>

you see that is there only 1 check inside this function, so the abstraction is not adding much here. 


<!-- Sent from Reviewable.io -->

2024-04-17 15:32 UTC, ysv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-18 11:22 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/client/cli/tx.go` line 281 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWLgG0Eu11K5b-_IRN:-Nvkvm9v44aD0j2T70xM:bk7dt9n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/client/cli/tx.go#L281)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

ordering of items is not guranteed in json. and most of the time, the proto files are generated programatically, it is only logical to use one encoding and not mix them.
</blockquote></details>

 ```
ordering of items is not guranteed in json
```
1) Are you sure that `json` in go doesn't granatree this?
2) We don't care about the order since the `DataDynamicIndexedItem` contains int index.
```

___
*[`x/asset/nft/keeper/keeper.go` line 1160 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWNwFPEFrWJDRGZDeu:-NvkwT337C9hxbtrtxOq:bm3yqt3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/x/asset/nft/keeper/keeper.go#L1160)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you see that is there only 1 check inside this function, so the abstraction is not adding much here.
</blockquote></details>

OK, done.


<!-- Sent from Reviewable.io -->

2024-04-18 15:38 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-19 07:32 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-19 11:02 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`proto/coreum/asset/nft/v1/tx.proto` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvWOVEH4pDLCydHc9SV:-Nvq0RJ64CAusV0AnBbi:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/372f6595bfd6373148ee9df86ea443542f22f8d9/proto/coreum/asset/nft/v1/tx.proto#L83)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

discussed on call and decided to remove NFT suffix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-23 15:49 UTC, ysv approved these changes
> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-24 07:54 UTC, miladz68 approved these changes
> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/800)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-24 09:55 UTC, merged