Implmenet POC version of asset extensions
CoreumFoundation/coreum pull request #802
Opened 2024-04-11 10:01 UTC by miladz68

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2024-04-15 11:41 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 24 files reviewed, 13 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYJA40gtGHc2KHYpV:-NvWYJA53GcKYywU6iqG:b1euxy6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/go.mod#L8)):*
> ```XML
> 	// cosmos keyring
> 	github.com/99designs/keyring => github.com/cosmos/keyring v1.2.0
> 	github.com/CoreumFoundation/coreum/v4/integration-tests => ./integration-tests
> ```

IMO the dependency should be vice versa. The shared code/contract should belong to the coreum, otherwise it will lead to the circular dependency.
___
*[`integration-tests/contracts/modules/contract.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWZ-5602SHJLKBjxMH:-NvWZ-5602SHJLKBjxMI:b-hpadfr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/integration-tests/contracts/modules/contract.go#L24)):*
> ```Go
> 	AuthzStargateWASM []byte
> 	//go:embed asset-extension/artifacts/asset_extension.wasm
> 	AssetExtensionWasm []byte
> ```

What about the integration tests? Why they are not implemented?
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWTlm5EKwS-jKYDroV:-NvWTlm5EKwS-jKYDroW:bx7ormo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/proto/coreum/asset/ft/v1/tx.proto#L80)):*
> ```proto
>   // wasm_code_id must be provided in case you want to use wasm extensions.
>   // It is the code id of wasm byte code that is already uploaded by the issuer.
>   uint64 wasm_code_id = 12;
> ```

Just wasm code is not enough. You need the instantiation payload and funs. So probably extra type is better. For example
```
ExtensionSettings {
    code_id 
    label
    instantiation_payload
    instantiation_funds
}
```
___
*[`x/asset/ft/keeper/before_send.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWlZ_CSYUk6yJGX31:-NvWWlZ_CSYUk6yJGX32:bppuav6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L99)):*
> ```Go
> 			}
> 
> 			extenstionContract, err := sdk.AccAddressFromBech32(def.ExtensionCwAddress)
> ```

typo : extension
___
*[`x/asset/ft/keeper/before_send.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWfLCEg0wmjL1Q4NO:-NvWWfLCEg0wmjL1Q4NP:bya79cn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L109)):*
> ```Go
> 			// we first send accounts to module account and then attach funds with module account as
> 			// the caller of the smart contract.
> 			k.bankKeeper.SendCoins(ctx, sender, assetFTmoduleAddress, attachedFunds)
> ```

You don't handle error here!
___
*[`x/asset/ft/keeper/before_send.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWRHH0LlzFpM9HVfm:-NvWWRHH0LlzFpM9HVfn:b-pduzoa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L110)):*
> ```Go
> 			// the caller of the smart contract.
> 			k.bankKeeper.SendCoins(ctx, sender, assetFTmoduleAddress, attachedFunds)
> 			contractMsg := map[string]interface{}{
> ```

IMO, this should be moved to a struct. 
___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvWX2NZ3gxi_wn1XUBn:b724r7c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
> ```Go
> 				ctx,
> 				extenstionContract,
> 				assetFTmoduleAddress,
> ```

Why can't we use `sender` as `caller` ?
___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-NvWXXEeBAJCysa5UW9Q:b30nw2m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
> ```Go
> 				attachedFunds,
> 			)
> 			if err != nil {
> ```

You must wrap it into specific error type, otherwise it won't be possible to distinguish the error. And add the error type check in the test. 
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYQAs9KEJq_IpmIRs:-NvWYQAs9KEJq_IpmIRt:b-wy40ev) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
> ```Go
> }
> 
> func TestApplyRate(t *testing.T) {
> ```

Why haven't you extended the tests with the `extentions` ?
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYVJF0l8QwO-gApIp:-NvWYVJF0l8QwO-gApIq:bg3w6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
> ```Go
> }
> 
> func TestApplyRate(t *testing.T) {
> ```

How does the extensions behave with the freezing/whitelisting ?
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-NvWVdbi2m4-8LRFPzZY:btkyfev) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
> ```Go
> 			settings.WasmCodeID,
> 			settings.Issuer,
> 			assetFTModuleAddress,
> ```

Could you please explain why - `admin` is `assetFTModuleAddress ` ?
___
*[`x/asset/ft/keeper/keeper.go` line 242 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVFx60Mx0Nx1SQBKF:-NvWVFx60Mx0Nx1SQBKG:b-j57suz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L242)):*
> ```Go
> 			[]byte("{}"),
> 			"",
> 			sdk.NewCoins(),
> ```

As we discussed before, all those args (should be passed in the MsgIssue). 



_Code quote:_
```Go
			[]byte("{}"),
			"",
			sdk.NewCoins(),
```
___
*[`x/asset/ft/keeper/keeper.go` line 244 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVoQJ40QkMdWt1F4z:-NvWVoQJ40QkMdWt1F5-:b3yvyr5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L244)):*
> ```Go
> 			sdk.NewCoins(),
> 			ctx.BlockHeader().AppHash,
> 			true,
> ```

nit: Could you please exmpain why it's true here.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 47 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYoHx4q14QIOZwjur:-NvWYoHx4q14QIOZwjus:b-ypkfpo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper_extension_test.go#L47)):*
> ```Go
> 		Features:      []types.Feature{types.Feature_extensions},
> 		URI:           "https://my-class-meta.invalid/1",
> 		URIHash:       "content-hash",
> ```

nit: If you don't need it, you might not fill it. 



_Code quote:_
```Go
		URI:           "https://my-class-meta.invalid/1",
		URIHash:       "content-hash",
```


<!-- Sent from Reviewable.io -->

2024-04-16 11:03 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 24 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYJA40gtGHc2KHYpV:-NvaQKbv3e6Qfxp60lwl:bc26h4k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/go.mod#L8)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO the dependency should be vice versa. The shared code/contract should belong to the coreum, otherwise it will lead to the circular dependency.
</blockquote></details>

let's discuss it in call. 
___
*[`integration-tests/contracts/modules/contract.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWZ-5602SHJLKBjxMH:-NvaQUbd2Sisej8FpCRf:bogn25v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/integration-tests/contracts/modules/contract.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the integration tests? Why they are not implemented?
</blockquote></details>

This is meant as POC to show how the extensions will look like. I will add the integration tests as part of the PR if we agree on the design. 
___
*[`x/asset/ft/keeper/before_send.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWlZ_CSYUk6yJGX31:-NvaRJBC4OiZ3XKNZ3cm:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

typo : extension
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/before_send.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWfLCEg0wmjL1Q4NO:-NvaRSnGActnmWpyulMv:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L109)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't handle error here!
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWRHH0LlzFpM9HVfm:-NvaRUx-DNdWSE7BSuAY:b2kle7r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L110)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO, this should be moved to a struct.
</blockquote></details>

It only adds unnecessary clutter. 
___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvaReyU-cVE-uKmT-_F:bxt8nz6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why can't we use `sender` as `caller` ?
</blockquote></details>

We can, but the smart contract might be interested in limiting access to this function to the module itself. Another idea is to pass sender as caller and convert the smart contract entry point to a sudo entry point.
We should probably discuss. 
___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-NvaWlFk-5N-hD71ozGb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You must wrap it into specific error type, otherwise it won't be possible to distinguish the error. And add the error type check in the test.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYQAs9KEJq_IpmIRs:-NvaXRxX05lvtv3p1ZWi:b1ndm94) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why haven't you extended the tests with the `extentions` ?
</blockquote></details>

we will need the complete feature to be implemented by the smart contract so those tests will be applicable. 
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYVJF0l8QwO-gApIp:-NvaXe39DahHSygUKrSZ:b-6saf7j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How does the extensions behave with the freezing/whitelisting ?
</blockquote></details>

that is not yet implemented. as of now those are just ignored. 
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-NvaXmRO7SwzINIH8D98:b-mi57ae) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why - `admin` is `assetFTModuleAddress ` ?
</blockquote></details>

we do not want to allow wasm migration as it was discussed earlier, unless we decide otherwise. 
___
*[`x/asset/ft/keeper/keeper.go` line 244 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVoQJ40QkMdWt1F4z:-NvaY-f4-Nre4sx7ESzJ:bh78bmn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L244)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: Could you please exmpain why it's true here.
</blockquote></details>

It passes the message as part of contract instanstiation to add more randomness to address generation. 
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 47 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYoHx4q14QIOZwjur:-NvaYEpc6fmiMY4nAzy2:bx7479s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper_extension_test.go#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: If you don't need it, you might not fill it.
</blockquote></details>

Done and removed. 


<!-- Sent from Reviewable.io -->

2024-04-16 11:22 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 25 files reviewed, 11 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYJA40gtGHc2KHYpV:-NvaaZSw-YklDRR-iMiW:b2nhktp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/go.mod#L8)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss it in call.
</blockquote></details>

OK.
___
*[`integration-tests/contracts/modules/contract.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWZ-5602SHJLKBjxMH:-NvaacZiEdDy53prbFTQ:b-1bdmrn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/integration-tests/contracts/modules/contract.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is meant as POC to show how the extensions will look like. I will add the integration tests as part of the PR if we agree on the design.
</blockquote></details>

OK, keeping until it's done.
___
*[`x/asset/ft/keeper/before_send.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWRHH0LlzFpM9HVfm:-NvaajtpCRlxNdCNRvPp:b-cc6r1y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L110)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It only adds unnecessary clutter.
</blockquote></details>

Actually - not. Why don't we use the maps in the integration tests when interacting with the smart contracts then? 
Also, you will be able to reuse it when trying to call the smart contract directly from the user, IMO such a test is required as well. 
___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvabfXW6apgdmI2k5ov:b-5d4sba) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

We can, but the smart contract might be interested in limiting access to this function to the module itself. Another idea is to pass sender as caller and convert the smart contract entry point to a sudo entry point.
We should probably discuss.
</blockquote></details>

OK, let's discuss, but why do we need to limit it? Anyone can call that func attaching the funds, isn't it?
___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-NvadABJC8GwCM5hiBK5:b-7gw8bj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Incorrect way of wrapping. Use `sdkerrors.Wrapf()`.
___
*[`x/asset/ft/keeper/before_send.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvabNbI21KpwnwzXwsq:-NvabNbI21KpwnwzXwsr:bwqmty1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e63ee763b081780f2e21cd39a13385c5a402e4df/x/asset/ft/keeper/before_send.go#L114)):*
> ```Go
> 			}
> 			contractMsg := map[string]interface{}{
> 				"transfer": map[string]interface{}{
> ```

It's required to have a test when you call that func (of smart contract) directly from user.
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYQAs9KEJq_IpmIRs:-NvacGnC6iUgb2e5tqvQ:b-nym8oq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we will need the complete feature to be implemented by the smart contract so those tests will be applicable.
</blockquote></details>

And what is left, which might change the current `ApplyRate` logic?
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYVJF0l8QwO-gApIp:-NvacNCl-RJ_lrc8Ei67:bbnc7w9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that is not yet implemented. as of now those are just ignored.
</blockquote></details>

WDYM `yet`, when are you going to implement it?
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-NvacoJB1OTVfTQ1zlFA:b-2oc2vb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we do not want to allow wasm migration as it was discussed earlier, unless we decide otherwise.
</blockquote></details>

We agreed to allow the migration. And that was discussed last time. If the issuer wants to remove it he/she can do it using the wasm Msg. 


<!-- Sent from Reviewable.io -->

2024-04-16 11:45 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 25 files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-Nvage1KBSXbbU3lZTfT:bxb3of8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK, let's discuss, but why do we need to limit it? Anyone can call that func attaching the funds, isn't it?
</blockquote></details>

It is more logical for that entry point to be limited via sudo, which gurantees that it is comming from the module. the contract can introduce a separate entry point to normal users if they wish. keeping them separated is logical and gives more control to the user. 
___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-NvahIbs0oZAOwGtlfnF:b4xyj1n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Incorrect way of wrapping. Use `sdkerrors.Wrapf()`.
</blockquote></details>

they are the same function call under the hood. 
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYQAs9KEJq_IpmIRs:-NvahPMO9nnP37k7aIWt:b-coco0h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

And what is left, which might change the current `ApplyRate` logic?
</blockquote></details>

the extension is meant to circumvent the enforcements, so for this test to be still valid, calculation and application rates must be done in smart contract, otherwise the tests will fail. 
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYVJF0l8QwO-gApIp:-NvahokTC1vYZHM3iy03:b-hnd43c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

WDYM `yet`, when are you going to implement it?
</blockquote></details>

there are tasks in the backlog, those implementations must be done as part of the sample smart contract, as far as the module is concerned, the freezing and whitelisting are ignored. 
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-Nvai63_74ppSKNxDiXN:b-i58t3a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We agreed to allow the migration. And that was discussed last time. If the issuer wants to remove it he/she can do it using the wasm Msg.
</blockquote></details>

we did not agree, you mentioned it and we said it must be discussed further. In earlier discussions it was decided to have a feature to enable it, so if we are to change that decision we need to discuss it with Reza one more time. 


<!-- Sent from Reviewable.io -->

2024-04-16 11:50 UTC, masihyeganeh requested changes
It really looks good to me, but @dzmitryhil mentioned some good points

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-:-NvajW0C7bD-XoPGnRdt:b71qidp)* status: 0 of 25 files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/asset-extension/Cargo.toml` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvajI4Q0sBRFdpiDgR_:-NvajI4Q0sBRFdpiDgRa:b-qrlixy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/integration-tests/contracts/modules/asset-extension/Cargo.toml#L34)):*
> ```TOML
> cosmwasm-storage = "1.2.5"
> cw2 = "1.0.1"
> thiserror = { version = "1.0.40" }
> ```

nit: You can use the short version instead of the object
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvaiyCrDcYwbXFI316F:-NvaiyCrDcYwbXFI316G:bwclal2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper_extension_test.go#L35)):*
> ```Go
> 	addr := sdk.AccAddress(ed25519.GenPrivKey().PubKey().Address())
> 
> 	codeID, _, err := testApp.WasmGovPermissionKeeper.Create(ctx, addr, moduleswasm.AssetExtensionWasm, &wasmtypes.AllowEverybody)
> ```

Isn't it better to embed AssetExtensionWasm here instead of importing it? This can prevent importing the integration-tests


<!-- Sent from Reviewable.io -->

2024-04-17 10:53 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 25 files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWTlm5EKwS-jKYDroV:-Nvf2f2r6SRuQW0Zma_n:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/proto/coreum/asset/ft/v1/tx.proto#L80)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Just wasm code is not enough. You need the instantiation payload and funs. So probably extra type is better. For example
```
ExtensionSettings {
    code_id 
    label
    instantiation_payload
    instantiation_funds
}
```
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWWRHH0LlzFpM9HVfm:-NvfGhqN3pWtJOjmFZ8j:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L110)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually - not. Why don't we use the maps in the integration tests when interacting with the smart contracts then? 
Also, you will be able to reuse it when trying to call the smart contract directly from the user, IMO such a test is required as well.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvfGkK44ViC2HGlM53X:b-gpj45k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is more logical for that entry point to be limited via sudo, which gurantees that it is comming from the module. the contract can introduce a separate entry point to normal users if they wish. keeping them separated is logical and gives more control to the user.
</blockquote></details>

I tried sudo but it does not allow to attach funds, so we have to use normal execute. 
___
*[`x/asset/ft/keeper/keeper.go` line 242 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVFx60Mx0Nx1SQBKF:-NvfePq53JPSuWN3_NSe:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L242)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As we discussed before, all those args (should be passed in the MsgIssue).
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvaiyCrDcYwbXFI316F:-NvffK0q-rkKYMiQGD0_:b-sne22j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper_extension_test.go#L35)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Isn't it better to embed AssetExtensionWasm here instead of importing it? This can prevent importing the integration-tests
</blockquote></details>

we will discuss it in the team. 


<!-- Sent from Reviewable.io -->

2024-04-17 11:33 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 26 files reviewed, 11 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 85 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvfnjDC1J79uuYqGXmM:-NvfnjDC1J79uuYqGXmN:bvwzltx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2bb76f7953e5cff2a1428a85d2b2b4233406c1dc/proto/coreum/asset/ft/v1/tx.proto#L85)):*
> ```proto
>   // code_id is the reference to the stored WASM code
>   uint64 code_id = 1;
>   // Label is optional metadata to be stored with a contract instance.
> ```

nit:  `Label`, `Msg json`, `Funds coins` comments start with capital, but all other with lower-case. 
___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvfoSm_14Ecg51dm8k4:b-q6g7ms) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I tried sudo but it does not allow to attach funds, so we have to use normal execute.
</blockquote></details>

OK, let's discuss this with the team.
___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-NvfofVB9687loHJitu-:b-567y9v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

they are the same function call under the hood.
</blockquote></details>

The `sdkerrors.Wrapf()` keeps the original error as parent, but here you loose it.
___
*[`x/asset/ft/keeper/before_send.go` line 167 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvfoK8-5-p1fpKpZKpI:-NvfoK8-5-p1fpKpZKpJ:bzfzwu3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2bb76f7953e5cff2a1428a85d2b2b4233406c1dc/x/asset/ft/keeper/before_send.go#L167)):*
> ```Go
> 	}
> 	contractMsg := map[string]interface{}{
> 		"extension_transfer": ExtensionTransferMsg{
> ```

nit: Better to move to a constant IMO.
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYQAs9KEJq_IpmIRs:-NvfoqloCPjspx0m1Vhe:b-tkvbp0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the extension is meant to circumvent the enforcements, so for this test to be still valid, calculation and application rates must be done in smart contract, otherwise the tests will fail.
</blockquote></details>

Let's discuss this with the team.
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYVJF0l8QwO-gApIp:-Nvfow3E90GNELXZ6t7r:b6fhn6c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

there are tasks in the backlog, those implementations must be done as part of the sample smart contract, as far as the module is concerned, the freezing and whitelisting are ignored.
</blockquote></details>

Let's discuss this with the team. 
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-Nvfp1Sp8kx9vXdBmYkG:b-kdanex) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we did not agree, you mentioned it and we said it must be discussed further. In earlier discussions it was decided to have a feature to enable it, so if we are to change that decision we need to discuss it with Reza one more time.
</blockquote></details>

I remember it differently :-)
Ok, let's discuss this with the team one more time.


<!-- Sent from Reviewable.io -->

2024-04-17 12:03 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 26 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-Nvftq-NBMdp9UEUsxCE:bquz67s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `sdkerrors.Wrapf()` keeps the original error as parent, but here you loose it.
</blockquote></details>

It calls the same method under the hood so it should not be different ! 


<!-- Sent from Reviewable.io -->

2024-04-17 14:05 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 0 of 26 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYJA40gtGHc2KHYpV:-NvgFrQEEci0ZjSlVTG1:bmex7rv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/go.mod#L8)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

move this one contract to keeper
___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvgJYioD7iDhqy3DVTX:b1cyyk2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK, let's discuss this with the team.
</blockquote></details>

it was decided to pass the original sender not the module address.
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-NvgMf2c2Vjrk5gIXvcy:bpvc3m8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I remember it differently :-)
Ok, let's discuss this with the team one more time.
</blockquote></details>

make the issuer the admin of the contract and let them decided to upgrade/remove admin later.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvaiyCrDcYwbXFI316F:-NvgN2SYEhRGijv4LGvF:b-n59b7t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper_extension_test.go#L35)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we will discuss it in the team.
</blockquote></details>

discussed above.


<!-- Sent from Reviewable.io -->

2024-04-18 11:26 UTC, dzmitryhil reviewed
> Reviewed 11 of 24 files at r1, 1 of 3 files at r2, 5 of 9 files at r3, 4 of 5 files at r4, 3 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 9 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-19 08:40 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 24 of 26 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWX2NZ3gxi_wn1XUBm:-NvpRobC7rOiKrUyw7L3:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L124)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it was decided to pass the original sender not the module address.
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYQAs9KEJq_IpmIRs:-NvpRtr6A8ruOhTRE_UI:bcgk4xz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss this with the team.
</blockquote></details>

It was decided to test each feature in its own feature task.
___
*[`x/asset/ft/keeper/before_send_test.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWYVJF0l8QwO-gApIp:-NvpS0Np3aS3WfvLX8_s:bcgk4xz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send_test.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss this with the team.
</blockquote></details>

It was decided to test each feature in its own feature task.
___
*[`x/asset/ft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWVdbi2m4-8LRFPzZX:-NvpSDiy2zAM8AzrhX_d:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

make the issuer the admin of the contract and let them decided to upgrade/remove admin later.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 11:55 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 24 of 26 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/contract.go` line 24 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWZ-5602SHJLKBjxMH:-NvqBtgw-uzUdDv5_vUs:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/integration-tests/contracts/modules/contract.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK, keeping until it's done.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvWXXEeBAJCysa5UW9P:-NvqC56m4qBcyhbL9syj:b-xn2ppl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f824615bbffeb7d0a0715dc602419bc8ee9dd1e8/x/asset/ft/keeper/before_send.go#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/6096171/xa5vs3ow_65bzERnSGBvvanE/image.png)
Probably I don't understand you, but see it calls the `Wrap` which keeps the error.
</blockquote></details>

I see what you mean, but look at the internals of `types.ErrExtensionCallFailed.Wrapf`, it just calls Wrapf under the hood, so it also keeps the underlying error. 
___
*[`x/asset/ft/keeper/before_send.go` line 114 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvabNbI21KpwnwzXwsq:-NvqBuZV3zZTVmEdx3qd:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e63ee763b081780f2e21cd39a13385c5a402e4df/x/asset/ft/keeper/before_send.go#L114)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's required to have a test when you call that func (of smart contract) directly from user.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 13:07 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 10 of 30 files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqQedC9fHKKxRxltAp:-NvqQedC9fHKKxRxltAq:b-l4lt5b) (no related file):*
Fix CI, please. The tests are failed.

___
___
*[`integration-tests/contracts/modules/contract.go` line 1 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqROQ_8tiF-vAf00U8:-NvqROQ_8tiF-vAf00U9:bm2g2tx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/integration-tests/contracts/modules/contract.go#L1)):*
> ```Go
> package modules
> ```

You can return `//go:build integrationtests`  
___
*[`x/asset/ft/keeper/before_send.go` line 150 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqPI2F1Zp0-olP-juH:-NvqPI2F1Zp0-olP-juI:b-o4u454) ([raw file](https://github.com/CoreumFoundation/coreum/blob/145aa2de25db9b066ce7cf23e51c46bd82f98cdf/x/asset/ft/keeper/before_send.go#L150)):*
> ```Go
> 	outOps accountOperationMap,
> ) error {
> 	assetFTmoduleAddress := authtypes.NewModuleAddress(types.ModuleName)
> ```

nit: recursion



_Code quote:_
```Go
recursoin
```
___
*[`x/asset/ft/keeper/before_send.go` line 152 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqPaxm-pRpxkeezwze:-NvqPaxm-pRpxkeezwzf:bjqb782) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/x/asset/ft/keeper/before_send.go#L152)):*
> ```Go
> 	// then we will end up in an infinite recursoin.
> 	_, isReceiverExtensionContract := outOps[def.ExtensionCwAddress]
> 	if isReceiverExtensionContract && len(outOps) == 1 {
> ```

So if I send to smart contract directly that interceptor won't work? If yes IMO we need to make something similar to IBC, to handle it. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 37 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqRahx1M310k8plgXp:-NvqRahx1M310k8plgXq:bjbbb36) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L37)):*
> ```XML
>     match msg {
>         ExecuteMsg::ExtensionTransfer { amount, recipients } => {
>             execute_extension_transfer(deps, env, info, amount, recipients)
> ```

We also need to add a test when we send coins from the smart contract (an additional method that accepts the recipient and amount). And test sending from contract to: user, another not extension contract, extension contract.

Also, we need tests with the IBC and smart contracts, where the contract is sender and recipient (that is under discussion). 


<!-- Sent from Reviewable.io -->

2024-04-22 10:42 UTC, masihyeganeh approved these changes
> Reviewed 16 of 20 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-23 08:30 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 27 of 30 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqQedC9fHKKxRxltAp:-Nw93jIW3Wd-eGB8bTPe:b-896fix) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Fix CI, please. The tests are failed.
</blockquote></details>

Done.

___
___
*[`x/asset/ft/keeper/before_send.go` line 152 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqPaxm-pRpxkeezwze:-NvqY38r14x0PW94YigA:boji70k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/x/asset/ft/keeper/before_send.go#L152)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So if I send to smart contract directly that interceptor won't work? If yes IMO we need to make something similar to IBC, to handle it.
</blockquote></details>

It will work, do you see a problem with it ?
___
*[`integration-tests/contracts/modules/contract.go` line 1 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqROQ_8tiF-vAf00U8:-Nw8eH_QAb2JtvteRlXY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/integration-tests/contracts/modules/contract.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can return `//go:build integrationtests`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 37 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqRahx1M310k8plgXp:-Nw93lyxDRK8HuBTtZVf:b-w0wlyq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We also need to add a test when we send coins from the smart contract (an additional method that accepts the recipient and amount). And test sending from contract to: user, another not extension contract, extension contract.

Also, we need tests with the IBC and smart contracts, where the contract is sender and recipient (that is under discussion).
</blockquote></details>

These tests will be part of the next PR, they are not as simple and they seem, they need a complete rewrite of our interceptor logic. 


<!-- Sent from Reviewable.io -->

2024-04-23 11:25 UTC, dzmitryhil reviewed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 4 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-23 11:44 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 152 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqPaxm-pRpxkeezwze:-Nw9e28kD-Gx8iOycHPO:b-gxkp3d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/x/asset/ft/keeper/before_send.go#L152)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It will work, do you see a problem with it ?
</blockquote></details>

Leave a FIXME to cover potential pitfals to be covered in future tasks.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 37 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NvqRahx1M310k8plgXp:-Nw9eD7hBzlOfQf5c4Dg:bw6i1xf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f180c4eab0bafe9ccde392a0f804d4cff2d6f6df/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L37)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

These tests will be part of the next PR, they are not as simple and they seem, they need a complete rewrite of our interceptor logic.
</blockquote></details>

Dicussed in call and mentioned the solution above. 


<!-- Sent from Reviewable.io -->

2024-04-23 11:44 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-23 13:44 UTC, dzmitryhil approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-29 09:01 UTC, dzmitryhil approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-30 08:21 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 11 of 33 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 276 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdQtZQ2Ta9JCOcZp0v:-NweY1hn-AR8GX-Cu_IT:b8lw3zl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/app/app.go#L276)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: needs explanation
</blockquote></details>

I don't think it does, it is just another keeper, we don't explain all the keepers, only the ones that we have modified. And we have not modified this one. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 35 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdT_0CER145nrZoE1V:-NweYOvn9A6UIzeVf1t8:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/integration-tests/modules/assetft_extension_test.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: 1_000_000
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/token.proto` line 17 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdRwLODF5IaUfLKZri:-NweWDlk4WhqtHS85cN4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/proto/coreum/asset/ft/v1/token.proto#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should this feature be named in singular or plural form ?
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 82 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdPQPC9E9HerwX9f60:-NweWnQV0ljEdoQkaZ8g:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/proto/coreum/asset/ft/v1/tx.proto#L82)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: needs explanation
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 19 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdPUWj9449ywxwZzqE:-NweWlluCqtOA4dy-HJ3:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/before_send.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: needs explanation
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 101 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdPaDY3IS7j646r_si:-NweWoqh1fniUONGGF3j:b-zatek8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/before_send.go#L101)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: minor but call seems to be better word here instead of execute
Also I would skip Asset since you are already inside asset/ft pkg

So final version I propose is: callExtension
</blockquote></details>

renamed to invokeAssetExtension, to be closer the name used in the wasm module
___
*[`x/asset/ft/keeper/before_send.go` line 106 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdQ7ch-mTN8Ro3aJ97:-NweX0bn8Jc3L1lBOmmG:bhoba4l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/before_send.go#L106)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: needs explanation
</blockquote></details>

the comment already exists! maybe u mean somewhere else ?
___
*[`x/asset/ft/keeper/before_send.go` line 139 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdQNtK3TRS7DGRVYbV:-NweXWOz9nBlm9ld1nEu:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/before_send.go#L139)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: needs explanation
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 253 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdRNoO3HronTESI0nx:-NweXn516kSIVitnlif4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/keeper.go#L253)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think it should be `ExtensionCWAddress` (CW)
Can we define this acronym in protos ?
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 60 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdS2l9BCXaojgHscnL:-NweYSv-93anJfKOzlFp:bkx52xj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/keeper_extension_test.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I don't like much such a long check. Do we have this code duplicated somewhere else ?
Shall we move it to some helper func ? Or maybe shorten it somehow ?
</blockquote></details>

we don't have it duplicated anywhere. we can shorten it by using reflection, and write a function that compares every field but ignores some of the fields, but seems like an overkill for this single check. 
___
*[`x/asset/ft/keeper/msg_server.go` line 62 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdSW-50-DuJnsrjeZG:-NweYpgW5Xu3BrTQFkXh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/msg_server.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: is it extension settings which you use in multiple places or u just need it for issuance ?
If you use it only for issuance then probably smth like: ExtensionIssueSettings is better ?
</blockquote></details>

Done.
___
*[`x/asset/ft/types/errors.go` line 25 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdTDj_4RVBy0JVv67d:-NweZKl031f10IXx0hRu:bmfmxap) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/types/errors.go#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

another thing which would be nice to test/see is the way events are produced when you call extension.
Maybe we can add todo for this ?
</blockquote></details>

I will add a task to discuss it later
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 1 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdT5UU1wYaFeDlrPYH:-NweZDe-AZcBsRUWt7GR:b-85tekt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does this contract needs any review from Keyne ?
</blockquote></details>

I don't think it does, it is a super simple prototype. 


<!-- Sent from Reviewable.io -->

2024-04-30 09:48 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 10 of 33 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 276 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdQtZQ2Ta9JCOcZp0v:-NwiKflFBtfngKI4il51:boefn2v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/app/app.go#L276)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think it does, it is just another keeper, we don't explain all the keepers, only the ones that we have modified. And we have not modified this one.
</blockquote></details>

Rename
WasmGovPermissionKeeper -> WasmPermissionedKeeper
___
*[`x/asset/ft/keeper/before_send.go` line 85 at r15](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiLPdaDHqVizHP5gJ9:-NwiLPdaDHqVizHP5gJA:b-dsv1m7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/367abdb50eedc361df5218a417fb956184c2c847/x/asset/ft/keeper/before_send.go#L85)):*
> ```Go
> 					return err
> 				}
> 				// We will not enforce any policies if the token has extensions. It is up to the contract
> ```

give more examples for what you mean by policies. also mention that we don't do the transfers for bank or rates. 
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 60 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdS2l9BCXaojgHscnL:-NwiLwIBBHTBSR2nihR8:b-ojpm9o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/keeper_extension_test.go#L60)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we don't have it duplicated anywhere. we can shorten it by using reflection, and write a function that compares every field but ignores some of the fields, but seems like an overkill for this single check.
</blockquote></details>

decided to keep it.


<!-- Sent from Reviewable.io -->

2024-04-30 10:22 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 10 of 33 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 106 at r13](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwdQ7ch-mTN8Ro3aJ97:-NwiR4_g92fB_xo0JVLu:b-7q8eo9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6eb875cd723d8cd68d456666fdab33134f575d93/x/asset/ft/keeper/before_send.go#L106)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the comment already exists! maybe u mean somewhere else ?
</blockquote></details>

added more info to the comment.


<!-- Sent from Reviewable.io -->

2024-04-30 10:33 UTC, ysv requested changes
> Reviewed 11 of 22 files at r14, 3 of 11 files at r15, 6 of 8 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/before_send.go` line 223 at r12](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiViXQ-ASbG7901TQq:-NwiViXQ-ASbG7901TQr:b8lknbh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d8f4d0c4450a58f5a694536156693bc16c78835c/x/asset/ft/keeper/before_send.go#L223)):*
> ```Go
> 		return sdk.ZeroInt()
> 	}
> 	// Since burning & send commissions are not applied when sending to/from token issuer or from any smart contract,
> ```

I still think this comment is useful.
Maybe it make sense to preserve it in some other place ?
___
*[`x/asset/ft/keeper/keeper.go` line 30 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiY14-5kEuZalSWOu3:-NwiY14-5kEuZalSWOu4:b-w45e8g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L30)):*
> ```Go
> // The contract must be able to properly process this message.
> type ExtensionInstantiateMsg struct {
> 	Denom string `json:"denom"`
> ```

AFAIK contract instantiation and attachment happens on asset issuance, right ?

IMO It should not be possible to attach existing contract to new asset ft.
I meant if contract is attached to one denom then it is not possible to issue another denom and attach the same contract
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiWOj_47PIbRlMdUS1:-NwiWOj_47PIbRlMdUS2:b4sgg1h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
> ```XML
>     recipient: String,
> ) -> Result<Response, ContractError> {
>     // TODO remove this if statement.
> ```

don't you think that contract has to receive coin (not amount Unit128)
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiXYsZ9RK_16kYQmsp:-NwiXYsZ9RK_16kYQmsq:be2wz9k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
> ```XML
>     recipient: String,
> ) -> Result<Response, ContractError> {
>     // TODO remove this if statement.
> ```

should it be rule for contract to verify denom before executing extension ?
Because in this specific case we want to apply this rule only for specific denom but not to anything.
The problem is that in other cases users might benefit from sending another denom than expected one.


<!-- Sent from Reviewable.io -->

2024-04-30 10:41 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 223 at r12](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiViXQ-ASbG7901TQq:-Nwi_zLX6dweH_5M80YW:beplwt9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d8f4d0c4450a58f5a694536156693bc16c78835c/x/asset/ft/keeper/before_send.go#L223)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I still think this comment is useful.
Maybe it make sense to preserve it in some other place ?
</blockquote></details>

what comment you mean ?
___
*[`x/asset/ft/keeper/keeper.go` line 30 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiY14-5kEuZalSWOu3:-NwiZs8K4VX8K8BoHKIA:b2n0vrr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

AFAIK contract instantiation and attachment happens on asset issuance, right ?

IMO It should not be possible to attach existing contract to new asset ft.
I meant if contract is attached to one denom then it is not possible to issue another denom and attach the same contract
</blockquote></details>

it works as you described, the instantiation and attachment happens in the Issue method, so the users cannot attach smart contracts that they instantiated themselves to the contract. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiWOj_47PIbRlMdUS1:-Nwi_4shDc7zwaCO8PAe:b-ordh2z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

don't you think that contract has to receive coin (not amount Unit128)
</blockquote></details>

the denom is fixed, and will be passed to the contract at instantiation, passing it again is duplication. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiXYsZ9RK_16kYQmsp:-Nwi_QsQ4U0KmwJL4uHt:bep0qfv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should it be rule for contract to verify denom before executing extension ?
Because in this specific case we want to apply this rule only for specific denom but not to anything.
The problem is that in other cases users might benefit from sending another denom than expected one.
</blockquote></details>

the contract developer can have other methods to cover those use cases, but the extension_transfer is only responsible to analyze a single token that it was assigned to at instantiation. 


<!-- Sent from Reviewable.io -->

2024-04-30 11:03 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 7 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send_test.go` line 90 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwibyCi-cDIhnYvKCHZ:-NwibyCi-cDIhnYvKCH_:b-gpaj4j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/before_send_test.go#L90)):*
> ```Go
> 			appliedRate: sdkmath.NewInt(101),
> 		},
> ```

nit: no needed empty line
___
*[`x/asset/ft/keeper/keeper.go` line 263 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-Nwie8ya89vuqRe2vjYz:-Nwie8ybEB_UhNanB4zg:b-bk6c0y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L263)):*
> ```Go
> 			instantiateMsgBytes,
> 			settings.ExtensionSettings.Label,
> 			settings.ExtensionSettings.Funds,
> ```

* Do transfer the funds to the contract at the time of the instantiation?
*  Should we prevent the attachment of the funds at the time of the instantiation of the newly issued token?
___
*[`x/asset/ft/keeper/keeper_test.go` line 805 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiemEv4Fneql6HLGF3:-NwiemEv4Fneql6HLGF4:bvvcimo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper_test.go#L805)):*
> ```Go
> 			distribution: map[string]map[*sdk.AccAddress]int64{
> 				denoms[0]: {
> 					&issuers[0]:    819, // 800 + 15 + 4 (5% commission)
> ```

Why did you change this?


<!-- Sent from Reviewable.io -->

2024-04-30 11:22 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send_test.go` line 90 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwibyCi-cDIhnYvKCHZ:-NwiiYDO0QIDLJWdQ2Kc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/before_send_test.go#L90)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: no needed empty line
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 263 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-Nwie8ya89vuqRe2vjYz:-Nwiiem8EGqg0OBaIJUf:b-rl4hkk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L263)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

* Do transfer the funds to the contract at the time of the instantiation?
*  Should we prevent the attachment of the funds at the time of the instantiation of the newly issued token?
</blockquote></details>

Yes, we do the transfer at the time of instantiation, if the user provides some tokens. it is up to the instantiator to decided if they wish to transfer some funds or not, there is not reason to block it. 
___
*[`x/asset/ft/keeper/keeper_test.go` line 805 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiemEv4Fneql6HLGF3:-Nwij7Qp3Weg1sGjx9TV:b-y0urif) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper_test.go#L805)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why did you change this?
</blockquote></details>

in the past, the calculations were done wholistically, i.e if you transfer 10 and 5, the rates were applied on the sum of them which is 15, now the rate is applied once for 10 and once for 5, as if they are separate transfers. this means that if there are rounding errors, they will be calculated per transfer. 


<!-- Sent from Reviewable.io -->

2024-04-30 11:41 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 32 of 33 files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 263 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-Nwie8ya89vuqRe2vjYz:-Nwin9HAE6CZEqlS9-xs:b-hrkmst) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L263)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Yes, we do the transfer at the time of instantiation, if the user provides some tokens. it is up to the instantiator to decided if they wish to transfer some funds or not, there is not reason to block it.
</blockquote></details>

* We need the integration test for it, could you please add TODO somewhere same for the label
* But can the transfer of the token at the time of the instantiation call the extension? And is it safe?


<!-- Sent from Reviewable.io -->

2024-04-30 11:42 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 32 of 33 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 263 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-Nwie8ya89vuqRe2vjYz:-Nwinqc76IsccGElUy3J:b6wjmk7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L263)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

* We need the integration test for it, could you please add TODO somewhere same for the label
* But can the transfer of the token at the time of the instantiation call the extension? And is it safe?
</blockquote></details>

It won't call the extension, since there is an if statement so the extension is not executed. 
I will add the todo.


<!-- Sent from Reviewable.io -->

2024-04-30 11:53 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 31 of 33 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 263 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-Nwie8ya89vuqRe2vjYz:-NwiqXBB4Sjyrp-qG8Di:b-iyts54) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/keeper.go#L263)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It won't call the extension, since there is an if statement so the extension is not executed. 
I will add the todo.
</blockquote></details>

I added the tests instead of the todo. 


<!-- Sent from Reviewable.io -->

2024-04-30 11:53 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 31 of 33 files reviewed, 4 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-30 12:46 UTC, ysv requested changes
> Reviewed 1 of 1 files at r18, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiWOj_47PIbRlMdUS1:-Nwj-f_Y5722lUznq3ni:b6lc6cg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the denom is fixed, and will be passed to the contract at instantiation, passing it again is duplication.
</blockquote></details>

mentioned it now
clear
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiXYsZ9RK_16kYQmsp:-Nwj1WgJ7v01b5WhCY1G:besjcyy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the contract developer can have other methods to cover those use cases, but the extension_transfer is only responsible to analyze a single token that it was assigned to at instantiation.
</blockquote></details>

add todo


<!-- Sent from Reviewable.io -->

2024-04-30 13:18 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: 32 of 33 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 51 at r17](https://reviewable.io/reviews/CoreumFoundation/coreum/802#-NwiXYsZ9RK_16kYQmsp:-Nwj9-Pz12cYtM6HLYf0:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/56430b10b1ab5d310b4c3cad2dbc048e338ea7d4/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

add todo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 13:19 UTC, dzmitryhil approved these changes
> Reviewed 9 of 22 files at r14, 3 of 11 files at r15, 5 of 8 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, 1 of 1 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/802)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-30 14:03 UTC, merged