Implement Clawback feature for assetft
CoreumFoundation/coreum pull request #804
Opened 2024-04-12 11:57 UTC by masihyeganeh

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

2024-04-16 06:05 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: 0 of 17 files reviewed, 9 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2130 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_RfFo43JeTARA72Ck:-Nv_RfFo43JeTARA72Cl:bjty17t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/integration-tests/modules/assetft_test.go#L2130)):*
> ```Go
> 	)
> 	requireT.Error(err)
> 	assertT.True(cosmoserrors.ErrUnauthorized.Is(err))
> ```

You can use ErrorIs of the `assertT`. 
___
*[`x/asset/ft/keeper/keeper.go` line 536 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_VOlC5PUoLeww2GrQ:-Nv_VOlC5PUoLeww2GrR:bk9rrvd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/keeper/keeper.go#L536)):*
> ```Go
> 
> // Clawback confiscates specified token from the specified account.
> func (k Keeper) Clawback(ctx sdk.Context, sender, addr sdk.AccAddress, coin sdk.Coin) error {
> ```

I would call `sender` -> `issuer` here to make it similar to to other such functions, where the action is allowed for the issuer only (same in the interface in the msg_server). 
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TRCv-jT5KU-cSe5N:-Nv_TRCv-jT5KU-cSe5O:b-tjgqii) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/keeper/keeper.go#L952)):*
> ```Go
> }
> 
> func (k Keeper) clawbackChecks(ctx sdk.Context, sender, addr sdk.AccAddress, coin sdk.Coin) error {
> ```

nit: I would propose to call the func validateClawbackAllowed or similar. 
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-Nv_UL6q7SZTmG8F_1Rh:bwciyee) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/keeper/keeper.go#L952)):*
> ```Go
> }
> 
> func (k Keeper) clawbackChecks(ctx sdk.Context, sender, addr sdk.AccAddress, coin sdk.Coin) error {
> ```

IMO there we should also check that clawback is prohibited for
* module accounts
* IBC escrow addresses
* WASM contract - not sure, better to discuss (for example for the bridge it's critical to prohibit, can be solved by not registering such tokens)
* groups accounts - not sure, better to discuss
* probably, others -  better to discuss

@ysv @miladz68 WDYT ?
___
*[`x/asset/ft/keeper/keeper.go` line 958 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TaRa-69Eq2zPg9jR:-Nv_TaRa-69Eq2zPg9jS:b-ohoe30) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/keeper/keeper.go#L958)):*
> ```Go
> 	}
> 
> 	if def.IsIssuer(addr) {
> ```

Also, you need to check that the token's issuer is the sender. 
___
*[`x/asset/ft/keeper/keeper.go` line 962 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TtmO0Wwd2LheHX5g:-Nv_TtmO0Wwd2LheHX5h:b-u9jlwd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/keeper/keeper.go#L962)):*
> ```Go
> 	}
> 
> 	return def.CheckFeatureAllowed(sender, types.Feature_clawback)
> ```

nit: I propose to put it to the first place in the func
___
*[`x/asset/ft/keeper/keeper_test.go` line 1267 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UCKYCs5huTzZB-Nt:-Nv_UCKYCs5huTzZB-Nu:b-c8maet) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/keeper/keeper_test.go#L1267)):*
> ```Go
> }
> 
> func TestKeeper_Clawback(t *testing.T) {
> ```

You don't test,  from what I see.

```
if def.IsIssuer(addr) {  
    return sdkerrors.Wrap(cosmoserrors.ErrUnauthorized, "issuer's balance can't be clawed back")  
}
```
___
*[`x/asset/ft/types/msgs.go` line 436 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_SnGFD5KYzxwaWgcb:-Nv_SnGFD5KYzxwaWgcc:b-9rca8k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/asset/ft/types/msgs.go#L436)):*
> ```Go
> }
> 
> func (m MsgClawback) ValidateBasic() error {
> ```

Missing unit test for the func. Check the unit tests of other ` ValidateBasic`. 
___
*[`x/deterministicgas/config.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_RsIREX6dq0HjFbsx:-Nv_RsIREX6dq0HjFbsy:b-ved4bq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3c8d695847a8f577d50146faf64d6c71e98449d2/x/deterministicgas/config.go#L86)):*
> ```Go
> 		MsgToMsgURL(&assetfttypes.MsgGloballyFreeze{}):      constantGasFunc(5_000),
> 		MsgToMsgURL(&assetfttypes.MsgGloballyUnfreeze{}):    constantGasFunc(5_000),
> 		MsgToMsgURL(&assetfttypes.MsgClawback{}):            constantGasFunc(73_500),
> ```

How did you compute that value? If you took the gas spent, then it's not correct. You need to sub the `FixedGas:       65000`.


<!-- Sent from Reviewable.io -->

2024-04-16 10:26 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: 0 of 21 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2130 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_RfFo43JeTARA72Ck:-Nva6uxY67VIWX8xGWfm:b-3903j3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/integration-tests/modules/assetft_test.go#L2130)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can use ErrorIs of the `assertT`.
</blockquote></details>

Almost all of the errors handled like this in the integration test. I can either change all of them, or not change this. Let's decide
___
*[`x/asset/ft/keeper/keeper.go` line 536 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_VOlC5PUoLeww2GrQ:-Nva7MprCQTadLrqqm71:buueym2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L536)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would call `sender` -> `issuer` here to make it similar to to other such functions, where the action is allowed for the issuer only (same in the interface in the msg_server).
</blockquote></details>

I agree, but there is another task that I'm working on to change the issuer to admin. I can either rename it there or just keep it like this, so it can be valid for both cases
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TRCv-jT5KU-cSe5N:-Nva7hK3AWQWWNqj8I66:b-gbkd5o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: I would propose to call the func validateClawbackAllowed or similar.
</blockquote></details>

I see that other functions that check the same thing are called like this. Let me know if I should unify them like what you suggested, or leave it like this
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-NvaAgI67p7fpQCPHUep:b-v2sfs9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO there we should also check that clawback is prohibited for
* module accounts
* IBC escrow addresses
* WASM contract - not sure, better to discuss (for example for the bridge it's critical to prohibit, can be solved by not registering such tokens)
* groups accounts - not sure, better to discuss
* probably, others -  better to discuss

@ysv @miladz68 WDYT ?
</blockquote></details>

I asked @miladz68 about the IBC and WASM, and he said that this feature is not used there. Correct me if I'm wrong here
___
*[`x/asset/ft/keeper/keeper.go` line 958 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TaRa-69Eq2zPg9jR:-NvaAHuoE_yEtG6pI54E:bi0kkjj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L958)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Also, you need to check that the token's issuer is the sender.
</blockquote></details>

It is already checking in IsFeatureAllowed
___
*[`x/asset/ft/keeper/keeper.go` line 962 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TtmO0Wwd2LheHX5g:-NvaB8ahE9zpD9x4MFTR:b-wo6c0b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L962)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: I propose to put it to the first place in the func
</blockquote></details>

We need the def to call this, so only thing that remains is the def.IsIssuer that comes before this. I'm not sure if it gives any improvement
___
*[`x/asset/ft/keeper/keeper_test.go` line 1267 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UCKYCs5huTzZB-Nt:-NvaC7qKCASBa6KSDuB6:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper_test.go#L1267)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't test,  from what I see.

```
if def.IsIssuer(addr) {  
    return sdkerrors.Wrap(cosmoserrors.ErrUnauthorized, "issuer's balance can't be clawed back")  
}
```
</blockquote></details>

Done.
___
*[`x/asset/ft/types/msgs.go` line 436 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_SnGFD5KYzxwaWgcb:-NvaFIqe3_LYr7CoC653:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/types/msgs.go#L436)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Missing unit test for the func. Check the unit tests of other ` ValidateBasic`.
</blockquote></details>

Done.
___
*[`x/deterministicgas/config.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_RsIREX6dq0HjFbsx:-NvaDEOx6PP2mIyJK5e_:b-1bdkof) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/deterministicgas/config.go#L86)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How did you compute that value? If you took the gas spent, then it's not correct. You need to sub the `FixedGas:       65000`.
</blockquote></details>

Yeah, this is one of the problems I faced. I used some small number here and let the tests run. It failed but said how much gas actually used. But when I subtracted the 65k from it, it failed again. The 73500 worked. But now I changed it back to 8500 and it works.
So it's fixed.


<!-- Sent from Reviewable.io -->

2024-04-16 11:10 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: 0 of 21 files reviewed, 4 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2130 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_RfFo43JeTARA72Ck:-NvaYRp-15Xc2MamWEyr:b-tmjz3s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/integration-tests/modules/assetft_test.go#L2130)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Almost all of the errors handled like this in the integration test. I can either change all of them, or not change this. Let's decide
</blockquote></details>

No need to update them for others, that approach is better, and for new tests we used it.
___
*[`x/asset/ft/keeper/keeper.go` line 536 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_VOlC5PUoLeww2GrQ:-NvaYdgDCPW64TjqRTux:b1kvj4c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L536)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I agree, but there is another task that I'm working on to change the issuer to admin. I can either rename it there or just keep it like this, so it can be valid for both cases
</blockquote></details>

Right, so you will rename the issuer, not the sender. So this attribute will be renamed to admin.
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TRCv-jT5KU-cSe5N:-NvaYyp70mt2klFQCwzP:bpgfgix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I see that other functions that check the same thing are called like this. Let me know if I should unify them like what you suggested, or leave it like this
</blockquote></details>

I see only one `freezingChecks`. Let's discuss this with the team if you wish. 
Check the https://reviewable.io/reviews/CoreumFoundation/coreum/800#-NvaJ0AW6OsyMyMgsgNV discussion it is relevant IMO. 
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-NvaZQ4-8nesuHyHFFKs:b-92k0aa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I asked @miladz68 about the IBC and WASM, and he said that this feature is not used there. Correct me if I'm wrong here
</blockquote></details>

WDYM @miladz68 ?
___
*[`x/asset/ft/keeper/keeper.go` line 958 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_TaRa-69Eq2zPg9jR:-NvaZqRs7o5QMS0XplMq:b-t3ht5v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L958)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is already checking in IsFeatureAllowed
</blockquote></details>

I see, right.


<!-- Sent from Reviewable.io -->

2024-04-17 07:06 UTC, miladz68 requested changes
> Reviewed 12 of 17 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 536 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_VOlC5PUoLeww2GrQ:-Nvep3iK54owzx6eoCbV:b-2thjq4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L536)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, so you will rename the issuer, not the sender. So this attribute will be renamed to admin.
</blockquote></details>

I think sender is more correct, the assertion that sender is equal to admin/issuer is part of logic, it is not needed to be reflected in the var name. 
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-NvepWQz21rLgbDQS2AA:blc2dc3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

WDYM @miladz68 ?
</blockquote></details>

module accounts and escrow address must be prohibited. 
I don't think wasm and groups should be prohibited.
___
*[`x/asset/ft/keeper/keeper_test.go` line 1267 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NverZoa4g_GuF5ERSPC:-NverZoa4g_GuF5ERSPD:b-6pfnhj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/keeper/keeper_test.go#L1267)):*
> ```Go
> }
> 
> func TestKeeper_Clawback(t *testing.T) {
> ```

more conditions to test
clawback frozen token must succeed
clawback from module account must fail
clawback from ibc escrow address must fail
clawback from group account as dima mentioned
___
*[`x/asset/ft/types/msgs.go` line 452 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NveqJ0e8Szze4gyvMGA:-NveqJ0e8Szze4gyvMGB:b-iekqlb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/types/msgs.go#L452)):*
> ```Go
> 
> 	if issuer.String() == m.Account {
> 		return sdkerrors.Wrap(cosmoserrors.ErrUnauthorized, "issuer's balance can't be clawed back")
> ```

this should not be in validate basics, it belongs to the keeper.
___
*[`x/asset/ft/types/msgs.go` line 456 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NveqOTHExTZTZAs-cLo:-NveqOTHExTZTZAs-cLp:bt6qieb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/types/msgs.go#L456)):*
> ```Go
> 
> 	if issuer.String() != m.Sender {
> 		return sdkerrors.Wrap(cosmoserrors.ErrUnauthorized, "only issuer can claw back balance")
> ```

this check does not belong here, it belongs to the keeper.


<!-- Sent from Reviewable.io -->

2024-04-17 11:35 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 7 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 536 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_VOlC5PUoLeww2GrQ:-NvfpQ154mXFv1_j3C9M:b-fml99p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L536)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think sender is more correct, the assertion that sender is equal to admin/issuer is part of logic, it is not needed to be reflected in the var name.
</blockquote></details>

I agree, that in general it might be sender, but we used issuer in such cases, that's why I proposed. Let's discuss with the team. 
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-Nvfpg-vDHX8478dM1lv:b-mc5kca) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

module accounts and escrow address must be prohibited. 
I don't think wasm and groups should be prohibited.
</blockquote></details>

Let's discuss with the team.


<!-- Sent from Reviewable.io -->

2024-04-18 06:01 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2130 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_RfFo43JeTARA72Ck:-NvfkxoX6Pf4rhdWpk5Y:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/integration-tests/modules/assetft_test.go#L2130)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

No need to update them for others, that approach is better, and for new tests we used it.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 536 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_VOlC5PUoLeww2GrQ:-NvfZOh1-OKbJILKi_Ty:b-dtrjw8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L536)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think sender is more correct, the assertion that sender is equal to admin/issuer is part of logic, it is not needed to be reflected in the var name.
</blockquote></details>

I agree with Milad. I imagine that "sender" means the person who sent the transaction/message. In the body of the logic we need to decide who it actually is
___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-NvjmLGQDRypsYEWwG0D:bizasg3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss with the team.
</blockquote></details>

It is decided that we should only prohibit module accounts
___
*[`x/asset/ft/keeper/keeper_test.go` line 1267 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NverZoa4g_GuF5ERSPC:-NvjmYic92JzqpMMFOOA:bviinmb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/keeper/keeper_test.go#L1267)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

more conditions to test
clawback frozen token must succeed
clawback from module account must fail
clawback from ibc escrow address must fail
clawback from group account as dima mentioned
</blockquote></details>

It is decided that we should only prohibit module accounts. other than that, what should happen when you clawback a frozen token? should it unfreeze first?
___
*[`x/asset/ft/types/msgs.go` line 452 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NveqJ0e8Szze4gyvMGA:-Nvfw4Sh80UIWODiDeDB:b-opi84s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/types/msgs.go#L452)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this should not be in validate basics, it belongs to the keeper.
</blockquote></details>

I was mimicking the freeze feature. So, it should change too?
___
*[`x/asset/ft/types/msgs.go` line 456 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NveqOTHExTZTZAs-cLo:-NvfwCSw1Q8wXRcAj1k2:b-opi84s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/types/msgs.go#L456)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this check does not belong here, it belongs to the keeper.
</blockquote></details>

I was mimicking the freeze feature. So, it should change too?


<!-- Sent from Reviewable.io -->

2024-04-18 06:18 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 952 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nv_UL6q7SZTmG8F_1Rg:-NvjpmigE60f-mzga3vs:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/81c1be1aad519812808feeac8aadae4e06f92413/x/asset/ft/keeper/keeper.go#L952)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is decided that we should only prohibit module accounts
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_test.go` line 1267 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NverZoa4g_GuF5ERSPC:-NvjpoxBBnRNcv0zWksa:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/keeper/keeper_test.go#L1267)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is decided that we should only prohibit module accounts. other than that, what should happen when you clawback a frozen token? should it unfreeze first?
</blockquote></details>

Done.
___
*[`x/asset/ft/types/msgs.go` line 452 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NveqJ0e8Szze4gyvMGA:-NvjptYoBI0fFR3vqo7v:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/types/msgs.go#L452)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I was mimicking the freeze feature. So, it should change too?
</blockquote></details>

Done.
___
*[`x/asset/ft/types/msgs.go` line 456 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NveqOTHExTZTZAs-cLo:-Nvjpu0A-fwJJfxyueki:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/x/asset/ft/types/msgs.go#L456)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I was mimicking the freeze feature. So, it should change too?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 10:32 UTC, miladz68 approved these changes
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-18 11:15 UTC, ysv requested changes
> Reviewed 5 of 17 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvkuci5Cbz9ivX2UkN_:-Nvkuci5Cbz9ivX2UkNa:b-caavrm) (no related file):*
partially reviewed
will continue the review

___
___
*[`integration-tests/modules/assetft_test.go` line 2035 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghZfUEsBIc9xNF1kc:-NvghZfUEsBIc9xNF1kd:b-evm8my) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2035)):*
> ```Go
> 
> // TestAssetFTClawback checks clawback functionality of fungible tokens.
> func TestAssetFTClawback(t *testing.T) {
> ```

looks good but we will probably have to add more tests for IBC escrow & WASM & Module account.
Unless we do all of them in unit tests



_Code quote:_
```Go
TestAssetFTClawback
```
___
*[`integration-tests/modules/assetft_test.go` line 2047 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvggYhT7OtM6IwN5sMI:-NvggYhT7OtM6IwN5sMJ:b-qza05y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2047)):*
> ```Go
> 
> 	issuer := chain.GenAccount()
> 	from := chain.GenAccount()
> ```

nit: usually we call it sender I think



_Code quote:_
```Go
from
```
___
*[`integration-tests/modules/assetft_test.go` line 2130 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvggpne7BZdzQQyNo7u:-Nvggpne7BZdzQQyNo7v:b-j7z9hz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2130)):*
> ```Go
> 	)
> 	requireT.Error(err)
> 	assertT.True(cosmoserrors.ErrUnauthorized.Is(err))
> ```

I'm wondering if we get ErrUnauthorized in this case 

Because this address doesn't exist on chain (since it is not funded) so failure should happen on estimation step, shouldn't it ?
___
*[`integration-tests/modules/assetft_test.go` line 2149 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghGweE4ptQtJVr3wN:-NvghGweE4ptQtJVr3wO:b-832pdi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2149)):*
> ```Go
> 	fungibleTokenClawbackEvts, err := event.FindTypedEvents[*assetfttypes.EventAmountClawedBack](res.Events)
> 	requireT.NoError(err)
> 	assertT.EqualValues(&assetfttypes.EventAmountClawedBack{
> ```

I can see that clawback is a single word
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/TrRhzUJI7LO6u1ke8umbtbR9/image.png)

Shouldn't it be just Clawback everywhere instead of clawBack ?

Pls check all places



_Code quote:_
```Go
EventAmountClawedBack
```


<!-- Sent from Reviewable.io -->

2024-04-18 11:25 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 6 unresolved discussions (waiting on @masihyeganeh and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-19 06:53 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2035 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghZfUEsBIc9xNF1kc:-Nvp6hW_8plbdixKN6zw:b-o2r6zn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2035)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

looks good but we will probably have to add more tests for IBC escrow & WASM & Module account.
Unless we do all of them in unit tests
</blockquote></details>

I actually have unit test for module account. But I'm not sure how to test the other two. And I'm not sure if it is needed or not. Because there is no restriction on any other kind of accounts
___
*[`integration-tests/modules/assetft_test.go` line 2047 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvggYhT7OtM6IwN5sMI:-Nvp54P8-yGsA4jmQYQb:bw52zm5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2047)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: usually we call it sender I think
</blockquote></details>

This one is a little different. You are clawbacking "from" an account. So, It's not "sender". But if "from" is not good enough, I can change it to "account" maybe
___
*[`integration-tests/modules/assetft_test.go` line 2130 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvggpne7BZdzQQyNo7u:-Nvp5QlbDPs4hmZX6Uxu:b-t8lux9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2130)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm wondering if we get ErrUnauthorized in this case 

Because this address doesn't exist on chain (since it is not funded) so failure should happen on estimation step, shouldn't it ?
</blockquote></details>

We actually get ErrUnauthorized (as you can see that this test passes), because it is checked that the sender is actually the issuer of the token in checks
___
*[`integration-tests/modules/assetft_test.go` line 2149 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghGweE4ptQtJVr3wN:-Nvp61PsAkbs1nMOUzYA:b-z63qlu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2149)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I can see that clawback is a single word
![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/TrRhzUJI7LO6u1ke8umbtbR9/image.png)

Shouldn't it be just Clawback everywhere instead of clawBack ?

Pls check all places
</blockquote></details>

![Screen Shot 1403-01-31 at 10.17.22.png](https://files.reviewableusercontent.io/images/reviewable/692335/ETq2dy2jopeh9vPUTmiORVzP/Screen%20Shot%201403-01-31%20at%2010.17.22.png)
At least my IDE is not happy when I'm handling it like a single word.
Let me know if you still believe that it should not be separated


<!-- Sent from Reviewable.io -->

2024-04-19 11:40 UTC, dzmitryhil approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-:-Nvq95HH2FCiGdwSSC5w:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-23 08:15 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 6 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-23 16:38 UTC, ysv requested changes
> Reviewed 5 of 17 files at r1, 1 of 1 files at r3, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 2035 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghZfUEsBIc9xNF1kc:-NwAk6h33Dr5xWs-ppiT:b-75bymk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2035)):*
> Because there is no restriction on any other kind of accounts

I would still test this since they are different type of accounts and might behave differently.
@miladz68 @dzmitryhil WDYT ?

Also it might make sense to check behaviour of vesting accounts in such case

> But I'm not sure how to test the other two

It is for sure doable via integration tests but maybe we can do it somehow simpler via unit

Lets discuss on call
___
*[`integration-tests/modules/assetft_test.go` line 2047 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvggYhT7OtM6IwN5sMI:-NwAkmoP6_0wC9ByT7iZ:brbk98t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2047)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

This one is a little different. You are clawbacking "from" an account. So, It's not "sender". But if "from" is not good enough, I can change it to "account" maybe
</blockquote></details>

I see, then sender is not ok.

Maybe account 
___
*[`integration-tests/modules/assetft_test.go` line 2130 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvggpne7BZdzQQyNo7u:-NwAmbed5Py2ll9HsAx2:b-lzv1wq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2130)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

We actually get ErrUnauthorized (as you can see that this test passes), because it is checked that the sender is actually the issuer of the token in checks
</blockquote></details>

yeah tests succeed and I'm confused why

that is strange since account existence is checked on ante handler which runs before keeper logic. So it should fail on acc existence step IMO. 
And I checked you don't verify issuer on ValidateBasic.

Maybe I misunderstood smth
Could you pls dig dipper and check ?
___
*[`integration-tests/modules/assetft_test.go` line 2149 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghGweE4ptQtJVr3wN:-NwAnPo--M0dON2z5Vdb:bjp86gs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2149)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

![Screen Shot 1403-01-31 at 10.17.22.png](https://files.reviewableusercontent.io/images/reviewable/692335/ETq2dy2jopeh9vPUTmiORVzP/Screen%20Shot%201403-01-31%20at%2010.17.22.png)
At least my IDE is not happy when I'm handling it like a single word.
Let me know if you still believe that it should not be separated
</blockquote></details>

I prefer Clawbacked since we use Clawback everywhere as single word.
IMO better for consistency
___
*[`x/asset/ft/keeper/keeper.go` line 963 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NwAnunT6atIF010ZLvK:-NwAnunT6atIF010ZLvL:b-4a0dqy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84705806362902e296e14c09afe45453cdd7e15c/x/asset/ft/keeper/keeper.go#L963)):*
> ```Go
> 
> 	if def.IsIssuer(addr) {
> 		return sdkerrors.Wrap(cosmoserrors.ErrUnauthorized, "issuer's balance can't be clawed back")
> ```

this is more question for next PR:

How it should behave once we split admin & issuer.
Maybe for issuer it should behave the same way as for other addresses ? It is like sending to yourself of bank send it is not prohibited 

Lets at least leave todo here for the next PR


<!-- Sent from Reviewable.io -->

2024-04-25 06:32 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2035 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghZfUEsBIc9xNF1kc:-NwIwaPL5hPwzoN1MvKA:b-bsz0kr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2035)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Because there is no restriction on any other kind of accounts

I would still test this since they are different type of accounts and might behave differently.
@miladz68 @dzmitryhil WDYT ?

Also it might make sense to check behaviour of vesting accounts in such case

> But I'm not sure how to test the other two

It is for sure doable via integration tests but maybe we can do it somehow simpler via unit

Lets discuss on call
</blockquote></details>

adding wasm tests won't hurt. if you question on how to get wasm accounts, let me know. for IBC a new test should be added to the IBC folder I guess. 


<!-- Sent from Reviewable.io -->

2024-04-25 13:34 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2035 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghZfUEsBIc9xNF1kc:-NwKSY9qDMdE3C1jKygM:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2035)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

adding wasm tests won't hurt. if you question on how to get wasm accounts, let me know. for IBC a new test should be added to the IBC folder I guess.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 2130 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvggpne7BZdzQQyNo7u:-NwKP6RN8-rC0WqLnYyB:bz2paxr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2130)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yeah tests succeed and I'm confused why

that is strange since account existence is checked on ante handler which runs before keeper logic. So it should fail on acc existence step IMO. 
And I checked you don't verify issuer on ValidateBasic.

Maybe I misunderstood smth
Could you pls dig dipper and check ?
</blockquote></details>

It is checked here:
https://github.com/CoreumFoundation/coreum/blob/aa9144d08377b8aa8a45f5ba27b8d61aaa0a505c/x/asset/ft/types/token.go#L186
___
*[`integration-tests/modules/assetft_test.go` line 2149 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NvghGweE4ptQtJVr3wN:-NwKODw01zBeGNIaALsv:b-e9pn2c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ed595641f28883dc0b3da4fe3e87e961055a5a5/integration-tests/modules/assetft_test.go#L2149)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I prefer Clawbacked since we use Clawback everywhere as single word.
IMO better for consistency
</blockquote></details>

![Screen Shot 1403-02-06 at 16.44.44.png](https://files.reviewableusercontent.io/images/reviewable/692335/88MHVghsLBu3dRy4LTs-q-uf/Screen%20Shot%201403-02-06%20at%2016.44.44.png)

Let's stick to current implementation
___
*[`x/asset/ft/keeper/keeper.go` line 963 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NwAnunT6atIF010ZLvK:-NwKNsj1Ew8rntGRuTYw:be1cizg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84705806362902e296e14c09afe45453cdd7e15c/x/asset/ft/keeper/keeper.go#L963)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this is more question for next PR:

How it should behave once we split admin & issuer.
Maybe for issuer it should behave the same way as for other addresses ? It is like sending to yourself of bank send it is not prohibited 

Lets at least leave todo here for the next PR
</blockquote></details>

It is already fixed in the next PR. `IsIssuer` is replaced by `IsAdmin`. Will change this too in that PR


<!-- Sent from Reviewable.io -->

2024-04-26 08:53 UTC, miladz68 approved these changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-26 09:52 UTC, dzmitryhil reviewed
> Reviewed 9 of 17 files at r1, 4 of 9 files at r2, 1 of 1 files at r3, 8 of 9 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-26 15:43 UTC, ysv requested changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper.go` line 963 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NwAnunT6atIF010ZLvK:-NwQ3LMW1RqTFG9Adp74:b-f9luxd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84705806362902e296e14c09afe45453cdd7e15c/x/asset/ft/keeper/keeper.go#L963)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is already fixed in the next PR. `IsIssuer` is replaced by `IsAdmin`. Will change this too in that PR
</blockquote></details>

but just changing this line to IsAdmin is not enough IMO
We should change logic here I think

For this PR it is ok to leave just TODO and we can discuss logic in the next one


<!-- Sent from Reviewable.io -->

2024-04-26 15:49 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 963 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-NwAnunT6atIF010ZLvK:-NwQ5EG2ApJbRqWSUrQ4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84705806362902e296e14c09afe45453cdd7e15c/x/asset/ft/keeper/keeper.go#L963)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but just changing this line to IsAdmin is not enough IMO
We should change logic here I think

For this PR it is ok to leave just TODO and we can discuss logic in the next one
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-26 15:53 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-29 10:32 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-29 10:35 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvkuci5Cbz9ivX2UkN_:-NwdQ3426FTWGxPEUxWU:b-896fig) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

partially reviewed
will continue the review
</blockquote></details>

Done?

___


<!-- Sent from Reviewable.io -->

2024-04-29 10:36 UTC, masihyeganeh reviewed
> Reviewed 9 of 17 files at r1, 4 of 9 files at r2, 1 of 1 files at r3, 7 of 9 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-29 10:55 UTC, masihyeganeh reviewed
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-04-29 10:55 UTC, ysv approved these changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/804#-Nvkuci5Cbz9ivX2UkN_:-NwdUhHU7Y3HwqUiJGOO:b2nign6) (no related file):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

yes

___


<!-- Sent from Reviewable.io -->

2024-04-29 11:02 UTC, merged