Implementing features in extension contract
CoreumFoundation/coreum pull request #818
Opened 2024-05-01 15:28 UTC by masihyeganeh

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/coreum/818)

2024-05-08 20:15 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 3 of 15 files reviewed, 25 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 270 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxH8bLq0hxCT5VX6vta:-NxOfVne7J-JA-SgLpeZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L270)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

extension is not related to signature verification, I think this step can be removed.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 551 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxHBIjn3Af0RQWLM-Dy:-NxOfO63EijYJQ9LIq7m:b9vi3kb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L551)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you don't need this feature.
</blockquote></details>

Done. But it was in the original test
___
*[`integration-tests/modules/assetft_extension_test.go` line 587 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxHBf8G7DPzzGbs_T4_:-NxOfGuX7squZbRbWHLh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L587)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

same as above, signature verification is not part of the extension, it is verified in the other test already.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 829 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxLzb9ZDJTA1Fe6g-NZ:-NxOfCDw4iWNVRgK2-7T:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L829)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this test does not interact with extesions, so it seems useless to be here. 2.6315789
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 897 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM-0po6SRXjg3Q2Z_p:-NxOesd12pABEek29Ymr:bktsyd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L897)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the extension contract must have the same burn privileges as the admin, meaning that it can burn tokens even if the feature is not enabled. What we want to test here is only that. I think a lot of test cases that are not related. 
I can only think of a single meaningful test case here, that the contract is able to burn tokens and assert that burning took place as intended.
</blockquote></details>

Our goal was duplicating all tests we already have, but just add the extension to them. I don't think that it hurts if we have those
___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxOeTXV7mTAG_TlBTCS:b-hta3jh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

As discussed for minting, there should be only one test case here, that the contract is able to mint tokens if feature is enabled, and assert that minting happened.
</blockquote></details>

I believe that we should test mintable and non-mintable tokens here. But I agree that tests in which the extension is not involved are not needed
___
*[`integration-tests/modules/assetft_extension_test.go` line 1245 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM-jw2-oOwxfjuBh4_:-NxOeDbe7JHOfDQ1Gq8t:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1245)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this check does not interact with extensions, it is not a meaningful check IMO.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 1259 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1Xjf8qAmFhrorK7F:-NxOdSWD5vmX9RAmkAW5:b-jsfnxg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1259)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we don't want to test minting, we know that it works. we just want to check that the extension contract has privileges to mint tokens if the feature is enabled.
</blockquote></details>

I don't agree. It's an integration test, so if the feature is enabled, it should be able to mint which also means that the contract had the privileges to mint
___
*[`x/asset/ft/keeper/keeper.go` line 690 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM2rauAlmfvStkI5wM:-NxOh32VDYwxNYXO3rUT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper.go#L690)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

only admin can transfer admin role, the extension contract is not allowed to do that.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 722 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM2yLkAVYKIMiCsn6j:-NxOgzoq18GMHnx7eSJb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper.go#L722)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

only admin can do this, not the extension contract.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 160 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM3jNS7W5q27qmDCms:-NxOhnleAWdv-tCEAWVs:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L160)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this case does not interact with extensions, it should be removed
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 164 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM3rpW4B6_dx3QqI-l:-NxOhnaq87JzDjs_bLPV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L164)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this case does not interact with extensions, it should be removed
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 169 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM3tB-Cf5B_rs6DWXL:-NxOhmwl2-Y4UVK3LVNG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L169)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this case does not interact with extensions, it should be removed
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` [...]

2024-05-09 05:19 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 3 of 15 files reviewed, 30 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 293 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQlQY-CxNQh3sdP3jx:-NxQlQY-CxNQh3sdP3jy:bpae5cm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L293)):*
> ```Go
> 	multiSendMsg := &banktypes.MsgMultiSend{
> 		Inputs:  []banktypes.Input{{Address: issuer.String(), Coins: coinsToSend}},
> 		Outputs: []banktypes.Output{{Address: recipient.String(), Coins: coinsToSend}},
> ```

If you want to test the `MsgMultiSend` use multiple recipients. 
I would propose to use both `MsgSend` with single recipient and `MsgMultiSend` with multiple. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 69 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQjTzW2v98Y25mh1wl:-NxQjTzW2v98Y25mh1wm:bit2ujh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L69)):*
> ```XML
>     // check that amount is present in the attached funds, and attached funds is enough
>     // to cover the transfer.
>     let attached_fund = query_bank_balance(
> ```

The variable name is not correct, the `contract_balance` is better name here. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 89 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQjjA951eY2JxnogZt:-NxQjjAA1jk9lYXa-LDH:bg4vkzb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L89)):*
> ```XML
>         }
> 
>         if features.contains(&assetft::BLOCK_SMART_CONTRACTS) {
> ```

IMO no need to check that feature, since you won't be able to call the contract if the feature is enabled :-)
@miladz68 @ysv @wojtek-coreum WDYT ?
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 99 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQkjis9JbIqUyCQ2Y1:-NxQkjis9JbIqUyCQ2Y2:b-x5w0ww) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L99)):*
> ```XML
>         // meaningful check.
>         if amount == Uint128::new(101) {
>             return assert_burning(
> ```

Could you please explain the `assert_burning` and `assert_minting` usage here?
Because if the burning/minting is disabled no matter whether you do that check here or not, the transaction should fail. So seems that part is not needed.
___
*[`x/asset/ft/types/token.go` line 206 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQl2pl3Czbh5g72omr:-NxQl2pl3Czbh5g72oms:b-g4h40b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/types/token.go#L206)):*
> ```Go
> 
> // HasAdminPrivileges returns true if the addr is the admin or the asset extension contract address.
> func (def Definition) HasAdminPrivileges(addr sdk.Address) bool {
> ```

nit: What was wrong with prev name?


<!-- Sent from Reviewable.io -->

2024-05-09 05:25 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 3 of 15 files reviewed, 31 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 89 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQjjA951eY2JxnogZt:-NxQnynGC0BjsAGf2Y4F:bowp642) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L89)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO no need to check that feature, since you won't be able to call the contract if the feature is enabled :-)
@miladz68 @ysv @wojtek-coreum WDYT ?
</blockquote></details>

I mean if the extensions are enabled it makes no sense to allow the `BLOCK_SMART_CONTRACTS` feature to be enabled. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 100 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQmw0o0CwLTHKu1e35:-NxQmw0o0CwLTHKu1e36:b6u0uge) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L100)):*
> ```XML
>         if amount == Uint128::new(101) {
>             return assert_burning(
>                 info.sender.as_ref(), amount, &token, features.contains(&assetft::BURNING)
> ```

IMO what is possible to test here is that you can mint/burn when you intercept the send. For example, you can define at the time of the installation and addresses, and if you send from that address you burn the tokens if you send to that address mint `x2`. Or any other example. You can ask @miladz68 probably it's a part of a different task?!


<!-- Sent from Reviewable.io -->

2024-05-09 07:44 UTC, miladz68 requested changes
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 22 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 897 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM-0po6SRXjg3Q2Z_p:-NxRBer13KtiMhQejei7:b-87x5op) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L897)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Our goal was duplicating all tests we already have, but just add the extension to them. I don't think that it hurts if we have those
</blockquote></details>

Actually our goal was to test extensions, and we took the code from previous tests so we don't write it from scratch. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxREpZ2BXMktMdO7bDR:b7zu936) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I believe that we should test mintable and non-mintable tokens here. But I agree that tests in which the extension is not involved are not needed
</blockquote></details>

agreed mintable and non-mintable tokens should both be tested. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 1259 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1Xjf8qAmFhrorK7F:-NxREzN85vILwXb2vLoP:bhhzlrp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1259)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I don't agree. It's an integration test, so if the feature is enabled, it should be able to mint which also means that the contract had the privileges to mint
</blockquote></details>

the minting part is already tested, and the mint message does not interact with extensions. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 1221 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRFCLH-gDvgvh0vN7j:-NxRFCLH-gDvgvh0vN7k:boovmc5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L1221)):*
> ```Go
> // TestAssetFTExtensionSendingToSmartContractIsDenied verifies that this is not possible to send token to smart contract
> // if issuer blocked this operation.
> func TestAssetFTExtensionSendingToSmartContractIsDenied(t *testing.T) {
> ```

Just a reminder, if you keep adding features on top of this PR, it will get so big that you will have hard time finalizing it. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 1329 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRFfsG4v4269B1oYKQ:-NxRFfsG4v4269B1oYKR:b-6iarpi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L1329)):*
> ```Go
> // TestAssetFTExtensionAttachingToSmartContractIsDenied verifies that this is not possible to attach token to smart
> // contract call if issuer blocked this operation.
> func TestAssetFTExtensionAttachingToSmartContractCallIsDenied(t *testing.T) {
> ```

smart test case :thumbsup: 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 176 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM66pd97s1OF_zUqRo:-NxRICBv-Q2bD_CnELSv:b-pzjw51) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L176)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

The TODO is exactly copied from [the doc](https://test.docs.coreum.dev/docs/modules/coreum-fungible-token#:~:text=The%20user%20cannot%20burn%20the%20frozen%20amount%20if%20both%20freezing%20and%20burning%20is%20enabled.)
</blockquote></details>

yes, the external behavior is as described in the doc, meaning cannot burn. but this is not the user burning the token, it is extension burning the token. the extension can burn the tokens that is in its custody as it sees fit. since the user transferred their tokens to the custody of the extension, the only condition that should be checked here, is that the balance of the user after this transfer is not below their frozen balance. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 178 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM6eSh0_NJWWyPLkYo:-NxRHxD69LOX3QSvzAxx:b-2g7vw1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L178)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is exactly what you wrote. Isn't it?
</blockquote></details>

what part did I write ? could you be more specific ?
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 69 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRH2TyBh5w2arBVZSg:-NxRH2TyBh5w2arBVZSh:b-os8xiw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L69)):*
> ```XML
>     // check that amount is present in the attached funds, and attached funds is enough
>     // to cover the transfer.
>     let attached_fund = query_bank_balance(
> ```

don't query bank balance of the contract, inspect attached funds. it is `info.funds`.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 89 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQjjA951eY2JxnogZt:-NxRD94CCKKQo9jbEmMv:bkejajx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L89)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean if the extensions are enabled it makes no sense to allow the `BLOCK_SMART_CONTRACTS` feature to be enabled.
</blockquote></details>

it does make sense, we block all other contracts, except the extension contract.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 191 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRDysQ869UaVxkOSKH:-NxRDysQ869UaVxkOSKI:bep31v2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L191)):*
> ```XML
>     // TODO(masih): The user cannot burn the frozen amount if both
>     // freezing and burning is enabled.
>     if !burning_enabled && sender != token.issuer {
> ```

you don't need this check to be able to check that burning works ok. just send 101 tokens with 2 scenarios, burnalbe and non-burnable. In both cases burning should have been done, make sure it was burnt correctly by inspecting the events and total supply. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 249 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRGGhCDEhX7_54p-XY:-NxRGGhCDEhX7_54p-XZ:b-lsngte) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L249)):*
> ```XML
> 
>   [...]

2024-05-09 10:14 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 22 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxRjVdL1p7AXa8fb9gp:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

agreed mintable and non-mintable tokens should both be tested.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 1259 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1Xjf8qAmFhrorK7F:-NxRjvW1C8iMZBfT9ojk:b-4ve6wx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1259)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the minting part is already tested, and the mint message does not interact with extensions.
</blockquote></details>

But it is not calling the native mint method of token. It is simulated with a magic amount and it is actually happened in the extension. So, I believe we need this test. Let me know if you insist on removing it
___
*[`integration-tests/modules/assetft_extension_test.go` line 1221 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRFCLH-gDvgvh0vN7j:-NxRk_Tn7GJfi44Waf6c:b-4a9yqn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L1221)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Just a reminder, if you keep adding features on top of this PR, it will get so big that you will have hard time finalizing it.
</blockquote></details>

You're right. I was actually implementing it while you were reviewing. I won't implement other features in this branch
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 176 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM66pd97s1OF_zUqRo:-NxRobUIBq6vZYZ5g_OA:ba4f2nx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L176)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yes, the external behavior is as described in the doc, meaning cannot burn. but this is not the user burning the token, it is extension burning the token. the extension can burn the tokens that is in its custody as it sees fit. since the user transferred their tokens to the custody of the extension, the only condition that should be checked here, is that the balance of the user after this transfer is not below their frozen balance.
</blockquote></details>

So, I'll delete the TODO
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 178 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM6eSh0_NJWWyPLkYo:-NxRoycB741EN7mCsh3k:bvw6i2d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L178)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what part did I write ? could you be more specific ?
</blockquote></details>

I mean, if the sender of the bankSend is the issuer (or admin) of the token, the smart contract can burn it. If I let all of the smart contract calls be able to burn, then any user that sends a bankSend can burn. Let me know if I'm not clear enough
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 69 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQjTzW2v98Y25mh1wl:-NxRnBwzBxOQo4l9nVMT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L69)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The variable name is not correct, the `contract_balance` is better name here.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 69 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRH2TyBh5w2arBVZSg:-NxRnCDr3D0qWPsWCuw3:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L69)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

don't query bank balance of the contract, inspect attached funds. it is `info.funds`.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 89 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQjjA951eY2JxnogZt:-NxRnT_K3H_2oJJ9ZW6C:bh40hm1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L89)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it does make sense, we block all other contracts, except the extension contract.
</blockquote></details>

I agree with Milad
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 99 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQkjis9JbIqUyCQ2Y1:-NxRnfDQ351FmwPlmqGY:bsrlejz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain the `assert_burning` and `assert_minting` usage here?
Because if the burning/minting is disabled no matter whether you do that check here or not, the transaction should fail. So seems that part is not needed.
</blockquote></details>

If the asset extension feature is enabled, those checks should happen in the extension, but enabling or disabling them still happens using those feature flags
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 100 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQmw0o0CwLTHKu1e35:-NxRoJSe5RSEhnRgXMiz:biub566) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L100)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO what is possible to test here is that you can mint/burn when you intercept the send. For example, you can define at the time of the installation and addresses, and if you send from that address you burn the tokens if you send to that address mint `x2`. Or any other example. You can ask @miladz68 probably it's a part of a different task?!
</blockquote></details>

This is exactly what you suggest but when the amount is equal to a magic number, instead of a specific account. Both is possible, but this one lets minting to more accounts and you can test more situations
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 191 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRDysQ869UaVxkOSKH:-NxRpTnW4C6ijHuhbgDe:b-1ezjhc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L191)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i> [...]

2024-05-10 07:01 UTC, miladz68 requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 20 unresolved discussions (waiting on @dzmitryhil, @i, @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRqEgcEkAWSHzKMbF1:-NxRqEgcEkAWSHzKMbF2:b-enzhbs) (no related file):*
Run `cargo fmt` at the root of the cargo project to make sure that the files are properly formatted. 

___
___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxWHhCI-125yndOHdcv:b2pv6mx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you are not testing that trying to mint non-mintable tokens are correctly rejected by the go code. you only reject it in the smart contract which is not what we intend to test. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 1259 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1Xjf8qAmFhrorK7F:-NxWI1dR8J9sz9uTkEKx:b-5lz99o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1259)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

But it is not calling the native mint method of token. It is simulated with a magic amount and it is actually happened in the extension. So, I believe we need this test. Let me know if you insist on removing it
</blockquote></details>

but the code below the comment `mint tokens and check balance and total supply` only tests the native code, which is already tested. I am not saying to remove the entire test, but the parts that don't affect and are not affected by extensions don't need to be tested. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 178 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM6eSh0_NJWWyPLkYo:-NxWHG6h98TQtYyqfUAT:b-bi8pzm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L178)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I mean, if the sender of the bankSend is the issuer (or admin) of the token, the smart contract can burn it. If I let all of the smart contract calls be able to burn, then any user that sends a bankSend can burn. Let me know if I'm not clear enough
</blockquote></details>

you are clear, and that is the behavior that we want to test, so remove this check. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 191 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRDysQ869UaVxkOSKH:-NxWHRex1vAKoVM3n-ju:b-i21nbn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L191)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

But it is testing more than that. It tests that non-burnables won't burn, but for burnable, you can decide who can burn it. Let me know if you insist on removing it
</blockquote></details>

asset extension must be able to burn both burnables and non-burnables, so the check should be removed. 


<!-- Sent from Reviewable.io -->

2024-05-10 11:29 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 10 of 16 files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRqEgcEkAWSHzKMbF1:-NxXFrX69bIOmCn8ClmY:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Run `cargo fmt` at the root of the cargo project to make sure that the files are properly formatted.
</blockquote></details>

Done.

___
___
*[`integration-tests/modules/assetft_extension_test.go` line 897 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM-0po6SRXjg3Q2Z_p:-NxX1ESd5ZzNwiw1jRNQ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L897)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Actually our goal was to test extensions, and we took the code from previous tests so we don't write it from scratch.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxX1bmE-xHuLD9FOVeG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you are not testing that trying to mint non-mintable tokens are correctly rejected by the go code. you only reject it in the smart contract which is not what we intend to test.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 293 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQlQY-CxNQh3sdP3jx:-NxTPZoHDDcc1vuqBrxm:b-rurq59) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L293)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If you want to test the `MsgMultiSend` use multiple recipients. 
I would propose to use both `MsgSend` with single recipient and `MsgMultiSend` with multiple.
</blockquote></details>

To be honest, this test is copied from the whitelist one to make sure the asset extension is compatible with that
___
*[`x/asset/ft/keeper/keeper.go` line 1073 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM3TZo8L6f9zU9uveS:-NxWfdfMAveyV9KGK9-5:b-jqkpq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper.go#L1073)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it should be possible to clawback extension contract balance. let's dicuss in the team.
</blockquote></details>

Done. But in another PR
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 235 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM4Ec_BFmLqNh6B5EC:-NxWi--R8lPcWK3ZjuFQ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L235)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

add a special condition into the smart contract to ignore default whitelisting, so we will know that we are able to overwrite the default behavior via smart contract.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 238 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM4QreD2NNiXSE-vis:-NxX7xtI7-OxT30UxolJ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L238)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

same as whitelisting, remove the conditions that do not interact with the extension. and add a special condition that shows we are able to overwrite the default behavior via smart contract. 
Same goes for minting and burning.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 438 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM5KZ83bDoeRi-kHkY:-NxX7yZ57Kq-kgqYS5uw:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L438)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Should be fixed as commented above.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 597 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM5Nd26pEGtfatRtAH:-NxX7zPR3v7uOyTK8Brm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/keeper_extension_test.go#L597)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Should be fixed as commented above.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 178 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM6eSh0_NJWWyPLkYo:-NxX9T5G4-d_GR9oRu3Z:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L178)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you are clear, and that is the behavior that we want to test, so remove this check.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 199 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM6t4CCAVH0MPL2dAy:-NxX9Z8tEbCI16LEUzIa:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L199)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

maybe remove this check, and let the go code catch and return this error, and also test for it. it will be an interesting test case.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 191 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRDysQ869UaVxkOSKH:-NxX9VxB3Y1gKtE9Ybh8:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L191)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

asset extension must be able to burn both burnables and non-burnables, so the check should be removed.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/error.rs` line 27 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRGQltDhGIpcyoEJDn:-NxXBNyr5769Td6oHWuH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/error.rs#L27)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Will do then I finalize this feature
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 12:44 UTC, miladz68 requested changes
> Reviewed 2 of 5 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @i, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxXWjoP-_Dq4t6fOzYF:b711qe4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you are still returning the error on the contract level and not the go level. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 293 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQlQY-CxNQh3sdP3jx:-NxXULFQ6OVDrJXXek_P:b-a0ltzw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L293)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

To be honest, this test is copied from the whitelist one to make sure the asset extension is compatible with that
</blockquote></details>

but I guess it makes sense to test multiple tokens via multisend, one with extension and one without.
___
*[`integration-tests/modules/assetft_extension_test.go` line 31 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXT06_6xzoJuVrAA0l:-NxXT06_6xzoJuVrAA0m:b-kyqzlx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/integration-tests/modules/assetft_extension_test.go#L31)):*
> ```Go
> 
> const (
> 	MagicAmountDisallowed         = 7
> ```

magic is not a good name maybe `TriggerAmountDisallowed` or `AmountDisallowedTrigger`
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 26 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXUqaC2GhS1rbKmkbV:-NxXUqaC2GhS1rbKmkbW:b-2y8pei) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L26)):*
> ```Go
> 
> const (
> 	MagicAmountDisallowed         = 7
> ```

import these in integration tests if they are accessible, so you are not duplicating them. 
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 223 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXX1Ry9GrwSSE2ihl4:-NxXX1Ry9GrwSSE2ihl5:b-nyli5q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L223)):*
> ```Go
> 	// sending magic amount will be transferred despise whitelisted amount being exceeded
> 	err = bankKeeper.SendCoins(ctx, issuer, recipient, sdk.NewCoins(
> 		sdk.NewCoin(denom, sdkmath.NewInt(MagicAmountIgnoreWhitelisting))),
> ```

what is the value of  `balance`  and `whitelisted` balance here ?
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 324 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXW3a44wGOqIZdpctg:-NxXW3a44wGOqIZdpcth:b-218m2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L324)):*
> ```Go
> 
> 	// send magic amount to transfer despite freezing
> 	err = bankKeeper.SendCoins(ctx, recipient, issuer, sdk.NewCoins(
> ```

what is the value of `(balance - frozen)` here ?
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 438 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXWKvY0dmctHQjk1ol:-NxXWKvY0dmctHQjk1om:b-2uk4a1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L438)):*
> ```Go
> 
> 	// try to burn as non-issuer
> 	err = bankKeeper.SendCoins(ctx, recipient, issuer, sdk.NewCoins(
> ```

also check total supply.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 458 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXWWXd76xlyaFOBkpU:-NxXWWXd76xlyaFOBkpV:b-2uk4a1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L458)):*
> ```Go
> 	// burn tokens and check balance and total supply
> 	err = bankKeeper.SendCoins(ctx, issuer, issuer, sdk.NewCoins(
> 		sdk.NewCoin(burnableDenom, sdkmath.NewInt(MagicAmountBurning))),
> ```

also check total supply.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 214 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXVUaD3QuAyNJW_0Gw:-NxXVUaD3QuAyNJW_0Gx:b-asjjsj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L214)):*
> ```XML
>     });
> 
>     if token.admin != Some(sender.to_string()) {
> ```

remove this check, let the error to be thrown by the go code, so we will know that interface works. 


<!-- Sent from Reviewable.io -->

2024-05-10 14:59 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 31 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXT06_6xzoJuVrAA0l:-NxXgeIk-Bn2DeiE8bxB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/integration-tests/modules/assetft_extension_test.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

magic is not a good name maybe `TriggerAmountDisallowed` or `AmountDisallowedTrigger`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 26 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXUqaC2GhS1rbKmkbV:-NxXiJzh-q0KkkWp6OoY:b-s97txx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

import these in integration tests if they are accessible, so you are not duplicating them.
</blockquote></details>

I don't think I can import them from keeper test. I can have them in a separate file somewhere that both of them can access, but it is not a good idea I think
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 223 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXX1Ry9GrwSSE2ihl4:-NxXv8U10rhR8CzhJuI1:b-bebhis) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L223)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what is the value of  `balance`  and `whitelisted` balance here ?
</blockquote></details>

Done. Added the check for those values
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 324 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXW3a44wGOqIZdpctg:-NxXo3aG6TJVPyFNgYA8:b-bebhis) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L324)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what is the value of `(balance - frozen)` here ?
</blockquote></details>

Done. Added the check for those values
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 438 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXWKvY0dmctHQjk1ol:-NxXx_0y4XwoLd3Kaltl:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L438)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

also check total supply.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 458 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXWWXd76xlyaFOBkpU:-NxXxwjgBsps74ZvFTSY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/keeper_extension_test.go#L458)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

also check total supply.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 15:03 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 13 of 16 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 214 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxXVUaD3QuAyNJW_0Gw:-NxY0g3ZDByT2YfMV38X:b6j0b4q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c1331ab3e9468385c46f3d94ca819e3323b175fa/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L214)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

remove this check, let the error to be thrown by the go code, so we will know that interface works.
</blockquote></details>

It will not throw any error, because the extension will mint the amount and it has privigates to do it. Am I wrong here?


<!-- Sent from Reviewable.io -->

2024-05-10 15:30 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 13 of 16 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1rkd1Uy7Jql2Vfov:-NxY5Vt6EQ55aL9m9bru:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you are still returning the error on the contract level and not the go level.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_extension_test.go` line 1259 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxM1Xjf8qAmFhrorK7F:-NxY69_6D8lbuQVv2TpF:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fc63549dd76169db275760b3cc845aec1e0dff6/integration-tests/modules/assetft_extension_test.go#L1259)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but the code below the comment `mint tokens and check balance and total supply` only tests the native code, which is already tested. I am not saying to remove the entire test, but the parts that don't affect and are not affected by extensions don't need to be tested.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 15:38 UTC, miladz68 reviewed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @i, @masihyeganeh, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-05-10 15:54 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 15 of 16 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 249 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxRGGhCDEhX7_54p-XY:-NxYCiA67A-c4qDF_EXi:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L249)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think you need this check, but the extension smart contract must be an exception just like the admin.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 16:00 UTC, masihyeganeh reviewed
> Reviewed 1 of 3 files at r2, 6 of 12 files at r3, 3 of 6 files at r4, 2 of 5 files at r5, 1 of 4 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-05-10 16:24 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: 15 of 16 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 293 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/818#-NxQlQY-CxNQh3sdP3jx:-NxYJUVUDEwdX-fk9Ifc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5222a448f733cd22a55fe7bfa4f9588a6e6f7eb/integration-tests/modules/assetft_extension_test.go#L293)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but I guess it makes sense to test multiple tokens via multisend, one with extension and one without.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 16:24 UTC, masihyeganeh reviewed
> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @i, @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-05-11 07:55 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @i, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-05-13 05:37 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/818)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2024-05-13 05:39 UTC, merged