Start znet programmatically
CoreumFoundation/coreum pull request #851
Opened 2024-05-22 07:46 UTC by wojtek-coreum

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2024-05-22 11:24 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyV0lSM-F4ART9Y1pxa:-NyV0lSM-F4ART9Y1pxb:bdmhv3i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ebec6c65f8a604f06e420f025198922dbc85f94d/Makefile#L42)):*
> ```Makefile
> 
> .PHONY: integration-tests-modules
> integration-tests-modules:
> ```

Wh still have the `CrustBuilder` in the makefile. Is it a POC ?
___
*[`build/coreum/tests.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyV1AcWEjL3XSh3SKHz:-NyV1AcX7d5pUynde4if:b46nvm4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ebec6c65f8a604f06e420f025198922dbc85f94d/build/coreum/tests.go#L54)):*
> ```Go
> 			BuildCoredDockerImage)
> 
> 		znetConfig := &infra.ConfigFactory{
> ```

IMO we should have keep the `znet restart` command, same as `znet remove && zner start`, which accepts same flags, but, use the `$(CoreumBuilder)` instead of `$(CrustBuilder)`. Otherwice you won't be able to tune the integration tests env, without the update in the go-code. 


<!-- Sent from Reviewable.io -->

2024-05-22 11:41 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`Makefile` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyV0lSM-F4ART9Y1pxa:-NyV5hB4DudLBt3Thd6i:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ebec6c65f8a604f06e420f025198922dbc85f94d/Makefile#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Wh still have the `CrustBuilder` in the makefile. Is it a POC ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 11:42 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/tests.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyV1AcWEjL3XSh3SKHz:-NyV5Il-4KXXnq3O2x6W:b-v3u3z4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ebec6c65f8a604f06e420f025198922dbc85f94d/build/coreum/tests.go#L54)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we should have keep the `znet restart` command, same as `znet remove && zner start`, which accepts same flags, but, use the `$(CoreumBuilder)` instead of `$(CrustBuilder)`. Otherwice you won't be able to tune the integration tests env, without the update in the go-code.
</blockquote></details>

And whatI may add `coreum-builder znet`  command which might work as `crust znet` but it will be a separate PR as it requires adjustements in znet


<!-- Sent from Reviewable.io -->

2024-05-22 14:04 UTC, ysv requested changes
> Reviewed 12 of 17 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`build/go.mod` line 12 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyVaIYy2cZ1IgRymJt6:-NyVaIYy2cZ1IgRymJt7:btmozkg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65b9f78734a489c1818203ea431f27633a705505/build/go.mod#L12)):*
> ```XML
> // CosmosSDK replacements
> replace (
> 	// cosmos keyring
> ```

I guess we can't avoid all these replacements ?

I'm wondering why we didn't need to have them before if we had coreum/v4 import which has all these replace ?
___
*[`build/coreum/tests.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyV1AcWEjL3XSh3SKHz:-NyVbXMJ7PA6FA_7LUH-:b-4owqnt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ebec6c65f8a604f06e420f025198922dbc85f94d/build/coreum/tests.go#L54)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

And whatI may add `coreum-builder znet`  command which might work as `crust znet` but it will be a separate PR as it requires adjustements in znet
</blockquote></details>

`coreum-builder znet` this would probably be nice
___
*[`build/coreum/tests.go` line 30 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyVbQW99K1E2K24ZW5x:-NyVbQW99K1E2K24ZW5y:b-57zxgi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65b9f78734a489c1818203ea431f27633a705505/build/coreum/tests.go#L30)):*
> ```Go
> )
> 
> var znetConfig = &infra.ConfigFactory{
> ```

I would prefer to define func smth like: `DefaultZnetConfig`


<!-- Sent from Reviewable.io -->

2024-05-23 05:01 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2024-05-23 07:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/go.mod` line 12 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyVaIYy2cZ1IgRymJt6:-NyZHO1wDodsLrVMXYFX:b35efja) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65b9f78734a489c1818203ea431f27633a705505/build/go.mod#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I guess we can't avoid all these replacements ?

I'm wondering why we didn't need to have them before if we had coreum/v4 import which has all these replace ?
</blockquote></details>

We can't. I find `replace` to be another evil of go language.
Probably it was not needed because of `replace github.com/CoreumFoundation/coreum/v4 => ../`
___
*[`build/coreum/tests.go` line 30 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-NyVbQW99K1E2K24ZW5x:-NyZHxRs2Cb6wShr9gXC:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65b9f78734a489c1818203ea431f27633a705505/build/coreum/tests.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would prefer to define func smth like: `DefaultZnetConfig`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-23 10:23 UTC, ysv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)



<!-- Sent from Reviewable.io -->

2024-05-28 11:46 UTC, dzmitryhil approved these changes
> Reviewed 12 of 17 files at r1, 1 of 3 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`build/coreum/tests.go` line 79 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-Nyz0DVR5j49VhVC4suG:-Nyz0DVR5j49VhVC4suH:b8qz27q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a15a449842e6db3bbc476853daf640d8e7503ac/build/coreum/tests.go#L79)):*
> ```Go
> 		znetConfig.Profiles = []string{apps.Profile3Cored, apps.ProfileIBC}
> 		znetConfig.TimeoutCommit = time.Second
> 		znetConfig.CoredVersion = "v3.0.3"
> ```

It would be nice to accept as CLI args all the values we update from time to time, for example, the previous cored version, to update it in the makefile, and not search in the go-code. 


<!-- Sent from Reviewable.io -->

2024-05-28 11:57 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @miladz68)

___
*[`build/coreum/tests.go` line 79 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/851#-Nyz0DVR5j49VhVC4suG:-Nyz2uBB7tsAE3ihLjo6:b-n4z2sg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a15a449842e6db3bbc476853daf640d8e7503ac/build/coreum/tests.go#L79)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to accept as CLI args all the values we update from time to time, for example, the previous cored version, to update it in the makefile, and not search in the go-code.
</blockquote></details>

maybe in next version of `build`


<!-- Sent from Reviewable.io -->

2024-05-28 12:00 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/851)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)



<!-- Sent from Reviewable.io -->

2024-05-28 12:00 UTC, merged