Add Price type with POC to prove that store sorts by price.
CoreumFoundation/coreum pull request #897
Opened 2024-06-25 11:11 UTC by dzmitryhil

# Description

Add Price type with POC to prove that store sorts by price.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

2024-06-28 11:45 UTC, miladz68 requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/897)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/897#-O0TQRUa6SAR25OYR_44:-O0TQRUa6SAR25OYR_45:b6xcwat) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1aeca00b3de8ea81142acbed58acdb3952d635b/proto/coreum/dex/v1/order.proto#L17)):*
> ```proto
> // Side is order side.
> enum Side {
>   sell = 0;
> ```

I think that 0 should be unspecified and be always rejected, to avoid the scenario that user forgets to provide a side and the order is defaulted to the sell side.


<!-- Sent from Reviewable.io -->

2024-07-01 10:33 UTC, masihyeganeh approved these changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/897)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2024-07-02 10:00 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/897)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/897#-O0TQRUa6SAR25OYR_44:-O0mshSR5h1b6n7vfyQ9:b-8z14om) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1aeca00b3de8ea81142acbed58acdb3952d635b/proto/coreum/dex/v1/order.proto#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's default codegen behaviour.
</blockquote></details>

I think you misunderstood my comment, let's discuss it in a call.


<!-- Sent from Reviewable.io -->

2024-07-02 12:15 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/897)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/897#-O0TQRUa6SAR25OYR_44:-O0nMeY61MVdZ5ki1Jbh:bb74ce2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1aeca00b3de8ea81142acbed58acdb3952d635b/proto/coreum/dex/v1/order.proto#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think you misunderstood my comment, let's discuss it in a call.
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2024-07-03 06:52 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/897)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/897#-O0TQRUa6SAR25OYR_44:-O0rMDl-6WybzQ3aX0tZ:bd3isee) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1aeca00b3de8ea81142acbed58acdb3952d635b/proto/coreum/dex/v1/order.proto#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

agreed to do add UNSPECIFIED enum as the default.


<!-- Sent from Reviewable.io -->

2024-07-04 06:09 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/897)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/897#-O0TQRUa6SAR25OYR_44:-O0wMBgV4HMF7k_uQ1Zf:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1aeca00b3de8ea81142acbed58acdb3952d635b/proto/coreum/dex/v1/order.proto#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

agreed to do add UNSPECIFIED enum as the default.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 06:12 UTC, closed without merging