Upgrade Cosmos SDK to v0.50.8
CoreumFoundation/coreum pull request #920
Opened 2024-08-06 12:25 UTC by miladz68

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/coreum/920)

2024-08-07 09:05 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: 0 of 244 files reviewed, 25 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2MPF-QHjVP55T01K:-O3g2MPF-QHjVP55T01L:b92kwwd) (no related file):*
IMO we need a task to check node init and start and connecting of next node to running.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2WkR9I9cDs_tQ2WF:-O3g2WkR9I9cDs_tQ2WG:b-3hzexq) (no related file):*
Do we still need to support legacy gov?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2bIT-s7iun1xamLx:-O3g2bIT-s7iun1xamLy:bpg19jx) (no related file):*
Have you checked new ante handlers? And is there any new?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g4R0zAvpB26HCkjpl:-O3g4R0zAvpB26HCkjpm:b-si4utl) (no related file):*
# [v0.50.9](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.50.9) is released 

___
___
*[`go.mod` line 40 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2ABW5jDfoSC6zjrN:-O3g2ABW5jDfoSC6zjrO:bkpznle) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/go.mod#L40)):*
> ```XML
> 	cosmossdk.io/x/upgrade v0.1.3
> 	github.com/CoreumFoundation/coreum-tools v0.4.1-0.20230627094203-821c6a4eebab
> 	github.com/CosmWasm/wasmd v0.52.0
> ```

What is new in wasm v0.52.0 ?
___
*[`app/amino_test.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g1ugh98vjEaUn0InW:-O3g1ugh98vjEaUn0InX:bl6vf57) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/amino_test.go#L21)):*
> ```Go
> 	slashingtypes "github.com/cosmos/cosmos-sdk/x/slashing/types"
> 	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"
> 	packetforwardtypes "github.com/cosmos/ibc-apps/middleware/packet-forward-middleware/v8/packetforward/types"
> ```

What is new in IBC v8?
___
*[`app/app.go` line 397 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fNt1Q0rTGh3Io4w7z:-O3fNt1Q0rTGh3Io4w8-:b-8185se) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/app.go#L397)):*
> ```Go
> 
> 	// register streaming services
> 	if err := bApp.RegisterStreamingServices(appOpts, keys); err != nil {
> ```

Is it required? Seems it was before as well, but we decided not to include. What is the use case for it?
___
*[`app/app.go` line 1314 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fPbSJ0byeEuBy7kqE:-O3fPbSJ0byeEuBy7kqF:b-7yprg3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fb6098b05b7d707ed743523cb9b52a3ad44f84c2/app/app.go#L1314)):*
> ```Go
> 	// list of app.Modules where we have to handle genesis registration and migraitons. we only need to
> 	// keep these deprecated handlers around to give time to users to migrate.
> 	cnftmodule.
> ```

Did we announce such removal before? Because it's a breaking change.
___
*[`app/upgrade/v5/upgrade.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2uknDVlWkv1cyijX:-O3g2uknDVlWkv1cyijY:b32wxw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/upgrade/v5/upgrade.go#L17)):*
> ```Go
> const Name = "v5"
> 
> // New makes an upgrade handler for v4 upgrade.
> ```

v5
___
*[`app/upgrade/v5/upgrade.go` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2yFs8uMKeW774Oms:-O3g2yFs8uMKeW774Omt:b-os7h34) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/upgrade/v5/upgrade.go#L18)):*
> ```Go
> 
> // New makes an upgrade handler for v4 upgrade.
> func New(mm *module.Manager, configurator module.Configurator) upgrade.Upgrade {
> ```

Did you follow the upgrade guide for the cosmos-sdk and IBC v8 upgrade? Could you share them?
___
*[`build/coreum/build.go` line 134 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fQI8_6Ibdq9GmdQ_3:-O3fQI8_6Ibdq9GmdQ_4:b-7flyd9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/build/coreum/build.go#L134)):*
> ```Go
> 			ccRelativePath = "/bin/x86_64-linux-musl-gcc"
> 			wasmHostDirPath = tools.Path("lib/libwasmvm_muslc.x86_64.a", targetPlatform)
> 			wasmCCLibRelativeLibPath = "/x86_64-linux-musl/lib/libwasmvm_muslc.x86_64.a"
> ```

Did you test the release command?
___
*[`build/coreum/build.go` line 198 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fQU3K8gtUoBWBJKnS:-O3fQU3K8gtUoBWBJKnT:bosix68) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/build/coreum/build.go#L198)):*
> ```Go
> 		formatProto,
> 		lintProto,
> 		// breakingProto, // TODO:revert after cosmos sdk v0.50.x upgrade
> ```

Why is it breaking, because of the nft removal only? 
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 80 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fRzcF3UbChgU7P-k7:-O3fRzcF3UbChgU7P-k8:bkgrzbq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/gas_price_test.go#L80)):*
> ```Go
> 				fmt.Sprintf("--%s=%s", flags.FlagBroadcastMode, flags.BroadcastSync),
> 			}, tc.flags...)
> 			bankTx := bankcli.NewTxCmd(addresscodec.NewBech32Codec(app.ChosenNetwork.Provider.GetAddressPrefix()))
> ```

Is it a new stile of writing the CLI? If yes - don't we want to update our code?
___
*[`cmd/cored/cosmoscmd/root.go` line 482 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fo_uXB902_jrcO2D3:-O3fo_uXB902_jrcO2D4:b-95zvzc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/root.go#L482)):*
> ```Go
> 
> func tempDir() string {
> 	dir, err := os.MkdirTemp("", "cored")
> ```

"cored" or ".core" ? For example, gaia uses  ".gaia". 
What is the use case for it? 
Same comment for all same places.
___
*[`integration-tests/ibc/ica_test.go` line 27 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fMbYK45gbT628rF9H:-O3fMbYK45gbT628rF9I:b-5fht1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/integration-tests/ibc/ica_test.go#L27)):*
> ```Go
> // TestICAController tests the ICA controller capabilities.
> func TestICACoreumController(t *testing.T) {
> 	// TODO(fix-tests)
> ```

As I understand the idea of such comments is to merge and fix them in independent tasks, right?
___
*[`integration-tests/modules/consensus_test.go` line 76 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3frQOA08e8TKRc_G4o:-O3frQOA08e8TKRc_G4p:blseti9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/integration-tests/modules/consensus_test.go#L76)):*
> ```Go
> 	newConsensusParams, err := consensusClient.Params(ctx, &consensustypes.QueryParamsRequest{})
> 	requireT.NoError(err)
> 	consensusParams.Params.Abci = &tendermintypes.ABCIParams{}
> ```

Why do you reset the `Abci` here?
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 64 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3ft8vj1bJvNyoytl_N:-O3ft8vj1bJvNyoytl_O:b-1c8ob) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/proto/coreum/asset/ft/v1/tx.proto#L64)):*
> ```proto
> message MsgIssue {
>   option (cosmos.msg.v1.signer) = "issuer";
>   option (amino.name) = "assetft/MsgIssue";
> ```

Don't we need to implement amino manually with that option?
___
*[`x/asset/ft/keeper/before_send_test.go` line 22 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fveWf86x_PCID9ZYf:-O3fveWf86x_PCID9ZYg:bja6p0k) ([raw file](https://github.com/CoreumFoundation/coreum/bl [...]

2024-08-07 15:25 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: 0 of 244 files reviewed, 25 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g4R0zAvpB26HCkjpl:-O3g9Uu7EVy8L_083u4W:b-9z1y01) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

# [v0.50.9](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.50.9) is released
</blockquote></details>

let's do that later, I will create a task.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2bIT-s7iun1xamLx:-O3g9m3AC9YG5jj9GXS3:b92se17) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have you checked new ante handlers? And is there any new?
</blockquote></details>

There is a task to review all new fuctionalities/ante-handlers

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2WkR9I9cDs_tQ2WF:-O3h6axD2MD_fsdoaNv5:b-d3d1na) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we still need to support legacy gov?
</blockquote></details>

yes, we still need some of the old handlers.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2MPF-QHjVP55T01K:-O3h6guCC5jYWv34_ZUO:b-ceq734) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we need a task to check node init and start and connecting of next node to running.
</blockquote></details>

but znet does it, what more do you want to test ? 

___
___
*[`go.mod` line 40 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2ABW5jDfoSC6zjrN:-O3h7NLYBUoGrAHdMTFK:b-75og37) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/go.mod#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is new in wasm v0.52.0 ?
</blockquote></details>

do you want an extensive change log ? in that case it is here. https://github.com/CosmWasm/wasmd/blob/v0.52.0/CHANGELOG.md
there is not much changes though, mostly upgrade to latest comos sdk and IBC. biggest change is replacing stargate queries with grpc queries. 
___
*[`app/amino_test.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g1ugh98vjEaUn0InW:-O3h948X2bOQZSE9hG18:b93fwdt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/amino_test.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is new in IBC v8?
</blockquote></details>

there are some nice features listed here (https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
I created a task to introduce the new features/ important changes to the team.
___
*[`app/app.go` line 397 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fNt1Q0rTGh3Io4w7z:-O3h9VDxB_jcUmKTOdNw:bhclq9q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/app.go#L397)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it required? Seems it was before as well, but we decided not to include. What is the use case for it?
</blockquote></details>

I doubt that it is required. I did not know we decided not to have it before. I will removed
___
*[`app/app.go` line 1314 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fPbSJ0byeEuBy7kqE:-O3hAxiN6_hi5GWDm3Sy:b-v0l96o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fb6098b05b7d707ed743523cb9b52a3ad44f84c2/app/app.go#L1314)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did we announce such removal before? Because it's a breaking change.
</blockquote></details>

Yes, we have marked them as deprecated since v3. 
___
*[`app/upgrade/v5/upgrade.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2uknDVlWkv1cyijX:-O3hJb-oAmD4ekdl3FKe:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/upgrade/v5/upgrade.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

v5
</blockquote></details>

Done.
___
*[`app/upgrade/v5/upgrade.go` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2yFs8uMKeW774Oms:-O3hBBbZ2C1PLDwfLuR-:b-a8fx6c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/upgrade/v5/upgrade.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you follow the upgrade guide for the cosmos-sdk and IBC v8 upgrade? Could you share them?
</blockquote></details>

sure
here https://github.com/cosmos/cosmos-sdk/blob/v0.50.8/UPGRADING.md#v050x
and here https://ibc.cosmos.network/v8/migrations/v7-to-v8/
___
*[`build/coreum/build.go` line 134 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fQI8_6Ibdq9GmdQ_3:-O3hBX6_1pR2TXjJF8YC:bbaggr4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/build/coreum/build.go#L134)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you test the release command?
</blockquote></details>

I did not test it, but created a task to ensure that it works correctly. 
___
*[`build/coreum/build.go` line 198 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fQU3K8gtUoBWBJKnS:-O3hBp431n3ncLa-2Kf_:byl96se) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/build/coreum/build.go#L198)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why is it breaking, because of the nft removal only?
</blockquote></details>

It is giving me this error 
go: module github.com/cosmos/ibc-go/v8: not a known dependency
it is because it is trying to list modules from the master branch and ibc/v8 is not present in the master branch.
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 80 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fRzcF3UbChgU7P-k7:-O3hEqN34DbxnzwrtmXn:bb5xzj4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/gas_price_test.go#L80)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it a new stile of writing the CLI? If yes - don't we want to update our code?
</blockquote></details>

we do want to upgrade all our cli tests and there is a big task for it. I have skipped all our CLI tests for now. 
___
*[`cmd/cored/cosmoscmd/root.go` line 482 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fo_uXB902_jrcO2D3:-O3hF63D6z0Htnm_7uXc:b-82ntg3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/root.go#L482)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

"cored" or ".core" ? For example, gaia uses  ".gaia". 
What is the use case for it? 
Same comment for all same places.
</blockquote></details>

well cosmos sdk is using "simapp", so we could use any word there, we don't care. 
the reason is that autocli, module basics and encoding config all are now genreated from the app it self, and for the app to initialize correctly it requires a file to init wasm directory and a few other things. so a temp directory is created and cleaned up after tests.
___
*[`integration-tests/ibc/ica_test.go` line 27 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fMbYK45gbT628rF9H:-O3hFgPgEFEBRwCbIgJP:bcnboyn)  [...]

2024-08-08 07:16 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: 0 of 244 files reviewed, 25 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`integration-tests/modules/consensus_test.go` line 76 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3frQOA08e8TKRc_G4o:-O3kptSk-gju29i50aNX:b5hmi9e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/integration-tests/modules/consensus_test.go#L76)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the abci param was being returned as nil, I changed my approach now and I set it to the previous value in the proposal. let me know if it is more clear now.
</blockquote></details>

Actually changing this will make the upgrade fail test. the abci param field is not present in v0.47 and returns nil, but after upgrade, it is set to empty value and not nil. 


<!-- Sent from Reviewable.io -->

2024-08-08 09:36 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: 0 of 244 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2MPF-QHjVP55T01K:-O3lJwQ87aCATM_3TOAV:b-c3so7l) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but znet does it, what more do you want to test ?
</blockquote></details>

Does it test it with the default config?

___
___
*[`app/app.go` line 1314 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fPbSJ0byeEuBy7kqE:-O3lKV_K8Qpc1GGgFIxr:bu2f06h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fb6098b05b7d707ed743523cb9b52a3ad44f84c2/app/app.go#L1314)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Yes, we have marked them as deprecated since v3.
</blockquote></details>

Right, but don't we need to share it with the community? At least for some time before the release. 


<!-- Sent from Reviewable.io -->

2024-08-08 09:41 UTC, masihyeganeh requested changes
> Reviewed 240 of 244 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`go.mod` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fA5dd9oWBGKd3Uksq:-O3fA5dd9oWBGKd3Uksr:bcc7w7o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/go.mod#L17)):*
> ```XML
> 	// dgrijalva/jwt-go is deprecated and doesn't receive security updates.
> 	// TODO(v5): remove it: https://github.com/cosmos/cosmos-sdk/issues/13134
> 	github.com/dgrijalva/jwt-go => github.com/golang-jwt/jwt/v4 v4.4.2
> ```

Do we still need all these replaces?
___
*[`app/amino_test.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gV_Ub0jzGBRfBwjah:-O3gV_Ub0jzGBRfBwjai:b-ypd7zi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/amino_test.go#L15)):*
> ```Go
> 	sdktxtypes "github.com/cosmos/cosmos-sdk/types/tx"
> 	"github.com/cosmos/cosmos-sdk/x/auth/migrations/legacytx"
> 	authtypes "github.com/cosmos/cosmos-sdk/x/auth/types"
> ```

Please change all imports to use `cosmossdk.io` instead of `github.com/cosmos/cosmos-sdk`
___
*[`app/app.go` line 365 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gZVYmCnkAZ_gVTuva:-O3gZVYmCnkAZ_gVTuvb:br3c8qb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/app.go#L365)):*
> ```Go
> 	})
> 	appCodec := codec.NewProtoCodec(interfaceRegistry)
> 	legacyAmino := codec.NewLegacyAmino()
> ```

Do we still need Amino in 0.50.x?
___
*[`app/app.go` line 946 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g_xeqDTPhkG0BVV7U:-O3g_xeqDTPhkG0BVV7V:brdzb90) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/app.go#L946)):*
> ```Go
> 		delayModule,
> 		dex.NewAppModule(appCodec, app.DEXKeeper),
> 		// always be last to make sure that it checks for all invariants and not only part of them
> ```

I see you added some modules after crisis. Is it intentional? This comment explicitly prohibits that
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 24 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gf6x55DIzJqDQFazb:-O3gf6x62vgUOpfSciHK:bsgsikr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/gas_price_test.go#L24)):*
> ```Go
> 
> func TestAutoGasPrices(t *testing.T) {
> 	t.SkipNow()
> ```

Please add a FIXME or TODO for each skipped test
___
*[`cmd/cored/cosmoscmd/root.go` line 55 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gg2L04d1jp2ApbvQC:-O3gg2L04d1jp2ApbvQD:b-sx9fil) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/root.go#L55)):*
> ```Go
> func NewRootCmd() *cobra.Command {
> 	// we "pre"-instantiate the application for getting the injected/configured encoding configuration
> 	tempApp := app.New(log.NewNopLogger(), dbm.NewMemDB(), nil, true, simtestutil.NewAppOptionsWithFlagHome(tempDir()))
> ```

Is it the actual way of getting the config? It looks weird
___
*[`cmd/cored/cosmoscmd/root.go` line 243 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3ggoQpA9hUu164lEpn:-O3ggoQpA9hUu164lEpo:b44e2r0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fb6098b05b7d707ed743523cb9b52a3ad44f84c2/cmd/cored/cosmoscmd/root.go#L243)):*
> ```Go
> 
> 	cmd.AddCommand(
> 		authcmd.GetAccountCmd(),
> ```

Is this command deleted?
___
*[`cmd/cored/cosmoscmd/root.go` line 486 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3ggalqEyHjYHkgsu25:-O3ggalqEyHjYHkgsu26:b-cdiw5k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/root.go#L486)):*
> ```Go
> 		panic("failed to create temp dir: " + err.Error())
> 	}
> 	defer os.RemoveAll(dir) //nolint:errcheck // we don't care
> ```

You could explicitly ignore them. It would be uglier, but you won't need to add lint exception
___
*[`x/asset/ft/client/cli/query_test.go` line 19 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3htKPP7m4jBKy6lEnl:-O3htKPP7m4jBKy6lEnm:b8oigyi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/586a8c133b6a143d12eb45445eadce110e0b09cc/x/asset/ft/client/cli/query_test.go#L19)):*
> ```Go
> 
> func TestQueryTokens(t *testing.T) {
> 	t.SkipNow()
> ```

Please add a TODO or FIXME comment
___
*[`x/asset/ft/keeper/grpc_query.go` line 126 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fw4TD9-gPX6TbXRIw:-O3htsvh3ZpJ2qHkfP-G:b-1nsn1c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/x/asset/ft/keeper/grpc_query.go#L126)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we should do that after a discussion, I see that in the SDK some keeper methods still need sdk.Context but most of them use context.Context. there is a task to follow it up.
</blockquote></details>

I think we should change them to context.Context
We need a task for it
___
*[`x/wbank/keeper/keeper_test.go` line 23 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3kiUUbD16rywoaXXmg:-O3kiUUbD16rywoaXXmh:bpvu4ur) ([raw file](https://github.com/CoreumFoundation/coreum/blob/586a8c133b6a143d12eb45445eadce110e0b09cc/x/wbank/keeper/keeper_test.go#L23)):*
> ```Go
> 
> 	testApp := simapp.New()
> 	ctx := testApp.BaseApp.NewContextLegacy(false, tmproto.Header{})
> ```

I saw you used `NewContext(false)` elsewhere when you're not passing any actual header. Should we use that here and other functions in this file too?


<!-- Sent from Reviewable.io -->

2024-08-08 10:04 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g2MPF-QHjVP55T01K:-O3lMTUkEXJ2emQA_9ZD:b2nign6) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it test it with the default config?
</blockquote></details>

yes

___
___
*[`go.mod` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fA5dd9oWBGKd3Uksq:-O3lMVm6EDCmN0LCeBNL:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/go.mod#L17)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Do we still need all these replaces?
</blockquote></details>

yes
___
*[`app/amino_test.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gV_Ub0jzGBRfBwjah:-O3lOExk692Qe2ksc2h-:b-el1r5e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/amino_test.go#L15)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Please change all imports to use `cosmossdk.io` instead of `github.com/cosmos/cosmos-sdk`
</blockquote></details>

Created a follow up task to do it properly and later. 
___
*[`app/app.go` line 365 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gZVYmCnkAZ_gVTuva:-O3lOMP5BAoL1HG28bi6:b4sfc3c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/app.go#L365)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Do we still need Amino in 0.50.x?
</blockquote></details>

yes amino is still needed. but can be replaced with auto generation. 
___
*[`app/app.go` line 946 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3g_xeqDTPhkG0BVV7U:-O3lOno_4-HTDoeXmRDF:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/app/app.go#L946)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I see you added some modules after crisis. Is it intentional? This comment explicitly prohibits that
</blockquote></details>

Done.
___
*[`app/app.go` line 1314 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fPbSJ0byeEuBy7kqE:-O3lOpmq86dZEhASfvyh:b-sjrw8w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fb6098b05b7d707ed743523cb9b52a3ad44f84c2/app/app.go#L1314)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, but don't we need to share it with the community? At least for some time before the release.
</blockquote></details>

make sense, will create a task to announce it.
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 24 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gf6x55DIzJqDQFazb:-O3lPmhH8LKt1BMiwZdh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/gas_price_test.go#L24)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Please add a FIXME or TODO for each skipped test
</blockquote></details>

Done.
___
*[`cmd/cored/cosmoscmd/root.go` line 55 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3gg2L04d1jp2ApbvQC:-O3lPpciDh8iMdSDy30d:bm40l4k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/root.go#L55)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Is it the actual way of getting the config? It looks weird
</blockquote></details>

it is the way done by cosmos-sdk, wasmd, gaia and ibc. it is weird but that is how it is. 
___
*[`cmd/cored/cosmoscmd/root.go` line 243 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3ggoQpA9hUu164lEpn:-O3lQ8Tm42PX-cZJFuEH:bb7sa0c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fb6098b05b7d707ed743523cb9b52a3ad44f84c2/cmd/cored/cosmoscmd/root.go#L243)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Is this command deleted?
</blockquote></details>

yes.
___
*[`cmd/cored/cosmoscmd/root.go` line 486 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3ggalqEyHjYHkgsu25:-O3lQCjG8RPerveue38l:b-2ysqw3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/cmd/cored/cosmoscmd/root.go#L486)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

You could explicitly ignore them. It would be uglier, but you won't need to add lint exception
</blockquote></details>

we have done it with lint before so I prefer to stick with it. we can change it everywhere but that is beyond the scope of this PR. 
___
*[`x/asset/ft/client/cli/query_test.go` line 19 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3htKPP7m4jBKy6lEnl:-O3lQYHJAMRPoXqxKZ8l:b-5qfzmg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/586a8c133b6a143d12eb45445eadce110e0b09cc/x/asset/ft/client/cli/query_test.go#L19)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Please add a TODO or FIXME comment
</blockquote></details>

actually, SkipNow is no longer needed. Removed
___
*[`x/asset/ft/keeper/grpc_query.go` line 126 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3fw4TD9-gPX6TbXRIw:-O3lQfDv411STx7eR8VG:b-sk2spx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8ea6f3324217602b3dc7c6716f44e9add04960e7/x/asset/ft/keeper/grpc_query.go#L126)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I think we should change them to context.Context
We need a task for it
</blockquote></details>

there is a task for it. 
___
*[`x/wbank/keeper/keeper_test.go` line 23 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/920#-O3kiUUbD16rywoaXXmg:-O3lQkQL1buL2_t2e25U:b-hhcr75) ([raw file](https://github.com/CoreumFoundation/coreum/blob/586a8c133b6a143d12eb45445eadce110e0b09cc/x/wbank/keeper/keeper_test.go#L23)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I saw you used `NewContext(false)` elsewhere when you're not passing any actual header. Should we use that here and other functions in this file too?
</blockquote></details>

both solutions are identical. Done. 


<!-- Sent from Reviewable.io -->

2024-08-08 11:56 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: 240 of 244 files reviewed, 10 unresolved discussions (waiting on @masihyeganeh and @ysv)



<!-- Sent from Reviewable.io -->

2024-08-08 13:02 UTC, masihyeganeh approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/920)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2024-08-08 13:04 UTC, merged